### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by SeaCheChe** [windingwind/zotero-better-notes#1]
1.不知道up主能否设置一个按钮或者设置能将某篇文章的metadata（如文献题目、杂志、影响因子、作者等）引入到Knowledge中，这样的话，对于笔记的完整性会更好
2.能否将生成的Knowledge中思维导图的每一个条目设置呈可以调整长短或者设置显示字数是自由的，现在的情况，如果某一个层级标题字数多现在显示不好，只能看到几个字

**Comment by windingwind** [comment]
1 具体需要哪些字段呢？在编辑时点击按钮插入还是在导出时自动插入
2 字数后面我设置允许的长度更大些。主要是无限长可能会导致导图很难看

**Comment by SeaCheChe** [comment]
感谢快速的回复，这个插件真的特别好，感觉再继续完善，我真的可以放弃我的obsidian联动了
1. 个人觉得article title、Journal name、IF、authors、published year、tags这几个如果能的话都能加上，如果是编辑的时候能够点击某个按钮一键插入是最好的，如果不需要可以不插入，这样自由度会比自动插入更高
2. 设置长一些会好一些，至少能显示的更清楚，思维导图就是为了显示框架结构，连框架的分支都看不全就看不清结构了，思维导图的意义就失去了，或者更好的是每一个节点的字段宽度可以自由拖拽来调节，这样自由度会更高，但是不知道好不好实现，实在不好实现，就做成字段允许长度大一些吧，辛苦啦
3. 还有一个小建议，就是笔记是否可以设置模板然后有个按钮可以一键插入模板，比如说我在看文献的时候有一个习惯的整理逻辑和框架习惯（比如B站某up主的方式，类似于下图思维导图的结构），然后把每个文献按照这个逻辑整理，或者看了一堆文献时按照某一个逻辑框架去梳理，插件能加入一个按钮允许我插入一个模板，我每次新建笔记的时候可以选择某一个模板。其实我现在使用咱们这个插件的方式就是我建了一个模板在一个单独的notes里，每次我看一个文献记笔记的时候，我就把模板copy-paste过来，再添加，虽然也没有多麻烦，但是感觉没有在插件加入一个模板按键的方式更方便、工作流不够流畅
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/105227871/167526321-40534dc3-d69d-4e11-865e-8057266e502e.png">


再次感叹插件很棒，再次给您点赞

**Comment by windingwind** [comment]
1 3是计划的功能。2会尝试修复。

**Comment by SeaCheChe** [comment]
太棒了，大神up主威武，期待新版本更新

**Comment by windingwind** [comment]
字数限制已经更新为50字

**Comment by SeaCheChe** [comment]
收到，已经下载最新版本试用，思维导图美观了很多，感谢up主更新

**Comment by SeaCheChe** [comment]
我是个github外行，知道B站up主不是您，但是不知道github的开发者应该怎么称呼，所以就称您为up主了，期待1+3号功能的实现哦，嘻嘻

**Comment by SeaCheChe** [comment]
对了，好像还有个问题，就是如果把PDF注释的某一条加入knowledge后，那条注释的便签里就会多一个"link..."的话，那个能否不要啊

**Comment by windingwind** [comment]
> 对了，好像还有个问题，就是如果把PDF注释的某一条加入knowledge后，那条注释的便签里就会多一个"link..."的话，那个能否不要啊

这个link是用于防止多次新建相同的note，在内测阶段有用户提出反复新建note不方便，所以添加了一个链接，如果点击花形图标新建note的时候，存在链接，就会打开已有的note。确实不美观，但是暂时想不到更好的保存连接关系的办法

**Comment by SeaCheChe** [comment]
哦，不过我其实也很少单独把个别批注注释加入knowledge，那如果是先将所有PDF注释生成一个总的笔记，再将这个笔记加入knowledge是不是没有这个链接，我暂时没发现有那个“link”的链接在哪里出现；不过话说回来可能每个人使用习惯不一样，我个人一般都是把所有注释都做完再统一做一个总的note，然后再放入knowledge中

**Comment by windingwind** [comment]
是的，因此当用户再次点击从注释创建一个总笔记，并不会打开已有的笔记，而是会新建。这个链接的意义在于存储笔记和注释的关联性

**Comment by SeaCheChe** [comment]
其实我没太明白存储笔记和注释的关联性的意义，可能我一般不太用吧。我的理解：对我来说在每条注释都增加一个Knowledge按钮的意义就是可以自由灵活的挑选注释来提取单个note，这样比系统自带的提取注释只能一次提取全部注释到一个单独note要灵活很多，但是实话讲是否每条小注释提取的note都需要链接能够从knowledge跳转回来我觉得也不一定，如果我除了选择某些注释提取为notes外，也会用系统自带功能来提取总注释生成总note并放入Knowledge的话，这个功能就意义不大，因为我可以从总注释的note来回到原文中查找单独某条注释。所以我的建议是能否增加一个开关，让用户选择是否生成这个链接在单条注释的备注里？当然，这也不是必须功能，就是个人一点想法

**Comment by lil-i321** [comment]
> 1 3是计划的功能。2会尝试修复。

能否加入已阅读、未阅读的功能呢？类似阅读完成清单，阅读任务列表。

**Comment by windingwind** [comment]
> > 1 3是计划的功能。2会尝试修复。
> 
> 能否加入已阅读、未阅读的功能呢？类似阅读完成清单，阅读任务列表。

是指对笔记条目添加已读未读，还是markdown的已读未读语法？
前者参见我的另一个插件zotero tag，后者建议向zotero官方提建议，短期内还是以完善本插件功能为主，暂时不会考虑大改编辑器部分

**Comment by lil-i321** [comment]
> 

感谢回复。
类似一个清单列表，集中显示 已经阅读文献、笔记名、创建时间、标签汇总、星标、关键词等信息。
请问本插件 侧重于 单个文献的知识整理，还是整个文献库的整理？感觉两者区别挺大的。
如果可以整理整个文献库，后期这个清单功能估计也可以实现。
(不要影响您的更新计划，只是个人建议。)

**Comment by lil-i321** [comment]
> > > 1 3是计划的功能。2会尝试修复。
> > 
> > 
> > 能否加入已阅读、未阅读的功能呢？类似阅读完成清单，阅读任务列表。
> 
> 是指对笔记条目添加已读未读，还是markdown的已读未读语法？ 前者参见我的另一个插件zotero tag，后者建议向zotero官方提建议，短期内还是以完善本插件功能为主，暂时不会考虑大改编辑器部分

感谢回复。
类似一个清单列表，集中显示 已经阅读文献、笔记名、创建时间、标签汇总、星标、关键词等信息。
请问本插件 侧重于 单个文献的知识整理，还是整个文献库的整理？感觉两者区别挺大的。
如果可以整理整个文献库，后期这个清单功能估计也可以实现。
(不要影响您的更新计划，只是个人建议。)

**Comment by SeaCheChe** [comment]
> > > > 1 3是计划的功能。2会尝试修复。
> > > 
> > > 
> > > 能否加入已阅读、未阅读的功能呢？类似阅读完成清单，阅读任务列表。
> > 
> > 
> > 是指对笔记条目添加已读未读，还是markdown的已读未读语法？ 前者参见我的另一个插件zotero tag，后者建议向zotero官方提建议，短期内还是以完善本插件功能为主，暂时不会考虑大改编辑器部分
> 
> 感谢回复。 类似一个清单列表，集中显示 已经阅读文献、笔记名、创建时间、标签汇总、星标、关键词等信息。 请问本插件 侧重于 单个文献的知识整理，还是整个文献库的整理？感觉两者区别挺大的。 如果可以整理整个文献库，后期这个清单功能估计也可以实现。 (不要影响您的更新计划，只是个人建议。)

我个人觉得这个插件可以用于整理单个文献，也可以整理某一个分类文件夹，这个要看每个人使用zotero的习惯和方式，插件运用起来也不太一样。插件侧重还是notes的管理+思维导图展示。个人理解，不知道对不对

**Comment by windingwind** [comment]
插件侧重的是笔记的快速撰写，整理与导出，管理文献应当是zotero本身的工作。既不是单个文献的知识整理，也不算是整个文献库的整理。文献是文件/元数据形式存放的，笔记是对文献的一种提炼；这个插件就是服务于提炼的过程的。

**Comment by SeaCheChe** [comment]
> 插件侧重的是笔记的快速撰写，整理与导出，管理文献应当是zotero本身的工作。既不是单个文献的知识整理，也不算是整个文献库的整理。文献是文件/元数据形式存放的，笔记是对文献的一种提炼；这个插件就是服务于提炼的过程的。

哈哈，看来我的理解也不够到位，不过对我来说它确实是对于笔记和知识整理和总结的利器，对于我这种文科生，学习成本又比obsidian低，非常给力，期待功能的完善

**Comment by lil-i321** [comment]
> 

我感觉 笔记的整理、提炼， 会是这个插件的一大亮点！
感谢！
期待功能的完善！

**Comment by lil-i321** [comment]
> 插件侧重的是笔记的快速撰写，整理与导出，管理文献应当是zotero本身的工作。既不是单个文献的知识整理，也不算是整个文献库的整理。文献是文件/元数据形式存放的，笔记是对文献的一种提炼；这个插件就是服务于提炼的过程的。

我感觉 笔记的整理、提炼， 会是这个插件的一大亮点！
感谢！
期待功能的完善！

**Comment by windingwind** [comment]
快速插入当前笔记的父条目引用已支持

**Comment by SeaCheChe** [comment]
> 快速插入当前笔记的父条目引用已支持

收到，马上更新

**Comment by SeaCheChe** [comment]
> 



> 快速插入当前笔记的父条目引用已支持

看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓

**Comment by windingwind** [comment]
> > 快速插入当前笔记的父条目引用已支持
> 
> 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓

在在条目笔记的编辑窗口有一个新按钮

**Comment by SeaCheChe** [comment]
很奇怪

> > > 快速插入当前笔记的父条目引用已支持
> > 
> > 
> > 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓
> 
> 在在条目笔记的编辑窗口有一个新按钮

很奇怪，我现在主笔记的左下角没有能够让我更换主笔记的按钮了，这是为什么？如何更改主笔记呢？
<img width="315" alt="image" src="https://user-images.githubusercontent.com/105227871/168593899-a435de59-09b8-4dfb-b25e-9b6b9b7d1510.png">
而且我刚刚不小心把“工作流”这个主笔记删除了，现在我点击任何一个笔记，在点击左上角小房子图标出来的主笔记成这样了，我也编辑不了这个“空白工作流”笔记，怎么办？
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/105227871/168594756-7ebc172c-c837-4a9b-8f71-375e3afa7dee.png">

**Comment by SeaCheChe** [comment]
> > > 快速插入当前笔记的父条目引用已支持
> > 
> > 
> > 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓
> 
> 在在条目笔记的编辑窗口有一个新按钮

我没有更换主笔记的按钮了，我没办法，只好装回了旧版本~

**Comment by SeaCheChe** [comment]
> > > 快速插入当前笔记的父条目引用已支持
> > 
> > 
> > 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓
> 
> 在在条目笔记的编辑窗口有一个新按钮

至于您说的增加了一个按钮，是在任意一个笔记插入笔记旁边有个”符号对吗？我点了没发现是啥作用😓

**Comment by windingwind** [comment]
> > > > 快速插入当前笔记的父条目引用已支持
> > > 
> > > 
> > > 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓
> > 
> > 
> > 在在条目笔记的编辑窗口有一个新按钮
> 
> 我没有更换主笔记的按钮了，我没办法，只好装回了旧版本~

大多数功能移到上方菜单栏，并添加了快捷键

**Comment by windingwind** [comment]
> > > > 快速插入当前笔记的父条目引用已支持
> > > 
> > > 
> > > 看不出更新在哪里，您可以更新一下说明文件或者工作流文件吗？我没看出来哪里有变化...尴尬😓
> > 
> > 
> > 在在条目笔记的编辑窗口有一个新按钮
> 
> 至于您说的增加了一个按钮，是在任意一个笔记插入笔记旁边有个”符号对吗？我点了没发现是啥作用😓

应该会在当前笔记末尾添加一个引用，可能与快速复制的设置有关，新功能我后面会再做测试

**Comment by SeaCheChe** [comment]
> 

重新装回新版本，测试了，我大概知道工作流了，新版本多了一个插入链接笔记内容的选项，这个很不错，很喜欢👍🏻，至于那个新出现的“按钮，还没整明白，我觉得您每次如果有重大更新，可以考虑更新一下工作流的那个文件，可能会更好一下

**Comment by windingwind** [comment]
> 重新装回新版本，测试了，我大概知道工作流了，新版本多了一个插入链接笔记内容的选项，这个很不错，很喜欢👍🏻，至于那个新出现的“按钮，还没整明白，我觉得您每次如果有重大更新，可以考虑更新一下工作流的那个文件，可能会更好一下

文档更新会晚于功能更新，需要时间来测试或者调整功能。这个功能不起作用的bug我会再检查看

**Comment by SeaCheChe** [comment]
> > 
> 
> 刷新笔记标题的功能非常赞，“ insert note's parent citation，我也没明白， ![图片](https://user-images.githubusercontent.com/57334649/168600486-fae3bd12-812d-4a7a-a67d-af61037278c7.png)

刷新笔记标题的工作我没懂？截图展示一下？

**Comment by SeaCheChe** [comment]
> > 重新装回新版本，测试了，我大概知道工作流了，新版本多了一个插入链接笔记内容的选项，这个很不错，很喜欢👍🏻，至于那个新出现的“按钮，还没整明白，我觉得您每次如果有重大更新，可以考虑更新一下工作流的那个文件，可能会更好一下
> 
> 文档更新会晚于功能更新，需要时间来测试或者调整功能。这个功能不起作用的bug我会再检查看

嗯嗯，好的，等稳定并更新完我再去仔细看说明，现在摸索的有点费劲

**Comment by lil-i321** [comment]
> > > 
> > 
> > 
> > 刷新笔记标题的功能非常赞，“ insert note's parent citation，我也没明白， ![图片](https://user-images.githubusercontent.com/57334649/168600486-fae3bd12-812d-4a7a-a67d-af61037278c7.png)
> 
> 刷新笔记标题的功能我没懂？截图展示一下？

![图片](https://user-images.githubusercontent.com/57334649/168601974-9f760f90-8f43-4d26-a7f6-82f33212336b.png)
在文献条目下修改标题，在此处点刷新，此处会更新。

**Comment by windingwind** [comment]
@lil-i321 @SeaCheChe 
关于新加功能快速插入引文无效的问题：在首选项设置里面，需要将导出的格式设置为citation style，而非export format
![XTY1ANTW{_J_JI3J~(IS1N3](https://user-images.githubusercontent.com/33902321/168618816-23927ba9-1777-4f66-97b3-886cad0c5763.png)

**Comment by lil-i321** [comment]
> @lil-i321 @SeaCheChe 关于新加功能快速插入引文无效的问题：在首选项设置里面，需要将导出的格式设置为citation style，而非export format 

这样是可以的，非常棒的功能！！
但是我之前配置的是export format ，是否影响其他插件呢？`better bibtex `这个插件也是广泛应用的。
![图片](https://user-images.githubusercontent.com/57334649/168620613-75093113-882f-4f84-ba3d-9db820c2b392.png)

**Comment by windingwind** [comment]
@lil-i321 不清楚你是否使用了其他涉及到这一功能的插件，如果影响了其他功能，可以暂时不用。
后续会为这个插件单独增加一个设置。

**Comment by lil-i321** [comment]
> 

这样最好不过了！感谢！

**Comment by SeaCheChe** [comment]
> > > 刷新笔记标题的功能非常赞，“ insert note's parent citation，我也没明白， ![图片](https://user-images.githubusercontent.com/57334649/168600486-fae3bd12-812d-4a7a-a67d-af61037278c7.png)
> > 
> > 
> > 刷新笔记标题的功能我没懂？截图展示一下？
> 
> ![图片](https://user-images.githubusercontent.com/57334649/168601974-9f760f90-8f43-4d26-a7f6-82f33212336b.png) 在文献条目下修改标题，在此处点刷新，此处会更新。

哦哦，明白了，我还在想这个按钮啥用处呢，棒👍🏻，我也同意插入link note之后没必要多"linked notes"，反正看左边的竖线就能知道是引用的

**Comment by windingwind** [comment]
由于这个issue提到的问题均已解决，并且讨论内容较长，我将会关闭这个issue。如果有相关的问题，仍可以在此issue里讨论；对于新问题，建议每一个问题单独提出issue，方便追溯。
issue太长容易漏掉提出的需求或问题。

**Comment by windingwind** [comment]
@lil-i321 @SeaCheChe 模板功能已支持，使用方法见#23

**Comment by iampearl918** [comment]
> 感谢快速的回复，这个插件真的特别好，感觉再继续完善，我真的可以放弃我的obsidian联动了
> 
> 1. 个人觉得article title、Journal name、IF、authors、published year、tags这几个如果能的话都能加上，如果是编辑的时候能够点击某个按钮一键插入是最好的，如果不需要可以不插入，这样自由度会比自动插入更高
> 2. 设置长一些会好一些，至少能显示的更清楚，思维导图就是为了显示框架结构，连框架的分支都看不全就看不清结构了，思维导图的意义就失去了，或者更好的是每一个节点的字段宽度可以自由拖拽来调节，这样自由度会更高，但是不知道好不好实现，实在不好实现，就做成字段允许长度大一些吧，辛苦啦
> 3. 还有一个小建议，就是笔记是否可以设置模板然后有个按钮可以一键插入模板，比如说我在看文献的时候有一个习惯的整理逻辑和框架习惯（比如B站某up主的方式，类似于下图思维导图的结构），然后把每个文献按照这个逻辑整理，或者看了一堆文献时按照某一个逻辑框架去梳理，插件能加入一个按钮允许我插入一个模板，我每次新建笔记的时候可以选择某一个模板。其实我现在使用咱们这个插件的方式就是我建了一个模板在一个单独的notes里，每次我看一个文献记笔记的时候，我就把模板copy-paste过来，再添加，虽然也没有多麻烦，但是感觉没有在插件加入一个模板按键的方式更方便、工作流不够流畅
> 
> <img alt="image" width="1299" src="https://user-images.githubusercontent.com/105227871/167526321-40534dc3-d69d-4e11-865e-8057266e502e.png">
> 
> 再次感叹插件很棒，再次给您点赞


请问这个的笔记模版在哪里下载？看这个思维导图框架也挺好看。


另外说几句自己的心得：这两天我也是在思考Better Note如何用来整理某一类（主题）的文献，毕竟我一开始是抱着这个目的找到的这款笔记软件。学习完之后发现BN更多是单篇文献记笔记，本来以为是要在主笔记中采用双链、引用单篇文献的笔记，不知道如何搭建主笔记的逻辑框架，搜索后来到了该帖。
看了这个帖子的回复后，我知道了可能要另想办法，做文献的整理和分类工作。
