### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by chloe0201** [windingwind/zotero-better-notes#10]
试用了一下，注释选择提取并建成一个新的笔记太有助于写作了，感觉ob已经不大能用到了，大神什么时候可以加入ob的dataview的功能啊，能有个表格整理文献笔记看起来会很清楚

**Comment by windingwind** [comment]
是否可以详细描述一下你所说的功能如何与zotero以及本插件结合（功能入口，功能位置，表现形式，交互方式等）

**Comment by chloe0201** [comment]
功能入口我不大懂，位置我觉得可以放到主笔记左侧大纲区域，能形成一个表格，表格能汇总多篇文献笔记。
![image](https://user-images.githubusercontent.com/105553060/168474772-1bc39fa3-a179-48a4-be31-a5d09b6674dd.png)
像这样的表，表头可以是笔记的一级标题，选择自己某一文件夹下的笔记，可以做这种表，方便多篇笔记一起回顾复习

**Comment by windingwind** [comment]
我大概理解了一下，可以结合zotero高级搜索功能，通过关键词筛选出特定的note，然后生成一个列表形式的新note。这样是否可以？

**Comment by chloe0201** [comment]
嗯嗯，大致就是这个意思

**Comment by windingwind** [comment]
目前支持从现有的多个笔记批量导入主笔记。在工作区窗口的文件->导入，或者快捷键cmd/ctrl+i/。
这样是否能够达到你所说的用途？

**Comment by chloe0201** [comment]
好像不太一样，table的形式比较一目了然提取的重点，比如想看文章重点，亮点，提示等像这样呈现：
![image](https://user-images.githubusercontent.com/105553060/168752494-bbcd705d-0b2a-49ba-a20b-7a593f82d907.png)
还有读单篇文献的时候可能总结的重点都差不多，能不能有个自定义模板的功能，如果要插入主笔记能自动跳出自己的模板，像这样的
![image](https://user-images.githubusercontent.com/105553060/168752840-fc77d10e-7572-4471-b0ea-439f25bf3bbe.png)
