### ISSUE TITLE
[Bug]导出markdown时公式格式出错

### ISSUE THREAD

**Issue by whyihaveyou** [windingwind/zotero-better-notes#100]
**Describe the bug**
如果主笔记里有比较长的latex公式，例如：
- $$  \lim_{x \to \infty} x^2_{22} - \int_{1}^{5}x\mathrm{d}x + \sum_{n=1}^{20} n^{2} = \prod_{j=1}^{3} y_{j}  + \lim_{x \to -2} \frac{x-2}{x} $$
则利用主笔记导出markdown的功能导出的markdown文件中，这段代码被替换成了
- $$  \lim\_{x \to \infty} x^2\_{22} - \int\_{1}^{5}x\mathrm{d}x + \sum\_{n=1}^{20} n^{2} = \prod\_{j=1}^{3} y\_{j}  + \lim\_{x \to -2} \frac{x-2}{x} $$
而前者可以正确显示，后者不行
仔细观察会发现是在部分字符串后面多加入了”\“

而且很神奇的的是：我在github上面提交的问题公式，分明是这样的：（图1）
![@ Y}7{1FGO5JB%CKU1COAR6](https://user-images.githubusercontent.com/84082485/181657900-4d4ce0c8-24b7-4605-afa1-b12a50a1bf17.png)

但GitHub似乎自动修正了语法：（图2）
![2T$QR`J70US V`THX M8$MX](https://user-images.githubusercontent.com/84082485/181658075-3e1a8243-bd0b-463a-bcb9-1133ce408847.png)

**To Reproduce**
1. 打开zotero,在主笔记里完成含有较长latex公式的输入
2. 点击主笔记页面的按钮，导出为markdown
3. 用vscode打开，用pdf插件进行预览，或者把对应的latex公式复制回主笔记。这一步是为了观察导出前后latex公式的变化
4. 如截图所示（见下）

**Expected behavior**
这个插件真的很好用，希望可以修复这个bug，这样我就可以导出为markdown进行下一步操作了（而不是现在这样，因为有bug,只能手动复制粘贴）

**Screenshots**
（图3）
![9WNMJ@$0)(9ZH``}L4H8FYD](https://user-images.githubusercontent.com/84082485/181656370-7a1c9d1b-7157-433e-93ef-8e489002f5ef.png)
这是图一中导出前后的两段代码生成公式的情况

**Desktop (please complete the following information):**
 - OS: windons
 - Version 0.6.8

**Additional context**
感谢作者的插件革掉了obsidian的命（doge）

**Comment by whyihaveyou** [comment]
以及，似乎输入矩阵也有问题，如用一般的markdown写矩阵：$$\begin{matrix}
0&1&1\\
1&1&0\\
1&0&1\\
\end{matrix}$$

不能正确显示

**Comment by windingwind** [comment]
@whyihaveyou 
下划线转义问题已修复，将在下个版本更新；
对于多行公式，请注意笔记的段落换行（回车）与段内换行（shift+回车）。只有后者的多行公式能够正常识别。
![image](https://user-images.githubusercontent.com/33902321/181667983-341b6ac1-f628-4bd2-aa2a-22fd01534e0b.png)
段内换行左侧只有一个`::`段落指示标，能够正常渲染
![image](https://user-images.githubusercontent.com/33902321/181668050-a3491d98-1992-4dd4-b132-45a15cfde509.png)

**Comment by whyihaveyou** [comment]
> @whyihaveyou 下划线转义问题已修复，将在下个版本更新； 对于多行公式，请注意笔记的段落换行（回车）与段内换行（shift+回车）。只有后者的多行公式能够正常识别。 ![image](https://user-images.githubusercontent.com/33902321/181667983-341b6ac1-f628-4bd2-aa2a-22fd01534e0b.png) 段内换行左侧只有一个`::`段落指示标，能够正常渲染 ![image](https://user-images.githubusercontent.com/33902321/181668050-a3491d98-1992-4dd4-b132-45a15cfde509.png)

非常感谢！矩阵的问题解决了！也非常期待你的更新~
