### ISSUE TITLE
[Bug] 当思维导图有太多分支时导出FreeMind会抱错打不开

### ISSUE THREAD

**Issue by SiyuQAQ** [windingwind/zotero-better-notes#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 
- Zotero Version: 6
- Plugin Version: 1.04

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/115268480/28694eb7-3193-4ef0-b3dd-5019e55e5b7c)

### Debug Output

自从 Zotero 开始没有错误被记录。

version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.36, extensions => Zotero Word for Windows Integration (6.0.4.SA.6.0.36, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.36, extension, disabled), Zotero PDF Translate (1.0.25, extension, disabled), Zotero Style (2.6.7, extension, disabled), Google Scholar Citation Count (3.2.2, extension, disabled), Zotero Better Notes (1.0.4, extension, disabled)

**Comment by SiyuQAQ** [comment]
我找到问题所在了，不是因为分支多的原因，当文字里含有下图这样格式的文本会使FreeMind打不开
![image](https://github.com/windingwind/zotero-better-notes/assets/115268480/63167101-ca23-42a9-80ab-b6f5f3c6bfb7)
当把圈替换为空格就能打开了

**Comment by windingwind** [comment]
若可能请提供freemind原文件，若问题在freemind侧则可能无法解决。

**Comment by SiyuQAQ** [comment]
[当思维导图有太多分支时导出FreeMind会抱错打不开.zip](https://github.com/user-attachments/files/15832934/FreeMind.zip)
两张思维导图中仅仅只有这一段话的区别: When comparing all aging clocks, the best performance in predicting calendar age was achieved by compositeAge (R = 0.93, MAE [mean absolute error] = 4.00, Nfeature [number of features] = 88) and facialAge (R = 0.93, MAE = 4.35) (Figures 5C and 5D).
