### ISSUE TITLE
[Feature]  Adding Perplexity

### ISSUE THREAD

**Issue by mgraffiedi** [windingwind/zotero-better-notes#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

Zotero Version: Last

### Describe the feature request

Perplexity is more reliable for literature questions and research in general. I do not know how hard it is to implement. However, the available models should be best fitted for zotero integration that ChatGPT. Would you be able to implement it?
Thanks

Marco

**Comment by windingwind** [comment]
Thanks for the suggestion. This plugin does not provide any feature related to "literature questions," and I have no plan to introduce it.
