### ISSUE TITLE
[Feature] Embed a note in another note: preview or full display

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.90+f829d7c43 (64-bit)
- Plugin Version: 1.1.4-beta.83

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to be able to see the content of the linked notes directly into the note containing the link.

**Why do you need this feature?**
This helps creating structured content.

### Describe the solution you'd like

**The solution you'd like**
I would like to have the option to embed a note in another note:
- Like Obsidian: https://help.obsidian.md/Linking+notes+and+files/Embed+files#Embed+a+note+in+another+note
- And in compact form, like the Preview mode of Evernote:
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/4270e9ec-6203-4246-a98b-b1ce7359bf78)

I should be able to change the display mode from an individual linked note, but also  from the outline,, to be able to expand or collapse them all quickly.
The embedded notes should not be editable from the note containing the link, but only from opening them in the right pane.

**Alternatives you've considered**
I can "import" the linked note, as mentioned here: https://github.com/windingwind/zotero-better-notes/issues/131
But this will duplicate the content of that note, which is not what I want.

There is also the preview pane, but that does not allow me to see all the content at once in the note containing the links.

**Comment by windingwind** [comment]
I haven't figured out how to implement the note embedding, so currently hover to preview is the easiest workaround.

**Comment by ramonmi** [comment]
> I haven't figured out how to implement the note embedding, so currently hover to preview is the easiest workaround.

Could the hover window be designed to be scrollable to preview the whole linked note?
