### ISSUE TITLE
Beta: Open Better Notes User Guide gets stuck at the Open Note stage

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-better-notes#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: Beta 7.0.0 91
- Plugin Version: 1.1.4 beta.84

### Describe the bug

I am only able to get through the first couple of screens of the new Users Guide. Then it describes how to open a note and, rather than having a Next button, it says Open Note. It opens one of my notes--always the same one--probably the first one in my Item List. It opens the note wide on my screen. It doesn't tell me what to do with it, so I close it, but it shows me an error, "Failed to open the note" with an OK button. When I click the OK button, it puts a very small square with a button in it saying "Open Note." When I click on that, it disappears. I don't now how to get to the rest of the User's Guide.

### Debug Output

See above

### Anything else?

None.

**Comment by windingwind** [comment]
Thanks for the report. Do you think the user guide would be helpful to new users of Zotero and/or Better Notes? People are usually confused about how to combine the *features* of the plugin to build their *workflow*. There isn't much documentation/videos available to new users (mainly because I'm too busy). The user guide attempts to get new users to know the features. Any advice/comment is welcome!

**Comment by DonnaCoxBaker** [comment]
I will let you know as soon as I take a look. I also plan to write a guide
on some of the plugins as soon as I can, and this one and the action and
tags one will be the first two I do--the most important of all the plugins,
I think. Do you have any idea when Zotero 7 will be finalized? I've been
waiting for that before my next book comes out.

Thanks for the rapid response on the bugs!

**Comment by DonnaCoxBaker** [comment]
Thanks so much for fixing the guide for me. I have gone through it, and it
does a great job of taking us through the environment. I  think many users
are going to need something deeper to see how it will aid them in their
work. It's a great addition to Zotero--taking it much further than it goes
with the present notes. Many people will need examples of how it works on
research projects. The quick guide I plan to write will probably fill in
the gaps, and I think I'll go ahead and get to work on it, even though
Zotero 7 is not ready. I might have questions for you because the new
interface works differently than I had gotten used to. I will also possibly
create a YouTube video, so maybe that will give you something to point
people to for a quick start.

It's a great plug-in! I'm eager to see people using it widely.


                   Visit me at Genohistory.com <https://genohistory.com>
                   Sign up for my Genohistory Notes newsletter!
<https://landing.mailerlite.com/webforms/landing/f0x2k7>

**Comment by windingwind** [comment]
Thanks for the feedback :) Feel free to ask questions (at https://github.com/windingwind/zotero-better-notes/discussions) and I will try my best to answer. Looking forward to your document and video and thank you for contributing to the community!

**Comment by DonnaCoxBaker** [comment]
My pleasure!

**Comment by DonnaCoxBaker** [comment]
Hey, windingwind. I will be mentioning you in the Quick Guide to Zotero
Plugins. This is an odd question but I know I'll need to use a pronoun to
mention you, and I don't know if you're a he or a she. May I ask?

Thanks!
Donna

                   Visit me at Genohistory.com <https://genohistory.com>
                   Sign up for my Genohistory Notes newsletter!
<https://landing.mailerlite.com/webforms/landing/f0x2k7>

**Comment by windingwind** [comment]
`he` :) It's totally ok to ask!

**Comment by DonnaCoxBaker** [comment]
Thanks!
