### ISSUE TITLE
[Feature] Inserting citation at classic view in main note

### ISSUE THREAD

**Issue by seifer08ms** [windingwind/zotero-better-notes#101]
**Is your feature request related to a problem? Please describe.**
![图片](https://user-images.githubusercontent.com/506463/182007171-267b3ba9-b8c8-44de-b037-72a4ba65399d.png)

I want to add citation to mainnote. However, I can’t select a paper from a folder when editing a main note. I can only input a few keywords to find the ref to insert, which is a bit inconvenient.
![图片](https://user-images.githubusercontent.com/506463/182007000-8e782737-e5cf-4a43-b241-c6c775f96d08.png)

**Describe the solution you'd like**

I want to insert citation into main note by selecting a ref from folder. Is it feasible to insert citation with classic view when editing main note ?

**Describe alternatives you've considered**

When editing a word document to insert a reference, I can insert the citation in classic view mode. 
![图片](https://user-images.githubusercontent.com/506463/182007091-f713d14a-8669-4392-9477-5df4b54f6f61.png)
However, when editing the main note, I cant use the classic view. Maybe we could transport the classic view function to the main note.

**Additional context**

**Comment by windingwind** [comment]
This is a Zotero feature and you may need to report to https://forums.zotero.org/
