### ISSUE TITLE
Link Creator Screen Design Too Tight

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-better-notes#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.92
- Plugin Version: 1.1.4-beta.89

### Describe the bug

I had noticed an item on this problem a few days ago, but it seems to have disappeared. I have two issues with the design of the Link Creator window, and have included a screenprint. First, the window opens too shallow from top to bottom, requiring the user to manually resize it to see a reasonable amount of data. Second, the top-left pane, which contains the library, is too narrow from side to side and can't be resized. If you're looking for a subcollection that is embedded several layers in, you can't see much of the label.

![image](https://github.com/windingwind/zotero-better-notes/assets/54809262/3dae75c4-08b9-4916-a6a3-b5a34468f58b)

### Debug Output

None.

### Anything else?

None.

**Comment by windingwind** [comment]
> the window opens too shallow from top to bottom

It should be able to persist the window size. Do you mean you cannot resize the window or the height is not persisted?

> Should be able to resize the collections list now.

**Comment by DonnaCoxBaker** [comment]
The changes are exactly what I needed. Thanks!
