### ISSUE TITLE
[Bug] Persist note window size

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#1015]
再详细描述一下需求，以供参考：
1）软件本身能实现的：打开notes列表，右键note>edit in a separate window，可以用z7软件的默认方式打开note且保持上次任意调整后的note界面布局及长宽比。
2）BN note的状况：在列表中双击note或使用open as window，可以以单独窗口打开BN note，但是，**此窗口的长宽比每次都会回到初始状态（如上面的截图，长宽分别为约电脑屏幕的1/2和1/3）**，不能维持上次调整后的状态（习惯上以调整到类似pc微信界面的窗口大小为宜，即略小于1/2电脑屏幕）。

_Originally posted by @occasional15 in https://github.com/windingwind/zotero-better-notes/issues/949#issuecomment-2193707387_

**Comment by occasional15** [comment]
完美了！

**Comment by occasional15** [comment]
似乎是个bug：单独BN note窗口右上角没有“最小化”和“最大化”按钮，只有“关闭”。（在列表中双击note或使用open as window打开）。而默认方式打开note则没问题（edit in a separate window）。
![image](https://github.com/windingwind/zotero-better-notes/assets/147971641/5473681b-6bfb-425f-8e8a-19e7f9f1910f)
