### ISSUE TITLE
[Bug] 打开以前的笔记不能查看内容，但是左侧内容能查看，导出笔记内容也是正常的

### ISSUE THREAD

**Issue by BOOLXXY** [windingwind/zotero-better-notes#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [x] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- windows 10 
- Zotero Version: 6.0.36
- Plugin Version:1.0.4

### Describe the bug

打开以前的笔记不能查看内容，但是左侧内容能查看，导出笔记内容也是正常的
![Snipaste_2024-07-03_08-58-18](https://github.com/windingwind/zotero-better-notes/assets/147134510/51e8acc7-5888-4628-afaf-bd185485e16f)
![Snipaste_2024-07-03_08-58-40](https://github.com/windingwind/zotero-better-notes/assets/147134510/01460e5c-a7a6-42ba-8aeb-f37eeafe97aa)

### Debug Output

(3)(+0030507): Starting full-text content processor

(3)(+0002709): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000035): WebSocket error

(1)(+0000000): WebSocket connection closed: 1006

(3)(+0000001): Delaying 30000 ms

(3)(+0010629): Notifier.trigger('select', 'tab', [tab-gY1KCYC4], {"tab-gY1KCYC4":{"type":"betternotes"}}) called [observers: 5]

(3)(+0000132): [Zotero Better Notes] [Warning] Creating element iframe with no namespace specified. Found multiply namespace matches.

(3)(+0000369): itemTree.render(). Displaying Item Tree

(3)(+0000121): [Zotero Better Notes] ok

(3)(+0000002): Reloading tags box

(3)(+0000017): Getting contents of jar:file:///C:/Users/17260/AppData/Roaming/Zotero/Zotero/Profiles/negae7qe.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000001): HTTP GET jar:file:///C:/Users/17260/AppData/Roaming/Zotero/Zotero/Profiles/negae7qe.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000482): Error: Font metrics not found for font: . getCharacterMetrics@resource://zotero/note-editor/editor.js:3253:11 lookupSymbol@resource://zotero/note-editor/editor.js:5297:14 makeSymbol@resource://zotero/note-editor/editor.js:5313:16 makeOrd@resource://zotero/note-editor/editor.js:5416:12 htmlBuilder@resource://zotero/note-editor/editor.js:14392:12 buildGroup@resource://zotero/note-editor/editor.js:6399:21 buildExpression@resource://zotero/note-editor/editor.js:6209:18 buildHTML@resource://zotero/note-editor/editor.js:6453:20 buildTree@resource://zotero/note-editor/editor.js:7082:21 renderToDomTree@resource://zotero/note-editor/editor.js:18177:12 render@resource://zotero/note-editor/editor.js:18116:14 renderMath@resource://zotero/note-editor/editor.js:62276:13 MathView@resource://zotero/note-editor/editor.js:62166:9 createMathView/<@resource://zotero/note-editor/editor.js:62415:24 create@resource://zotero/note-editor/editor.js:55764:30 addNode@resource://zotero/note-editor/editor.js:56377:51 updateChildren/<@resource://zotero/note-editor/editor.js:55867:17 iterDeco@resource://zotero/note-editor/editor.js:56486:13 updateChildren@resource://zotero/note-editor/editor.js:55846:9 NodeViewDesc@resource://zotero/note-editor/editor.js:55751:13 create@resource://zotero/note-editor/editor.js:55795:20 addNode@resource://zotero/note-editor/editor.js:56377:51 updateChildren/<@resource://zotero/note-editor/editor.js:55867:17 iterDeco@resource://zotero/note-editor/editor.js:56486:13 updateChildren@resource://zotero/note-editor/editor.js:55846:9 NodeViewDesc@resource://zotero/note-editor/editor.js:55751:13 docViewDesc@resource://zotero/note-editor/editor.js:55978:12 EditorView@resource://zotero/note-editor/editor.js:59435:24 EditorCore@resource://zotero/note-editor/editor.js:69252:17 _init@resource://zotero/note-editor/editor.js:69741:24 EditorInstance@resource://zotero/note-editor/editor.js:69704:5 @resource://zotero/note-editor/editor.js:70217:23

(3)(+0000002): HTTP GET jar:file:///C:/Users/17260/AppData/Roaming/Zotero/Zotero/Profiles/negae7qe.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000133): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000002): [Zotero Better Notes] pop ol </ol> []

(3)(+0000001): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push pre <pre>数据集大小：小型数据集可能更适合LOO，而大型数据集可能更适合k折或随机交叉验证。 ["pre"]

(3)(+0000001): [Zotero Better Notes] pop pre 模型类型：某些方法可能更适合特定类型的模型，例如时间序列交叉验证适用于时间序列预测模型。</pre> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] pop ol </ol> []

(3)(+0000002): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000000): [Zotero Better Notes] pop ol </ol> []

(3)(+0000001): [Zotero Better Notes] push pre <pre><span style="color: rgb(6, 6, 7)"><span style="background-color: rgb(255, 255, 255)">传统的随机轨迹预测方法通常使用轨迹特征添加潜在变量来表示多模态性； ["pre"]

(3)(+0000000): [Zotero Better Notes] pop pre MID是通过参数化马尔科夫链将所有可行走区域的不确定性逐渐降低到确定性预测，从而生成轨迹。</span></span></pre> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul","ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] push pre <pre class="math">$$q(x_t \mid x_{t-1}) = \mathcal{N}(x_t; \sqrt{\alpha_t} x_{t-1}, (1 - \alpha_t) I) ["ul","pre"]

(3)(+0000001): [Zotero Better Notes] pop pre 其中，x_0 是原始数据，x_T​ 是完全被噪声污染的数据，\alpha_t​ 是噪声衰减系数。$$</pre> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ul","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000000): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] push ul <ul> ["ol","ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> ["ol"]

(3)(+0000000): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000000): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000001): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000000): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0000000): [Zotero Better Notes] push ol <ol> ["ol"]

(3)(+0000000): [Zotero Better Notes] pop ol </ol> []

(3)(+0000000): [Zotero Better Notes] push ul <ul> ["ul"]

(3)(+0000001): [Zotero Better Notes] pop ul </ul> []

(3)(+0016340): Getting contents of C:\Users\17260\AppData\Roaming\Zotero\Zotero\Profiles\negae7qe.default\treePrefs.json

(3)(+0000001): Writing column prefs of length 7359 to file C:\Users\17260\AppData\Roaming\Zotero\Zotero\Profiles\negae7qe.default\treePrefs.json

(3)(+0001751): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000014): WebSocket error

(1)(+0000000): WebSocket connection closed: 1006

(3)(+0000001): Delaying 60000 ms

(3)(+0060023): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000012): WebSocket error

(1)(+0000000): WebSocket connection closed: 1006

(3)(+0000001): Delaying 60000 ms

(3)(+0060019): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000013): WebSocket error

(1)(+0000001): WebSocket connection closed: 1006

(3)(+0000000): Delaying 60000 ms

**Comment by windingwind** [comment]
感谢反馈，但恐怕我无法提供帮助。zotero6的对应版本已经停止维护，且未见其他同类反馈，因此将无法确认/修复，请谅解
