### ISSUE TITLE
How to remove html span in md export [Bug] 

### ISSUE THREAD

**Issue by 777uliahshafar** [windingwind/zotero-better-notes#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 10
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4
 

### Describe the bug

Hello, I use obsidian for managing my note, therefore I'd like to export zotero note in markdown. However, I encountered the issue regarding the html tag included in my note. I drag the highlighted text from pdf to better note to create notes in zotero. The result show like this :
```
## “1.Introduction” (Castaño-Rosa et al., 2022, p. 1)

> # <span class="highlight" data-annotation="%7B%22attachmentU....7D" ztype="zhighlight"><a href="zotero://open-pdf/library/items/X43ISR52?page=1&#x26;annotation=6MA7CIYN">“1.Introduction”</a></span>
>
```
Could anyone tell me how to remove the span tag from html so I can get the pure clean markdown note file. Thank you. 

### Debug Output

[Debug Output.txt](https://github.com/user-attachments/files/16083156/Debug.Output.txt)

**Comment by windingwind** [comment]
Hi, this format is for storing the necessary information during the two-path syncing between Zotero note and markdown. There were some discussions on this topic, but currently, there is no better solution.
