### ISSUE TITLE
[Feature] 表格一次性插入多行/列功能

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version: beta.95
- Plugin Version: 1.1.4-beta.91

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

- 插入表格时可设置行列数量
- 一次性插入多行/多列

**Why do you need this feature?**
A clear and concise description of why you need this feature.

- 方便表格编辑

### Describe the solution you'd like

**The solution you'd like**

- 插入表格时可设置行列数量之前已被提及甚至实现，see https://github.com/windingwind/zotero-better-notes/issues/99 ，但是Zotero7的插件似乎没有这个功能了？
- 除插入表格设置行列外，选中多行，向上或向下插入时默认插入与选中行数相同的空行，类似Excel那种。列同理。当然能实现插入时可设定插入行数/列数更好。
- 现有功能是可选中多行后右击，但仅插入一行；而选中多列右击时会默认取消选中，光标自动移到右击位置所在单元格。

**Alternatives you've considered**

**Comment by chihan-dog** [comment]
多行多列表格的使用需要先配置好“模板”，可以参照此链接进行配置：https://github.com/windingwind/zotero-better-notes/discussions/221
