### ISSUE TITLE
[Bug] New Item Note from Template opens empty command palette

### ISSUE THREAD

**Issue by atyshka** [windingwind/zotero-better-notes#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS 14.5
- Zotero Version: 7.0.0-beta.95+694ccecf4
- Plugin Version: 1.1.4-beta.96

### Describe the bug

When attempting to create an item note from a template in Zotero, the following command palette interface is shown:
<img width="1142" alt="Screenshot 2024-07-08 at 2 13 25 PM" src="https://github.com/windingwind/zotero-better-notes/assets/19317207/8218bdcc-a996-43c9-9f40-913776640b69">

There don't seem to be any valid commands in this command search interface. Is this a bug or something I'm not understanding?

### Debug Output

1720462702282	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

1720462702534	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1720462702979	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Upload request 1/3GAZDNUD failed"]

[JavaScript Error: "You have reached your Zotero File Storage quota. Some files were not uploaded. Other Zotero data will continue to sync to the server.

See your zotero.org account settings for additional storage options.

Thomaz_Breazeal_2008_Teachable robots.pdf (824 KB)"]

[JavaScript Error: "Upload request 1/2XAH5IM4 failed"]

[JavaScript Error: "You have reached your Zotero File Storage quota. Some files were not uploaded. Other Zotero data will continue to sync to the server.

See your zotero.org account settings for additional storage options.

Reyes et al_2011_Featureweighting in dynamic timewarping for gesture recognition in depth data.pdf (2226 KB)"]

appName => Zotero, version => 7.0.0-beta.96+4f780424e, os => macOS 14.5, locale => en-US, extensions => Better Notes for Zotero (1.1.4-beta.96, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Better BibTex for Zotero (6.7.211, extension, disabled)

(3)(+0008261): Writing reader state to /Users/atyshka/Zotero/storage/IYP53QIS/.zotero-reader-state

(3)(+0001676): Scheduling next feed update

(4)(+0000001): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000002): Next feed check in 2412 seconds

(4)(+0000001): SELECT libraryID AS id FROM feeds WHERE refreshInterval IS NOT NULL AND ( lastCheck IS NULL OR (julianday(lastCheck, 'utc') + (refreshInterval/1440.0) - julianday('now', 'utc')) <= 0 )

(3)(+0000004): Running update for feeds:

(3)(+0000000): All feed updates done

(3)(+0000001): Scheduling next feed update

(4)(+0000000): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000002): Next feed check in 2412 seconds

(4)(+0000455): SELECT COUNT(*) FROM settings WHERE setting='mImport' AND key='cleanup'

(3)(+0005491): itemTree.render(). Displaying Item Tree

(3)(+0000005): Viewing item

(4)(+0000005): Registering notifier observer 'Zd' for [item]

(4)(+0000003): Registering notifier observer 'e4' for [item]

(4)(+0000002): Registering notifier observer 'NH' for [item]

(3)(+0000002): Refreshing item box

(3)(+0000022): Switching lastCreatorFieldMode to 0

(3)(+0000001): Switching lastCreatorFieldMode to 0

(3)(+0000005): Setting mode to 'edit'

(3)(+0000001): Reloading tags box

(3)(+0000267): itemTree.render(). Displaying Item Tree

(3)(+0009330): {}

(3)(+0004861): Starting full-text content processor

(4)(+0000002): Registering notifier observer 'fulltext_3d' for [sync]

**Comment by windingwind** [comment]
Hi, have you added any note templates?

**Comment by atyshka** [comment]
I have not added any, but I see the default templates when I open Settings here. Shouldn't these appear as options, or am I misunderstanding?
<img width="883" alt="Screenshot 2024-07-09 at 10 16 45 AM" src="https://github.com/windingwind/zotero-better-notes/assets/19317207/b0628ae2-2759-4ccb-8cc7-e55e3e185e5a">

**Comment by windingwind** [comment]
These are the [builtin templates](https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#builtin-templates), only templates that start with `[item]` or `[text]` can be recognized and used directly.

**Comment by atyshka** [comment]
Apologies for the misunderstanding, thank you!
