### ISSUE TITLE
[Bug] Do not prefix tags after syncing to markdown

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#1024]
It seems there is no way then to auto-update tags in Obsidian? New Zotero tags won't get added to Obsidian unless the tags field is prefixed with $, but adding that prefix means that Obsidian doesn't recognize it as a tags field

_Originally posted by @atyshka in https://github.com/windingwind/zotero-better-notes/issues/527#issuecomment-2218685563_

**Comment by atyshka** [comment]
Wow, thanks for adding this feature so quickly!
