### ISSUE TITLE
[Bug] Does not work with pubpeer_zotero_plugin

### ISSUE THREAD

**Issue by StuckWithTheBug** [windingwind/zotero-better-notes#103]
The AddOn Better Notes is not starting while the AddOn [PubPeer_zotero_plugin](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin) is enabled.

The Context menu with right click on a note or entry shows up, but the workspace is not available. The _Open Workspace_ button is not visible, as the menu above the note editor.

On MacOS and Zotero 6.0.12-beta.2+fc0f6157d, Zotero Better Notes 0.6.14 and Pub Peer PlugIn 0.0.14.

**Comment by windingwind** [comment]
I installed the pubpeer plugin and they seem to work fine. Could you please go to Help->Debug Output->Show Output and paste or upload the output here?

**Comment by StuckWithTheBug** [comment]
`
[JavaScript Error: "TypeError: Zotero.Knowledge4Zotero is undefined" {file: "chrome://zotero/content/standalone/standalone.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1


[JavaScript Error: "TypeError: Zotero.Knowledge4Zotero is undefined" {file: "chrome://zotero/content/standalone/standalone.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1


version => 6.0.12-beta.2+fc0f6157d, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => de, appName => Zotero, appVersion => 6.0.12-beta.2+fc0f6157d, extensions => Better BibTex for Zotero (6.7.17, extension), Pubpeer Plugin for Zotero (0.0.14, extension), Zotero Citation Counts Manager (1.3.0, extension), Zotero LibreOffice Integration (6.0.0.SA.6.0.12-beta.2+fc0f6157d, extension), Zotero Word for Mac Integration (6.0.2.SA.6.0.12-beta.2+fc0f6157d, extension), Zotero PDF Translate (0.8.16, extension), Zotero Better Notes (0.6.14, extension)

(3)(+0000000): Using data directory /Users/nils/Zotero

(3)(+0000005): IPC: Initializing pipe at /Users/nils/Zotero/pipes/1659426166911

(3)(+0000002): Asynchronously opening database 'zotero'

(3)(+0000000): /Users/nils/Zotero/zotero.sqlite

(4)(+0000003): PRAGMA main.locking_mode=EXCLUSIVE

(4)(+0000001): PRAGMA page_size

(4)(+0000000): PRAGMA cache_size=250

(4)(+0000001): PRAGMA foreign_keys=true

(4)(+0000010): SELECT version FROM version WHERE schema='system'

(3)(+0000001): Proxy not required for https://zoteroproxycheck.s3.amazonaws.com/test

(4)(+0000002): SELECT version FROM version WHERE schema='userdata'

(4)(+0000000): SELECT version FROM version WHERE schema='compatibility'

(4)(+0000002): SELECT value FROM settings WHERE setting='db' AND key='integrityCheck'

(3)(+0000000): HTTP GET resource://zotero/schema/global/schema.json

(3)(+0000004): HTTP GET resource://zotero/schema/global/schema.json succeeded with 200

(4)(+0000002): SELECT version FROM version WHERE schema='globalSchema'

(3)(+0000001): Database is up to date with global schema version 19 -- skipping update

(3)(+0000000): HTTP GET resource://zotero/schema/userdata.sql

(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200

(4)(+0000001): PRAGMA foreign_keys = false

(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql

(3)(+0000108): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200

(4)(+0000000): SELECT 1 FROM itemDataValues WHERE value=0 LIMIT 1

(4)(+0000002): Beginning DB transaction xqt6s5TN

(3)(+0000001): HTTP GET resource://zotero/schema/system.sql

(3)(+0000001): HTTP GET resource://zotero/schema/system.sql succeeded with 200

(3)(+0000000): Updating custom tables

(4)(+0000000): PRAGMA foreign_keys

(4)(+0000001): SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND tbl_name=? ['customItemTypes']

(4)(+0000000): DELETE FROM itemTypesCombined

(4)(+0000004): DELETE FROM fieldsCombined

(4)(+0000001): DELETE FROM itemTypeFieldsCombined

(4)(+0000001): DELETE FROM baseFieldMappingsCombined

(4)(+0000000): INSERT INTO itemTypesCombined SELECT itemTypeID, typeName, display, 0 AS custom FROM itemTypes UNION SELECT customItemTypeID + 10000 AS itemTypeID, typeName, display, 1 AS custom FROM customItemTypes

(4)(+0000001): INSERT INTO fieldsCombined SELECT fieldID, fieldName, NULL AS label, fieldFormatID, 0 AS custom FROM fields UNION SELECT customFieldID + 10000 AS fieldID, fieldName, label, NULL, 1 AS custom FROM customFields

(4)(+0000001): INSERT INTO itemTypeFieldsCombined SELECT itemTypeID, fieldID, hide, orderIndex FROM itemTypeFields UNION SELECT customItemTypeID + 10000 AS itemTypeID, COALESCE(fieldID, customFieldID + 10000) AS fieldID, hide, orderIndex FROM customItemTypeFields

(4)(+0000001): INSERT INTO baseFieldMappingsCombined SELECT itemTypeID, baseFieldID, fieldID FROM baseFieldMappings UNION SELECT customItemTypeID + 10000 AS itemTypeID, baseFieldID, customFieldID + 10000 AS fieldID FROM customBaseFieldMappings

(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql

(3)(+0000001): HTTP GET resource://zotero/schema/userdata.sql succeeded with 200

(4)(+0000000): SELECT version FROM version WHERE schema='triggers'

(3)(+0000000): HTTP GET resource://zotero/schema/triggers.sql

(3)(+0000002): HTTP GET resource://zotero/schema/triggers.sql succeeded with 200

(3)(+0000002): Updating custom tables

(4)(+0000000): PRAGMA foreign_keys

(4)(+0000000): DELETE FROM itemTypesCombined

(4)(+0000000): DELETE FROM fieldsCombined

(4)(+0000001): DELETE FROM itemTypeFieldsCombined

(4)(+0000000): DELETE FROM baseFieldMappingsCombined

(4)(+0000000): INSERT INTO itemTypesCombined SELECT itemTypeID, typeName, display, 0 AS custom FROM itemTypes UNION SELECT customItemTypeID + 10000 AS itemTypeID, typeName, display, 1 AS custom FROM customItemTypes

(4)(+0000001): INSERT INTO fieldsCombined SELECT fieldID, fieldName, NULL AS label, fieldFormatID, 0 AS custom FROM fields UNION SELECT customFieldID + 10000 AS fieldID, fieldName, label, NULL, 1 AS custom FROM customFields

(4)(+0000000): INSERT INTO itemTypeFieldsCombined SELECT itemTypeID, fieldID, hide, orderIndex FROM itemTypeFields UNION SELECT customItemTypeID + 10000 AS itemTypeID, COALESCE(fieldID, customFieldID + 10000) AS fieldID, hide, orderIndex FROM customItemTypeFields

(4)(+0000001): INSERT INTO baseFieldMappingsCombined SELECT itemTypeID, baseFieldID, fieldID FROM baseFieldMappings UNION SELECT customItemTypeID + 10000 AS itemTypeID, baseFieldID, customFieldID + 10000 AS fieldID FROM customBaseFieldMappings

(4)(+0000002): Committed DB transaction xqt6s5TN

(4)(+0000001): PRAGMA foreign_keys = true

(4)(+0000001): Beginning DB transaction 8qlvUaxF

(4)(+0000001): SELECT value FROM settings WHERE setting='client' AND key='lastVersion'

(4)(+0000001): Committed DB transaction 8qlvUaxF

(4)(+0000001): SELECT key, value FROM settings WHERE setting='account'

(4)(+0000000): SELECT userID, name FROM users

(4)(+0000002): SELECT L.libraryID, L.type AS _libraryType, L.editable AS _libraryEditable, L.filesEditable AS _libraryFilesEditable, L.version AS _libraryVersion, L.storageVersion AS _libraryStorageVersion, L.lastSync AS _libraryLastSync, L.archived AS _libraryArchived, (SELECT COUNT(*)>0 FROM collections C WHERE C.libraryID=L.libraryID) AS hasCollections, (SELECT COUNT(*)>0 FROM savedSearches S WHERE S.libraryID=L.libraryID) AS hasSearches FROM libraries L WHERE type NOT IN (?,?) ['feed', 'group']

(4)(+0000001): SELECT L.libraryID, L.type AS _libraryType, L.editable AS _libraryEditable, L.filesEditable AS _libraryFilesEditable, L.version AS _libraryVersion, L.storageVersion AS _libraryStorageVersion, L.lastSync AS _libraryLastSync, L.archived AS _libraryArchived, (SELECT COUNT(*)>0 FROM collections C WHERE C.libraryID=L.libraryID) AS hasCollections, (SELECT COUNT(*)>0 FROM savedSearches S WHERE S.libraryID=L.libraryID) AS hasSearches, F.name AS _feedName, F.url AS _feedUrl, F.lastUpdate AS _feedLastUpdate, F.lastCheck AS _feedLastCheck, F.lastCheckError AS _feedLastCheckError, F.cleanupUnreadAfter AS _feedCleanupUnreadAfter, F.cleanupReadAfter AS _feedCleanupReadAfter, F.refreshInterval AS _feedRefreshInterval, (SELECT COUNT(*) FROM items I JOIN feedItems FI USING (itemID) WHERE I.libraryID=F.libraryID AND FI.readTime IS NULL) AS _feedUnreadCount FROM feeds F JOIN libraries L USING (libraryID)

(4)(+0000000): SELECT L.libraryID, L.type AS _libraryType, L.editable AS _libraryEditable, L.filesEditable AS _libraryFilesEditable, L.version AS _libraryVersion, L.storageVersion AS _libraryStorageVersion, L.lastSync AS _libraryLastSync, L.archived AS _libraryArchived, (SELECT COUNT(*)>0 FROM collections C WHERE C.libraryID=L.libraryID) AS hasCollections, (SELECT COUNT(*)>0 FROM savedSearches S WHERE S.libraryID=L.libraryID) AS hasSearches, G.groupID, G.name AS _groupName, G.description AS _groupDescription, G.version AS _groupVersion FROM groups G JOIN libraries L USING (libraryID)

(4)(+0000001): SELECT COALESCE(MAX(collectionID) + 1, 1) FROM collections

(4)(+0000001): SELECT COALESCE(MAX(creatorID) + 1, 1) FROM creators

(4)(+0000000): SELECT COALESCE(MAX(creatorTypeID) + 1, 1) FROM creatorTypes

(4)(+0000000): SELECT COALESCE(MAX(customFieldID) + 1, 1) FROM customFields

(4)(+0000001): SELECT COALESCE(MAX(customItemTypeID) + 1, 1) FROM customItemTypes

(4)(+0000000): SELECT COALESCE(MAX(fieldID) + 1, 1) FROM fields

(4)(+0000001): SELECT COALESCE(MAX(valueID) + 1, 1) FROM itemDataValues

(4)(+0000000): SELECT COALESCE(MAX(itemTypeID) + 1, 1) FROM itemTypes

(4)(+0000000): SELECT COALESCE(MAX(itemID) + 1, 1) FROM items

(4)(+0000000): SELECT COALESCE(MAX(libraryID) + 1, 1) FROM libraries

(4)(+0000001): SELECT COALESCE(MAX(proxyID) + 1, 1) FROM proxies

(4)(+0000000): SELECT COALESCE(MAX(savedSearchID) + 1, 1) FROM savedSearches

(4)(+0000000): SELECT COALESCE(MAX(tagID) + 1, 1) FROM tags

(4)(+0000001): SELECT itemTypeID AS id, typeName AS name, custom FROM itemTypesCombined

(4)(+0000002): SELECT itemTypeID AS id, typeName AS name, custom FROM itemTypesCombined WHERE typeName IN ('webpage', 'attachment', 'note', 'annotation')

(4)(+0000000): SELECT customItemTypeID AS id, label, icon FROM customItemTypes

(4)(+0000001): SELECT * FROM fieldFormats

(4)(+0000000): SELECT * FROM fieldsCombined

(4)(+0000001): SELECT fieldID, itemTypeID FROM itemTypeFieldsCombined

(4)(+0000007): SELECT DISTINCT baseFieldID FROM baseFieldMappingsCombined

(4)(+0000004): SELECT IT.itemTypeID, F.fieldID AS baseFieldID, BFM.fieldID FROM itemTypesCombined IT LEFT JOIN fieldsCombined F LEFT JOIN baseFieldMappingsCombined BFM ON (IT.itemTypeID=BFM.itemTypeID AND F.fieldID=BFM.baseFieldID)

(4)(+0000016): SELECT DISTINCT baseFieldID FROM baseFieldMappingsCombined

(4)(+0000041): SELECT itemTypeID, baseFieldID, fieldID, fieldName FROM baseFieldMappingsCombined JOIN fieldsCombined USING (fieldID)

(3)(+0000002): PluginInstaller: fetching addon info

(3)(+0000001): PluginInstaller: addon info fetched

(3)(+0000001): PluginInstaller: fetching addon info

(3)(+0000001): PluginInstaller: addon info fetched

(4)(+0000001): SELECT DISTINCT fieldID FROM baseFieldMappingsCombined

(4)(+0000003): SELECT itemTypeID, fieldID FROM itemTypeFieldsCombined ORDER BY orderIndex

(4)(+0000006): SELECT creatorTypeID AS id, creatorType AS name FROM creatorTypes

(4)(+0000001): SELECT itemTypeID, creatorTypeID AS id, creatorType AS name, primaryField FROM itemTypeCreatorTypes NATURAL JOIN creatorTypes

(4)(+0000010): SELECT itemTypeID, creatorTypeID FROM itemTypeCreatorTypes WHERE primaryField=1

(4)(+0000001): SELECT fileTypeID AS id, fileType AS name FROM fileTypes

(4)(+0000001): SELECT charsetID AS id, charset AS name FROM charsets

(4)(+0000001): SELECT predicateID AS id, predicate AS name FROM relationPredicates

(3)(+0000001): Getting contents of /Users/nils/Library/Application Support/Zotero/Profiles/ccfya7pp.default/session.json

(3)(+0000001): Running unlock callbacks

(3)(+0000000): HTTP server listening on 127.0.0.1:23119

(4)(+0000000): ATTACH ':memory:' AS 'indexing'

(4)(+0000001): CREATE TABLE indexing.fulltextWords (word NOT NULL)

(4)(+0000002): SELECT version FROM version WHERE schema='lastsync'

(4)(+0000001): SELECT version FROM version WHERE schema='lastlocalsync'

(4)(+0000001): SELECT name, syncObjectTypeID AS id FROM syncObjectTypes

(3)(+0000003): Registering auto-sync idle observer

(3)(+0000000): Registering URIContentListener

(4)(+0000001): SELECT * FROM proxies

(4)(+0000004): SELECT ROWID AS id, libraryID, key FROM collections

(4)(+0000001): SELECT ROWID AS id, libraryID, key FROM items

(3)(+0000001): Getting contents of /Users/nils/Zotero/locate/engines.json

(4)(+0000005): SELECT ROWID AS id, libraryID, key FROM savedSearches

(4)(+0000001): SELECT fieldName FROM fieldsCombined WHERE fieldName NOT IN ('accessDate', 'date', 'pages', 'section','seriesNumber','issue')

(1)(+0000002): Unknown item type 'nsfReviewer'

(1)(+0000000): Unknown item type 'nsfReviewer'

(1)(+0000000): Localized string not available for searchConditions.dateAdded

(1)(+0000000): Localized string not available for searchConditions.title

(1)(+0000001): Localized string not available for searchConditions.abstractNote

(1)(+0000000): Localized string not available for searchConditions.artworkSize

(1)(+0000000): Localized string not available for searchConditions.language

(1)(+0000000): Localized string not available for searchConditions.shortTitle

(1)(+0000000): Localized string not available for searchConditions.archive

(1)(+0000000): Localized string not available for searchConditions.archiveLocation

(1)(+0000000): Localized string not available for searchConditions.libraryCatalog

(1)(+0000000): Localized string not available for searchConditions.callNumber

(1)(+0000000): Localized string not available for searchConditions.url

(1)(+0000000): Localized string not available for searchConditions.rights

(1)(+0000000): Localized string not available for searchConditions.extra

(1)(+0000000): Localized string not available for searchConditions.seriesTitle

(1)(+0000000): Localized string not available for searchConditions.volume

(1)(+0000000): Localized string not available for searchConditions.numberOfVolumes

(1)(+0000000): Localized string not available for searchConditions.place

(1)(+0000000): Localized string not available for searchConditions.publisher

(1)(+0000000): Localized string not available for searchConditions.runningTime

(1)(+0000000): Localized string not available for searchConditions.ISBN

(1)(+0000000): Localized string not available for searchConditions.number

(1)(+0000000): Localized string not available for searchConditions.code

(1)(+0000001): Localized string not available for searchConditions.legislativeBody

(1)(+0000000): Localized string not available for searchConditions.session

(1)(+0000000): Localized string not available for searchConditions.history

(1)(+0000000): Localized string not available for searchConditions.publicationTitle

(1)(+0000000): Localized string not available for searchConditions.series

(1)(+0000000): Localized string not available for searchConditions.edition

(1)(+0000000): Localized string not available for searchConditions.numPages

(1)(+0000000): Localized string not available for searchConditions.court

(1)(+0000000): Localized string not available for searchConditions.reporter

(1)(+0000000): Localized string not available for searchConditions.versionNumber

(1)(+0000000): Localized string not available for searchConditions.system

(1)(+0000000): Localized string not available for searchConditions.conferenceName

(1)(+0000000): Localized string not available for searchConditions.DOI

(1)(+0000000): Localized string not available for searchConditions.committee

(1)(+0000000): Localized string not available for searchConditions.seriesText

(1)(+0000000): Localized string not available for searchConditions.journalAbbreviation

(1)(+0000000): Localized string not available for searchConditions.ISSN

(1)(+0000000): Localized string not available for searchConditions.scale

(1)(+0000000): Localized string not available for searchConditions.country

(1)(+0000000): Localized string not available for searchConditions.assignee

(1)(+0000000): Localized string not available for searchConditions.issuingAuthority

(1)(+0000000): Localized string not available for searchConditions.filingDate

(1)(+0000000): Localized string not available for searchConditions.applicationNumber

(1)(+0000000): Localized string not available for searchConditions.priorityNumbers

(1)(+0000000): Localized string not available for searchConditions.references

(1)(+0000000): Localized string not available for searchConditions.legalStatus

(1)(+0000000): Localized string not available for searchConditions.meetingName

(1)(+0000000): Localized string not available for searchConditions.codeNumber

(1)(+0000000): Localized string not available for searchConditions.citationKey

(1)(+0000000): Localized string not available for searchConditions.accessDate

(1)(+0000000): Localized string not available for searchConditions.date

(1)(+0000000): Localized string not available for searchConditions.pages

(1)(+0000000): Localized string not available for searchConditions.section

(1)(+0000000): Localized string not available for searchConditions.seriesNumber

(1)(+0000000): Localized string not available for searchConditions.issue

(4)(+0000003): SELECT tagID, name FROM tags

(4)(+0000002): SELECT * FROM creators

(3)(+0000005): Loading collection relations

(4)(+0000000): SELECT * FROM collectionRelations JOIN relationPredicates USING (predicateID)

(3)(+0000000): Loaded collection relations in 0 ms

(3)(+0000000): Loading item relations

(4)(+0000000): SELECT * FROM itemRelations JOIN relationPredicates USING (predicateID)

(3)(+0000001): Loaded item relations in 1 ms

(4)(+0000000): SELECT itemID AS id, fieldID, value FROM itemData JOIN itemDataValues USING (valueID) WHERE fieldID IN (?, ?) [58, 16]

(3)(+0000012): Getting contents of /Users/nils/Library/Application Support/Zotero/Profiles/ccfya7pp.default/retractions.json

(4)(+0000028): SELECT libraryID, itemID, DI.itemID IS NOT NULL AS deleted, RI.flag FROM items JOIN retractedItems RI USING (itemID) LEFT JOIN deletedItems DI USING (itemID)

(4)(+0000001): SELECT COUNT(*) FROM settings WHERE setting='globalSchema' AND key='migrateExtra'

(3)(+0000002): Loading synced settings for library 1

(4)(+0000000): SELECT setting, value, synced, version FROM syncedSettings WHERE libraryID=? [1]

(3)(+0000001): Loading all collections in Meine Bibliothek

(3)(+0000000): Loading primaryData for collections in Meine Bibliothek

(4)(+0000001): SELECT O.collectionID, O.collectionName AS name, O.libraryID, O.key, O.version, O.synced, DC.collectionID IS NOT NULL AS deleted, O.parentCollectionID AS parentID, CP.key AS parentKey, (SELECT COUNT(*) FROM collections WHERE parentCollectionID=O.collectionID) != 0 AS hasChildCollections, (SELECT COUNT(*) FROM collectionItems WHERE collectionID=O.collectionID) != 0 AS hasChildItems FROM collections O LEFT JOIN deletedCollections DC ON (O.collectionID=DC.collectionID)LEFT JOIN collections CP ON (O.parentCollectionID=CP.collectionID) WHERE 1 AND O.libraryID=? [1]

(3)(+0000003): Loaded primaryData in Meine Bibliothek in 4 ms

(3)(+0000000): Loading childCollections for collections in Meine Bibliothek

(4)(+0000000): SELECT C1.collectionID, C2.collectionID AS childCollectionID FROM collections C1 LEFT JOIN collections C2 ON (C1.collectionID=C2.parentCollectionID) WHERE C1.libraryID=? [1]

(3)(+0000001): Loaded childCollections in Meine Bibliothek in 1 ms

(3)(+0000000): Loading childItems for collections in Meine Bibliothek

(4)(+0000000): SELECT collectionID, itemID FROM collections LEFT JOIN collectionItems USING (collectionID) WHERE libraryID=? [1]

(3)(+0000002): Loaded childItems in Meine Bibliothek in 2 ms

(3)(+0000000): Loading relations for collections in Meine Bibliothek

(4)(+0000000): SELECT collectionID, predicate, object FROM collections LEFT JOIN collectionRelations USING (collectionID) LEFT JOIN relationPredicates USING (predicateID) WHERE libraryID=? [1]

(3)(+0000001): Loaded relations in Meine Bibliothek in 1 ms

(3)(+0000000): Loaded collections in Meine Bibliothek in 8 ms

(3)(+0000000): Loading all searches in Meine Bibliothek

(3)(+0000001): Loading primaryData for searches in Meine Bibliothek

(4)(+0000000): SELECT O.savedSearchID, O.savedSearchName AS name, O.libraryID, O.key, O.version, O.synced, DS.savedSearchID IS NOT NULL AS deleted FROM savedSearches O LEFT JOIN deletedSearches DS ON (O.savedSearchID=DS.savedSearchID) WHERE 1 AND O.libraryID=? [1]

(3)(+0000000): Loaded primaryData in Meine Bibliothek in 0 ms

(3)(+0000000): Loading conditions for searches in Meine Bibliothek

(4)(+0000001): SELECT savedSearchID, searchConditionID, condition, operator, value, required FROM savedSearches LEFT JOIN savedSearchConditions USING (savedSearchID) WHERE libraryID=?ORDER BY savedSearchID, searchConditionID [1]

(3)(+0000000): Loaded conditions in Meine Bibliothek in 1 ms

(3)(+0000000): Loaded searches in Meine Bibliothek in 2 ms

(3)(+0000001): Initializing Quick Copy

(3)(+0000001): Running initialization callbacks

(3)(+0000000): Triggering "zotero-loaded" event

(3)(+0000002): Initializing Zotero pane

(3)(+0000051): Initializing React CollectionTree

(3)(+0000011): Refreshing collections pane

(4)(+0000002): SELECT savedSearchID FROM savedSearches WHERE libraryID=? [1]

(5)(+0000006): Trying to restore persist data for #zotero-items-column-title but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-firstCreator but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-itemType but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-date but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-year but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-publisher but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-publicationTitle but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-journalAbbreviation but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-language but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-accessDate but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-libraryCatalog but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-callNumber but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-rights but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-dateAdded but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-dateModified but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-archive but elem not found

(5)(+0000001): Trying to restore persist data for #zotero-items-column-archiveLocation but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-place but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-volume but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-edition but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-pages but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-issue but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-series but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-seriesTitle but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-court but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-medium but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-genre but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-system but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-extra but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-hasAttachment but elem not found

(5)(+0000000): Trying to restore persist data for #zotero-items-column-numNotes but elem not found

(3)(+0000004): Rendering tag selector

(3)(+0000002): Rendering tag list

(3)(+0000011): LibreOfficePlugin: Communication server listening on 127.0.0.1:23116

(3)(+0000000): LibreOfficePlugin: Registering shutdown listener

(3)(+0000000): ZoteroMacWordIntegration: Initializing integration pipes

(3)(+0000000): IPC: Initializing pipe at /Users/Shared/.zoteroIntegrationPipe_nils

(3)(+0000001): IPC: Initializing pipe at /Users/nils/Library/Containers/com.microsoft.Word/Data/.zoteroIntegrationPipe

(3)(+0000000): React CollectionTree initialized

(3)(+0000000): Initializing React ItemTree main

(3)(+0000005): itemTree.render(). Displaying Item Pane Message

(3)(+0000001): React ItemTree main initialized

(3)(+0000000): User interface ready in 4762 ms

(3)(+0000009): Connecting to streaming server at wss://stream.zotero.org/

(3)(+0000002): itemTree.render(). Displaying Item Pane Message

(3)(+0000015): Notifier.trigger('add', 'tab', [tab-bpYhjzvf], {"tab-bpYhjzvf":{"itemID":297}}) called [observers: 5]

(3)(+0000006): Notifier.trigger('add', 'tab', [tab-ySijmxVC], {"tab-ySijmxVC":{"itemID":308}}) called [observers: 5]

(3)(+0000002): Loading all items in Meine Bibliothek

(3)(+0000001): Loading primaryData for items in Meine Bibliothek
`
hopefully this is enough

**Comment by windingwind** [comment]
I've tested and it works well on my PC.
Could you please tell me why you think this is caused by the confliction with pubpeer? Does it work if the pubpeer is disabled?

My suggestions:
Download this addon from the release page again and reinstall it. Please check the installed .xpi is 3046KB and it's not broken.
If it still doesn't work, does fallback to ealier versions help?

**Comment by StuckWithTheBug** [comment]
If I disable the PubPeer PlugIn it will work as expected.
I will try an older Version, as I already installed the plugin multiple times before I opened the ticket.

**Comment by windingwind** [comment]
From the debug output you pasted above, it seem like the Better Notes is not loaded correctly.

That is extremely wierd as their seem to be no reason that thses two plugins have any confliction, especially I'm running both of them on my Zotero currently.

To not miss any potential causes, could you please provides more details about the pubpeer? Like, are there any configs that might change the Zotero startup behaviors? I'm not familiar with pubpeer.

**Comment by StuckWithTheBug** [comment]
Ok, I downgraded from the Zotera beta to the release 6.0.11, the actual version.
Then I tried it again, doesn't work, disabled the PubPeer-Plugin, worked.
Enabled the PP-Plugin, doesn't worked. Removed the PP-Plugin and installed it again, works fine^^

**Comment by windingwind** [comment]
Thanks for the patient reply. I'll try to check what's happening. As you said, I already have the Better Notes installed when I install the PP.
