### ISSUE TITLE
增加一个总览所有笔记的视图

### ISSUE THREAD

**Issue by Cheng7966** [windingwind/zotero-better-notes#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 
- Zotero Version:  7
- Plugin Version: 1.1

### Describe the feature request

在做文献综述和主题探索的时候特别需要汇总文献的笔记

### Describe the solution you'd like

1. 以表格的形式汇总所有文献，字段尽量全面，包括元数据，插件添加的字段，annotation，notes等
2. 可以按照元数据，文件夹，tag形式筛选，
3. 可以直接修改tag，文件夹，note等信息；
4. 可以导出到独立笔记，markdown文件，office等格式

### Anything else?

看到了这个插件：https://github.com/frianasoa/Ze-Notes，类似，希望能借鉴一下

**Comment by llity** [comment]
有这个功能就太方便了，特别能针对每个collection显示所有的笔记，可以搜索、复杂粘贴、点击编辑等。
类似
![image](https://github.com/user-attachments/assets/9f044d78-8922-4885-831c-4b172c9bd5d2)

**Comment by windingwind** [comment]
zotero未来将支持在文库中显示annotation，因此不会考虑。谢谢建议

**Comment by llity** [comment]
> zotero未来将支持在文库中显示annotation，因此不会考虑。谢谢建议

是显示notes哦，不是标注。

**Comment by windingwind** [comment]
zotero也会支持笔记在库中的搜索关键词匹配显示的

**Comment by llity** [comment]
哦，那就方便了。谢谢
