### ISSUE TITLE
[Bug] Sync Error:NotFoundError:Could not open the file at D:\test\xxxx .md.tmp for writing

### ISSUE THREAD

**Issue by YYde123** [windingwind/zotero-better-notes#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 23H2
- Zotero Version: 7.0.0.beta99
- Plugin Version:1.1.4.beta.99

### Describe the bug

在使用同步笔记，导出md文件时，弹出Sync Error:NotFoundError:Could not open the file at D:\test\xxxx .md.tmp for writing；同步管理器中可以显示
<img width="226" alt="屏幕截图 2024-07-15 101934" src="https://github.com/user-attachments/assets/e98a4027-85a1-46b5-9aea-fdf85290bd7a">
<img width="677" alt="1" src="https://github.com/user-attachments/assets/ed2b5445-13bb-4a64-9537-4a24aa216843">

### Debug Output

1721010380704	addons.xpi	WARN	Checking D:\APP\zotero\Zotero_win-x64\distribution\extensions for addons

1721010381269	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721010381271	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721010381273	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721010381273	addons.webextension.zoterotag@euclpts.com	WARN	Loading extension 'zoterotag@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721010382084	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Attempt to override an existing message: "delitemwithatt-delete-collection-and-attachment"." {file: "delitemwithatt-addon.ftl" line: 0}]

[JavaScript Error: "TypeError: _0x46ca57 is undefined" {file: "jar:file:///C:/Users/%E4%B8%80%E6%84%8F%E4%B8%80%E5%BC%82de/AppData/Roaming/Zotero/Zotero/Profiles/02vc3kca.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 1}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/%E4%B8%80%E6%84%8F%E4%B8%80%E5%BC%82de/AppData/Roaming/Zotero/Zotero/Profiles/02vc3kca.default/extensions/zoterofile@polygon.org.xpi!/chrome/content/scripts/zoterofile.js" line: 4994}]

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/%E4%B8%80%E6%84%8F%E4%B8%80%E5%BC%82de/AppData/Roaming/Zotero/Zotero/Profiles/02vc3kca.default/extensions/zoterofile@polygon.org.xpi!/chrome/content/scripts/zoterofile.js" line: 4994}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "XML Parsing Error: mismatched tag. Expected: </term>.
Location: moz-nullprincipal:{f5a9dd3c-5bfe-4ce9-b4c8-b644bc29b039}
Line Number 27, Column 7:" {file: "moz-nullprincipal:{f5a9dd3c-5bfe-4ce9-b4c8-b644bc29b039}" line: 27 column: 7 source: "    </terms>"}]

[JavaScript Error: "File is not valid XML" {file: "chrome://zotero/content/xpcom/style.js" line: 633}]
Zotero.Style@chrome://zotero/content/xpcom/style.js:633:11
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:172:25
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

[JavaScript Error: "Style with ID http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-xhs already loaded from china-national-standard-gb-t-7714-2015-xhs.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14

1721010403672	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721010403944	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/%E4%B8%80%E6%84%8F%E4%B8%80%E5%BC%82de/AppData/Roaming/Zotero/Zotero/Profiles/02vc3kca.default/extensions/zoterofile@polygon.org.xpi!/chrome/content/scripts/zoterofile.js" line: 4994}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

appName => Zotero, version => 7.0.0-beta.99+174bde745, os => Windows 10.0 22635, locale => zh-CN, extensions => Wandering File (0.2.8, extension), Easier Citation (0.4.3, extension), Jasminum (1.0.0-16, extension), Del Item With Attachment (0.3.2, extension), Zotero 插件市场 (1.6.2, extension), Actions and Tags for Zotero (1.0.0-beta.44, extension), Linter for Zotero (1.18.0, extension), Ethereal Reference (0.9.1, extension), Chartero (2.8.2, extension), Translate for Zotero (1.1.0-beta.53, extension), Ethereal Style (4.5.6, extension), Awesome GPT (1.0.0, extension), Zotero Reading List (1.3.2, extension), Better Notes for Zotero (1.1.4-beta.99, extension), PDF Figure (0.2.4, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), MarkDB-Connect (0.1.0, extension, disabled), Green Frog (0.19.03, extension, disabled), zotero-annotation-manage (0.6.93, extension, disabled)

(3)(+0028269): itemTree.render(). Displaying Item Tree

(3)(+0002137): [Warning] Creating element title with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000576): itemTree.render(). Displaying Item Tree

(3)(+0007499): [Better Notes for Zotero] runTemplate: [ExportMDFileNameV2]

(3)(+0000001): [Better Notes for Zotero] test-RPKDRPZ9.md

(3)(+0000000): Creating string pref 'extensions.zotero.Knowledge4Zotero.syncDetail-79434'

(3)(+0000001): [Better Notes for Zotero] sync start export 1 0

(3)(+0000000): [Better Notes for Zotero] will be synced: 1 0 0

(3)(+0000002): [Better Notes for Zotero] runTemplate: [ExportMDFileNameV2]

(3)(+0000000): [Better Notes for Zotero] test-RPKDRPZ9.md

(3)(+0000008): [Better Notes for Zotero] runTemplate: [ExportMDFileContent]

(3)(+0000000): [Better Notes for Zotero] # test * 你好 * 你好 * 你好

(3)(+0000000): [Better Notes for Zotero] runTemplate: [ExportMDFileHeaderV2]

(4)(+0000001): SELECT collectionID FROM collections WHERE collectionID IN (SELECT collectionID FROM collectionItems WHERE itemID=?) [79434]

(3)(+0000000): [Better Notes for Zotero] {"tags":["📝已笔记","📖阅读中"],"parent":"","collections":["00笔记库"]}

(3)(+0000002): [Better Notes for Zotero] [BetterNotes Syncing Error] {}

(3)(+0006832): itemTree.render(). Displaying Item Tree

(3)(+0002718): itemTree.render(). Displaying Item Tree

(3)(+0000592): itemTree.render(). Displaying Item Tree

(3)(+0000979): itemTree.render(). Displaying Item Tree

(3)(+0004325): [Better Notes for Zotero] sync start auto 0 1

(3)(+0000000): [Better Notes for Zotero] will be synced: 0 0 0

### Anything else?

另外，我目前是想要将batter notes 笔记和logseq 笔记同步使用，（即batter Notes内编辑笔记，然后直接用logseq继续编辑，编辑内容同样可以呈现在batter notes中）将batter notes笔记软件同步导出到logseq页面文件夹内，但这样导出同步后，logseq打开batter notes笔记格式不对，不知道是不是因为[ExportMDfileNameV2]的问题，我前面浏览过您在2023年给一个用户的回复，里面提到了[ExportMDfileNameV2]的修改，我也尝试使用了您提供的代码，但是因为Sync Error问题，一直没成功。

**Comment by YYde123** [comment]
第一，我尝试过用管理员模式启动zotero，但是也是同样的错误！我以为是写入权限的问题，还检查了一下文件夹权限，文件夹所有权限都是一样，而且管理员模式都不行，那可能是其他问题。
第二，我尝试用zotero自带的笔记导出，这个可以成功导出。

**Comment by windingwind** [comment]
文件系统相关的问题可能和其他软件占用等问题，由于是个例，无法复现，可能难以解决

**Comment by YYde123** [comment]
好的好的，非常感谢！
