### ISSUE TITLE
[Feature] 设置/User Guide中增加永不提示选项

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version: 7.0.0-beta.99+174bde745 (64-bit)
- Plugin Version: 1.1.4-beta.99

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

现在每次打开Zotero 7beta时，加载better notes插件后就会弹出user guide，虽然可以点击稍后提示，但是对于已经熟悉此插件的用户，是否可以提供一个不再提示的选项？

**Why do you need this feature?**
A clear and concise description of why you need this feature.

减少不必要的提示

### Describe the solution you'd like

**The solution you'd like**

在User Guide界面增加 *不再提示* 的选项，点击后重新打开软件加载插件后不再弹出user guide

**Alternatives you've considered**

或者可以考虑在设置选项卡增加这个选项

**Comment by windingwind** [comment]
只要完整看完一遍就不会再显示了

**Comment by ramonmi** [comment]
> 只要完整看完一遍就不会再显示了

原来如此
