### ISSUE TITLE
[Feature] 增加logseq格式化处理

### ISSUE THREAD

**Issue by YYde123** [windingwind/zotero-better-notes#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win11 23H2
- Zotero Version: 7.0.0beta.99
- Plugin Version:1.1.4beta.99

### Describe the feature request

当前问题：batter notes的导出的md笔记可以和logseq的md同步编辑，但是当前batter notes导出的md笔记在logseq中没办法正常显示，原因logseq采用“-”的形式来进行分级，而batter notes 直接是文本。
better notes使用项目符号的md格式
<img width="798" alt="1" src="https://github.com/user-attachments/assets/87c7e143-147c-4bb5-8b7a-a0d7604bbcdc">
在logseq中的显示
<img width="928" alt="3" src="https://github.com/user-attachments/assets/e19fee16-7a09-404e-9981-7b381d5603a5">

logseq的md格式
<img width="713" alt="2" src="https://github.com/user-attachments/assets/cfdb8964-3ce2-4a77-b337-2fd61f5a409b">
在logseq的显示
<img width="931" alt="4" src="https://github.com/user-attachments/assets/edaf99cd-2560-4b5b-afd1-bbe10a0d371b">

### Describe the solution you'd like

能否在格式化文本功能中加入类似与项目符号一栏，将“*”更换为logseq使用的“-”，作为logseq格式版？
<img width="230" alt="5" src="https://github.com/user-attachments/assets/eb209045-0269-4f32-9e99-72ddd8111975">

**Comment by YYde123** [comment]
前面那个笔记同步bug，换个方式，既然better notes不能导出，那从外部导入md作为笔记是可以，然后就发现了logseq的md还有区别，不知道能不能加上Logseq的“-”模板，感谢大佬！！！

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/768

**Comment by YYde123** [comment]
感谢感谢！！！原来前面已经有人提过！
