### ISSUE TITLE
[Bug] 代码块相关bug 

### ISSUE THREAD

**Issue by ZhenhongDu** [windingwind/zotero-better-notes#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows 11 
- Zotero Version: 7.0.0-beta.95+694ccecf4 (64-bit)
- Plugin Version: Better Notes for Zotero版本1.1.4-beta.86构建2024-06-2404:17:51

### Describe the bug

1.  当代码块在最后一行时，无法新建一行 （鼠标无法在代码块后操作，无法新建，只能往前移动代码块）
![image](https://github.com/user-attachments/assets/6e3195c2-b19a-422f-8433-360481cc723a)

2. 在代码块中使用tab键，所有的行都会缩进；

![image](https://github.com/user-attachments/assets/e6df9464-d844-4d29-963e-14b3c3a4377a)
按下tab之后
![image](https://github.com/user-attachments/assets/5971a1b2-1e91-4b13-9666-69c1ec4622ad)

### Debug Output

程序本身没有报错

### Anything else?

代码块后面会支持不同语言和颜色吗

**Comment by windingwind** [comment]
谢谢反馈，与插件无关，请报告给zotero
