### ISSUE TITLE
[Bug] Note tabs do not reopen after restart of Zotero

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.101+220bb4383 (64-bit)
- Plugin Version: 1.1.4-beta.99

### Describe the bug

Note tabs are not reopening after restarting Zotero.

### Debug Output

1721131147011	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1721131147664	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721131149506	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "uncaught exception: Object"]

appName => Zotero, version => 7.0.0-beta.101+220bb4383, os => Windows 10.0 19045, locale => en-GB, extensions => Better Notes for Zotero (1.1.4-beta.99, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Open PDF for Zotero (0.0.11, extension, disabled), Zotero Better Authors (4.1.3, extension, disabled), ZoteroPreview (0.7.8, extension, disabled), Debug Log for Zotero (2.0.17, extension, disabled), Zotero Attanger (1.2.3, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.44, extension, disabled), Notero (0.5.17, extension, disabled), Zotero OCR (0.7.3, extension, disabled), Translate for Zotero (1.1.0-beta.54, extension, disabled), Better BibTex for Zotero (6.7.212, extension, disabled)

**Comment by windingwind** [comment]
Thanks for the report, it's a known bug.

**Comment by citadel-lewis** [comment]
I'm using the latest beta of Zotero 7 and Better Notes but note tabs still not reopening on restart
