### ISSUE TITLE
[Bug]: In Export Note and SubNotes Selection "Auto Sync to Export Path" not selectable  

### ISSUE THREAD

**Issue by paulgenz** [windingwind/zotero-better-notes#104]
**Describe the bug**
Hi, first: thanks for putting in all the work on this awesome add-in!  

**To Reproduce**
1. when selecting a note item in Zotero
2. and right-click selecting *Export Note and SubNotes*
3. the Selection of the tickbox *Auto Sync to Export Path* is not possible
4. ALSO: The selection of the tickbox "Export Linked Notes to MarkDown File" is not possible

**Screenshots**
![bug_paulgenz](https://user-images.githubusercontent.com/72145690/182415938-6318233c-505c-41b2-9e98-0f821436b57f.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Zotero: 6.0.9
 - Better Notes: 0.6.15

**Additional context**
Additionally to this problem I am not able to export Notes to a markdownfile, as described in another [Issue](https://github.com/windingwind/zotero-better-notes/issues/102#issuecomment-1202837898)

Best regards, Paul

**Comment by windingwind** [comment]
The 'embed linked notes' is conlict with the 'export linked notes to MD'. The linked notes could either be embeded or exported seperately, but we cannot apply both to them.
If you place the cursor on the disabled checkbox for a while, you might see a hint text explaining this.

**Comment by paulgenz** [comment]
Okay. It is as you say. Thank you!
