### ISSUE TITLE
[Bug] No workspace options or main notes options

### ISSUE THREAD

**Issue by someone-jxf** [windingwind/zotero-better-notes#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0
- Plugin Version:1.1.4-beta.99

### Describe the bug

<img width="139" alt="Snipaste_2024-07-19_18-05-17" src="https://github.com/user-attachments/assets/23d13999-224c-4cdf-8e5f-19faa378f2c9">
<img width="765" alt="1" src="https://github.com/user-attachments/assets/1f931a62-5d4a-4fd4-a164-705aaec9943b">

### Debug Output

1721383804895	addons.xpi	WARN	Checking E:\Zotero7\Install\distribution\extensions for addons

1721383805270	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1721383805700	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Failed to load resource://services-settings/remote-settings.sys.mjs" {file: "resource://gre/modules/PartitioningExceptionListService.sys.mjs" line: 88}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

appName => Zotero, version => 7.0.0-beta.103+691d26886, os => Windows 10.0 22631, locale => zh-CN, extensions => Better Notes for Zotero (1.1.4-beta.99, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Actions and Tags for Zotero (1.0.0-beta.44, extension, disabled), Jasminum (1.0.0-16, extension, disabled), Translate for Zotero (1.1.0-beta.49, extension, disabled), Ethereal Reference (0.9.3, extension, disabled), Ethereal Style (4.5.8, extension, disabled), Awesome GPT (1.0.2, extension, disabled)

**Comment by windingwind** [comment]
#1021
