### ISSUE TITLE
[Feature] Support multiple selection in link creator

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#1041]
I was wondering if it was possible (or will be possible in future) to select multiple notes at one time for inserting into a note via the "Link Creator" UI? 

At present, if I do manage to select multiple notes in Step 1, only the first note gets inserted to the position in Step 2.

_Originally posted by @troyjcross in https://github.com/windingwind/zotero-better-notes/discussions/1038_

**Comment by MaxVonMustermann** [comment]
So the goal here seems to be to select multiple files and create a note based on several files instead of just one? This would be highly appreciated, since it would improve organizing annotation management a lot. Or did I misunderstand what you intend to do in this regard?
