### ISSUE TITLE
[Feature] 共存多个单独note窗口

### ISSUE THREAD

**Issue by occasional15** [windingwind/zotero-better-notes#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version:  7
- Plugin Version: beta 104

### Describe the feature request

**Why do you need this feature?**
时常需要同时打开多个单独note窗口（open as window）进行对照查看和编辑，而最近更新版本取消了这一功能，希望可以保留。

**Comment by windingwind** [comment]
启用接管笔记打开方式情况下，在库中按shift打开即为窗口打开方式。也可在笔记编辑器右上角三个点按钮，在窗口中打开

**Comment by occasional15** [comment]
> 启用接管笔记打开方式情况下，在库中按shift打开即为窗口打开方式。也可在笔记编辑器右上角三个点按钮，在窗口中打开

打开方式没问题，就是最新版BN note只能同时打开一个窗口，打开一个新窗口时，原来打开的窗口会自动关闭（被覆盖）；而旧版可以打开多个窗口并共存。
