### ISSUE TITLE
[Bug] Zotero 7 hangs and (Not Responding) after a few seconds of opening

### ISSUE THREAD

**Issue by helsingi** [windingwind/zotero-better-notes#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.105+c5c613c82 (64-bit)
- Plugin Version: 1.1.4-beta.104

### Describe the bug

When I opened Zotero, I can use it for a few seconds before it hangs, stops working, and the app window says (Not Responding).
Tried using Zotero with Better Notes disabled, and it worked fine.

### Debug Output

Could not copy the debug output because all zotero windows are not responding, but took a screenshot. It seems the issue happens once Better Notes starts syncing notes.
![Screenshot 2024-07-24 081217](https://github.com/user-attachments/assets/45e120f0-3527-4b56-8ec2-47170c00e47a)

### Anything else?

My synced notes could be the problem because I just enabled syncing notes yesterday and put the synced notes in local folder of my own cloud storage. I also synced the same notes on another computer using Linux.
Suggestion: to show an error message whenever syncing of notes is problematic and continue other processes instead of hanging the entire application.

**Comment by windingwind** [comment]
I have pushed a new release. Please check if that helps.

By the way, are you using Solid State Drives or Mechanical Hard Drives? How many synced notes do you have, and how large are they?

If you still find the auto-sync hangs Zotero, you can set the syncing period to `-1` to disable auto-syncing and sync manually.

**Comment by helsingi** [comment]
Thanks. They are two notes: 457KB and 246KB. I have an ssd nvme m2.
I updated now to the new release (105) and set the auto-sync value to -1 and tried manual sync but it gave me conflict manage window. I waited for it 3 minutes and finally decided to force close zotero. I will go back to not syncing notes for now.

**Comment by helsingi** [comment]
I expected this dialog and waited for it 3 minutes but gave up and tried to close open dialog or main zotero window but all freeze. Is my note too big that it takes that long to retrieve the merge conflict dialog?

**Comment by windingwind** [comment]
Well, that's abnormal. Since I cannot reproduce and there is no similar case reported, here are some options to help us figure out what's happening:

1. if convenient, could you please share the markdown file of the note mentioned in the debug output above with me (via email or link);
2. otherwise, please try to remove this note item from the syncing list in Tools -> Sync Manager -> Select and click Unsync, and then click Sync in the sync manager to manually sync other notes. What happens? (your data is safe - the note and the markdown file are just unlinked. you can link them back at any time)

Let me know if you need further assistance.

**Comment by helsingi** [comment]
I am afraid I can't share the file. But thanks a lot for your support. I will do a fresh installation soon on both machines and hopefully it will work fine.

**Comment by windingwind** [comment]
thanks for the reply. a fresh install isn't necessary - you can start zotero via command line with flag `-p` and create a new profile for test.

**Comment by firefoot007** [comment]
The same issue was happening with me. Unsync and re-sync fixed it for me.
