### ISSUE TITLE
笔记打开后对电脑运行内存占用较多，在撰写文字时有卡顿感

### ISSUE THREAD

**Issue by Youngee0808** [windingwind/zotero-better-notes#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows
- Zotero Version: Zotero 7. beta105
- Plugin Version: 1.1.4-beta.105

### Describe the bug

1. 笔记打开后对电脑运行内存占用较多
2. 在撰写文字时有卡顿感,, 每输入一个词组大纲界面会刷新一下

### Debug Output

wu

**Comment by windingwind** [comment]
笔记-右键菜单-关闭语法检查

**Comment by Youngee0808** [comment]
您好，我尝试按照你的建议进行了设置，但在我的主笔记撰写文字还是会有卡顿感。我又尝试新开了一个独立笔记，在新笔记里这种问题就不存在了。所以出现这个问题的原因是因为我那个主笔记文件太大（主笔记里包含了很多图片）？有什么好的解决办法么？谢谢您的回复！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月26日(星期五) 晚上10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] 笔记打开后对电脑运行内存占用较多，在撰写文字时有卡顿感 (Issue #1049)





 
笔记-右键菜单-关闭语法检查

**Comment by windingwind** [comment]
建议采用笔记链接，在记录的时候就将一个长笔记拆分成多个分类的小的子笔记，统一链接到一处，方便索引、查找、修改。

由于笔记过长/过大导致的性能问题无法解决，故此关闭
