### ISSUE TITLE
[Feature] Can citation mark style of annotation in note be more detailed or be replaced with citationkey?

### ISSUE THREAD

**Issue by LamFTS** [windingwind/zotero-better-notes#105]
Hi there, I want to know whether citation style of annotation in the note can be more detailed? When I add a annotation into note, the citation mark of this annotation contains only name of author, year of publish and paper even if I change citation style of note in setting, I wish the annotation citation mark contains the title of article I annotated or replace the current mark style with citationkey(my citationkey contains all information I need), I hope this feature can be implemented. Sorry to bother u. :)
![图片](https://user-images.githubusercontent.com/53118840/183042241-41343c99-9837-412a-ad26-e81c3e742ffe.png)
My current citation style of note:
![图片](https://user-images.githubusercontent.com/53118840/183042349-e565649b-a2f7-47e5-8bd6-5ea50c7d725d.png)
This is it should look like:
![图片](https://user-images.githubusercontent.com/53118840/183042614-8f833311-f380-4f20-8ab5-7530ec629736.png)

Environment information:
System : Windows 11 22000.832
Zotero : 6.0.10
Zotero Better Note: 0.6.16

**Comment by windingwind** [comment]
This `笔记引用格式(Citation Style in Notes)` is a feature called 'quick cite' introduced by this plugin. Use this from the note editor -> '“' button.

If you want to change the annotation format, please use Zotero's template: https://www.zotero.org/support/note_templates
