### ISSUE TITLE
[Bug] Sync Error: Operation Error: Could not move temporary file

### ISSUE THREAD

**Issue by shadowofdeepdark** [windingwind/zotero-better-notes#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version:  7.0.0-beta.105+c5c613c82 (64-bit)
- Plugin Version: 1.1.4-beta.104

### Describe the bug

The problem: ![image](https://private-user-images.githubusercontent.com/103291805/351620012-e3fc086b-5416-45df-a6d0-0132af466f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDkxMzEsIm5iZiI6MTcyMTgwODgzMSwicGF0aCI6Ii8xMDMyOTE4MDUvMzUxNjIwMDEyLWUzZmMwODZiLTU0MTYtNDVkZi1hNmQwLTAxMzJhZjQ2NmYwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzIzZWI0NjA5NDcxNTE4Nzc4MTU0ZDNlZDdjMzZjOTVmMjBhMWQ4MzBjZDc5ZjY3Njk4YmExZjRlMzNkYzVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WaH-je7fEbzol8ZqruXl_uKAD0Vn5CA-BzF1JkfBRVo)
Zotero Edition: 7.0.0-beta.105+c5c613c82 (64-bit)
Set up: ![image](https://private-user-images.githubusercontent.com/103291805/351620618-e23314e2-24ae-4166-956a-40e72aae3e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDkxMzEsIm5iZiI6MTcyMTgwODgzMSwicGF0aCI6Ii8xMDMyOTE4MDUvMzUxNjIwNjE4LWUyMzMxNGUyLTI0YWUtNDE2Ni05NTZhLTQwZTcyYWFlM2U0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTcwMjMwM2ZlYzNhMjUyZmMxNzRkY2JjOWE1YTYwYmY0NDg5Y2E0NzY2OTgxMzk2Yzg2ZjRmYzQxYTdjMzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kdOvCYOtjDdAcGiv70O7y2ndIJ6S-8QG-aLPJwjrn1w)
Context: trying to sync with Obsidian and the file was saved in the location of attempted obsidian file

### Debug Output

[Debug Output_files.zip](https://github.com/user-attachments/files/16359287/Debug.Output_files.zip)
As some types in the files are not supported for uploading, I created a zip to include them all.

**Comment by windingwind** [comment]
i didn't see the mentioned error in the debug output. please make sure to record debug output in advance.
