### ISSUE TITLE
[Feature] 添加笔记的时候能不能把添加的句子在原pdf上做一些标记呢？

### ISSUE THREAD

**Issue by BigCatNotFat** [windingwind/zotero-better-notes#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows
- Zotero Version: 7
- Plugin Version:1.1.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
添加笔记的时候能不能把提问的句子在原pdf上做一些标记呢？这样我就在打开pdf的时候知道哪些地方做过标记了

### Describe the solution you'd like

**The solution you'd like**
在勾画原文的时候添加笔记时可以选择标记原文也可以选择不用标记原文
**Alternatives you've considered**

**Comment by windingwind** [comment]
可活用zotero的tag功能。

另外不理解“在勾画原文的时候添加笔记时可以选择标记原文也可以选择不用标记原文”
