### ISSUE TITLE
[Bug] 在电脑端的笔记以markdown的形式插入图片后，无法通过坚果云将图片传输到ipad端，只能传出文本，所以ipad端看到的笔记没有图片，但是电脑端能看到图片

### ISSUE THREAD

**Issue by Rorschachzz0514** [windingwind/zotero-better-notes#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows ipados
- Zotero Version: 6
- Plugin Version:1.04

### Describe the bug

在电脑端的笔记以markdown的形式插入图片后，无法通过坚果云将图片传输到ipad端，只能传出文本，所以ipad端看到的笔记没有图片，但是电脑端能看到图片

### Debug Output

在电脑端的笔记以markdown的形式插入图片后，无法通过坚果云将图片传输到ipad端，只能传出文本，所以ipad端看到的笔记没有图片，但是电脑端能看到图片

**Comment by windingwind** [comment]
禁用所有插件，然后向PC端的任意笔记插入任意图片，待同步完成后检查是否移动端可看见图片。若仍然出现问题，请向zotero报告。

另，未按issue要求提问，故此关闭
