### ISSUE TITLE
[Feature] 支持从obsidian 自动sync .md 文件

### ISSUE THREAD

**Issue by hy-zhao** [windingwind/zotero-better-notes#106]
请问可否支持 note在 obsidian中编辑之后自动同步到zotero之中？

md的文件编写在obsidian中操作简单的多，而且界面也要整洁许多。

但是目前在md之中编辑之后不能同步到zotero中，手动点击sync之后，zotero中的内容会直接覆盖到obsidian中编写的内容。

**Comment by windingwind** [comment]
由于相关issue中已说明的原因，双向同步是危险的，因此不会支持。

**Comment by hy-zhao** [comment]
感谢回复，刚去爬了一下相关的issue，大概可以理解不支持反向同步的原因。不过是否可以支持一个可选择非自动的反向同步按钮。主要是两方面的原因：
1. zotero的笔记功能没有 obsidian 之类的软件方便，页面展示的美化也相当有限，更强大的地方在于文献的管理，您的这个软件又可以支持内部的文献笔记索引，实际上是把在 obsidian 这类纯笔记软件极不方便的文献级别的相互链接实现了，好棒☆(￣▽￣)/$:*。那么让它和笔记软件相结合实际上是各自发挥优势。
2. zotero输出的md文件的格式在obsidian这些软件之中都由于转移符号的原因都乱掉了，比如链接，缩进list在obsidian中都无法正常浏览，当然这也可能是无法双向同步的一个原因？

非常感谢开发这个插件！

**Comment by windingwind** [comment]
1. 非自动的反向同步听起来比较接近“导入markdown”？导入的话是可以做的。
2. 缩进列表具体指的是什么呢？格式的问题希望可以进一步说明，我好做对应的匹配或修复。

**Comment by hy-zhao** [comment]
![image](https://user-images.githubusercontent.com/52598758/183097058-4cb26ee9-aa10-437c-bee2-e6e3db57c7bd.png)
比如这种，左边是note，同步之后obsidian打开右边的二级list就没有了。

请问“导入markdown”是怎么操作呀？可以导入markdown作为一个文献的note吗？

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/183098823-d3c8d583-8815-4496-8bda-71304a9ffe21.png)

我试了下可以正常导出并显示多级列表的？

如果确实需要导入功能的话也可以做，可以具体描述下在什么场景下需要导入markdown吗？

**Comment by hy-zhao** [comment]
刚解决了把所有的list重新缩进，发现是我粘贴导致的。

这个导入相当于建了一个note，但是我想在md的编辑器里面写这个note。因为现在不支持双向同步，就导入我在md编辑器里面的笔记作为文献的note。这样我就可以把文献的note归入到main note之中。最后只同步main note，那么obsidian里面也可以和zotero一样可以使用双向链接查看笔记。最简单的可能还是支持双向，但是从外部比如obsidian往zotero note里面sync的时候必须先用户确认可以同步，这样可以大概可以解决对同步的不同需求吧。

**Comment by windingwind** [comment]
如果允许双向同步，看起来是双向实际上含有三个主体间的同步：外部markdown，本地笔记，云端笔记。后两者之间的同步是不受用户控制的，因此将导致不可预见的混乱。我相信大多数用户不需要这个功能。我的依据如下：
如果笔记知识是河流，zotero等与文献直接交互的笔记处于上游，而不直接和原材料接触的，进行精加工的笔记软件如ob处于下游。将下游的产品重新同步回上游的需求我认为是存疑的。

相比双向同步可能带来的问题和复杂性，我倾向于不支持双向同步。

另外zotero笔记也支持大多数的markdown语法（除了代码高亮，但我想一般不会有人在文献笔记里涉及代码）。可能并不是功能不完整，只是界面不习惯。

如果要导入markdown：
- 源在复制时支持富文本格式复制，可以直接粘贴；
- 纯文本复制的（例如大多数markdown笔记软件），可以复制后在菜单栏编辑->转换剪贴板中markdown，然后粘贴。

**Comment by hy-zhao** [comment]
好的，感谢，第二步可以解决我的问题。也许可以请求zotero支持选择默认的笔记文件类型，这样一切的问题就迎刃而解了，如果可以这样那么甚至可以引入其它的下游笔记软件，非常强大。

**Comment by windingwind** [comment]
对于zotero来说，不存在严格意义的笔记类型。笔记数据以格式化文本（富文本）存在内部数据库。不清楚“支持选择默认的笔记文件类型”指的是什么？

**Comment by hy-zhao** [comment]
就是可以设置笔记存储为md或者rtf或者org等等，而不是默认的格式化文本，fsnotes有这个功能。也可能是我不理解zotero的内部机制，把同步想的过于简单，认为只是文件的同步，才会产生这样的想法。

**Comment by windingwind** [comment]
同步的不是文件，而是数据库字段。因此讨论笔记格式看起来没有必要

**Comment by windingwind** [comment]
zotero对markdown的格式功能提供了相对完整的支持，例如标题，列表，引用等等。我觉得没有必要严格区分它是否是markdown笔记

**Comment by hy-zhao** [comment]
还有一个小问题，就是note到处md的时候会出现在标题下方，列表下方等类似的分割出多出一行空格，不知道是不是macos的问题，我看你的win的转换效果特别好。
![image](https://user-images.githubusercontent.com/52598758/183239702-6d95e618-03c2-4ace-947f-3d1209011367.png)

**Comment by windingwind** [comment]
@hy-zhao 
1. 标题、层级之间的空行是markdown标准语法允许的形式，在渲染时不应当显示为空行，typora、vscode、github等大多数markdown编辑器都遵循这一语法规范。markdown中的单个空行仅代表换行，一个以上空行才代表空行。因此导出结果是规范的，应当是你使用的编辑器或编辑器主题格式不规范。
2. 高亮、链接格式在zotero笔记上方工具栏中可设置（类似word），请使用内置的高亮和链接格式。另外，`==xx==`似乎不是标准的markdown语法，不受大多数markdown编辑器支持。
3. 在导出时可以取消勾选“转换方括号[]”即可避免转义链接和图片格式。

**Comment by hy-zhao** [comment]
嗯嗯，感谢回复，我再看看怎么解决吧

**Comment by windingwind** [comment]
将关闭该问题。
