### ISSUE TITLE
[Bug] 在betternotes模板编辑器中，有几个undefined的选项，无法删除也无法编辑

### ISSUE THREAD

**Issue by marrypoter2023** [windingwind/zotero-better-notes#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 6.0.36
- Plugin Version:1.0.4

### Describe the bug

在betternotes模板编辑器中，有几个undefined的选项，无法删除也无法编辑
![bug](https://github.com/user-attachments/assets/4b148a41-6364-469f-9dc5-226f8fad8ee7)
如图所示

### Debug Output

![image](https://github.com/user-attachments/assets/90bc5245-edd0-4dda-8ca3-d5edf2a41d03)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/802

**Comment by Kagkks** [comment]
问题解决了，谢谢！
