### ISSUE TITLE
[Bug] can not create main note

### ISSUE THREAD

**Issue by peiliu0408** [windingwind/zotero-better-notes#1067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  maxos Sonoma
- Zotero Version:  7.0.0-beta.108+80cc97125
- Plugin Version: 1.1.4-beta.109

### Describe the bug

can not create main note

### Debug Output

None

### Anything else?

<img width="919" alt="截屏2024-07-30 15 43 09" src="https://github.com/user-attachments/assets/7c9d0122-c527-425d-8523-7b81ee3217ff">
<img width="422" alt="截屏2024-07-30 15 43 17" src="https://github.com/user-attachments/assets/67a57e72-eea2-4068-8ac1-f5a6df067279">

as shown in the above screenshot, the main note could not be created.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes?tab=readme-ov-file#getting-started-with-the-workspace
