### ISSUE TITLE
[Bug]主笔记的 “ 点了没反应

### ISSUE THREAD

**Issue by adahfbch** [windingwind/zotero-better-notes#107]
主笔记的 “ 点了没反应，分笔记里的 ” 是正常的，Mac系统

在主笔记里插入多条item的时候，item2中会讨论有关item1的东西，希望直接引用表示item1，但是点了 “ 没反应，不像作者这个视频里讲解的，点 “ 的时候会弹出可以选择的引文界面

<img width="1135" alt="截屏2022-08-06 23 34 40" src="https://user-images.githubusercontent.com/95211729/183255773-5babc676-9856-4c61-b303-0e3f702161b6.png">

**Comment by windingwind** [comment]
请打开工具-调试输出-查看输出，然后执行出现问题的操作，然后将调试输出的窗口内容复制在此。

**Comment by adahfbch** [comment]
>Mac里工具那只有一个error console 和 Run Javascript，如果我没理解错作者的话，为了方便查看我点 “ 后出现的error，我把error console里的内容全都clear后，点了 “ ，但error console里没有显示error，于是把程序退出重启后，再点 “ 就可以正常弹出选择引文的窗口，问题在不知道发生了什么的情况下解决了，感谢作者!

**Comment by windingwind** [comment]
解决就好。将关闭该问题
