### ISSUE TITLE
[Feature] 希望"通过注释添加笔记"功能生产Note时可以携带注释标签

### ISSUE THREAD

**Issue by mo-qc** [windingwind/zotero-better-notes#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0
- Plugin Version:1.1.4-beta.113

### Describe the feature request

一篇PDF中有多个注释，每个注释均有不同的标签，当使用“通过注释添加笔记”功能上，一份PDF中的多个注释生成了一份Note，但每个注释的自有标签却丢失了，能否生成注释笔记时，每个注释后都能带上阅读标注读者所赋予的标签时，方便归类整理

**Comment by windingwind** [comment]
该功能为zotero功能，与插件无关
