### ISSUE TITLE
[Bug] 彻底删除注释笔记后，将无法创建同一注释的笔记

### ISSUE THREAD

**Issue by Papewhit** [windingwind/zotero-better-notes#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0-beta.116+7f21da933 (64-bit)
- Plugin Version: 1.1.4-beta.113

### Describe the bug

在注释条目上点击“花型按钮”创建注释笔记后，若删除该条笔记，则：

- 被移动到回收站的该条笔记仍能通过“花型按钮”打开
- 在回收站彻底删除该条笔记后，将无法通过“花型按钮”再次创建该条注释的笔记

此时，只能删除该条注释、重新创建注释、重新创建注释笔记。

尝试禁用所有其他插件，仅保留 Better Notes 插件，仍能复现。

### Debug Output

操作过程：
在 PDF 文件上创建注释 -> 点击按钮创建注释笔记 -> 关闭笔记弹窗 -> 将笔记移动至回收站 -> 点击按钮尝试打开笔记
 -> 关闭弹出的笔记标签页 -> 从回收站彻底删除笔记 -> 点击按钮尝试创建笔记

[Debug Output 2024-08-08-2.txt](https://github.com/user-attachments/files/16554700/Debug.Output.2024-08-08-2.txt)

**Comment by clooo603** [comment]
我也有这个情况，必须要重新删掉注释，才能在这个注释上用那个花型按钮
