### ISSUE TITLE
[Feature] Enhancement to Relation Graph in 

### ISSUE THREAD

**Issue by pcinque** [windingwind/zotero-better-notes#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:
2.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
The relation graph in the Better Notes tab/window displays relation links to Zotero Notes (to the note or location in the note). Note pages can have links to web pages and external programs (via protocol link e.g. onenote: ).

**Why do you need this feature?**
It would be useful to show relation links to these external links to show a more complete picture of relationships.

### Describe the solution you'd like

**The solution you'd like**
Add relation links to the Relations Graph to display external links contained in the note.
Add relation links to the Relations Graph to display zotero: links including Annotation links.

**Alternatives you've considered**
Obsidian?

**Comment by physicslog** [comment]
Would be great if the "Relation Graph" window can be resized with user preferences and also able to open as a new window. Any plan?
