### ISSUE TITLE
增加双链笔记的细粒度---可以引用笔记中某个小节

### ISSUE THREAD

**Issue by Infinemen** [windingwind/zotero-better-notes#108]
**我如何使用的**
我想写一个把关于某个课题的笔记作为主笔记，需要按自己的组织框架，对应插入该课题下的多篇文章中内容（每篇文章会有一个自己的阅读笔记）。

**需求**
希望能够支持按笔记中的小节插入，即增加细粒度

**例子**
主笔记：  全球变暖

一级标题： 研究意义

插入： 文献A阅读笔记中  研究意义小节

一级标题： 研究方法
1. 插入： 文献A阅读笔记中  研究方法小节
2. 插入： 文献B阅读笔记中  研究方法小节

文献A
文献A阅读笔记

文献B
文献B阅读笔记

**最后**
我刚刚开始使用这个插件三四天，我不确定我想要的笔记管理形式是否已经可以在插件实现。目前看文献已经很舒服了，感谢您开发这么好用的插件，致敬。

**Comment by windingwind** [comment]
插入小节功能最大的障碍是如何处理用户对目标笔记的编辑？用户可能移动，修改，删除或者重复命名小节。

**Comment by Infinemen** [comment]
我不是特别了解双链笔记背后的设计原理和逻辑，回答不了你的问题，可能你也不是想问我，只是想在这里讨论。

我只用过Logseq，刚刚试了下，无论在引用的笔记还是源笔记更改是可以互相同步的。

**Comment by windingwind** [comment]
这涉及到笔记底层（编辑操作），很可惜由于zotero的笔记系统我无法改变，因此很难实现引用与源的互相同步。而且由于zotero的多端同步功能，现有的笔记很可能在同步时被任何形式修改或删除，因此将无法确定链接锚点。

如果实现笔记的段落链接，可能无法实现修改后双向同步，只能由用户管理链接锚点。例如，链接到某笔记的某层标题，或链接到某一行。

**Comment by Infinemen** [comment]
>如果实现笔记的段落链接，可能无法实现修改后双向同步，只能由用户管理链接锚点。例如，链接到某笔记的某层标题，或链接到某一行。

这个会实现么，目前，觉得比较难形成自己关于某个大课题的阅读笔记。

**Comment by windingwind** [comment]
可以的，只要用户需要&可以实现，我都会考虑做。
和功能无关，讨论笔记粒度问题，可能大家的使用方式不同，我感受到各人对笔记粒度的需求和用法很不相同。
我自己设想的是从批注笔记-条目笔记-主笔记（独立笔记）依次粒度递增，分别对应引用文章段落-引用文章中的某一个归纳的点-主要的链接位置。对于最小粒度的笔记，我自己使用方式是从批注创建笔记后添加链接，供参考。

回到功能上，如果不在意段落/行级别链接无法自动更新，我将会考虑在合适的时机引入该功能。

**Comment by Infinemen** [comment]
这样，一篇文献下面是不是出现多条笔记。如果是，那这样的话，文献管理的时候会不会有点乱？会不会增加同步负担？

**Comment by windingwind** [comment]
一篇文献具有多条笔记是zotero允许的功能，用户自由度更高。
文献管理看各人的方法和习惯，如果按照双链笔记思路，不需要关心笔记具体存放位置和数量，只需要沿着某一个入口笔记（例如主笔记），顺着链接深入回顾或者完善即可。我自己使用过程中好像不会去关注到底一个文献下面有几个笔记。
同步负担不清楚具体指什么，同样的内容放在一个笔记或者多个笔记不影响同步消耗的流量。

**Comment by windingwind** [comment]
关于这点，我计划先支持将注释快速插入到主笔记。是否会一定程度满足这里讨论的“细粒度”需要？

**Comment by windingwind** [comment]
Supports line-level jump via note link.
This is a new feature in v0.7.1(Only supports Zotero 6.0.14+, which is currently a beta version).

![image](https://user-images.githubusercontent.com/33902321/188258001-d49138bc-3187-4552-b66e-bb438b4faed6.png)

**Comment by windingwind** [comment]
已经支持复制当前节链接。

**Comment by RTcui** [comment]
> 已经支持复制当前节链接。

感谢回复，试了功能。      复制当前节链接在主笔记中粘贴后，会生成一个单链笔记。点击预览会调转如下图所示。

![image](https://github.com/windingwind/zotero-better-notes/assets/103620369/de0c287c-2995-4a3d-b2c9-e954513a5025)
但是，笔记预览区显示全部笔记也会影响专注度。

我的应用场景模式图如下：  每篇文献都有一个总的笔记，笔记中有背景、意义等，最终会自己做个总结归纳成自己的一句话。     多篇文献的归纳句子一汇总就是一篇综述，所以才有了上面我回复中提到的按个需求。

        不知道其他用户有这个需求的人多不多，还有这个功能是否可以实现。【目前我是单独复制当前节，然后再生成一个子笔记，最后再将子笔记插入到工作区笔记的】
![image](https://github.com/windingwind/zotero-better-notes/assets/103620369/fcf476c9-de5d-46ea-b1b8-025b3c7c50fa)
