### ISSUE TITLE
[Bug] 在编辑器中常规的[]()格式无法识别

### ISSUE THREAD

**Issue by logseq20182018** [windingwind/zotero-better-notes#1080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win10
- Zotero Version: 7
- Plugin Version:2.0

### Describe the bug

![image](https://github.com/user-attachments/assets/a8f95d4e-3386-4718-aac7-c515f0776217)
编辑器中常规md格式无法识别，如([Saelens et al., 2019, p5](zotero://open-pdf/library/items/SBYIGYXG?page=5&annotation=SVSYW7DX))

### Debug Output

-

### Anything else?

-

**Comment by windingwind** [comment]
请使用编辑工具栏-插入链接
