### ISSUE TITLE
[Bug] 无法将窗口移动到新窗口

### ISSUE THREAD

**Issue by 11good11** [windingwind/zotero-better-notes#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

![image](https://github.com/user-attachments/assets/3e81f011-cfe6-40c9-9d08-c65e42e15c57)
移动到新窗口编辑，但是始终没法操作，这个问题很久就出现了，但是一直没解决，现在是正式版本了，希望能够获得关注。

### Debug Output

无

### Anything else?

无

**Comment by windingwind** [comment]
可通过笔记编辑器菜单-在单独窗口打开
