### ISSUE TITLE
[Bug] 右键菜单双横线问题

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11
- Zotero Version: 7.0
- Plugin Version: 2.0.0

### Describe the bug

- 对于parent item，右键菜单出现一处双横线分界线，大多在Better Notes上方，但不全是，有时也在其他插件引入的菜单上方
![屏幕截图 2024-08-15 111742](https://github.com/user-attachments/assets/fb6199c6-ff55-4576-a13c-13680816c937)

- 对于attachment item，右键菜单出现两处双横线分界线
![屏幕截图 2024-08-15 111916](https://github.com/user-attachments/assets/461958ee-7ee0-435c-b305-dbc5aa2da433)

- 怀疑有可能是大佬开发的 https://github.com/windingwind/zotero-plugin-template 中存在的UI问题，这个问题由来已久，至少在Zotero7beta10x就发现了，现在发布了正式版，希望可以得到更新

### Debug Output

None

**Comment by windingwind** [comment]
与插件模板无关。有的插件选择在自己菜单栏的下方加分割线，有的选择在上方（例如本插件），就有可能出现冲突的情况。

理论上，所有插件都应该在内容上方加分割线，以与其他菜单内容相区分。因此本插件的行为没有问题，谢谢反馈

**Comment by ramonmi** [comment]
- 看起来至少translate插件存在一些问题
    - 开启item menu选项时，菜单截图正常
![屏幕截图 2024-08-23 182129](https://github.com/user-attachments/assets/108e11a6-63bd-4497-82cc-115f1d11c6ca)
    - 关闭item menu选项时（两个选项都关闭），分割线仍然保留着，就会出现这种情况，以下截图只开了translate插件
![屏幕截图 2024-08-23 182158](https://github.com/user-attachments/assets/feb527bb-892a-4a94-9f83-3ba928d96eaa)

不知是否可以较为方便的实现设置里两个item menu选项都关闭时，去除该分割线。谢谢
BTW，设置里的选项勾选/取消勾选后似乎没有立即生效，必须重启软件才生效
