### ISSUE TITLE
[Feature] 笔记内能否添加对行内数学公式的支持呢？

### ISSUE THREAD

**Issue by nwomn** [windingwind/zotero-better-notes#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 
- Zotero Version: 7.0.1
- Plugin Version: 2.0.0

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
我尝试在笔记中添加行内公式，但发现2.0.0版本的笔记中仅支持一整行的数学公式块，似乎并不支持类似Obsidian、Notion中$$的方式添加行内公式，是否能添加对行内数学公式的支持呢？

### Describe the solution you'd like

**The solution you'd like**
就是希望能支持穿插在文本之间的行内公式，而不是单独占用一行的块公式

**Alternatives you've considered**

**Comment by windingwind** [comment]
支持的。另外与插件无关，请向zotero forums反馈

<img width="334" alt="image" src="https://github.com/user-attachments/assets/53b7853e-1044-4760-af43-ff476f2ce607">
