### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CharmingCarl** [windingwind/zotero-better-notes#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.1
- Plugin Version:2.0.0

### Describe the bug

在笔记中的摘要部分里的英文单词在换行时没有合理换行，一个单词被分成两行里显示。

### Debug Output

![debug-output](https://github.com/user-attachments/assets/92751b43-71e3-468d-af7e-10bd2bb87598)

**Comment by windingwind** [comment]
不理解。如果你是指来自pdf的批注（annotation）的格式，则是原pdf的排版问题，与插件/zotero均无关
