### ISSUE TITLE
[Feature] 希望设置选项可以统一放到 工具 菜单中，或单独的设置面板

### ISSUE THREAD

**Issue by tangjyan** [windingwind/zotero-better-notes#109]
这么多插件只有 zotero-better-notes 插件的设置放在了 `编辑` 菜单下，而且占据了 `首选项` 原本处在的最后一行，
建议要么统一放到`工具`菜单下，或者单独的设置面板

**Comment by windingwind** [comment]
放置功能入口都是按照功能本身的属性，例如导入导出在文件菜单，插入内容，调整内容在编辑菜单，界面功能在查看菜单。只是因为插件提供的功能以编辑为主，因此大多数在编辑菜单下。
由于已经按照目前的分类方式发布了较长时间，请用户在此讨论是否应该移动所有菜单内容到单独的菜单栏，或者保持原状？并说明原因。
将根据用户意见决定是否修改功能入口位置。

**Comment by tangjyan** [comment]
1、既然是主动下载安装插件的用户，自然有插件的概念，需要调整什么插件的设置，就去什么插件的设置调整，这是自然而然的，因此放在`工具`菜单下，有个统一的设置入口很合理；
2、`首选项`、`退出`这种约定俗成在菜单最后一行的习惯，被插件的设置顶替掉看起来真的很突兀；

**Comment by windingwind** [comment]
大部分是功能入口而非设置，因此简单放在工具下面不合理；
其次，菜单栏项有几十项不同的功能，未来可能还会增加，全部放在工具下面也不方便使用，不现实。
由于是涉及到用户习惯的重要改动，我希望听取更多用户的意见建议。

**Comment by windingwind** [comment]
@tangjyan 
已在最新版本中将首选项与退出调整为菜单栏最后一项

**Comment by tangjyan** [comment]
小建议，如果融入系统菜单的话，那最好
1、`编辑`中的三个菜单项应该之间没有横线隔开，因为都是一个软件的；
![image](https://user-images.githubusercontent.com/21167731/184319602-0f9a83c1-60dc-4da8-b84c-30c6d029eab6.png)
2、`帮助`中的`关于`也应让系统的`关于`置底
![image](https://user-images.githubusercontent.com/21167731/184319675-537c51e6-f54d-4777-9158-c675b20b5342.png)

**Comment by windingwind** [comment]
1. 为何分栏：
![image](https://user-images.githubusercontent.com/33902321/184327936-7b9d6f73-111d-43d4-9018-1115e50e7a16.png)
与是否是一个插件无关，与功能分类有关。这几个内容分栏是因为它们功能归类不同

2. 帮助中的关于内容不是常用菜单项。似乎没有充分理由需要置底。尽可能减少不必要的开发和维护。
