### ISSUE TITLE
[Feature] Compile annotations from different files into one single note

### ISSUE THREAD

**Issue by MaxVonMustermann** [windingwind/zotero-better-notes#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Mac OS 15.1
- Zotero Version: Zotero 7
- Plugin Version: 2.0.0

### Describe the feature request

Creating a note based on several parent files in order to have an overview of every annotation would highly improve the user experience.

### Describe the solution you'd like

The title says it all basically. One note based on several parent file.

### Anything else?

Thank you in advance!

**Comment by windingwind** [comment]
Could be #236. See also https://github.com/windingwind/zotero-better-notes/issues/85#issuecomment-1212751592
