### ISSUE TITLE
Bug: new tools are shown above the PDF file content index

### ISSUE THREAD

**Issue by woodwm** [windingwind/zotero-better-notes#11]
After installing the add-on, new tool are shown above the PDF file content index and I think this should not happen.

Another bug is that after click the icon "Add link of current note to the main note", it create a link to the main note in the main note rather than to the PDF content index or PDF.

![image](https://user-images.githubusercontent.com/13971199/168477515-95f00e99-f7d9-427f-ac32-3eabbb11519a.png)

**Comment by windingwind** [comment]
Will fix it in the next release.
The toolbar issue will not be handled currently. It is not an emergency bug
