### ISSUE TITLE
条目右侧工具栏不显示的问题

### ISSUE THREAD

**Issue by Mapximena** [windingwind/zotero-better-notes#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.3（64-bit）
- Plugin Version:2.0.3

### Describe the bug

1.安装插件后，点击条目，右上角不显示插件按钮
![cb2f83928f76325cb06e5f2f0fbd419](https://github.com/user-attachments/assets/20921027-c25d-4b4f-994c-79a9ff2577aa)

![87eced79a2ac964081605f5dd26a57a](https://github.com/user-attachments/assets/aa05d347-35b5-4de6-b021-8abe6091d632)

2.在帮助选项中点击“打开Better Notes用户指南”后给的“welcome to better notes”文档右侧却出现了插件按钮，但点击其他条目和文件还是没有
![f1d57330d41efa736fcdd14626b82fd](https://github.com/user-attachments/assets/9f1c08eb-233f-4275-9f0b-8a44d295b1c8)

![a2652dda6039feb5746e552b4be1c1a](https://github.com/user-attachments/assets/c5186c25-df57-4992-8760-157e6f360291)

3.点击新建笔记，右侧出现按钮
![fe769e1ed016b6d8819635dd33f3bc0](https://github.com/user-attachments/assets/f65e8fc6-2a13-4349-b158-e3cc5fae30c8)

4.重新导入条目和文件，右侧按钮不显示
5.更新重装插件依旧没有解决，目前只装了pdf translate和better note两个插件，无其他插件

总之，如何解决条目右侧按钮不显示的问题？谢谢！

### Debug Output

[Debug Output.zip](https://github.com/user-attachments/files/16776047/Debug.Output.zip)

**Comment by windingwind** [comment]
你的图1选中的是regular item，当然不会显示笔记工具栏。仅打开笔记时会有笔记栏。

建议先熟悉zotero基础使用再熟悉插件功能
