### ISSUE TITLE
[Bug] BN笔记输出pdf图片的比例会异常压缩

### ISSUE THREAD

**Issue by FemiSphere** [windingwind/zotero-better-notes#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.3-beta.2+10d27b8f6 (64-bit)
- Plugin Version: 2.0.3

### Describe the bug

首先感谢开发者！
## 问题是这样：
在笔记中粘贴图片，而后使用自带的导出pdf功能，在部分情况下，图片比例会被异常压缩（体现为长度被压缩）
- 右键调节图像尺寸后输出仍然存在这一情况
- 在笔记中插入较多图片时，只有部分图片输出后存在比例失调，怀疑是否和图片的长宽比有关？

### 正常显示的笔记页面：
![image](https://github.com/user-attachments/assets/9b4a0cee-4160-495f-9f86-52141d74634c)
### 导出pdf的异常情况：
![image](https://github.com/user-attachments/assets/af7b95d9-98e3-4bd1-a187-b156d710dfc5)
### 我在输出pdf时候的选项：
![image](https://github.com/user-attachments/assets/9f0cb6b1-d5dd-4ee3-8686-358f3f11d9b3)

再次感谢开发者，期待问题早日解决！！

### Debug Output

1724754673536	addons.xpi	WARN	Checking D:\Zotero\distribution\extensions for addons

1724754673576	addons.xpi-utils	WARN	addMetadata: Add-on undefined is invalid: Error: Invalid addon ID: expected addon ID undefined, found undefined in manifest(resource://gre/modules/addons/XPIDatabase.jsm:3108:15) JS Stack trace: addMetadata@XPIDatabase.jsm:3108:15
processFileChanges@XPIDatabase.jsm:3569:26
checkForChanges@XPIProvider.jsm:3121:60
startup@XPIProvider.jsm:2532:12
callProvider@AddonManager.sys.mjs:228:31
_startProvider@AddonManager.sys.mjs:536:17
startup@AddonManager.sys.mjs:742:14
startup@AddonManager.sys.mjs:3666:26
observe@amManager.sys.mjs:73:29

1724754673953	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "TypeError: t.destroy is not a function" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

appName => Zotero, version => 7.0.3-beta.2+10d27b8f6 (x64), os => Windows 11 22631, locale => zh-CN, extensions => Jasminum (1.0.0-16, extension), Zotero Attanger (1.2.4, extension), Zoplicate (3.0.3, extension), Actions and Tags for Zotero (2.0.0, extension), Translate for Zotero (2.0.0, extension), Zotero 插件市场 (1.6.15, extension), Easier Citation (0.4.4, extension), Ethereal Reference (1.0.0, extension), Awesome GPT (1.2.0, extension), Better Notes for Zotero (2.0.3, extension), Linter for Zotero (1.18.3, extension), Ethereal Style (4.8.0, extension, disabled)

**Comment by GangLongYu** [comment]
Thank you very much for your great plugin.  I have the same problem when exporting notes to pdf.
