### ISSUE TITLE
[Bug]笔记界面拖拽文本块，却会复制并粘贴

### ISSUE THREAD

**Issue by whyihaveyou** [windingwind/zotero-better-notes#111]
如果我没有理解错，按理说应该是拖拽文本块可以实现移动，而按住control再拖拽文本块实现的是复制粘贴。
但我发现这两种操作方式都会导致复制粘贴。
不知道是不是我的理解问题

**Comment by whyihaveyou** [comment]
bug范围：在文献库的侧边栏是ok，但在工作区就存在该bug了

**Comment by windingwind** [comment]
已修复
