### ISSUE TITLE
[Feature]  Add a biblography option in better notes

### ISSUE THREAD

**Issue by econstar** [windingwind/zotero-better-notes#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 7
- Plugin Version: Laatest
  - Hello , Thanks for Nice Plug in, I thought there is space for improvement in better notes, when we adding citations can you add a biblography option too, this would be great help for all of us. 

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

- we using word plug in but if there is option of add biblography in better notes it will simple most of the our procesess

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**
- Requirement of Add a biblography option as in MS Word Plug in

**Comment by iampearl918** [comment]
开发者您好！类似这个帖子提到的，请问better note中如何更改文献引用的样式？
只在我第一次插入引注时，弹出来窗口让我选择样式（同word中插入引注），但word中可根据需要更改，better note中之后再也不能更改了，或者是我没找到更改的位置！？😭

**Comment by windingwind** [comment]
The note is not for academic writing, so it's not likely you can insert a bibliography.

You can use the `insert citation` button in the note and then export to DOCX/insert note from MS Word. The citations will be converted to bib automatically.
