### ISSUE TITLE
笔记标题无法对齐

### ISSUE THREAD

**Issue by dualer** [windingwind/zotero-better-notes#112]
**Describe the bug**
![image](https://user-images.githubusercontent.com/85242539/184057222-e4d675d6-39af-43a3-bd0c-ce4d931a59c3.png)

如上图所示, Workspace中的标题无法对齐

**Comment by windingwind** [comment]
因为在无序列表内，下级标题是列表行（wald，2001）的子元素。
在标题行前回车或shift+tab即可。这不是bug，在word里面用列表也是一样的。

**Comment by dualer** [comment]
ok, 标题前回车不行, shift+tab可以, 谢谢.
