### ISSUE TITLE
[Bug] 在用"$$”编辑公式后, 中文输入法会失效，但可以输入英文。

### ISSUE THREAD

**Issue by joker507** [windingwind/zotero-better-notes#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4

### Describe the bug

在用"$$”编辑公式后, 中文输入法会失效，但可以输入英文。

### Debug Output

在用"$$”编辑公式后, 中文输入法会失效，但可以输入英文。

**Comment by windingwind** [comment]
升级zotero与插件
