### ISSUE TITLE
[Feature]批量修改标题的级别

### ISSUE THREAD

**Issue by goodluckhu** [windingwind/zotero-better-notes#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

### Anything else?

哈喽，可以问一个关于zeotero better notes的问题吗。众所周知，我们使用mark down语法编辑笔记。然而我发现存在这样一个问题，把mark down语法编译好的文本(例如使用插件)复制到txt文本中，然后再复制txt的文本粘贴到BN中，发型#识别不了，不能转成正确的标题格式。之所以我会遇到这个问题是我想批量修改标题级别，例如我想在三级标题前插入一个标题，插入后使得三级标题及三级以后的标题都往后变化(三级变四级，四级变五级)。因为在做笔记的时候 ，利用思维导图，就想在某个节点前增加节点。

**Comment by windingwind** [comment]
> 之所以我会遇到这个问题是我想批量修改标题级别，例如我想在三级标题前插入一个标题，插入后使得三级标题及三级以后的标题都往后变化

对于该例子，新建一个三级标题，然后在左侧大纲栏tree view模式下，将目标层级全部拖拽入该新栏之下，即可自动更改标题等级

> 把mark down语法编译好的文本(例如使用插件)复制到txt文本中，然后再复制txt的文本粘贴到BN中

https://github.com/windingwind/zotero-better-notes/discussions/824
