### ISSUE TITLE
[Bug] Left and right columns disappearing in the notes workspace

### ISSUE THREAD

**Issue by nkuegler** [windingwind/zotero-better-notes#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 Version 22H2
- Zotero Version: 7.0.3 (64-bit)
- Plugin Version: 2.0.3

### Describe the bug

When deleting the introductory note "Welcome to Better Notes", in all other notes the left and right columns (table of contents, relation graph, ...) are not visible anymore and I did not find a way to show them again other than restoring the introductory note.

### Debug Output

none

**Comment by windingwind** [comment]
Please attach screenshot, thank you

**Comment by nkuegler** [comment]
I am sorry, the issue was resolved by a minor change in the settings. It had to do with how the notes were opened by zotero, not with the introductory note. 

Sorry for wasting your time, Please close this issue

**Comment by nkuegler** [comment]
Sorry for wasting your time,
