### ISSUE TITLE
[Bug] 无法自动生成条目笔记

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-better-notes#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows11 23H2
- Zotero Version: 7.0.3
- Plugin Version:2.0.5

### Describe the bug

高亮标注段落，左侧的笔记区也有笔记生成，但是文献条目下没有对应的笔记条目生成，必须要点击一下左侧better note的图标，才会在文献下面生成笔记。

### Debug Output

无

**Comment by windingwind** [comment]
没有此功能。若需要添加批注时自动生成笔记，请使用[action插件](https://github.com/windingwind/zotero-actions-tags)自行设定动作
