### ISSUE TITLE
[Bug] md导出没有内容

### ISSUE THREAD

**Issue by willawui** [windingwind/zotero-better-notes#113]
您好，很棒的工作！
想请教一下关于 导出结果没有内容，创建了一个空的 md 文件以及包含图片信息的 文件夹attachments。

 - OS: MacOS Monterey 12.3
 - Zotero: 6.0.11
 - Zotero Better Notes: 0.6.18

![Screenshot 2022-08-11 at 10 57 53](https://user-images.githubusercontent.com/54614244/184064151-8cd91876-f79a-496d-b853-32bf9779685c.png)
![Screenshot 2022-08-11 at 12 20 03](https://user-images.githubusercontent.com/54614244/184064211-928e2e97-0174-41b2-9b97-0eb43ae7dbe3.png)

这里是调试输出。[debug_output.txt](https://github.com/windingwind/zotero-better-notes/files/9306069/debug_output.txt)

感谢

**Comment by windingwind** [comment]
看起来是由于某种原因，其中某一个图片注释内容错误或丢失。请尝试以下版本。下载后将文件名后缀改为.xpi：
[zotero-better-notes.zip](https://github.com/windingwind/zotero-better-notes/files/9306936/zotero-better-notes.zip)

**Comment by willawui** [comment]
重装了以后可以导出内容了，谢谢。 还有个问题是 attachments 文件夹出现是正常的对吗？

**Comment by windingwind** [comment]
是的，markdown是纯文本，无法内置图片，必须把图片导出来，以链接方式引用。

**Comment by willawui** [comment]
好的，非常感谢。

**Comment by willawui** [comment]
好的，非常感谢。
