### ISSUE TITLE
[Bug] Less-than symbol destroys markdown file when color highlights are exported

### ISSUE THREAD

**Issue by jbschulte** [windingwind/zotero-better-notes#114]
Hi, I am super happy about the update that allows to keep the color of the annotations in the Markdown export. Thanks! However, the Markdown file will be destroyed if the annotations contain a "<" symbol. Is there any way to fix this?

**Comment by windingwind** [comment]
Could you please provide an example of the note and the 'destroyed' markdown file? What does 'destroy' means?
