### ISSUE TITLE
[Feature]  Can You please provide add a biblography feature in better notes

### ISSUE THREAD

**Issue by econstar** [windingwind/zotero-better-notes#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Add a Biblography feature in better notes**
While we are using better notes if you provide adding citations plug in like in MS Word, If you do that it would be helpful 

### Describe the solution you'd like

**Please Provide adding citations like in existly available for word 7**

**Comment by windingwind** [comment]
<img width="269" alt="image" src="https://github.com/user-attachments/assets/b85cf81a-a4f9-46cd-9d77-1df47405ae84">

**Comment by econstar** [comment]
Hello, 

Thanks for reply, I am asking about a a feature like available for MS Word where we can add citations from given library edit styles in bibliography that's it , so that it could be easy for all of us writing in zotero itself. please mention your thoughts

**Comment by windingwind** [comment]
The citations in the note will be converted to the so called _biblography_ when you export it to a MS Word format.

**Comment by windingwind** [comment]
You can change the citation style in the exported MS Word.

No one would write the full paper in a note. The citation style isn't that important here.
