### ISSUE TITLE
[Bug] 导出md失败

### ISSUE THREAD

**Issue by wangjun-kai** [windingwind/zotero-better-notes#1142]
- OS: Windows 11 23H2
- Zotero Version: Zotero 7
- Plugin Version:Better Notes for Zotero2.0.8

### Describe the bug

导出MarkDown File×
D.\文档\Obsidian Vault\文献阅读(8-2023).md
找不到文件请检查文件名是否正确，然后重试。

**Comment by upYangxy** [comment]
附议，同样无法导出md，请求处理。

OS: Windows 10
Zotero Version: Zotero 7
Plugin Version: Better Notes for Zotero2.0.8

选择"export note“后，会在笔记所在文件夹下产生新的空白笔记，同时也未能正常导出md笔记。
