### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by likemuuxi** [windingwind/zotero-better-notes#115]
首先感谢作者的辛苦开发，我想提问下能否实现如下功能：

**复制zotero内置PDF阅读器的标注，并格式化文本，以便于粘贴到笔记中。**

下文链接为quiker的一个动作，想要实现类似的效果。
[复制标注:Zotero ](https://getquicker.net/Sharedaction?code=9929ca26-05da-4056-88bb-08da1d3e98c7)

**Comment by windingwind** [comment]
是需要复制批注为markdown格式吗

**Comment by likemuuxi** [comment]
> 
是下面这种链接，导出zotero笔记时标注下链接，我不知道是不是就是markdown格式
[pdf](zotero://open-pdf/library/items/RJK2PWIT?page=2&annotation=ECNYLZ7L)

**Comment by windingwind** [comment]
与插件相关性不大的功能暂不支持
