### ISSUE TITLE
[Feature] Citation style change in Better Notes Option

### ISSUE THREAD

**Issue by econstar** [windingwind/zotero-better-notes#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Auto-Adapt Citation Styles Based on Context
The "Better Notes" plugin could automatically adapt the citation style depending on the context of the document (e.g., academic papers, blog posts, or presentations). For instance, in academic documents, it could default to a formal citation style like APA or Chicago, while in more informal writing, it might suggest simpler citation styles like MLA or footnotes.
### 2. In-Text Citation Preview
The plugin could display a live preview of how the citation would look in various styles before the user commits to a particular style. This would help users instantly see the formatting changes and choose the best fit for their needs.
### 3. Custom Citation Styles
Support for user-defined custom citation styles would be beneficial, allowing users to tailor styles to specific journal guidelines or institutional preferences. This could be integrated into the plugin settings, giving users more flexibility.

### Auto-Adapt Citation Styles Based on Context
The "Better Notes" plugin could automatically adapt the citation style depending on the context of the document (e.g., academic papers, blog posts, or presentations). For instance, in academic documents, it could default to a formal citation style like APA or Chicago, while in more informal writing, it might suggest simpler citation styles like MLA or footnotes.
### 2. In-Text Citation Preview
The plugin could display a live preview of how the citation would look in various styles before the user commits to a particular style. This would help users instantly see the formatting changes and choose the best fit for their needs.
### 3. Custom Citation Styles
Support for user-defined custom citation styles would be beneficial, allowing users to tailor styles to specific journal guidelines or institutional preferences. This could be integrated into the plugin settings, giving users more flexibility.

**Comment by windingwind** [comment]
Thanks for the suggestion, but unfortunately it is not technically possible.
