### ISSUE TITLE
[Bug] v2.0.10 breaks some console functionality

### ISSUE THREAD

**Issue by dvanoni** [windingwind/zotero-better-notes#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS 15.0
- Zotero Version: 7.0.7
- Plugin Version: 2.0.10

### Describe the bug

A user of my Zotero plugin reported https://github.com/dvanoni/notero/issues/589 where the plugin had recently stopped working. They have a number of Zotero plugins installed and determined that the latest version of BN was causing the issue. Looking at the screenshot they shared, I determined that BN v2.0.10 appears to be breaking some functionality of `console` that my plugin uses, but v2.0.9 works fine.

The specific issues are:

- CSS styling of messages no longer works
- Some methods are missing, e.g. `groupCollapsed` and `table`

It looks like BN v2.0.10 is changing the `Zotero.getMainWindow().console` object to something slightly different. In the below video, I start with v2.0.9 and show that `console` is as expected. Then I upgrade to v2.0.10 and show that `console` has changed.

https://github.com/user-attachments/assets/839e4676-bb8f-4a7a-b426-18a146d19147

### Debug Output

```
[JavaScript Error: "TypeError: console2[prop] is not a function" {file: "jar:file:///Users/dvanoni/Library/Application%20Support/Zotero/Profiles/sh91zsq8.default/extensions/notero@vanoni.dev.xpi!/content/notero.js" line: 1426}]
get/<@jar:file:///Users/dvanoni/Library/Application%20Support/Zotero/Profiles/sh91zsq8.default/extensions/notero@vanoni.dev.xpi!/content/notero.js:1426:27
onCommand@jar:file:///Users/dvanoni/Library/Application%20Support/Zotero/Profiles/sh91zsq8.default/extensions/notero@vanoni.dev.xpi!/content/notero.js:3109:20


appName => Zotero, version => 7.0.7 (x64), os => macOS 15.0, locale => en-US, extensions => Notero (0.6.4, extension), Better Notes for Zotero (2.0.10, extension), Zutilo Utility for Zotero (3.10.0, extension, disabled), ZotFile (5.1.2, extension, disabled), Mdnotes for Zotero (0.1.3, extension, disabled), Night for Zotero (0.4.23, extension, disabled), Better BibTex for Zotero (6.7.240, extension, disabled)
```

**Comment by windingwind** [comment]
Thanks for letting me know. I’ll check
