### ISSUE TITLE
[Bug] 同步会卡住

### ISSUE THREAD

**Issue by unscrewnk** [windingwind/zotero-better-notes#1158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 23H2
- Zotero Version: 7.0.8-beta.2+237a2e5b8 (64-bit)
- Plugin Version:2.0.12-2.0.14

### Describe the bug

使用模板生成的条目笔记可以正常导出并同步，当导出没有模板的所有笔记时，md文件没有输出，但是附件会同步过去，同步管理器日期显示为1970年，且后续所有文件都无法同步，重启zotero后条目笔记可以重新同步，更新插件版本、无法解决，排查发现重置file header模板可以解决，使用现有模板时，导出时选择不生成yaml依然会卡住
![image](https://github.com/user-attachments/assets/5946e28d-2967-46ba-be4e-5345ae3c6d6a)
![image](https://github.com/user-attachments/assets/3caa8ac7-ed9b-48d3-a379-2143b192c922)
![image](https://github.com/user-attachments/assets/01fa8a87-b0a6-431a-809d-22f2847adcae)

### Debug Output
选中三个文件同步
[bug.txt](https://github.com/user-attachments/files/17348420/bug.txt)

**Comment by windingwind** [comment]
同步模式下必须使用yaml头，因此若相关模板不正确则自然无法正常导出并同步。

**Comment by windingwind** [comment]
不应假设noteItem一定有parentItem，请更正你的模板

**Comment by unscrewnk** [comment]
> 不应假设noteItem一定有parentItem，请更正你的模板

好的，谢谢，已经解决了
