### ISSUE TITLE
[Help Wanted] Looking for Collaborators to Maintain Documentation

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#116]
Hi,

I’m the author of this Zotero plugin(Better Notes). I’m looking for collaborators who could help me with maintaining documentation.

There have been a lot of important changes and bug fixes since the plugin is published, but the documentations(README, template usage, template development, and user guide) are out-of-date. Some of these docs even contain misleading information.

However, I don’t have much time to maintain the documentation. In the last few months, I try to respond to bug reports and feature requests as quickly as possible. These activities took up most of my free time.

If you are using this plugin and willing to help with the documentation, please reply here or contact me at wyzlshx@foxmail.com. Do not require any programming skills!

Sincerely,
winding

**Comment by windingwind** [comment]
We also plan to maintain a Chinese version of the documentation.
我们也计划维护一份中文版本的文档。如有意愿，也欢迎在此留言或联系我。

**Comment by benytzlich** [comment]
hi is there a already a course of action in place and framework, that could help me to navigate the update of the documentation? I still learn all the functions and applications of the addon, and i dont know if that would help then?

**Comment by windingwind** [comment]
@benytzlich 
Thanks for your interest. I’ve published a Chinese version of document last week here: https://w6zjinn49j.feishu.cn/wiki/space/7132878100186087428?ccm_open_type=lark_wiki_spaceLink

In the next few weeks, I’ll update and merge the doc to GitHub README.

If you have interest on helping me maintaining documentation(mainly on GitHub), you could help me do some updates to the README when there are new features, or maintaining the Chinese doc mentioned above.

**Comment by windingwind** [comment]
done
