### ISSUE TITLE
[Feature] 附件文件夹

### ISSUE THREAD

**Issue by unscrewnk** [windingwind/zotero-better-notes#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win 11 23h2
- Zotero Version: 
- Plugin Version:

### Describe the feature request

现在似乎附件文件夹只能放到同步的文件夹下方，可否自由选择在obsidian库中的存放位置

### Describe the solution you'd like

。

### Anything else?

。

**Comment by unscrewnk** [comment]
> 你想放在哪里

比如说我zotero笔记导出实在文献笔记文件夹，附件就一起在这里，obsidian设定的附件文件夹在config/attachments，现在是
![image](https://github.com/user-attachments/assets/7af1b9b7-3346-4a16-97f5-cbb65a20039a)
![image](https://github.com/user-attachments/assets/692c5916-5836-4b3c-9af2-f713cc4d4606)
我想的是直接遵循obsidian的路径

**Comment by windingwind** [comment]
config文件夹和你的导出文件夹是什么关系

**Comment by unscrewnk** [comment]
> config文件夹和你的导出文件夹是什么关系

不同路径，obsidian库的附件、模板之类我都放在config，现在导出笔记的附件是独立的

**Comment by PhDrc-G** [comment]
使用markdown语言做的表格好像不能正确的生成在笔记中，同时双击打开笔记文件是空白的，只有在单独的窗口编辑时是正常显示的

**Comment by windingwind** [comment]
> > config文件夹和你的导出文件夹是什么关系
> 
> 不同路径，obsidian库的附件、模板之类我都放在config，现在导出笔记的附件是独立的

目前只支持相对路径，不支持附件目录的绝对路径
