### ISSUE TITLE
[Feature] Parameterising specific synchronization rules

### ISSUE THREAD

**Issue by DesmetQuentin** [windingwind/zotero-better-notes#1162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Linux Ubuntu 22.04.4 LTS
- Zotero Version: 7.0.7 (64-bit)
- Plugin Version: 2.0.16

## The problem

I am using the plugin with synchronization with my Obsidian vault (in Markdown) and there are several things that do not work well when synchronizing. For instance, when using Wikilinks (with the syntax `[[link]]`) in Obsidian, synchronization in Zotero transforms the first double brackets into `\[\[`, which breaks the link on the Obsidian side. Another example is just about esthetics: the bullet points are rendered with `*   ` (three spaces) in md, when I'd rather put `- ` (a dash and one space).

## The feature

A natural solution would be to have somewhere in the settings of Zotero Better Notes, a section with the possibility to change the defaults conversion behaviors, for the several exporting type you propose (md in my case). For the two examples I provide, I think there could be in the md section a bullet point setting where one could enter in a form the string to use (in my case: `- `, while the default would be `*   `), and for specific character patterns like with the Wikilinks, the user could add as many as needed in a list of patterns to keep unchanged (in my case, I'd put: `[[`, `]]`).

I hope this makes sense. And if there is already a way to do that, I'd be happy to hear about it.

**Comment by windingwind** [comment]
You can use the ExportMDFileContent template to customize the note2markdown parsing. I believe there are some similar ones available in the discussions.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/646

https://github.com/windingwind/zotero-better-notes/discussions/768

**Comment by DesmetQuentin** [comment]
Ok, it's very great now! Thank you very much! I am now using the following:

``` js
${{
  return mdContent.replaceAll("\\[\\[", "[[").replaceAll("*   ", "- ").replaceAll("--", "–").replaceAll("->", "→").replaceAll("“", '"').replaceAll("”", '"');
}}$
```
