### ISSUE TITLE
[Bug] 无法将pdf的英文原文粘贴到笔记

### ISSUE THREAD

**Issue by guaguastandup** [windingwind/zotero-better-notes#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.4.1
- Zotero Version: 7.0.0-beta.104+7e01a7d0e
- Plugin Version: 2.0.16

### Describe the bug

在pdf中复制的英文原文，无法粘贴到笔记中
![problem1](https://github.com/user-attachments/assets/efa8a1f3-c678-4b0a-bfb3-4e1255e14eef)

### Debug Output

1729239925009	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

1729239925841	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1723}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

appName => Zotero, version => 7.0.0-beta.104+7e01a7d0e, os => macOS 14.4.1, locale => zh-CN, extensions => Better Notes for Zotero (2.0.16, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Duplicates Merger for Zotero (1.1.5, extension, disabled), Jasminum (1.0.0-14, extension, disabled), Ethereal Reference (0.7.5, extension, disabled), Awesome GPT (1.0.5, extension, disabled), Ethereal Style (5.1.5, extension, disabled), Translate for Zotero (2.0.4, extension, disabled)
(3)(+0027584): Running /usr/bin/sw_vers '-productVersion'

(3)(+0003613): Starting full-text content processor

(4)(+0000002): Registering notifier observer 'fulltext_e5' for [sync]

(4)(+0002909): Registering notifier observer 'tagsBox_Qq' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_2Q' for [item]

(4)(+0000001): Registering notifier observer 'noteEditor_Lu' for [item,file]

(3)(+0000000): Reloading tags box

(3)(+0000124): Using a custom CSS style:

(3)(+0000000): .output_wrapper { font-size: 16px; color: #3e3e3e; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", "Microsoft YaHei", Arial, sans-serif; } li { margin-bottom: 0.5em; /* color:#159957; */ } .code_size_default { line-height: 18px; font-size: 14px; font-weight: normal; word-spacing: 0px; letter-spacing: 0px; } .code_size_tight { line-height: 15px; font-size: 11px; font-weight: normal; word-spacing: -3px; letter-spacing: 0px; } a { text-decoration: none; color: #1e6bb8; word-wrap: break-word; } strong { font-weight: bold; } em { font-style: italic; } del /* 删除线 */ { font-style: italic; } strong em /* 强调的斜体 */ { font-weight: bold; } hr { height: 0.91px; margin: 1.5rem 0px; border: none; border-top: 1px dashed #A5A5A5; } code /* 行内代码 */ { word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; color: #e96900; background: #f8f8f8; } a, a:visited { /* 普通状态和访问过的链接 */ color: #42B983; /* 深绿色 */ text-decoration: underline; /* 下划线 */ } a:hover, a:focus { /* 鼠标悬停和聚焦状态 */ color: rgba(255, 69, 0, 0.5); /* 更深的绿色 */ } blockquote { border-left: 4px solid #4caf50; /* 鲜明的绿色边界 */ background-color: #e8f5e9; /* 浅绿色背景 */ color: #2e7d32!important; /* 引用文本的深绿色 */ padding: 0.01px!important; /* 内边距 */ margin: 0px 0!important; /* 减小上下外边距 */ } /* 如果您想让所有设置为加粗的文本都变成橙红色，可以使用以下通用规则 */ b, strong { font-size: 1em; color: rgba(255, 69, 0, 1); /* 橙红色 */; background-color: #f0f0f0; /* 淡灰色背景 */ padding: 2px 4px; /* 加点内边距让背景更明显 */ border-radius: 2px; /* 可选：为背景添加圆角 */ } h1, h2 { letter-spacing: 2px; margin-bottom: 2em; margin-right: 5px; padding: 8px 15px; border-radius: 5px; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); /* 文字阴影，增强对比 */ box-shadow: 1px 1px 2px rgba(51, 51, 51, 0.5); /* 盒子阴影，可根据需要调整 */ text-align: center; } h1 { font-size: 1.2em; border-left: 10px solid rgba(240, 19, 19, 0.5); /* 可以根据需要调整边框颜色 */ background: rgba(240, 19, 19, 0.25); } h2 { font-size: 1em; border-left: 10px solid rgba(102, 204, 153, 0.5); /* 可以根据需要调整边框颜色 */ background: rgba(102, 204, 153, 0.25); } ol, ul { padding-left: 16px; } ol { counter-reset: item; /* 重置计数器 */ } ul li, ol li { list-style-type: none; /* 移除默认列表标记 */ position: relative; color: red; /* 默认颜色 */ } ul li:before { content: '•'; position: absolute; left: -25px; font-size: 22px; color: currentColor; transform: translateY(-15%); } ol li:before { content: counter(item) '.'; counter-increment: item; position: absolute; font-size: 0.9em; left: -20px; color: currentColor; } /* 根据嵌套层级改变颜色 */ ul li ul li, ul li ol li, ol li ul li, ol li ol li { color: blue; } ul li ul li ul li, ul li ul li ol li, ul li ol li ul li, ul li ol li ol li, ol li ul li ul li, ol li ul li ol li, ol li ol li ul li, ol li ol li ol li { color: green; } /* 调整嵌套列表的缩进 */ ul ul, ol ol, ul ol, ol ul { padding-left: 2em; /* 子列表的缩进大于父列表 */ } /* 为表格设置边框样式 */ table { border-collapse: collapse; width: 100%; table-layout: fixed; /* 让列宽更均匀 */ } table th:first-child, table td:first-child { width: 30%; font-size: 0.9em; text-align: center; vertical-align: middle; } table th:nth-child(2), table td:nth-child(2) { width: 70%; font-size: 0.8em; text-align: left; } table th { font-size: 1.3em!important; text-align: center!important; font-weight: bold!important; border: 2px solid black; padding: 5px; color: #1e6bb8!important; background-color: rgba(21, 100, 178, 0.1); } table tr:nth-child(2n) { background-color: #F8F8F8; }

(3)(+0000008): Getting contents of jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(3)(+0000058): HTTP GET jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000002): Getting contents of jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(3)(+0000062): HTTP GET jar:file:///Users/zhangxinyue/Library/Application%20Support/Zotero/Profiles/nq2y6e9g.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css succeeded with 200

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000049): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0005239): Using note template:

(3)(+0000001): <blockquote style="color:black"> {{if comment}} <p>{{comment}}</p> {{end if}} 📖原文: {{highlight}} <br/> 📌引自: {{citation}} </blockquote>

(3)(+0002545): Writing reader state to /Users/zhangxinyue/Zotero/storage/JXHX252C/.zotero-reader-state

(3)(+0000208): Using note template:

(3)(+0000000): <blockquote style="color:black"> {{if comment}} <p>{{comment}}</p> {{end if}} 📖原文: {{highlight}} <br/> 📌引自: {{citation}} </blockquote>

(3)(+0022305): Getting contents of /Users/zhangxinyue/Library/Application Support/Zotero/Profiles/nq2y6e9g.default/treePrefs.json

(3)(+0000003): Writing column prefs of length 11673 to file /Users/zhangxinyue/Library/Application Support/Zotero/Profiles/nq2y6e9g.default/treePrefs.json

**Comment by windingwind** [comment]
原文没复制上吧，请检查剪贴板

**Comment by guaguastandup** [comment]
> 原文没复制上吧，请检查剪贴板

![2](https://github.com/user-attachments/assets/b34913b8-b77e-4b3a-b4d7-e3c1dd3795c3)
复制上了，可以看右上角maccy软件的提示。

刚才更新了zotero版本到最新，还是一样的。

复制粘贴内容：
nd importance to surface the records needed to inform the agent’s moment-to-moment behavior. The second is reflection, which synthesizes memories into higherlevel inferences over time, enabling the age

**Comment by guaguastandup** [comment]
> 录屏看下吧，截图看不出来。复制粘贴不是插件功能

好的，谢谢，这是我的录屏。

https://github.com/user-attachments/assets/f1f29259-66ab-483e-b500-00e40fef4d62

**Comment by windingwind** [comment]
帮助- restart in troubleshooting mode，然后重试看是否正常

**Comment by guaguastandup** [comment]
> 帮助- restart in troubleshooting mode，然后重试看是否正常

🥺 抱歉，应该是我本地出了什么问题，开了troubleshooting后一开始无法选中文字，过了一会可以选中文字，也可以复制到剪切板，但是没法粘贴到zotero笔记上

**Comment by RivaLei** [comment]
请问开了troubleshooting可以复制，那可以推断是插件的问题吗？如何解决呢？

**Comment by guaguastandup** [comment]
> 请问开了troubleshooting可以复制，那可以推断是插件的问题吗？如何解决呢？

我是开了TroubleShooting也无法复制。
然后我开了TrougbleShooting，在日志里发现，我在添加笔记时调用了noteTemplates，并且这个noteTemplate是我自己以前编辑过的，是我之前尝试使用社区的模版的时候修改的，当时加了一些if else判断语句。

然后我到Advanced Preferences里把这个字段：`extensions.zotero.annotations.noteTemplates.highlight`重置了，把相关的一些template配置也改成默认的，就修复了。

可能是因为之前改了全局的preference，所以卸载插件依然存在这个问题。
