### ISSUE TITLE
[Bug] 做筆記時更新頻繁導致閃屏，及已打到下一行但閃屏後只更新到上一行

### ISSUE THREAD

**Issue by 94Claire** [windingwind/zotero-better-notes#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.8 (64-bit)
- Plugin Version: 7.0.8 (64-bit)

### Describe the bug

感謝開發如此好用的插件！
之前使用 Zotero 6 沒問題，今天升級到 Zotero 7後，做筆記時，筆記更新頻繁，導致閃屏。以及有時候，已打到下一行，但閃屏後只更新到上一行。

### Debug Output

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "popupParent is null" {file: "resource://zotero/note-editor/editor.html" line: 3774}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this.editorView is undefined" {file: "resource://zotero/note-editor/editor.js" line: 6}]

appName => Zotero, version => 7.0.8 (x64), os => Windows 10.0 19045, locale => en-GB, extensions => Better Notes for Zotero (2.0.16, extension), Translate for Zotero (2.0.4, extension, disabled), Notero (0.6.7, extension, disabled), Scite Zotero Plugin (V7+) (2.0.2, extension, disabled), Actions and Tags for Zotero (2.0.3, extension, disabled)

### Anything else?

若是問題出在硬體無法支援頻繁的更新同步，希望可以有手動調整更新同步間隔時間的選項。感謝！

**Comment by windingwind** [comment]
请检查 Settings -> Better Notes -> Sync -> Auto-sync Period 并设置为-1，然后重启Zotero，则关闭了自动同步。然后请尝试是否正常。

若仍有问题，请提供更多信息，例如笔记的内容大小，屏幕截图等。

**Comment by 94Claire** [comment]
感謝提供解方！
關閉自動同步及預覽後，這幾天已無屏閃問題。
不過，在將筆記放入索引筆記時，不確定是否因連結太多，Zotero易停擺、無回應。
（如圖，左方為索引筆記的獨立視窗，右方為各筆記視窗準備複製鏈結）
<img width="960" alt="CaptureZotero-" src="https://github.com/user-attachments/assets/241ab2e7-e79f-4f92-b195-c6aaca8d9369">

**Comment by windingwind** [comment]
感谢反馈。请检查若在单独窗口打开该索引笔记（左侧窗口的右上角`...`按钮->Open in a Separate Window），然后关闭该左侧窗口，然后尝试复制链接到索引笔记的操作，是否还会出现卡顿。

**Comment by FavorMylikes** [comment]
I met the same issue. Restart could alleviate this problem. But it shouldn't be the best solution.

**Comment by windingwind** [comment]
@FavorMylikes If the steps above don't work for you, please start a new issue.
