### ISSUE TITLE
[Feature] When editing LaTeX mathematical formulas, it would be helpful to provide highlighting.

### ISSUE THREAD

**Issue by csdui** [windingwind/zotero-better-notes#1169]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Environment

- OS: MacOS 15
- Zotero Version:7.0.6
- Plugin Version:2.0.17

### Describe the feature request

When editing LaTeX mathematical formulas, it would be helpful to provide highlighting.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
It's not a feature of this plugin, please report to the Zotero forums.
