### ISSUE TITLE
[Feature] LaTeX usepackages

### ISSUE THREAD

**Issue by jmanthony3** [windingwind/zotero-better-notes#117]
Would it be possible to include a `preamble.tex` file containing common usepackages and macros that I am used to, written, or have collected? E.g. if I wanted to annotate that some part of an equation cancels to zero, then I could include the $\LaTeX{}$ usepackage _cancel_ for the `cancelto{}{}` macro.

I am not even sure how the $\LaTeX{}$ is being rendered: I am assuming that a local installation of pdflatex or xelatex is used to render and output to pdf formats? If so, then is there a local directory that a `preamble.tex` could be included? If everything is rendered with MathJax, then is there a way to import MathJax libraries for similar functionality?

So instead of this:
![image](https://user-images.githubusercontent.com/62029937/184889934-6b3c78fa-9dcb-43f2-8bca-80cfb1e40e10.png)

I would like to see this:
![image](https://user-images.githubusercontent.com/62029937/184890676-7c640b51-f353-4706-964f-a54d701923ed.png)

**Comment by windingwind** [comment]
The LaTex rendering is based on MathJax. It does not support `\usepackge`.
However, MathJax provides many extensions to support commonly used LaTex macros. The cancelto is here:
https://docs.mathjax.org/en/latest/input/tex/extensions/cancel.html

In the latest version, I've migrated from `tex-svg.js` to `tex-svg-full.js`, which should support the cancel macros. Please update and try.

If the package you want to use is not loaded automatically, please use `\require{package_name}`. Supported packages are here: https://docs.mathjax.org/en/latest/input/tex/extensions/index.html

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/184924183-c892f695-10dd-4bf5-8aed-413ffacddfb5.png)

**Comment by jmanthony3** [comment]
Thank you, @windingwind! I have updated and am able to successfully render!

![image](https://user-images.githubusercontent.com/62029937/184925384-1dc0b242-23bb-4900-95de-bd3304e067c9.png)
