### ISSUE TITLE
[Bug] 添加Text后选择的字号大小和颜色不能沿用

### ISSUE THREAD

**Issue by OUTHIM** [windingwind/zotero-better-notes#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7
- Plugin Version: 2.0.18 

### Describe the bug

Hi！感谢您开发的插件，真的很好用！

有一个问题是在使用"添加text"功能，选择了字号大小和颜色后，下次再次使用时字号大小和颜色又会恢复默认。

对于其他类似高亮，区域等功能，选择的颜色都会被保存，这样会方便很多。

因此希望能够对“添加text"功能也支持保存字号和颜色！

谢谢！

### Debug Output

省略

**Comment by windingwind** [comment]
不太理解。可参考https://forums.zotero.org/discussion/86855/make-note-editor-beautiful

**Comment by windingwind** [comment]
非插件功能，故此关闭
