### ISSUE TITLE
[Feature] 通过加标签的方式自动将每条笔记归类到一个页面下

### ISSUE THREAD

**Issue by tangjyan** [windingwind/zotero-better-notes#118]
我个人理解这个插件相比于zotero自带的笔记就是更进一步做好了各笔记的管理分类整理，可以通过顶部logo自动选择当前笔记位于哪个子标题下方。但是如果可以通过标签，或者说双链实现是否更简单呢？

比如说这条笔记我要放到 #主笔记 的 ##论文笔记 下，用你的方式是需要鼠标点选。那如果我直接在标题中或者其他位置输入 [[论文笔记]] 或者 #论文笔记 ，通过反链的方式自动汇总。之后我只需要在主笔记中，将这些标签进行适当的排列就可以了。

附一篇类似观点的文章 [双向链接时代的快速无压记录]( https://www.yuque.com/deerain/gannbs/ffqk2e)

**Comment by windingwind** [comment]
谢谢分享，关于双链的形式，其实是我在规划这个插件的时候思考的第一个问题，也是一直在思考的问题。非常高兴能够讨论。

## 设计功能时考虑的要素
首先我想说明，我是一个轻/中度笔记用户，因此可能并不会像分享的文章作者对笔记的各种工具或理论有深刻的理解和实践。因此也非常欢迎来自任何比我更具经验的用户的意见和批评。

另一方面，我不是任何笔记/文献管理/的工具/理论的坚定支持者，因此设计插件的时候不会考虑太多现有的理论和笔记哲学。作为插件开发者，在考虑**引入新功能**时对我的重要性依次是：
- 核心功能稳定可用
- 实现简单快速
- 可维护性与可扩展性
- 界面、操作等用户体验与用户习惯
- 诸如笔记哲学之类的其他因素

这可能和大多数用户的考虑顺序是相反的。因为作为开发者，如果无法维护或者需要很长时间实现新功能，是非常不利的。希望能够理解。

## 插件做了什么

核心功能如你所说，是：
- 为了在zotero内实现双链的一套底层功能
- 笔记的分类整理，或称双链
- 在上述功能的基础上，包装了一些其他增强性的笔记功能（latex，导出，同步，模板等），将内置笔记补全为一个勉强合格的兼容markdown和标记语言（富文本）编辑器。

后两点是并列的。对于大多数用户而言，双链仅仅起到链接归纳的作用，可能第三点更加有用（尤其考虑到很多zotero用户是非理工专业，对markdown的代码式语法不熟悉或抗拒）。我收到的大多数功能请求也是关于第三点。

除了上述三点以外，我认为最重要的但也最被忽视的另一个核心功能是对zotero的文献（元数据，批注，标签等）等轻松使用或关联。这个功能主要实现是zotero本身，但如果没有Better Notes，使用这些功能相对复杂（例如obsidian的zotero集成）或可做的事情很少（zotero内置笔记本身只能简单插入批注）。

## 双链功能设计思路

最初有三种选择：
- zotero自带的related item功能（无法跨库链接，放弃）
- 类obsidian方案（即你说的标签方案，需要重新设计zotero笔记编辑器/进行大量修改，放弃）
- url scheme方案（现行方案）

出于实现简单且使用上直观的考虑（如上所述，zotero很大一部分用户对markdown语法不熟悉，对word类型的超链接熟悉），最终实现的是超链接方案。


## 是否可以做标签式双链

现在基础功能已经稳定下来，我同意是时候回顾一下是否可以实现其他方式的双链。我认为obsidian风格的双链是可行的。以下是我的想法，欢迎探讨。

### 实现思路
为开启ob风格双链的集合内的每一个笔记的修改进行监听，若有[[tag]]，则会在同一集合下具有对应标签/具有相同标题的笔记（一或多个）行末加入当前笔记的链接（为方便转跳，仍使用链接形式）。同时当前笔记末尾添加回链。
为避免重复链接，当前笔记与目标笔记的related item将互相添加。

欢迎讨论。确定细节后将作为下一阶段的主要开发目标。

**Comment by tangjyan** [comment]
我说一个常见的场景：
在看论文的时候，假设要有一个笔记是`论文佳句学习`，那么其中有 `摘要`、`引言`、`方法`……之类的块、段落或者说是子页面。当我看论文句子的时候高亮了一个句子，zotero就会自动生成一个注释，我希望的场景就是我在这个注释下添加一个`方法`标签，那么这条笔记会自动汇集到`方法`之下，而且应该是句子本身，而不是`Annotation`这样无含义的标题。这样每一个标签下面都是一篇完整的内容汇总。

当然这些标签也可以是各种方法，算法，实验等等。只要把这些标签在主笔记中分门别类的整理好，那就OK了。

**Comment by windingwind** [comment]
@tangjyan 看起来有一些误解：
1. 自动将高亮/批注加入主笔记，目前这一功能开关在编辑菜单栏下。关于按标签归类是很好的建议，不过触发条件就从`添加批注`变成`为批注添加标签`。可以设置为另一个功能。
2. “应该是句子本身，而不是Annotation这样无含义的标题”：这是由QuickNote模板控制的，实际上标题可以是任意内容。由于开发早期底层功能的限制，默认的QuickNote模板为所有插入的笔记添加了首行“Annotation”。将在下一版本中更改为QuickNoteV2模板，修复这一问题。

相比自动将高亮/批注加入主笔记，我更偏好先从批注创建一个笔记，经过修改再链接。相比直接添加批注，更能利用“双链”的优势。当然两种使用方法都是支持的。

**Comment by tangjyan** [comment]
> 相比自动将高亮/批注加入主笔记，我更偏好先从批注创建一个笔记，经过修改再链接。相比直接添加批注，更能利用“双链”的优势。当然两种使用方法都是支持的。

这就是一个粒度问题了。笔记有时候是一篇文章中的一句话，有时候也可以是一篇文章中自己阅读后总结出来的一段话，或几段话。不过这些都不影响使用标签双链自动归类。

这个话题还是挺大的，希望有更多的用户一起来讨论。看看大家的使用场景是怎样的。

**Comment by windingwind** [comment]
@tangjyan 
已更新版本。QuickNote模板已不再使用，目前的QuickNoteV2模板接替其功能，在pdf阅读器界面的左侧批注栏中的花形插件图标点击时从选择的批注创建快速笔记。
目前其默认行为是：
- 若批注无comment（评论），则直接将批注内容加入快速笔记；
- 若有comment，将解析comment的markdown语法并加入快速笔记，然后将批注内容加入快速笔记。
- 继承批注的tag。

因此上述Annotation标题将不再出现。

**Comment by windingwind** [comment]
> > 相比自动将高亮/批注加入主笔记，我更偏好先从批注创建一个笔记，经过修改再链接。相比直接添加批注，更能利用“双链”的优势。当然两种使用方法都是支持的。
> 
> 这就是一个粒度问题了。笔记有时候是一篇文章中的一句话，有时候也可以是一篇文章中自己阅读后总结出来的一段话，或几段话。不过这些都不影响使用标签双链自动归类。
> 
> 这个话题还是挺大的，希望有更多的用户一起来讨论。看看大家的使用场景是怎样的。

如果要实现“一句话”粒度的自动双链，则需要同时监听笔记与批注。另外，由于zotero本事具有标签功能，我感觉并不需要完全按照ob风格在正文中输入tag，而是使用zotero的标签系统替代之？这样更有利于搜索等其他内置功能。

**Comment by tangjyan** [comment]
> 



> * 若批注无comment（评论），则直接将批注内容加入快速笔记；
> * 若有comment，将解析comment的markdown语法并加入快速笔记，然后将批注内容加入快速笔记。
> * 继承批注的tag。

太帅了，这已经实现我想引用一句话的目的了。

**Comment by tangjyan** [comment]
> 而是使用zotero的标签系统替代之？

Zotero的标签好像锚点是一则笔记，当然把每句话都当成一个独立的笔记也可以。但是不知道能不能实现按标签自动归类的功能。还有在主笔记中展示的笔记是否也应该显示 标签？

**Comment by windingwind** [comment]
需要澄清的是目前该快速笔记操作仅会将批注创建为一条笔记，但不会将该笔记链接到主笔记。我认为将“根据标签自动链接笔记”功能与这个快速笔记操作相结合是比较合适的。相比监听所有批注的修改，此途径在实现上也更加简洁。近期将在该操作上先尝试实现“根据标签自动链接”功能。

所有item（条目，附件，笔记，批注）均可有标签，且支持按标签归类（批注除外），可在条目视图的左下角根据标签筛选笔记、条目、附件等。

主笔记中展示笔记可以显示标签，我认为最简单的做法是修改QuickInsert模板，其控制插入链接到主笔记的行为。默认行为是一行子笔记的链接，当然也可以加上子笔记的标签等等信息。

大多数双链相关的核心功能我均使用模板来增加灵活性。对普通用户而言，模板设置是无感的；对寻求自定义的高级用户而言，模板可以实现几乎任何功能。

**Comment by tangjyan** [comment]
> 所有item（条目，附件，笔记，批注）均可有标签，且支持按标签归类（批注除外），可在条目视图的左下角根据标签筛选笔记、条目、附件等。

我大概理解了你的意思，但是在传统的标签体系中，所有的标签都是平等的。在标签面板中，标签与标签之间是没有拓扑关系的。但是在实际中，标签与标签肯定是有一定关系的，聚类、层级、关联、排序等等。如果是自带的标签应该是实现不了这种关系的。但是如果使用双向链接，#标签 和 [[双链]]是等价的，都是一个页面，其他标签也可以被放置到另一个标签中。或者在主笔记中，我可以按照自己的方式管理标签的层级，而不是zotero自带的标签面板中平铺直叙。

**Comment by windingwind** [comment]
是的，我同意标签之间没有关联是阻止其用于双链的主要缺陷。但内置的标签在搜索以及筛选上也具有重要作用，如果能够两者结合比较好。
我的想法是：
ob风格是在正文里写某种格式的内容，例如[[]]，作为标签。在zotero中，完全也可以把这个字段写在标签栏，这样就可以利用好标签功能。在新增以#开头的标签时，即会在主笔记对应段落插入链接，和点击花形图标效果相同。

**Comment by windingwind** [comment]
将在下一版本更新该功能。已预发布。
具体用法详见https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/yxpiew

**Comment by tangjyan** [comment]
> 将在下一版本更新该功能。已预发布。 具体用法详见https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/yxpiew

试用了一下，虽然和我想象的不是很相同，但是也非常棒了，结合了zotero自身的标签系统，说不定会增加笔记的通用性。
