### ISSUE TITLE
[Feature] AsciiDoc Support

### ISSUE THREAD

**Issue by jmanthony3** [windingwind/zotero-better-notes#119]
I noticed that one could copy/paste large chunks of MarkDown text from the clipboard into a Zotero note (see screenshot below). Would it be possible to also copy/paste text written in AsciiDoc which is a more standardized markup language without weird flavors?

![image](https://user-images.githubusercontent.com/62029937/185204495-e6a00e06-0fac-463b-b8d5-ed93518264b6.png)

**Comment by windingwind** [comment]
Hi, could you please share an example of the ‘AsciiDoc’?

**Comment by jmanthony3** [comment]
The screenshot below is from one of my class notes in AsciiDoc ([here](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) is a quick reference to the syntax of the language).
![image](https://user-images.githubusercontent.com/62029937/185405723-fee8fc17-5c67-4bd3-b182-bae3976574be.png)

**Comment by windingwind** [comment]
I'll try to find if there is something like asciidoc2html on Github we can use.

**Comment by windingwind** [comment]
I found a solution https://www.npmjs.com/package/asciidoctor. Hope it works.

**Comment by windingwind** [comment]
Please update to v0.6.27
