### ISSUE TITLE
[Bug] The magic key donot support click by mouse

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11
- Zotero Version: 7.0.9
- Plugin Version: 2.1.1

### Describe the bug

新功能魔法键`/`使用键盘可以非常方便的调用，但是如果我用`/`调用其魔法键的选项，再用鼠标左击，该功能无反应，且`/`保留在光标处，不止是特别设计还是小bug

### Debug Output

none

**Comment by windingwind** [comment]
没有很理解什么意思。可以通过
1. 按esc
2. 按ctrl+z
3. 光标回到笔记，继续输入内容

三种方式关闭弹窗

**Comment by windingwind** [comment]
是每个选项都无法使用吗？请提供一下debug output方便排查问题

**Comment by ramonmi** [comment]
> 是每个选项都无法使用吗？请提供一下debug output方便排查问题

是的，每个选项用鼠标点击都没反应。debug output中记录了两个操作，一是`/`调用弹窗，鼠标点击插入引用，无反应；而是`/`调用弹窗，键盘导航至引用，按`enter`，操作成功。

[Debug Output.txt](https://github.com/user-attachments/files/17731063/Debug.Output.txt)
