### ISSUE TITLE
[Bug] Exporting Markdown adds unwanted escape characters i.e. '\'

### ISSUE THREAD

**Issue by gjdreisbach** [windingwind/zotero-better-notes#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version:  7.0.9
- Plugin Version: 2.1.4

### Describe the bug

I have a specific setting for the extensions.zotero.annotations.noteTemplates.highlight setting in the editor config to export annotations in a specific way such that obsidian renders them the way I want by creating annotation blocks (I use this obsidian plug in https://github.com/javalent/admonitions).  This setting works properly when I create a note from annotations using better notes (i.e. the code blocks appear properly), but when I attempt to export them to markdown, escape characters are added that negates the rendering in obsidian. 
![image](https://github.com/user-attachments/assets/3f309a1d-56ad-4f8a-b284-df3377fe2fe6)

![image](https://github.com/user-attachments/assets/b255f5d7-f4ad-4380-9011-53547d4a888c)

### Debug Output

1. Have codeblock in better notes note using ``` character 

i.e. 
``` text
```

2. export note to markdown using better notes exporting tool
3. open exported note in obsidian
4. You will see it instead becomes
\`\`\` text
\`\`\`  
5. This stops obsidian from rendering the code block

### Anything else?

More than happy to provide any other information you may need.  If this is simply a hidden setting I can change too I am more than happy to do so. 

thanks!

**Comment by windingwind** [comment]
Please take a screenshot of your note in Zotero. The code block should not be converted to characters with slashes.

The zotero note is never a markdown note, and thus three back quotes in the note are not recognized as valid syntax. In that case, please use `<code></code>` instead.

**Comment by gjdreisbach** [comment]
![image](https://github.com/user-attachments/assets/925c2003-a8e7-45f2-8f70-46321238f409)

This is a picture of my note in zotero.  Maybe it's relevent but I created this note via the command "Create note from annotations" within zotero and it ends up like this, with no back ticks.  Do you think that has something to do with it?

with regards to <code></code> are you saying that should be in my highlight export setting instead of three back ticks? That would make sense.

appreciate all your help on this.  Its a super cool tool and just want to make my workflow work with it

**Comment by windingwind** [comment]
Yes.

A valid code syntax in the note should look like this, and it does not support the `ad-method` attribute.


<img width="426" alt="image" src="https://github.com/user-attachments/assets/d1f0e9e7-382e-4d7c-bb9a-e56ffb15f791">


But anyway, if you really want to do it this way, you can edit the `ExportMDContent` template of this plugin to remove the slashes with regex.

**Comment by gjdreisbach** [comment]
Great idea with the regex.  Managed to get that to work so I am all good now thank you very much!

**Comment by jay-tux** [comment]
@windingwind is there an option to specify the language of a code block in the plugin? I'm using Obsidian with mermaid graphs (which render perfectly fine in Obsidian), but the better-notes sync throws the language away, leaving me with just the textual form for the graph. Is there a possibility to either a) retain this information, or b) have the sync be Obsidian->Zotero only?

**Comment by windingwind** [comment]
@jay-tux it does not support language, as mentioned above.

> retain this information

no

> sync be Obsidian->Zotero only

then it's not a sync. use the import from markdown
