### ISSUE TITLE
Cannot show the preview panel

### ISSUE THREAD

**Issue by BenjaminDbb** [windingwind/zotero-better-notes#12]
I found there may be an addon bug in the macOS.
The preview panel cannot be displayed correctly.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/24951668/168508806-bdea21fe-b3cf-46e2-bd8c-20535085ce5b.png">

**Comment by windingwind** [comment]
The preview only shows content after you open a note link.

**Comment by windingwind** [comment]
I'll close this issue, as there have been many significant updates.
Feel free to open it again.
