### ISSUE TITLE
[Bug]Linking Note to workspace can not work correctly on Mac(M1)

### ISSUE THREAD

**Issue by Dai-ge** [windingwind/zotero-better-notes#120]
System and device: Mac(M1)
Version of Plugin: 0.6.25

This button should add link of the current note to the main note
<img width="386" alt="image" src="https://user-images.githubusercontent.com/57291510/185434353-1223a383-c4b8-419e-a381-87d01c6a8093.png">

However, after clicking it, it will only add a main note link in the current note, and this link is unusable in current note, it can not direct the user to the main note. And the setted main note is empty and there is no link of the current note.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/57291510/185434808-2885a641-0918-4077-9bc9-0498314779fa.png">
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/57291510/185435342-c6f553a0-9ee5-49eb-9c9d-7a1a10419d22.png">

**Comment by windingwind** [comment]
Could you please check Edit->Note Template Editor->[QuickInsert] and post a screenshot?

**Comment by Dai-ge** [comment]
Do you mean a screenshot like this one?
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/57291510/185452229-44f45600-17d0-4357-a52e-8ba31f2ba1b9.png">

**Comment by windingwind** [comment]
This bug happens when the note editor of the main note was once activated and destroyed later, because it's not correctly removed from the editor instance list.
I've fixed this bug in the latest release.

**Comment by Dai-ge** [comment]
Great,Thank you!
