### ISSUE TITLE
[Bug] Exported Better notes not detected in the Sync manager and cannot sync

### ISSUE THREAD

**Issue by jamadab** [windingwind/zotero-better-notes#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 23H2
- Zotero Version: 7.0.9 (64-bit)
- Plugin Version:2.1.6

### Describe the bug

First, very many thanks for the amazing plugin. I am new to the plugin and unfortunately I cannot sync my BN. 

I export the BN into a BNFolder  within the obsidian vault (Export current note > keep note links (I check sync notes and YAML) > use system export > select Markdown > BNFolder).  However, when I open the BN sync manager > Detect, it does not detect/show the BN in the BNFolder (it says 0 new notes hence no notes to sync).  In the Zotero, the BN doesnot show the "sync now" also.  Also the BN file name doesnt have the appended codes I usually see on imported BN. Any solution to this?. I have not installed any templates. I have uninstalled and re-installed BN but still no export BN detected in Sync manager and thus no sync. However, i can see the exported BN in Obsidian.

![Screenshot (123)](https://github.com/user-attachments/assets/202a526f-781b-44a9-a839-4b64ab0246f6)
![Screenshot (126)](https://github.com/user-attachments/assets/66fea706-d6b6-4a33-a432-42e9bd7011c8)
![Screenshot (127)](https://github.com/user-attachments/assets/63576175-4ef6-4030-a337-2a44d985f29e)
![Screenshot (128)](https://github.com/user-attachments/assets/204d267c-4b61-4433-96bf-16aa44b2799b)
![Screenshot (129)](https://github.com/user-attachments/assets/5f7bbedd-def8-49ef-aeea-bfc13b98e0cf)
![Screenshot (130)](https://github.com/user-attachments/assets/685a7563-80f5-49f8-baf2-0453b1b76110)

### Debug Output

I have disabled all plugins but still the same issue.

### Anything else?

Nope

**Comment by windingwind** [comment]
`use system export` won't work. Please directly click OK here.

> <img width="268" alt="image" src="https://github.com/user-attachments/assets/3a8dd5dd-1edd-49ce-8223-8dfc955659a0">
