### ISSUE TITLE
[Bug] Sending a child note reference to the main note by selecting a heading does not insert in correct position

### ISSUE THREAD

**Issue by shoeferlin** [windingwind/zotero-better-notes#121]
**Describe the bug**
When sending a child note reference to the main note through the provided shortcut from Better Notes and selecting a heading, the child note is not referenced in the correct place under the selected heading.

**To Reproduce**
1. Go to a child note
2. Hover over the provided shortcut by Better Note (the network icon)
3. Click on the heading where you want to insert the reference to the child note in the main note
4. See wrong insertion: Child note reference is not added in the right place under the correct heading of the main note

**Expected behavior**
Expecting the reference of a child note to appear under the selected heading in the main note

**Screenshots**
![Screenshot 2022-08-23 at 17 08 51](https://user-images.githubusercontent.com/37844541/186195753-51a0aa67-85fc-4e54-a602-2ffada78e69d.png)
Hovering over icon and then selecting heading in a child note
![Screenshot 2022-08-23 at 17 16 37](https://user-images.githubusercontent.com/37844541/186196499-90b6b941-a7d0-4880-8a22-c3a28c3d1d15.png)
Reference is not under the heading "Introduction" but somewhere else

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: Chrome 104
 - Zotero: 6.0.13
 - Better Notes: 0.6.26

**Additional context**
Thanks for the amazing plugin otherwise. Would be super helpful once this is fixed.

**Comment by windingwind** [comment]
I see, it seems to be a feature, not a bug.
Currently, the link(note reference) is inserted at the end of a section.
The Introduction section is like this:

- Introduction(target section)
  - Motivation...(subsection)
  - Problem...(subsection)
  - Proposed...(subsection)

-> end of the target section
- Related Work(next section)

Is there anything I can do to help your need? A possible solution: support pressing `shift` and clicking to insert the ref before the next section or subsection. Any suggestions?

**Comment by shoeferlin** [comment]
Oh, thank you. Would be amazing to support subsections in the future. My workflow is to have the outline of my paper with multiple heading levels in the main note and then linking notes from references into the subsections where they fit.

**Comment by windingwind** [comment]
We support multi level headings. I’m not sure what does ‘subsection’ means? The heading 2+ or the unordered list?

**Comment by shoeferlin** [comment]
Sorry, my message was not very clear. Yes, your proposal solution to press `shift` while clicking to insert before the next section or subsection would be amazing! Maybe this could even be default behavior.

**Comment by windingwind** [comment]
> Sorry, my message was not very clear. Yes, your proposal solution to press `shift` while clicking to insert before the next section or subsection would be amazing! Maybe this could even be default behavior.

The shift to insert before section is not supported yet. I’ll let you know when it’s ready. Thanks for your suggestion!
Currently, the insert behavior is to put the link at the end of clicked section(before next section of the same level)

**Comment by shoeferlin** [comment]
@windingwind, you are incredible. Thanks! Thank you very much!
