### ISSUE TITLE
[Bug] Insert link button not working

### ISSUE THREAD

**Issue by thesaltydispatcher** [windingwind/zotero-better-notes#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 Home (Build 19045)
- Zotero Version: 7.0.10
- Plugin Version: 2.1.6

### Describe the bug

While working in a note, clicking the "insert link" button does nothing.

### Debug Output

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{dfadb3a2-f7bb-4b65-b92b-159dd8417e21} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

appName => Zotero, version => 7.0.10 (x64), os => Windows 10.0 19045, locale => en-US, extensions => Better Notes for Zotero (2.1.6, extension)

(3)(+0009889): itemTree.render(). Displaying Item Tree

(3)(+0011289): [Better Notes for Zotero] {}

(4)(+0000872): Unregistering notifier observer in notifier with id 'noteWindow_Ol'

(4)(+0000001): Unregistering notifier observer in notifier with id 'noteEditor_Eh'

(3)(+0000001): No pref observer registered for given symbol

(4)(+0000001): Unregistering notifier observer in notifier with id 'tagsBox_ku'

(3)(+0000001): No pref observer registered for given symbol

(4)(+0000000): Unregistering notifier observer in notifier with id 'relatedbox_1y'

(3)(+0006633): Getting contents of C:\Users\pacro\AppData\Roaming\Zotero\Zotero\Profiles\jx1ka5me.default\treePrefs.json

(3)(+0000006): Writing column prefs of length 6439 to file C:\Users\pacro\AppData\Roaming\Zotero\Zotero\Profiles\jx1ka5me.default\treePrefs.json

**Comment by windingwind** [comment]
Could you please provide a screenshot or record of the steps to reproduce?
