### ISSUE TITLE
[Bug] cannot type after typing some math equations

### ISSUE THREAD

**Issue by CSMsamuel** [windingwind/zotero-better-notes#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows 10
- Zotero Version: 7.0.11-beta.3+b5310d5f0 (64-bit)
- Plugin Version: 2.1.7

### Describe the bug

After typing some math equations in the math environment, I cannot type Chinese words(and sometimes also English)(use the Microsoft input method). If I continue to type, zotero will close automatically.

### Debug Output

[Debug output.zip](https://github.com/user-attachments/files/17978834/Debug.output.zip)

**Comment by CSMsamuel** [comment]
Sometimes inline equations like this $f(x)=x+1$ can also trigger this bug.

**Comment by paras-zomby** [comment]
I have same issue too, and but only chinese word, not encounter english case
My OS is Windows 11 and use 2.1.9 goodnotes plugin

**Comment by windingwind** [comment]
This is a bug with some upstream dependency of Zotero, not this plugin. It should be fixed in the recent/following versions of Zotero.

Please stop reporting this bug here.
