### ISSUE TITLE
[Feature] Display the markdown of a given note

### ISSUE THREAD

**Issue by RizzwareEngineer** [windingwind/zotero-better-notes#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Apple M1
- Zotero Version: 7.0.9
- Plugin Version: Latest Stable (as of Dec 3)

### Describe the feature request

I would love for the sidebar display of post-it notes to visually display its Markdown and not just its text. 

**For example:**
Below depicts a post-it note that does have Markdown in it internally but as seen on the sidebar, only text is  displayed.  
<img width="495" alt="Screenshot 2024-12-03 at 11 45 54 AM" src="https://github.com/user-attachments/assets/e9d7133c-1e75-4705-ba8f-6759fa8a1b30">

Only when I click into the post-it note do I see the desired Markdown display as depicted below.
<img width="512" alt="Screenshot 2024-12-03 at 11 42 28 AM" src="https://github.com/user-attachments/assets/7d8db290-e85a-43c7-a58f-5b42d884e8d5">

### Describe the solution you'd like

It would be great if the sidebar display of the given post-it note could display Markdown without me clicking into it.

**Comment by RizzwareEngineer** [comment]
Now that I think about it, I would love for ANY annotation that shows up on the sidebar to also display its Markdown.

**Comment by windingwind** [comment]
The annotation rendering is not controlled by the plugin and thus is impossible to implement. Thankd for the suggestion.
