### ISSUE TITLE
[Feature] Formula rendering

### ISSUE THREAD

**Issue by fengyefengye** [windingwind/zotero-better-notes#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

OS: Windows 11 22H2 
Zotero Version: 7.0.0 
Plugin Version: 2.1.9

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
The Zotero note - taking plugin has an issue with formula rendering. When I copy a formula such as $formula$ and paste it into the notes, it doesn't get auto - rendered. Additionally, for manually - entered formulas, they only get rendered after I manually input a space after the formula. This is a very inconvenient process and disrupts the smooth workflow of taking notes with mathematical formulas. 
**Why do you need this feature?**
Efficient note - taking with formulas is essential. In academic and research settings, we often need to quickly record and review formulas from various sources. The current behavior of the plugin where copied formulas don't render automatically and manual formulas require an extra step of adding a space is time - consuming and counter - productive. We need the plugin to auto - render both copied and manually - entered formulas without these inconvenient extra steps so that we can focus on the content of our notes and the understanding of the formulas more effectively.

### Describe the solution you'd like

I would like the Zotero note-taking plugin to have the following improvements regarding formula rendering: Firstly, for copied formulas, when pasted into the notes, the plugin should automatically recognize the formula format (such as those in LaTeX format wrapped with appropriate delimiters like  '$' for inline formulas). It should then trigger the rendering process immediately without any additional manual operations, so that the pasted formulas are displayed in their proper rendered visual form just like when they are originally presented in other platforms or documents that support formula display. 

Secondly, for manually entered formulas, the requirement of adding a space after the formula to trigger rendering should be removed. Instead, as soon as the user finishes typing the formula within the correct delimiters (e.g., typing '$formula$' completely), the plugin should automatically detect it and render it on the spot. This way, it would provide a seamless and efficient experience for users to input and view formulas in the Zotero notes, making it more convenient for academic, research, and any other work that involves dealing with mathematical expressions. 

Overall, the goal is to make the formula rendering process in the Zotero note-taking plugin as intuitive and automatic as possible, eliminating the current cumbersome and inconvenient steps. 

### Anything else?

![image](https://github.com/user-attachments/assets/6af71d81-37a6-4bdc-ad07-0ded3155149a)

**Comment by fengyefengye** [comment]
zotero公式功能出现bug，当修改已输入的多行公式时造成zetero闪退
$$\begin{aligned}
\mathcal{H} _ {\mathbb{S} _ {r}^{w}}= & -\sum_ {w_ {j} \in \mathbb{S} _ {r}^{w}} \sum_ {s_ {i} \in \mathbb{S}^{c}} P\left$w_ {j}, s_ {i}\right$  \log P\left$w_ {j}, s_ {i}\right$  \\
& -\sum_ {w_ {j} \in \mathbb{S} _ {r}^{w}} \sum_ {s_ {i} \in \mathbb{S}^{c}} P\left$w_ {j}, s_ {i}\right$ \left$-\log P\left$s_ {i} \mid w_ {j}\right$ \right$ ,
\end{aligned}$$
填入上述公式然后渲染完成后修改就会导致闪退，甚至于删除公式后的空格都会导致闪退
而且有个不方便的点是只能识别$$ (此处是空格)而不能识别$$(此处无空格)，导致将其识别为行内公式
![image](https://github.com/user-attachments/assets/11f0ccc4-48b1-4a30-9d94-1766125ce743)
![image](https://github.com/user-attachments/assets/76c95d24-ed86-4ed3-9979-f2ec5529e3fc)

**Comment by windingwind** [comment]
与插件无关，向https://forums.zotero.org/discussions 报告
