### ISSUE TITLE
[Feature] A dedicated shortcut key for the highlighting feature

### ISSUE THREAD

**Issue by fengyefengye** [windingwind/zotero-better-notes#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7
- Plugin Version: 2.1.9

### Describe the feature request

I would like the Zotero note-taking plugin to have a dedicated shortcut key for the highlighting feature. 

### Describe the solution you'd like

For instance, a simple combination like "Ctrl + H" (on Windows/Linux) or "Command + H" (on Mac) could be assigned to quickly activate the highlighting function. When users are reviewing or annotating their notes, they can effortlessly select the text they want to highlight and then use this shortcut key to apply the highlighting immediately, instead of having to navigate through the menu options each time to find the highlighting tool. This would significantly improve the efficiency of using the highlighting feature in the Zotero notes and make the note-taking process more convenient and fluid, especially when dealing with large amounts of text and when quick highlighting of important points is needed for better organization and review of the note content.

**Comment by fengyefengye** [comment]
There are also many shortcut key functions that are needed. For example, clearing the format of copied text. However, it's not possible to customize shortcut keys.

**Comment by windingwind** [comment]
report to https://forums.zotero.org/discussions
