### ISSUE TITLE
[Bug] Lists mysteriously increase indent level and more (but blank) entries

### ISSUE THREAD

**Issue by jmanthony3** [windingwind/zotero-better-notes#123]
I cannot be sure why this occurs, but occasionally lists appear to contain more entries which are blank. Furthermore, for every entry in the list the indent level increases by 1. So while a list should look like this...
![image](https://user-images.githubusercontent.com/62029937/186521740-ac37ee69-d4eb-40f9-9023-c821f7cf49c2.png)

The list looks like this instead...
![image](https://user-images.githubusercontent.com/62029937/186520762-2d445ec4-76b8-4de9-8eda-85ef20270743.png)

This behavior extends to either numbered or bulleted (unordered) lists:
![image](https://user-images.githubusercontent.com/62029937/186521853-a27d0b05-7d54-4838-9493-91b557474cf8.png)

As best I can tell, the severity of occur seems to compound on itself whenever I manually sync with Zotero, but I am not entirely positive:
![image](https://user-images.githubusercontent.com/62029937/186522210-94b7799d-c225-4d80-a382-42d84311966a.png)

EDIT: The issue seems to occur only on lists within a block quote.

**Comment by windingwind** [comment]
So weird. To help me locate the bug:
- Does this happens every time you sync, or happens randomly?
- Does this happens after all plugins are disabled?
- Does this happen when you are writing or using a function of a plugin, or not doing anything at that time?
- What plugins are enabled currently?

**Comment by jmanthony3** [comment]
I was finally able to reproduce the error with repetition. The number of inserted blank lines and indent increase corresponds to the number of times I attempt to directly embed a note into another. I was able to reproduce this with the Better BibTex for Zotero and Better Notes plugins enabled beyond the standard plugins for Microsoft Word and LibreOffice Integrations.

![image](https://user-images.githubusercontent.com/62029937/186671945-a34c1f1d-8b0d-4758-8f1f-88768a1e5fcf.png)

## Process
Before embedding a note, lists within a block quote look like this (as expected):
![image](https://user-images.githubusercontent.com/62029937/186674110-8912be39-3a7c-4cff-886c-9513a6fdd8eb.png)

After embedding a note one time:
![image](https://user-images.githubusercontent.com/62029937/186674225-45d83ef9-3457-451c-a846-c303ea4d665e.png)

After embedding a second note:
![image](https://user-images.githubusercontent.com/62029937/186674350-403e1eaf-b4af-46e5-b47b-35c632b0b3c6.png)

**Comment by windingwind** [comment]
May I ask why you try to embed the note again, as it is already embedded? To preview the content, simply open the note links or preview with corsur on the link.

**Comment by jmanthony3** [comment]
I am not trying to embed the same note twice, but embed two different notes into the same main note.

**Comment by windingwind** [comment]
I get the point. I’ll try to reproduce and fix it soon.
Thanks for your report!

**Comment by windingwind** [comment]
should be fixed after v0.6.29.
