### ISSUE TITLE
[Feature] 如何关闭Ctrl+S保存markdown文件的功能？

### ISSUE THREAD

**Issue by WrRan** [windingwind/zotero-better-notes#124]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

如题。日常使用中，习惯性按Ctrl+S，但并不在笔记编辑界面，并不想自动保存。请问如何关闭该功能。

**Comment by windingwind** [comment]
将在下次更新改为ctrl+shift+s保存

**Comment by windingwind** [comment]
已更新快捷键
