### ISSUE TITLE
[Feature] Improve documentation for exporting notes for bi-directional linking

### ISSUE THREAD

**Issue by mruderman** [windingwind/zotero-better-notes#125]
This is an amazing project that I would like to use with LogSeq. Current documentation states: 

> _"Bi-directional link note(双链笔记) is supported! Link your notes inside Zotero **with just one click.**...Export with its' linked sub-notes to Obsidian:"_

However, I don't know what that "one click is." When I go to export a main note I see a number of options for exporting main notes:
![image](https://user-images.githubusercontent.com/63901943/186865240-3b502833-08f0-4fbd-ad79-ec307de4a3db.png)
that have choices for embedding linked notes, keeping synced, etc. I tried a number of combinations of these settings, but can't get an output that works. It's not clear if I need to specifically specify all of the linked notes or otherwise.

A solution would be to provide a little more documentation about specific settings and which notes need to be exported.  Perhaps more descriptions of which options need to be selected for specific use cases (e.g., LogSeq with auto sync, or for Obsidian users if there are any differences).

I have done trial and error selections for these options, but have been able to get it to work.

Thank you again for sharing this fantastic project!

**Comment by windingwind** [comment]
To link a note to the current main note 'by one click', see https://github.com/windingwind/zotero-better-notes/blob/master/UserGuide.md#21-from-note
To export the selected not to md:
- Embed linked notes. This will embed the content of note links and export it to a single md file;
- Export linked notes to md files. This will export note links to separate md files.

We do need a big update to the documentation. I've posted a plan to maintain the docs: #116

**Comment by windingwind** [comment]
> but can't get an output that works

I'm not sure if the output md file is blank, or it just does not contain linked notes. Could you please describe it in detail?

**Comment by mruderman** [comment]
Yes, sorry about that.
Here is an example main note I try to export:
![image](https://user-images.githubusercontent.com/63901943/187000924-5bc5d55b-a965-4bce-82ac-2d576a93a0c2.png)
After I export, with above settings (except I toggled square bracket), I get the following md files in the target LogSeq pages folder:
![image](https://user-images.githubusercontent.com/63901943/187002500-e5ba6d44-f1d0-4dfa-b71a-4747c304657b.png)
where the md filenames have hyphens substituted for spaced and at the end end of the file name there is appended some kind of ID code.

Having the hyphens and the ID in the filename prevents correct linking in LogSeq.
Without changing the body of any of the md files, simply replacing the hyphens back with spaces and getting rid of the final hyphen and ID code at the end fixes all this behavior.

Perhaps users' choice of export settings could be their desired note system (LogSeq, Obsidian, Roam, etc.). which would be easier for non-technical or non-dev users to understand.

Thank you again for being an incredible developer!

**Comment by windingwind** [comment]
Hi,

We have a feature called note template to handle these cases.
The md file name is controlled by note template ‘exportMDFileName’, see https://github.com/windingwind/zotero-better-notes/blob/master/TemplateUsage.md#system-templates

By default it’s `note title-note id.md`. We use note id to avoid conflicts, as there might be notes with the same title, like ‘Annotations’(generated by Zotero). Spaces and other characters that are not allowed to appear in file name is replaced with ‘-’.

You could remove the note id part and replace hyphen ‘-’ with anything else LogSeq supports. It’s a little bit strange that LogSeq does not support ‘-‘, which is an allowed character in file name.

Just to remind, the sync is single-path(Zoteo2MDfile). If you modify the MD file and then modify the Zotero Note, the prior modification in the MD file will be overwritten. It’s recommended to use the sync only if you use the MD files as a backup or you are sure the Zotero note is finished and will not be edited. If you want to edit the note again, please cancel the sync from File->Better Notes Sync Manager.

**Comment by mruderman** [comment]
Thank you for taking the time to reply, this is very helpful. I was not
aware of the one-way sync. I will have to rethink my workflow.

**Comment by windingwind** [comment]
Share my workflow with you:

For me, Zotero is like a logging camp. I crop the trees(papers) and place different kind of wood to different wagons(notes). Later, I transport them(output them as markdown files) to furniture factory(Obsidian), and make chairs and desks with the wood(notes).

**Comment by mruderman** [comment]
A beautiful workflow. I may work a little different. When I go to the forest, often I take little cuttings from trees and propagate them in a nursery. Later I may go back and take more cuttings from the same tree (but perhaps nearby trees too) them take them back and maybe graft them onto older cuttings or put them in a new kind of soil. Sadly, I'm not the most organized horticulturist out there, and I can see myself mixing up sources of cuttings on my map (if I have one).

One of the coolest things about your plugin is how any 'main' note can also be a regular note in a different context. At the same time, that very cool feature might also be dangerous for me when I get lost in woods.

Also, I notice you don't have a GitHub sponsor donation setup for your account! I understand GitHub isn't processing donations in all countries, but perhaps you have another means of accepting them?

**Comment by windingwind** [comment]
Hi, @mruderman 
I've updated the documentation of this plugin and the Chinese version is here: https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/biigg4

You could translate it to English: 
![image](https://user-images.githubusercontent.com/33902321/188118054-0a63020d-ce85-4375-a726-0af50cf6d108.png)

**Comment by windingwind** [comment]
I've added a sponsor button on this github repo😄
Thanks for your suggestion!

**Comment by mruderman** [comment]
You have your first sponsor!

**Comment by windingwind** [comment]
Wow! So honored to be sponsored!

Thank you so much 🤩🤩

Please contact me if you have any need with this plugin 🥳

**Comment by windingwind** [comment]
Will close this issue. Feel free to open it any time.
