### ISSUE TITLE
[Bug]点击文献笔记的show on page后，未跳至该页面以及原文部分未高亮

### ISSUE THREAD

**Issue by hymsmmu** [windingwind/zotero-better-notes#128]
**Describe the bug**
点击文献笔记的show on page后，未跳至该页面以及原文部分未高亮

**Additional context**
![屏幕截图 2022-08-27 165047](https://user-images.githubusercontent.com/112151799/187023058-4a2dce88-8356-4c10-bb60-e6e2ba75d14f.png)

**Comment by windingwind** [comment]
这是zotero的bug，与插件无关。官方回复将在未来版本修复。
