### ISSUE TITLE
[Features]建议将线条默认为黑色，当分级标题高亮时，则变化为标题高亮相对应的颜色

### ISSUE THREAD

**Issue by hymsmmu** [windingwind/zotero-better-notes#129]
**Is your feature request related to a problem? Please describe.**
笔记大纲界面里思维导图的线条颜色较多，并且与主笔记中高亮文本颜色不相关

**Describe alternatives you've considered**
建议将线条默认为黑色，当分级标题高亮时，则变化为标题高亮相对应的颜色

**Comment by windingwind** [comment]
暂不支持
