### ISSUE TITLE
Is it necessary to edit the link？& Differentiate display main note

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-better-notes#13]
1--
![图片](https://user-images.githubusercontent.com/57334649/168536698-beb336e0-be26-443d-8e2e-bbb3a8dfa7b1.png)
手动修改链接的需求是否有必要呢？
此处有无必要加入修改标题名的选项，同时原笔记条目相应**双向**更新。
2--
![图片](https://user-images.githubusercontent.com/57334649/168538578-2f0c5f6b-8169-4619-87b4-6af2ce92c14f.png)
在My knowledges分类下的，有主笔记和多个独立笔记地情况，能否通过特殊标识符直观地区分一下？这样就不用选中每一个条目去找了。

**Comment by windingwind** [comment]
1 链接文本更新v0.2.2已支持更新主笔记中的链接标题。从主笔记更新到子笔记标题是危险的，将会丢失格式，因此不会支持双向更新。
2 推荐的操作方式是直接打开工作区对主笔记进行编辑。设计工作区窗口的目的就是省去寻找各个笔记的麻烦。

**Comment by lil-i321** [comment]
> 

1、v0.2.2索引更新功能怎么用呢？没看出来有什么变化呀。
2、明白了，是我操作不对。

**Comment by windingwind** [comment]
相关功能都已实现，未实现的则暂无必要。
将关闭issue，有问题随时可以打开。
