### ISSUE TITLE
希望能够在编辑note时候增加vim模式，或者调用vim[Feature]

### ISSUE THREAD

**Issue by brucejuz** [windingwind/zotero-better-notes#130]
这真的是一个非常好的插件，在zotero中直接增加学习笔记大大的方便知识结构管理。
希望能够在编辑时候直接调用Vim模式或者调用vim编辑器，方便编辑。谢谢！
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
vim模式可能暂不考虑支持。调用外部的文本编辑器也不是很现实，因为zotero的笔记是以富文本形式存储的。

**Comment by hengfei-wang** [comment]
非常希望能够加入vim的功能，同时也希望能把vim功能也带到PDF查看中，我觉得应该会有很多人欢迎这个功能，对这个功能感兴趣的可以挺一下。
