### ISSUE TITLE
试了3次，没能安装上。[Bug]

### ISSUE THREAD

**Issue by lmlm1995** [windingwind/zotero-better-notes#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
试了3次，没能安装上，说是zotero版本不合适。

**Comment by windingwind** [comment]
0.7.x版本只支持zotero 6.14+。已暂时移除。

**Comment by Hansomeboy** [comment]
请问，6.14+在哪里下载呀，官网只有6.0.13

**Comment by windingwind** [comment]
不好意思之前说错了，是6.0.14。目前这还是beta版本，等待正式发布后更新即可。对于正式版本用户，最新插件版本为0.6.29
