### ISSUE TITLE
[Feature] 可否支持页面内指定位置跳转，以及不同笔记之间调转

### ISSUE THREAD

**Issue by wangxiaofeng93** [windingwind/zotero-better-notes#133]
可否支持页面内指定位置跳转，以及不同笔记之间调转

类似markdown的 指定跳转点

或者OneNote的”复制指向笔记、分区、段落的链接“
![1662044957857](https://user-images.githubusercontent.com/100408196/187948954-e8368794-6c31-4f9a-9230-efa9d06140bd.jpg)

**Comment by windingwind** [comment]
类似问题见#108。转跳时具体到行在技术上是可行的，主要的担忧是用户对内容的编辑会导致行位置变化，例如插入了新的内容，则原本的行会后移。
关于复制当前笔记的链接，是可行的。计划放在这个位置，是否可以？
![image](https://user-images.githubusercontent.com/33902321/187954935-a146769e-8ef8-45a8-8f0e-9f110fb4cc06.png)

另外笔记之间的转跳本身就支持。

**Comment by wangxiaofeng93** [comment]
> https://github.com/windingwind/zotero-better-notes/issues/108 如果实现笔记的段落链接，可能无法实现修改后双向同步，只能由用户管理链接锚点。例如，链接到某笔记的某层标题，或链接到某一行。
1. 我就是这个意思，不知道底层会不会混乱。
2. ‘’复制当前笔记的链接‘’ 可行，如此的话，是不是意味着，复制一个主笔记的链接，可以插入到另外一个主笔记
3. ‘’另外笔记之间的转跳本身就支持‘’，目前是主笔记和子笔记之间的链接，我这个更偏向于第二条说的，不限于主笔记和子笔记，可以实现主笔记与主笔记之间的。

**Comment by windingwind** [comment]
这个可以实现。待下次更新后合并更新

**Comment by windingwind** [comment]
Support the line-level jump via note links。
This is a new feature in v0.7.1(Only supports Zotero 6.0.14+, which is currently a beta version).

![image](https://user-images.githubusercontent.com/33902321/188257982-f2bb2cb9-fc46-43c3-a3b7-9b9ab4dc4398.png)
