### ISSUE TITLE
[Feature]导出建议

### ISSUE THREAD

**Issue by Hansomeboy** [windingwind/zotero-better-notes#134]
希望可以有一个功能批量导出pdf和其对应的笔记
**可以像notion的那种导出**
通过文件夹结构
层级结构的导出
--总文件夹
------分类1（文件夹）
----------文献1
--------------pdf
--------------笔记转pdf文件（md也可以接受）（最好是latex编译预览后的标准笔记）
----------文献2
------..........
----分类2
......
希望之后的版本可以有

**Comment by Hansomeboy** [comment]
或者导出报告里面可以能转换latex写的东西（现在导出的报告，里面用latex写的都不会转换成编译后的）这个小地方能改进就非常好了，如果可以万分感谢~

**Comment by windingwind** [comment]
latex编译是指公式，还是指所有latex语法？
