### ISSUE TITLE
“通过注释添加笔记”出现乱码情况，操作复现如下：1.打开zotero 2.在我的图书馆中打开任意1篇PDF文件 3.选中PDF中的任意一个段落或者一句话、一个字 4.选择用译文创建笔记 5.点击所创建的笔记 第四步之后，未出现我用译文创建的笔记内容，而是出现了一串混乱的字符 第五步，点击所谓“创建的笔记”即混乱的字符，无法进行链接到原文位置,可能是我的模板编辑器曾经有所改动导致的，下面附上链接：https://electric-giant-623.notion.site/zotero-abdd6487be4349218e1495cda7b3cb0f

### ISSUE THREAD

**Issue by yangxiaoxiao12** [windingwind/zotero-better-notes#135]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
请附上界面截图与更详细的关于“乱码”的描述，另外我不清楚“选用译文创建笔记”是什么功能？

**Comment by mjthoraval** [comment]
This is a follow up report from this post in the Zotero forum:
https://forums.zotero.org/discussion/99494/add-notes-and-annotation-links-broken-in-v-6-0-13#latest

That post included these screenshots:
https://electric-giant-623.notion.site/zotero-ce2b39a27b1344e78713fa4a473533c1
https://electric-giant-623.notion.site/zotero-abdd6487be4349218e1495cda7b3cb0f

And the final comment from dstillman:
"Yes, the preferences system doesn't support extended characters. It might be possible to put escaped characters in there (using the JS escape() command), but I haven't tested that."

**Comment by windingwind** [comment]
Thanks, @mjthoraval , I have replied to the latest discussion.

It should not be a bug with Better Notes, as this 'add to note' function is neither provided by this plugin nor modified or relate to any Better Notes functions.

Sorry I cannot help. Maybe translating these docs to English and finding solutions in the forums would be a better way to solve it.

**Comment by windingwind** [comment]
Close this issue because it’s unrelated to this plugin.
