### ISSUE TITLE
The add-on "Zotero Better Notes" could not be installed.

### ISSUE THREAD

**Issue by Zumh** [windingwind/zotero-better-notes#136]
**Describe the bug**
The add-on "Zotero Better Notes" could not be installed. It may be incompatible with this version of Zotero

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Adds-On'
3. Gear icon 
4. Click on 'Adds-On from file'
5. Select Better-notes.xpi

**Expected behavior**
install zotero-better-notes adds on

**Screenshots**
The add-on "Zotero Better Notes" could not be installed. It may be incompatible with this version of Zotero

**Desktop (please complete the following information):**
 - Windows 11

# **Temporary Solution**
Modify xpi file
1. change xpi to zip file extention
2. unzip zip file 
3.  edit file 'install.rdf' in text editor.
![image](https://user-images.githubusercontent.com/17211423/188504049-e2055303-c6d2-4ce9-a324-7f08669d9a5d.png)
# Change 
   <em:minVersion>6.0.14</em:minVersion>
    <em:maxVersion>*</em:maxVersion>
# to this
   <em:minVersion>6.0.13</em:minVersion>
    <em:maxVersion>6.0.*</em:maxVersion>
4. replace install.rdf with recent change install.rdf
5. change file extention from zotero-better note  .zip to .xpi
6. reinstall adds on like normal zotero's adds on.

**Comment by foolishman83** [comment]
遇到同样情况。目前zotero官网提供下载的只有6.0.13版本，想问6.0.14以上版本还从哪里下载体验？

**Comment by windingwind** [comment]
The 0.7.x plugin is currently a pre release, which is not compatible to any existing versions of Zotero and will be able to be installed on Zotero 6.0.14 once it’s formally released.

6.0.14 is still a beta version.

**Comment by cookierm** [comment]
The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes#-install
