### ISSUE TITLE
[Feature] Option to allow multiple main notes

### ISSUE THREAD

**Issue by OSantt** [windingwind/zotero-better-notes#137]
** Problem **
When a Main note is set, it is transferred to the main library and supersedes the old main note. This behaviour is undesirable in the case of multiple projects.

** Feature request **
 I use collections and subcollections to collect litterature on particular subjects, it would be nice to be able to, at least, set a main note per collection and subcollection. Even better, allow several main notes to exist alongside each other.

**Comment by windingwind** [comment]
Technically possible, but practically not possible I think. If there are multiple main notes, we don’t know which main note will be use to insert the link and adding an extra step might be confusing?

Welcom any suggestions!

**Comment by llity** [comment]
或者在这里能快速切换主笔记。
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/11771112/190885489-fa2e7593-03ac-4935-b975-2d4dbc5ede85.png">

**Comment by windingwind** [comment]
Will support a quick switch of main notes in the next release(once Zotero 6.0.14 is ready)
![image](https://user-images.githubusercontent.com/33902321/190901291-dbe0b1ce-4436-4e20-a668-97da01758daf.png)

**Comment by OSantt** [comment]
Thanks, this looks great.
