### ISSUE TITLE
有没有适配macOS的版本？

### ISSUE THREAD

**Issue by Pengxiang-Li** [windingwind/zotero-better-notes#140]
很棒的插件！
在使用zotero 6 for MAC （电脑 MacBook pro M1 ）过程中，无法添加插件，希望用到适配macos版本的better notes。
<img width="442" alt="image" src="https://user-images.githubusercontent.com/51403237/190190763-6bab772d-f10c-4afb-aea4-6f7d07ad46fb.png">

**Comment by windingwind** [comment]
IMPORTANT
This version is only for Zotero 6.0.14+. Please download the earlier release here: https://github.com/windingwind/zotero-better-notes/releases/tag/0.6.29
对于Zotero版本早于v6.0.14的用户，请下载更早版本。

请勿下载预发布版本，正式版本最高为0.6.29
