### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by JonathanBrazil** [windingwind/zotero-better-notes#142]
**Is your feature request related to a problem? Please describe.**
Long notes are hard to read

**Describe the solution you'd like**
Collapsible dot points

**Describe alternatives you've considered**
I've considered using headings and using the outline to navigate but that is limited as only 6 or so headings are allowed. 

**Additional context**
Remnote does this.

**Comment by windingwind** [comment]
Collapse text is not very possible to realize as a Zotero plugin. Please consider reporting to https://forums.zotero.org/discussions and ask the Zotero team to support it.

**Comment by JonathanBrazil** [comment]
Okay, thanks for letting me know!
