### ISSUE TITLE
[Feature] Sync when there are changes in markdown

### ISSUE THREAD

**Issue by davidoskky** [windingwind/zotero-better-notes#143]
**Is your feature request related to a problem? Please describe.**
I like to have all my notes in Zotero because it is easy to find an article and immediately read your thoughts about it.
I would like to have the possibility to edit these notes outside zotero as well.
Sometimes I'm working in Obsidian and if I find some error in a literature note I have to go back and forth with Zotero to correct the errors.

**Describe the solution you'd like**
Zotero loads up the changes done to the markdown file in order to stay in sync with it.

**Describe alternatives you've considered**
The zotero note might simply contain a link that opens a normal note in obsidian.

**Comment by windingwind** [comment]
Please discuss here: #147

**Comment by windingwind** [comment]
It's available now. See #244 .
