### ISSUE TITLE
[Bug]对应zotero版本的ZBN安装后，没有出现笔记

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#145]
**Describe the bug**
macOS版
重启很多次软件，只看见过1-2次ZBN界面，大部分时间都消失状态。
Zotero 6.0.13版，ZBN下载了对应的低版本。

**Comment by llity** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/11771112/190844306-e93f386e-e886-4c6e-97f7-768b26ad4e85.png">
之前这里出过1-2次 note，后面怎么重启，重新安装拓展都没有。

**Comment by windingwind** [comment]
请检查：
1. 插件版本；
2. 其他安装了什么插件；
3. 禁用其他所有插件后，是否正常？

**Comment by llity** [comment]
排查完毕，和Pubpeer 插件有冲突，希望能解决。谢谢
<img width="853" alt="image" src="https://user-images.githubusercontent.com/11771112/190884081-a7433478-2be2-4896-b713-1c4ad52b6616.png">

**Comment by llity** [comment]
可能和其他插件还有冲突，无法编辑。

**Comment by llity** [comment]
我更新最新测试版试一试

**Comment by windingwind** [comment]
见 https://github.com/windingwind/zotero-better-notes/issues/103 。

> So as for now, my suggest is the PubPeer Plugin needs to be installed after the Better Notes Plugin
hope this helps

**Comment by llity** [comment]
目前问题是，笔记无法编辑。

**Comment by windingwind** [comment]
请具体描述或截图

**Comment by llity** [comment]
可以了，之前在高版本创建过Nots，编辑界面无法编辑，重新创建一下就行了。不知道插件有方法进行重新初始化吗？谢谢
<img width="367" alt="image" src="https://user-images.githubusercontent.com/11771112/190885099-b1be45f2-eb67-454f-8861-7b572ab79ea3.png">

**Comment by llity** [comment]
主笔记好像只能一个，如果能多个就方便整理不同分类的思路了。
<img width="680" alt="image" src="https://user-images.githubusercontent.com/11771112/190885228-c913d4c7-cdfa-4390-bbec-9dcd916d45b1.png">

**Comment by windingwind** [comment]
> 可以了，之前在高版本创建过Nots，编辑界面无法编辑，重新创建一下就行了。不知道插件有方法进行重新初始化吗？谢谢 <img alt="image" width="367" src="https://user-images.githubusercontent.com/11771112/190885099-b1be45f2-eb67-454f-8861-7b572ab79ea3.png">

引起无法编辑可能是当前笔记在回收站内，应该和创建版本无关，和初始化应该也无关

**Comment by windingwind** [comment]
> 主笔记好像全部列出来，如果能多个就方便整理不同分类的思路了。 <img alt="image" width="680" src="https://user-images.githubusercontent.com/11771112/190885228-c913d4c7-cdfa-4390-bbec-9dcd916d45b1.png">

将在未来支持主笔记的快速切换

**Comment by llity** [comment]
谢谢
