### ISSUE TITLE
从文献附件中切到笔记中的图片同步到ipad的笔记中不显示

### ISSUE THREAD

**Issue by Bridge0415** [windingwind/zotero-better-notes#146]
PC端：
![QQ图片20220917145737](https://user-images.githubusercontent.com/34123072/190844795-edae75d5-46f1-466c-9787-b84d9e5a9019.png)

ipad端：
![QQ图片20220917145751](https://user-images.githubusercontent.com/34123072/190844820-19345f56-cf62-4c84-9a3e-6b855a714eb8.jpg)

**Comment by windingwind** [comment]
同步速度慢与zotero服务器的访问速度有关，与插件无关。请在https://forums.zotero.org/discussions 反馈问题。
