### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by Bridge0415** [windingwind/zotero-better-notes#148]
## Template Type

QuickNoteV2

## Desired Template Performance

1. Attach the title of the item when adding the quick note to the main note.
2. If the note has no comments, use "annotation" as the default title.

![Snipaste_2022-09-18_12-13-21](https://user-images.githubusercontent.com/34123072/190885454-0bd11cf2-a637-43c7-ae8c-bddb0828d303.jpg)

## Current Template

```js
${await new Promise(async (r) => {
let res = "annotation"
if(annotationItem.annotationComment){
res = ""
res += Zotero.Knowledge4Zotero.parse.parseMDToHTML(annotationItem.annotationComment);
}
res +="<blockquote><i>《"
res +=topItem.getField('title')
res += "》</i></blockquote>"
res += await 
Zotero.Knowledge4Zotero.parse.parseAnnotationHTML(noteItem, [annotationItem], true);
r(res);})}
```

**Comment by windingwind** [comment]
Thank you!
Added to the doc here: https://github.com/windingwind/zotero-better-notes/issues/85#issuecomment-1250231737
