### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#149]
**Is your feature request related to a problem? Nope.**
可以在笔记里面显示，链接到哪个分级吗？谢谢。我的想法是主笔记下面的方法，可能来自多篇文章中的笔记内容。
<img width="862" alt="image" src="https://user-images.githubusercontent.com/11771112/190892399-519b1c1c-8dd5-4667-bd93-6db99c1057fe.png">

**Comment by windingwind** [comment]
已支持，将在未来版本发布
