### ISSUE TITLE
Genealogies of Knowledge possible?

### ISSUE THREAD

**Issue by pallykkja** [windingwind/zotero-better-notes#15]
Hello, I posted this in Zotero forum:

Feature request: Genealogies of Knowledge plugin possible?
[p.m.lykkja](https://forums.zotero.org/profile/771991/p.m.lykkja) [39 minutes ago](https://forums.zotero.org/discussion/97206/feature-request-genealogies-of-knowledge-plugin-possible)
Hello, I am wondering if it is possible to make a plugin with Genealogies of Knowledge software? https://sourceforge.net/projects/modnlp/ It would be nice to load up fulltext from a library so it can be text mined. It is a suprising easy to use and intuitive, and could be perfect as a plugin to Zotero: http://genealogiesofknowledge.net/software/manual/

**Comment by windingwind** [comment]
Could you please describe how this software will be used along with Zotero(and this plugin)?

**Comment by pallykkja** [comment]
The GoK software is just 66 mb, and if it could be possible to make a corpus by choosing lets say 10 000 pdf files from Zotero, and create a corpus that can be opened in GoK software, then the GoK software can do the rest.

**Comment by pallykkja** [comment]
This software is used to check how words are used in a context, that is why it is long lines with the word in the middle, and you can sort on the words up to five words left and right, alphabetically ordered. It is five plugins in the GoK software that is very easy to use.

**Comment by pallykkja** [comment]
The technical use of GoK is very intuitive and easy, I think maybe the only problem is to build a corpus by exporting from Zotero to GoK.

**Comment by windingwind** [comment]
It's hard to get the point as I‘ve never used the GoK.

Does it search the pdfs, or need a data file in its own format? And I still don't know the relation between this software and this addon.

**Comment by windingwind** [comment]
Zotero provides a full-text search, including the meta-data. Another thing I must consider if I decide to introduce this GoK into the addon/Zotero's current workflow is: how should I convince people to install any extra software just for one feature that Zotero can already partly do?

One of the most important reasons that I develop this addon is that using another software, i.e Obsidian, with Zotero, is not that convenient.

**Comment by pallykkja** [comment]
I am sorry,  I am very new to Github. It could only be a new addon, but because I have tried your excellent other addon, I thought you could be interested in building an addon with GoK. I can check if it need its own format and come back to you.

Best,
Pål
________________________________

**Comment by windingwind** [comment]
@pallykkja 
The PDF attachments must be processed and split its text and images, which is very complicated.

I think the best solution is to request the GoK a new feature to import from Zotero/Endnote/Mendeley data.

**Comment by windingwind** [comment]
I'll close this issue. Thanks for your kind suggestion!
