### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by codebian** [windingwind/zotero-better-notes#150]
**Describe the bug**
无法使用插入模板创建笔记

**To Reproduce**
1. Go to '编辑'
2. Click on '插入模板''使用模板插入多条笔记''使用模板插入多个条目'
3. 本来应该有弹窗
4. 但是没有弹窗，无法使用这三个选项卡

**Screenshots**
![image](https://user-images.githubusercontent.com/90493482/190935233-1c33b611-9aa8-42f0-8e69-ba5488be9c1d.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Version 最新版zotero，最新版betternotes

**Additional context**
在安装下面4个插件前可以使用，但是在挨个禁用直到全部禁用这4个插件后，仍然无法使用插入模板等功能，不知道是什么原因
![image](https://user-images.githubusercontent.com/90493482/190935449-c5b7864c-4a6d-4882-8ebf-70af90f97486.png)
![image](https://user-images.githubusercontent.com/90493482/190935463-7c4c550e-47ba-474b-bffb-40f5a8ee56f3.png)
![image](https://user-images.githubusercontent.com/90493482/190935480-80bf1a97-f3b0-414f-bc33-67c7d229d6c7.png)
![image](https://user-images.githubusercontent.com/90493482/190935490-04d94a52-1b16-49b1-94d8-ce6745e7db08.png)

**Comment by windingwind** [comment]
请在此处打开调试窗口，然后操作一次插入模板，然后将调试输出上传此处。

**Comment by codebian** [comment]
[Debug Output-9.22-无法打开插入模板弹窗.txt](https://github.com/windingwind/zotero-better-notes/files/9626527/Debug.Output-9.22-.txt)
非常抱歉现在才传送，麻烦您了

**Comment by codebian** [comment]
https://user-images.githubusercontent.com/90493482/191873216-160a6bc5-eebc-4478-86b1-1c117409d785.mp4

录了一段视频，不知能否解释清楚，万分感谢Orz

**Comment by windingwind** [comment]
目前可通过打开工作区窗口来解决。将在下一版本修复。

**Comment by windingwind** [comment]
已修复，请更新到zotero 6.0.14+并更新插件
