### ISSUE TITLE
[Bug] 利用“[Item] collect annotations by color-typeB”插入模板时无法识别annotation的颜色

### ISSUE THREAD

**Issue by CGL5230** [windingwind/zotero-better-notes#152]
利用“[Item] collect annotations by color-typeB”生成模板笔记时，无法识别annotation的颜色。但是typeA可以识别。这个是我设置错了还是？
图1是annotation标注的颜色，四个颜色都有：
![image](https://user-images.githubusercontent.com/57136380/191022405-0c1838ed-c9a1-4834-a57c-ef444c466b30.png)
接下来是typeB的插入模板笔记，可以看到，并没有实现typeB该有的效果：
![image](https://user-images.githubusercontent.com/57136380/191022592-ad952896-8ffb-4417-872e-f3ae23b8521c.png)
接下来是typeA的模板，这个就可以识别：
![image](https://user-images.githubusercontent.com/57136380/191022855-153883f6-9050-4c89-816e-cd8e15f1ac3d.png)

**Comment by windingwind** [comment]
type B本身不会为颜色添加标题，也不会做识别颜色。详见最初关于这两个模板的讨论，他们提交type b只是将各个条目的注释收集到一起。
要显示注释颜色，请：
![image](https://user-images.githubusercontent.com/33902321/191950761-8ce4f430-56ad-41f2-8ad5-d3ef51eb9145.png)
