### ISSUE TITLE
[Bug]export笔记为markdown时存在的一些问题

### ISSUE THREAD

**Issue by manipulative** [windingwind/zotero-better-notes#153]
您好，我在导出note到本地markdown时，发现一些链接可以嵌入markdown，而另一些则不会。
这是我要导出的note
<img width="410" alt="image" src="https://user-images.githubusercontent.com/26652791/191573036-89e7a3f8-86a1-42a6-8ff5-8eff0fc4d60e.png">
这是导出后在md文件中显示的样子
<img width="648" alt="image" src="https://user-images.githubusercontent.com/26652791/191573141-25d17c01-1e77-4409-a19d-6d8af3d38b68.png">
可以发现，前两个链接并没有显示为linked note，但第三四条显示为了linked note。
请问这是什么问题呢？

**Comment by windingwind** [comment]
请检查：
1. 未嵌入的笔记是否被删除；
2. 未嵌入的笔记链接内是否包含`ignore=1`。这是用于防止反复嵌入的。当你在编辑器中手动嵌入过一次后，链接就会增加这个参数，表示内容已嵌入。如果手动嵌入后要手动删除内容，请将链接中此处改为`ignore=0`

**Comment by windingwind** [comment]
是否有更新？若无，将关闭问题

**Comment by manipulative** [comment]
不好意思忘记及时反馈，修改ignore后可以成功解决我的问题，谢谢！祝betternote越来越好
