### ISSUE TITLE
[Feature]关于笔记引用显示的相关问题

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#154]
目前发现引用到主比较后，标签为二级TITLE。

- 能否以文章所在目录+文章的特征KEY[类似BBT的auth.lower + shorttitle(3,3) + year]+TITLE 来展示。这样可以知道引用来着哪个collection （图1）。
- 如果在子笔记中选择一段文字添加到主笔记，能否以截断文字的形式显示在主笔记中 (图2)，这种显示方式对于收集大量文献聚合具有明显的优势，也许再附上上面的特征目录便于区分。
- 非常兴奋即将到来的双向同步，目前单项同步观察中（目前同步CPU会飙升一下）。
- 也许遇到了子笔记引入主笔记的bug，发现不管在子笔记哪个二标题下引入，引入标签都在子笔记底部，而没有在二级标题内（图3），或者目前子笔记只能被整体引用吗？
- 一篇文章中的anatation，通过按钮插入笔记中默认新建一个笔记（图4），能否全部只插入一个笔记中？
- 同步管理器，Name太长，没有自动截断（图5）。

谢谢

方案：图1、2在主笔记中结合起来显示、子笔记中在光标处/选中文本末尾显示“主笔记/二级标题...”  我发现子笔记始终是最顶部的一段话被插入到主笔记生成引用标签。目前看来只能通过选中一段笔记，再插入到主笔记中可能更好。

图1：
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/11771112/192135642-a18d13a0-bd55-42c8-b987-f9de7cb095c1.png">

图2：
<img width="632" alt="image" src="https://user-images.githubusercontent.com/11771112/192106514-ad8c7852-9aed-490d-9d33-2a5bc40d5a2d.png">

图3：
<img width="558" alt="image" src="https://user-images.githubusercontent.com/11771112/192106653-6564da6a-56ae-42c9-978e-3e99fbc6d7df.png">

图4：
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11771112/192127236-a132a4a0-8cc3-4372-9af4-3a086092ac20.png">

图5：
<img width="651" alt="image" src="https://user-images.githubusercontent.com/11771112/192135417-9d92d17f-b0bf-4ac0-acb6-305213f3ae73.png">

**Comment by windingwind** [comment]
1. 可以。QuickInsert模板定义了链接内容的生成方式，修改模板即可自定义链接文本。
2. 同上，根据你需要的方式（例如选取子笔记第二行）并以此生成链接
3. 很遗憾同步及其他功能更新将推迟，目前主要工作是适配zotero7，因为有大量内容需要修改或完全重写
4. 不是bug。支持两种插入位置，默认插入位置是节末尾，可按住shift以插入到节前。见#121
5. 全部插入一个笔记中，可使用zo自带的 从注释创建笔记
6. 其实有自动截断，zotero控制，似乎是100？字符。非恶性bug仅做记录，暂不修复，理由同上，感谢反馈

**Comment by llity** [comment]
谢谢，zotero 7没找到相关信息，期待一下，这套完善的笔记系统非常好用。

**Comment by windingwind** [comment]
同步相关见#244 。此处关闭
