### ISSUE TITLE
[思维图]：H1一级标题太长显示不全，有什么办法可以解决吗？

### ISSUE THREAD

**Issue by lan-slot** [windingwind/zotero-better-notes#155]
![微信截图_20220925160712](https://user-images.githubusercontent.com/68606787/192152104-270646d0-b02a-4547-ad3e-5d18e51a626d.png)

Like this,The first level title is too long to be displayed completely,How to display it completely？
Thanks！

**Comment by windingwind** [comment]
先前版本已支持自动换行而非截断
