### ISSUE TITLE
[Feature] template 能否加入yaml格式

### ISSUE THREAD

**Issue by stdAri** [windingwind/zotero-better-notes#157]
为了配合其他md软件使用，有没有办法可以利用yaml格式给笔记添加信息。目的是将文献的metadata写入到yaml，在obsidian中利用利用dataview去直接检索相关的yaml内容。

- 当前如果用`---`的方式添加yaml文本，导出的文本为`\---`。
- 如果用下面这种方式导出的话，导出文本为`* * *`,都没有办法很好地兼容yaml。
![image](https://user-images.githubusercontent.com/7691836/192545590-04502107-e03f-45ef-ba0a-c8607e1e9403.png)

**Comment by windingwind** [comment]
是需要导出为yaml文件，还是在导出md过程中遇到符号转义问题？

**Comment by stdAri** [comment]
编辑器会自动将MD的`---`语法转义成`单行`,如果直接是`---`导出的时候会变成`\---`,单行导出为`* * *`，所以可以理解为导出为MD文件，但是是包含了YAML格式的信息，作为markdown的metadata，但是这种行为在Zotero内部是不支持的，或者说Zotero不认为这是yaml格式的信息，导出过程中会对其进行转义，破坏原有的格式

**Comment by windingwind** [comment]
你是通过何种方式导出的，导出并不会转义行分隔符。
![image](https://user-images.githubusercontent.com/33902321/193176141-744b97e6-03ff-4160-93ba-5922a720ac1d.png)

**Comment by stdAri** [comment]
你这种是按照作为单行导出的。

我是按照这种方式，直接将对应的yaml格式文本复制进去。然后进行导出(这样子的做法，是考虑到自定义Template导出的时候，可以复制到粘贴板，然后在将对应的metadata粘贴到笔记里)
``` markdown
---
test:test
---
```
![image](https://user-images.githubusercontent.com/7691836/193180785-2fe4fb1c-7d04-4959-99fe-6cb0746645b5.png)

如果用这种导出方式的话，是会转义字符的

**Comment by windingwind** [comment]
已去除对-的转义，将在下一版本发布

**Comment by windingwind** [comment]
已更新

**Comment by luohuaaa** [comment]
> 已更新

没有吧，---导出到markdown照样变成 \---

**Comment by luohuaaa** [comment]
> 已更新
没有吧，’---‘导出到markdown照样变成‘\---'

**Comment by luohuaaa** [comment]
> 已更新
没有吧，---导出到markdown照样变成\\---

**Comment by windingwind** [comment]
专门模板控制文件头的yaml header，因此不会支持正文的yaml

**Comment by luohuaaa** [comment]
> 

正文加yaml其实是因为betternote自带的表头基本没什么用，比如作者、年份这类最基本的信息全都没有，理论上只要是条目笔记就应该可以读取这些信息吧，能否扩充一下表头的内容？

**Comment by windingwind** [comment]
请看文档。表头由模板自定义
