### ISSUE TITLE
[Bug] 编辑区按钮没有tooltip

### ISSUE THREAD

**Issue by pluiez** [windingwind/zotero-better-notes#158]
**Describe the bug**
1. 主笔记区的编辑菜单按钮，以及主页按钮，悬停无法显示tooltip

**To Reproduce**
1. zotero 版本：6.0.13
2. 安装 better-notes 版本：0.6.29
3. 在文献库点击“工作区”，跳转到工作区
4. 鼠标悬停编辑菜单按钮，以及主页按钮，不显示tooltip
5. 在文献库的条目视图里的笔记，可以显示tooltip

**Screenshots**
1. 悬停编辑区工具栏按钮或“🏠 主页”按钮，不显示tooltip
![image](https://user-images.githubusercontent.com/4468773/192683147-4469172a-3697-4e18-a1ec-eec2a6870feb.png)
2. 文献库的条目视图中的笔记，可以显示tooltip
![image](https://user-images.githubusercontent.com/4468773/192686035-9a7278ca-f4f0-404d-9bfe-b05dfd5d5207.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 专业版 21H1
 - zotero 版本：6.0.13
 - better-notes 版本：0.6.29

**Additional context**
尝试过删除插件并重装，但仍然存在上面的问题。

**Comment by windingwind** [comment]
感谢提出，这是一个已知问题，目前不清楚如何解决。由于已列在计划列表，此处将关闭。
