### ISSUE TITLE
[Bug] Not updating in Zotero 6.0.14-beta.6+a7e6fc330

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#159]
I am using the latest beta of Zotero on Windows 10: 6.0.14-beta.6+a7e6fc330
I understand that this beta is the same as the stable Zotero 6.0.14. So I was expecting to get the latest release of Better Notes: 0.7.2.
However, it seems that the update is stuck to Release 0.6.29 on the beta.
Can you confirm that Release 0.7.2 is working on the latest beta? In that case, is it ok to install manually Release 0.7.2?
If it should be working, would it be possible to adjust the automatic updates for the beta?
Thank you very much.

**Comment by windingwind** [comment]
Hi, I've changed min version requirement from 6.0.14 -> 6.0.14-beta in 0.7.3. According to https://udn.realityripple.com/docs/Mozilla/Toolkit_version_format#Examples .

Thank you!

**Comment by mjthoraval** [comment]
Thank you very much! It has updated now.
