### ISSUE TITLE
[vote]-Is it necessary to retain the keywords “Linked Note:”?

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-better-notes#16]
Is it necessary to retain the keywords “**Linked Note:**”? 
Please give your opinions.
![图片](https://user-images.githubusercontent.com/57334649/168601034-c7d16921-5e4c-47bf-b1c5-9a8a42efe802.png)

**Comment by windingwind** [comment]
由于新的模板功能已经完全实现了插入/展开格式的自定义，因此这个需求已经解决，将关闭该问题。
