### ISSUE TITLE
[Documentation] Translate text and TOC of yuque.com books

### ISSUE THREAD

**Issue by VladimirAlexiev** [windingwind/zotero-better-notes#160]
- Built-in translation: https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/biigg4?translate=en
  The text is translated but the TOC is not
![image](https://user-images.githubusercontent.com/536250/193016016-0c6bf0fa-241b-4e72-adc4-7fb8545e3f7d.png)

- Google translation: https://zotero-yuque-com.translate.goog/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/biigg4?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp
  The TOC is translated but the text is missing :-(
![image](https://user-images.githubusercontent.com/536250/193016494-15e01f2e-0c33-4948-888d-aab88b31349f.png)

Is it possible to have both text and TOC?

---

BTW this automated translation is surprisingly accurate:
> If you are carefully investigating a wide variety of literature note methods, you may feel your head is big.

That's exactly how I feel! My head is too big from everything I've crammed, yet too small to keep it organized and cram more ;-)

**Comment by mjthoraval** [comment]
It is working for me in Chrome:
1) Go to the page in Chinese: https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/biigg4
2) Right click -> Translate to English.
I get both the TOC and the content translated.

**Comment by windingwind** [comment]
Maintaining the documentation is really a heavy burden for me. I'm sorry I don't have much time but currently, I can only provide the Yuque version of the documentation in Chinese.

I agree things are becoming much too complex when it comes to literature notes. Trying to explain my plugin clearly is no easier than trying to understand different note tools.

If you have any suggestions about how to organize the documentation or if you need any further explanation about certain parts, I would be glad to help.

**Comment by windingwind** [comment]
Hi,
I'm using a script to download md files from Yuque and translate them to English using NiuTrans. Here's the English version of Wiki:
https://github.com/windingwind/zotero-better-notes/wiki

**Comment by VladimirAlexiev** [comment]
@mjthoraval This way works for me too. 
But I think the built-in translation uses NiuTrans and is better than Google Translate, right @windingwind ?

**Comment by windingwind** [comment]
I'm not sure what translation service Yuque uses. I use NiuTrans to translate the Yuque docs to GitHub wiki, which performs better in en-zh translation, at least for me.
