### ISSUE TITLE
[Feature] 在笔记Home按钮默认列出My notes文件夹的主笔

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#162]
Home按钮的主笔记功能需要进一步添加。默认主笔记保存在 My notes文件夹。

谢谢
<img width="547" alt="image" src="https://user-images.githubusercontent.com/11771112/193179493-f1feb40a-baa2-45f6-a36a-7a959d92a457.png">

**Comment by windingwind** [comment]
由于不计划实现该功能，将关闭问题。谢谢反馈
