### ISSUE TITLE
[Feature] 建议添加类似word中重复上一次操作的快捷键

### ISSUE THREAD

**Issue by pluiez** [windingwind/zotero-better-notes#163]
**Describe the solution you'd like**
Word 支持用快捷键 F4 重复上一次编辑动作，这样可以提高重复编辑操作的效率。比如右键 insert->表格，默认是一个 2 列表格，可以先右键选择 在列右插入 ，然后按 F4 3 次，就可以创建一个多列表格。

**Comment by windingwind** [comment]
可能有点太复杂了。许多编辑操作并非由插件提供，因此我能支持的操作极其有限。建议向Zotero社区提出该请求。

要插入指定大小的表格，请使用 菜单栏=>插入模板=>[Text] table

**Comment by windingwind** [comment]
由于不计划实现该功能，将关闭问题。谢谢反馈！
