### ISSUE TITLE
[Bug]笔记链接无法跳转到对应行

### ISSUE THREAD

**Issue by handsome-77** [windingwind/zotero-better-notes#164]
**Describe the bug**
复制一个笔记中某一行的链接作为另一个笔记的超链接，点击该超链接无法跳转到对应行。

**To Reproduce**
1. 打开笔记1，选择某一行（如第8行）
2. 点击“copy note link of current note”，即复制笔记1第8行链接
3. 打开笔记2，为文字添加超链接，该超链接为步骤2复制的链接，超链接添加完成
4. 关闭笔记1
5. 点击该超链接，无法跳转到笔记1的第8行，而是跳转到第一行

**Expected behavior**
希望点击超链接后，能够跳转到笔记的对应行

**Screenshots**
![image](https://user-images.githubusercontent.com/83406401/193393487-24e86e57-4715-4ac4-af30-69062194a9a3.png)
![image](https://user-images.githubusercontent.com/83406401/193393514-8cc98cff-ef59-41e7-a14f-093b38d875b6.png)
![image](https://user-images.githubusercontent.com/83406401/193393531-5482ac49-b3c8-40bd-a340-5a16aa41ec84.png)
![image](https://user-images.githubusercontent.com/83406401/193393565-c0e9b7c6-2c93-44ea-9854-dccd9264953f.png)

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser：chrome
 - Zotero Version：6.0.15
 - Add-on Version：0.7.13

**Comment by windingwind** [comment]
谢谢反馈，这是目前已知的问题。目前仅在通过链接第一次打开笔记时能够转跳位置。
计划近期修复

**Comment by windingwind** [comment]
已修复。

**Comment by kuyree** [comment]
> **Describe the bug** 复制一个笔记中某一行的链接作为另一个笔记的超链接，点击该超链接无法跳转到对应行。
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. 打开笔记1，选择某一行（如第8行）
> 2. 点击“copy note link of current note”，即复制笔记1第8行链接
> 3. 打开笔记2，为文字添加超链接，该超链接为步骤2复制的链接，超链接添加完成
> 4. 关闭笔记1
> 5. 点击该超链接，无法跳转到笔记1的第8行，而是跳转到第一行
> 
> **Expected behavior** 希望点击超链接后，能够跳转到笔记的对应行
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/83406401/193393487-24e86e57-4715-4ac4-af30-69062194a9a3.png) ![image](https://user-images.githubusercontent.com/83406401/193393514-8cc98cff-ef59-41e7-a14f-093b38d875b6.png) ![image](https://user-images.githubusercontent.com/83406401/193393531-5482ac49-b3c8-40bd-a340-5a16aa41ec84.png) ![image](https://user-images.githubusercontent.com/83406401/193393565-c0e9b7c6-2c93-44ea-9854-dccd9264953f.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: windows11
> * Browser：chrome
> * Zotero Version：6.0.15
> * Add-on Version：0.7.13

所以，请问现在是可以跳转了吗？我就还是不跳下去，求教

**Comment by occasional15** [comment]
> 谢谢反馈，这是目前已知的问题。目前仅在通过链接第一次打开笔记时能够转跳位置。 计划近期修复

可是我测试了好几次，打开链接后无法转到对应的行或节，还是只能到第一行。【Zotero Version：7.0.0-beta.51+7c5600913 (64-bit)；Add-on Version：1.1.4-36】
