### ISSUE TITLE
betternotes的颜色模板，希望可以不同文章的同样颜色的笔记放在一起，便于归类

### ISSUE THREAD

**Issue by RINA0012** [windingwind/zotero-better-notes#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/issues/85#issuecomment-1210063595

请善用搜索
