### ISSUE TITLE
[Bug]0.70.3新版本似乎在笔记界面无法看到Tex

### ISSUE THREAD

**Issue by swenqing** [windingwind/zotero-better-notes#166]
![image](https://user-images.githubusercontent.com/37140550/193501516-2b2f782c-9ca5-4201-b7d9-080fbc6dccbf.png)

**Comment by swenqing** [comment]
> ![image](https://user-images.githubusercontent.com/37140550/193501516-2b2f782c-9ca5-4201-b7d9-080fbc6dccbf.png)

**Comment by JDYG** [comment]
这是bug吗？我也没有看到tex的选项，请问怎么打开？

**Comment by windingwind** [comment]
zotero6.0.14+支持直接编辑和显示公式，不需要切换渲染模式，因此移除了该按钮
