### ISSUE TITLE
[Feature]增加自定义链接功能

### ISSUE THREAD

**Issue by dhdkc** [windingwind/zotero-better-notes#168]
希望可以添加一个自定义链接笔记和论文pdf内容的选项，即可以选择将某段笔记内容链接到pdf的任一句子，并实现点击该段笔记内容即可在pdf中显示链接的对应的句子，而不限于通过复制pdf内容实现链接。

**Comment by windingwind** [comment]
不通过复制文本内容的话，如何确定pdf的具体位置？

**Comment by windingwind** [comment]
由于长时间无进一步讨论，将关闭
