### ISSUE TITLE
Template list is empty & Template Editor dos not work[Bug]

### ISSUE THREAD

**Issue by yannick-boehm** [windingwind/zotero-better-notes#169]
After updating Zotero Better Notes the Template List is empty. I haven't deleted any of the templates. 
![image](https://user-images.githubusercontent.com/102553711/194720087-53172000-2d31-4f40-8974-ecf42b41e42e.png)
Furthermore it is not possible to create new templates. When clicking on "Create"-button literally nothing changes.  
I admit that I changed the [QuickInsert] Template before updating the add-on. The changed template result in the following issue: 
![image](https://user-images.githubusercontent.com/102553711/194725330-f85302c6-325d-4c6d-b557-5ef0fa5b8e99.png)
I could fix the template if had a chance to enter the fully listed template editor. 

I have uninstalled the add-on and installed a fresh xpi from the github repository but nothing has changed so far.

**Comment by windingwind** [comment]
Sorry but it seems to be a bug caused by recent bug fixes. Currently, you could use the ealier version 0.7.2 instead and I will fix it as soon as possible.

Your data is safe. Don’t worry.

**Comment by windingwind** [comment]
Please update to v0.7.6. It should have been solved.
Thanks for the feedback!
