### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by zhao-shanhe** [windingwind/zotero-better-notes#170]
在主笔记中有多篇文章的笔记时，通过文中高亮——转化为笔记——插入主笔记（*）。在插入主笔记的时候文章太多，导致有时候插入发生错误，能否锁住其余文章笔记。。或者是其他的方法。。
再次感谢，笔记功能非常好用。

**Comment by windingwind** [comment]
可以具体描述一下发生错误是指什么？

**Comment by zhao-shanhe** [comment]
你好，也是最近才开始使用这个笔记插件。一个主笔记下我放了十几篇文献。在我把笔记插入主笔记的时候，有时候就插错地方了，而且自己也没意识到，是在后面导出以后才发现的。
所以我想，如果可以把其他的笔记暂时锁住，或者我在编辑的这一部分突出一下，这样可能会更好一些…


对你的贡献再次感谢。












Shan-He&nbsp;Zhao
***@***.***

---Original---
From: ***@***.***&gt;
Date: Sun, Oct 9, 2022 11:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [windingwind/zotero-better-notes] [Feature] (Issue #170)

**Comment by windingwind** [comment]
我不是特别理解，是指因为当前光标位置不清晰所以容易插入到错误的位置，而非插件有错误，是这个意思吗

**Comment by zhao-shanhe** [comment]
主笔记里太多文章了，我插入的时候混了…
我把这篇文章的笔记插入到其他文章的笔记里了，因为所有的笔记都可以编辑…









Shan-He&nbsp;Zhao
***@***.***

---Original---
From: ***@***.***&gt;
Date: Mon, Oct 10, 2022 10:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [windingwind/zotero-better-notes] [Feature] (Issue #170)




 
我不是特别理解，是指因为当前光标位置不清晰所以容易插入到错误的位置，而非插件有错误，是这个意思吗

**Comment by windingwind** [comment]
是在使用哪个功能插入？请确认在Zotero中笔记指的是可编辑的文本区域，和高亮批注不同。这里的描述使我有点困惑。

笔记可以编辑是很自然的，我还是不太理解。
