### ISSUE TITLE
[Bug] Links errors

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#173]
Every time I click on a link, it seems to generate an error.
I have tried to gather the main error reports:
<code>[JavaScript Error: "inputRef.current is null" {file: "resource://zotero/note-editor/editor.js" line: 51093}]
[JavaScript Error: "inputRef.current is null" {file: "resource://zotero/note-editor/editor.js" line: 51093}]
[JavaScript Error: "inputRef.current is null" {file: "resource://zotero/note-editor/editor.js" line: 51093}]
[JavaScript Error: "inputRef.current is null" {file: "resource://zotero/note-editor/editor.js" line: 51093}]
[JavaScript Error: "inputRef.current is null" {file: "resource://zotero/note-editor/editor.js" line: 51093}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 883}]
Security Error: Content at moz-nullprincipal:{da62401a-2b89-4c62-a796-ed7e9ce5f350} may not load or link to chrome://knowledge4zotero/content/treeView.html.
version => 6.0.16-beta.3+29dd0cf5d, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-GB, appName => Zotero, appVersion => 6.0.16-beta.3+29dd0cf5d, extensions => Zotero Better Notes (0.7.7, extension), DOI Manager (1.4.2, extension, disabled), Zutilo Utility for Zotero (3.10.0, extension, disabled), Open Pdf for Zotero (0.0.4, extension, disabled), zotero-plugin-full-creators (1.0.1, extension, disabled), ZoteroPreview (0.1.6, extension, disabled), Night for Zotero (0.4.16, extension, disabled), ZoteroAbstractCleaner (0.0.7, extension, disabled), ZoteroSpecialTagsColumn (0.0.5, extension, disabled), Zotero AutoIndex (5.0.9, extension, disabled), Folder Import for Zotero (0.0.5, extension, disabled), Zotero PDF Preview (0.2.10, extension, disabled), Zotero PDF Translate (0.8.25, extension, disabled), Better BibTex for Zotero (6.7.24, extension, disabled), Zotero LibreOffice Integration (6.0.2.SA.6.0.16-beta.3+29dd0cf5d, extension, disabled), Zotero Word for Windows Integration (6.0.1.SA.6.0.16-beta.3+29dd0cf5d, extension, disabled)</code>

It seems that the <code>Security Error: Content at moz-nullprincipal</code> appears when clicking a link inside a link preview.

**Comment by windingwind** [comment]
Thanks for your report. These outputs occur after one recent update of Zotero, but I am not sure exactly which one. It is an exception raised inside Zotero's note editor, not from the plugin. So possibly I can do nothing to help.

In the early Zotero 6, they do not happen. As long as it does not affect any functions, I may not spend too much time on this issue. Currently, my main focus is to refactor the code to be able to replant in the coming Zotero 7.

**Comment by windingwind** [comment]
For me, the `line: 51093` error does not occur. The `line: 68673` error's source code is:

```js
window.addEventListener('focus', event => {
  let container = event.target.closest('.math-src'); // here

  if (container) {
    container.spellcheck = false;
  }
}, true);
```
So this is the code added recently to disable the spellcheck in math blocks. Every time the note is focused(also triggered by click), it will try to find a math block, while it does not exists because we are not in a math block.

Maybe discussing this in zotero-dev would be more helpful.

**Comment by windingwind** [comment]
As for the `Security Error: Content at moz-nullprincipal`, I guess this is caused by firefox's security strategies in iframes. Just ignore it.

**Comment by mjthoraval** [comment]
I realize that the `event.target.closest is not a function` is the error that keeps coming in a loop when I try to open a note link with the Better Notes plugin disabled, as reported in [this other thread](https://github.com/windingwind/zotero-better-notes/issues/167#issuecomment-1272480279).
So I guess they are all related to the recent disabling of spellcheck in math blocks. I would probably not have the technical knowledge to report properly in zotero-dev, but I could report in the forums if you think that could work.

**Comment by mjthoraval** [comment]
Here is the report in the forums:
https://forums.zotero.org/discussion/100288/bug-6-0-16-beta-3-locked-in-looped-typeerror

**Comment by windingwind** [comment]
Thanks, hope the Zotero team would notice it.
