### ISSUE TITLE
[Feature] QuickInsert Text of sub-note

### ISSUE THREAD

**Issue by yannick-boehm** [windingwind/zotero-better-notes#174]
First of all, thank you very much for your fast bug-support🙏🏼 

I wonder if there is a way to modify the QuickInsert button behavior. I would rather have the text of the sub-note inserted into the main note instead of a link to the sub-note. I know that I can click onto the link and insert the sub-note as a "linked Note" but that is plenty of work to do when having loads of sub-notes. 

Perhaps creating a different button to really quick insert text of sub-note to main-note would do the thing. 
It would also be nice if the text updates in main-note when changing the corresponding sub-note. 

I may overlook something but is there any chance to realise this kind of behavior?

**Comment by windingwind** [comment]
If you mean this button:
![image](https://user-images.githubusercontent.com/33902321/194754276-72b41bcf-e260-4dd1-8dae-9d2661be42ed.png)

Then absolutely YES!

The link content and style are controlled by the template called "QuickInsert". Please update to the latest and replace it with the text below:
```js
${await new Promise(async (r) => {
  let newLines = [];
  const convertResult = await Zotero.Knowledge4Zotero.NoteUtils.convertNoteLines(
    subNoteItem,
    [],
    true
  );
  const subNoteLines = convertResult.lines;
  // Prevent note to be too long
  if (subNoteLines.join("\n").length > 100000) {
    Zotero.Knowledge4Zotero.ZoteroViews.showProgressWindow(
      "Better Notes",
      "The linked note is too long. Import ignored."
    );
    return;
  }
  const templateText =
    await Zotero.Knowledge4Zotero.TemplateController.renderTemplateAsync(
      "[QuickImport]",
      "subNoteLines, subNoteItem, noteItem",
      [subNoteLines, subNoteItem, noteItem]
    );
  newLines.push(templateText);
  const newLineString = newLines.join("\n");
  const notifyFlag = Zotero.Promise.defer();
  const notifierName = "insertLinkWait";
  Zotero.Knowledge4Zotero.events.addNotifyListener(
    notifierName,
    (event, type, ids, extraData) => {
      if (
        event === "modify" &&
        type === "item" &&
        ids.includes(noteItem.id)
      ) {
        notifyFlag.resolve();
        Zotero.Knowledge4Zotero.events.removeNotifyListener(notifierName);
      }
    }
  );
  await Zotero.Knowledge4Zotero.NoteUtils.modifyLineInNote(
    noteItem,
    (oldLine) => {
      Zotero.debug(oldLine);
      const params = Zotero.Knowledge4Zotero.NoteParse.parseParamsFromLink(link);
      const newLink = !params.ignore
        ? link + (link.includes("?") ? "&ignore=1" : "?ignore=1")
        : link;
      const linkIndex = Zotero.Knowledge4Zotero.NoteParse.parseLinkIndexInText(oldLine);
      Zotero.debug(linkIndex);
      return `${oldLine.slice(0, linkIndex[0])}${newLink}${oldLine.slice(
        linkIndex[1]
      )}\n${newLineString}`;
    },
    lineIndex,
    true
  );
  // wait the first modify finish
  await notifyFlag.promise;
  let hasAttachemnts = false;
  for (const _n of [subNoteItem, ...convertResult.subNotes]) {
    if (Zotero.Items.get(_n.getAttachments()).length) {
      hasAttachemnts = true;
      break;
    }
  }
  if (hasAttachemnts) {
    await Zotero.DB.executeTransaction(async () => {
      await Zotero.Notes.copyEmbeddedImages(subNoteItem, noteItem);
      for (const subNote of convertResult.subNotes) {
        await Zotero.Notes.copyEmbeddedImages(subNote, noteItem);
      }
    });
    await Zotero.Knowledge4Zotero.NoteUtils.scrollWithRefresh(
      Zotero.Knowledge4Zotero.NoteUtils.currentLine[noteItem.id]
    );
  }
})}
```
It is part of the plugin's code for embedding the linked note content. Be aware the APIs used in this template may change in future releases.

**Comment by yannick-boehm** [comment]
Unfortunately the following error appears when clicking the button with changed [QuickInsert] template:

![image](https://user-images.githubusercontent.com/102553711/194757863-a33ca195-1db2-4c55-bca2-dc7a944310f2.png)

At first glance I cannot find any missing curly braces.

**Comment by windingwind** [comment]
Please check for updates on the plugin page and update plugin to 0.7.7.

**Comment by yannick-boehm** [comment]
Awesome, works like a charme. Thank you very much.

**Comment by yannick-boehm** [comment]
the provided code snippet does not work anymore. 
Could you please help me out?

**Comment by windingwind** [comment]
The API `Zotero.Knowledge4Zotero.events` is renamed to `Zotero.Knowledge4Zotero.ZoteroEvents`. Replace it with the new API:

```js
${await new Promise(async (r) => {
  let newLines = [];
  const convertResult = await Zotero.Knowledge4Zotero.NoteUtils.convertNoteLines(
    subNoteItem,
    [],
    true
  );
  const subNoteLines = convertResult.lines;
  // Prevent note to be too long
  if (subNoteLines.join("\n").length > 100000) {
    Zotero.Knowledge4Zotero.ZoteroViews.showProgressWindow(
      "Better Notes",
      "The linked note is too long. Import ignored."
    );
    return;
  }
  const templateText =
    await Zotero.Knowledge4Zotero.TemplateController.renderTemplateAsync(
      "[QuickImport]",
      "subNoteLines, subNoteItem, noteItem",
      [subNoteLines, subNoteItem, noteItem]
    );
  newLines.push(templateText);
  const newLineString = newLines.join("\n");
  const notifyFlag = Zotero.Promise.defer();
  const notifierName = "insertLinkWait";
  Zotero.Knowledge4Zotero.ZoteroEvents.addNotifyListener(
    notifierName,
    (event, type, ids, extraData) => {
      if (
        event === "modify" &&
        type === "item" &&
        ids.includes(noteItem.id)
      ) {
        notifyFlag.resolve();
        Zotero.Knowledge4Zotero.ZoteroEvents.removeNotifyListener(notifierName);
      }
    }
  );
  await Zotero.Knowledge4Zotero.NoteUtils.modifyLineInNote(
    noteItem,
    (oldLine) => {
      Zotero.debug(oldLine);
      const params = Zotero.Knowledge4Zotero.NoteParse.parseParamsFromLink(link);
      const newLink = !params.ignore
        ? link + (link.includes("?") ? "&ignore=1" : "?ignore=1")
        : link;
      const linkIndex = Zotero.Knowledge4Zotero.NoteParse.parseLinkIndexInText(oldLine);
      Zotero.debug(linkIndex);
      return `${oldLine.slice(0, linkIndex[0])}${newLink}${oldLine.slice(
        linkIndex[1]
      )}\n${newLineString}`;
    },
    lineIndex,
    true
  );
  // wait the first modify finish
  await notifyFlag.promise;
  let hasAttachemnts = false;
  for (const _n of [subNoteItem, ...convertResult.subNotes]) {
    if (Zotero.Items.get(_n.getAttachments()).length) {
      hasAttachemnts = true;
      break;
    }
  }
  if (hasAttachemnts) {
    await Zotero.DB.executeTransaction(async () => {
      await Zotero.Notes.copyEmbeddedImages(subNoteItem, noteItem);
      for (const subNote of convertResult.subNotes) {
        await Zotero.Notes.copyEmbeddedImages(subNote, noteItem);
      }
    });
    await Zotero.Knowledge4Zotero.NoteUtils.scrollWithRefresh(
      Zotero.Knowledge4Zotero.NoteUtils.currentLine[noteItem.id]
    );
  }
})}
```

**Comment by SYH0323** [comment]
> If you mean this button: ![image](https://user-images.githubusercontent.com/33902321/194754276-72b41bcf-e260-4dd1-8dae-9d2661be42ed.png)
> 
> Then absolutely YES!
> 
> The link content and style are controlled by the template called "QuickInsert". Please update to the latest and replace it with the text below:
> 
> ```js
> ${await new Promise(async (r) => {
>   let newLines = [];
>   const convertResult = await Zotero.Knowledge4Zotero.NoteUtils.convertNoteLines(
>     subNoteItem,
>     [],
>     true
>   );
>   const subNoteLines = convertResult.lines;
>   // Prevent note to be too long
>   if (subNoteLines.join("\n").length > 100000) {
>     Zotero.Knowledge4Zotero.ZoteroViews.showProgressWindow(
>       "Better Notes",
>       "The linked note is too long. Import ignored."
>     );
>     return;
>   }
>   const templateText =
>     await Zotero.Knowledge4Zotero.TemplateController.renderTemplateAsync(
>       "[QuickImport]",
>       "subNoteLines, subNoteItem, noteItem",
>       [subNoteLines, subNoteItem, noteItem]
>     );
>   newLines.push(templateText);
>   const newLineString = newLines.join("\n");
>   const notifyFlag = Zotero.Promise.defer();
>   const notifierName = "insertLinkWait";
>   Zotero.Knowledge4Zotero.events.addNotifyListener(
>     notifierName,
>     (event, type, ids, extraData) => {
>       if (
>         event === "modify" &&
>         type === "item" &&
>         ids.includes(noteItem.id)
>       ) {
>         notifyFlag.resolve();
>         Zotero.Knowledge4Zotero.events.removeNotifyListener(notifierName);
>       }
>     }
>   );
>   await Zotero.Knowledge4Zotero.NoteUtils.modifyLineInNote(
>     noteItem,
>     (oldLine) => {
>       Zotero.debug(oldLine);
>       const params = Zotero.Knowledge4Zotero.NoteParse.parseParamsFromLink(link);
>       const newLink = !params.ignore
>         ? link + (link.includes("?") ? "&ignore=1" : "?ignore=1")
>         : link;
>       const linkIndex = Zotero.Knowledge4Zotero.NoteParse.parseLinkIndexInText(oldLine);
>       Zotero.debug(linkIndex);
>       return `${oldLine.slice(0, linkIndex[0])}${newLink}${oldLine.slice(
>         linkIndex[1]
>       )}\n${newLineString}`;
>     },
>     lineIndex,
>     true
>   );
>   // wait the first modify finish
>   await notifyFlag.promise;
>   let hasAttachemnts = false;
>   for (const _n of [subNoteItem, ...convertResult.subNotes]) {
>     if (Zotero.Items.get(_n.getAttachments()).length) {
>       hasAttachemnts = true;
>       break;
>     }
>   }
>   if (hasAttachemnts) {
>     await Zotero.DB.executeTransaction(async () => {
>       await Zotero.Notes.copyEmbeddedImages(subNoteItem, noteItem);
>       for (const subNote of convertResult.subNotes) {
>         await Zotero.Notes.copyEmbeddedImages(subNote, noteItem);
>       }
>     });
>     await Zotero.Knowledge4Zotero.NoteUtils.scrollWithRefresh(
>       Zotero.Knowledge4Zotero.NoteUtils.currentLine[noteItem.id]
>     );
>   }
> })}
> ```
> 
> It is part of the plugin's code for embedding the linked note content. Be aware the APIs used in this template may change in future releases.

大佬，请问这段粘贴到哪里呢？我直接在【编辑】→【模板】那里改quickinsert的代码不行。

**Comment by windingwind** [comment]
Notifier callback registration in `Zotero.Knowledge4Zotero.ZoteroEvents` is moved to `Zotero.Knowledge4Zotero.ZoteroNotifies`.

As I stated before, this template uses on inner APIs and you should not rely on it.

```ts
${await new Promise(async (r) => {
  let newLines = [];
  const convertResult = await Zotero.Knowledge4Zotero.NoteUtils.convertNoteLines(
    subNoteItem,
    [],
    true
  );
  const subNoteLines = convertResult.lines;
  // Prevent note to be too long
  if (subNoteLines.join("\n").length > 100000) {
    Zotero.Knowledge4Zotero.ZoteroViews.showProgressWindow(
      "Better Notes",
      "The linked note is too long. Import ignored."
    );
    return;
  }
  const templateText =
    await Zotero.Knowledge4Zotero.TemplateController.renderTemplateAsync(
      "[QuickImport]",
      "subNoteLines, subNoteItem, noteItem",
      [subNoteLines, subNoteItem, noteItem]
    );
  newLines.push(templateText);
  const newLineString = newLines.join("\n");
  const notifyFlag = Zotero.Promise.defer();
  const notifierName = "insertLinkWait";
  Zotero.Knowledge4Zotero.ZoteroNotifies.registerNotifyListener(
    notifierName,
    (event, type, ids, extraData) => {
      if (
        event === "modify" &&
        type === "item" &&
        ids.includes(noteItem.id)
      ) {
        notifyFlag.resolve();
        Zotero.Knowledge4Zotero.ZoteroNotifies.unregisterNotifyListener(notifierName);
      }
    }
  );
  await Zotero.Knowledge4Zotero.NoteUtils.modifyLineInNote(
    noteItem,
    (oldLine) => {
      Zotero.debug(oldLine);
      const params = Zotero.Knowledge4Zotero.NoteParse.parseParamsFromLink(link);
      const newLink = !params.ignore
        ? link + (link.includes("?") ? "&ignore=1" : "?ignore=1")
        : link;
      const linkIndex = Zotero.Knowledge4Zotero.NoteParse.parseLinkIndexInText(oldLine);
      Zotero.debug(linkIndex);
      return `${oldLine.slice(0, linkIndex[0])}${newLink}${oldLine.slice(
        linkIndex[1]
      )}\n${newLineString}`;
    },
    lineIndex,
    true
  );
  // wait the first modify finish
  await notifyFlag.promise;
  let hasAttachemnts = false;
  for (const _n of [subNoteItem, ...convertResult.subNotes]) {
    if (Zotero.Items.get(_n.getAttachments()).length) {
      hasAttachemnts = true;
      break;
    }
  }
  if (hasAttachemnts) {
    await Zotero.DB.executeTransaction(async () => {
      await Zotero.Notes.copyEmbeddedImages(subNoteItem, noteItem);
      for (const subNote of convertResult.subNotes) {
        await Zotero.Notes.copyEmbeddedImages(subNote, noteItem);
      }
    });
    await Zotero.Knowledge4Zotero.NoteUtils.scrollWithRefresh(
      Zotero.Knowledge4Zotero.NoteUtils.currentLine[noteItem.id]
    );
  }
})}
```

**Comment by GouPengyun** [comment]
现在这个方法插入几次笔记之后主笔记的文档层次就会被搞乱。原本设置的一级标题会莫名其妙的被变成引用的内容，如图。![1677398112230](https://user-images.githubusercontent.com/76691403/221398916-9c431cc1-9454-4412-9319-d38dda0a50ff.png)
