### ISSUE TITLE
[Feature] Annotation2Note: don't support nested list

### ISSUE THREAD

**Issue by Beau-Yang** [windingwind/zotero-better-notes#178]
注释转笔记功能在markdown基础语法上运行正常，但是它目前似乎并不支持嵌套列表的语法。

我在一个注释的评论内写了如下代码：

```markdown
- abc
  - 123 
```

我所期望的：

- abc
  - 123

我得到的：

- abc - 123

注意：

Zotero 和 Github 一样不支持使用 `Tab` 缩进文本。在这两个平台上， `Tab` 是用来选择整个输入框的。因此我用4个空格来替代常用的 `Tab` 并且我还尝试了根据 [Github Markdown Nested Lists](https://docs.github.com/cn/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#nested-lists) 来创建嵌套列表，但是两者都没有成功。

我认为对嵌套列表的支持是必要的，因为它是Markdown中最常用的标记之一。

最后，感谢你所做的一切。

---

The Annotation2Note works well on the basic markdown syntax but it seems that it doesn't support the nested list syntax now.

I wrote the code below in the comment of an annotation:

```markdown
- abc
  - 123
```

What I expected:

- abc
  - 123

What I got:

- abc - 123

Note that: 

Zotero doesn't support indenting texts using `Tab` like Github. `Tab` is used to choose the whole input box in these two platforms. So I replaced the common `Tab` with four spaces and I also tried to create a nested list according to [Github Markdown Nested Lists](https://docs.github.com/cn/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#nested-lists) but neither of them worked.

I think it is meaningful to support the nested list given that it is one of the most commonly used markups in Markdown.

Finally, thanks for everything you did.

**Comment by windingwind** [comment]
fixed.

The standard indenting is 4 spaces.

![image](https://user-images.githubusercontent.com/33902321/195393065-f93bef28-6beb-483b-8ceb-339e0b125cb0.png)
