### ISSUE TITLE
添加一个“在单独窗口编辑”的按钮

### ISSUE THREAD

**Issue by 1067237855** [windingwind/zotero-better-notes#179]
![1](https://user-images.githubusercontent.com/104330036/195378471-5556fc4a-917b-4b9b-933b-8d17ad076d16.png)

**Comment by windingwind** [comment]
将支持shift+点击以在单独窗口打开。不需要额外按钮

**Comment by 1067237855** [comment]
> 将支持shift+点击以在单独窗口打开。不需要额外按钮

这种“shift+点击以在单独窗口打开”的功能确实很方便，但是很难被人发现并使用吧？？？

**Comment by 1067237855** [comment]
> 另外提醒一下，标题在导出md时会转换成md的标题格式（# 标题），在标题内容中加入#号可能不必要。

谢谢大佬提醒，因为我不咋用md文件，所以对我没啥影响，## 标题 功能是另一个插件自动生成的，不太好改动
