### ISSUE TITLE
[Feature] Dispaly the status and position of the item notes added to the main note.

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-better-notes#18]
对于有多条注释但只有个别条生成了条目笔记并加入了主笔记的情况，并不能在pdf阅读器中判断哪条笔记加入了主笔记，只能在workspace中的主笔记中对比检索。
希望能够显示条目笔记**是否加入主笔记的状态**以及**加入的位置**。

**Comment by windingwind** [comment]
为主笔记添加一个tag是否合适？
对于子笔记，可以添加tag，或者在笔记文字内添加文本信息。但如果用户手动删除了主笔记中的某个链接，追溯到被删除的子笔记是困难的，需要对主笔记的所有子笔记实时监视并比较，造成较大的开销。需要思考是否值得这样做。
另外加入的位置是指具体的行数？

**Comment by lil-i321** [comment]
我觉得 在主笔记添加tag，并不太能提高pdf阅读器中的判断上述问题的效率。
确实需要考虑，实时监测链接是否有效，好像确实比较麻烦。
比如，此处是否方便显示一行字（主笔记的某个标题），1.即表示了插入到了哪个标题下，2.又表示了已经插入过主笔记了，3.点击这行字，又能够跳转到这个链接处。
![图片](https://user-images.githubusercontent.com/57334649/168810685-b4957369-e9af-4112-b5ca-be0eff397c34.png)

**Comment by windingwind** [comment]
需要考虑主笔记可能发生变化。某个笔记可能在主笔记a但不在主笔记b，或两处都在。当主笔记变化时，应如何行为？

**Comment by lil-i321** [comment]
> 需要考虑主笔记可能发生变化。某个笔记可能在主笔记a但不在主笔记b，或两处都在。当主笔记变化时，应如何行为？

能否这样：
step1. 鼠标一指向这行字，就弹出一个下拉框，包含了这条子笔记加入的所有主笔记即位置(标题)，比如有3处添加了如：主笔记a-介绍，主笔记b-结论，主笔记c-介绍；
step2. 若在主笔记b的结论中删除了这条笔记，鼠标指向这行字时，下拉框还会显示主笔记b-结论，但点击时，“主笔记b-结论”就会消失。
即，这行字会记录所有添加过的主笔记名及位置，点击会跳转，若在某主笔记某处中删除了，点击哪条记录，哪条记录才更新。
![图片](https://user-images.githubusercontent.com/57334649/168825726-e74d6a1d-067a-4487-8095-9ba9c9351e70.png)

**Comment by lil-i321** [comment]
@windingwind 
PS了个图，这样是不是更直观呢？
![图片](https://user-images.githubusercontent.com/57334649/168942245-509a0482-90ae-4995-a4f4-eaa9ef320f72.png)

**Comment by windingwind** [comment]
界面显示我想还是放在笔记编辑页面合适，并只在当前主笔记搜索。每次加入主笔记，都会将主笔记加入related

**Comment by lil-i321** [comment]
> 界面显示我想还是放在笔记编辑页面合适，并只在当前主笔记搜索。每次加入主笔记，都会将主笔记加入related

放在外面（条目笔记汇总页面）会不会更方便呢？这样就不用一条一条地点进去看是哪里related了。
希望不影响您的思路。

**Comment by hpxing** [comment]
我觉得没什么太大的必要，觉得有用的笔记肯定主动加入到主笔记了，我觉得这个主笔记就相当于我们写的文章，需要自己梳理自己建立逻辑关系等等，不能考虑太多自动化的东西，要不然还是个半成品，不利于整理思路~~
另外每个pdf的标注加入主笔记必须在pdf标注内生产note link: "zotero://note/u/CSMIP9QG/" 类似这个的东西，还在条目下面生产一个很短的笔记？？

**Comment by windingwind** [comment]
@hpxing 这个链接是为了建立注释-笔记的联系，避免重复创建笔记。生成很短的笔记只是一个被称为QuickNote的特性，为了方便将单个注释添加进主笔记。
除了QuickNote的方式，也可以通过其他途径建立笔记，包括zotero自带的一些功能。只要是笔记，就可以插入其链接到主笔记。

**Comment by lil-i321** [comment]
> 我觉得没什么太大的必要，觉得有用的笔记肯定主动加入到主笔记了，我觉得这个主笔记就相当于我们写的文章，需要自己梳理自己建立逻辑关系等等，不能考虑太多自动化的东西，要不然还是个半成品，不利于整理思路~~ 另外每个pdf的标注加入主笔记必须在pdf标注内生产note link: "zotero://note/u/CSMIP9QG/" 类似这个的东西，还在条目下面生产一个很短的笔记？？

注释数量多于有用的笔记呢？有些注释就是注释，第一次阅读时有些注释并不想并没有添加，第二次阅读时再想补充添加时却不知道哪条已经添加过了，也不知道添加到哪了，得去主笔记中查看有没有该条注释，不麻烦吗？
--如果有一个标记，能够显示出是否已经添加已经添加的位置，岂不很方便？

**Comment by windingwind** [comment]
@lil-i321 新版本已经支持双链，并可通过模板自定义反链的格式

**Comment by lil-i321** [comment]
> @lil-i321 新版本已经支持双链，并可通过模板自定义反链的格式

什么效果呢？试过了，没有效果呀。

**Comment by windingwind** [comment]
@lil-i321 
![image](https://user-images.githubusercontent.com/33902321/173178557-f947befe-6649-41cc-99bc-7a47eb0618a5.png)
新插入的子笔记链接可通过模板控制，在子笔记末尾添加插入的信息。默认是一个链接
