### ISSUE TITLE
优化笔记之间逻辑关系

### ISSUE THREAD

**Issue by Biogo-go** [windingwind/zotero-better-notes#180]
要是能在这个图谱基础之上，有标记可供选择来进一步构建逻辑关系，比如某个观点支撑另一个观点或者反对另一个观点，然后点击某个论点的时候，与另一个论点相连接的线 能够加粗显示或者用其他醒目的方式显示，这样就更好啦
![111](https://user-images.githubusercontent.com/96036991/195508349-1b79cfe2-8b90-47d5-b809-db258deefff4.png)

**Comment by windingwind** [comment]
目前思维导图主要依赖于标题层级来更新显示，要自定义关联的话，需要考虑怎么把设置的关联数据保存下来。可以讨论下这方面怎么实现：
- 这些关联信息应该存储在哪里？
- 一旦标题被删除或修改，关联信息如何保证正确生效？

**Comment by Shirley5** [comment]
如果能像marginnote一样可以在树状笔记图里手动调节各级笔记的层级就更好了！

**Comment by Joycoooi** [comment]
> 要是能在这个图谱基础之上，有标记可供选择来进一步构建逻辑关系，比如某个观点支撑另一个观点或者反对另一个观点，然后点击某个论点的时候，与另一个论点相连接的线 能够加粗显示或者用其他醒目的方式显示，这样就更好啦 ![111](https://user-images.githubusercontent.com/96036991/195508349-1b79cfe2-8b90-47d5-b809-db258deefff4.png)

这个思维导图做的很好看呀，可以讲一下吗🙏

**Comment by Joycoooi** [comment]
> 要是能在这个图谱基础之上，有标记可供选择来进一步构建逻辑关系，比如某个观点支撑另一个观点或者反对另一个观点，然后点击某个论点的时候，与另一个论点相连接的线 能够加粗显示或者用其他醒目的方式显示，这样就更好啦 ![111](https://user-images.githubusercontent.com/96036991/195508349-1b79cfe2-8b90-47d5-b809-db258deefff4.png)

想知道你是怎么设置的呀😁，是把一个topic点，分成基础研究，文献综述以及自己的理解部分吗，感激你这个逻辑做的很好，如果有时间的话，可以麻烦您讲一下吗，感谢🥹，刚刚没有表述清楚

**Comment by windingwind** [comment]
> 如果能像marginnote一样可以在树状笔记图里手动调节各级笔记的层级就更好了！

支持在标题列表中调整层级
