### ISSUE TITLE
[Bug] Refresh Editor = Deletes the note

### ISSUE THREAD

**Issue by NazimSerbest** [windingwind/zotero-better-notes#182]
Thanks for this great addon! I'm unfamiliar with coding, so please excuse my language.

I clicked 'Refresh Editor' under the 3-dot menu in Workspace. I was expecting this to refresh the preview mode, but instead the entire Main Note (except the Heading 1) was erased - hours of concentrated work gone. Can I save the note? It's already synced to my Zotero cloud.

Is this a bug, or did I do something wrong? I'm not sure how I can reproduce this in code. I could not find the event in the Error Console.

Also, most of the buttons of the addon are not working at the moment. I'm running Zotero 6.0.15 on Windows 11. For example, when I right-click a Zotero note and click Set Main Note, this does not work if the Workspace is closed. Or: When I click Preview in Workspace under the 3-dot menu for a Zotero note, nothing happens. Here's what it says in Error Console:

[JavaScript Error: "TypeError: event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
@resource://zotero/note-editor/editor.js:68673:19

[JavaScript Error: "TypeError: event.target.closest is not a function" {file: "resource://zotero/note-editor/editor.js" line: 68673}]
@resource://zotero/note-editor/editor.js:68673:19
 

-

**Comment by windingwind** [comment]
Hi,

Sorry for the data lost. If you do have the note synced, maybe you could ask for help in Zotero forums. Sorry I could not help if the problem cannot be reproduced. Proveding more information about what are you doing at that time would be helpful.

Are you currently putting the Zotero database in a cloud storage application, like Onedrive or iCloud, syncing directorythat will automatically sync the files under the directory? This is the most possible reason for your data loss. Please stop doing that.

The refresh button should not cause the note content to be lost. What it does is unbind and rebind the current note data to the note editor, which happend every time you open a note or select them in the library. 

You don't need to use the refresh unless you see the editor behaves strange, like unable to edit or the tables can not be focused.

**Comment by windingwind** [comment]
See https://www.zotero.org/support/zotero_data and https://www.zotero.org/support/kb/data_directory_in_cloud_storage_folder

**Comment by NazimSerbest** [comment]
Thank you for the links windingwind. I'll keep you posted if I can restore the date, or reproduce what happened with the Refresh Editor button.

I am not using a cloud storage application. I just use the Zotero cloud (i.e. the storage that Zotero sells).

Thanks also for the clarification about what the refresh button is supposed to do.

**Comment by windingwind** [comment]
I confirm refreshing the note editor will cause data loss in some cases, but it's hard to track. The most possible reason is the data save is delayed in Zotero.

I've added a save before refreshing. Thanks for your feedback.
