### ISSUE TITLE
collect annotations by color无法导出插入到主笔记，请问怎么怎么操作的啊

### ISSUE THREAD

**Issue by DocAndymomo** [windingwind/zotero-better-notes#183]
Thank you very much.

I confirm that the code for a adding other colours is working.
I would just change "Perple" to "Purple" in the code.
What happens to the templates when Better Notes is updated? Are the modifications deleted to put the new template?

I can also add templates in any notes now.

_Originally posted by @mjthoraval in https://github.com/windingwind/zotero-better-notes/issues/177#issuecomment-1279962475_

**Comment by windingwind** [comment]
please describe in detail.

**Comment by llity** [comment]
通过color插入笔记确实没发生任何变化。

**Comment by windingwind** [comment]
> 通过color插入笔记确实没发生任何变化。

As I said, please describe in DETAIL.

**Comment by llity** [comment]
corner
I want to insert notes by annotated color, but nothing happens, just a 'dialog' in the bottom right corner.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/11771112/197182403-9dc2ac90-4bf5-4b20-9daf-e6a1b1c873ba.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/11771112/197182312-0415fde2-de86-40b5-9387-42e2bc096e87.png">

**Comment by windingwind** [comment]
@llity There would be a popup window asking to to choose which item(s) to be incluede in template running. Please check if it is occlueded by other windows or show up in another screen.

![image](https://user-images.githubusercontent.com/33902321/197224316-8166868f-d0b0-4602-b7b3-45b80316bfeb.png)

**Comment by mjthoraval** [comment]
I can reproduce the problem.
If the Workspace is opened, the insert annotations by color is working. However, if you close the workspace, it behaves as reported by @llity.
It seems to trigger the following error:
`[JavaScript Error: "TypeError: editor is undefined" {file: "chrome://knowledge4zotero/content/scripts/index.js line 47579 > AsyncFunction" line: 36}] `
Let me know if you can reproduce.

**Comment by windingwind** [comment]
Thanks @mjthoraval . Templates that adds annotations to an existing note requires the note editor is alive. So open the note editor(like workspace window), and it should work as expected.

**Comment by mjthoraval** [comment]
By "the note editor is alive", do you mean opening the Workspace in a tab in Zotero?
In that case, is there any way around, to be able to insert templates with annotations without having to open the Workspace?
Otherwise, maybe an error popup should come out to explain why nothing happens?
As I am trying to use this plugin without the Main Note or the Workspace, it would be nice to get the features working even without opening the Workspace.

**Comment by windingwind** [comment]
Theoretically speaking, note editor can be in workspace, right sidebar of pdf reader, or standalone window.

So it should work in other note editors, besides the workspace note editor.

I’ll add an error popup in the next release. Thanks!

**Comment by mjthoraval** [comment]
There may be a misunderstanding here. I really mean the Workspace when I say that the Workspace must be open for the template to insert annotations by color to work, not any note editor.
Here is the [screen recording](https://drive.google.com/open?id=11xhFgmxiHAAhFK5JHByOoOIRPw08y_EZ&authuser=mjthoraval%40gmail.com&usp=drive_fs) showing the problem.

**Comment by llity** [comment]
@mjthoraval Thanks, I just opened the workspace, and it works fine. The error occurred as you mentioned above. :)

**Comment by llity** [comment]
Is it possible to insert annotations by (red, yellow, etc.) color?

**Comment by llity** [comment]
I will modify the code for each annotation color. It‘s convenient for collecting the important annotations.

**Comment by windingwind** [comment]
> @windingwind There may be a misunderstanding here. I really mean the Workspace when I say that the Workspace must be open for the template to insert annotations by color to work, not any note editor. Here is the [screen recording](https://drive.google.com/open?id=11xhFgmxiHAAhFK5JHByOoOIRPw08y_EZ&authuser=mjthoraval%40gmail.com&usp=drive_fs) showing the problem.

@mjthoraval 

If you run templates via the Zotero menu -> Edit -> insert templates, they will be inserted into the main note. If no note editor of the main note is alive, then the template will be copied to the clipboard.

Some templates require an active note editor. That's why it doesn't work if you try to insert annotations to the main note when there are no active note editors of the main note.

A hint would be great. Thanks for the suggestion.

**Comment by windingwind** [comment]
Resolved. Please feel free to reopen.

**Comment by windingwind** [comment]
You may need to remove the old template and then restart Zotero to update the template after updating the plugin.
