### ISSUE TITLE
[Feature] No note suffix on first export

### ISSUE THREAD

**Issue by davidoskky** [windingwind/zotero-better-notes#184]
**Is your feature request related to a problem? Please describe.**
I export notes to md and use them in an external editor.
I don't like that the notes have the suffix because it makes the filename more difficult to read.
For most articles, I have just one note and I don't have a lot of articles with the same title, thus the suffix is useless in most cases.

**Describe the solution you'd like**
Would it be possible to check if a file with the same name already exists in the folder and only in that case add the suffix to the filename?

**Describe alternatives you've considered**
Keep it as is, I cannot change the filenames manually since that would cause syncing problems and I don't want to remove the suffix altogether to prevent loss of data.

**Comment by windingwind** [comment]
> Would it be possible to check if a file with the same name already exists in the folder and only in that case add the suffix to the filename?

Thanks for the suggestion. The syncing system is going to be totally re-designed, though it will take months to finish. I don't have enough time.😢

**Comment by davidoskky** [comment]
Thank you for your great work @windingwind, I'd like to help but I have no experience with javascript....
If you could point me at some simple issue to tackle I might give it a try.

**Comment by windingwind** [comment]
Discussing about the details of fetures and providing ideas is also big support. 

In the futrue syncing system, the biggest problem is
- The citations/annotations in note cannot be modified, while their corrsponding MD segments might be modified or deleted;
- The conficts between MD and note may occur, especially when there are modifications in multiply devices' Zotero.

If you are interested in the syncing, suggestions would be a great help.

**Comment by windingwind** [comment]
As this issue is resolved, I'll close it.

Discussing the behavious of the futrue syncing system in #147.
