### ISSUE TITLE
希望恢复对公式支持

### ISSUE THREAD

**Issue by heimi98** [windingwind/zotero-better-notes#185]
虽然最新版 Zotero 为笔记添加了公式功能，但不能在引用原文的文字内部渲染公式。希望能恢复之前的公式功能。

**Comment by Narip2** [comment]
Install the add-on, but I cannot see Latex button while in your document there is such a button!
And normally people will copy latex from other places which will lead `shift+enter` very tedious!

**Comment by windingwind** [comment]
如果要使用旧版公式功能，可安装旧版本插件并关闭自动更新。
对于现有公式功能的问题或需求，请向zotero官方论坛反馈。
