### ISSUE TITLE
重新安装插件后工作区内home按钮突然不能切换主笔记[Bug]

### ISSUE THREAD

**Issue by mintmilk** [windingwind/zotero-better-notes#186]
不知道具体原始是改变了zotero工作目录的原因还是重新安装插件的原因

**Comment by windingwind** [comment]
请提供插件版本和zotero版本号，及操作步骤和截图

**Comment by windingwind** [comment]
home按钮记录了最近访问的主笔记，因此重新安装插件后可能历史记录被清除。当你设置过其他主笔记以后，会出现在弹出菜单中。

**Comment by windingwind** [comment]
将暂时关闭issue。如果设置过不同的主笔记后仍然出现该问题，请再打开

**Comment by conquerzzz** [comment]
zotero6.0.15 插件0.7.12
已经设置过不同主笔记，但在home按钮的弹出菜单中只有打开工作区的选项，没有其他选项
![image](https://user-images.githubusercontent.com/91196737/197383907-283fe0ed-daec-4c3f-8bef-7bd3abd33c6c.png)

**Comment by conquerzzz** [comment]
可能与插件更新有关
