### ISSUE TITLE
[Bug]本地pdf工作区bug

### ISSUE THREAD

**Issue by OrangeLuckKing** [windingwind/zotero-better-notes#187]
**Describe the bug**
对导入的本地pdf做笔记后，添加到工作区中的次级笔记界面。点击跳转到原文笔记界面并不响应！！！
直接在网站导入的pdf工作正常。

**Comment by windingwind** [comment]
https://zotero.yuque.com/books/share/f3fe159f-956c-4f10-ade3-c87559cacb60/yul2qm

![image](https://user-images.githubusercontent.com/33902321/197221845-7c69b013-ceef-46ad-90c7-80583c26ea27.png)

**Comment by OrangeLuckKing** [comment]
明白了，不过支持无父条目PDF，也可链接打开本地导入的PDF就更加方便了，谢谢 。

**Comment by windingwind** [comment]
无父条目的pdf，无法创建子笔记。在这样的情况下无法确定笔记具体归属到哪个条目。所以没法做到。

**Comment by windingwind** [comment]
导入的pdf，英文的可利用zotero自带功能抓取元数据，中文可利用茉莉花插件获取父条目元数据，其他的可自行建立父条目。

**Comment by OrangeLuckKing** [comment]
明白了 谢谢
