### ISSUE TITLE
safe name export, note md filenames contain U+201C [Bug]

### ISSUE THREAD

**Issue by sjgknight** [windingwind/zotero-better-notes#188]
**Describe the bug**

Exported note filenames contain forbidden characters.

**To Reproduce**

I'm exporting a set of notes with a particular tag, using  'Export notes and subnotes to markdown'. (This actually seems to select all item notes, even if they're not selected in the interface). 

Many of the exported notes will have U+201C (not "), at the start, because the notes are created from annotations, and the first line of the note is used to create the note title. Some item titles also start with " so this may apply to those/notes that use the item title too. 

Such notes cannot be found on my filesystem. I'm trying to read them in R and merge, etc, and can't rename or open from there.

**Expected behavior**

I'm sure there are a few workarounds, but one would simply be either to strip characters on export, or/and to give the option to use the note ID as filename.md. 

**Desktop (please complete the following information):**

 - OS: Windows 10

**Comment by windingwind** [comment]
> either to strip characters on export, or/and to give the option to use the note ID as filename.md.

Yes. As these characters are allowed in filenames (otherwise the file could not be created correctly), we keep them as is by default.

You could edit the ExportMDFileName template and do whatever you need to process the filename.
