### ISSUE TITLE
Set collapses as a default in the left panel 

### ISSUE THREAD

**Issue by virologist** [windingwind/zotero-better-notes#19]
Hi, @windingwind 

Can you set the left panel to collapse status as a default (as shown as the below)? 
![image](https://user-images.githubusercontent.com/54756814/168818853-d6552f98-c3dd-4fef-a4f6-f7cf843cc48f.png)
So, in this way, we can jump to a certain part as soon as possible.

Yang

**Comment by windingwind** [comment]
Thanks. Planned.
