### ISSUE TITLE
需要同时阅读pdf和做笔记时，笔记段落和图片可能会太长，想要阅读笔记下一节时很不方便，容易被打断思路

### ISSUE THREAD

**Issue by helloddllk** [windingwind/zotero-better-notes#190]
你好，有时候需要同时阅读pdf和做笔记，段落和图片可能会太长，想要阅读下一部分时很不方便，容易被打断思路
![image](https://user-images.githubusercontent.com/101552628/197315645-63b66ae0-940f-4e0f-a7d4-7ada0c128d8e.png)
![image](https://user-images.githubusercontent.com/101552628/197315654-b35ac7d9-4a33-4c7a-ae7c-3c92a1aad677.png)

可不可在笔记中增添一个段落和图片的折叠和展开按钮，下图中只能展开一级，要是像3.1，3.12等等这样的小节也能展开是最好的了
![image](https://user-images.githubusercontent.com/101552628/197315770-de99a160-323e-4dd7-9cd4-e6d162e130a0.png)

这个插件非常好用，期待作者的更新

**Comment by windingwind** [comment]
可以点击左侧导航栏快速定位节位置。

所有标题格式的内容都可以显示，最多支持六级标题

![image](https://user-images.githubusercontent.com/33902321/197316247-aacc898e-c897-4902-91d4-f002b241a985.png)

**Comment by helloddllk** [comment]
感谢作者的回复，我说的是在这种工作情形下，因为要边看边读，所以不可能切换到工作区
![image](https://user-images.githubusercontent.com/101552628/197316334-25ff633d-cd78-42c0-8c54-59c9630db5e7.png)

**Comment by helloddllk** [comment]
感谢作者的回复，你说的这个功能我知道，这个应该是文章的内容的定位，我想的是笔记内部的内容能不能折叠，就是我圈出来的地方
![image](https://user-images.githubusercontent.com/101552628/197316740-261b13b6-8c8d-4ccc-83cd-249f79ac5ae0.png)

而且我想要的是如下这种效果，当然不限于段落，其他如表格和图片都能这样是最好的，感觉这个功能可以有效提高做笔记和阅读笔记的效率，不知道方不方便实现

- 折叠前

![Snipaste_2022-10-22_11-16-45](https://user-images.githubusercontent.com/101552628/197316831-e17d689d-d653-4afa-b06c-8e8beab76b1a.png)

- 折叠后

![Snipaste_2022-10-22_11-18-36](https://user-images.githubusercontent.com/101552628/197316849-ad502de1-1a1b-4c23-983c-80453b1f45de.png)

**Comment by windingwind** [comment]
很抱歉，这个收起做不了，至少没法以插件形式做。有需要可向zotero官方提需求。

**Comment by windingwind** [comment]
由于未计划，将关闭。感谢反馈，有需要可再打开。
