### ISSUE TITLE
[Item]This template is to collect annotations and notes grouped only by tags

### ISSUE THREAD

**Issue by brunollave** [windingwind/zotero-better-notes#191]
## Template Type

Item

## Desired Template Performance

This template is to collect annotations and notes grouped only by tags. It would be ideal ig we can make it works without an input at the begining, instead of that the script should take all the tags of the selected files.

## Current Template

```js
// @beforeloop-begin
${(()=>{
sharedObj.tagRaw = prompt("Please input tags. Split with '',:", "");
return "";
})()}
// @beforeloop-end
// @default-begin
${await new Promise(async (r) => {
  async function getAnnotation(item) {
    try {
      if (!item || !item.isAnnotation()) {
        return null;
      }
      let json = await Zotero.Annotations.toJSON(item);
      json.id = item.key;
      delete json.key;
      for (let key in json) {
        json[key] = json[key] || "";
      }
      json.tags = json.tags || [];
      return json;
    } catch (e) {
      Zotero.logError(e);
      return null;
    }
  }

  async function getAnnotationsByTag(_item, tag) {
    let annots = _item.getAnnotations();
    annots = tag.length? 
      annots.filter((_annot) => _annot.getTags().map(_t=>_t.tag).includes(tag)) :
      annots;
    let annotations = [];
    for (let annot of annots) {
      const annotJson = await getAnnotation(annot);
      annotJson.attachmentItemID = _item.id;
      annotations.push(annotJson);
    }
    const editor =
      await Zotero.Knowledge4Zotero.knowledge.getWorkspaceEditorInstance();
      await editor.importImages(annotations);
      return Zotero.EditorInstanceUtilities.serializeAnnotations(annotations);
    }
  const attachments = Zotero.Items.get(topItem.getAttachments()).filter((i) =>
    i.isPDFAttachment()
  );
  let res = "";
  if(!sharedObj.tagRaw){
    return;
  }
 for (let attachment of attachments) {
    for(tag of sharedObj.tagRaw.split(",").filter(t=>t.length)){
      res += `<h1>Tag: ${tag}</h1>`;
      const tags = (await getAnnotationsByTag(attachment, tag)).html
      res += tags ? tags : "<p>No result</p>";
  }
  }
  r(res);
})}
// @default-end

```

**Comment by windingwind** [comment]
Should the collected annotations and notes with the same tag be grouped by their parent items? Maybe an example of what the innput and result should be would be helpful.

**Comment by brunollave** [comment]
Hello @windingwind thanks for your message. 

Yes, the idea is to group annotations and notes just by tags. Identify all the annotations and notes of the selected files, then group the data by tags and then use each tag as header line and the annotations and notes as part of the paragraph in order to obtain a similar Structure like this:

TAG1:
   Content1A (Author 1b...)  
   Content1A (Author 1c...)  
   Content1A (Author 1d...)  

TAG2:
   Content1A (Author 2b...)  
   Content1A (Author 2c...)  
   Content1A (Author 2d...)  

Thanks for the support.

**Comment by windingwind** [comment]
@brunollave 

https://github.com/windingwind/zotero-better-notes/issues/85#issuecomment-1212751592

See the last template: [Item] all annotations and notes by tag

**Comment by Kapri2725** [comment]
I'm using Zotero + Better Notes (3.0.5).

I saw the item template on github:
"[Item]This template is to collect annotations and notes grouped only by tags #191"
Oct 22, 2022

AND
[Item] all annotations and notes by tag
Author: [@windingwind](https://forums.zotero.org/profile/windingwind)
Discuss: #191
Aug 12, 2022

But when I try to use this template I receive the following error:

"Template [Item] all annotations and notes by tag Error: ReferenceError: editor is not defined"

Is this template still maintained?

I think this is one of the most important features for zotero: to be able to gather knowledge (annotations) about specific topic (tag) across several sources (items) and to cross examine those annotations would be very useful.

**Comment by windingwind** [comment]
> Is this template still maintained?

no, unfortunately. this is based on a very old version (as you can see, 4 years ago) of the plugin. Please see other template in the discussions.

**Comment by Kapri2725** [comment]
Sorry but i don't seem to find any template that has this features, could you help me?

> > Is this template still maintained?
> 
> no, unfortunately. this is based on a very old version (as you can see, 4 years ago) of the plugin. Please see other template in the discussions.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/236

**Comment by Kapri2725** [comment]
Sorry maybe I was not very clear.

That note template #236 collects notes and annotations by item and then tag, what I'm looking for is for a template that collects notes and annotations by a specific tag and then item similarly to #241 but the latter collects by all tags and I wan't to select the specific tags.
