### ISSUE TITLE
[Bug]行内插入latex块导致中文无法输入

### ISSUE THREAD

**Issue by littleheuer** [windingwind/zotero-better-notes#192]
**bug描述**
当使用$$符号在行内插入latex公式时，若使用键盘将光标在代码块内外移动，将无法输入中文，只能鼠标点击代码块才能重新输入

**操作**
1. 在行内键入"$[任意公式]$"
2. 使用键盘的left或right在代码块内外移动
3. 稳定触发bug

**预期效果**
光标移动不会影响中文输入

**截图**
![GIF](https://user-images.githubusercontent.com/38415542/197327992-b20936da-cd7f-440c-9e67-7b04be23090e.gif)

**系统及插件版本**
 - OS: win11
 - Version 0.7.12

**Comment by windingwind** [comment]
与插件无关。请向zotero社区反馈。
