### ISSUE TITLE
Extract Annotations to Item Note [Feature]

### ISSUE THREAD

**Issue by Beau-Yang** [windingwind/zotero-better-notes#194]
As for me, my workflow is to make annotations of a paper firstly, write its item note and finally collect all item notes into one main note. So I think it's more meaningful if BN can support extracting annotations (including converting its content to markdown format) to the item note. For now, the "Add Item Note from Annotations" provided by Zotero can not convert annotation contents to markdown format and doesn't support templates.

Workflow: `Paper Annotation -> Paper Item Note -> Subject Main Note`

What I need is a way to achieve the process of `Paper Annotation -> Paper Item Note`. (collect annotations by color or tag)

---

What's more, could BN also support the use of templates in the export process? It can be more convenient for those who want to use other note-taking apps to manage notes from Zotero.

For example, Obsidian supports the callout syntax. So it's very nice if we can convert the notes of Zotero to the corresponding codes like this according to its color.

```markdown
> [!note] NoteTitle # red: note; blue: info, ...
> > Paper Cited Content
> Note Content
```

Thanks for everything you did!

**Comment by windingwind** [comment]
> "Add Item Note from Annotations" provided by Zotero can not convert annotation contents to markdown format

Zotero note editor is NOT based on markdown. You can export notes to markdown.

> convert the notes of Zotero to the corresponding codes like this according to its color

What do you mean by referring to `its color`? Notes don't have color.

**Comment by Beau-Yang** [comment]
1. What I mean is converting the markdown syntax in the annotation comments like the 'Quick Note from Annoation' part. The difference is collecting the results to the item note instead of a quick note.

2. Sorry for the confusion. What I want to say is the color of the annotations.

**Comment by windingwind** [comment]
Yes. If you are familiar with programming, it would be easy to integrate `QuickNoteV3`'s MD parsing to `collect annotations by color` template.

If you need further help, please let me know.

**Comment by windingwind** [comment]
As there is no more update, I'll close this issue.
