### ISSUE TITLE
[Bug]无法设置主笔记，创建一个新的笔记设置为主笔记失败。

### ISSUE THREAD

**Issue by donkeyYH** [windingwind/zotero-better-notes#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
> A clear and concise description of what the bug is.
> If applicable, add screenshots to help explain your problem.

**Comment by donkeyYH** [comment]
A video has been recorded to illustrate the problem. Tried restarting zotero, as well as reinstalling the plugin and lowering the plugin version also did not work.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] [Bug]无法设置主笔记，创建一个新的笔记设置为主笔记失败。 (Issue #195)





  
A clear and concise description of what the bug is.
 If applicable, add screenshots to help explain your problem.

**Comment by windingwind** [comment]
i can’t see the video. please drag it into the github issue comment box.

**Comment by donkeyYH** [comment]
https://user-images.githubusercontent.com/92150903/197451295-ea261daa-013d-4d80-aeb0-a52988db5c12.mp4

**Comment by windingwind** [comment]
are these notes deleted when you try to set them as main note?

please go to help-debug output-view output and then try to set these notes as main note and paste/upload the debug output here.

**Comment by donkeyYH** [comment]
are these notes deleted when you try to set them as main note? No.
D1772318009

**Comment by donkeyYH** [comment]
0.7.12

**Comment by donkeyYH** [comment]
[JavaScript Error: "Error 413 for item CD9XRTNH in 我的文库:

ZoteroObjectUploadError: Note '差异 模拟软件的差异  OpenFOAM  FLuent 风雪流的模拟...' too long for item '11649500/CD9XRTNH'"]

[JavaScript Error: "Note '差异 模拟软件的差异  OpenFOAM  FLuent 风雪流的模拟...' too long for item '11649500/CD9XRTNH'" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1357}]

[JavaScript Error: "Made no progress during upload -- stopping" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1416}]

[JavaScript Error: "Made no progress during upload -- stopping" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1416}]

version => 6.0.15, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.15, extensions => Zutilo Zotero 工具箱 (3.10.0, extension), Zotero LibreOffice Integration (6.0.2.SA.6.0.15, extension), Zotero Word for Windows Integration (6.0.1.SA.6.0.15, extension), ZotFile (5.1.2, extension), Better BibTex for Zotero (6.7.27, extension), Zotero PDF Translate (0.8.28, extension), Zotero AutoIndex (5.0.9, extension), Zotero Better Notes (0.7.12, extension)

(3)(+0059445): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(3)(+0000007): {Zutilo} Mon Oct 24 2022 14:06:40 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:40 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:40 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:40 GMT+0800: targetItems: 0

(3)(+0000720): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(3)(+0000013): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000001): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000386): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000001): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000126): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:06:41 GMT+0800: targetItems: 0

(3)(+0000951): Knowledge4Zotero: onEditorEvent setMainNote

(3)(+0000000): Knowledge4Zotero: setMainNote

**Comment by donkeyYH** [comment]
[JavaScript Error: "Error 413 for item CD9XRTNH in 我的文库:

ZoteroObjectUploadError: Note '差异 模拟软件的差异  OpenFOAM  FLuent 风雪流的模拟...' too long for item '11649500/CD9XRTNH'"]

[JavaScript Error: "Note '差异 模拟软件的差异  OpenFOAM  FLuent 风雪流的模拟...' too long for item '11649500/CD9XRTNH'" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1357}]

[JavaScript Error: "Made no progress during upload -- stopping" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1416}]

[JavaScript Error: "Made no progress during upload -- stopping" {file: "chrome://zotero/content/xpcom/sync/syncEngine.js" line: 1416}]

version => 6.0.15, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.15, extensions => Zutilo Zotero 工具箱 (3.10.0, extension), Zotero LibreOffice Integration (6.0.2.SA.6.0.15, extension), Zotero Word for Windows Integration (6.0.1.SA.6.0.15, extension), ZotFile (5.1.2, extension), Better BibTex for Zotero (6.7.27, extension), Zotero PDF Translate (0.8.28, extension), Zotero AutoIndex (5.0.9, extension), Zotero Better Notes (0.7.12, extension)

(3)(+0049151): updateOCRStyleMenu

(3)(+0004212): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(3)(+0000005): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000001): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000682): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(3)(+0000014): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000001): {Zutilo} Mon Oct 24 2022 14:07:36 GMT+0800: targetItems: 0

(3)(+0000310): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000233): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000000): {Zutilo} Mon Oct 24 2022 14:07:37 GMT+0800: targetItems: 0

(3)(+0000880): Knowledge4Zotero: onEditorEvent setMainNote

(3)(+0000000): Knowledge4Zotero: setMainNote

**Comment by windingwind** [comment]
fixed.

**Comment by donkeyYH** [comment]
I don't understand what you mean

**Comment by windingwind** [comment]
I just fixed this bug and released a new version of the plugin.

**Comment by donkeyYH** [comment]
Thanks
