### ISSUE TITLE
[Bug] Sometimes can not input with chinese input method after using latex$

### ISSUE THREAD

**Issue by YiHui-Liu** [windingwind/zotero-better-notes#197]
**Describe the bug**
Sometimes can not input with chinese input method (I am using Microsoft Pinyin input method) after using latex$

**To Reproduce**
1. input a formula like $x(i;\delta t)$
2. change IME to Microsoft Pinyin IME, can not input

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: Zotero
 - Version: 6.0.15
 - Plugins:
   * Zotero Better Notes 0.7.9
   * Jasminum 0.2.0
   * Sci-Hub Plugin for Zotero 1.4.4
   * Zotero IF 1.4.7
   * Zotero PDF Translate 0.8.25

**Comment by windingwind** [comment]
After zotero 6.0.15, the math is controlled by the Prosemirror editor, not this plugin. Please report to the Zotero forums.
