### ISSUE TITLE
增加一键引入metadata功能

### ISSUE THREAD

**Issue by SeaCheChe** [windingwind/zotero-better-notes#20]
设置一个按钮能将某篇文章的metadata（如article title、Journal name、IF、authors、published year、tags等）引入到Knowledge中，这样的话，对于笔记的完整性会更好

**Comment by windingwind** [comment]
以什么样的格式引入？这可能需要一个相对复杂的设置界面，后续考虑实现

**Comment by SeaCheChe** [comment]
格式上还真没有想法，只要有办法引入就可以的，类似于zotero导入obsidian引入Metadata的方式就可以的

**Comment by windingwind** [comment]
见#23 ，可以引入元数据，并且格式高度自由
欢迎对新功能提出意见，并分享你的模板！

**Comment by windingwind** [comment]
鉴于笔记模板功能已经能够满足该功能，将关闭issue。

**Comment by hymsmmu** [comment]
![屏幕截图 2022-08-26 164513](https://user-images.githubusercontent.com/112151799/186863833-89aca5e3-aed2-43d6-bc2d-cee66f491118.png)

**Comment by hymsmmu** [comment]
> 鉴于笔记模板功能已经能够满足该功能，将关闭issue。

请问现已将右侧列表格中文字左对齐，但为什么有的文字左边还是有空格呢？
![屏幕截图 2022-08-26 164513](https://user-images.githubusercontent.com/112151799/186865816-fd9b9947-538f-4bcc-9587-929bb08dc1e3.png)
