### ISSUE TITLE
[Feature]请问可以添加给不同颜色的高亮设置快捷键的功能吗

### ISSUE THREAD

**Issue by ellya00** [windingwind/zotero-better-notes#202]
**Is your feature request related to a problem? Please describe.**
在阅读的时候想用数字快捷键快速标记不同颜色文本，但是只能通过鼠标点击选择

**Describe the solution you'd like**
是否可以添加设置快捷键功能呢

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
alt+4可以切换高亮颜色。
插件主要功能围绕笔记，对于PDF阅读器的功能需求与插件无关，建议向zotero论坛提建议。

**Comment by ellya00** [comment]
> alt+4可以切换高亮颜色。 插件主要功能围绕笔记，对于PDF阅读器的功能需求与插件无关，建议向zotero论坛提建议。

**Comment by ellya00** [comment]
谢谢解答～

**Comment by ellya00** [comment]
> 谢谢解答～
