### ISSUE TITLE
添加条目笔记

### ISSUE THREAD

**Issue by Keyman4** [windingwind/zotero-better-notes#203]
## 条目笔记-macos

条目笔记-macos

## Desired Template Performance

中文论文好像不能添加条目笔记？

## Current Template

```js
// Paste your template here
```

**Comment by windingwind** [comment]
与中文论文无关。条目笔记需要在条目下，请为pdf创建父条目。

**Comment by windingwind** [comment]
另外这个issue与笔记模板无关，不需要标记为笔记模板相关问题。
