### ISSUE TITLE
[Feature] dark mode for MacOS

### ISSUE THREAD

**Issue by toorukt** [windingwind/zotero-better-notes#204]
I'm using zotero-night plugin and userChome.css to make zotero displayed in dark mode on Mac.
However, it seems that these methods are not work properly for better-notes workplace.
I found it is able to edit `extension.zotero.note.css` to customize note window theme but have no idea what I should do.
Could you please consider adding a native dark mode inside better-notes?
Or may I ask some advices on how to customize it by myself?
I really appreciate for your time!

**Comment by windingwind** [comment]
Sorry but I do not have time to maintain an extra dark mode... Is anyone interested in this?

**Comment by woaixuexixuexi** [comment]
Windows also needs it！🙏

**Comment by evangelos-ch** [comment]
> Sorry but I do not have time to maintain an extra dark mode... Is anyone interested in this?

[tefkah/zotero-night](https://github.com/tefkah/zotero-night) is getting fairly popular and adds a much needed cross-platform dark mode to Zotero. I know it's improved the app for the better for me, so integrating with it or adding some form of dark mode to Better Notes so it can be consistent would be great! It is currently the only part of the UI that's not in dark mode for me.

Totally understand if it would be too much hassle though.

**Comment by windingwind** [comment]
If you are using zotero-night, it should be possible to automatically switch to dark mode, as long as the night plugin recognizes my pages. Maybe you could post an issue there? I would be glad to help.

The only one elements need to be taken care of by Zotero night is the workspace’s note editors. I have a dark mode for the mindmaps and treeview, which is just not enabled.
