### ISSUE TITLE
Latex math equation editing causes Zotero collapse[Bug]

### ISSUE THREAD

**Issue by EE-SIS** [windingwind/zotero-better-notes#205]
**Describe the bug**
After editing several latex equations in betternote, the Zotero would not response and then collapse.

**To Reproduce**
1. Insert a math equation as $plain Tex$.
2. Edit normal text on sides of the equation. e.g. backspace redundant blank in front of the equation
3. Not responding happens. (not sure if related to number of links (~40) and citations (~100) in the other part of Note, or add-ons problem)

**Desktop (please complete the following information):**
 - OS: win10

**Comment by windingwind** [comment]
If you are NOT using Better Notes <=0.6.29 and Zotero <= 0.6.14, the collapse is not related to this plugin. Please check that.

**Comment by windingwind** [comment]
If you are using Zotero >= 0.6.15, please report to the Zotero forums: https://forums.zotero.org/discussions
If no further updates, I'll close this issue.

**Comment by YiHui-Liu** [comment]
Similar bugs of this problem in Zotero forums：
* [Why zotero always crash after finishing the input of formula?
](https://forums.zotero.org/discussion/102869/why-zotero-always-crash-after-finishing-the-input-of-formula)
* [Note editor: Can't continue to use input method editor after entering inline math](https://forums.zotero.org/discussion/100416/note-editor-cant-continue-to-use-input-method-editor-after-entering-inline-math)
