### ISSUE TITLE
Zotero PDF reader

### ISSUE THREAD

**Issue by abon556** [windingwind/zotero-better-notes#207]
Winding 你好，
我想请问一个Zotero的使用问题，

在Zotero中看外文文献的时候，文章中会有引用文献的数字小标号，例如[1]这样。
然我后想看[1]引用的那篇文献的话，我就需要点一下这个超级链接，然后pdf浏览器就会跳到文末的参考文献位置去。
我想返回刚才的阅读的地方就要手动拉回去，如果文章篇幅长的话，还不一定能马上找到，致使阅读思路中断。

但是如果是在网站上阅读的话，例如爱斯维尔上的文章，想要看引用的那篇文章，点击超链接后就会在侧栏直接弹出来信息，非常方便。

所以我想请问一下是否有相关的插件能够解决这个问题，或者进行相应的编程实现，是否方便。

期待您的回复
Abon
wuyipeng@zju.edu.cn

**Comment by windingwind** [comment]
你好，阅读界面上方横栏有一个向左箭头按钮，即是返回之前位置。点击链接以后可以通过这个按钮回到之前位置。

**Comment by abon556** [comment]
windingwind




非常感谢你的回信，我在阅读 better note手册的时候，第3节中说大纲的思维导图可以导出，但是我在工作区没有找到相关的按钮，希望能帮忙看下。

3 工作区/Workspace (yuque.com)

“点击大纲栏中的标题，可转跳主笔记中对应的行；拖拽树视图中的标题层级，可快速移动段落。

大纲栏目前是只读的，不可编辑。

可点击下方按钮导出思维导图：矢量图SVG格式或FreeMind导图格式。”




祝好！

***@***.***

**Comment by windingwind** [comment]
目前由于最新版本是测试版，而测试版不会自动更新，因此无法自动更新，需手动下载安装包
