### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by ShaolongTang** [windingwind/zotero-better-notes#208]
## Template Type

图表

## Desired Template Performance

想要在原本自带的图表的基础上为每一行、没一列设置高度和宽度

## Current Template

```js
自带的那个table
```

**Comment by windingwind** [comment]
好像无法实现。只能对所有笔记设置表格宽度最小值。（需要插件层面的更新，而非模板层面）

**Comment by ShaolongTang** [comment]
好的 麻烦啦~

**Comment by windingwind** [comment]
由于无法通过模板完成，将关闭。
