### ISSUE TITLE
Making annotations automatically adds them to the Main Note

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#209]
I have just noticed that in the latest version, all the annotations I do in the Zotero PDF Reader directly go to the Main Note, without doing anything else than simply annotating.
Is there any reason for this? Can you reproduce?

Using Zotero 6.0.19-beta.3+89bc09469 on Windows 10, with Better Notes 0.7.21

**Comment by windingwind** [comment]
Is `Edit-Auto Insert Annotations to Main Note` enabled? This is a feature.

**Comment by mjthoraval** [comment]
Thank you for your reply.
Indeed. I have probably enabled it by accident then.
