### ISSUE TITLE
从pdf中提取笔记支持颜色

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-better-notes#21]
我有多个插件，不知道上不上这个插件的功能，导出的笔记直接有引用链接，挺棒的。但是我想问一下能否支持导出的笔记带荧光笔的颜色？

之前自己折腾zotero的时候，希望倒出来的笔记带高亮颜色，并且进行了一番探索，需要改造几个地方

```c
几个改造的值

extensions.zotfile.pdfExtraction.NoteTruePage;false
extensions.zotfile.pdfExtraction.formatAnnotationHighlight;<p>#%(color)# - <span style="background-color:%(color);">"%(content)"</span> (%(cite))</p>
extensions.zotfile.pdfExtraction.formatAnnotationNote;<p><i>%(content) (<a href="%(uri)">note on p.%(page)</a>BY.%(label)) </p><br>

下划线笔记有问题，一直不能导出来，可能是zotfile对新版zotero兼容性不太好
extensions.zotfile.pdfExtraction.formatAnnotationUnderline;<p>"<u>%(content)</u>" (%(label); p.%(page); %(uri))</p>
extensions.zotfile.pdfExtraction.formatAnnotationUnderline;<p>"<u>%(content)</u>" (%(cite))</p>

```

每行解读：“编辑->首选项->高级->设置编辑器”中的键;键值

导出来的效果：

![](https://s3.bmp.ovh/imgs/2022/05/18/0fbae9ddffb184ec.png)

参考
## 参考资料

[ZotFile: Extracting more features of annotations - Zotero Forums](https://forums.zotero.org/discussion/74966/zotfile-extracting-more-features-of-annotations)

[Using Zotero, Zotfile and Scrivener to carry out research, annotate PDFs and extract the annotations as notes. – AN -|- ANCIENT -|- ACADEMIC](https://an-ancient-academic.com/2019/05/22/using-zotero-zotfile-and-scrivener-to-carry-out-research-annotate-pdfs-and-extract-the-annotations-as-notes/)

[notes [Zotero Documentation]](https://www.zotero.org/support/notes)

**Comment by windingwind** [comment]
这取决于你导出的格式。markdown语法不支持高亮颜色以及下划线。

**Comment by windingwind** [comment]
如果导出富文本格式（word等），是会带有格式的

**Comment by Geo123abc** [comment]
> 如果导出富文本格式（word等），是会带有格式的

我这种方法导出来的是有高亮颜色的，上面的截图也是zotero的，那说明zotero自带的笔记编辑器应该是一个富文本编辑器？

**Comment by windingwind** [comment]
看你的截图你是否在使用zotero5？zotero6重做了笔记部分。
通过插件的导出到剪贴板或者直接复制笔记全文，粘贴到word中是带格式的。

**Comment by Geo123abc** [comment]
截图确实是 zotero 5的（很久之前截的图），现在在使用zotero6，zotero6中也可以实现提取的注释带高亮（见下图），上面那些“键”是zotfile的（参见[ZotFile: Extracting more features of annotations - Zotero Forums](https://forums.zotero.org/discussion/74966/zotfile-extracting-more-features-of-annotations)）
我安装的插件比较多，涉及到PDF注释提取的有这三个：zotero本身的，zotfile的，青柠那个插件的，
测试发现
1. 带高亮的是zotfile提取的（需要改“键”值）
2. 青柠是调取zotfile的功能
3. zotero6自带的

![青柠插件调用zotfile功能](https://i.bmp.ovh/imgs/2022/05/18/28bfbe0a7446606a.png)

![zotfile正在提取注释](https://s3.bmp.ovh/imgs/2022/05/18/ada2df3537952fa5.png)

![在zotero6中使用两种方法提取PDF注释的效果](https://s3.bmp.ovh/imgs/2022/05/18/617bfb6584437ce6.png)

问题：zotero-better-notes 是直接编辑zotero6自己导出的注释吧？不知道zotero是否也存在类似zotfile这样的“键”可以自定义提取出来的样式，如果有的话，就很好玩了。

**Comment by windingwind** [comment]
zotero6 自带对高亮颜色的支持。
![image](https://user-images.githubusercontent.com/33902321/168969926-25cbd65f-43f1-4c77-801e-fa564b8e42e8.png)

**Comment by windingwind** [comment]
根据自定义模板（包含元数据等，并可自定义格式）从注释创建笔记是插件计划的功能，将在未来的更新中支持。

**Comment by Geo123abc** [comment]
> zotero6 自带对高亮颜色的支持。 ![image](https://user-images.githubusercontent.com/33902321/168969926-25cbd65f-43f1-4c77-801e-fa564b8e42e8.png)

谢谢，学到了，果然讨论可以学到很多
