### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by renameart** [windingwind/zotero-better-notes#210]
First of all, thank for your job for my study. And i hope a new  feature that can make comments on PDF

**Comment by windingwind** [comment]
> can make comments on PDF

I don't quite understand. Currently, you can add comments to annotations or write comments as annotations.

**Comment by renameart** [comment]
if you want to annotation a formula, the note will be disorder. what's more, if you want to make a summary about a paragraph， the best way is put it on the beside of the paragraph.  when you review the paper, it will give a immediate recall. Another reason is there are many people hope this function when i review  blogs about zotero-better-notes.
if you can provide AliPay or WecharPay, I will sponsor you within my means。Thank you a lot.
![image](https://user-images.githubusercontent.com/61444248/202837789-9e88ba1b-ed85-4ea6-be49-981e165537cc.png)
![image](https://user-images.githubusercontent.com/61444248/202837818-d2e0e18e-0218-42db-883c-abc7f11b40c6.png)

**Comment by windingwind** [comment]
> if you want to annotation a formula, the note will be disorder

https://zotero.yuque.com/staff-gkhviy/better-notes/bx4h6u
https://zotero.yuque.com/staff-gkhviy/better-notes/pavzsz

> the best way is put it on the beside of the paragraph

![image](https://user-images.githubusercontent.com/33902321/202841432-8612b781-ae96-4992-87e3-533bbfe21caa.png)

**Comment by renameart** [comment]
首先感谢您的积极回复。您说的这个方法我在记笔记的过程中用到过，这种方法的优点是，如果需要大量的文字来做记录，而文档空白处又放不下这么多文字的时候，您说的这个功能十分的好用。但是其中存在的问题是，一旦我用这种方法做了很多笔记，因为笔记被折叠起来，当我复习的时候不能直接看到当初的笔记，需要一个一个点开才能看到当初的内容，不能直接看到当初的笔记内容。如果用我描述的这个方法，可以直接看到笔记内容，非常的方便。

**Comment by windingwind** [comment]
左侧栏可以看所有的批注。
谢谢反馈，这个功能与笔记无关，应向https://forums.zotero.org/discussions 请求该功能。
