### ISSUE TITLE
条目笔记缺少收缩延展功能，笔记内容平铺下来不方便阅读； 主笔记的思维导图功能不太灵活，记多了容易卡，上下移动也会卡。希望能够吸收一下幕布软件的一些优点！

### ISSUE THREAD

**Issue by NandinShi** [windingwind/zotero-better-notes#211]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
> 条目笔记缺少收缩延展功能

无法实现

> 笔记内容平铺下来不方便阅读

推荐主笔记+链接笔记的记录方式。

> 主笔记的思维导图功能不太灵活，记多了容易卡，上下移动也会卡。

请详细描述，不太灵活指的是什么？

> 希望能够吸收一下幕布软件的一些优点

请详细描述
