### ISSUE TITLE
工作区内的home按钮无法切换主笔记

### ISSUE THREAD

**Issue by conquerzzz** [windingwind/zotero-better-notes#213]
zotero6.0.15 插件0.7.24
已经设置过不同主笔记，但在home按钮的弹出菜单中只有打开工作区的选项，没有其他选项
无法切换主笔记
![image](https://user-images.githubusercontent.com/91196737/202839756-92fc98ad-5da0-4a6d-8a72-92099e762bfc.png)

**Comment by windingwind** [comment]
菜单栏 工具-开发者-run JavaScript，粘贴此内容并点击运行，将结果复制出来：
```js
recentIds = (
  Zotero.Prefs.get("Knowledge4Zotero.recentMainNoteIds")
).split(",");
// Remove main note and duplicate notes
recentMainNotes = Zotero.Items.get(
  new Array(
    ...new Set(
      recentIds.filter(
        (id) =>
          Number(id) !==
          parseInt(
            Zotero.Prefs.get(
              "Knowledge4Zotero.mainKnowledgeID"
            )
          )
      )
    )
  )
)
recentMainNotes.map(item=>item.getNoteTitle())
```

**Comment by conquerzzz** [comment]
结果如下：
getNoteTitle() can only be called on notes and attachments


张致熙
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月19日(星期六) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] 工作区内的home按钮无法切换主笔记 (Issue #213)





 
菜单栏 工具-开发者-run JavaScript，粘贴此内容并点击运行，将结果复制出来：
 recentIds = (   Zotero.Prefs.get("Knowledge4Zotero.recentMainNoteIds") ).split(","); // Remove main note and duplicate notes recentMainNotes = Zotero.Items.get(   new Array(     ...new Set(       recentIds.filter(         (id) =&gt;           Number(id) !==           parseInt(             Zotero.Prefs.get(               "Knowledge4Zotero.mainKnowledgeID"             )           )       )     )   ) ) recentMainNotes.map(item=&gt;item.getNoteTitle())

**Comment by conquerzzz** [comment]
![@YH6PRIEG U~Y6UU38@A`HB](https://user-images.githubusercontent.com/91196737/202842017-360322dd-de11-45fb-ada2-65d0a0d4c583.png)

**Comment by windingwind** [comment]
运行：
```js
recentIds = (
  Zotero.Prefs.get("Knowledge4Zotero.recentMainNoteIds")
).split(",");
// Remove main note and duplicate notes
recentMainNotes = Zotero.Items.get(
  new Array(
    ...new Set(
      recentIds.filter(
        (id) =>
          Number(id) !==
          parseInt(
            Zotero.Prefs.get(
              "Knowledge4Zotero.mainKnowledgeID"
            )
          )
      )
    )
  )
)
recentMainNotes
```

**Comment by conquerzzz** [comment]
问题已解决，万分感谢！！！
