### ISSUE TITLE
[Bug]There is no `TEX` bottom in latest version

### ISSUE THREAD

**Issue by sunshineharry** [windingwind/zotero-better-notes#214]
**Describe the bug**
There is no `TEX` bottom in latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/52942042/202839841-4dca7b0e-f269-4b01-aba0-e5002a715bae.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Version Lastest(Sep. 19, 2022)

**Comment by windingwind** [comment]
It's deprecated in plugin >= v0.7.0, as Zotero supports math blocks.
