### ISSUE TITLE
[Feature]条目笔记的不同层级标题可以展开/收缩，并设置相应快捷键，可以参考幕布大纲结构

### ISSUE THREAD

**Issue by xinyuzhangxy** [windingwind/zotero-better-notes#215]
**Is your feature request related to a problem? Please describe.**
有些条目笔记很长，上下翻找到自己想看的内容比较麻烦。

**Describe the solution you'd like**
条目笔记的不同层级标题做成可以展开/收缩的模式，并设置相应快捷键，可以参考幕布的大纲结构。

**Comment by windingwind** [comment]
见 #190

**Comment by xinyuzhangxy** [comment]
> 见 #190

收到，谢谢~
