### ISSUE TITLE
[Bug]Zotero Better Notes开了之后rss感叹号了！

### ISSUE THREAD

**Issue by asong2022** [windingwind/zotero-better-notes#216]
[Bug]Zotero Better Notes开了之后rss感叹号了！

**Comment by windingwind** [comment]
请更新到最新版本插件

**Comment by asong2022** [comment]
> 请更新到最新版本插件

谢谢

**Comment by asong2022** [comment]
> 请更新到最新版本插件

自动同步更新笔记内容到Obsidian【注：由于Zotero内部同步机制的缘故，双向同步可能导致严重的数据丢失或覆盖问题，因此笔记同步是单向从Zotero=>Ob的。在Ob中修改此同步笔记内容之前前，需要先在Zotero内取消该笔记的同步。】

您好！看了您对您工作流的介绍，现在您的Better Notes能自动同步了，您能介绍一下您从Zotero到ob笔记的工作流程现在是如何操作的吗
