### ISSUE TITLE
可以显示3个层级以上的笔记的连接结构图吗？

### ISSUE THREAD

**Issue by Zheng392** [windingwind/zotero-better-notes#217]
目前的只能显示3个层级：referred note→main note→linked note，不知道能否显示3个层级以上的笔记链接图吗？非常感谢~

**Comment by windingwind** [comment]
请详细描述什么是“笔记链接图”？

**Comment by Zheng392** [comment]
比如说A、B、C、D、E是五个不同的笔记，其中箭头代表note link。
![image](https://user-images.githubusercontent.com/17561867/202906325-d7446016-153a-496f-9b6f-e80685336557.png)

**Comment by windingwind** [comment]
笔记链接可根据需要任意添加，没有层级限制的

**Comment by Zheng392** [comment]
我的意思是能不能在工作区的大纲栏里显示以上那样的3个以上层级的笔记关系图？

**Comment by windingwind** [comment]
大纲栏是笔记内所有标题及链接的索引与层级，与笔记之间的关系无关的
