### ISSUE TITLE
笔记截图路径问题

### ISSUE THREAD

**Issue by Lunar-W** [windingwind/zotero-better-notes#22]
感谢作者！使用过程中（主力MAC+Zotero 6+OB）发现 Zotero  的截图存储路径是在本地，但在 OB 里打开笔记需要在绝对路径前面加上 file:/// 或file:/ 才能显示图片，一个一个替换太麻烦了，请问作者大大能否有好的解决办法？
![image](https://user-images.githubusercontent.com/46470041/168990797-368326f7-8265-4bdc-865e-2896c69f2cd8.png)
![image](https://user-images.githubusercontent.com/46470041/168990826-95230b81-ce31-467b-8c5a-319cf237b751.png)

**Comment by windingwind** [comment]
已在新版修复。

**Comment by Lunar-W** [comment]
真棒！！！
