### ISSUE TITLE
[Bug] All annotations are added to Main note, giving sync error

### ISSUE THREAD

**Issue by nathancashion** [windingwind/zotero-better-notes#247]
**Describe the bug**
As I annotate any item in Zotero, those annotations are appended to the end of the main "Knowledge for Zotero User Guide: Workflow" note. Eventually, this note becomes so large that Zotero cannot sync the library.
I have to open the note, find the beginning of the annotations, and delete the rest of the note.

**To Reproduce**
1. Annotate enough items in Zotero over time (~10 items, depending on how much I annotate)
2. Automatic sync fails and gives an error stating the note "# Knowledge for Zotero User Guide: Workflow" has too many lines and cannot by uploaded.
3. Open # Knowledge for Zotero User Guide: Workflow note, delete appended annotations.
4. Sync resumes

**Expected behavior**
I expect annotations to remain isolated to the file I am annotating until I export them. Even then, they should export to a new note under the item, not the Main note for this plug-in.

**Screenshots**
I can add later when this happens again.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser Chrome, Brave, Safari
 - Version [Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (x86_64)](https://brave.com/latest/)

**Tablet (please complete the following information):**
 - Device: iPad Pro 11" 2021
 - OS: iPad OS 16.2
 - Browser Safari

**Additional context**
I have been experimenting with other plugins to integrate with Obsidian, such as Obsidian Zotero Integration (https://github.com/mgmeyers/obsidian-zotero-integration), but I am not sure how this would have contributed.

**Comment by windingwind** [comment]
Please see #209

**Comment by nathancashion** [comment]
Thank you!

**Comment by nathancashion** [comment]
Thank you!
