### ISSUE TITLE
Unable to create/export synced notes [Bug] 

### ISSUE THREAD

**Issue by IpeTek** [windingwind/zotero-better-notes#249]
Reverted back to BN 0.7.14. Now export to md. with sync works as expected. 

The problem with the last couple of the latest versions: When trying to create a note in sync only an ordinary non-synced note gets created. No Zotero-ID (of type IDGER5G) attached to the name of the note, either. 

Zotero 6.0.18

**Comment by windingwind** [comment]
fixed in v0.7.26
Thanks!
