### ISSUE TITLE
希望笔记可以自动命名

### ISSUE THREAD

**Issue by young-liuos** [windingwind/zotero-better-notes#25]
每次把从注释中生成的笔记然后设置主笔记导出的markdown的文件名字都是注释两个字，能不能根据注释所在的条目的元数据自己设置命名规则自动命名啊？

**Comment by windingwind** [comment]
是否你的笔记第一行是图片？
笔记的标题是首行文本，导出的文件名是笔记标题。
![image](https://user-images.githubusercontent.com/33902321/170805624-d50b5a98-33a9-477e-b5ec-a467a6ab68d6.png)

**Comment by windingwind** [comment]
由于这不是一个严格意义的功能请求或bug，将关闭该问题。有需要可再打开
