### ISSUE TITLE
Automatically add Citation Key when adding link to note

### ISSUE THREAD

**Issue by lhtmed** [windingwind/zotero-better-notes#26]
Hi, 
   Zotero-better-notes is a excellent add-on to my liking.
   Here I have a suggetsion might make it more smart:
   Is it possilbe to automatically add citation key along with the link added to note?
   This will make writing much easier.

Best.

**Comment by windingwind** [comment]
Do you mean the citation key from the Better Bibtex addon?

In the future version, users will be able to edit the insert template and thus you can add anything you want.

**Comment by lhtmed** [comment]
Yes.

Waiting!

**Comment by windingwind** [comment]
The insert/import template is supported in v0.3.6
