### ISSUE TITLE
关于此插件各界面夜间模式的支持

### ISSUE THREAD

**Issue by IOSure** [windingwind/zotero-better-notes#260]
**Is your feature request related to a problem? Please describe.**
通过[ZoteroTheme](https://github.com/iShareStuff/ZoteroTheme)，[zotero-night](https://github.com/tefkah/zotero-night)等插件，可以设置zotero pdf阅读器的显示模式为夜间模式，或者护眼模式。
而better-notes插件显示为zotero的白色模式。
我自己本身是喜欢在夜间模式中阅读pdf
在阅读pdf和批注。再到使用better-notes的整理笔记之间，来回切换，从暗黑到白色，来回切换，不是太好
谢谢

**Describe the solution you'd like**
对better-notes插件增加模式切换按钮，或者可以跟随zotero的显示模式

**Describe alternatives you've considered**

**Additional context**
暗黑模式：
<img width="943" alt="image" src="https://user-images.githubusercontent.com/38939899/204662432-49400650-b084-4bd3-a3cf-e8495799a787.png">

**Comment by windingwind** [comment]
见#204，此处关闭
