### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by shi131** [windingwind/zotero-better-notes#261]
**请问，图片注释可以支持在betternotes中直接显示吗，目前显示的是图片注释的链接，点击才能预览.**
**请问，导入betternotes的图片注释，默认显示的标题等级，想把图片注释的链接调成正文等级（即在大纲中不显示），该怎么操作呢.**

**Comment by windingwind** [comment]
1. 可以。直接复制粘贴注释/拖进去/通过模板添加都可以
2. 
![image](https://user-images.githubusercontent.com/33902321/205217900-415a4d88-771e-4e28-960c-5dd8864fea10.png)

**Comment by shi131** [comment]
1. 复制粘贴/拖进betternotes的图片在刷新笔记的时候会清空掉。
2. 通过第二条的方式会是图片注释的链接失效。
3. 我的想法是，zotero看文献时框选注释出来的图片能不能通过点击花形按钮添加到betternotes之后就在betternotes显示图片，而不是显示链接。

**Comment by windingwind** [comment]
1. 刷新笔记是用于特殊情况下表格等元素无法编辑的，图片导入需要时间，在导入完成之前刷新就会导致消失，没必要不需要刷新，会自动保存
2. 第二条的截图是回答你说的调成正文等级，不是插入图片
3. https://github.com/windingwind/zotero-better-notes/discussions/245

**Comment by windingwind** [comment]
链接是默认在大纲中显示的，取消链接直接插入图片注释就不会显示了
