### ISSUE TITLE
[Note Template]请问一下笔记模板中怎么获取到对应条目的会议名称啊？

### ISSUE THREAD

**Issue by Lonicer** [windingwind/zotero-better-notes#262]
## Template Type

![image](https://user-images.githubusercontent.com/70836946/205212244-56fa5c66-4540-433a-815d-33c0089ee065.png)
就是这里

然后
 <td style="background-color:#f3faf4;">
            ${topItem.getField('publicationTitle')}
        </td>
这个只能得到期刊名称。
希望您能解答一下，万分感谢！
Item, Note, Quick Import, Quick Insert, ...

## Desired Template Performance

Describe what you want.

## Current Template

```js
// Paste your template here
```

**Comment by windingwind** [comment]
见 https://github.com/windingwind/zotero-better-notes/blob/master/TemplateDoc.md#about-item-fields
![image](https://user-images.githubusercontent.com/33902321/205217779-2545cf0d-da08-4869-8acd-8b64b2924c3d.png)

**Comment by Lonicer** [comment]
好的，非常感谢·！！！！






勾陈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] [Note Template]请问一下笔记模板中怎么获取到对应条目的会议名称啊？ (Issue #262)





 
见 https://github.com/windingwind/zotero-better-notes/blob/master/TemplateDoc.md#about-item-fields
