### ISSUE TITLE
is it possible to add more deeper headings ? 

### ISSUE THREAD

**Issue by mnkhprre** [windingwind/zotero-better-notes#263]
I am studying a dissertation and it is a fairly vast and deep topic and i need  more deeper headings 
<img width="154" alt="Screenshot 2022-12-02 at 17 08 44" src="https://user-images.githubusercontent.com/54448793/205312795-ae4546fc-79e8-4f28-8d16-a7ef1f79ecb0.png">

deeper heading and customizable heading.  i need it, plz add it.

**Comment by windingwind** [comment]
H1-6 are supported. Use the markdown-like 1-6*`#`+`space`, or select text and ctrl+shift+`1-6`

**Comment by mnkhprre** [comment]
> H1-6 are supported. Use the markdown-like 1-6*`#`+`space`, or select text and ctrl+shift+`1-6`

oh, thx for that.  I have a question about what is your future plan to this piece of masterpiece?

**Comment by windingwind** [comment]
Hi, the short-term plans are:
- Fix bugs in the two-path syncing;
- Editable mind map;
- Make adjustments for Zotero 7

This plugin is not fully mature now. In the long run, it will become a stable version and be maintained like other mature plugins, like PDF Translate and Tag.

If you are asking me if it will become a new note-taking software, my answer is no. We have plenty of note editors, like Obsidian. I don't want to replace any of them.

**Comment by mnkhprre** [comment]
> 

lol I am not even denoting it. it is a beautiful extension. i think if we can a that tags on mind map will be more usable.

**Comment by windingwind** [comment]
Any suggestion is welcomed. We could discuss this further in a new issue.
