### ISSUE TITLE
[Feature]请问笔记中的图床链接怎么解析不出来呀？

### ISSUE THREAD

**Issue by Lonicer** [windingwind/zotero-better-notes#264]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/70836946/205417260-2840f8ed-2718-4d41-bbcc-37f0d4461ea0.png)
就像这样不能解析，只能粘贴，但是这张图片我已经上传到图床，在导出的话又是一张新assets图片了
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
请循其本。图床的目的是提供跨平台的图片存储，zotero笔记本身就支持无限存储量的图片，支持跨平台同步，因此不需要使用图床。

**Comment by Lonicer** [comment]
好的，谢谢您






勾陈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月3日(星期六) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] [Feature]请问笔记中的图床链接怎么解析不出来呀？ (Issue #264)





 
请循其本。图床的目的是提供跨平台的图片存储，zotero笔记本身就支持无限存储量的图片，支持跨平台同步，因此不需要使用图床。

**Comment by wadeok** [comment]
但是zotero无法跨设备同步笔记里的图片，所以我才想到用图床生成链接写入笔记里，结果不能显示图片？

**Comment by windingwind** [comment]
可以跨设备同步。同步问题与插件无关，向官方论坛反馈

**Comment by Windrain7** [comment]
> 请循其本。图床的目的是提供跨平台的图片存储，zotero笔记本身就支持无限存储量的图片，支持跨平台同步，因此不需要使用图床。

zotero笔记中的图片属于附件，会占用文件同步的空间，而文件同步空间是有限制的，只有300M，所以zotero并不支持无限存储量的图片，希望能够增加解析图床链接的功能。

**Comment by windingwind** [comment]
你可以使用webdav，也可以选择购买zotero存储空间。

**Comment by Windrain7** [comment]
pdf附件的文件同步已利用其他办法解决，现在就是图片文件同步无法解决，必须使用zotero的存储空间。相比于图床，zotero的存储空间还是比图床要贵。

**Comment by windingwind** [comment]
从技术角度，你的问题可以相似地理解为“MS Word的图片可以支持图床吗”。答案显然是否。
从使用角度，理由如上所述，此处不再回复。
