### ISSUE TITLE
[Bug] Bad link format name in Obsidian when exporting from zotero's default pdf viewer

### ISSUE THREAD

**Issue by KalyaSc** [windingwind/zotero-better-notes#269]
Hello, thank you for you plugin and hardwork !

**Describe the bug**
When I export my notes as MD file from zotero to my Obsidian folder, the link is not formated correctly. The link works perfectly but the name is just (pdf). 

**To Reproduce**
1. Create my notes in the default zotero pdf viewer
2. Click on "export with linked notes"
3. Save into my obsidian vault
4. The note is exported but the link name is PDF 

**Expected behavior**
I expected the link to have a similar format name as the zotero citation link

**Screenshots**

<img width="1085" alt="zotero-better-notes-Citation-link" src="https://user-images.githubusercontent.com/95717211/206099186-829565d5-9a00-49ca-abab-d55eaf416ad8.png">

**Desktop:**
 - OS: MacOS 12.5.1
 - Browser Firefox

**Complementary:**
The Zotero citation link brings me only to the pdf in the zotero folder, so thats not the solution. Also if it's to complicated to change, I can live with it, but i'm probably to much of a perfectionist.

Thank you !

**Comment by windingwind** [comment]
This is the behavior of Zotero’s default export an I follow that. One link opens pdf and another reveals the item in Zotero library.

In the pre release 0.8.x, the export is totally different and will replace the one we have currently. Maybe you could try that.

**Comment by windingwind** [comment]
The exported md should look like this in v0.8.0:
![image](https://user-images.githubusercontent.com/33902321/206165923-8620108d-568f-4e3e-8d40-45f7212c657a.png)

Make sure you use the export provided by this plugin, not the Zotero export.

https://github.com/windingwind/zotero-better-notes/wiki/2-Zotero-Notes-Zotero-Notes.en#export-notes

**Comment by KalyaSc** [comment]
Hi :)

I think that's what I'm doing. But I doesn't work. 

![ZoteroBetterNotesExportation](https://user-images.githubusercontent.com/95717211/206392622-ef4afceb-78c5-4a82-b9c6-a89e3880dafe.jpg)

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/206400116-7e9b565a-d7e6-446d-a982-c6abfde83575.png)
The left fig is Zotero's built-in export result; the right fig is the result of this plugin. Plugin v0.8.3

Please check if there are two MD files under your export directory. The default filename of the plugin's export is named `note name-note key.md`, while I don't find the note key in your export.

![image](https://user-images.githubusercontent.com/33902321/206400827-3bccc1b2-0f02-4c9a-959b-f6f229cc85a2.png)

**Comment by windingwind** [comment]
Any updates? Does this happen on the latest version of the plugin?
