### ISSUE TITLE
功能：在zotero中拷贝标注的文字或者区域，在logseq中粘贴，可以以一定格式显示内容（包含区域，一般为图片），并且可以通过外链在zotero中定位？

### ISSUE THREAD

**Issue by qiyueliuhuo** [windingwind/zotero-better-notes#27]
如题
目前copy文字是可以的，就是格式不能调整（不过也还可以）

区域没法弄

暂时的方法：
自己截图，把区域标注截图下来，再在logseq中粘贴图片。

总结，就是需要在markdown的编辑器中完美做笔记。

**Comment by windingwind** [comment]
将文本/图片注释添加到主笔记，在笔记完成后导出主笔记，即可在其他软件中正常使用。
由于嵌入的markdown图片链接是zotero内部存储的，在其他设备上可能看不到，建议在导出到其他软件时将图片链接拷贝到其他目录下，大多数笔记软件如Obsidian都有这个功能

**Comment by appw-cn** [comment]
目前是可以的。但是可能由于markdown语法问题，我习惯在注释中直接用md语法写笔记，然而“###”会变成“/###”，“>”会变成“/>”。不知道是否可以关闭这个自动加“/”的功能呢？大佬知道开关在哪里，通过设置编辑器可以吗？谢谢~

**Comment by windingwind** [comment]
感谢支持。很遗憾，鉴于目前插件开发计划于方向，暂不会实现复制功能。一是因为插件已经实现了收集文献信息的笔记功能，使用插件进行笔记则无需在软件之间复制粘贴；二是非核心功能的引入会增加开发和维护成本，望理解。
将关闭该issue。

**Comment by windingwind** [comment]
@qiyueliuhuo 0.5.14支持快速拷贝图片笔记。
