### ISSUE TITLE
[Feature] alternative image exportation. 

### ISSUE THREAD

**Issue by mnkhprre** [windingwind/zotero-better-notes#273]
is it possible to export schemes and maps from better notes as jpg or png? 
or is it possible to export schemes and maps from better notes as .smmx(SimpleMind map file extension) ? 
<img width="103" alt="Screenshot 2022-12-11 at 17 20 19" src="https://user-images.githubusercontent.com/54448793/206909113-5a9c9170-414d-45e0-807d-8f833813412b.png">

**Comment by windingwind** [comment]
SVG is vector graphics, while PNG or JPG store items in pixels, which means they cannot be zoomed infinitely. The image would be either very big, or the details will be lost.

It is possible to export them as PNG or JPG though.

SimpleMind can import FreeMind (.mm) and .opml files. I don't think we need to add extra support for .smmx.
