### ISSUE TITLE
将普通笔记插入主笔记时被挡住了怎么办？

### ISSUE THREAD

**Issue by coisini-95** [windingwind/zotero-better-notes#274]
![图片](https://user-images.githubusercontent.com/78250635/206913546-3a8daca7-23a0-4299-b854-63b3957b9075.png)
如图所示，将普通笔记插入主笔记目录时，最下一级目录被浮动的提示页挡住了（磁各向异性下面还有一级目录），请问这怎么办，或者能把这个浮动提示页删除吗？

**Comment by coisini-95** [comment]
> 😂加一个“按一下esc关闭提示”如何

听起来不错，感谢大佬

**Comment by coisini-95** [comment]
> 😂加一个“按一下esc关闭提示”如何

大佬我发现笔记在单独窗口的时候（直接双击打开笔记的情况）按esc键可以关闭浮动提示条，但是当笔记在侧边的时候（边看文献边记笔记的情况）按esc键提示条不会消失，请问这是bug吗

**Comment by windingwind** [comment]
换成ctrl了，esc不识别
