### ISSUE TITLE
[Bug] 开启插件后 RSS 订阅无法更新

### ISSUE THREAD

**Issue by ridfer** [windingwind/zotero-better-notes#275]
**Describe the bug**

**To Reproduce**
1. 开启 Zotero Better notes 插件
2. 右键更新已有的rss订阅
3. 出现rss更新错误标识

**Expected behavior**
rss 正常更新（关闭插件后）
![image](https://user-images.githubusercontent.com/30251010/206954606-ee066764-fb2b-4251-8655-f2ebc60f45d4.png)

**Screenshots**
开启插件后更新错误
![image](https://user-images.githubusercontent.com/30251010/206954477-5867c3b9-a6e6-4026-b78b-ffd0eb82957b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser edge
 - Version 0.7.28

**Additional context**

**Comment by windingwind** [comment]
请关闭其他所有插件然后重试。如果仍然出现问题，请提供错误调试（帮助-调试输出-查看调试输出）

**Comment by windingwind** [comment]
仅开启zotero-if是否会导致rss问题？

**Comment by windingwind** [comment]
需要联系if作者看下具体是什么问题。

**Comment by windingwind** [comment]
由于该问题无法由我解决，将关闭
