### ISSUE TITLE
为什么我把一个文献条目删除后，在回收站里了。但是这个条目下面笔记与主笔记之间链接仍然有效？而且我还不能直接在回收站对这个笔记的链接进行删除。由于需要处理大量文献，如果不能在我删除条目的同时让链接失效，后续会反复增加工作量。感谢！

### ISSUE THREAD

**Issue by Juanjuanqwe** [windingwind/zotero-better-notes#278]
****Is** your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
“不能直接在回收站对这个笔记的链接进行删除”是什么意思？另外不要重复提问。

**Comment by windingwind** [comment]
由于长时间无回复，将关闭
