### ISSUE TITLE
[Bug] Issues about jumping of annotation in notes

### ISSUE THREAD

**Issue by seifer08ms** [windingwind/zotero-better-notes#28]
After upgrading to releases v0.4.3 and v0.4.4, I found some issues with the jump function of annotations.
1. The annotation in the note can only jump to selecting the item, not to the page where it is located. The show page button is disappeared.
<img width="255" alt="1653991359(1)" src="https://user-images.githubusercontent.com/506463/171148677-75850191-5bd6-4d99-a874-b9d4a5bfe171.png">
2. The markdown file, exported from a note of annotations, contains the page links jumping to a specific location of annotations. However, the image is embedded incorrectly, and the page links of images are missing.

![image](https://user-images.githubusercontent.com/506463/171148873-0d6dc799-3bcd-46f8-969f-8f397e732b5f.png)
3. There is no page link in the main note( pdf link in the above screenshot ), and therefore the function of jumping to a page is not available. However, the markdown generated with the default export function has a page link, but it is impossible to embed the image. 
![image](https://user-images.githubusercontent.com/506463/171149013-afac56a2-6d62-4098-999f-9c39b9a1f70d.png)

**Comment by windingwind** [comment]
1. This is a Zotero behavior. The **Annotation Text** has `show on page`, while the `Annotation Citation` doesn't.
![image](https://user-images.githubusercontent.com/33902321/171313278-860b36e2-75af-423e-a7aa-f8ce01b77e04.png)
![image](https://user-images.githubusercontent.com/33902321/171313303-57b1d4a4-b09e-4e20-83c4-4472337f5bc0.png)

2 & 3  
What do you mean by referring `the image is embedded incorrectly, and the page links of images are missing`? Images are embedded in markdown format. In markdown, an image cannot be linked to a URL.

**Comment by seifer08ms** [comment]
还是用中文吧


1.  我之前点击那个位置能同时弹出show on page 和show item，很奇怪为何现在点击文字和图片才能show on page，不过这个不重要。可能是我误解了。
-----
>总结：
>用插件的导出功能，图片能生成markdown的图片内嵌显示，但缺少跳转链接。
>右键export note功能， 图片能带跳转链接，但无法生成markdown的内嵌显示语法。
------------------------------------------
3 .  我指的是zotero的图片标注的跳转，zotero里点击图片可跳转，导出后应该也有个对应的跳转链接：

导出的markdown的图片位置不对，变成在开头的位置，而且没有跳转链接：

![图片](https://user-images.githubusercontent.com/506463/171320933-b4cd744a-315c-4dd6-b84a-0eaa93a9b06b.png)

但是如果用右键的export note，位置和跳转链接是正常的，只是图片不能内嵌在markdown里：

![图片](https://user-images.githubusercontent.com/506463/171322865-f03e81ad-16da-4518-beb2-70b42c71a4ec.png)

这个图片标注在zotero里的pdf里是这样的：
![图片](https://user-images.githubusercontent.com/506463/171320630-c70dedbe-7cd8-4036-bd29-b74e2b410845.png)
annotation 标注里点击能跳转到上面pdf的位置：
![图片](https://user-images.githubusercontent.com/506463/171320698-46a19633-2368-4399-8475-6e7faff45f34.png)
note里对应的内容，点击图片支持show on page：
![图片](https://user-images.githubusercontent.com/506463/171322548-8a80723e-8f95-4876-bc43-d4c41889fb0c.png)

**Comment by windingwind** [comment]
@seifer08ms 已修复

**Comment by seifer08ms** [comment]
插件导出到了整个markdown文件的开头处了，就是第一行，实际应该是好几段之后的位置。

假设图片原来是第三段的后面，note和annotation都指向的第三段后面的位置。但是插件导出的图片内嵌到了文件最开始部分，第一行。右键export note导出的 图片位置是对的，也是在第三段后面的位置。

**Comment by windingwind** [comment]
@seifer08ms 请截图看下笔记内容？

**Comment by seifer08ms** [comment]
而zotero里的笔记，开头部分是这样的：
![图片](https://user-images.githubusercontent.com/506463/171326888-d8e0cba8-cbb5-43bb-bf23-b54922da1d94.png)
@windingwind

**Comment by seifer08ms** [comment]
> 很奇怪，我尚没有遇到过这种问题。有进展再沟通

@windingwind ,谢谢 。 另外，好像最新的release v0.4.5 没有xpi文件可下载？

**Comment by windingwind** [comment]
已更新，应已解决全部问题
