### ISSUE TITLE
在条目笔记中已经删除或者解除与主笔记的链接，但是这个链接在主笔记中仍然存在且有效！

### ISSUE THREAD

**Issue by Juanjuanqwe** [windingwind/zotero-better-notes#280]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
请在zotero中清空回收站。
