### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by RTcui** [windingwind/zotero-better-notes#283]
模板问题如下：
有些HTML代码在模板中不支持的求助；
1.比如样式设置；
2.添加的表格不能正常输入文字【比如下面代码中表格中要点三后面的输入框和问题后面的输入框，都是设置的可输入文本的 HTML代码，但是在笔记中并不能输入】；
    但是所有的代码在ZotCard配置里面都是可以完全正常显示的。
**有没有高手能指点一二？？**

// Paste your template here  代码如下

文献信息表

<h3>表格：</h3>
<table border="1">
<tr>
  <th align="center">标题</th>
  <td colspan="5">${title}</td>
</tr>
<tr>
  <th>中文</th>
  <td colspan="5">写入标题翻译</td>
</tr>
<tr>
  <th>年份</th>
  <td>${date}</td>
  <th>IF</th>
  <td>${libraryCatalog}区${callNumber}分</td>
  <th>期刊</th>
  <td>${journalAbbreviation}</td>
</tr>
<tr>
  <th>一作</th>
  <td colspan="5">${authors}</td>
</tr>
<tr>
  <th>作者单位</th>
  <td colspan="5">作者单位代码</td>
</tr>
<tr>
  <th>摘要</th>
  <td colspan="5">摘要内容</td>
</tr>
<tr>
  <th>要点一</th>
  <td>具体酶内容</td>
  <th rowspan="3">问题</th>
  <td rowspan="3" colspan="3"><textarea name="message" rows="10" cols="30">The cat was playing in the garden.问题内容</textarea></td>
</tr>
<tr>
<th>要点二</th>
  <td>底物具体内容</td>
</tr>
<tr>
<th>要点三</th>
  <td contenteditable="true">可输入的内容：细胞过程/机制</td>
</tr>
</table>

**Comment by windingwind** [comment]
具体变量用法请先看模板文档

**Comment by RTcui** [comment]
您好，我已收到您的邮件，当我看到后会立即给您回复！

**Comment by windingwind** [comment]
表格无法聚焦光标是Zotero笔记偶尔出现的bug，可通过右键移动光标，或者右上角刷新笔记。

**Comment by RTcui** [comment]
> 表格无法聚焦光标是Zotero笔记偶尔出现的bug，可通过右键移动光标，或者右上角刷新笔记。

谢谢~
