### ISSUE TITLE
[Feature]是否可以实现在笔记中选中一段话，通过右键把此段话生成一个新笔记。感谢

### ISSUE THREAD

**Issue by RTcui** [windingwind/zotero-better-notes#284]
是否可以实现在笔记中选中一段话，通过右键把此段话生成一个新笔记。感谢！

**Comment by windingwind** [comment]
这个功能的应用场景是什么？

**Comment by RTcui** [comment]
> 这个功能的应用场景是什么？
首先感谢开发大神回复！
我的个人习惯是：有一个整体的阅读文献的笔记模板，每次阅读后会生成一个整体的笔记。在这个整体笔记中会有一段话是自己的总结，可以单独把这句话拿出来单独成为一个笔记。这样用来写综述的时候就可以单独把这句话插入到主笔记中。目前我是复制这句话粘贴到一个新的笔记中，如果可以选中-右键生成，就会更方便。
不知道别的小伙伴是否会有类似的需求。

**Comment by RTcui** [comment]
> 这个功能的应用场景是什么？
首先感谢开发大神回复！
我的个人习惯是：有一个整体的阅读文献的笔记模板，每次阅读后会生成一个整体的笔记。在这个整体笔记中会有一段话是自己的总结，可以单独把这句话拿出来单独成为一个笔记。这样用来写综述的时候就可以单独把这句话插入到主笔记中。目前我是复制这句话粘贴到一个新的笔记中，如果可以选中-右键生成，就会更方便。
不知道别的小伙伴是否会有类似的需求。

**Comment by windingwind** [comment]
感觉不是特别普遍的需求，如果没有其他人需要的话将不考虑。谢谢理解！
