### ISSUE TITLE
能否降低提示同步note的频率或者静默提示？感谢！

### ISSUE THREAD

**Issue by ChunwuZhu** [windingwind/zotero-better-notes#289]
note的默认同步时间是30s，长时间写note的时候会频繁在右下角弹窗提示同步note，偶尔会影响写作。能否增加一个功能设置同步note的时候不显示弹窗或者降低弹窗显示的评论？感谢！

**Comment by windingwind** [comment]
请升级到正式发布版本

**Comment by she529** [comment]
笔记发生修改会自动同步，而不是根据设定的同步时间来同步，所以在写note的时候会一直弹窗提示同步  大佬这个可以改吗

**Comment by windingwind** [comment]
更新版本

**Comment by she529** [comment]
> 更新版本


https://user-images.githubusercontent.com/75371769/230390772-36023628-647d-4c59-9949-631d88e78345.mp4

**Comment by she529** [comment]
> > 更新版本

按照设置的时间 不应该这么频繁同步 但是只要更改就会自动同步 并提示

**Comment by windingwind** [comment]
了解，下个版本加入设置
