### ISSUE TITLE
[Bug] Exported Images producing incorrect file structure and filenames. 

### ISSUE THREAD

**Issue by andrewcrook** [windingwind/zotero-better-notes#29]
macOS 12.4
Zotero 6
zotero-better-notes Release 0.4.7

1. Open PDF for annotation in Zotero 6
2. Add annotations to notes
3. Export notes as Markdown 

Result

Attachment folder creates new folder in root with the parent path in the file name. This is empty.
Image files are being created with the path in the filename rather than saving to the path ends up in the root.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/803618/171450718-5fb4ed91-68af-4fef-894c-aa73874d3620.png">

Should be 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/803618/171451210-fa381742-41ee-4f28-a867-2e58f2c5d1f6.png">

**Comment by windingwind** [comment]
Thanks for letting me know!
Seem like it’s caused by the different path splitter in Win & Mac, as the test is done on Windows.
Will fix it soon!

**Comment by windingwind** [comment]
@andrewcrook Please try v0.4.8 and see if it does it right?
I don't have a mac.🤔

**Comment by andrewcrook** [comment]
@windingwind 

it does work filename and folder creation wise , however, the image links in the exported markdown has path separator issue

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/803618/171477610-ac7324ee-ac6c-421c-8e1e-f0c96d7ccf95.png">

`000-Inbox/attachments/EUS29KTD.png`

I am not familiar with Zotero internals 
I know Electron which uses Node has a path module which has functions to format paths automarically for different OSs
Is there something similar for Zotero?  does Zotero’s APIs offer something? 
I presume it uses spidermonkey to run JavaScript for plugins?

**Comment by andrewcrook** [comment]
`FILE:///` - https://en.wikipedia.org/wiki/File_URI_scheme

It actually looks like windows and unix is the same for this schema

**Comment by windingwind** [comment]
are there still a file separater bug?
zotero is actually a browser, not a node env. in windows, they are \ and in mac they should be /.

**Comment by windingwind** [comment]
Please try the latest v0.4.9
Pass test on MacOS

**Comment by andrewcrook** [comment]
@windingwind Sorry I removed some notes because something strange happen and v0.4.8 wasn’t downloaded properly. Then when I reinstalled v0.4.8 wouldn’t work at all.

**_v0.4.9**. is working correctly in terms of file structure and the image links in markdown now works._

My old note regarding `FILE://` was because v0.4.8 used it in the markdown or image location and the separators were wrong in the markdown I see that you have changed it to a relative path and no longer using the FILE schema anyway. But  FYI standard FILE schema URIs are the same between windows and unix `FILE:///folder1/folder2/test.md` although windows will accept ‘\’ as non-standard and `:///`means local ‘//‘ is really for when you included a hostname. Windows UNCs area bit more confusing and has non-standard methods one benign `:////` 🙄

any way thanks for fixing

**Comment by andrewcrook** [comment]
Test passed on MacOS

**Comment by windingwind** [comment]
Thanks for your suggestion!
Using the relative path is a more safe way to manage attachments in Markdown. The images in Zotero storage may be lost if you delete the note or annotation.
In the future versions maybe I'll add an absolute path mode. These suggestions about file paths would be helpful!
