### ISSUE TITLE
[Bug] Unable to uninstall better-notes

### ISSUE THREAD

**Issue by ezlxq** [windingwind/zotero-better-notes#295]
**Describe the bug**
Add-ons control window doesn't appear when selected

**To Reproduce**
1. Go to 'Tools'
2. . Click on 'Addons'

**Expected behavior**
Add-ons manager window to appear to disable or uninstall better-notes

**Desktop (please complete the following information):**
 - OS: [W10]
 - Browser [Chrome]
 - Version [Version 108.0.5359.125]

**Comment by ezlxq** [comment]
Yeah, tried that but it didn't solve the problem. :(
Can't find any advice in the general zotero forums

**Comment by windingwind** [comment]
I mean totally exit Zotero, not just close the window.

If you are using mac, please restart your computer.

**Comment by ezlxq** [comment]
Sorted, thanks. I'll come back to better notes soon!
