### ISSUE TITLE
[Bug] The function of extension is invalid in v0.4.8

### ISSUE THREAD

**Issue by seifer08ms** [windingwind/zotero-better-notes#30]
我更新了0.4.8,发现插件增加的 打开工作空间，和插件自己的导出按钮都不见了。安装回0.4.7，这两个又出现了。另外我测试了下0.4.7导出图片的功能，发现位置被修复正确，但图片没有嵌入，生成的这个图片路径是找不到图片的，

![图片](https://user-images.githubusercontent.com/506463/171517647-a0223915-4dd5-4a0b-8dc1-5797972fc71e.png)

不知道是不是这个问题 在0.4.8中修复了，但0.4.8又出现别的bug导致功能按钮不见了

**Comment by windingwind** [comment]
图片现在会被复制到导出目录下的attachments文件夹。048的问题将会排查

**Comment by windingwind** [comment]
048似乎是发布的时候未打包完全，已经替换下载资源

**Comment by seifer08ms** [comment]
Problem solved perfectly. Thanks.
