### ISSUE TITLE
主笔记功能的一些小建议[Feature]

### ISSUE THREAD

**Issue by BoBo-YunYun** [windingwind/zotero-better-notes#305]
有两个小建议，希望作者大大考虑下：

1. zotero的笔记面板上方是否可以增加一个按钮，功能为：将当前笔记设置为主笔记并刷新；

2. 在每个条目都只有一个主笔记的前提下，是否可以在zotero外部的面板中增加一个独立的选项，类似您开发的zotero pdf preview一样，功能为：选中每个条目后可直接在外部预览主笔记。 

感觉上述两个功能很实用，希望作者大大考虑

**Comment by windingwind** [comment]
感谢建议，
1. 计划
2. 预览比较复杂，个人时间有限暂时不考虑
