### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by sydlfl** [windingwind/zotero-better-notes#306]
## Template Type

Template about Auto-insert New Annotations to Note

## Desired Template Performance

I am wondering if I can edit the template mentioned above, but I can't find or edit the default template for the auto-insert function.

## Current Template

```js
// It would help a lot if the position of the template mentioned above can be shared. Thank you! 
```

**Comment by windingwind** [comment]
Edit-Note Template Editor.

Don’t forget to save your modifications.

**Comment by windingwind** [comment]
If it’s not shown there, then it’s not editable.

**Comment by sydlfl** [comment]
Thank you for your advice! I guess it's not editable since I have tried to modify every template shown there but no one was relevant to the auto-insert function.
