### ISSUE TITLE
Addon does not show up after installing and activating

### ISSUE THREAD

**Issue by ychenfo** [windingwind/zotero-better-notes#31]
I downloaded the `.xpi` file and tried to install this addon following the [steps in the readme file](https://github.com/windingwind/zotero-better-notes#install), but after restarting Zotero nothing new about this plugin shows up. The only thing that I can notice is this `set main note` item in the drop-down menu: ![image](https://user-images.githubusercontent.com/43136427/171536815-3a2b7b76-6fd9-40ec-830f-c247dac4b94a.png), which does not give me any response after being clicked.

The following is a screenshot of Zetoro after installing the plugin, and making sure that in the addon manager, the status of this plugin is enabled.
![image](https://user-images.githubusercontent.com/43136427/171538352-c88aa9eb-3d5f-4fa4-9eb5-1edabf70c1fc.png)

I am new to Zotero so I am not sure if I missed anything. Thanks!

**Comment by CrescentonC** [comment]
issue solved by downloading the new verison of the release: https://github.com/windingwind/zotero-better-notes/issues/30#issuecomment-1144313723
