### ISSUE TITLE
[Bug]主笔记页面中，子笔记展开后无法收回，且思维导图内容混乱

### ISSUE THREAD

**Issue by johnbriton** [windingwind/zotero-better-notes#310]
**Describe the bug**
1. 在主笔记内链接的笔记，通过这个按键展开后无法收回，只能整体删除后重新展开
![image](https://user-images.githubusercontent.com/28997207/210575783-250046d5-9884-4a52-9fa4-db630c490ccc.png)
2. 展开子笔记后，左侧的思维导图会错误地读取全部展开的子笔记内容，变得非常臃肿
![image](https://user-images.githubusercontent.com/28997207/210576393-4091f8a5-cdcb-4531-9800-9d5c7ee84eb2.png)

**To Reproduce**
1. 链接子笔记至主笔记
2. Click on 主笔记中子笔记的链接
3. 点击这个按钮
![image](https://user-images.githubusercontent.com/28997207/210576924-3349314a-7199-4f1d-9f75-a2fd1e974f0c.png)

**Expected behavior**
1. 子笔记可以随时展开全文、收回至标题
2. 这个操作不应影响主笔记的思维导图，或至少可以用清晰的方式区分主笔记和子笔记的导图结构
3. 给点击链接后跳出的五个图标添加名称

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Zotero 6.0.19
 - Version 0.8.7 Build 2022-12-28

**Comment by windingwind** [comment]
这个按钮不是展开或预览，是嵌入子笔记内容。详见文档

**Comment by windingwind** [comment]
预览子笔记通过光标位于笔记链接时的悬浮窗，预览或编辑子笔记全文在右侧预览栏

**Comment by johnbriton** [comment]
> 这个按钮不是展开或预览，是嵌入子笔记内容。详见文档

感谢回复，谢谢开发者的工作！感觉插件很有用，原谅我没仔细看文档就尝试上手。刚刚读了下文档，发现这些功能确实已经在文档中有了描述，但我个人觉得也许有些功能还是可以考虑，以提升使用时的流畅度：
- 首先是子笔记嵌入之后，思维导图的内容紊乱问题：
![image](https://user-images.githubusercontent.com/28997207/210599471-c924849b-7e57-470d-b42c-9ec088662e14.png)
- 其次，希望可以增加一下图标的名称，或者在悬浮光标时能暂时预览图标的名称，这样对功能的理解可能会直观些，如zotero的笔记内引用弹窗：
![image](https://user-images.githubusercontent.com/28997207/210598082-27e9bbe0-8055-4ed8-8310-d427235d9730.png)
- 此外，嵌入子笔记内容后无法ctrl+z撤销，如果误操作就需要手动全部删除，希望可以改进。

再次感谢！

**Comment by windingwind** [comment]
1. 标题层级问题将后续修复
2. 悬浮提示是有的，由于未知原因在工作区不显示。这个目前无法修复。
3. 撤销的情况较复杂，带有图片的笔记操作目前无法撤销。

**Comment by UncleWang05** [comment]
我接着这个展开问题：

就是子笔记嵌入之后，无法通过bar上的刷新按钮更新同步，例如在子笔记上做修改，无法同步到主笔记上的嵌入部分。

**Comment by windingwind** [comment]
是的，因此不推荐手动嵌入，而是建议使用笔记链接预览。在当前笔记框架下刷新很难实现

**Comment by windingwind** [comment]
Closed for #429
