### ISSUE TITLE
[Bug]Refreshing note editor causes Zotero Built-in latex to crash

### ISSUE THREAD

**Issue by johnbriton** [windingwind/zotero-better-notes#312]
## Describe the bug
In Zotero notes, we can use $ in front and back of Te_ST to create latex block like $Te_ST$. 
![image](https://user-images.githubusercontent.com/28997207/210675471-a87fb44f-70ba-4f10-ab81-637f44654fc0.png)

However, After **refreshing** the note editor, this will change into plain text without any latex rendering.
This happens in various ways.
### Bug 1: Latex crash
- It is possible that after refreshing, $Te_ST$ will turn into TeSTTe_STTeS​T. The $ just disappears.
![image](https://user-images.githubusercontent.com/28997207/210675672-2be24c82-e2a1-4ba3-872a-242f6c61fb3b.png)
- It is also possible that only one $ is replaced, with the other $ unchanged.
![image](https://user-images.githubusercontent.com/28997207/210675915-dca3a7fb-0c66-4f52-94e1-3411cec005da.png)
- Sometimes both $ are present, but zotero just failed to render it in latex.
![image](https://user-images.githubusercontent.com/28997207/210676099-a02ecb3b-f13d-4b17-9ba8-b4678c5f595a.png)
### Bug 2: Multiple Enter
- Also, sometimes more than one Enter is inserted between two lines separated by one single Enter.
-Before:
![image](https://user-images.githubusercontent.com/28997207/210676599-d438bdbc-b336-4a99-820e-fc5c7fd39626.png)
-After:
![image](https://user-images.githubusercontent.com/28997207/210676696-6771a71b-c6aa-4dce-b7ee-10d600927158.png)

### A more complex formula as an example:
Before:
![image](https://user-images.githubusercontent.com/28997207/210676156-77e44d9d-5a73-4885-8d59-0007228baefa.png)
After:
![image](https://user-images.githubusercontent.com/28997207/210676205-cffd8d23-fd7f-46c7-86b0-b91b82d14bc3.png)
![image](https://user-images.githubusercontent.com/28997207/210676227-3fd4e348-e0aa-4b41-a86c-ede14a0aedb6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Zotero 6.0.19
 - Better Notes 0.8.8 Build 2023-01-04

### Zotero crash report:

[JavaScript Error: "message is undefined" {file: "resource://zotero/note-editor/editor.js" line: 69997}]

[JavaScript Error: "TypeError: node is undefined" {file: "chrome://zotero/content/contextPane.js" line: 315}]
_focus@chrome://zotero/content/contextPane.js:315:1
_togglePane@chrome://zotero/content/contextPane.js:441:7
_toggleNotesButton@chrome://zotero/content/contextPane.js:271:5

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

[JavaScript Error: "TypeError: node is undefined" {file: "chrome://zotero/content/contextPane.js" line: 315}]
_focus@chrome://zotero/content/contextPane.js:315:1
_togglePane@chrome://zotero/content/contextPane.js:441:7
_toggleNotesButton@chrome://zotero/content/contextPane.js:271:5

[JavaScript Error: "TypeError: node is undefined" {file: "chrome://zotero/content/contextPane.js" line: 315}]
_focus@chrome://zotero/content/contextPane.js:315:1
_togglePane@chrome://zotero/content/contextPane.js:441:7
_toggleNotesButton@chrome://zotero/content/contextPane.js:271:5

[JavaScript Error: "TypeError: node is undefined" {file: "chrome://zotero/content/contextPane.js" line: 315}]
_focus@chrome://zotero/content/contextPane.js:315:1
_togglePane@chrome://zotero/content/contextPane.js:441:7
_toggleNotesButton@chrome://zotero/content/contextPane.js:271:5

[JavaScript Error: "message is undefined" {file: "resource://zotero/note-editor/editor.js" line: 69997}]

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

[JavaScript Error: "_notesPaneDeck.selectedPanel is undefined" {file: "chrome://zotero/content/contextPane.js" line: 209}]

version => 6.0.19, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.19, extensions => Zutilo Zotero 工具箱 (3.10.0, extension), ZotFile (5.1.2, extension), Jasminum (0.2.4, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.19, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.19, extension), Zotero Better Notes (0.8.8, extension)

**Comment by windingwind** [comment]
Thanks for the report. The error logs are not produced by this plugin.

This behavior may be related to the recent update, which tries to save note content from the editor before refreshing. I'll dig deeper to see what's happening there.

However, don't rely on the refresh, unless the editor behaves strangely. Zotero saves and updates the note from/to note editors automatically.

**Comment by windingwind** [comment]
removed in the next major version.
Closed for #429
