### ISSUE TITLE
[Bug]打开PDF后右侧的条目信息刷新缓慢

### ISSUE THREAD

**Issue by BoBo-YunYun** [windingwind/zotero-better-notes#314]
作者你好，今天使用better notes发现一个小bug：

在打开工作区的情况下，再打开条目的PDF，右侧的条目信息不刷新，需要过好一会儿才能刷新过来，如下图：
![image](https://user-images.githubusercontent.com/121593119/211128552-9647497d-e5d4-4368-ae56-cac27f365f15.png)

但是，在关闭工作区的情况下，打开PDF，右侧信息可以立马刷新。

**Comment by windingwind** [comment]
Closed for #429
