### ISSUE TITLE
[Feature] Extract tags and meta information of parentItem / Zotero main item

### ISSUE THREAD

**Issue by jankap** [windingwind/zotero-better-notes#319]
I might be misunderstanding the concept, but is there a way to export the main item's (e.g. the journal article or a book) meta information to markdown? Somehow, I'm missing that as the main item all my notes which come from annotations actually refer to when I look at the tree in Obsidian.

If yes, is there an automatic way?

Thanks :)

**Comment by windingwind** [comment]
Yes. Are you using the syncing, or the note template?

**Comment by jankap** [comment]
Honestly I don't know.

Let me describe: 
- import a Zotero item via pdf or doi
- add initial tags to the Zotero item
- skim the pdf, add annotations using the new PDF reader, tag the annotations, too

Now, what I'd love to have is an automated MD export of: 
- the Zotero main item, incl. all tags, meta data, bibtex citation key as a standalone .md file, using the citation key as filename
- all annotations, including their tags and meta data, and it's relation to the above mentioned main item, ideally as citekey

All MD files shall be synced in two ways. The expectation is that changing something in the MD file, it shall be reflected in the related Zotero item, e.g. the annotations shall change. 

Nice to have:
- automatically create a folder for each exported Zotero top level item where all annotations go into
- no notes below the Zotero top lvl item, just the PDF. The annotations are in the database, do I have to create note items to pull them out?

What I've tried:
- import the item, add tags etc. Rightclick on the zotero item -> export notes and subnotes -> error "no standalone/item note selected"
- created annotations in the pdf reader, try to export via process mentioned above -> still error "no standalone/item note selected"
- Clicked on the yellow "quick note" icon, a note item appears. Right click on top lvl item export now works, but no automatic sync is possible
- Export via note right click seems to work and sync seems to work. But only md file <-> note. The annotation is not updated -> inconsistency

I'm afraid I still don't understand the workflow of that plugin :)

Questions:
- how do I export the meta data of the main zotero item?
- do I have to enable syncing for every note explicitely?
- do I have to create a note for each annotation?
- is there a connection between note and annotation that can be synced?

Big thanks!

**Comment by windingwind** [comment]
sorry for the delay.

1. this plugin only provides note-markdown syncing, via GUI or via API. there will not be a way to **automatically** export things, at least not implemented in this plugin;
2. the metadata can be placed in the yaml header of the markdown. see the discussions. there are many templates available.
3. all syncing must be manually set (for now)
4. annotations cannot be exported. notes can be exported. so if you want to export an annotation to md file, you will need to create a note from it/embed it in a note first.
5. no. annotation embedded in a note cannot be updated when the annotation is changed.
