### ISSUE TITLE
[Feature] 模板中能否插入citation key，或者自动生成@citationkey这样命名的markdown，或者是能自定义默认文件名？

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#32]
模板中能否插入citation key，或者自动生成@citationkey这样命名的markdown，或者是能自定义默认文件名？
如果在支持批量导出markdown，我觉得就可以完全替代 mdnote和 obsidian里一些类似bibnotes 转换 better bibtex为markdown繁琐的工作流，实现一统天下了。

_Originally posted by @seifer08ms in https://github.com/windingwind/zotero-better-notes/issues/23#issuecomment-1144314595_

**Comment by windingwind** [comment]
@seifer08ms
@windingwind 关于导出所有子笔记避免重命名的问题，是否可以参考 better bibtex的解决方案，设置为默认@citationkey命名，obsidian的bibnotes解析的时候也默认citationkey。另外zotero的插件zotero obsidian citation默认也通过@citationkey在zotero的item上重新跳回obsidian的对应markdown，这套双向工作流习惯用的citationkey的方式比较有群众基础了，只要自己维护好zotero的citationkey唯一性就可以避免重名，better bibtex里可以在唯一性和可读性之间取一个平衡，来设置自动生成的citationkey的具体内容。

是否用默认命名可以通过选项只在批量导出所有子笔记为单独的markdown时才启用。

**Comment by windingwind** [comment]
为了方便讨论，移到此处。

**Comment by windingwind** [comment]
@seifer08ms
1. 关于citekey
主动维护citekey会是很大的工作量，且带来大性能消耗。由于bbt会在后台更新citekey增加耗电和性能占用，我平时都禁用它（这也是为什么不希望再走依赖citekey的老路）。Zotero内部对每个item都有内部的key，并且可以跨账号、平台使用，其他Ob/Zo插件放着现成的key不用却去用无法跨平台且依赖第三方插件的citekey，是低效且浪费的做法。

2. citekey与本功能的关系。 
citekey-条目是可以平衡可读性与唯一性的，但导出的**子笔记**大多数归属某条目，并一个条目会有多条笔记。bbt的基础是条目信息一般不变，但笔记内容可能发生任意变化。不算一个太好的策略。

为什么抵触“将一个话题内容导出到一个文件”呢？即使考虑到灵活性，仍然可以在任何时候返回Zotero并调整、编辑、重新导出

**Comment by windingwind** [comment]
@seifer08ms 谢谢详细耐心的回复。从开发者角度考虑，总是希望对一个功能规划到特别清晰再开展工作，因为必须考虑到不同用户的需求，并时刻留意实现的复杂性来保证系统可维护，非常感谢你能理解。这也是为什么我从决定开发这个插件开始就规划了这项功能，但迟迟没有做的主要原因。

并非抵触导出这样或那样的形式，如前所述，开发维护一个功能需要时间和精力投入，如果不经设计就开始做，可能导致后续无穷无尽的麻烦（开发者还要考虑不同版本间的兼容性，用户操作的习惯性），尤其是对于工作流有较大影响的功能，一直是持谨慎态度的。一般会等到我有充足时间快速修复bug时再上重大更新，平时比较多其他的事情要忙

端午假期愉快，节后我挑有空的时间先按照讨论的思路尝试做一下。保持联系！

**Comment by hpxing** [comment]
@seifer08ms 楼主所说的功能在青柠学术 的插件里实现了 不是推广别的插件 只是探讨一些使用上的问题~~~关于key的问题插件可以自己维护一种key，例如年份+作者+标题截取一部分+zotero里面那个唯一标识符

**Comment by windingwind** [comment]
@hpxing 通过模板功能，better notes也可以插入包括citekey在内的任意字段，这个之前就支持了。
主要的讨论是批量导出markdown，这个功能正在开发中

**Comment by windingwind** [comment]
@seifer08ms 
批量导出markdown已经可用，通过多选笔记条目后的右键菜单。尽管暂时其中的链接还是以嵌入原始笔记的形式出现。
在测试该批量导出功能稳定后，预计将会提供一个新的模板类型，ExportFileName，用于自定义导出的子笔记文件名规则（例如citekey等），默认是笔记标题+笔记的内部key。

**Comment by windingwind** [comment]
@seifer08ms 
批量/单个导出时，将子笔记作为单独的markdown与自定义文件名均可用。
自定义文件名可修改[ExportMDFileName]模板。默认是`笔记标题+笔记的内部key.md`，可以改成别的，如citekey

**Comment by seifer08ms** [comment]
@windingwind ，多谢，我学习下新功能。

**Comment by windingwind** [comment]
@seifer08ms 
这是我使用**导出一个主笔记及其链接子笔记为单独的多个markdown文件**功能后，在Obsidian中的效果。
配合模板功能的高度定制化特性，我有信心说，已经可以摆脱Zo-Ob联动的复杂插件和复杂配置了。
![image-20220614160012687](https://user-images.githubusercontent.com/33902321/173526766-a16e6569-e035-4b5e-8eca-255179fe3891.png)
