### ISSUE TITLE
[Feature] Show formula and figures at Zotero Reports

### ISSUE THREAD

**Issue by Fanisting** [windingwind/zotero-better-notes#320]
**Is your feature request related to a problem? Please describe.**
When I generate a report from the item, there are "Notes" section in the report, and everything looks nice except the screenshots and formula in the report. The screenshots are created by Zotero's "selected area". 

**Describe the solution you'd like**
Enable formula and figures in Zotero Report.

**Describe alternatives you've considered**
Maybe support the report as another document type that can be exported by Zotero-better-notes?

**Additional context**
My demand is to generate a beautiful report for others to see, so it may be enough for myself to manage the notes in workspace, it is still not enough to generate a report which contains:
1. meta data of the paper
2. My notes.

**Screenshots**:

In the note: 
![image](https://user-images.githubusercontent.com/87118530/211995602-edae9c2b-a41e-4938-966d-f992f40814a5.png)

But in the report, the figure disapprears:
![image](https://user-images.githubusercontent.com/87118530/211995789-ac4878a9-e317-47f4-a82b-af4ff9c9bfa4.png)

**Comment by windingwind** [comment]
Closed for #429
