### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zqdave1993** [windingwind/zotero-better-notes#321]
插入自带笔记模板table时，显示错误。
![image](https://user-images.githubusercontent.com/28385719/212852632-951ca1ed-22f7-4255-ac3c-984da55e4c62.png)
且我的没有默认的date模板。请作者百忙中解答一下，多谢！

**Comment by windingwind** [comment]
更新插件，更新模板（删除后重启插件），在discussion栏搜索需要的模板

**Comment by windingwind** [comment]
Closed for #429
