### ISSUE TITLE
[Help] Somehow imported content from all linked notes into main note

### ISSUE THREAD

**Issue by bradmont** [windingwind/zotero-better-notes#323]
I'm just getting started with better notes, it seems _awesome_ for knowledge management. But I kind of ruined my main note by somehow making it import the content from all linked notes (it also changed the display style, showing vertical bars along the side of nested items -- subheadings, imported linked note content, etc).

If you could let me know what I did, how I can avoid doing it again, and if it's possible to undo, I'd really appreciate it!

**Comment by bradmont** [comment]
Ooh, sorry, should I have put this in discussions?

**Comment by windingwind** [comment]
Hi,

OK to discuss here. I guess you are using the ‘embed linked note’ function?

This operation is not undoable in the latest version.

Manually delete the embeded linked note would help.

Two ways to embed the linked notes:

1. Click the embed button in link popup (appears when cursor is on a note link)

2. Export to new note with linked note embeded. This will create a new note with links embedded, while the original note will not be overwritten.
