### ISSUE TITLE
[Bug] 通过笔记模板插入Item会在前上方多插入空行

### ISSUE THREAD

**Issue by mffseal** [windingwind/zotero-better-notes#328]
我想使用笔记模板的插入Item功能，为每篇文章的笔记添加一级标题，方便双向链接到主笔记时识别到标题。
我的笔记模板如下：
[Item] insert title：
```js
<h1>${topItem.getField("title").trim()}</h1>
```
但是插入到笔记后会在标题前多出空行，导致点击Link按钮后无法识别的一级标题。

**Comment by windingwind** [comment]
Closed for #429
