### ISSUE TITLE
[Bug] Sync button greyed out when attempting to save to markdown

### ISSUE THREAD

**Issue by wilkohardenberg** [windingwind/zotero-better-notes#329]
**Describe the bug**
As per the title, the auto-sync option is greyed out when I attempt to save a note to markdown

**To Reproduce**
1. Click export with linked notes button in upper right corner
2. Save and sync dialog pops up
3. Check relevant boxes

**Expected behavior**
The button should not be greyed out and autosync should work

**Screenshots**
![Screenshot 2023-01-24 at 12 33 59](https://user-images.githubusercontent.com/1612993/214281817-a69176e8-276b-468d-8ce8-bc0b161b26ff.png)

**Desktop (please complete the following information):**
 - OS: Mac 12.4

**Comment by windingwind** [comment]
Syncing to MD is not possible with `Embed linked notes` enabled. Hover the checkbox and there will appear a tooltip describing what happens. It is designed to be so, not a bug.
Thanks for your report.
