### ISSUE TITLE
[Bug] Can't find the add-on's own menu

### ISSUE THREAD

**Issue by wilkohardenberg** [windingwind/zotero-better-notes#330]
**Describe the bug**
I'm unable to find the menu from where to add files to the workspace and manage the templates.

**To Reproduce**
I open the workspace and there is no menu.

**Expected behavior**
I expected a menu to be there in the upper left corner of the image below.

**Screenshots**
![image](https://user-images.githubusercontent.com/1612993/214583500-40352fcb-e42e-420b-af3f-11e6d243c276.png)

**Desktop (please complete the following information):**
 - OS: Mac 12.4

**Comment by windingwind** [comment]
Macos menu bar is on the top of the screen.
