### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by akgfelice** [windingwind/zotero-better-notes#331]
**Is your feature request related to a problem? Please describe.**
If I try to add an item to the main note using  the cite button I get no link but a line saying "undefined"
**Describe the solution you'd like**
I would like to be able to insert a link as I would do it when writing in a word processor by selecting from my library, regardless if there is already a note or extracted annotations.

**Describe alternatives you've considered**
I can create a note manually and then create a link starting from the note, but this is an extra step I hope I can avoid. 

**Additional context**
I am not sure if this might be actually a bug. I am on the standalone zotero version 6.0.19-beta.15+6374aea1c. Add ons: Better Bibtext, Zutilo, Zotfile and word integration. I am on Windows 10

Thanks for your effort. This add on could be a game changer.

**Comment by windingwind** [comment]
The citation button is removed in the next version. Closed for #429
