### ISSUE TITLE
笔记中图片在不同设备间无法同步显示

### ISSUE THREAD

**Issue by sageyin** [windingwind/zotero-better-notes#332]
**Describe the bug**
截图笔记的图片在不同设备间无法同步，只在一台截图的设备上正常。
文字笔记，双向链接同步正常。

**Expected behavior**
希望可以在不同设备间同步显示**图片笔记**。

**Screenshots**

![图片同步异常](https://user-images.githubusercontent.com/55968895/215035324-82ffd558-bf63-4f3d-ad4a-7547a436c6f3.png)

**Comment by windingwind** [comment]
同步问题请反馈zotero官方社区，与插件无关

**Comment by sageyin** [comment]
好的，感谢！

**Comment by sageyin** [comment]
> 同步问题请反馈zotero官方社区，与插件无关

好的，谢谢

**Comment by 1tonsilla** [comment]
> 同步问题请反馈zotero官方社区，与插件无关

官方关于同步图片相关方案可能很难改变。
我使用zotfile+同步盘，不知道better note能否将笔记中的图片通过zotfile转移到同步盘的文件夹中，来达到同步图片的目的呢？
