### ISSUE TITLE
[Feature] Sync imported note

### ISSUE THREAD

**Issue by davidoskky** [windingwind/zotero-better-notes#333]
**Is your feature request related to a problem? Please describe.**
I'm using https://github.com/mgmeyers/obsidian-zotero-integration to quickly add citations in obsidian; this automatically generates a note for the article and I sometimes use that to quickly take some notes. This notes however will not be shown in Zotero. To show them in Zotero I have to copy them in manually and then export the note with sync.
It is possible to import the note, and that will work; however there's no option to keep it in sync on the same file, you have to export it again and Better Notes will generate a new file with the note content.
This is problematic because Better Notes and this obsidian plugin use different conventions for filenames and are thus not compatible.

**Describe the solution you'd like**
Allow importing a note and keeping the original file in sync.

**Describe alternatives you've considered**
These two systems cannot really work together at the moment. Either this allows exporting notes with custom filenames or the other plugin should be able to be set to specific filenames, but that feels more complex as user interaction.
It's currently impossible to make them work together because of the random string of characters added to the end of the file name.

**Comment by windingwind** [comment]
The filename is controlled by the template [ExportMDFilename]. You can remove the item key and format the filename to for your need.

Syncing the imported md file is possible. Hopefully after the big update for Zotero 7 compatibility, I could work on this.

Thanks for the feedback!

**Comment by davidoskky** [comment]
Alright, thanks!
I was able to edit the export filename to make the two systems work together.
Anyways, if it will be possible to import and sync files with a custom filename I would prefer that.
Thank you for your great work and availability!

**Comment by windingwind** [comment]
the latest beta supports this.
