### ISSUE TITLE
[Feature]在工作区主笔记页面也显示标签

### ISSUE THREAD

**Issue by nickcao123456** [windingwind/zotero-better-notes#334]
**Is your feature request related to a problem? Please describe.**
工作区主笔记链接的笔记多了之后难以管理，在查找某个想要的笔记时很花费时间
**Describe the solution you'd like**
在工作区的左下角也添加跟主页一样的标签筛选功能或者是类似的功能，可以快速筛选笔记

**Comment by windingwind** [comment]
Closed for #429
