### ISSUE TITLE
[Bug]通过标签添加笔记直接显示在光标出，而不会识别其对应的节标签

### ISSUE THREAD

**Issue by Emily-one** [windingwind/zotero-better-notes#335]
通过标签 # 添加笔记直接显示在主笔记光标处，而不会识别其对应的节标签。

**Comment by Xulangsz** [comment]
我的情况也一样。
另外注释的评论里没有对应的链接，如果点击quick note，会生成一样的笔记，这时候注释的评论里出现无法跳转的链接，同时笔记里双链的添加位置和跳转是正常的。

**Comment by windingwind** [comment]
Closed for #429
