### ISSUE TITLE
对PDF导出功能进行优化，现在的pdf导出后为无边框的且带有[H]符号，不美观且不方便打印

### ISSUE THREAD

**Issue by FemiSphere** [windingwind/zotero-better-notes#340]
首先非常感谢作者的一系列工作。
目前betternotes导出的pdf文件是无边框的，并且带有类似H1或H2这样的标识符。
希望better notes能够对pdf导出功能进行优化，实现带有一定页边距的文件导出（类似Obsidan的pdf导出，当然有了betternotes之后就很少用Obsidan了），这样文件更方便分享和打印。

**Comment by Sunnanini** [comment]
跪求作者大大可以把导出pdf的功能优化一下，能使用户到处时，可以选择导出的纸张大小和页边距之类的。
即使代码收费也是支持的~知识付费我愿意~

**Comment by windingwind** [comment]
Closed for #429
