### ISSUE TITLE
[Bug]同时用night和betternotes插件时，右侧笔记栏一直处于夜晚模式

### ISSUE THREAD

**Issue by suyouR** [windingwind/zotero-better-notes#341]
**Describe the bug**
同时用night和betternotes插件，有时候右侧笔记栏在白天模式正常使用中是夜晚模式，但是打开单独编辑窗口或者工作区就又是正常的了。

**To Reproduce**
1. 直接打开就能看到

**Expected behavior**
修复bug

**Screenshots**
![image](https://user-images.githubusercontent.com/122534045/216221494-365847bb-c95b-47f4-b117-a38b026ff23b.png)

**Desktop (please complete the following information):**
 - Version [0.8. 8]

**Comment by windingwind** [comment]
与本插件无关，请向night作者报告
