### ISSUE TITLE
[Feature] Collapse or expand headings

### ISSUE THREAD

**Issue by SquareSon** [windingwind/zotero-better-notes#344]
**Is your feature request related to a problem? Please describe.**
I wonder if it is possible to allow users to collapse or expand headings in your document, like Microsoft Word, so that a wordy note is more clear.

**Describe the solution you'd like**
To collapse or expand headings in your document, like Microsoft Word.

**Comment by windingwind** [comment]
Not possible as a plugin, limited by the note framework Zotero uses.
