### ISSUE TITLE
[Feature]能否增加打印机或注释文字框功能

### ISSUE THREAD

**Issue by poricaihong** [windingwind/zotero-better-notes#346]
大佬，请问能否增加类似“打字机“或”注释框“这样的文字注释功能，可以直接在文件上标注文字而不是现在这样只是一个注释的标签，这样阅读起来更方便，一目了然不用去看注释栏。

**Comment by windingwind** [comment]
应向zotero社区反馈。该插件只负责笔记，批注不是插件内容范围。

**Comment by poricaihong** [comment]
谢谢。已看到zotero的开发者已收到相似的意见，正在准备处理，但是过程很慢，好像说是比较大的更新。
----- 原始邮件 -----
发件人：windingwind ***@***.***>
收件人：windingwind/zotero-better-notes ***@***.***>
抄送人：poricaihong ***@***.***>,  Author ***@***.***>
主题：Re:_[windingwind/zotero-better-notes]_[Feature]能否增加打印机或注释文字框功能_(Issue_#346)
日期：2023年03月27日 23点32分


应向zotero社区反馈。该插件只负责笔记，批注不是插件内容范围。
