### ISSUE TITLE
item links broken in markdown export

### ISSUE THREAD

**Issue by Sleepwalker6** [windingwind/zotero-better-notes#35]
1. After exporting to markdown in obsidian links to annotaions are broken (both annotation page and the item). Item ID is missing.
2. Shortcuts are missing in ouline area. There is only view mode.
![image](https://user-images.githubusercontent.com/106707747/171728297-8b6989cf-f6f5-483e-a8f7-8581a5d83d8e.png)

I am on widows 7 OS. 
Thanks for the great addon.

**Comment by windingwind** [comment]
1. Does this happens to EVERY link? Please check if the cited attachment is moved or deleted.
2. These buttons are moved to the menu bar on the left top of the window.left top

**Comment by Sleepwalker6** [comment]
1. Yes, every link is broken.  ID of the items is missing. 
![1](https://user-images.githubusercontent.com/106707747/171808458-f1d70dd3-2fdc-4f48-9248-948079f5ddba.jpg)


3. I found another issue with the page number in the link to the annotaion. Page number on the link to the annotaion is a wrong page and is not the same with the alias shown before that.
 
![2](https://user-images.githubusercontent.com/106707747/171809138-76d19198-dd69-4dbb-94b3-6136671c74f3.jpg)

thank you very much.

**Comment by windingwind** [comment]
So weird. This should not happen, for the code for generating this link is exactly the same as Zotero's official note2markdown code.

May I ask how did you get the right version?

**Comment by Sleepwalker6** [comment]
Thanks.
Its an addon called zotero integration for obsidian

https://github.com/mgmeyers/obsidian-zotero-integration

**Comment by windingwind** [comment]
I compared the code of Zotero integration for obsidian, finding out that there does exist a difference when processing annotation links.

Better Notes follows the standard Zotero way, which means this might be a Zotero bug, or your annotation data is modified by some addons in a somehow non-standard way. You can try to export the note with Zotero's built-in note exporting function and see if it is broken.

As for the page, again, the int4ob uses `pageLabel` and we use `position.pageIndex + 1`, as Zotero does. I can't judge which one is right. I'd prefer to follow the Zotero way.

Here is the new version. Please download, unzip, and try and see if the bug is fixed.
[test_version_35.zip](https://github.com/windingwind/zotero-better-notes/files/8833905/test_version_35.zip)

**Comment by Sleepwalker6** [comment]
I used zotero's export function(Right-click on the main note, select export note >choose markdown) and it was Ok. and exported md file has valid links and links are not broken.
I also used the test_version_35 and it still produce broken links.

For page number I think you addon does right and has no problem.

**Comment by windingwind** [comment]
Please try this and paste debug output here:
After installed, please go to Help->Debug Output Logging->View Output, and then do a note export.
After the export, please copy everything in the debug output window and paste them here.
[test2.zip](https://github.com/windingwind/zotero-better-notes/files/8836617/test2.zip)

**Comment by windingwind** [comment]
Sorry for my late reply. I was just busy fixing bugs in the 0.5.x update. Is this bug still exist?

**Comment by Sleepwalker6** [comment]
Unfortunately I still have that problem.([title_paper](zotero://select/library/items/items))
I am on 0.5.15.
Thanks

**Comment by windingwind** [comment]
@Sleepwalker6 
It is very strange. The export works well with my notes.
Anyway, I use the same code as the Zotero default export for this part. as I've mentioned.
Do you have any ideas? Please provide any evidence that might be related to this bug. Or, did you try to disable all other addons and export again?

**Comment by Sleepwalker6** [comment]
Thanks, I will try that with other addons disabled and also with another computer . I'll send the results here. Thank you

**Comment by Sleepwalker6** [comment]
I disabled All the addons except Zotero betternotes. 
When I export the note using the addon I still have the issue with the link.
But exporting with zotero creates no problem at all.
![image](https://user-images.githubusercontent.com/106707747/174650591-63faa0ef-02c5-4fdc-8bbe-2f64ef1231e5.png)

**Comment by windingwind** [comment]
@Sleepwalker6 

Please try the debug steps:
1. Make sure there is at least one highlight annotation in your main note;
2. Goto Tools->Developer->Run JavaScripts;
3. Paste this code there and press 'Run'
```js
var container = Zotero.Knowledge4Zotero.knowledge.parseNoteHTML();
var nodes = container.querySelectorAll(
  'span[class="highlight"], img[data-annotation]'
);
var annotation = JSON.parse(
  decodeURIComponent(nodes[0].getAttribute("data-annotation"))
);
let uri = annotation.attachmentURI || annotation.uri;
uri
```
![image](https://user-images.githubusercontent.com/33902321/174953023-bfe9dab1-fd36-4f91-9aa4-79f18c3da42f.png)
4. Paste the output result here.

**Comment by Sleepwalker6** [comment]
There is something I should mention: zotfile has a feature to manage your pdf attachments.
![image](https://user-images.githubusercontent.com/106707747/175359521-75653ece-301a-48a8-822a-f671d99ad9fb.png)

You can give locations other than zotero's main storage and rules to organize your pdfs. Maybe that is the problem.

**Comment by Sleepwalker6** [comment]
I tried above process on another computer: 
- win10 + all addons disabled >> The same results
![Uploading anotherPC.jpg…]()

**Comment by windingwind** [comment]
So weird. The item link inside Zo is correct.
Please update to the latest version and try:
1. Open 'Help->Debug output->View output' and do an export.
2. Copy-paste all outputs here.

There should be item links like:
```
(3)(+0000001): Translate: http://zotero.org/users/6099279/items/9RJQMLTE

(3)(+0000000): Translate: 9RJQMLTE

(3)(+0000004): { "key": "ZWY9GYFU", "version": 7362, "itemType": "attachment", "parentItem": "9CYAM3SZ", "linkMode": "embedded_image", "contentType": "image/png", "filename": "image.png", "dateAdded": "2022-06-07T07:27:55Z", "dateModified": "2022-06-07T07:27:55Z" }

(3)(+0000163): Translate: C:\Users\w_xia\Zotero\storage\3YPFT4A2\image.png

(3)(+0000002): Translate: C:\Users\w_xia\Desktop\test\attachments\3YPFT4A2.png

(3)(+0000023): Translate: C:\Users\w_xia\Zotero\storage\ZJVYZSAL\image.png

(3)(+0000001): Translate: C:\Users\w_xia\Desktop\test\attachments\ZJVYZSAL.png

(3)(+0000002): Translate: C:\Users\w_xia\Zotero\storage\ZWY9GYFU\image.png

(3)(+0000001): Translate: C:\Users\w_xia\Desktop\test\attachments\ZWY9GYFU.png
```

**Comment by windingwind** [comment]
Seem like this only happens to you and I still don't know what's going on with your export. Using remote connection/control software would be more efficient to solve the problem if possible.

**Comment by Sleepwalker6** [comment]
I really doubt that I am the only one. 
Today I installed zotero (6.0.9) and the addon(0.5.17) on a new brand windows 10. (no other addon is installed)
and stills the problem exists.

**Comment by windingwind** [comment]
Could you please show me the debug output?
I haven't received similar bug reports. As this issue has been open for weeks, it is possible that this only happens to you, or at least not all users.
I'll help you and try to figure out why. However, it is challenging for developers to fix a bug that cannot be reproduced. If possible, I would recommend allowing me to access your PC via remote control. If you do not trust third-party software, we could also use MS remote desktop.

**Comment by Sleepwalker6** [comment]
I should say I really appreciate your help and patience, since I cheked  the addon on 3 different pcs I thought I must be doing something wrong.
For links to zotero item and pdf page to work it seems that we need 3 different IDs.
![image](https://user-images.githubusercontent.com/106707747/175810227-0cfc0ccd-3e3b-43ca-bf6e-8ab703bdb9dc.png)

- The addon (for me) fails to produce ID#1 (which is GA3GVJD9 in this case according to zotro's native export).
- Addon has no problem with creating ID#2 ( which VHPNJXBP) 
- The code you mentioned above produces  ID#2 which was already OK with the addon. 
- What we need to chech is ability of the addon to produce ID#1 (GA3GVJD9)

**Comment by Sleepwalker6** [comment]
`
[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 783}]

[JavaScript Error: "TypeError: io is undefined" {file: "chrome://zotero/content/note.js" line: 38}]

Security Error: Content at moz-nullprincipal:{7dc7b058-07f6-7aa3-b049-beeb0ba78e9e} may not load or link to chrome://knowledge4zotero/content/treeView.html.

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///C:/Users/Me/AppData/Roaming/Zotero/Zotero/Profiles/v4fjkukv.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/translators/Better%20Note%20Markdown.js
Line Number 1, Column 1:" {file: "jar:file:///C:/Users/Me/AppData/Roaming/Zotero/Zotero/Profiles/v4fjkukv.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/translators/Better%20Note%20Markdown.js" line: 1 column: 1 source: "/*"}]

version => 6.0.9, platform => Win32, oscpu => Windows NT 6.1; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.9, extensions => Zotero Better Notes (0.5.17, extension), ZotFile (5.0.16, extension, disabled), Mdnotes for Zotero (0.2.3, extension, disabled), MarkDBConnect (0.0.18, extension, disabled), Better BibTex for Zotero (6.7.10, extension, disabled), Zotero LibreOffice Integration (6.0.0.SA.6.0.9, extension, disabled), Zotero Word for Windows Integration (6.0.0.SA.6.0.9, extension, disabled)

(3)(+0027813): Notifier.trigger('select', 'tab', [tab-X2y2Rxaj], {"tab-X2y2Rxaj":{"type":"betternotes"}}) called [observers: 5]

(3)(+0000066): Reloading tags box

(3)(+0000006): Knowledge4Zotero: onEditorEvent addNoteInstance

(3)(+0000046): Knowledge4Zotero: main Knowledge

(3)(+0000032): Knowledge4Zotero: onEditorEvent enterWorkspace

(3)(+0000308): itemTree.render(). Displaying Item Tree

(3)(+0000049): Knowledge4Zotero: updateMindMap

(3)(+0001881): Knowledge4Zotero: onEditorEvent export

(3)(+0000774): Starting full-text content processor

(3)(+0000072): Better Notes: sync start

(3)(+0000832): { "dataIn": null "dataOut": null "deferred": { "resolve": function(value) {...} "reject": function (reason) {...} "promise": { "isFulfilled": false, "isRejected": false } } }

(3)(+0000004): ===>null<=== (object)

(3)(+0000015): Getting contents of chrome://Knowledge4Zotero/content/translators/Better Note Markdown.js

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000001): HTTP GET chrome://Knowledge4Zotero/content/translators/Better Note Markdown.js

(3)(+0000050): HTTP GET chrome://Knowledge4Zotero/content/translators/Better Note Markdown.js succeeded with 200

(3)(+0000001): /* ***** BEGIN LICENSE BLOCK ***** TOO MUCH TEXT HERE} }

(3)(+0000058): Saving translator 'Better Note Markdown'

(3)(+0000001): { "translatorID": "1412e9e2-51e1-42ec-aa35-e036a895534c" "label": "Better Note Markdown" "creator": "Martynas Bagdonas; Winding" "target": "md" "minVersion": "5.0.97" "maxVersion": "" "priority": 50 "configOptions": { "noteTranslator": true } "displayOptions": { "includeAppLinks": true } "inRepository": true "translatorType": 2 "lastUpdated": "2022-06-01 23:26:46" "_codePath": "chrome://Knowledge4Zotero/content/translators/Better Note Markdown.js" }

(3)(+0000014): Initializing translators

(4)(+0000001): SELECT rowid, fileName, metadataJSON, lastModifiedTime FROM translatorCache

(3)(+0000117): Getting contents of D:\Programfiles2\ZoteroLocal\translators\Better Note Markdown.js

(4)(+0000005): REPLACE INTO translatorCache VALUES (?, ?, ?) ['Better Note Markdown.js', '{"translatorID":"1412e9e2-51e1-42ec-aa35-e036a895534c","translatorType":2,"label":"Better Note Markdown","creator":"Martynas Bagdonas; Winding","target":"md","priority":50,"lastUpdated":"2022-06-01 23:26:46","browserSupport":"g","minVersion":"5.0.97","maxVersion":"","inRepository":true,"configOptions":{"noteTranslator":true},"displayOptions":{"includeAppLinks":true}}', 1656242473533]

(3)(+0000533): Cached 681 translators in 655 ms

(4)(+0001784): Translate: Binding sandbox to http://www.example.com/

(3)(+0000011): Getting contents of D:\Programfiles2\ZoteroLocal\translators\Better Note Markdown.js

(4)(+0000034): Translate: Parsing code for Better Note Markdown (1412e9e2-51e1-42ec-aa35-e036a895534c, 2022-06-01 23:26:46)

(3)(+0000011): Translate: Beginning translation with Better Note Markdown

(3)(+0000008): Translate: ----Debug Link----

(3)(+0000004): { "attachmentURI": "http://zotero.org/users/local/ydE4i5nD/items/VHPNJXBP" "annotationKey": "L8VJVKS9" "color": "#ffd400" "pageLabel": "1455" "position": { "pageIndex": 1 "rects": [ "0": [ "0": 57.657 "1": 671.261 "2": 209.779 "3": 679.687 ] "1": [ "0": 57.657 "1": 659.299 "2": 210.289 "3": 667.725 ] "2": [ "0": 57.657 "1": 647.337 "2": 175.666 "3": 655.763 ] ] } "citationItem": { "uris": [ "0": "http://zotero.org/users/local/ydE4i5nD/items/GA3GVJD9" ] "locator": "1455" } }

(3)(+0000001): Translate: http://zotero.org/users/local/ydE4i5nD/items/VHPNJXBP

(3)(+0000001): Translate: VHPNJXBP

(3)(+0000001): Translate: ----Debug Link----

(3)(+0000002): { "attachmentURI": "http://zotero.org/users/local/ydE4i5nD/items/VHPNJXBP" "annotationKey": "KUQ7LEEE" "color": "#ffd400" "pageLabel": "1455" "position": { "pageIndex": 1 "rects": [ "0": [ "0": 399.344 "1": 372.376 "2": 544.923 "3": 380.802 ] "1": [ "0": 394.413 "1": 360.414 "2": 544.968 "3": 368.84 ] "2": [ "0": 394.413 "1": 348.452 "2": 542.41 "3": 356.878 ] ] } "citationItem": { "uris": [ "0": "http://zotero.org/users/local/ydE4i5nD/items/GA3GVJD9" ] "locator": "1455" } }

(3)(+0000002): Translate: http://zotero.org/users/local/ydE4i5nD/items/VHPNJXBP

(3)(+0000001): Translate: VHPNJXBP

(3)(+0000021): Translate: Translation successful

(5)(+0000001): Translate: Running handler 0 for done`

**Comment by Sleepwalker6** [comment]
[aaa.txt](https://github.com/windingwind/zotero-better-notes/files/8986497/aaa.txt)

**Comment by windingwind** [comment]
Hi, I just made some fixes to the bugs with the export & quick note function.
Could you please check if the broken link & image loss bugs still happen?

**Comment by Sleepwalker6** [comment]
Hi Thanks, 5.18 didnt fix the item link. 
v5.19 and 5.20 export emty files and don't export anything.

**Comment by windingwind** [comment]
> Hi Thanks, 5.18 didnt fix the item link. v5.19 and 5.20 export emty files (0 byte md file) and don't export anything. The also fail to export annotations(for me).

Sorry to hear that. However, this also means we might be close to the true cause of the bug.
I'd like to know:
1. Is the main note/its linked sub-notes/annotations/citations in a group library?
2. Does the progress window 'Export to xxx.md' show up when the latest version exports empty files? Does it happen to both two export ways, or just in one?
3. Could you please paste the debug output?

Thanks a lot!

**Comment by windingwind** [comment]
The progress window is: 
![image](https://user-images.githubusercontent.com/33902321/176086600-1c414d2e-6cef-4e2a-b2f8-fdc5be8995f2.png)

And could you please show me the debug output? The blank output indicates there might be a conversion bug.
Thanks for your patience!

**Comment by Sleepwalker6** [comment]
After checking that on 2 pcs:
- Yes, It shows the progress window.
- what I see while experimenting with the addon was that whenever main note contains images it creates empty file and attachment folder. However when there is only text in the main note the addon creates the markdown file with valid content.
- Even when the file is ok the link problem (.../items/items) still remains unchanged.
- currently I can't send the debug file. I'll try to send as soon as its possible.

**Comment by windingwind** [comment]
No hurry. You can also email me the debug file: wyzlshx@foxmail.com

**Comment by Sleepwalker6** [comment]
Do you have any ideas on what might be the problem? Can't you reproduce the current problem especially with 5.20 which the problem might seems even worse.
For a few days I won't be able to check the addons.
Thanks

**Comment by windingwind** [comment]
The v0.5.19 & 20 fix the bugs below:
1. Linked notes in different groups cause the output image lost.
2. Async bugs with export. In old versions, the next export will not wait for the former one's finish. Thus sometimes the image will not be exported correctly.

These fixes are related to #68. However, in the case that your links are broken, the new code of image link parsing may be the cause of the blank export bug.

**Comment by windingwind** [comment]
Hi, fixing this bug is planned as always. I am waiting for the debug output😳

Please send me the output when you have the blank file exported?

**Comment by windingwind** [comment]
Any updates?

**Comment by Sleepwalker6** [comment]
just sent a debug file.
Thanks

**Comment by windingwind** [comment]
Thanks. I've emailed you a new version of this plugin.

**Comment by windingwind** [comment]
Any updates?

**Comment by Sleepwalker6** [comment]
Hi,I haven't thoroughly tested the new unpdate, but it seems that:- the empty file problem is resolved.- the item/item problem is still exist.

    On Friday, July 29, 2022 at 09:04:09 AM GMT+4:30, windingwind ***@***.***> wrote:  
 
 


Any updates?

**Comment by Sleepwalker6** [comment]
One question:While exporting [!note] (which is callout format in obsidian) special characters have `\` before them (pic1). Is  there a way to avoid that and have pic2.Thanks



    On Friday, July 29, 2022 at 10:42:00 PM GMT+4:30, Sajadinia, Hosein ***@***.***> wrote:  
 
  Hi,I haven't thoroughly tested the new unpdate, but it seems that:- the empty file problem is resolved.- the item/item problem is still exist.

    On Friday, July 29, 2022 at 09:04:09 AM GMT+4:30, windingwind ***@***.***> wrote:  
 
 


Any updates?

**Comment by windingwind** [comment]
glad to know the blank file bug is fixed. I’ll install a new Zotero using local library recently to see what’s happening to the links.

about the [] conversion: should I just disable this conversion rule([]=>\[\]), or just disable it for the [!note] case?

**Comment by Sleepwalker6** [comment]
Thanks.[!note] is just an example and there are different callout style.Having the option to disable it on [ and ] would be great.

    On Saturday, July 30, 2022 at 06:12:10 AM GMT+4:30, windingwind ***@***.***> wrote:  
 
 


glad to know the blank file bug is fixed. I’ll install a new Zotero using local library recently to see what’s happening to the links.

about the [] conversion: should I just disable this conversion rule([]=>[]), or just disable it for the [!note] case?

**Comment by windingwind** [comment]
I just tested on my new Zotero environment and everything seems to be OK now. Could you please try the latest version?
BTW, the [] conversion is not handled yet.

I guess the images are correctly exported now. Please also check #75 .

Thanks for the patience!

**Comment by windingwind** [comment]
The [] conversion is supported in the latest release
