### ISSUE TITLE
[Note Template] 手动添加的yaml会被自动同步覆盖，被[ExportMDFileHeader]中的yaml覆盖

### ISSUE THREAD

**Issue by zzytim** [windingwind/zotero-better-notes#351]
## Template Type

不选择yaml的时候可以导出为无yaml的md文件
![image](https://user-images.githubusercontent.com/112047514/217120535-5c14aafe-dfaa-4ecf-b1b0-ba5f32b2b408.png)
然后手动添加yaml，可以为自定义的yaml
![image](https://user-images.githubusercontent.com/112047514/217120809-4642b56f-dccd-4024-bb78-4dfbb158482c.png)
但是自动同步会覆盖自定义的yaml，即使导出时候没有选择yaml
![image](https://user-images.githubusercontent.com/112047514/217121360-3e73c63e-10e3-4e4e-9268-4cc258bb966d.png)

## Desired Template Performance

Describe what you want.
希望添加用户自定义yaml的[ExportMDFileHeader]。或者可以不勾选yaml的时候不同步yaml，这样可以自定义yaml

## Current Template

```js
// Paste your template here
${await new Promise(async (r) => {
  let header = {};
  header.tags = noteItem.getTags().map((_t) => _t.tag);
  header.parent = noteItem.parentItem? noteItem.parentItem.getField("title") : "";
  header.collections = (
    await Zotero.Collections.getCollectionsContainingItems([
      (noteItem.parentItem || noteItem).id,
    ])
  ).map((c) => c.name);
  r(JSON.stringify(header));
})}
```

**Comment by windingwind** [comment]
Closed for #429
