### ISSUE TITLE
[Bug] 通过注释添加笔记时候的几个bug

### ISSUE THREAD

**Issue by molu-ggg** [windingwind/zotero-better-notes#352]
1.虽然说右键可以添加注释到笔记，但是一般都是先高亮再注释的，但是这个插件无法做到
2.虽然可以通过高亮直接添加注释到笔记，但是笔记每次插入会刷新，刷新后会自动跳转到笔记页开始的部分，这太太太太不方便了
3.笔记可以显示高亮，但是新插入的笔记并不会开启高亮
4.将翻译内容添加到主笔记只有当该插件关闭界面的时候才能插入到笔记里，否则智慧显示原文高亮内容
可以说2,3,是致命的遗憾，希望您能改善，谢谢！

**Comment by SYH0323** [comment]
1.笔记窗口右上角的三个点，显示注释颜色；
2.直接拖拽高亮区域到子笔记；
3.通过1和2就解决了；
4.我不清楚你说的意思。
