### ISSUE TITLE
[Feature] 插入的本地文件链接，能否增加预览和打开功能

### ISSUE THREAD

**Issue by Langeeker** [windingwind/zotero-better-notes#354]
一般的 markdown 笔记软件，拖入本地文件后，会自动转换成链接形式出现，zotero 里拖拽文件到笔记没有反应。即使复制了本地文件路径作为链接，也不能像 url 链接一样打开链接（打开本地文件）。如果这个功能能实现，再加上对本地文件链接的一个多媒体文件预览功能，zotero 笔记就和一般的笔记软件一样好用了。再次谢谢开发者的贡献，感谢！

**Comment by windingwind** [comment]
Closed for #429
