### ISSUE TITLE
[Feature] Markdown导出图片到不同文件夹 (separate image in different folder when export markdown file)

### ISSUE THREAD

**Issue by Losk-x** [windingwind/zotero-better-notes#356]
**Is your feature request related to a problem? Please describe.**

English: I'm always frustrated when the exported markdown images all in one folder ("attachments") with confused image name. It's hard to classify the markdown file related to the image with its name or path. 

中文：导出markdown文件时，图片路径无法对应到markdown文件，目前是统一存放到attachments目录下无法区分。当导出多个不同markdown文件时，它们的图片路径混在一起，难以区分迁移。

**Describe the solution you'd like**

English: When export markdown file, build a folder as a subfolder of "\attachments" for every markdown file with the filename as the folder name in order to separate the attachment per markdown file. 

中文：需要在导出markdown文件时，在attachments目录下建立以markdown文件名的文件夹，存放该markdown文件包含的图片。

**Comment by windingwind** [comment]
暂不支持
