### ISSUE TITLE
功能：请考滤导出 Latex 文件的功能

### ISSUE THREAD

**Issue by normanify** [windingwind/zotero-better-notes#36]
很多杂志要求文章不需要 Word格式，而是要求提供 latex 文件。请考滤能否增加导出 Latex 文件的功能？

**Comment by normanify** [comment]
使用下来，觉得 BetterNote 可以作为写作的工具了。而不是单纯做一点笔记。

**Comment by windingwind** [comment]
latex是一种代码格式，`.tex`的编译需要多种依赖包，并根据不同的环境、编译器、预设代码内容不同而不同。插件受限于安装包大小，无法实现完整的latex功能。

因此，如果从带格式的笔记导出到latex，很可能与论文需要的格式不同。

如果以纯文本格式导出源码，笔记的功能优势将无法体现，无法使用笔记中所有的格式选项，包括标题，高亮，引用链接等等。

推荐用overleaf平台编辑latex，不需要配置环境。

**Comment by normanify** [comment]
出版社一般有自己的 Latex样式模版，无需考滤格式问题。真正需要的功能是从 Markdown 中的文本对应到 Latex 中：
标题：
1）#      ->  \chapter{Chapter 1}
2)  ##   -> \section{ Section 1}
3)  ### -> \subsection{ Section 1.1}

图片：
4）[(img)] -> \graphic{...}

文献引用：
5) [referecne] -> \cite{citationKey}

这些功能导出的内容，足够用户将文档迁移到任意 Latex 环境中 Overleaf 中。

**Comment by windingwind** [comment]
由于长时间无回复，将关闭问题
