### ISSUE TITLE
[Feature]关于插入引注功能的格式问题

### ISSUE THREAD

**Issue by vzionv** [windingwind/zotero-better-notes#366]
**Feature描述**
当我使用插入引注功能时，选择插入引注后在note中显示的是：（作者，年份），如p1所示，能否自定义引注格式，比如（标题，作者）。
![p1](https://user-images.githubusercontent.com/67307337/219937958-9bdde538-0053-4026-b943-cc41516ab901.png)

**所做尝试**
我尝试了修改zotero-better-notes的“笔记引用格式”选项（p2），但是这个选项好像只针对“Insert Citations"有效（p3）。
我也尝试了修改zotero首选项中的导出格式（p4），但仍然无济于事。
据我所知，这个引注格式与样式文件(.csl)有关，有两种numeric和author-date，但zotero-better-notes似乎并不理会两种类型，只采用author-date格式。
![p2](https://user-images.githubusercontent.com/67307337/219938184-e0c2d60d-891e-45fb-ae35-dfb0df98ecc4.png)
![p3](https://user-images.githubusercontent.com/67307337/219938201-f54a62cd-c9cd-417a-abf3-32f963906b8d.png)
![p4](https://user-images.githubusercontent.com/67307337/219938217-8a58aab1-0e5c-4a84-9e5b-4876d9303e94.png)

**期待改进**
我不清楚这是zotero本身的限制还是zotero-better-notes的问题，希望可以开放这个选项的模版，让用户自定义引注的格式。

**Comment by gmsft** [comment]
也很期待这个功能。因为笔记导出为pdf之后，只有作者的话，想不起来是哪个文献。
比如现在是下面这种格式：
<img width="528" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/6802304/8c5b88d8-bc95-4d3a-a3a1-d670435a4faf">

**Comment by windingwind** [comment]
由于：
1. 该功能已经于最新版本移除
2. Zotero笔记内的引注显示不受控制
此处关闭
