### ISSUE TITLE
笔记模板优化

### ISSUE THREAD

**Issue by lulunofish** [windingwind/zotero-better-notes#367]
我会为每个项目添加固定模板的子笔记，但是使用item类别的模板时每次都需要查找文献，非常不方便。能否在项目的右键菜单或通过快捷键等方式让item模板默认为当前项目添加子笔记呢？

**Comment by CaoKang-David** [comment]
同求。
我建议是在选定了条目的情况下，可以在哪个选项里面设置好要使用的模板，通过鼠标一键点击套用或者快捷键一键套用。
现在条目下新建笔记的方式有两个 通过+号展开二级菜单选择，也不太方便，能否像工具栏一样直接点选？

**Comment by EdwardGiao** [comment]
[Text]类型的模板是直接默认在当前文件笔记插入，但没法获取元数据

**Comment by windingwind** [comment]
Closed for #429
