### ISSUE TITLE
[Bug] Remove HTML tags from headings

### ISSUE THREAD

**Issue by LaraYang** [windingwind/zotero-better-notes#373]
Each note heading is labeled with its HTML tag in the form of a grey icon. See below for an example -- next to "Zotero Netter Notes USer Guide: Workflow", there's a little icon with H1 as the text. I see these icons in some of the pictures in the user guide and not in some others. I'd like to remove them. How do I go about doing so? 
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/4248102/221326392-5e9c70e9-e4c3-4305-92e5-9580b36d56be.png">

Thanks for your help!

**Comment by windingwind** [comment]
Hi,

This is a feature to indicate the level of the headings. Zotero Notes’ h3-h6 can be very similar and hard to distinguish. They are not part of your note and you won’t see them after export.

Currently there is no way to hide it.

**Comment by LaraYang** [comment]
Thanks for the quick response! This feature is a bit visually unsightly when quoted in main note (see attached; the icons are not treated as text and thus the vertical indentation line goes right through them). If it's ever possible, the ability to disable it would be much appreciated. Thanks. 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/4248102/221329174-60fc71af-2a36-44f3-88ba-a466d91326b2.png">

**Comment by windingwind** [comment]
I’ll fix this in the future.

**Comment by windingwind** [comment]
Closed for #429
