### ISSUE TITLE
[Note Template]QuickInsert#174Errot

### ISSUE THREAD

**Issue by GouPengyun** [windingwind/zotero-better-notes#374]
现在这个方法插入几次笔记之后主笔记的文档层次就会被搞乱。原本设置的一级标题会莫名其妙的被变成引用的内容，如图。
![1677398112230](https://user-images.githubusercontent.com/76691403/221398969-08c4a522-8a33-4217-ab16-15cf72ece216.png)

**Comment by windingwind** [comment]
Closed for #429
