### ISSUE TITLE
[Bug] Zotero better notes could not link one note to main note, confliction with Zotero Sytle add-on.

### ISSUE THREAD

**Issue by free521521521** [windingwind/zotero-better-notes#375]
**Describe the bug**
When click the better notes icon on the top center of one note. there is a link show up in this note, BUT nothing show up in the main note.
I try to disable all the add-ons but better notes, it works. finally I find out  there is a confilction with Zotero Style add-on.https://github.com/MuiseDestiny/zotero-style

**Screenshots**
I recorded:

https://user-images.githubusercontent.com/47398199/221495522-cf5dccf5-ffa6-4202-98dc-4e2b709fff0c.mov

I showed what happen when I link a note to the main note.

**Desktop (please complete the following information):**
 - MacOS 12.6
 - Zotero-better-notes 0.8.9
 - Zotero-style 2.2.6

**Comment by windingwind** [comment]
Closed for #429
