### ISSUE TITLE
[Bug]在笔记中键入lateX公式，非常容易导致zotero崩溃。

### ISSUE THREAD

**Issue by liushuishuiStudy** [windingwind/zotero-better-notes#379]
如题：在笔记中键入latex公式，非常容易导致zotero崩溃。

环境配置
version => 6.0.22, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.22, extensions => Zotero Style (2.0.7, extension), ZotFile (5.1.1, extension), Zotero Tag (0.3.0, extension), Jasminum (0.1.6, extension), Zotero Better Notes (0.7.28, extension), Zotero PDF Translate (0.8.28, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.22, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.22, extension)

**Comment by Eizenyz** [comment]
请问解决了吗，我现在也碰到这个问题，不知道该怎么办。

**Comment by pxf0429** [comment]
7.0.8-beta.2+237a2e5b8 (64-bit) 依旧有这个问题

**Comment by windingwind** [comment]
与插件无关，向zotero反馈

**Comment by GSJ-SD** [comment]
我在输入latex公式的时候也出现了这个问题，目前的发现是在$$中【手动输入】“{”与"}"时会出现Zotero的页面切换，其中"{"是打开/关闭左侧导航窗格，"}"是打开/关闭右侧导航窗格（默认笔记页面在右侧）；而复制"{"和"}"再粘贴就不会出现这个问题。

**Comment by windingwind** [comment]
@GSJ-SD 不要在无关且关闭的issue下回复
