### ISSUE TITLE
用zotero better notes写笔记时会突然变卡，甚至zotero软件闪退

### ISSUE THREAD

**Issue by Droptheblazo** [windingwind/zotero-better-notes#381]
最近用zotero（版本6.0.22）总是闪退，具体的场景为使用zotero better notes（版本号0.8.9）时发现写的东西稍微有点多时（其中加入了不少的截图），首先写东西会变得有点卡卡的，最上方的占空间后面的数字会乱跳，之后用markdown语言输入n级标题时（###+空格）会出现闪退的现象
zotero better notes用了zotcard模板，不过应该没什么影响吧
求大佬帮忙解决

**Comment by Droptheblazo** [comment]
> 我也会这样！大佬们看看这里555555555

摩西拉钩带明星

**Comment by Mercylago22** [comment]
没想到这里也有膜宝的粉丝 家人你的zotero还卡吗

**Comment by lil-i321** [comment]
我也会这样！

**Comment by windingwind** [comment]
Closed for #429

**Comment by Imgreenhand** [comment]
我也遇到过做笔记时闪退的情况，闪退一般都是在latex公式附近做修改的时候，还不知道是什么原因

**Comment by silvervinell** [comment]
我也是这样，不知道为什么，把自动同步时间改成十分钟一次都会卡。打开活动监视器一看，zotero占了快6G的内存。可是我只是开了一个文献，在写主笔记呜呜呜

**Comment by Svmeteor** [comment]
写latex公时会被卡闪退

**Comment by e-zz** [comment]
遇到类似问题。

## 环境
在仅启用 Better Notes 插件的情况下，问题依然存在。
> 平台：win10
> zotero： 6 
> 插件：0.7.28
> 输入法：微软拼音

## 描述
笔记中 latex 公式渲染后，紧接着只能输入英文字符。如果输入中文， 有时不出现输入框，如果继续尝试输入中文字符，会无响应，然后点击鼠标会立即闪退。

**Comment by yangv97** [comment]
> 遇到类似问题。
> 
> ## 环境
> 在仅启用 Better Notes 插件的情况下，问题依然存在。
> 
> > 平台：win10
> > zotero： 6
> > 插件：0.7.28
> > 输入法：微软拼音
> 
> ## 描述
> 笔记中 latex 公式渲染后，紧接着只能输入英文字符。如果输入中文， 有时不出现输入框，如果继续尝试输入中文字符，会无响应，然后点击鼠标会立即闪退。

同，请问解决了吗，我是win11下的zotero7也出现这种问题的
