### ISSUE TITLE
[Bug]主笔记中的表格功能是正常的，但是其他的所有笔记中表格无法正常使用

### ISSUE THREAD

**Issue by luohuaaa** [windingwind/zotero-better-notes#383]
**Describe the bug**
主笔记中的表格功能是正常的，但是其他的所有笔记中表格无法正常使用。可以插入表格，但是光标无法正常移动到表格内，导致无法输入。

**To Reproduce**
1.在除主笔记以外的任何笔记内右键-插入-表格
2.表格内光标无法正常移动，无法正常输入

**Expected behavior**
表格功能恢复正常

**Screenshots**

**Desktop (please complete the following information):**
win11 Version 22H2
zotero 6.0.22
zotero better notes 0.8.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yonglong2020** [comment]
举手！同样的问题

**Comment by Hyushuo** [comment]
同样的问题 +1

**Comment by windingwind** [comment]
Please comment here: https://forums.zotero.org/discussion/104653/bug-cannot-move-cursor-into-table-in-note-editor#latest

to let the Zotero team notice this bug.

**Comment by windingwind** [comment]
Confirm resolved in Zotero 7. Close here
