### ISSUE TITLE
[Bug]将笔记导出为markdown文件后，会出现“\"

### ISSUE THREAD

**Issue by luohuaaa** [windingwind/zotero-better-notes#388]
这是zotero笔记里的显示：
![image](https://user-images.githubusercontent.com/68732610/224208006-191bbc24-4eaf-4fef-9a78-a23c45455c8b.png)
zhe'shi这是导出为markdown文件后的显示：
![image](https://user-images.githubusercontent.com/68732610/224208093-e1ada134-c45d-4394-bd68-06366211e7dd.png)

**Comment by windingwind** [comment]
请看文档。不要在正文添加yaml header，有专门模板控制

**Comment by luohuaaa** [comment]
> 请看文档。不要在正文添加yaml header，有专门模板控制

模板太难了，看都看不懂，别说改了，跟看天书一样

**Comment by luohuaaa** [comment]
![image](https://user-images.githubusercontent.com/68732610/224250265-8367a29e-2a99-47cc-aeac-2a8cc73358ed.png)
请问我只是把原来的noteItem改成topItem，为什么无法导出呢？

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/blob/master/TemplateDoc.md#exportmdfileheader

这个模板中变量只有noteItem, 要获取父条目请noteItem.parentItem。请注意父条目不一定始终存在

**Comment by luohuaaa** [comment]
> https://github.com/windingwind/zotero-better-notes/blob/master/TemplateDoc.md#exportmdfileheader
> 
> 这个模板中变量只有noteItem, 要获取父条目请noteItem.parentItem。请注意父条目不一定始终存在

感谢解答，关于yalm header我现在还剩最后两个问题。请问作者名怎么改成yalm支持的格式呢？还有后面的那几行要怎么去掉呢
![image](https://user-images.githubusercontent.com/68732610/224314766-342db909-712d-48ea-bd19-7f9e328a3d2f.png)

**Comment by windingwind** [comment]
作者的信息需要看下条目数据。后面几行是同步用的，不能去除
