### ISSUE TITLE
[Bug]导出笔记时如果要修改保存名称，则必须手动在名称后加.md才可以保存为markdown文件

### ISSUE THREAD

**Issue by luohuaaa** [windingwind/zotero-better-notes#389]
直接修改名字，不加.md后缀：
![image](https://user-images.githubusercontent.com/68732610/224208415-c8aa29cb-41f9-427f-bfe2-0663f3da8be0.png)

![image](https://user-images.githubusercontent.com/68732610/224208506-dc3051d4-dde2-4ac3-8a3c-be3839497b31.png)
修改名字并加.md后缀：
![image](https://user-images.githubusercontent.com/68732610/224208597-3a74dc5a-ddc0-46f3-8c0a-d218eb4da2ff.png)
![image](https://user-images.githubusercontent.com/68732610/224208642-0985de38-ea92-422d-b189-dc859d108c17.png)

**Comment by windingwind** [comment]
这很正常，md文件的定义就是后缀是md的文件。不加后缀当然没有后缀了

**Comment by luohuaaa** [comment]
> 这很正常，md文件的定义就是后缀是md的文件。不加后缀当然没有后缀了

下面都已经定义保存类型了，为什么还要重复定义？

**Comment by windingwind** [comment]
Closed for #429
