### ISSUE TITLE
[Bug]ExportMDFileName模板失效，无论怎么修改，哪怕是改成乱码或者空白，默认保存名都是笔记第一行

### ISSUE THREAD

**Issue by luohuaaa** [windingwind/zotero-better-notes#390]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luohuaaa** [comment]
![image](https://user-images.githubusercontent.com/68732610/224316766-08646210-150d-4358-b67e-872d4c7d0f4b.png)

**Comment by luohuaaa** [comment]
模板已经反复修改保存，插件也禁用了又重新启用，都没有效果

**Comment by luohuaaa** [comment]
我按照之前您的回答中推荐的修改方式，来修改默认保存名为citekey，但是无法生效
![image](https://user-images.githubusercontent.com/68732610/224317255-f1890323-991c-44d0-96be-68df81bcbcc5.png)

**Comment by windingwind** [comment]
Closed for #429
