### ISSUE TITLE
[Bug]插入笔记模板后，开头总是会空两行

### ISSUE THREAD

**Issue by luohuaaa** [windingwind/zotero-better-notes#391]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luohuaaa** [comment]
![image](https://user-images.githubusercontent.com/68732610/224369357-dc5e75b0-dcf5-436a-aea2-7d33b170fbda.png)

**Comment by luohuaaa** [comment]
已经排除是模板代码的问题，因为即使模板里只有一个字母，插入后也还是会空两行

**Comment by zhcccy** [comment]
+1

**Comment by windingwind** [comment]
Closed for #429
