### ISSUE TITLE
[Feature] Two-way sync: support for markdown ToDo syntax "- [ ]"  AND add warning of possible data loss due to insertion of markdown tables

### ISSUE THREAD

**Issue by e-zz** [windingwind/zotero-better-notes#394]
The plugin has a very robust two-way sync mechanism. I notice it's even equipped with a diff tool for merging sync conflicts. Thanks for the amazing work.

But some markdown syntax is simply distored, and actually leads to problems in zotero. 

### Reproduce
For reproducing the bugs, I guess the text below might help. Please be sure to add these lines to the external md file instead of the original note item in zotero.
```markdown

This line and the checkbox below should disappear after syncing back to zotero
- [ ] checkbox_before_table

Here is the sample table that should cause data loss after being synced to zotero
ID | Name | Rank
-- | ---- | ----
1 | Tom Preston-Werner | Awesome
2 | Albert Einstein | Nearly as awesome

- [ ] checkbox_aftert_table
```
So the "bugs" here are
1. A checkbox `- [ ]` will be pruned to `- \n`, a bullet with linebreak
2. Markdown tables might cause data loss. Actually, all content in a note is removed after sync backwards from external md file. (But don't worry. I restored the lost data from obsidian)

If still not reproducible, please copy these lines into the external md file and try again. Also, please don't forget to PRESS the SYNC NOW BUTTON in the sync manager to make it work.

### Feature requested
I wouldn't ask for markdown tables in Zotero. I have seen other issues of markdown tables, so I understand the difficulty of supporting it in Zotero. But I still hope a better strategy for syncing checkboxes `- [ ]`. I believe this makes a lot of sense. With checkboxes, zotero notes can be more compatible with some GTD softwares, which is actually a very nice feature.

Anyway, since these bugs can always be avoided by a cautious user, I wouldn't say they are bugs. However, it might be a good idea to ask people explicitly to avoid these syntaxes. 

And thank the author again for the time and work spent on this wonderful add-on.

**Comment by windingwind** [comment]
The todo list is not supported in Zotero and the md table in the example does not follow the standard of markdown. We only support standard markdown syntax.

**Comment by e-zz** [comment]
I see, Thanks.
Hope this plugin will become more popular and get greater attention from Zotero community.

**Comment by 6-AND-9** [comment]
> The todo list is not supported in Zotero and the md table in the example does not follow the standard of markdown. We only support standard markdown syntax.

Checkboxes are part of the standard markdown syntax, as an extension: https://www.markdownguide.org/extended-syntax/

If you don't plan on implementing the extension, could we at least get an option to disable automatic re-formatting during sync?

**Comment by windingwind** [comment]
@6-AND-9 
You can modify the built-in template `Export MD File Content` to convert the parsed todo syntax during syncing.
