### ISSUE TITLE
[Note Template] 求助，在导出的笔记开头添加logseq风格的元数据

### ISSUE THREAD

**Issue by blackwint3r** [windingwind/zotero-better-notes#396]
也许算是Feature Request。

如题，我想要利用better-notes的同步功能，双向同步logseq中的md文件和zotero中的note。但是better notes导出的md中yaml格式元数据logseq无法识别。

想要通过更改导出模板实现该功能，折腾一整晚也没有成功。

logseq风格的元数据形如`key:: value`, 出现在md文件的首行，一个包含元数据的loqseq文件长得像下面这样：
```
alias:: TITLE
tags:: [[tag1]], [[tag2]]
item_link:: zotero://select/items/xxxxx
note_link:: zotero://note/u/xxxxx/
file:: file:///home/user/PDF_NAME.pdf

- 笔记的正文balabala。。。。

```

好像更改ExportMDFileHeader模板不行，因为logseq元数据根本不在md的frontmatter里。

如果退而求在其次，自己在note的首行 手动插入元数据，那么因为[Text模板无法获取任何variable](https://github.com/windingwind/zotero-better-notes/blob/master/TemplateDoc.md#text)，也无法实现。
只能用Item模版，但是这样每次都要在zotero中导航到相应的note或者item，麻烦了不少。

仔细看了模版开发文档，并没能找到解决方法，另外发现类似的问题在[这里](https://github.com/windingwind/zotero-better-notes/issues/309#issuecomment-1370728192)提到过。

**Comment by blackwint3r** [comment]
使用第三种用Item模板的方法，目前也遇到了很多问题。

例如，即使导出时不勾选yaml front matter，第一次导出没有yaml；但之后若在zotero中更改了note，同步的时候yaml又会冒出来，出现在md文件最开头。这导致即使在导出的md中手动添加logseq的元数据，也会被这些yaml破坏导致logseq无法识别元数据。

又比如，logseq（以及obsidian）的大纲模式是用短横线 `- `作为bullet，但是它们被同步到zotero中变成了`*`，再同步回logseq的时候`*`被当作普通的字符，格式就全乱了。

开始以为是很直接而且很容易实现的需求，但是实践中遇到好多问题，诚心求助😭

**Comment by windingwind** [comment]
很抱歉，目前只支持标准yaml格式头。近期在重构插件，暂时不能支持logseq格式头
