### ISSUE TITLE
能不能增加一个删除注释颜色的功能，原来导出为markdown都不会自带注释颜色的，现在我导出放到obsidian里一大片全是高亮太可怕了。

### ISSUE THREAD

**Issue by spritschelf** [windingwind/zotero-better-notes#399]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
在笔记工具栏中选择 隐藏注释颜色即可
