### ISSUE TITLE
Classified old notes cannot be updated in real time

### ISSUE THREAD

**Issue by fengyelai** [windingwind/zotero-better-notes#4]
After I have created a PDF note called"A", and have used k4z import into a collection of finishing notes. When I add / modify new notes in this PDF note "A", the collected sorting notes cannot be updated.

**Comment by windingwind** [comment]
Thanks for your suggestion.

This is difficult to realize, for the links inside the main note may be modified/deleted by the user. Force to overwrite the modified note title is rude.

Maybe a button to update the linked notes would be an acceptable solution.

**Comment by fengyelai** [comment]
Thank you for your reply
If there is a good solution, it will be a magic plug-in
In addition, after each click, the generated note link (like: Note link:“ zotero://note/u/7YRHTWDA/ ") can it not be displayed, because this part will be displayed when using other plug-ins. Of course k4z, it does not appear in the notes. Is there a solution or hiding it
thx

**Comment by virologist** [comment]
Hi, @fengyelai 

Thanks for your suggestions
You are right. k4z cannot be updated in the middle column of workplace when you modify its title. But it can be updated in the right column which has more details about the note. 
The pop-up note link guides the users to the right panel and then to the pdf when they click it. So, I think it is necessary unless we have other panel layout ideas. It's also a Zotero feature. I guess it may not be easy to hide it.

Best,
Yang

**Comment by windingwind** [comment]
@fengyelai v0.2.2 supports the link text update.
