### ISSUE TITLE
[Feature]能不能增加这么个功能，如下

### ISSUE THREAD

**Issue by EdwardGiao** [windingwind/zotero-better-notes#405]
功能需求：
点击“**添加笔记**”按键后在笔记里生成的文字只是加了引号其他格式跟笔记正文一样，这样在浏览笔记的时候就不太醒目，现在只能手动调整格式。
所以**能不能自动给这个链接到笔记里所生成的文字跟笔记正文不一样的格式**？比如默认为斜体或者字号再小一些？

**如图：**

![image](https://user-images.githubusercontent.com/92902985/227923056-25a1f17e-3247-45fa-9a09-d35575abe05e.png)

**Comment by windingwind** [comment]
1. 这是翻译插件的功能，与better notes无关
2. 不会实现
谢谢理解
