### ISSUE TITLE
[Bug]批量导出md文件时无法选择自动同步

### ISSUE THREAD

**Issue by lulunofish** [windingwind/zotero-better-notes#407]
为几篇文章都添加了子笔记，想批量导出时发现导出的md文件无法实现自动同步，只能每个子笔记手动导出（也尝试了全选2个条目后右键导出，导出的笔记还是未同步的选项）。在4.9 笔记同步/Sycn说明里看到的是“在库视图中，选择数个笔记条目，右键菜单栏点击“导出笔记及子笔记”，然后在“设为同步”时点击确认”，想问下有没有解决方法？
![GIF 2023-3-28 15-07-59](https://user-images.githubusercontent.com/102539985/228156215-94136c28-aa8f-4b8f-96b7-f8298dd9e454.gif)

**Comment by yuduchen-han** [comment]
我也遇到这个问题了，请问您解决了吗

**Comment by windingwind** [comment]
Closed for #429
