### ISSUE TITLE
[Bug]群组中PDF在主笔记中引用无法跳转到PDF

### ISSUE THREAD

**Issue by Linzezi** [windingwind/zotero-better-notes#408]
**Describe the bug**
![image](https://user-images.githubusercontent.com/129649018/229337914-d61c6005-fd65-4358-b6a8-e3e81681eb73.png)
点击在页面中显示但无法跳转到PDF，大部分群组文件中PDF的引用都会出现这个问题

**Comment by Linzezi** [comment]
求作者大大解答呜呜

**Comment by windingwind** [comment]
批注跳转是zotero的功能，应该和插件没有关系。请看下非主笔记正常吗？跳转目标的pdf是否已经在本地下载了，是否可以从库中正常打开。如果还有问题，可以向zotero论坛反馈

**Comment by Linzezi** [comment]
> 批注跳转是zotero的功能，应该和插件没有关系。请看下非主笔记正常吗？跳转目标的pdf是否已经在本地下载了，是否可以从库中正常打开。如果还有问题，可以向zotero论坛反馈

非主笔记也不行，跳转的PDF都已在本地下载，可以正常打开。已向Zotero论坛反馈，谢谢哥
