### ISSUE TITLE
[Note Template]导出markdown文档，怎么更改图片的样式模板

### ISSUE THREAD

**Issue by weanqin** [windingwind/zotero-better-notes#409]
导出为markdown之后，图片的格式为下图：
![image](https://user-images.githubusercontent.com/75720444/229372318-5418d71e-eb4f-461b-8a58-a9daffea0c02.png)
怎么才能更改导出后方括号中的格式呢？

**Comment by windingwind** [comment]
仅支持标准markdown语法
