### ISSUE TITLE
[Bug]"insert citation" 功能无法使用

### ISSUE THREAD

**Issue by Allen-Wang1997** [windingwind/zotero-better-notes#412]
我按照用户手册上对导出格式做了设置：
![image](https://user-images.githubusercontent.com/53132988/229802313-fbe867e2-759c-4c6f-be6f-4d8eb9a767b5.png)

笔记中点击 “ 按钮，会弹出选择条目的对话框：（如果能直接自动插入父条目文献就更好了）
![image](https://user-images.githubusercontent.com/53132988/229804228-56a99548-5795-4f7e-adb1-63059d798e22.png)

但选择条目后，并 OK 后，笔记页面并没有插入引用，也没有任何改动或反应。

**Comment by windingwind** [comment]
该功能已移除
