### ISSUE TITLE
[Feature] Toggle for "Note Saved" Pop-up Notifications

### ISSUE THREAD

**Issue by citadel-lewis** [windingwind/zotero-better-notes#415]
**Is your feature request related to a problem? Please describe.**
In my main workspace note I have quite a few double-stranded child notes synced to filesystem (Obsidian vault). When adding content to these child notes I usually have them opened in the right-hand notes pane. But then when I'm editing the child note there is a pop-up notification from Better Notes stating that the note has been saved to the filesystem - it does this with every keystroke. It often blocks the view of the text I am adding.

**Describe the solution you'd like**
An option to disable these notifications - perhaps only generate a notification if there has been a problem saving the note.

**Describe alternatives you've considered**
I can open the note in a separate window but that is not ideal

**Additional context**
![image](https://user-images.githubusercontent.com/65517233/230548732-1d5c5174-5430-428c-a4f0-68cb791783bc.png)

**Comment by windingwind** [comment]
Closed for #429
