### ISSUE TITLE
如何更改跳转显示标注高亮的颜色

### ISSUE THREAD

**Issue by Elodie-0117** [windingwind/zotero-better-notes#422]
![image](https://user-images.githubusercontent.com/126692797/231164898-ed62ef27-74b1-4ce7-931a-56c09dff66a6.png)
这个深蓝色有点太深了，已经看不见文字了。
记得之前好像有看到哪里可以设置这个高亮颜色2秒消失的，找不到那个帖子了

**Comment by Elodie-0117** [comment]
> ![image](https://user-images.githubusercontent.com/126692797/231164898-ed62ef27-74b1-4ce7-931a-56c09dff66a6.png) 这个深蓝色有点太深了，已经看不见文字了。 记得之前好像有看到哪里可以设置这个高亮颜色2秒消失的，找不到那个帖子了

补充：刚跳转过来的时候，深蓝色会自动消失，但点击放大或缩小页面后，深蓝色又立马跳出来了

**Comment by windingwind** [comment]
非插件功能，请向社区反馈。

**Comment by Elodie-0117** [comment]
> 非插件功能，请向社区反馈。
好的
