### ISSUE TITLE
[Feature] UI design request for minimality on macOS 

### ISSUE THREAD

**Issue by mnkhprre** [windingwind/zotero-better-notes#423]
<img width="711" alt="Ekran Resmi 2023-04-11 19 57 49" src="https://user-images.githubusercontent.com/54448793/231236282-35fb915f-52d1-4692-911a-8efe409ec671.png">

Can the layout be more compact like in the screenshot? 

**Describe alternatives you've considered**
The export button should be in a three-dot icon.

**Comment by windingwind** [comment]
Thanks for the suggestion. It is designed so to make people notice one of the core feature (linking notes). I am afraid such a big change in UI will make some users confused.

Would it be OK if I add an option to make the top line of tool bar hover to show?
