### ISSUE TITLE
[Bug]较大容量笔记导致崩溃

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-better-notes#427]
大家有没有这种现象呢？只要笔记稍微大一些（如：14k，3400字），0.8.9就会崩溃，
初步认为只和笔记字数有关。

**Comment by windingwind** [comment]
请尝试最新1.0.0版本

**Comment by lil-i321** [comment]
> 请尝试最新1.0.0版本
1.0.0-3：不能同步，

![Snipaste_2023-04-15_15-49-25](https://user-images.githubusercontent.com/57334649/232197261-9fe1052f-d643-4b40-a41a-3bcc59b9282e.png)

**Comment by lil-i321** [comment]
且不能生成md文件。
