### ISSUE TITLE
可以让导出的word文档中带有可编辑的参考文献链接吗？[Feature]

### ISSUE THREAD

**Issue by wu7chao** [windingwind/zotero-better-notes#428]
**Is your feature request related to a problem? Please describe.**
我在写综述，如果笔记导出到word中的文字，能够保存我引用的参考文献，并且导入后还能修改参考文献的格式，就好了。请问怎么样让导出的word文档中带有可编辑的参考文献链接？

**Comment by windingwind** [comment]
暂无法实现

**Comment by windingwind** [comment]
已支持，#822
