### ISSUE TITLE
[Feature]关于笔记引用能否增加引用光标所在段落到主笔记

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#431]
目前引入主笔记只能是整个笔记引用，能否实现引用光标所在段落、或者鼠标选中段落？

此外，左侧的标志点击zbn的icon是生成一个新的子笔记，能否添加到当前笔记的光标所在位置。
谢谢

**Comment by Reichenbar** [comment]
在zbn的icon旁边有竖着排列的三个点的icon，点击里面的 *Add to Note* 就可以把这段注释添加到当前笔记。此外，选中文章中的一段话，也可以直接点击 *Add to Note* 添加到当前笔记，而无需生成注释。

**Comment by windingwind** [comment]
1. 未实现。笔记链接设计的思路是整个笔记为一个整体，每个子笔记单独放置一个内容，不要把子笔记变得太长。
2. 生成子笔记以后通过上方花形图标创建双链

**Comment by RTcui** [comment]
> 目前引入主笔记只能是整个笔记引用，能否实现引用光标所在段落、或者鼠标选中段落？

这个可以代替上述需求吗  https://github.com/windingwind/zotero-better-notes/issues/133#issuecomment-1236055947

或者这个需求是否可以，生成一个新笔记后再引用 https://github.com/windingwind/zotero-better-notes/issues/284
