### ISSUE TITLE
[Bug]笔记无法正确定位，含有两个PDF文档的注释

### ISSUE THREAD

**Issue by tbs575** [windingwind/zotero-better-notes#432]
如图，有两个PDF文档，两个PDF文档都有注释。单独做一个笔记，笔记内容将连接到两个不同PDF时，预览看到结果并不正确
![image](https://user-images.githubusercontent.com/30616402/232718671-48b62431-a216-43b7-884d-a043e2e779d0.png)

如下图，两个红色框来自两个PDF文档的注释，但点击预览后，看到都是同样的内容（同一PDF）
![image](https://user-images.githubusercontent.com/30616402/232719180-7524501e-d2e4-45c8-acee-2b34835ae782.png)

不知道是不是Bug？谢谢

**Comment by windingwind** [comment]
无法判断属于哪一个pdf。打开条目下的最匹配pdf。
