### ISSUE TITLE
同步的时候提示这个

### ISSUE THREAD

**Issue by jinshengcui** [windingwind/zotero-better-notes#434]
![image](https://user-images.githubusercontent.com/33824346/233763764-f70a4e34-a62a-467b-89b5-b84bd0d97fdb.png)
目前笔记字数5万多了，然后新增笔记内容到主笔记的时候就会非常卡，同步也实现不了。甚至zotero直接卡到无法响应。已经排除其他插件冲突问题了，是不是这个插件本身就有字数限制呢？

**Comment by windingwind** [comment]
Zotero对笔记长度有限制，出于同步或性能考虑。建议使用笔记链接的方式归纳。
