### ISSUE TITLE
[Bug]通过标签添加双链，无法添加到相应标题下，都是在笔记末尾

### ISSUE THREAD

**Issue by yi879041671** [windingwind/zotero-better-notes#441]
通过标签添加双链，#标签后，无法添加到相应标题下，都是在光标处或者笔记末尾。
能否加回这个共呢个，同时不加#的标签直接添加到相同标签标题后。

**Comment by windingwind** [comment]
新版本改为`@`开头（标题）或`@@`（末尾）。此处关闭
