### ISSUE TITLE
在本地笔记删除后，同步自动删除，两边软件内的明明都删除了，当再打开软件，发现笔记又回来了，只能再打开取消同步，才会彻底删除

### ISSUE THREAD

**Issue by cjh995** [windingwind/zotero-better-notes#443]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cjh995** [comment]
如题

**Comment by windingwind** [comment]
或许在某一侧删除而另一侧未删除时，后台发生了同步，或从zotero服务器产生了同步。先取消同步再删除是正确的操作
