### ISSUE TITLE
[Note Template] 您好，我想问一下，怎么给这个笔记自动添加一个标签呢，我感觉可以，但是我不会

### ISSUE THREAD

**Issue by cjh995** [windingwind/zotero-better-notes#446]
![image](https://user-images.githubusercontent.com/131834632/236158024-4b028177-67b4-4162-88b4-9601439c8843.png)

**Comment by cjh995** [comment]
就是，我导出去后，可以通过标签查找到这些导出的，本来是再这个笔记最后手动加标签的，无意间点开这个导出的，看了看，我感觉应该是可以自动加标签的，对吧

**Comment by cjh995** [comment]
您好，我这个，还是不懂的，麻烦您告知一下，需要把noteItem.addTag("tag1"); noteItem.saveTx() 代码加到什么位置，我不知道加到那，我就加到了这里
![image](https://user-images.githubusercontent.com/131834632/236361994-3c3b5652-d127-4b81-ae5d-3fd11ac68e1d.png)
结果导出的，结果是这样的
![image](https://user-images.githubusercontent.com/131834632/236362034-af765e75-0153-487e-81f3-a5761671d8ee.png)
预期想的 "tag1" 没出现，值出现个 tags: true 。所以想请教一下是加到哪里，或者需要修改哪里，麻烦您了

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/236373078-5d0bdd83-2d1e-4f97-91e9-5e30887765bf.png)

**Comment by cjh995** [comment]
感谢大佬，以解决，感谢感谢，
