### ISSUE TITLE
为啥插件使用说明跟下载的不一致呀，是还没更新版本嘛

### ISSUE THREAD

**Issue by Tangjhno1** [windingwind/zotero-better-notes#452]
1

**Comment by Reichenbar** [comment]
我也发现了这个问题。感觉应该是插件版本更新了，但是使用说明没有及时更新。这个 [Quick Start](https://github.com/windingwind/zotero-better-notes#-quick-start) 应该是最新的。

**Comment by windingwind** [comment]
yes
