### ISSUE TITLE
取消自动弹出欢迎界面

### ISSUE THREAD

**Issue by m3lab-zzl** [windingwind/zotero-better-notes#455]
现在每次打开ZOTERO，都会弹出better-notes的欢迎界面，只能手动关闭。

是否能提供一个类似于（取消开机自启动）的选项，使得打开zotero不会再弹出这个一闪一闪的 better-notes 的欢迎界面？
![image](https://github.com/windingwind/zotero-better-notes/assets/102862066/e6d40792-1917-4618-b22d-830bcaca911b)

**Comment by windingwind** [comment]
更新版本
