### ISSUE TITLE
[Feature]markdown导出时能否增加选项关闭白底黑字的文字格式转换

### ISSUE THREAD

**Issue by bugsbunny8** [windingwind/zotero-better-notes#458]
当前Zotero-better-notes版本为1.0.1， Zotero为6.0.26

note中间的内容为
```
* XXXXX
```
导出的markdown文件中转化为
```
*   <span style="color: rgb(33, 37, 41)"><span style="background-color: rgb(255, 255, 255)">XXXXX</span></span>
```
![image](https://github.com/windingwind/zotero-better-notes/assets/408559/1642138e-6ba0-4a42-8c9f-7d3a1f9224fe)

建议在markdown导出时增加一个简化模式选项，不使用style来导出文字的信息格式，直接导出对应的文字信息。
即导出markdown内容也为：
```
* XXXXX
```
![image](https://github.com/windingwind/zotero-better-notes/assets/408559/6a35349a-ace6-4dde-a171-1b9204fe7acc)

zotero-better-note中为白底黑字，或者建议在导出时直接去除该格式信息，否则在其他编辑器的深色模式中看起来不是太好

**Comment by windingwind** [comment]
与用户设置的笔记格式有关。如果创建的注释本身带有颜色，则尊重原始数据。
导出设置**不对任何格式进行修改**，以保证同步的可靠性。
