### ISSUE TITLE
导出笔记的特殊字符问题【已解决】

### ISSUE THREAD

**Issue by appw-cn** [windingwind/zotero-better-notes#46]
在导出笔记时，”###“会变成”\\###“，”>“会变成”\\>“。让原本写得好好的markdown笔记，原本的标记都没有了。
请问”自动加\“这个功能可以手动关闭吗？在哪里关闭呢？通过高级设置里的设置编辑器可以吗？谢谢大佬

**Comment by windingwind** [comment]
笔记中的不同标题层级会自动在导出时变成markdown的标题格式，写作时在数个#后按一次空格就会自动变成对应标题。不需要额外打#字符，因此也不会存在被转换的问题

**Comment by windingwind** [comment]
@appw-cn 
设置模板为：
<p><h3>{{comment}}</h3><br>>{{highlight quotes='false'}}</p>
能够达到你需要的效果

**Comment by windingwind** [comment]
在zotero，以及任何标准的富文本编辑器中，使用html标签是标准的做法，而markdown语法不是。zotero笔记针对markdown语法做了一些适应，但看起来不针对模板

**Comment by appw-cn** [comment]
> 在zotero，以及任何标准的富文本编辑器中，使用html标签是标准的做法，而markdown语法不是。zotero笔记针对markdown语法做了一些适应，但看起来不针对模板

大佬威武，找到原因了。非常感谢~ have a nice day
