### ISSUE TITLE
帮助菜单栏中，无任何关于better notes的选项。

### ISSUE THREAD

**Issue by moxi000** [windingwind/zotero-better-notes#461]
如题，在菜单栏的帮助选项中没有关于better notes的任何设置，mac与win都这样，导致一部分功能无法使用。公式ocr服务设置在最新版mac和win都看不到，并且新手指引这一项也没有。使用的软件版本和插件版本均是最新版
<img width="760" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/66484370/21097bd7-d825-4f18-8454-cda538a50629">

**Comment by moxi000** [comment]
经过测试，发现最新的几个版本没有了工作区的菜单栏，但退回到0.7x的版本是有菜单栏的

**Comment by moxi000** [comment]
详细测试后发现，自1.0版本开始后，工作区菜单栏消失，且大纲异常。

**Comment by windingwind** [comment]
最新版本对功能进行精简，因为我一个人无力维护更多功能。使用手册部份内容可能过时，谢谢理解。
以上都不是bug，是设计如此。

**Comment by nhan000** [comment]
So you removed the OCR LaTeX feature? That's a bummer. It's really handy when I need it. I used it a few months ago and was surprised that I couldn't find it anymore.

Anyway, you can consider removing the feature from the manual. Appreciate it! https://github.com/windingwind/zotero-better-notes/wiki/4.5-Formula-Support-Math-Support.en

**Comment by windingwind** [comment]
Will be back soon. I am really busy and can’t get everything ready before Zotero 7 beta is released, so I just left these minor features behind and released a stable Z7 version without them.
