### ISSUE TITLE
[Bug] auto-insert annotation setting disappeared

### ISSUE THREAD

**Issue by BeyondIM** [windingwind/zotero-better-notes#463]
When I upgraded from 0.89 to 1.01, the auto-insert annotation setting disappeared. How can I enable auto-insert annotation now? tks.

**Comment by windingwind** [comment]
Sorry some features are not supported yet. There’s a big change in the 1.x version and the plugin is fully refactored.

I don’t have much time recently. If you have interest, PR is always welcomed.

**Comment by BeyondIM** [comment]
Thank you for your work, best regards.
