### ISSUE TITLE
子笔记的大纲

### ISSUE THREAD

**Issue by VickyLin7958** [windingwind/zotero-better-notes#464]
您好，

我是zotero better notes的mac版本新用户。首先想请教一下：主笔记是只有一个吗？我电脑上版本好像称呼不是许多教程里显示的main note而是workspace note, 然后只能选中一条笔记set as workspace note.

如果是的话，请问可否实现子笔记内也有自己的根据标题层级生成的大纲？很喜欢主笔记的大纲功能，平时复习/使用子笔记里关于某篇文献内容的时候也希望可以有一个大纲很明确的看到这篇笔记的结构，并且跳转。（因为子笔记有时候也会很长，划上划下的感觉没有那么清晰的能感受到这篇笔记的结构脉络。

感谢阅读。

**Comment by Reichenbar** [comment]
教程里说同一时间，只能有一个主笔记。个人感觉，如果想在复习子笔记时查看大纲，完全可以把子笔记设置为主笔记来查看啊。

**Comment by windingwind** [comment]
是的。

**Comment by VickyLin7958** [comment]
> 教程里说同一时间，只能有一个主笔记。个人感觉，如果想在复习子笔记时查看大纲，完全可以把子笔记设置为主笔记来查看啊。

意思是每一次复习子笔记的时候都设置为主笔记吗？但是有时候复习的时候，不止要复习一个子笔记 可能需要同时复习很多篇呢？而且个人感觉每次都要手动换成主笔记，不复习的时候再换回来，很麻烦诶。

**Comment by Reichenbar** [comment]
是啊，目前这个插件应该是只允许查看主笔记的大纲。那要同时复习很多篇子笔记，估计就实现不了了。
