### ISSUE TITLE
[Feature] Automatically generated tags using Quick Note from Annotation

### ISSUE THREAD

**Issue by Reichenbar** [windingwind/zotero-better-notes#465]
**Is your feature request related to a problem? Please describe.**
When I use *Quick Note from Annotation*, it will automatically generate a tag (by default, zotero://note/u/*). I know it indicates the note link. But if I create many notes this way, this operation will cause many meaningless tags, making tag management difficult.

Automatically generated tags:
![note tags](https://github.com/windingwind/zotero-better-notes/assets/72991945/c0711cd2-1b27-4f99-923a-5093096ada6e)

Automatically generated tags in Zotero main interface:
![tags in main interface](https://github.com/windingwind/zotero-better-notes/assets/72991945/de62fcfe-6666-4b60-87d8-3f3eeb3cf200)

**Describe the solution you'd like**
In my view, the automatically generated tags indicating the note link are unnecessary since they cannot help us manage notes better and make tags a mess. So can you please remove these automatically generated tags for the operation *Quick Note from Annotation*? Or if you think these tags are really helpful, maybe you can put them in the comments of annotations, instead of tags.

**Comment by windingwind** [comment]
They used to be in the note comment, but users think they are disturbing, so I moved them to tags. The link is designed to prevent creating duplicate notes.

The default tag manager is not that convenient. You could refer to zotero-style plugin for a more accurate and direct tag system. It only takes tags start with `#` into consideration.
