### ISSUE TITLE
[Feature] No note template to choose

### ISSUE THREAD

**Issue by Reichenbar** [windingwind/zotero-better-notes#466]
**Is your feature request related to a problem? Please describe.**
When I want to use note templates either through *Edit -> Insert Template to Workspace Note* or *New Item Note from Template*, I cannot choose templates. Can you please figure out why this happens and how to solve it? Thanks a lot!

<img width="664" alt="templates" src="https://github.com/windingwind/zotero-better-notes/assets/72991945/3cd40722-1c77-4077-9a3b-0fd14a46f340">

**Comment by windingwind** [comment]
You could add new templates via menu Edit-Note Template Editor.
