### ISSUE TITLE
[Bug] 笔记工作区的侧栏（笔记窗口和预览窗口）重复，且无法永久关闭

### ISSUE THREAD

**Issue by rucnyz** [windingwind/zotero-better-notes#467]
假设某个论文存在条目笔记，那么当我们在做笔记的时候自然就会在论文界面打开笔记窗口，即下图的情况。
<img width="1095" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/62874089/d038bb34-6113-44e2-9a1c-b7d002e8f665">

那么此时转换到笔记工作区后，工作区也会自动打开笔记窗口。而如果我们再点击链接打开预览窗口时，便可以发现笔记窗口和预览窗口都打开了，而且是重复的

<img width="1038" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/62874089/b93114a5-23e4-4a66-9afe-0992dd19f5cb">

有没有办法可以让笔记工作区在任何情况下都不自动打开笔记窗口呢，无论是初始点击还是从其他的论文页面跳转过来？

**Comment by windingwind** [comment]
不是重复。最右侧是pdf阅读器的笔记边栏，是新增的功能，和预览栏不是一个东西。要切换多个视图，鼠标移到工作区标签上，点击视图切换按钮即可

**Comment by rucnyz** [comment]
抱歉我的意思可能没有表述清楚，我知道那个可以被关掉，但是我无法让笔记工作区在开启时默认不开这个东西，不然每次切换过去都需要费一道力先关掉他
