### ISSUE TITLE
[Feature] 如何为笔记中的标题添加数字序号

### ISSUE THREAD

**Issue by Reichenbar** [windingwind/zotero-better-notes#469]
笔记中的标题默认都是无序号的，为了便于阅读，请问怎么为其添加数字序号呢（如下图所示）？我知道可以手动为每个标题添加数字序号，但是感觉这种方法不是很便捷。有没有自动为标题添加数字序号的操作呢？感谢回复！

![number heading](https://github.com/windingwind/zotero-better-notes/assets/72991945/e5f8c84f-a8a7-4250-84f4-d86ad32442ba)

**Comment by windingwind** [comment]
手动添加即可哦

**Comment by 11good11** [comment]
我也很希望能够有自动添加标题序号的功能，真的会非常方便的
