### ISSUE TITLE
mac版的zotero功能缺失[Bug]

### ISSUE THREAD

**Issue by ZoyDo** [windingwind/zotero-better-notes#470]
**Describe the bug**
在mac版的zotero中，很多文档中的介绍的功能都没有。例如安装重启没有开始引导，主菜单的帮助菜单里也没有better note的功能选项

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version 13.2.1

**Comment by windingwind** [comment]
为了适配zotero7，在最新版本进行了插件的完全重写。部分小功能由于我个人没有精力维护，目前还没有实现，并可能未来也不考虑实现。过多的细小功能导致插件维护非常困难，望理解。
用户指引等功能移除了。不再需要
