### ISSUE TITLE
[Feature] 使用过程中新创建”#“格式的标签，是否有办法直接推送到主笔记中，进而整理相关tag，而不必进入主笔记手动输入

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#472]
能否增添一个机制来快速把特定tag推送到主笔记中的heading，比如利用template等？最好可以用快捷键等比较便捷的方式

另外，如果#类标签早已创建，但并未在主笔记中设置相关标题，后边又决定把相关标签在主笔记中进行统计，此时，之前创建的那些具有该标签的note是否能被捕捉到？ 

如果不能，也许应该为主笔记设置一个统计与他关联的item的数组，然后给予一个类似刷那样的按钮，让他去捕捉相关文档里已存在的需要自动捕获的标注，然后把他们都抓取进来

另外，对于这些抓取的任务，建议提供一个排序功能，应用到整个note或特定子标题，按插入时间、年份、作者等去重新排序，类似obsidian里dataview的那种感觉

**Comment by windingwind** [comment]
通过#开头标签直接加入工作区笔记的功能在1.0以前实现了，之后可能有时间我会迁移到现在版本上

如果要收集现有的某类标签，可通过笔记模板功能。

对于dataview类的功能，由于我个人精力问题，不考虑在这个插件中实现。

**Comment by JinchaoC** [comment]
> 通过#开头标签直接加入工作区笔记的功能在1.0以前实现了，之后可能有时间我会迁移到现在版本上
> 
> 如果要收集现有的某类标签，可通过笔记模板功能。
> 
> 对于dataview类的功能，由于我个人精力问题，不考虑在这个插件中实现。

请问是1.0前的版本都支持通过标签"#+heading"的形式链接note和annotation吗?

**Comment by windingwind** [comment]
Unfortunately, this feature will not be added to this plugin. You may want to create a new plugin to achieve this. Thank you for your understanding.
