### ISSUE TITLE
[寻求帮助]无法正常使用该插件

### ISSUE THREAD

**Issue by shao12781566** [windingwind/zotero-better-notes#473]
在插入该插件后，无法如同以往第一次使用该插件时一样弹出使用帮助文档并打开工作台
主动打开后先后弹出两个javacript弹窗为“工作区笔记未设置。创建一个吗？”“请选择一个有效的分类”，
修改模板时所有模板统一显示为“无法预览”且无法使用

**Comment by windingwind** [comment]
以上均是正常。新版本移除了设置向导（因为简化并分散提示到了各个功能）。
新建工作区笔记的提示出现是因为你当前没有设置工作区笔记。点是会指引你创建，点否可以自己创建。

**Comment by shao12781566** [comment]
收到，问题已解决，谢谢！
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月20日 23:38
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [windingwind/zotero-better-notes] [寻求帮助]无法正常使用该插件 (Issue #473)
        
      
    
  

以上均是正常。新版本移除了设置向导（因为简化并分散提示到了各个功能）。
新建工作区笔记的提示出现是因为你当前没有设置工作区笔记。点是会指引你创建，点否可以自己创建。

**Comment by soarinskygg** [comment]
为什么我，点击ok之后又提示我 没有分类，依旧无法设置创建工作区？
