### ISSUE TITLE
[Bug] 大部分模板无法使用，如prompt not defined, 以及 topItem not defined等问题

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#476]
用的最新版本插件，以及zotero 6.0.27-beta。 

目前就[Text] create table 可以使用

**Comment by mayuxi987** [comment]
我也用到了类似的error.  Topitem not defined.

**Comment by windingwind** [comment]
1.0.0版本全面调整了插件的模板API，原本使用内部API的模板将无法使用。之后会逐渐完善新的笔记模板文档

**Comment by CopleManba** [comment]
所以应该怎么解决呢？

**Comment by ghweili** [comment]
是否可考虑同时保留两种方案？对于1.00版本之前的，似乎zotcard生成的模板也可以用，这样的话对于不熟悉相关语言的建立和修改模板更容易

**Comment by keji1115** [comment]
Template [Text]SCI笔记 Error: ReferenceError: title is not defined，把[Text]改成[Item]也不行
请问为什么还是会出现这个标题

**Comment by CopleManba** [comment]
版本问题，我现在用回旧版本就可以

**Comment by windingwind** [comment]
已更新笔记模板文档，并添加了对item模板除editor变量以外的所有预定义变量。
prompt not defined是因为代码环境变化，`prompt` => `Zotero.getMainWindow().prompt`.
非bug，此处关闭
