### ISSUE TITLE
[Bug]打开Zotero阅读器后条目元数据页面显示不正常，必须切换到其他页面后才能正常显示

### ISSUE THREAD

**Issue by HPDell** [windingwind/zotero-better-notes#477]
**Describe the bug**
在数据库中打开一个文献的pdf附件进行阅读后，原本界面右边显示条目元数据、笔记、相关文献等的界面无法正常显示，情况如下

![image](https://github.com/windingwind/zotero-better-notes/assets/17842185/15656c58-e1de-4da0-846d-3b622ec50641)

只有当切换到别的标签页（数据库或者工作区）之后，再切换回该阅读窗口，才能正常显示

![image](https://github.com/windingwind/zotero-better-notes/assets/17842185/acb43a1e-ec0f-435a-809b-01d0e60c93d3)

经测试，不是 Zotero-reference 插件导致的问题。

**To Reproduce**
1. Go to the reading view by double clicking a paper. 
2. Click on the meta view by clicking the button <img width="40" alt="image" src="https://github.com/windingwind/Zotero-better-notes/assets/17842185/6fd5211f-168a-4b89-bd7c-7af20d548b51">
3. See error

**Expected behavior**
Meta data (Info, tags, related) should have been shown on the panel.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.0

**Comment by Loticyang** [comment]
同样遇到这个问题
