### ISSUE TITLE
Betternotes 可以加入撤销功能。如果有误操作，可以返回。[Feature]

### ISSUE THREAD

**Issue by NUOLA-NUO** [windingwind/zotero-better-notes#479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NUOLA-NUO** [comment]
有时候会误操作。是否可以加入撤销功能。

**Comment by windingwind** [comment]
Ctrl z 或菜单栏 编辑 撤销
