### ISSUE TITLE
[Bug]工作区笔记中的笔记无法链接PDF

### ISSUE THREAD

**Issue by suejun0730** [windingwind/zotero-better-notes#489]
不能直接通过笔记跳转至文章，最顶层上找不到PDF链接按钮了。
（使用系统：MacOS）
现在：
<img width="968" alt="截屏2023-05-29 23 15 48" src="https://github.com/windingwind/zotero-better-notes/assets/134952268/e03024c2-da19-453a-b7a3-723ed5546fd7">

之前：
<img width="873" alt="截屏2023-05-29 23 19 14" src="https://github.com/windingwind/zotero-better-notes/assets/134952268/afcd0db1-074f-4bff-bcb4-7cb9ffde28a0">

**Comment by windingwind** [comment]
右侧齿轮-打开附件

**Comment by suejun0730** [comment]
> 右齿轮-打开附件

谢谢您的回复，想追问一下是否是因为版本更新，因此不再有PDF链接图标了呢？
