### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by yigaohanxi** [windingwind/zotero-better-notes#490]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yigaohanxi** [comment]
工作区笔记，添加链接功能不可用

**Comment by windingwind** [comment]
1. 工作区笔记无法添加链接到它本身
2. 标签笔记功能暂时移除。我没有更多精力维护所有功能
