### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sjads** [windingwind/zotero-better-notes#492]
你好，大佬，我升级最新版本以后，发现有一个bug，就是我在阅读文献的时候侧边工具栏消失了
![image](https://github.com/windingwind/zotero-better-notes/assets/96932407/7d5cb3ea-3b9c-435d-98c1-fe452d38de89)，
如果我将zotero-better-notes插件卸载或者禁止，这个时候侧边工具栏会出现
![image](https://github.com/windingwind/zotero-better-notes/assets/96932407/8c3b6366-83b1-4cfb-ae46-a103ca6e498d)

不知道为啥，是跟zotero-pdf-translate插件冲突了吗

**Comment by windingwind** [comment]
请提供具体zotero版本，与插件版本哦

**Comment by sjads** [comment]
您好，大佬，我的·zotero-better-notes插件是1.0.2zotero软件版本是6.0.26
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/1/2023 21:50
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [windingwind/zotero-better-notes] [Bug] (Issue #492)
        
      
    
  

请提供具体zotero版本，与插件版本哦

**Comment by windingwind** [comment]
由于zotero6版本插件已经不再维护，仅维护zotero7版本插件，此处关闭
