### ISSUE TITLE
笔记超链接问题[Bug]

### ISSUE THREAD

**Issue by hyhshgk2** [windingwind/zotero-better-notes#493]
以往笔记可以复制某一行的链接，现在右键菜单没有了，也找不到其他地方

![image](https://github.com/windingwind/zotero-better-notes/assets/127581333/f661d8a4-d3ce-4fa9-a922-dc9234e26c28)

**Comment by windingwind** [comment]
编辑器右上角-齿轮-复制笔记链接，会复制带有光标行号的链接。所有操作都尽可能移到同一个入口了

**Comment by hyhshgk2** [comment]
> 

谢谢，但不知道哪里设置不对，无论光标在哪行，复制的都只有第一行
![image](https://github.com/windingwind/zotero-better-notes/assets/127581333/51da5e37-44a2-49b0-95ef-591e43513994)
