### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by ashed** [windingwind/zotero-better-notes#495]
**Is your feature request related to a problem? Please describe.**
Your extension need more locales.

**Describe the solution you'd like**
I translate addon.properties and overlay.dtd to Russian

**Describe alternatives you've considered**
No alternative solutions, just i18n

**Additional context**
[zotero-BetterNotes-ru-RU.zip](https://github.com/windingwind/zotero-better-notes/files/11624168/zotero-BetterNotes-ru-RU.zip)

Add please ru-RU locale to your extension

**Comment by windingwind** [comment]
Thanks!

If you are familiar with git, you may directly create a pull request and I will simply merge it. Otherwise, as I'm traveling these days, you may have to wait for another week before we could get the localized version merged and released.

**Comment by ashed** [comment]
fixed i18n, updated to v1.0.4

[zotero-BetterNotes-ru-RU-1.0.4.zip](https://github.com/windingwind/zotero-better-notes/files/11990584/zotero-BetterNotes-ru-RU-1.0.4.zip)
Add it, please.

And BTW after Zotero extension updating I'll see nothing changes.
Maybe i18n have wrong integration with main code?

**Comment by windingwind** [comment]
Sorry but we have give up the dtd and properties i18n system, because the platform is turning to Fluent. See the latest version of the main branch.

And if possible, committing changes via pull request would be more friendly to both users, maintainer(me), and contributors(you). Everyone, including other Russian speakers, will be able to review these changes before being merged.

**Comment by windingwind** [comment]
See the latest code here: https://github.com/windingwind/zotero-better-notes/tree/master/addon/locale/ru-RU

To create a PR, you'll need to first fork this repo, make changes in your forked one, and the create a pull request to the main branch of this repo.

Thanks for your time and efforts!
