### ISSUE TITLE
[Bug] 使用autosync 生成的md文件用于obsidian时，会多出转义符，导致callout无法正常识别

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#497]
**Describe the bug**
使用autosync 生成的md文件，每条注释在obsidian中会默认用callout的格式来显示，但我这里会多一个转义符，比如">\[warning]"，导致无法正常显示，目前是这样的：

![image](https://github.com/windingwind/zotero-better-notes/assets/33361275/4efe81f4-2122-4d7d-8287-deb29eeaefd9)

尽管手动删除这些斜线的话是可以正常显示，但过段时间zotero的对应内容会覆盖掉ob中删除斜线的效果，就又恢复了上述错误显示效果。

另外现在文字是绿色且下划线显示，是否有办法改为黑色无下划线？

![image](https://github.com/windingwind/zotero-better-notes/assets/33361275/e985df82-f9ed-44c1-b4ec-8eaf80c244c7)

使用的版本：windows 11， zotero 6.0.26，better notes: obsidian v1.3.4，

**Comment by ghweili** [comment]
不仅如此，我在obsidian的某行放了两个标签，发现第一个标签在一定时间后也会多个转义符，

![image](https://github.com/windingwind/zotero-better-notes/assets/33361275/3ca40e66-47e1-49d9-970c-330958295363)

**Comment by ghweili** [comment]
似乎文字内容中的下划线也可能会出现类似问题。如果这个是不同软件对转义符有不同要求的话，建议在导出页面给予设置选项，取消或开放转义字符，这样用户就可以自行解决这个问题

**Comment by windingwind** [comment]
同步、导出等markdown相关的功能仅支持markdown的标准语法，对obsidian等的扩展语法（方言）不做支持。因此，这些特殊符号会根据markdown标准进行转义。
禁用转义符是不可能的，因为这些需要转义的符号在markdown语法中都有特殊作用。禁用会使导出与同步时内容的语义发生变化。例如，`![x](y)`是图片而`\![x](y)`是链接。

**Comment by windingwind** [comment]
文字颜色是ob主题设置的，导出的markdown不包含任何颜色，除非带有颜色格式。

**Comment by ghweili** [comment]
我能理解你的考量，不过考虑到导出到其他软件时，不同软件可能会有一些特殊的语法规则，直接导出markdown可能会遇到我提到的这些问题。 如果能给予用户自行设定特殊规则的权限话，那应该会更好，比如说，在设置界面提供一个框，可以让用户以词典的形式输入一些映射规则，比如{"sth1":"newsth1"， "sth2":"newsth2"}，或者把这些规则存到txt文件中由插件读取，并且在转换时能自动把这些规则生效，则可以顺利在其他各种软件中使用。 

目前的情况是，尽管可以在ob等软件中用某些功能去实施这些规则，但当zotero update note后，obsidian 里的这些措施会被重新覆盖掉。
