### ISSUE TITLE
[Feature]导出到md时，标签前边会自动加#, 但有时标签本身是#开头的话就无法正确识别，是否可添加设置处理这种情况

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#498]
目前在与zotero style 联用，这个插件可以让特定tags以nested tags形式显示，但要求这种tag以#开头，当包含这样标签的zotero笔记被导出为md并用obsidian读取时，会连续两个##，就无法被识别成标签了。 尽管zotero style可以改这个开头的符号，但试了下，包括感叹号等大部分符号开头的zotero标签都无法在obsidian中顺利识别，似乎zotero只能支持下划线或字母数字等作为标签的组成。

是否可以在导出页面添加一个设置，即，如果zotero的标签是以#开头，则导出时就不再额外添加#了，或者添加一些规则，比如某些字符自动替换成某些字符（比如空字符），这样的话应该可以确保标签在其他软件中顺利识别。

**Comment by windingwind** [comment]
同步、导出等markdown相关的功能仅支持markdown的标准语法，对obsidian等的扩展语法（方言）不做支持。因此，这些特殊符号会根据markdown标准进行转义。

**Comment by ghweili** [comment]
我能理解你的考量，不过考虑到导出到其他软件时，不同软件可能会有一些特殊的语法规则，之际导出markdown也可能会遇到我提到的这些问题。 如果能给予用户自行设定特殊规则的权限话，那应该会更好，比如说，在设置界面提供一个框，可以让用户以词典的形式输入一些映射规则，比如{"sth1":"newsth1"， "sth2":"newsth2"}，或者把这些规则存到txt文件中由插件读取，并且在转换时能自动把这些规则生效，则可以顺利在其他各种软件中使用。 

目前的情况是，尽管可以在ob等软件中用某些功能去实施这些规则，但当zotero update note后，obsidian 里的这些措施会被重新覆盖掉。
