### ISSUE TITLE
[Bug]导出当前笔记为markdown，“设置自动同步”无法选中，是灰色的

### ISSUE THREAD

**Issue by zjuliangxun** [windingwind/zotero-better-notes#499]
**Describe the bug**
导出当前笔记为markdown，“设置自动同步”无法选中，是灰色的。

![image](https://github.com/windingwind/zotero-better-notes/assets/49814475/5c708823-ee43-44a0-b1da-86e4098b4e1d)

**To Reproduce**
zotero是官网最新的6.0.26，插件是1.0.2
然后其他的配置都是默认的，创建第一个主笔记，然后导出md的时候，无法选中“同步”这个选项。

**Expected behavior**
希望能正常选中，想在zotero外部使用typora来编辑笔记，再同步回去。

**Desktop (please complete the following information):**
 - OS: win11
 - Browser chorme

**Additional context**
这是zotero的后台错误日志
![image](https://github.com/windingwind/zotero-better-notes/assets/49814475/6bc6391a-3bed-433c-a639-fbb2d52a81e8)

**Comment by windingwind** [comment]
链接需要分别单独导出模式
