### ISSUE TITLE
【功能强化】同步注释tag

### ISSUE THREAD

**Issue by appw-cn** [windingwind/zotero-better-notes#5]
非常喜欢这个小插件！

有一个小建议，就是在zotero pdf阅读器中，可以对注释笔记加上标签。希望通过插件新增笔记时，标签信息也会同时给加新增的注释。
图1：
<img width="168" alt="image" src="https://user-images.githubusercontent.com/101581031/167760892-308847d0-a6cb-4279-a6eb-c8f2e34d3322.png">
图2：（希望实现的效果）
<img width="533" alt="image" src="https://user-images.githubusercontent.com/101581031/167761006-008dcfed-dc0d-4833-a0ba-e784a1d88bc4.png">

**Comment by windingwind** [comment]
已添加到TODO任务列表。

**Comment by beifengli** [comment]
大佬您好，我也非常喜欢这个插件。请问您不能实现批量地插入已有的注释呢？
我在pdf阅读时候，会对注释笔记加上标签，想将同一标签的内容提取到一个笔记文档中一起对比这看。相同标签的内容放在一起能够方便的进行横向的比较。
十分希望您能实现这个功能。

**Comment by windingwind** [comment]
> 大佬您好，我也非常喜欢这个插件。请问您不能实现批量地插入已有的注释呢？ 我在pdf阅读时候，会对注释笔记加上标签，想将同一标签的内容提取到一个笔记文档中一起对比这看。相同标签的内容放在一起能够方便的进行横向的比较。 十分希望您能实现这个功能。

已计划。另外最好每个问题单独开issue。

**Comment by beifengli** [comment]
好的，谢谢大佬提醒。

**Comment by windingwind** [comment]
@appw-cn 已支持
