### ISSUE TITLE
sync error: reference error. blob is not defined

### ISSUE THREAD

**Issue by dongwhfdyer** [windingwind/zotero-better-notes#502]
**Describe the bug**

I just started to use better-notes plugin two weeks ago. I used it to sync the notes with external md files. I believe it worked well at the beginning. But it seems to prompt errors recently. I don't think I have made any special modification with this application. I can still export the notes to md files for sync purposes. But I no longer be able to sync. 
![image](https://github.com/windingwind/zotero-better-notes/assets/59996817/4201bbb4-d4e1-4e3b-9b52-6cabab187982)

**To Reproduce**

When clicking on this or just waiting for the automatic sync process, the error came out.
![image](https://github.com/windingwind/zotero-better-notes/assets/59996817/0acf0cb2-b29e-4407-9599-b6978c5e52ea)

**Expected behavior**
Sync smoothly.

**Screenshots**

![image](https://github.com/windingwind/zotero-better-notes/assets/59996817/fa80e260-dd8a-4e71-8538-36846f4a106b)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: edge
 - zotero-better-notes version: release 1.0.2

**Comment by windingwind** [comment]
Ok I will check. Thanks

**Comment by windingwind** [comment]
Ok I will check. Thanks

**Comment by dongwhfdyer** [comment]
so do you know how to solve it? It still stays as a problem. 😭

**Comment by windingwind** [comment]
Will release soon
