### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lisasuosuo** [windingwind/zotero-better-notes#507]
**Describe the bug**
首先非常感谢作者开发出了这么棒的插件！对作者的辛苦表示大大的感谢！

问题：使用最新版本插件和zotero7 Beta版本的时候的时候，发现模版编辑页面字重叠了。而且无法往下正常拖动

![image](https://github.com/windingwind/zotero-better-notes/assets/21986381/4baaf084-3759-4c9a-92b1-e7111cc4b8ba)

**Comment by windingwind** [comment]
谢谢反馈

**Comment by windingwind** [comment]
已修复

**Comment by lisasuosuo** [comment]
给作者速度点赞！
