### ISSUE TITLE
[Help Needed] How to auto-insert new comments/annotations to Note?

### ISSUE THREAD

**Issue by nhan000** [windingwind/zotero-better-notes#508]
Hi, is the feature here [4.4 Automatically insert new comments into notes Auto insert New Annotations to Note.en · windingwind/zotero-better-notes Wiki](https://github.com/windingwind/zotero-better-notes/wiki/4.4-Automatically-insert-new-comments-into-notes-Auto-insert-New-Annotations-to-Note.en)

I see someone has asked here as well https://zotero.yuque.com/staff-gkhviy/better-notes/ncnkfs but I don't see any replies yet.

It says I can turn the feature on/off in the "Edit" in the Menu bar but I don't see any options to turn on/off that feature. 
![image](https://github.com/windingwind/zotero-better-notes/assets/85216095/6d7014aa-a670-4fe0-ba0a-e30b16614ef2)

Thank you!

**Comment by nhan000** [comment]
I don't think this feature is available? [4.6 Quick insert markdown or AciiDoc Quick Insert MD & AciiDoc.en · windingwind/zotero-better-notes Wiki](https://github.com/windingwind/zotero-better-notes/wiki/4.6-Quick-insert-markdown-or-AciiDoc-Quick-Insert-MD-&-AciiDoc.en)

**Comment by windingwind** [comment]
Yes, not available now. I am adding it back.

**Comment by nhan000** [comment]
Could you please confirm that the feature here is not currently available as well? [4.9 Note Synchronization Sycn.en](https://github.com/windingwind/zotero-better-notes/wiki/4.9-Note-Synchronization-Sycn.en). Just because I'm particularly interested in that feature.

Thanks a lot for making this plugin. I know you're also making it easier for other devs to migrate their plugins as well. Really appreciate your work!

**Comment by windingwind** [comment]
Syncing works well.

**Comment by windingwind** [comment]
The wiki and yuque need update. I have put everything in the readme, which should be correct for the latest version.

The wiki is going to be abandoned by the way.

**Comment by nhan000** [comment]
Thanks for your reply. I can't seem to check the Auto-sync toggle 
![image](https://github.com/windingwind/zotero-better-notes/assets/85216095/bc5681f6-f6df-4a8e-a811-13672a26ae6c)

**Comment by windingwind** [comment]
Unfortunately, this feature will not be added to this plugin. You may want to create a new plugin to achieve this. Thank you for your understanding.
