### ISSUE TITLE
How to rapidly switch main note?

### ISSUE THREAD

**Issue by seredes** [windingwind/zotero-better-notes#509]
Hi, until a few weeks ago, it was easy to quickly switch the main note by accessing a drop-down menu with the most recent notes listed. But now I don't see the menu anymore...?

I think one could access it by clicking on a symbol in the top left corner, that is still visible in some screenshots on the readme page:

![image](https://github.com/windingwind/zotero-better-notes/assets/20558980/d88bf90a-1c40-4745-9bfd-fb68519f447c)

But now In Zotero I don't see it anymore?

![image](https://github.com/windingwind/zotero-better-notes/assets/20558980/5f419d21-9988-462b-908a-04e7dabaca44)

Please bring it back, it was very useful.

Thanks a lot for all your work.

**Comment by nhan000** [comment]
The author windingwind is migrating the features to Zotero 7 so a few features may be missing. If the previous features are important to you, you can uninstall the plugin and reinstall previous releases [Releases · windingwind/zotero-better-notes](https://github.com/windingwind/zotero-better-notes/releases?page=2)
