### ISSUE TITLE
自动给不同颜色的批注打标签，并提取到相应的笔记中

### ISSUE THREAD

**Issue by zyx335588** [windingwind/zotero-better-notes#51]
如题，作者是否可以考虑增加上述自动化功能。
让用户给每种颜色的批注添加一个标签，然后自动将该批注添加到以批注为标题的笔记中。
例如：
红色的批注添加一个“重要概念”的标签，并将其放到以“重要概念”为标题的笔记中
黄色的批注添加一个“主流观点”的标签，并将其放道以“主流观点”为标题的笔记中
……
这样可以在阅读完文献或书籍后，自动生成有用信息，方便后续的回顾，也可以通过现在插件中的模版功能，对笔记进行简单的横向和纵向的整合复用。

**Comment by windingwind** [comment]
但是自动加入某个笔记比较复杂，用户可能会想插入不同的笔记。
我的建议是设置Item模板，在添加的时候，对所选条目下所有符合条件的批注（颜色）以特定格式加入当前主笔记。

**Comment by normanify** [comment]
急需这个功能。根据不同颜色的 Annotation，导出到不同的笔记中。

**Comment by windingwind** [comment]
@normanify 
不能实现导出到**不同**笔记，只能在当前主笔记导入某种颜色/某类标签的条目信息。
如果需要同一篇文章的内容导出到不同笔记，则：
1. 推荐导出到主笔记下的两个层级段落。这也是主从笔记双链的标准用法；
2. 实在要导出到不同笔记，就只能多操作几遍。

请在文档中搜索基础的模板，告诉我需要根据哪个模板，在什么位置，以什么形式插入什么内容。

**Comment by yingker** [comment]
我习惯在zotero中，用不同颜色的高亮，标注pdf文献，并加上不同的标签作为子笔记，很希望能按照不同颜色或者标签导出子笔记到OB中。这个可能是很多用户的习惯和共同要求。
据说：模板功能可以实现按照颜色或者标签导出笔记，但我试了一下，实现不了。其实多数普通用户对模板怎么使用也是不太清楚，请大神详细示范一下。

**Comment by windingwind** [comment]
The example template runs on addon >= v0.5.13. Please update to the latest release.

Modify the `let color = "#ffd400";` to select corresponding annotations.

Annotation colors: Yellow #ffd400, Red #ff6666, Green#5fb236, Blue #2ea8e5, Perple #a28ae5

Name: [Item] annotations by color

Content:
```js
${await new Promise(async (r) => {
  topItem = Zotero.Items.get(5366);
  async function getAnnotation(item) {
    try {
      if (!item || !item.isAnnotation()) {
        return null;
      }
      let json = await Zotero.Annotations.toJSON(item);
      json.id = item.key;
      delete json.key;
      for (let key in json) {
        json[key] = json[key] || "";
      }
      json.tags = json.tags || [];
      return json;
    } catch (e) {
      Zotero.logError(e);
      return null;
    }
  }

  async function getAnnotationsByColor(_item, color) {
    const annots = _item
      .getAnnotations()
      .filter((_annot) => _annot.annotationColor === color);
    let annotations = [];
    for (let annot of annots) {
      const annotJson = await getAnnotation(annot);
      annotJson.attachmentItemID = _item.id;
      annotations.push(annotJson);
    }

    const editor =
      await Zotero.Knowledge4Zotero.knowledge.getWorkspaceEditorInstance();
    await editor.importImages(annotations);
    return Zotero.EditorInstanceUtilities.serializeAnnotations(annotations);
  }

  const attachments = Zotero.Items.get(topItem.getAttachments()).filter((i) =>
    i.isPDFAttachment()
  );
  let res = "";
  let color = "#ffd400";
  for (let attachment of attachments) {
    res += `<h2><p style="background-color:${color};">Annotations</p>: 📄${attachment.getFilename()}</h2>
    ${(await getAnnotationsByColor(attachment, color)).html}
    `;
  }
  r(res);
})}
```

Result:
![image](https://user-images.githubusercontent.com/33902321/174333203-2c50586d-0e6e-46fc-8b9e-4c60da7ed75d.png)
