### ISSUE TITLE
插件安装问题

### ISSUE THREAD

**Issue by UntermRad** [windingwind/zotero-better-notes#516]
你好，我在安装插件后，许多内容与教程文档中都不一致。部分如下图所示。请问是插件更新之后界面改变了吗？
<img width="258" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/136336843/ffc67e72-5076-43bb-b28e-f3f58bc15f21">
<img width="412" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/136336843/23f1ffb5-27bb-4179-8883-28c6852c3311">
<img width="439" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/136336843/31bfec88-583c-44ac-85ec-cf24d71e6277">
<img width="130" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/136336843/98a4fbae-c7f7-4065-b85e-19381643bae9">

**Comment by nhan000** [comment]
See https://github.com/windingwind/zotero-better-notes/issues/508

**Comment by windingwind** [comment]
yes
