### ISSUE TITLE
[Bug] 希望改善【主笔记大纲过长后】从按钮将笔记添加进主笔记 操作的体验

### ISSUE THREAD

**Issue by Loticyang** [windingwind/zotero-better-notes#517]
![image](https://github.com/windingwind/zotero-better-notes/assets/8101717/efba6087-8e1f-4dab-86ed-3233e3ea56dc)

问题描述：如图，我目前使用主笔记的大纲已经非常长，需要用鼠标下滑才能看完。由此会产生一个bug：

对于这个列表中比较靠下的大纲标题，如果我想把条目笔记添加到其中——我单击一次大纲标题后，无法成功创建双链笔记，必须再点一次。我想这个bug比较容易复现。

最后感谢插件作者的贡献，betternotes是我个人认为zotero插件中最关键的一个，idea非常棒。

**Comment by guolizhang-tyler** [comment]
主笔记感觉还需要优化 感觉可以取消主笔记 实现可以选择多个笔记中记录，这样还可以避免大纲过长的问题。

**Comment by windingwind** [comment]
> 主笔记感觉还需要优化 感觉可以取消主笔记 实现可以选择多个笔记中记录，这样还可以避免大纲过长的问题。

本来就可以做到在工作区中打开不同的笔记条目，楼主的问题是UI交互上的，不是一回事。另外不同的内容请单独开issue

**Comment by guolizhang-tyler** [comment]
> > 主笔记感觉还需要优化 感觉可以取消主笔记 实现可以选择多个笔记中记录，这样还可以避免大纲过长的问题。
> 
> 本来就可以做到在工作区中打开不同的笔记条目，楼主的问题是UI交互上的，不是一回事。另外不同的内容请单独开issue


好的 谢谢 我的意思是 我看到文献中的句子时只能导入到主笔记工作区 如果想到导入其他笔记中 得先设置成主笔记才行？ 或许我还没用懂这个软件~

**Comment by doctorofeyes** [comment]
> > > 主笔记感觉还需要优化 感觉可以取消主笔记 实现可以选择多个笔记中记录，这样还可以避免大纲过长的问题。
> > 
> > 
> > 本来就可以做到在工作区中打开不同的笔记条目，楼主的问题是UI交互上的，不是一回事。另外不同的内容请单独开issue
> 
> 好的 谢谢 我的意思是 我看到文献中的句子时只能导入到主笔记工作区 如果想到导入其他笔记中 得先设置成主笔记才行？ 或许我还没用懂这个软件~

要实现这个功能你可以用到另一个扩展笔记软件叫做zotcard，配合bnote才是真正的神
