### ISSUE TITLE
为什么链接某篇论文笔记至主笔记时不成功？

### ISSUE THREAD

**Issue by Dongqianyu** [windingwind/zotero-better-notes#519]
当我在当前笔记，想链接当前笔记到工作区笔记时，点击链接按钮，只能在当前笔记出现 Referred in 主笔记

但是主笔记中并不会出现当前笔记的链接，

除此之外，明明链接的是主笔记里的某个二级标题下，但是在当前笔记里也只会出现Refered in 主笔记

重启zotero, 重新安装了betternotes也无法解决 

请问该如何处理呢，蹲一个答复，十分感谢~

**Comment by windingwind** [comment]
请粘贴或上传菜单栏-工具-调试-查看调试输出，谢谢

**Comment by Tariya321** [comment]
ops，我出现了同样的问题，console记录的信息如下
`[JavaScript Warning: "Unknown property ‘enable-background’.  Declaration dropped." {file: "resource://zotero/note-editor/editor.html" line: 0}]`

**Comment by Tariya321** [comment]
> ops，我出现了同样的问题，console记录的信息如下 `[JavaScript Warning: "Unknown property ‘enable-background’. Declaration dropped." {file: "resource://zotero/note-editor/editor.html" line: 0}]`

经过摸索，发现了一些问题出现的规律：当一个item下存在多个pdf文件时，该错误发生。
优化这一问题可能的方法有：（1）检索与之相关的代码；（2）避免存在多个pdf文件，应由插件sci-hub的开发者处理。

**Comment by Tariya321** [comment]
> > ops，我出现了同样的问题，console记录的信息如下 `[JavaScript Warning: "Unknown property ‘enable-background’. Declaration dropped." {file: "resource://zotero/note-editor/editor.html" line: 0}]`
> 
> 经过摸索，发现了一些问题出现的规律：当一个item下存在多个pdf文件时，该错误发生。 优化这一问题可能的方法有：（1）检索与之相关的代码；（2）避免存在多个pdf文件，应由插件sci-hub的开发者处理。

遗憾的是，这一方法并不总是奏效

**Comment by hannah037** [comment]
遇到了同样的问题，时灵时不灵，不知道为什么

**Comment by Tariya321** [comment]
可惜的是，原作者windingwind貌似目前没有针对此帖进行修复的计划

Best Regards
洪志连
----------
M  +86 15905657974
***@***.***


发件人: hannah037
发送时间: 2023年9月20日 15:31
收件人: windingwind/zotero-better-notes
抄送: Zhilian Hong; Comment
主题: Re: [windingwind/zotero-better-notes] 为什么链接某篇论文笔记至主笔记时不成功？ (Issue #519)

遇到了同样的问题，时灵时不灵，不知道为什么

**Comment by windingwind** [comment]
我需要发生问题时确切完整的调试输出报告（tool-debug-view output），以及稳定复现的操作方式。

**Comment by hannah037** [comment]
> 我需要发生问题时确切完整的调试输出报告（tool-debug-view output），以及稳定复现的操作方式。

好滴 等我下次出现问题 感谢大大

**Comment by hannah037** [comment]
> 我需要发生问题时确切完整的调试输出报告（tool-debug-view output），以及稳定复现的操作方式。

我猜测是因为主笔记笔记内容太多，列表太长的原因，或者 zotero在同时运行一些需要用到 JAVA 的操作
我把主笔记区的笔记拆分成几个短的之后，用了一天多没有出现问题

**Comment by windingwind** [comment]
由于暂时没有可复现的报告，此处关闭
