### ISSUE TITLE
内置链接跳转不正常

### ISSUE THREAD

**Issue by Big-Bad-Wolf123** [windingwind/zotero-better-notes#52]
![image](https://user-images.githubusercontent.com/74827176/172934320-410fdf0a-a2b9-4831-94fa-4225c54d8173.png)

**Comment by windingwind** [comment]
请确认该链接的笔记是否存在？如果被删除，将跳回主笔记

**Comment by Big-Bad-Wolf123** [comment]
> 

发现问题了，被链接的笔记只能在主分组 "my library" 里，如果是在"group libraries" 里则无法跳转。
mian note 位置不受影响

**Comment by Big-Bad-Wolf123** [comment]
> 请确认该链接的笔记是否存在？如果被删除，将跳回主笔记
发现问题了，被链接的笔记只能在主分组 "my library" 里，如果是在"group libraries" 里则无法跳转。
mian note 位置不受影响

**Comment by Big-Bad-Wolf123** [comment]
zotero://note/u/NFUHZNPT/?ignore=1 这种在my library里的链接就能跳转正常

zotero://note/4709747/Y6H3AIHI/ 这种链接在group libraries里的链接 就只能跳回主笔记

**Comment by windingwind** [comment]
v0.5.8 已修复
