### ISSUE TITLE
Markdown 语法不知道是什么 flavor，是否考虑加入星号 *Italic text* 斜体啊

### ISSUE THREAD

**Issue by JackieMium** [windingwind/zotero-better-notes#520]
如题，既然 `**blah**` 呈现 **粗体** 也支持了，通过 `*blah*` 达到 *blah* 显示斜体算是很常用的 markdown 语法了，能否考虑也支持下斜体啊，谢谢！

**Comment by windingwind** [comment]
zotero笔记是支持部分md语法的富文本。可通过ctrl/cmd+i设为斜体
