### ISSUE TITLE
[Note Template] 自动导出的yaml怎么删除单引号

### ISSUE THREAD

**Issue by dxwy** [windingwind/zotero-better-notes#522]
## Template Type

ExportMDFileHeaderV2

## Desired Template Performance

自动导出的yaml中，怎么去掉字符串类型字段的单引号。或者说它现在存在的作用是什么，我觉得不应该存在。

![image](https://github.com/windingwind/zotero-better-notes/assets/46398670/cd16773e-9f1b-4920-949f-95da4eb611ee)

## Current Template

以下是ExportMDFileHeaderV2默认模板，没改

```js
${await new Promise(async (r) => {
    let header = {};
    header.tags = noteItem.getTags().map((_t) => _t.tag);
    header.parent = noteItem.parentItem
      ? noteItem.parentItem.getField("title")
      : "";
    header.collections = (
      await Zotero.Collections.getCollectionsContainingItems([
        (noteItem.parentItem || noteItem).id,
      ])
    ).map((c) => c.name);
    r(JSON.stringify(header));
  })}
```

**Comment by windingwind** [comment]
yaml由上游依赖https://github.com/jeremyfa/yaml.js 生成。引号是yaml规范中允许的格式，不影响
