### ISSUE TITLE
[Bug] 导出md文件评论多出换行符的问题

### ISSUE THREAD

**Issue by library0012** [windingwind/zotero-better-notes#524]
Zotero 版本 6.0.26
Better-note 版本 1.0.1

操作复述：
1. 高亮一部分内容，并添加评论，会形成一条注释
2. 把这条注释添加到Better note 里，然后用better note 导出md 文件，
3. 高亮部分会以嵌入块的形式出现 即>xxxx，评论会出现在对应块下方，但是如果有多行，评论就会出现换行符

截图如下：
![image](https://github.com/windingwind/zotero-better-notes/assets/66898712/a8ff7960-7d4c-472d-8173-d3a449c924d6)
![image](https://github.com/windingwind/zotero-better-notes/assets/66898712/fb6ce48d-e691-4f0f-8030-619e8e3623fc)
![image](https://github.com/windingwind/zotero-better-notes/assets/66898712/d2a45a99-7870-4641-8e8a-81cdbbf028cd)

**Comment by yiqiaowang-arch** [comment]
I had a similar issue, right before the citation.
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/7eebc1a2-3df2-4b1c-915a-72bacb2158b5)

**Comment by windingwind** [comment]
See https://github.com/windingwind/zotero-better-notes/issues/620#issuecomment-1675075064

可自己修改模板，按喜好去除换行符等。默认的导出行为只是符合markdown标准的其中一种选择，众口难调，自己设置最好。
