### ISSUE TITLE
[Feature Request] Adding open-pdf link to citations while export to md

### ISSUE THREAD

**Issue by anandkumar89** [windingwind/zotero-better-notes#525]
**Is your feature request related to a problem? Please describe.**
Current format for export to markdown is `"Annotation is linked to highlight on pdf"(citation is zotero://select)`. However, text is wrapped inside html and is not much markdown friendly if we want to change annotated text. 

1. proposed export format:  `"Annotation as text"(citation as zotero-link-highlight)`
2. Also, link could be in markdown format `[citekey](zotero-link)` would be much helpful as this can later be edited in bulk using regex when moving notes to final report/latex.

**Describe the solution you'd like**
Instead, text could be plain text or linked to highlight as user decides but citation links to highlight on pdf. Since there is separate citation per annotation, references to highlights won't be lost. 

If this request makes two-way sync difficult then each referenced block can be wrapped in `p` or `div` with id, but with minimal use of html. Going forward, it may be better to have a markdown only notes in zotero as markdown has received much support/extensions recently.

**Describe alternatives you've considered**
Since, this processing is done by internal api in plugin, there's not much I could do rather than manually editing the markdown. 

**Additional context**
End goal of all these export/note taking is to be able to refractor in long report where we often paraphrase annotations in own words, but keeping context (highlight link) is important, in case we need to gather more context later. I do write long docs in markdown before moving it to latex for making reports / papers. 
A markdown friendly export which can later be copy pasted to latex with minimal find/replace edits and paraphrasing is much helpful.

**Comment by windingwind** [comment]
Thanks for the suggestion. The citing information in the HTML is necessary if we want to support syncing. If we decide to provide an export option with pure markdown, it will be impossible to restore a Zotero note anymore. It's just a one-time conversion.

**Comment by anandkumar89** [comment]
I realised pure markdown syncing could be difficult. However, in that case, linking `citation` at end of each highlight to open-pdf instead of zotero-select could be useful. (highlight link, i.e. open-pdf does same and more than zotero-select) 

This will help achieve minimal use of html and also preserve sync.
