### ISSUE TITLE
[Bug]无法在群组文库内建立主笔笔记

### ISSUE THREAD

**Issue by hpxing** [windingwind/zotero-better-notes#53]
**Describe the bug**
[Bug]无法在群组文库内建立主笔笔记
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
请确保你对群组有写权限。在我自己的群组测试正常。
![image](https://user-images.githubusercontent.com/33902321/173006015-c2dfb9e1-a061-43cc-a4b3-30a355f99ed6.png)

**Comment by hpxing** [comment]
有权限的
新建的时候提示 please select the collection
![1654846891604(1)](https://user-images.githubusercontent.com/43682925/173015844-56080666-201d-4068-ab61-6d0f4005886e.png)

发现原因了 我选择epp的时候，就会提示我选择分类， 如果选择下面的未命名分类就可以新建了
谢谢
