### ISSUE TITLE
最新版本与zotero6.0.26版本不兼容

### ISSUE THREAD

**Issue by qwpyyx** [windingwind/zotero-better-notes#530]
![image](https://github.com/windingwind/zotero-better-notes/assets/43367931/4ae8ba57-dfb6-43cc-8979-d105f6853341)

请问如何解决?

**Comment by windingwind** [comment]
安装1.1.0以下版本。1.1.0是只为zotero7开发的

**Comment by qwpyyx** [comment]
好的，我更新zotero7以后使用了最新版本1.1.3，但是编辑栏中并没有“使用模板插入多条笔记”和“使用模板插入多个条目”，请问这是什么原因呢？谢谢！（我这里编辑只有“插入模板到工作区笔记”、“模板编辑器”、“导出模板到文件”以及“从剪切板导入新模板”这四个选项）

**Comment by windingwind** [comment]
ui改动。插入模板到工作区=旧插入模板
