### ISSUE TITLE
[Feature]新增笔记链接自动更新功能

### ISSUE THREAD

**Issue by davidhappypotter** [windingwind/zotero-better-notes#533]
使用场景：
1.笔记A引用了笔记B，即笔记A中有笔记B的链接。
2.当完成笔记B的内容修改后，自动更新笔记A中的链接。

备注：
当前情况是，需要点击笔记A中对应笔记B的链接上，然后点击刷新按钮。对于多个笔记需要更新的情况，此操作过程有点繁琐。

**Comment by windingwind** [comment]
请在创建链接的时候决定第一行内容，作为链接文本。无法自动更新
