### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by thams86** [windingwind/zotero-better-notes#534]
Hello,
I have made a note template and I would love if this note template would automatically incorporate the authors' last name a year of publication at the top of the note. But I'm not being able to code that

## Template Type

Note, Quick Import

## Desired Template Performance

automatically incorporate the authors' last name a year of publication

The title of the note ideally would come as something like:

<h1> Doe (2023) Notes: [today's date] </h1>

## Current Template

This is what I have now:

<h1> <"author"><"year"> Notes: ${new Date().toLocaleDateString()} </h1>

thank you
```

**Comment by windingwind** [comment]
Sorry, the description is unclear and I don't know what you want

**Comment by windingwind** [comment]
Are you looking for this: https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#script-syntax

**Comment by thams86** [comment]
Hello, 
sorry I was not clear. I'm quite new to this. This link you sent with the different options does seem to help, but I keep getting errors. Such as: **Template [Text] Notes Error: SyntaxError: missing : after property id.**

I would like my child notes to **get (author, year)** from that item automatically. 

thank you for your help

**Comment by windingwind** [comment]
The syntax in the link requires the latest beta, which is only for Zotero 7. On 6, you should use:

```js
${await new Promise(async (resolve) => {
  const creators = topItem.getCreators();
  let content = "";
  const year = topItem.getField("year");
  if (creators.length === 0) {
    content = "no author";
  } else if (creators.length === 1) {
    content = `${creators[0].lastName}, ${year}`;
  } else {
    content = `${creators[0].lastName} etal., ${year}`;
  }
  // The getPDFLink is from above
  const link = await getPDFLink(topItem);
  let str = `<a href="${link}">${content}</a>`;
  resolve(str);
})}
```

**Comment by macrospecter** [comment]
I'm on Zotero 6, and found that this doesn't work for me. I tried both a copy/paste method of installation within the Templates Editor and import from clipboard using the File menu option. Both just produce empty notes, no content. I'm experiencing the same issue with all of the templates posted here. When applied, they either show an error that there's something wrong in the syntax (usually the older templates) or nothing happens, just no content is appended. Is there some other way of installing templates that I'm missing?

**Comment by windingwind** [comment]
Well, what's your plugin version and OS? And how you managed to use the template? You must have the template name starts with `[Item]` to indicate the data source.

And the template above is not for import: it's just a template segment, although it is also runnable. Copy-paste in the template editor.

**Comment by macrospecter** [comment]
I was able to get some of the templates working (in Zotero 6)! It may've
been because of the "[Item]" designator--I had missed that.

**Comment by thams86** [comment]
Thankyou for your help
