### ISSUE TITLE
[Bug]创建不了主笔记

### ISSUE THREAD

**Issue by justBruceFeng** [windingwind/zotero-better-notes#535]
**Describe the bug**
1.进入Zotero后左侧文件没有主笔记一栏
2.在子类下面创建文件也没有创建主文件选项
![image](https://github.com/windingwind/zotero-better-notes/assets/55623084/90537680-050a-4b01-9bfb-da68fbf18770)
3.进入工作区笔记后，左上角文件处也没有设置主笔记等字样
![image](https://github.com/windingwind/zotero-better-notes/assets/55623084/5a9f54fb-a6b5-49e1-8644-4888beac73f3)

**Desktop (please complete the following information):**
 - OS: win10
 - Version [Zotero 6.0.26] [zotero-better-notes 1.0.4]

**Additional context**
跟着B站视频和帮助文档进行配置的，结果发现这些地方和视频或者文档不同，遂不知如何继续使用。

**Comment by windingwind** [comment]
新版界面有调整，工作区笔记=主笔记

**Comment by justBruceFeng** [comment]
> 新版界面有调整，工作区笔记=主笔记

好的大佬哈哈哈~谢谢解答！
