### ISSUE TITLE
[Bug]笔记工作区出现了看文献时右边的条目笔记区

### ISSUE THREAD

**Issue by coisini-95** [windingwind/zotero-better-notes#539]
![图片](https://github.com/windingwind/zotero-better-notes/assets/78250635/db244f3f-4403-4707-9022-5342ae886484)

如图所示，这个条目笔记区一直出现在笔记工作区，点开某个笔记查看后，整个屏幕会出现4个分区，很怪；只有在看文献那个页面关掉条目笔记区，笔记工作区内才会也消失。

**Comment by windingwind** [comment]
Not a bug. Toggle views using the buttons on the workspace tab.
