### ISSUE TITLE
笔记编辑窗口中，能调整图片的大小

### ISSUE THREAD

**Issue by LIKAISAA** [windingwind/zotero-better-notes#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
暂时无法实现，图片大小是自适应的且由zotero处理

**Comment by LIKAISAA** [comment]
好的

**Comment by windingwind** [comment]
已支持

**Comment by pengxy0** [comment]
@windingwind 大佬，这图片大小调整需要右击输入数值，比较繁琐。可以拖拉调节大小，或者全选设置，用代码实现同意调整也可以。这样可以实现不
