### ISSUE TITLE
[Bug]插入笔记模板功能异常

### ISSUE THREAD

**Issue by YMisDerek** [windingwind/zotero-better-notes#544]
您好，请问是否有办法修复编辑选项卡中，插入笔记模板到特定笔记的功能。
![image](https://github.com/windingwind/zotero-better-notes/assets/106132050/e449a07e-1fc6-4b10-9ef7-11224163c022)

不知道是我个人zotero软件异常，还是插件遇到什么异常，从zotero6升级到7没有解决。
系统：windows11。
已尝试办法：更新zotero6到版本7，更新better notes到最新版。

**Comment by windingwind** [comment]
不是bug。这里写着是插入到工作区笔记。
要插入到当前笔记，在笔记编辑器右上角齿轮-插入目标到光标行

**Comment by YMisDerek** [comment]
> 不是bug。这里写着是插入到工作区笔记。 要插入到当前笔记，在笔记编辑器右上角齿轮-插入目标到光标行

原来如此，懂了，谢谢解答。
