### ISSUE TITLE
[Bug] Config Editor bottom not working

### ISSUE THREAD

**Issue by thams86** [windingwind/zotero-better-notes#545]
**Describe the bug**
I want to access the Config Editor in the Advanced Configuration of preferences, but when I click it does not open

**To Reproduce**
1. Go to 'Zotero Preferences; Advanced; Config Editor'
2. Click on 'Config Editor'
3. Nothing happens

**Expected behavior**
To view the available templates, go to the Advanced pane of the Zotero preferences, open the Config Editor, and search for annotations.noteTemplates.

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - Zotero 6

**Comment by windingwind** [comment]
Report to zotero forums please. Not related to the plugin

**Comment by thams86** [comment]
sorry, my bad
