### ISSUE TITLE
[Bug] 导出md后，项目符号的部分会有多余的换行

### ISSUE THREAD

**Issue by sueapaiok** [windingwind/zotero-better-notes#546]
导出后，项目符号的部分中，有些粗体和划线的部分会换行（obsidian和typora阅读状态下都是）

（图左边better notes, 右边obsidian)
![image_93](https://github.com/windingwind/zotero-better-notes/assets/36531839/b7f54b48-6e44-491e-b342-576e413503b3)

但找到了解决措施……这种情况直接从betternotes复制黏贴过去的格式倒是更好的：会换行的粗体/划线部分会直接变成无格式状态

（图为直接复制黏贴到obsidian的版本）
![image_94](https://github.com/windingwind/zotero-better-notes/assets/36531839/8c1b1dc9-7fd4-4205-95c2-7f2b513520d4)

但要是能有优化好的完整的，划线粗体能导出，就更好了

**Comment by yiqiaowang-arch** [comment]
I had the same issue in some of my exported .md files, but I didn't have any blacked texts, so it only happens before and after some inline equations. 
Further, I assumed that this issue only happens to formatted text in either bulleted or numbered list. Please refer to the following screenshot for the problem.
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/d578ce4c-e8c3-4776-ac7f-70fe2a20e522)

**Comment by hannahlulu057** [comment]
> 

直接复制也有空行，强迫症非常难受T T

**Comment by windingwind** [comment]
#524
