### ISSUE TITLE
[Bug] Cannot disconnect note from Workspace

### ISSUE THREAD

**Issue by macrospecter** [windingwind/zotero-better-notes#547]
I cannot seem to disconnect a sidebar note from the Workspace. I was just playing around with the plugin to understand what it can do, and clicked "set as workspace note" for one of my notes. And now, a day later, I can't unlink the note from the workspace. This is **turning out to be a problem because now my templates are ALL dumping into the workspace note rather than my active one**. When I select "Insert Template at Cursor" from within the sidebar note, this should insert the template in that current note; instead, the template ends up in the workspace note in an inactive tab. This partially explains why many templates appeared not to be working for me.

**Comment by windingwind** [comment]
Please share the template you are using

**Comment by macrospecter** [comment]
Oh the issue here isn’t that I’m using a template. It’s that a note is stuck to the workspace. I can’t remove it. And every template I try to use is dumping into the workspace, not just one. How can I unstick the note?

Thank you so much!

**Comment by macrospecter** [comment]
Here's an example of one template that I tried to insert (but again, it's not the only one). It works just fine on my other computer, where the workspace is not stuck. I'm on Z6, BN 1.0.4.

${await new Promise (async (r) => {
  async function getAnnotation(item) {
    try {
      if (!item || !item.isAnnotation()) {
        return null;
      }
      let json = await Zotero.Annotations.toJSON(item);
      json.id = item.key;
      delete json.key;
      for (let key in json) {
        json[key] = json[key] || "";
      }
      json.tags = json.tags || [];
      return json;
    } catch (e) {
      Zotero.logError(e);
      return null;
    }
  }

  function getEditorInstance(noteId) {
    return Zotero.Notes._editorInstances.find(
      (e) =>
        e._item.id === noteId && !Components.utils.isDeadWrapper(e._iframeWindow)
    );
  }

  async function getAnnotationsByColor(_item, color) {
    const annots = _item.getAnnotations().filter(item => item.annotationColor === color);
    if (annots.length === 0) {
      return {
        html: "",
      };
    }
    let annotations = [];
    for (let annot of annots) {
      const annotJson = await getAnnotation(annot);
      annotJson.attachmentItemID = _item.id;
      annotations.push(annotJson);
    }

    let editor = getEditorInstance(targetNoteItem.id)
    if (!editor) {
      alert("No active note editor detected. Please open workspace.");
      return r("");
    }
    await editor.importImages(annotations);
    return Zotero.EditorInstanceUtilities.serializeAnnotations(annotations);
  }

  const attachments = Zotero.Items.get(topItem.getAttachments()).filter((i) =>
    i.isPDFAttachment()
  );

  let res = `<h3>${"PDF Annotations"}</h3>`;

  const colors = {

    "#a28ae5": "Must Cite",            // Purple
    "#e56eee": "Quotable Language",           // Magenta

    "#5fb236": "Theses",        // Green
    "#2ea8e5": "Sources",            // Blue
"#ff6666": "Disagree",         // Red
"#aaaaaa": "Extra",           // Grey
    "#f19837": "Definitions"       // Orange
  }
  for (const attachment of attachments) {

    for (const color in colors) {
      if (Object.hasOwnProperty.call(colors, color)) {
        const colorName = colors[color];
        const renderedAnnotations = (await getAnnotationsByColor(attachment, color)).html;
        if (renderedAnnotations) {
          res += `<h3><p style="color:${color};">${colorName}</p></h3>\n${renderedAnnotations}`;
        }
      }
    }
    const renderedAnnotations = (
      await getAnnotationsByColor(
        attachment,
        (_annot) => !colors.includes(_annot.annotationColor)
      )
    ).html;
    if (renderedAnnotations) {
      res += `<h2><p>Other Annotations</p></h2>\n${renderedAnnotations}`;
    }
  }
  r(res);
})}

**Comment by windingwind** [comment]
1. What do you mean by the note stuck in the workspace? If you set another note as a workspace note (via right-click or editor toolbar popup), the workspace note is not changed. Is that the case?
2. I can't reproduce this. Insert template via the editor toolbar button doesn't work? Or you are using the menu-Edit-Insert template in the workspace?

**Comment by macrospecter** [comment]
Oh I'm sorry, I thought that I had replied to this. The issue with the stuck workspace is really causing a problem, because I can't use any templates. 

1. I can change which note is set as the workspace note, but I cannot altogether disconnect the workspace from a given note. This is a problem because I cannot use the workspace for any separate purpose; any time I edit it, it just edits the original note that is linked to the workspace (the workspace note and the original note that I set as the workspace note seem to be syncing). So it's just like having a regular item note in a separate tab. Maybe that's somehow useful for some users, but I didn't think that was the purpose of the workspace.

2. The fact that I can only insert templates into the workspace is the bigger problem, though I suspect it is related to the above. To insert a template, I am definitely not using the menu-Edit-Insert Template option, which explicitly says that it will insert the template in the workspace. Instead, I'm trying, within a given sidebar note, to use the option, which appears in the Better Notes-specific tool bar in the right sidebar, to Insert Template at Cursor. Whenever I do that, again within a specific note, it instead inserts the template into the workspace in a totally different tab (even if the tab is in the completely collapsed state). This only started once a note got stuck in the workspace in the first place.

**Comment by windingwind** [comment]
Well, the workspace is designed to contain (or connect to) a note item. I'm not sure what you want to do with a workspace without a note. The workspace does not provide any actual functionalities without a valid note.

The template you showed above is outdated and might not work for BN 1.0+, so if that template does not work, it might not prove anything. Please try this and see if this inserting template bug still happens: https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#import-note-template

**Comment by macrospecter** [comment]
Sorry for the delay on this. For reasons unknown to me, the error stopped occurring on one computer and then, about a week later, stopped occurring on the other. I was waiting to see if the correction was permanent and it seems to be. I'm still not sure what was happening. But I had tried your template and it didn't make any difference--initially, the error occurred with any template, and, eventually, it occurs with none of them. Thank you for your help!
