### ISSUE TITLE
[Bug] Issues with linked note text in Workspace Note (creation of duplicated block quotes and/or unexpected deletion of paragraphs)

### ISSUE THREAD

**Issue by Feli07notoldman** [windingwind/zotero-better-notes#549]
# Issues with linked note text in Workspace Note (creation of duplicated block quotes and/or unexpected deletion of paragraphs)

**Description of the bug**

Following unexpected behavior has been observed when working with note links in a workspace note:

    **Medium critical**: A linked note text in block quotes will unintentionally be displayed multiple time
    **Very high critical**: Paragraphs (or other note links) below the note link, which do not belong to the linked note text, may be deleted unexpectedly!

The bug may be also in normal notes when using note links and “Better notes” features.

**To Reproduce and Expected behavior**  
Steps to reproduce the behavior see below “Scenario…” and “Reproduce bugs ...”

**Desktop (details):**

1. Windows 10    
2. Firefox 114.0.2    
3. as well as in Zotero 6.0.26, Better notes 1.0.4    
4. and also in Zotero 7.0.0-beta.14+f1003a1d1 (32-bit), with Better Notes 1.1.14-0
    

## Scenario at start of evaluation the behavior of links , 4 links and 3 individually text lines by user

1-Lorem Ipsum (this is a link. In workspace note it is being displayed in blue color, underlined)

![Screenshot2](https://github.com/windingwind/zotero-better-notes/assets/138296531/107e8487-a85f-4443-a0a2-31344ff414f7)

## Reproduce bugs ...
(1) Try following with a brand new link to a note (demonstration of **expected** behavior):

1. Mark link with cursor (cursor is in between two letters!), show note text by clicking on icon 
   \-> text of linked note is being displayed    
2. Mark link with cursor (cursor is in between two letters!), hide note text by clicking on icon 
   \-> text of linked note is being undisplayed    
3. Repeat 1) and 2) which presents to user the expected behavior
    

---

![Screenshot](https://github.com/windingwind/zotero-better-notes/assets/138296531/951c234d-b442-4789-98c8-fff1c7d8894d)

(2) Try following with another brand new link to a note (demonstration of **unexpected** behavior - **medium criticality**):

1. Mark link with cursor (cursor is highlighting at minimum one ore more letters!), show note text by clicking on icon  
    \-> text is being displayed    
2. Mark same link with cursor (cursor is highlighting at minimum one ore more letters!), hide note text by clicking on icon  
    \-> **Bug:** text is being displayed multiple - **medium criticality**    
3. Repeat 2) which does not present to user the expected behavior.    
    **Bug**: It should not make a difference, whether user is marking a link by placing cursor between two letters, or I am highlighting one ore more letters (grey back ground) of the selected link. Highlighting of one or more letters may unintentionally occur, if user is moving mouse cursor towards the icon in “link menu”, while still keeping left mouse button pressed for a short while. This happened many times to me.
    

---
(3) Try following with another brand new link to a note (demonstration of **unexpected** behavior - **medium criticality**):

    Comment: Step 1. and 2. is a repetition of above scenario (2)  
    Step 3. and 4.  is different from above scenario (2)

1. Mark link with cursor (cursor is highlighting one ore more letters!), display note text by clicking on icon  
    \-> text is being displayed as first instance, as expected by user    
2. Mark same link with cursor (cursor is highlighting one ore more letters!) User tries now to remove note text by clicking on icon  
    \-> **Bug**: however, text is unexpectedly being displayed as a second instance - **medium criticality**    

3. Mark same link with cursor (cursor is in between two letters!), User tries now to remove one note text by clicking on icon  
    \-> Programm does not recognize, that link text has been already displayed yet.  
    \-> **Bug:** text is being displayed unexpectedly as a further instance (the 3rd one) - **medium criticality**  
     User expected that now at least one instance of displayed text would be removed, however, it does not.    
4. Mark same link with cursor (cursor is in between two letters!), hide note text by clicking on icon  
    \-> one text instance is being undisplayed now, the other ones remain    
    **Conclusion: Only a second try of this “remove process step” is successful.**    
    **Application of same process step 4. leads to a different behavior than in step 3**.
    

---
(4) Try following with another brand new link to a note, add two (2) manually created lines below the link to a note (demonstration of **unexpected** behavior - **very high criticality**):

1. Mark link with cursor (cursor in between two letters!), show note text by clicking on icon  
    \-> text is being displayed as expected by user    
2. Mark same link with cursor (cursor is highlighting one ore more letters!), hide note text by clicking on icon  
    \-> text is being undisplayed as a expected by user    
3. Mark same link with cursor (cursor in between two letters **or** cursor is highlighting one ore more letters!), now user expects text to be displayed when clicking on icon  
    \-> **Bug: text below of link is unexpectedly being deleted now - very high criticality**    
    This is a abnormal behavior of the program and results in user frustration, as manual entered text is being delayd which is not part of the link
    
4. **Bug: Repeating step 3. will delete consecutive text paragraph below of link - very high criticality**    
    That is very frustrating as any attempt of displaying the text of the linked note will just delete consecutive paragraph below the link. The workspace note will be destroyed more and more. The note has to be restored out of mind or from a healthy backup.

Best regards

**Comment by Feli07notoldman** [comment]
Additionally please find two screenshots which might support bug report
# Scenario (2)
![Screenshot3_Sc2](https://github.com/windingwind/zotero-better-notes/assets/138296531/bff6e2db-fae7-4954-a656-dae4dcb51249)

# Scenario (4)
![Screenshot4_Sc4](https://github.com/windingwind/zotero-better-notes/assets/138296531/68c812ba-2f85-48bd-8e35-6245bd455d34)

Best regards

**Comment by windingwind** [comment]
Sorry for the delay. I am too busy these days.

To clarify, this button is to `toggle` the link content, which means the first click will expand the content in the next line of the link (in block quote) and the second click will toggle it.

Ideally, users would expect it to `detect` if the following line of a link IS or IS NOT the link content. However, this is not possible for technical reasons.

So the workaround is when the link does not contain a flag `ignore=1`, the link is treated as `toggled`, and when there is the flag, the link is treated as `expanded`. And when we `expand` the link, actually we insert the note link content after the link line and mark the link as `ignore=1`; when we `toggle` the link, actually we *remove the following line* of the link and remove the flag `ignore=1` from the link.

So, this explains why you encounter this. There was a bug with the select - link update, causing the flag not recorded. Should have been fixed in 1.1.4-10.
