### ISSUE TITLE
救命哇！那个在笔记中直接引用参考格式文献的功能去哪了5555

### ISSUE THREAD

**Issue by cutebird00** [windingwind/zotero-better-notes#552]
如题如题！
我怎么找不到那个功能了救我，就是可以直接在笔记里写出参考格式文献的！
现在该在哪里找它呢

**Comment by yiqiaowang-arch** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/3a158ffc-3936-44af-a985-1b61444bceec)
你指的是不是这个功能？这应该是zotero笔记自带的功能，跟better notes似乎没有关系？

**Comment by yiqiaowang-arch** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/79b86fd3-740d-4e6c-a7f8-4b0ecdbe8ad4)
如果你指的是这个功能，至少我没有找到设置中有开/关这项功能的选项。
即使没有这个按钮，在文献里ctrl+C复制，然后在笔记里Ctrl+V粘贴，也可以达到自动插入citation的效果。（复制粘贴时插入引用，是zotero笔记的自带功能）

**Comment by cutebird00** [comment]
谢谢你！但我指的不是这两个功能，

**Comment by cutebird00** [comment]
谢谢你！但我指的不是这两个功能
![1688363895860](https://github.com/windingwind/zotero-better-notes/assets/138377212/ef8633be-360a-470c-b45b-31edd762c427)
你看，就是我之前在笔记中是可以直接插入这个的。但是我现在不知道如何实现这样的插入了。
![1688363940285](https://github.com/windingwind/zotero-better-notes/assets/138377212/f8cf986e-9064-4c7f-b824-54cac5c84e4c)
引用那里插入的只能是这样的，在看笔记的时候不是很方便，不能直接知道这个地方参考文章的题目和期刊55

**Comment by windingwind** [comment]
这个功能由于可以使用插入笔记模板达到同样的效果，不再专门设置按钮了

**Comment by cutebird00** [comment]
> 这个功能由于可以使用插入笔记模板达到同样的效果，不再专门设置按钮了

好的谢谢！我还没学会笔记模板怎么用😫，顺便我还想请问为什么复制的表格无法在笔记中粘贴呀？

**Comment by windingwind** [comment]
目前好像还没有这个模板，如果你需要可以提出具体的引文样式要求，我有空做一个。
富文本的表格是可以粘贴的我记得

**Comment by cutebird00** [comment]
> 目前好像还没有这个模板，如果你需要可以提出具体的引文样式要求，我有空做一个。 富文本的表格是可以粘贴的我记得
啊啊啊谢谢！非常感恩！我觉得原来那样就挺好的~有作者（前三就行）+标题+期刊+时间+DOI就很好啦！！

**Comment by mengcanzhai** [comment]
[https://github.com/windingwind/zotero-better-notes/discussions/569](url)
这个模板应该差不多符合你的要求了

**Comment by cutebird00** [comment]
> [https://github.com/windingwind/zotero-better-notes/discussions/569](url) 这个模板应该差不多符合你的要求了

非常感谢！！！

**Comment by lisasuosuo** [comment]
上面的模板链接关闭了

**Comment by mengcanzhai** [comment]
> 上面的模板链接关闭了

[https://github.com/windingwind/zotero-better-notes/discussions/569](https://github.com/windingwind/zotero-better-notes/discussions/569)
