### ISSUE TITLE
[Feature]请问可否给侧边栏的笔记加一个大纲的功能？

### ISSUE THREAD

**Issue by yzy1228682367** [windingwind/zotero-better-notes#554]
笔记太长的话，在侧边栏做笔记的时候不太方便，请问可否给侧边栏的笔记加一个大纲的功能呢？
![CleanShot 2023-07-04 at 15 15 35@2x](https://github.com/windingwind/zotero-better-notes/assets/50101175/5bfd8bea-0204-4b89-aadf-ba9a26e08fe1)

**Comment by gaofeng-lin** [comment]
我也正想说这个问题，希望能给条目笔记增加目录功能。笔记写的多，来回翻比较麻烦。希望可以增加这个功能。 @windingwind

**Comment by Donnie-L** [comment]
是的，很需要这个功能。因为习惯边阅读pdf边在侧栏记笔记，而且一个专题只用一个独立笔记，很容易笔记就很长了，如果没有目录，翻阅很不方便。

或者在工作区的阅览，是否可以直接阅览pdf，现在好像只能预览别的笔记，不能阅览pdf。

**Comment by RTcui** [comment]
同求此功能

**Comment by xjtusjtu** [comment]
同样希望此功能！恳求开发者大佬考虑！
