### ISSUE TITLE
[Change note title] 

### ISSUE THREAD

**Issue by thams86** [windingwind/zotero-better-notes#555]
**Is your feature request related to a problem? Please describe.**
I would like to change the automatic title that comes when we ask to add notes from annotations. Right now I'm doing it manually.
#Annotations  (04/07/2023, 08:34:00)#
#Author last name + year Note 04/07/2023 #

**Describe the solution you'd like**
I want my notes from my pdf annotations to come with the title: 
#Author(s) last name + year Note 04/07/2023 #

**Describe alternatives you've considered**
I've tried to change it myself by accessing the Config Editor, but I was not sure which code to change

**Additional context**
When dealing with multiple sources it is hard to switch from one note to the other and know right away which note belongs to which paper. This would help my organization

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#builtin-templates

The quick note template might be what you are looking for
