### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by yushi1985** [windingwind/zotero-better-notes#556]
**Describe the bug**
mac版无法导出笔记，导出界面所有选项都无法选择，没有复选框可点，插件已更新至1.0.4版，zotero版本号为6.0.26

**Screenshots**
<img width="332" alt="截屏2023-07-05 下午10 22 02" src="https://github.com/windingwind/zotero-better-notes/assets/138691778/6d878b83-6c93-4cc4-80a0-b430fbc85411">
 已安装插件如图：
<img width="1111" alt="截屏2023-07-05 下午10 25 43" src="https://github.com/windingwind/zotero-better-notes/assets/138691778/a767948b-9dfa-421f-aaf6-2c363bfac31d">
<img width="1111" alt="截屏2023-07-05 下午10 25 47" src="https://github.com/windingwind/zotero-better-notes/assets/138691778/9f7a2e80-0a58-4a80-91fd-7b7dd0bf28b6">

**Additional context**

**Comment by bzwierz** [comment]
I'm facing similar problem on Fedora 38 (Linux). I have all the checkboxes available, but the extensions do not export any files format.

**Comment by windingwind** [comment]
@yushi1985 Please drag the window border to make the window larger. Does the checkbox show up?

@bzwierz Any screenshots or descriptions of your export options? And what is your Zotero version? The 7 beta is not able to do printing and thus exporting PDF is not available, at least for now.

**Comment by yushi1985** [comment]
> @yushi1985 Please drag the window border to make the window larger. Does the checkbox show up?
> 
> @bzwierz Any screenshots or descriptions of your export options? And what is your Zotero version? The 7 beta is not able to do printing and thus exporting PDF is not available, at least for now.

I try. But It doesn't show up.

**Comment by windingwind** [comment]
@yushi1985 Please provide the debug output: Menu-Help-Debug Output-View

**Comment by bzwierz** [comment]
> @bzwierz Any screenshots or descriptions of your export options? And what is your Zotero version? The 7 beta is not able to do printing and thus exporting PDF is not available, at least for now.

I'm on 6.0.13. 
![obraz](https://github.com/windingwind/zotero-better-notes/assets/82037159/18dd1a8c-570e-4577-a24c-ba836d25ed35)
![obraz](https://github.com/windingwind/zotero-better-notes/assets/82037159/041762d0-80be-44df-ad95-65a1bbfb7675)
"Otwórz" means "Open" in polish, so it doesn't even give me any option to save markdown files.

**Comment by bzwierz** [comment]
> @bzwierz Any screenshots or descriptions of your export options? And what is your Zotero version? The 7 beta is not able to do printing and thus exporting PDF is not available, at least for now.
I'm on 6.0.13. 

"Otwórz" and "Zapisz" means "Open" and "Save" respectively. Disabling save changes "Open" in file manager to "Save", but even then the file isn't saved in the desired location. 
![Zrzut ekranu z 2023-07-07 12-42-30](https://github.com/windingwind/zotero-better-notes/assets/82037159/12d83310-b233-486d-9c9b-ab46c9c441b5)
![Zrzut ekranu z 2023-07-07 12-42-50](https://github.com/windingwind/zotero-better-notes/assets/82037159/cf619010-1691-4b68-9781-e045f87f37a4)
The same happens when exporting directly from Note Workspace.

**Comment by windingwind** [comment]
Hi @bzwierz ,

To clarify, it's `open` because you checked the `Set Auto-Sync`. In that case, you are asked to choose in which directory the files will be synced and the note you want to sync along with its sub-notes(linked notes) will all be synced to that directory.

But no md file is apparently a bug. Please provide the debug output: Menu-Help-Debug Output-View

**Comment by bzwierz** [comment]
`
[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "TypeError: Zotero.File.normalizeToUnix is not a function" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/bootstrap.js -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/index.js" line: 12854}]

Security Error: Content at moz-nullprincipal:{4265db80-29db-4b59-a6d5-4d468f5f643a} may not load or link to chrome://betternotes/content/treeView.html.

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "TypeError: Zotero.File.normalizeToUnix is not a function" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/bootstrap.js -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/index.js" line: 12854}]

[JavaScript Error: "TypeError: Zotero.File.normalizeToUnix is not a function" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/bootstrap.js -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/index.js" line: 12854}]

[JavaScript Error: "TypeError: Zotero.File.normalizeToUnix is not a function" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/bootstrap.js -> jar:file:///home/bzwierz/.zotero/zotero/fatv8fgu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/index.js" line: 12854}]

version => 6.0.13, platform => Linux x86_64, oscpu => Linux x86_64, locale => pl-PL, appName => Zotero, appVersion => 6.0.13, extensions => ZotFile (5.1.2, extension), Zotero LibreOffice Integration (6.0.0.SA.6.0.13, extension), Sci-Hub Plugin for Zotero (1.4.4, extension), Mdnotes for Zotero (0.2.3, extension), Better BibTex for Zotero (6.7.93, extension), Zotero Better Notes (1.0.4, extension)
`
Thank you for your help!

**Comment by windingwind** [comment]
Oh no, this is so weird. A Zotero's built-in function is missing and thus you failed to export the note. Could you please try to disable all other plugins and try again? This should not be possible to happen...

**Comment by windingwind** [comment]
OK, I find out why. You are running Zotero 6.0.13 which is a relatively old version. Please update your Zotero.

**Comment by bzwierz** [comment]
Yes, that was the problem - rpm (native Fedora package) hasn't been updated in a while, flatpak version works without problem. Thank you once again!

**Comment by LamFTS** [comment]
I am a linux user, I encounter the same problem that note can't be export properly event though there was a windows prompt to ask me to select the location for saving, but nothing happen after click "save". My zotero is the latest version (6.0.26). here are the debug information:
```

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://lamfts%40hotmail%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://lamfts%40hotmail%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///home/lamfts/.zotero/zotero/6kpjvsqu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

version => 6.0.26, platform => Linux x86_64, oscpu => Linux x86_64, locale => zh-CN, appName => Zotero, appVersion => 6.0.26, extensions => Tara (0.0.3, extension), Del Item With Attachment (0.1.06, extension), Zutilo Zotero 工具箱 (3.10.0, extension), ZotFile (5.1.2.999, extension), Zotero Tag (0.3.0, extension), Storage Scanner for Zotero (5.0.12, extension), Zotero PDF Preview (0.3.7, extension), Mdnotes for Zotero (0.2.3, extension), Chartero (1.3.2, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.26, extension), Zotero Citation (0.3.1, extension), Jasminum (0.2.6, extension), Zotero Better Notes (1.0.1, extension), ZotCard (2.8.1, extension), Zotero Style (2.6.7, extension), Zotero PDF Translate (1.0.24, extension), Better BibTex for Zotero (6.7.94, extension), Green Frog (0.13.0, extension, disabled), Night for Zotero (0.4.23, extension, disabled)
```

**Comment by yushi1985** [comment]
> 
```
(3)(+0164303): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000004): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0001260): [Warning] Creating element title with no namespace specified. Found multiply namespace matches.

(3)(+0000004): {}

(3)(+0000004): [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000003): {}

(3)(+0000007): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000003): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000003): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000000): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000003): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000002): {}

(3)(+0000003): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000002): {}

(3)(+0000001): {}

(3)(+0000005): {}

(3)(+0001643): itemTree.render(). Displaying Item Tree
```
是这个内容吗？

**Comment by windingwind** [comment]
The Z6 version is not maintained. Any bugs that are only related to the Z6 version plugin will not be resolved.
