### ISSUE TITLE
工作区笔记能否增加快速改变字体颜色、高亮的方式，比如快捷键？

### ISSUE THREAD

**Issue by 56125a** [windingwind/zotero-better-notes#559]
感谢您的插件，非常实用。
在工作区笔记中高亮某段文字或者更改某些字体颜色需要通过 选中文本—选择工作区图标—选择颜色 进行，能否使这个步骤像markdown语法，通过输入特定的标记使字体改变颜色或高亮，比如：<span style="background-color: #5fb23680">highlighted<span>？
或者增加其他更加简便的方法？
再次感谢您。

**Comment by windingwind** [comment]
感谢建议。此类属于笔记的基础功能，不计划包含在本插件中，请谅解。高亮并非md的原生语法。

**Comment by xiaoxiang01a** [comment]
@56125a ，与题主需求相同，另辟蹊径弄了个quicker动作实现了该功能
可以给动作绑定自定义快捷键，[zotero工作区笔记高亮-quicker](https://getquicker.net/Sharedaction?code=4fb7800e-930c-4c1d-9271-08dd1cff887f)
