### ISSUE TITLE
[Feature] Syncing Better Notes across devices?

### ISSUE THREAD

**Issue by macrospecter** [windingwind/zotero-better-notes#560]
I'm not sure if this is a feature request, or if it already exists. Is it possible to use Better Notes markdown syncing on multiple devices? That is, can I export/auto-sync a note to Obsidian on my work computer and then change the note in Zotero on my home computer and have those changes sync to Obsidian? I have searched the forums/documentation and did not see this mentioned directly (sorry if I missed it), but some comments seem to imply that it is not possible.  

I understand that as long as I make the changes in Obsidian, they will sync back to Zotero on all computers (because my Obsidian notes are synced). But it sounds like, if Better Notes itself cannot sync across devices, this will severely limit my ability to make changes to notes _within_ Zotero; I will have to keep track of which notes I exported at home and which I exported at work, and then only change each note on the appropriate computer. 

Thank you!

**Comment by windingwind** [comment]
The syncing only happens on your current device and where/which note to sync is stored locally.

The notes in Zotero are controlled by the syncing system of Zotero, which can be synced across devices.

We could support syncing the whole collection to a folder, which might fulfill your need here, but at least it is not available for now.

**Comment by davidoskky** [comment]
You can do this already using the zotero [sync](https://www.zotero.org/support/sync) mechanism. This is how I do it. However, you'll have to make sure you open zotero and complete the online sync and the following better notes exportation before you start modifying the document externally or you will get two notes with different contents.

**Comment by macrospecter** [comment]
Thanks, @windingwind. This would be a great feature! Especially if a user may be changing work locations/computers in future, it would be useful to have more portability for the sync settings/controls. It's also a bit hard for me when I'm first starting out with the plugin because some of my notes are originally synced on one machine, and others on another--so I can't control the syncing all in one place. But for now, at least, the ability to sync the note content themselves across devices is working and a fabulous feature of Better Notes.

**Comment by macrospecter** [comment]
Thanks, @davidoskky. I think, though, that Zotero sync only syncs the note contents and not the Better Notes plugin information. What that means is that it's not possible to control the *fact of the sync* of a note from more than one machine (e.g., you can't check or end the sync/check when the last sync occurred). At least that's what it sounds like above from the developer's comment, and has been my experience.
