### ISSUE TITLE
[Feature] Import images linked in external file

### ISSUE THREAD

**Issue by davidoskky** [windingwind/zotero-better-notes#565]
**Is your feature request related to a problem? Please describe.**
I often edit notes externally in obsidian. Generally I add all the images I need in Zotero and then move them around the text as needed, however sometimes I forget about it and add them through obsidian.
Whenever I do that, the note cannot be synced and an error is produced in Zotero; so that I have to remove the image from obsidian and then add it back in Zotero.

**Describe the solution you'd like**
During the synchronization, Better Notes should find new images and import them into the collection to add them to the note.

**Comment by windingwind** [comment]
Currently (and probably always) only standard markdown image are accepted and can be synced into Zotero note: `![title](/path/to/image.png)`

**Comment by davidoskky** [comment]
I have tested with standard markdown: there is no problem with synchronization, however the image appears as unknown on Zotero.
I have tried both with relative and full path.
