### ISSUE TITLE
[Bug] Syncing md leads to data-looses with using ---

### ISSUE THREAD

**Issue by JOOmsH** [windingwind/zotero-better-notes#567]
The initial markdown export replaces all horizontal lines "---" with "***". However, most md-prettier replace it backwards with "---". After re-syncing with Zotero, all data up to the last “---” in the MD file will be erased without warning. It's not the expected behavior.

```md
---
tags: []
Parent: ""
Collections: []
version: 0
Library ID: 1
itemKey: XXDKUJMC
---
[//]: # (will be deleted!)
Important notes
---
More notes
```

**Comment by windingwind** [comment]
fixed in 1.1.4-13
