### ISSUE TITLE
[Bug] Adding multiple times 'Resize Image'

### ISSUE THREAD

**Issue by JOOmsH** [windingwind/zotero-better-notes#568]
Right click on an image and each time you hover over an advanced option a new "Resize Image" will be added.

![image](https://github.com/windingwind/zotero-better-notes/assets/52428904/0bbdf575-42ed-43fa-864b-59731482d6bc)

**Comment by windingwind** [comment]
A known issue. Thanks for reporting.

**Comment by windingwind** [comment]
fixed in the latest prerelease on zotero 7.
