### ISSUE TITLE
无法直接在阅读页面将笔记链接到工作区笔记

### ISSUE THREAD

**Issue by qwpyyx** [windingwind/zotero-better-notes#570]
版本为7.0.0-beta，betternote版本为1.1.4-0。
问题：
之前可以直接在阅读页面进行标注，出现左边的注释栏后可以快速链接到笔记工作区的相关位置，现在这个操作弄不了了。只能在阅读页面标注后，返回到笔记工作区再添加一次，请问这是什么原因？感谢
以前可以直接这样：
![image](https://github.com/windingwind/zotero-better-notes/assets/43367931/1bc25b95-06d0-4eda-952f-38656aa1fe26)

现在只能这样操作：
![image](https://github.com/windingwind/zotero-better-notes/assets/43367931/5c5e5430-80f8-4714-8297-c5efb4070c27)

**Comment by windingwind** [comment]
请尝试最新版。此处关闭
