### ISSUE TITLE
请问通过标签添加双链的功能是没有了吗？

### ISSUE THREAD

**Issue by Tommy0712** [windingwind/zotero-better-notes#571]
您好，现在在PDF阅读界面高亮文字之后对其**为笔记或批注加上以#开头且与主笔记中节标题相同的标签时，会自动将该内容（笔记或批注）加入主笔记。**这个功能是取消了吗？是否有其他的方法对这些比较细粒度的笔记添加双链，复制黏贴有些麻烦，之前看到重要的内容加上标签就可以链接到主笔记提纲对应的位置，这个功能非常实用。
<img width="664" alt="屏幕截图 2023-07-13 203346" src="https://github.com/windingwind/zotero-better-notes/assets/104200182/0aeab2ef-a062-470e-b697-c66d0e80440a">
现在添加“#＋标题”之后在主笔记中未链接。

**Comment by windingwind** [comment]
是的。

**Comment by Tommy0712** [comment]
请问后期还会考虑加上吗？还是说只能用老版本插件呢？

**Comment by windingwind** [comment]
不考虑加上，没时间精力维护这些细节功能。
