### ISSUE TITLE
TopItem is not defined 

### ISSUE THREAD

**Issue by wangchunlin** [windingwind/zotero-better-notes#579]
## Template Type

Item, Note, Quick Import, Quick Insert, ...

## Desired Template Performance

Describe what you want.
当导入自定义模板到笔记区，遇到了这个 ‘Refereceerror: topitem is not defined’ 请问如何解决？
## Current Template
![image](https://github.com/windingwind/zotero-better-notes/assets/12987646/cd116576-0005-4bec-97d1-85a7ccf59b06)

```js
// Paste your template here
```

<h1><span>&lt;笔记标题&gt;</span></h1>\n
<hr/>
</span></h1>\n <h2 style="color: #1B5E20; background-color:#F1F8E9;">💡 Meta Data
</h2>
<table>
    <tr>
        <th style="background-color:#dbeedd;"><p style="text-align: right">Title </p></th>
        <td style="background-color:#dbeedd;"> ${topItem.getField('title')}</td>
    </tr>
    <th style="background-color:#f3faf4;"><p style="text-align: right">Journal </p></th>
    <td style="background-color:#f3faf4;"> ${topItem.getField('publicationTitle')}&nbsp;<em>(${topItem.getField('DOI')})</em>
    </td>
    </tr>
    <tr>
        <th style="background-color:#dbeedd;"><p style="text-align: right">Authors </p></th>
        <td style="background-color:#dbeedd;"> ${topItem.getField('authors')}</td>
    </tr>
    <th style="background-color:#f3faf4;"><p style="text-align: right">Pub.date </p></th>
    <td style="background-color:#f3faf4;"> ${topItem.getField('date')}</td>
</table>
</span></h1>\n <h2 style="color:  #E65100; background-color:  #FFF8E1;">📜 研究背景 & 基础 & 目的</h2>
<hr/>
<p></p>
</span></h1>\n <h2 style="color:#2E7D32; background-color:    #F1F8E9;">&#x1F4CA 研究内容</h2>
<hr/>
<p></p>
</span></h1>\n <h2 style="color:#4A148C; background-color:    #F5F5F5;">🚩 研究结论</h2>
<hr/>
<p></p>

</span></h1>\n <h2 style="color: #006064; background-color:   #E0F7FA;">📌 感想 & 疑问</h2>
<hr/>
<p></p>
</span></h1>\n <h2 style="color:#1565C0; background-color:   #E1F5FE;">🔬 理论推导</h2>
<hr/>

**Comment by netgrims** [comment]
I actually experience the same problem. Many of the templates are not working because of this. Am I doing something wrong, is the template outdated, or is there some other issue?

**Comment by windingwind** [comment]
do a search before asking.

**Comment by crl7923** [comment]
我是在链接条目笔记和主笔记时遇到了这个问题，请问您解决了吗，怎么解决呀？
