### ISSUE TITLE
模板能否备份或导出？

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#580]
### Discussed in https://github.com/windingwind/zotero-better-notes/discussions/395

<div type='discussions-op-text'>

<sup>Originally posted by **Aren-py** March 17, 2023</sup>
应用场景：将A电脑中的模板备份或导出，然后导入新的B电脑。目前能备份的插件如tara，无法将bn的模板进行备份，不知道可有其他办法？</div>

**Comment by MuiseDestiny** [comment]
BN的模板数据应该存在prefs.js，
可否使tara可以把prefs.js也备份了，这样很多插件的设置都可以同步了。只是同一个prefs.js我不确定是否能同时应用于两台设备环境。可能还需要一些细节处理。

这样好处是不仅解决BN的模板备份，会让tara的功能更强大。

**Comment by windingwind** [comment]
Release 1.1.4-2
