### ISSUE TITLE
[Bug] "outline is empty" in the main note

### ISSUE THREAD

**Issue by compegant** [windingwind/zotero-better-notes#582]
**Describe the bug**
The outline shows error, but the mind map works well.

**Screenshots**
<img width="625" alt="iShot_2023-07-21_16 44 50" src="https://github.com/windingwind/zotero-better-notes/assets/39365278/1c958389-b33a-4579-b6fa-1d5461911d26">

![2471689924106_ pic](https://github.com/windingwind/zotero-better-notes/assets/39365278/ecc92169-dce8-48e2-b6c7-903698e44f53)

**environment**
Better note version 1.0.4
Zotero version 6.0.26

**Comment by windingwind** [comment]
Please ensure that you have included at least one H1 heading line.
