### ISSUE TITLE
[Bug]使用模板创建新的笔记后，思维导图显示有错误

### ISSUE THREAD

**Issue by QingYu-sunshine** [windingwind/zotero-better-notes#586]
如图所示，使用模板创建新的笔记后，思维导图显示不全，导致创建笔记后无法直接将新的笔记链接到该笔记中的某些项目中

![image](https://github.com/windingwind/zotero-better-notes/assets/123077881/6154291a-5ddd-4fb7-9c91-b745a73b7a81)

经过我的实验，在该笔记中任意一行中随便改动一下就可以使思维导图显示正常。如下图所示，我随便找了一个地方打了一个空格，再点击空白处，就正常了。
![image](https://github.com/windingwind/zotero-better-notes/assets/123077881/8456135e-5f75-4d21-8d59-c5d8bba91d92)

**Comment by windingwind** [comment]
模板直接将标题赋予颜色，因此导致无法识别。修改后自动保存时，标题颜色转换为标题内的带颜色文本，因此正常识别。应请求模板来源修改模板，不是bug
