### ISSUE TITLE
[Bug]ZoteroGPT malfunctioning and lag | 插件zoteroGPT不正常出现并且卡顿

### ISSUE THREAD

**Issue by minghaoguo20** [windingwind/zotero-better-notes#589]
**Describe the bug**
In notes, zoteroGPT often appears inexplicably.
When I want to write a heading, I enter three # followed by a space key. At this moment, the note freezes for about 1-2 seconds, and then zoteroGPT randomly appears. However, I do not want zoteroGPT to appear at that time, nor do I want zotero to freeze for a few seconds just because of a space key.
When I want to write a list, I enter a -, followed by a space key. At this moment, the note freezes for about 1-2 seconds.
在笔记中，zoteroGPT经常无缘无故出现。
当我想要写一个标题的时候，我输入3个#，紧接着按下空格键。这个时候笔记卡死大概1-2秒，然后zoteroGPT随机出现。但我并不希望zoteroGPT这个时候出现，也不希望zotero仅仅因为一个空格键就卡死几秒钟。
当我想要写一个列表的时候，我输入-，紧接着按下空格键。这个时候笔记卡死大概1-2秒。

**To Reproduce**
Refer to the description in "Describe the bug."
参考Describe the bug中的描述

**Expected behavior**
I hope to be able to customize the keyboard shortcuts for switching ZoteroGPT.
Or customize whether to enable the use of ZoteroGPT.
In fact, I don't use ZoteroGPT in my notes at all, except when I'm writing a paper. When I need ZoteroGPT, I will open the corresponding paper's page and use it there, which is more convenient.
我希望可以自定义切换zoteroGPT的快捷键。
或者自定义是否开启zoteroGPT的使用。
事实上，除了撰写论文的时候，我根本不会在笔记中使用zoteroGPT。当我需要zoteroGPT的时候，我会打开对应论文的页面，在那里用更方便。

**Screenshots**
<img width="1335" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/69155059/29238306-9b44-4f78-b8f7-9778f535a793">

**Desktop (please complete the following information):**
- MacBook Air M2 16+512
- macOS 13.4
- Zotero 6.0.26

**Comment by windingwind** [comment]
please report to zotero-gpt

**Comment by minghaoguo20** [comment]
> please report to zotero-gpt

But...
Why do I need to report to zoteroGPT?
Isn't this a setting in the notes?
Isn't the space key triggering zoteroGPT part of the notes' configuration?
为什么需要报告给zoteroGPT？
这难道不是note中的设置吗？
空格键触发zoteroGPT不是note的设定吗？

**Comment by windingwind** [comment]
no
