### ISSUE TITLE
快速切换工作区笔记[Feature]

### ISSUE THREAD

**Issue by WangYe661** [windingwind/zotero-better-notes#590]
**Is your feature request related to a problem? Please describe.**
在工作时需要将内容汇总到不同的工作区笔记中
**Describe the solution you'd like**
在某一个版本中有快速切换工作区笔记的功能，希望该功能回归

**Describe alternatives you've considered**

**Additional context**

**Comment by windingwind** [comment]
zotero7 & plugin prerelease
