### ISSUE TITLE
[Bug]betternotes 与translate，style插件冲突问题

### ISSUE THREAD

**Issue by RTcui** [windingwind/zotero-better-notes#591]
**Describe the bug**
1. 冲突一：与style   
   打开betternotes后，style插件提供的标签和#标签都显示为空，禁用后恢复正常【刚更新notes插件时没问题，今天打开突然出现问题】 详见下面链接 https://github.com/MuiseDestiny/zotero-style/issues/522#issue-1825582067

2. 冲突二：与translate 
  标题翻译错误，并且无法使用，禁用betternotes后恢复正常。

**Expected behavior**
希望得到开发者恢复并解决，谢谢。

**Screenshots
<img width="431" alt="搜狗截图20230728101530" src="https://github.com/windingwind/zotero-better-notes/assets/103620369/9a486383-934b-4430-a4ec-fb7297a6e707">

<img width="166" alt="搜狗截图20230728103916" src="https://github.com/windingwind/zotero-better-notes/assets/103620369/407b23fd-fbcd-467d-8844-df5702c8e3bd">

**

**Desktop (please complete the following information):**

- OS: [win11]
- Zotero Version(6.0.26)
- Version [zotero-better-notes1.0.4]

**Comment by windingwind** [comment]
不再维护z6版本插件
