### ISSUE TITLE
The add-on "%S" could not be installed. It may be incompatible with this version of Zotero

### ISSUE THREAD

**Issue by debinz** [windingwind/zotero-better-notes#593]
我试图安装这个最新插件，发现最新版本的插件（Release 1.1.4-4）似乎与最新版本的Zotero（6.0.26）不兼容？不知道能不能解决这个问题？🙇‍非常感谢
![image](https://github.com/windingwind/zotero-better-notes/assets/24296206/54332aa7-5d92-4b53-8f1c-a93a96394c2a)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes#-install

**Comment by fisherchase** [comment]
做一下补充，点击作者给的说明链接之后，在 Install - More Versions中选择适合zotero 6.0的版本即可；
（因为我自己一开始没注意到）
