### ISSUE TITLE
obsidian zotero双向同步错误。导出笔记的时候，提示错误win5

### ISSUE THREAD

**Issue by a1576799** [windingwind/zotero-better-notes#594]
在点击export后，导出笔记。
![image](https://github.com/windingwind/zotero-better-notes/assets/18475748/27bdd6f1-12a0-4993-8d81-1f12981fb965)

通过obsidian可以打开这个md笔记，格式都是对的。

但是如果在obsidian修改该笔记后，然后关闭该笔记。

回到zotero点击sync会出现一下提示：

![image](https://github.com/windingwind/zotero-better-notes/assets/18475748/103d2d4d-b0d9-4ff6-9031-8b8aaf3401dd)

查看sync界面，会发现同步时间是错的，而且不知道为什么有的路径是斜杠，有的是反斜杠。

![image](https://github.com/windingwind/zotero-better-notes/assets/18475748/0bcab692-b370-4e97-b109-a6f32d0691c7)

请问有木有朋友知道该如何解决这个双向同步的错误？ 

谢谢

**Comment by a1576799** [comment]
另外，有没有办法可以修改导出路径。因为现在每次都是需要重新导出一遍，很费事

**Comment by IzabelleFagundes** [comment]
same error here when the note have images. What might I be doing wrong?
