### ISSUE TITLE
Add notes repeatedly in specific situations

### ISSUE THREAD

**Issue by fengyelai** [windingwind/zotero-better-notes#6]
![image](https://user-images.githubusercontent.com/33919191/167770015-4f1ecbf2-7b74-4ef0-b086-19928528fd69.png)
After finishing the notes extracted to k4z at one time, delete the automatically generated entry notes (on the right) and completely delete them in the recycle bin. Click the Yellow Icon in the notes (on the left) again. Each click will generate an entry note and add a note link

**Comment by windingwind** [comment]
The link here is for re-open the note created from this annotation.

I don't see why you want to delete a note and re-create it repeatedly.

**Comment by windingwind** [comment]
I'll close this issue. Feel free to open it again.
