### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kuangyan-zyy** [windingwind/zotero-better-notes#600]
windows11 22H2
zotero7.0.0-beta.26+6dcc70f53 (64-bit)
插件版本:1.1.4-4
问题：笔记导出PDF或者word等文件时，找不到导出的文件在哪里，只能通过zotero打开笔记源文件，而不是在其他阅读器里打开导出后的PDF或者在office中打开word。不确定是不是我对插件的导出功能理解有误，还望解答。

**Comment by Kuangyan-zyy** [comment]
已确认导出时选择的是插件自己的导出，而不是zotero的导出。

**Comment by 1tonsilla** [comment]
https://github.com/windingwind/zotero-better-notes/issues/604#issue-1837844997
我也遇到这个问题了，另外请问图片是如何同步的，目前好像只能同步文字（因为是zotero自带的同步功能）

**Comment by windingwind** [comment]
see #604. close here.
