### ISSUE TITLE
Zotero6.0.26插入模板无响应[Note Template]

### ISSUE THREAD

**Issue by EdwardGiao** [windingwind/zotero-better-notes#601]
## Template Type

Item, Note, Quick Import, Quick Insert, ...

## Desired Template Performance

Describe what you want.

## Current Template

```js
// Paste your template here
```
**如图**
![GIF 2023-8-3 16-15-24](https://github.com/windingwind/zotero-better-notes/assets/92902985/83dc2866-14f7-48eb-9278-f6a6e30f001c)

**Comment by windingwind** [comment]
如图所示，插入到了工作区笔记。请检查工作区笔记。
