### ISSUE TITLE
[Bug] Notes have started syncing with ".md?" rather than ".md" in file name

### ISSUE THREAD

**Issue by macrospecter** [windingwind/zotero-better-notes#602]
I have been using a custom template for my file name (see screenshots below). It worked great for a couple of weeks--until yesterday. It is now has two problems: (1) it is failing to pick up the "cite key" field and (2) it is saving files as .md? rather than .md, which makes them unreadable in my markdown editor. I changed the template to collect the title field rather than cite key, and then it retrieves that field correctly, but it still saves the file as .md?. 

I am on Zotero 6, BN 1.0.4; I did not do any updates yesterday or in the days leading up to it.

I'm attaching some screenshots. 

A. The template (and preview of the file name for a specific note) I've been using, which used to capture the citekey field

![Screenshot 2023-08-03 at 9 23 02 AM](https://github.com/windingwind/zotero-better-notes/assets/136653833/fc2cb450-29a3-40d0-9264-9d34f37083a4)

B. The same template (and preview of the file name for a specific note), modified to capture the title field

![Screenshot 2023-08-03 at 9 23 19 AM](https://github.com/windingwind/zotero-better-notes/assets/136653833/ba6d9acb-d6d1-42d7-958c-5b5c22ee2323)

C. The files after export as they appear in Finder

![Screenshot 2023-08-03 at 9 26 36 AM](https://github.com/windingwind/zotero-better-notes/assets/136653833/c9d6bef1-facc-426b-96fe-a3ac62e64b1e)

Would appreciate any help!

**Comment by macrospecter** [comment]
Just an update on this: Better Notes has basically become unusable for me given this issue, so I tried updating to Zotero 7. However, the problem persists. 

Since I do not see others having this problem, I assume it is something in my setup. I tried uninstalling and reinstalling Better Notes, but all my settings seem saved. Could anyone tell me how to do a full uninstall? Thank you!

**Comment by windingwind** [comment]
Preferences are persisted even if plugins are deleted/disabled. You can reset a note template, e.g. the ExportMDFileNameV2, by clicking `reset` or `options > reset` and then `save` in the template editor.

**Comment by windingwind** [comment]
BTW, are any other programs creating temp files ending with `?`? Like some obsidian plugins cache the markdown file to `md?` temporarily but which is later recognized as the syncing target by better notes.

You may also try to clear the syncing in Tools > Sync manager and set up syncing again outside the obsidian folder to see what will happen.

**Comment by macrospecter** [comment]
Yes, I've reset (and changed) my file name template multiple times, but the problem persists. 

I've also restarted Obsidian in safe mode (no plugins active) and the problem persists. I've also disabled all plugins on Zotero's side (other than BN) and the problem persists.

I've also tried exporting outside of the Obsidian folder (to Desktop) and the problem persists. 

If it might be helpful, I noticed that the problem started on one of my machines and did not begin happening on the other machine until about 24-48 hours later. 

Do you know if there's a Better Notes preferences file that I could delete to try to reboot my settings?
