### ISSUE TITLE
[Bug]pdf和word导出失败

### ISSUE THREAD

**Issue by 1tonsilla** [windingwind/zotero-better-notes#604]
**Describe the bug**
点击导出pdf、导出word 均失败，只有导出md成功。

**To Reproduce**
版本号：zotero 7 beta 28
插件号：1.1.4-3和1.1.4-4均无法导出

具体情况请看截图，可能更清楚：
word无法导出：1.1.4-4点导出会跳出来保存框，点保存，但是其实并没有保存下来。1.1.4-3是一样的bug
pdf无法导出：1.1.4-4点导出会闪现一个窗口，然后自动关闭该窗口。 1.1.4-3点导出会跳出上述窗口，但不会关闭

**Screenshots**
![image](https://github.com/windingwind/zotero-better-notes/assets/33661246/523b4ebd-4add-419c-95ec-0e1d236b6560)
![image](https://github.com/windingwind/zotero-better-notes/assets/33661246/4fd6bee1-1de4-40eb-9686-8a41bb36662a)

谢谢！

**Comment by windingwind** [comment]
Yes, it's a known issue. thanks for letting me know.

**Comment by MZGuo111** [comment]
请问修复了吗？我使用mac版也是同样的问题，导出md正常，导出pdf点击后直接没有反应
