### ISSUE TITLE
在右侧主笔记编辑窗口中，选中某一行文字进行降低或者提升标题层级容易发生错乱，比如提升了上一个标题的层级[Bug]

### ISSUE THREAD

**Issue by LIKAISAA** [windingwind/zotero-better-notes#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
由于该功能较少使用，已在近期版本移除，将关闭。
