### ISSUE TITLE
[Bug] 笔记双向同步或者导出成markdown时会出现大量的反斜杠

### ISSUE THREAD

**Issue by xh542428798** [windingwind/zotero-better-notes#614]
多次修改后，会把一些obsidain的语法给反斜杠掉，比如callout，不知道这是什么历史原因？
希望能够再导出后，做一步删除反斜杠的操作

![image](https://github.com/windingwind/zotero-better-notes/assets/49368033/0a610398-8c31-4873-95e5-a0f5a10edc8d)
![image](https://github.com/windingwind/zotero-better-notes/assets/49368033/e9b85d95-a528-4ebc-9548-36d71bcfb234)

**Comment by xh542428798** [comment]
mdnotes的导出功能可以去除大部分html标签，是否可以借鉴过来呢

**Comment by windingwind** [comment]
callout等任何非标准markdown语法不会被识别。所有markdown中涉及的纯文本中的语义字符（_*-[]等)都会按照markdown标准进行转义。

**Comment by windingwind** [comment]
html标签是为了同步功能而特意按特定格式保留的。

**Comment by wyy-yiyang** [comment]
zotero 7.0.0-beta.66+d0299a1ac，Better Notes for Zotero 1.1.4-beta.57。笔记中“[”输出markdown文件时为“\[”，请问如何修改？
<img width="351" alt="Snipaste_2024-03-18_17-09-30" src="https://github.com/windingwind/zotero-better-notes/assets/59425079/3bedc86a-a4da-4c9c-b636-047a7f02e2a1">

**Comment by wyy-yiyang** [comment]
> callout等任何非标准markdown语法不会被识别。所有markdown中涉及的纯文本中的语义字符（_*-[]等)都会按照markdown标准进行转义。

zotero 7.0.0-beta.66+d0299a1ac，Better Notes for Zotero 1.1.4-beta.57。笔记中“[”输出markdown文件时为“\[”，请问如何修改？
