### ISSUE TITLE
[Feature] 每次打开工作区，大纲、主笔记和预览三个模块的大小都要重新调整，希望能更新下记忆功能，省得每次都得调

### ISSUE THREAD

**Issue by EdwardGiao** [windingwind/zotero-better-notes#62]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xianchengyue** [comment]
预览区是空白的怎么解决呢？

**Comment by windingwind** [comment]
空白预览是因为没有打开笔记链接。记忆功能暂时不支持
