### ISSUE TITLE
文本格式和高亮等常用 可以增加快捷键提示吗？

### ISSUE THREAD

**Issue by Jonathan-zxp** [windingwind/zotero-better-notes#63]
比如标题#快捷键 ：在忘记快捷键的情况下，虽然可以点击上面的面板也可达到新建标题的目的 但是能不能在后面加上一些小字提示是哪些快捷键？

**Comment by windingwind** [comment]
这是markdown语法，非常简单，可自行搜索了解。不会加入界面快捷键
