### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MTZun97** [windingwind/zotero-better-notes#631]
**Describe the bug**
Creating unwanted automatic tag

**To Reproduce**
1. open the pdf, and highlight any text.
2. click the yellow button to export the highlighted text into the workspace notes.
3. when I check the tags bar, there will be a new tag created automatically (e.g, zotero://note/u/2GV46CZU/) 
4. Those tags are created automatically as many as I highlight in the pdf.

**Expected behavior**
I don't want the tags to create automatically.

**Screenshots**
highlighted text
![image](https://github.com/windingwind/zotero-better-notes/assets/95432260/461e76a8-a037-41c3-9a64-99654a077bd2)

The automatically created tags
![image](https://github.com/windingwind/zotero-better-notes/assets/95432260/f952a379-e1ea-439a-abb6-cac1e92f2988)

**Desktop (please complete the following information):**
- window 11 home
- chrome
- zotero 6.026 and betternotes 1.0.4

**Comment by windingwind** [comment]
this tag is to prevent creating duplicate notes from the same annotation. it is designed to be so.
