### ISSUE TITLE
mac系统，不能新建其他的笔记，以及删除不掉主笔记（workspace note）里不小心插入的链接

### ISSUE THREAD

**Issue by Demo-Zhang** [windingwind/zotero-better-notes#636]
mac系统，找不到新建其他笔记的地方，而且以前有随意插入到workspace note里面的笔记，现在无法删除链接。在该篇笔记中和workspace note中都无法删除，可以选中，但是按删除键没有反应。

**Comment by windingwind** [comment]
笔记在回收站里就无法编辑。mac用cmd+backspace删除东西
