### ISSUE TITLE
[Bug] 注解上的`TEX`按钮无效

### ISSUE THREAD

**Issue by RayKr** [windingwind/zotero-better-notes#639]
**Describe the bug**
注解上的TEX点击没有反应。

**Screenshots**
<img width="260" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/10293675/174c6d10-eb67-4c60-a2e5-75c156142b7f">

**Desktop (please complete the following information):**

- OS: m1 macOS 13.5
- Zotero Version: 7.0.0-beta.36+3ef1f0992
- Zotero-better-notes Version: 1.1.4-14

**Comment by windingwind** [comment]
该功能已移除

**Comment by CongxunHong** [comment]
> 该功能已移除

那是不是意味着不能使用markdown语言编辑文字颜色了呀？

**Comment by windingwind** [comment]
1. 批注ocr公式移到：https://github.com/windingwind/zotero-actions-tags/discussions/220
2. 批注的评论不支持md语法。通过插件的花型图标从批注创建笔记时，会做md语法的转换

**Comment by CongxunHong** [comment]
> 1. 批注ocr公式移到：[[Share] OCR math to latex from image annotations zotero-actions-tags#220](https://github.com/windingwind/zotero-actions-tags/discussions/220)
> 
>     2. 批注的评论不支持md语法。通过插件的花型图标从批注创建笔记时，会做md语法的转换

好的好的，明白了，谢谢！
