### ISSUE TITLE
[Bug]在工作区更新正文时，大纲频繁跳动，能否改为只在改动标题时才跳动

### ISSUE THREAD

**Issue by linjoe99** [windingwind/zotero-better-notes#640]
您好，首先非常感谢您提供的插件！

在使用时，我发现了一个小问题：

如下图，在工作区更新正文时，大纲频繁跳动（比如输入正文333或3333时，标题1、1.2、2也会跳动），

![图片](https://github.com/windingwind/zotero-better-notes/assets/89997697/9dff990c-b55d-4245-a123-a8ec014118d7)

能否改为只在改动标题时才跳动？

另外，希望可以取消大纲的拖拽功能，有时候（尤其是在刚刚提到的“跳动”发生后）容易误触导致大纲顺序错乱

**Comment by yzy1228682367** [comment]
啊哦 我以为大纲的拖拽功能是betternote 相较于word的一个很大的优势耶，因为mac里面的标题无法拖拽。

**Comment by linjoe99** [comment]
额，确实编辑的时候好用，但是有时候只想阅读时会误触


| |
林新乔
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年8月20日 14:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] [Bug]在工作区更新正文时，大纲频繁跳动，能否改为只在改动标题时才跳动 (Issue #640) |

啊哦 我以为大纲的拖拽功能是betternote 相较于word的一个很大的优势耶，因为mac里面的标题无法拖拽。
