### ISSUE TITLE
No workspace default note after installing

### ISSUE THREAD

**Issue by MVMYCHE** [windingwind/zotero-better-notes#643]
**Describe the bug**
After installing the plug in, didn't get the "Better Notes User Guide" nor the Workspace default note with tips on how to use Better Notes.

**To Reproduce**

1. Download plugin 1.0.4
2. Install plugin to zotero 
3. Relauch Zotero
4. No User Guidance when starting and not available in Help in top menu bar
5. Click on the Workspace tab
6. No default Workspace note available

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome
- Version: iOS 13.4, Chrome v. 115, Zotero 7.0.0 beta (also tried rolling back to 6.0.26 and I still have the same problems)

**Comment by windingwind** [comment]
The wizard is removed.
