### ISSUE TITLE
[Feature]导出MD文件并同步，由Obsidian编辑时，[[ 符号，会回写成 \[\[ 符号。

### ISSUE THREAD

**Issue by Vincentniuniu** [windingwind/zotero-better-notes#645]
Zotero版本：7.0.0-beta.36+3ef1f0992 (64-bit)
Better Notes版本：1.1.4-16
    使用背景情况：
    用Better Notes写了笔记，导出MD文件，并且设置同步。此时，用obsidian打开MD文件夹，所有链接，页面布局都可以，同时，无论在Better Notes里编辑，还是在obsidian里编辑，都是双向同步的，完美。
    但是，如标题中所述，有一个小问题，表现在两个方面：1.如果在Obsidian中用  [[  符号做引用，不同步的情况下，完全没有问题。同步后，到Better Note里，显示  [[XXXX]]  ，同时，Obsidian同步成了 " \ [ \ [ "符号（我只能在这里加上”号和空格，不然显示不出来，实际上是没有“号和空格的）。2.如果直接在Better Note中写入 [[ ，同步后，Obsidian也是同步成了  "\ [ \ [ "。这两种情况，都导致了Obsidian中引用失效。只有手动去掉 \ 才能恢复。
    目前只能一直用Vscode的文件文本替代功能，手动去 \ 。每同步一次，就要手动去一次。
    此问题，从之前的版本，一直到最新的版本都存在。
    期望：Better Notes的同步功能打通了和OB双向互联的通道，我使用起来觉得非常好。只有最后这一个小问题需要解决，如果能够解决，对我来说，几乎是全能的笔记软件了。但是我不是程序员，不知道问题出在哪里。如果有时间和精力，请作者看一下是否有望解决。感谢。

**Comment by windingwind** [comment]
#646
