### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by M4C3N4** [windingwind/zotero-better-notes#647]
**Describe the bug**
I cannot install the plugin i receive the message:
"The instalation has failed
O extra "%S" não pode ser instalado. Pode ser incompatível com esta versão do Zotero"

![image](https://github.com/windingwind/zotero-better-notes/assets/53420811/aa4beab9-9273-40df-aac2-e387db62d293)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes#-install
