### ISSUE TITLE
添加将指定颜色的注释添加到笔记的功能，这样可以根据不同的注释类型生成不同的笔记，可以构成生词本、灵感笔记等等不同的笔记类型。

### ISSUE THREAD

**Issue by littlecaldera** [windingwind/zotero-better-notes#650]
添加将指定颜色的注释添加到笔记的功能，这样可以根据不同的注释类型生成不同的笔记，可以构成生词本、灵感笔记等等不同的笔记类型。
![847608f503c84734873a4c9f1d0fe52](https://github.com/windingwind/zotero-better-notes/assets/87259743/46a12461-fcbc-4aca-a832-2c2b970b2f61)

**Comment by windingwind** [comment]
见https://github.com/windingwind/zotero-better-notes/discussions 相关笔记模板
