### ISSUE TITLE
[Bug] The formatting in note disappears when export to markdown.

### ISSUE THREAD

**Issue by BlankSeed** [windingwind/zotero-better-notes#652]
**Describe the bug**

In the note in zotero, i have

![image](https://github.com/windingwind/zotero-better-notes/assets/21105199/d5ca4a28-d87c-4775-aea3-7ccf853f1fe7)

in the self-defined template this is
![image](https://github.com/windingwind/zotero-better-notes/assets/21105199/84764506-b1f6-4958-bac0-b881df6d18cf)

when export i select
![image](https://github.com/windingwind/zotero-better-notes/assets/21105199/3ae1f027-a00e-4333-9fa0-76973f0ac487)

but i get the below in the exported code

![image](https://github.com/windingwind/zotero-better-notes/assets/21105199/5eea6470-1184-4d3e-b196-eb6dd3ae9ddd)

It seems a direct copy from the note in zotero would also lose the format in the headings, wonder how to solve this? Thanks!

**Comment by windingwind** [comment]
`<h2><span style="color: #ff7700"><span style="background-color: #ffd40080">title</span></span></h2>` works for me.

**Comment by BlankSeed** [comment]
> `<h2><span style="color: #ff7700"><span style="background-color: #ffd40080">title</span></span></h2>` works for me.

It seems the span command inside the heading is effective, but the style command in the heading tag like <h2 style="color:#396d0c; background-color:#e1e9f0;"> invalid. Wonder if it is possible to add color to the tag? Or is this limitation when converting html to markdown? Thanks!

**Comment by windingwind** [comment]
No.
