### ISSUE TITLE
[Bug] 添加超链接弹窗自动弹出且不会自己取消

### ISSUE THREAD

**Issue by gaochuanchao** [windingwind/zotero-better-notes#654]
这个弹窗会自动弹出来, 并且无法自己消失, 只能打开其他笔记后再打开这个笔记才会消失. 但时不时又会自己弹出来.
<img width="302" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/22146315/01f6bd5a-bb9b-42c8-89b5-3d217100e831">

**Comment by windingwind** [comment]
升级插件
