### ISSUE TITLE
better notes 笔记中选择插入引注，不弹出文献选择框

### ISSUE THREAD

**Issue by Fuhan1994** [windingwind/zotero-better-notes#657]
![image](https://github.com/windingwind/zotero-better-notes/assets/30313397/4b70b45a-b87c-4b10-9a87-761f3cd83c99)
笔记中选择插入引注，不弹出文献选择框，只显示如图，点击无反应

**Comment by windingwind** [comment]
非插件功能请向zotero forums反馈

**Comment by Fuhan1994** [comment]
这个不算插件功能么，插入引注是插件的功能

**Comment by windingwind** [comment]
不是
