### ISSUE TITLE
[Bug] 插入条目笔记或者模板笔记后，无法向下滑动

### ISSUE THREAD

**Issue by cohesioncompany** [windingwind/zotero-better-notes#658]
**Describe the bug**
阅读文献时，插入条目笔记或者模板笔记后，滚动条没了，无法向下滑动

**To Reproduce**

1. 打开文献，通过条目添加笔记或者通过模板添加笔记
![image](https://github.com/windingwind/zotero-better-notes/assets/103297347/9489264c-6cba-4942-bfca-b27420d20ff5)
2. 无论哪个方法添加笔记，滚动条都不出现，并且无法向下滚动
![image](https://github.com/windingwind/zotero-better-notes/assets/103297347/b157e16f-5389-4c49-834a-263181778326)

**Desktop (please complete the following information):**

- zotero [beta.38 (64-bit)]
- better notes [1.1.4-17]
其他插件如下
![image](https://github.com/windingwind/zotero-better-notes/assets/103297347/3320c20e-9a5c-4e04-bf7c-4778768d3029)

**Comment by cohesioncompany** [comment]
抱歉提出这个问题，现在我发现，这貌似是我侧边栏的bug，不管插不插笔记，滚动条都不会出现。
但是我检查不出这是怎么引起的😟

**Comment by windingwind** [comment]
我无法复现，请尝试关闭所有插件后重试

**Comment by cohesioncompany** [comment]
好的谢谢，已经排查，并不是better notes的原因，具体我还要再看看www



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月29日 11:44 |
| 收件人 | ***@***.***> |
| 抄送至 | Keqiang ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] [Bug] 插入条目笔记或者模板笔记后，无法向下滑动 (Issue #658) |

我无法复现，请尝试关闭所有插件后重试
