### ISSUE TITLE
[Feature]插入的表格列宽如何调整

### ISSUE THREAD

**Issue by CelanXu** [windingwind/zotero-better-notes#660]
首先，非常感谢大佬开发本插件，让zotero的笔记功能更进一步。
在使用过程中，本人经常使用表格来进行多文献整理，但是每次使用都会因表格的列宽无法自行调整而苦恼，影响后续阅读
请问在后续开发中，能否加入表格的列宽执行调整，及一次性插入多行/多列，十分感谢！

**Comment by windingwind** [comment]
表格是zotero本身的功能，列宽是自适应，暂时无法通过插件进行更改。可以在官方论坛提建议。

一次性插入多行多列可以通过笔记模板实现。
