### ISSUE TITLE
[Bug]新版本有两个重要的按钮不见了，没法操作。

### ISSUE THREAD

**Issue by Nolan-zhong** [windingwind/zotero-better-notes#665]
**Describe the bug**

新版本有两个重要的按钮不见了。

**Screenshots**
新本版截图：按钮不见了
![image](https://github.com/windingwind/zotero-better-notes/assets/141936929/c7a8dd35-3f53-4a5b-b583-33e71c4172ad)

在这里没有按钮没法操作
![image](https://github.com/windingwind/zotero-better-notes/assets/141936929/846d9543-47be-4d0c-ab4c-39623a0571b0)

旧版的截图

![image](https://github.com/windingwind/zotero-better-notes/assets/141936929/7b37d3ef-90ad-479a-bf5d-450715d52634)

**Desktop (please complete the following information):**

- OS: win11
- Browser:chrome
- Version:better notes for zotero 1.1.4-17

**Comment by windingwind** [comment]
1. 转跳笔记父条目pdf按钮移到右侧齿轮菜单内。
2. 关闭按钮由工作区标签的悬浮按钮替代
![image](https://github.com/windingwind/zotero-better-notes/assets/33902321/42540d7f-b811-4695-a9ce-126ad3691690)

**Comment by Nolan-zhong** [comment]
谢谢@windingwind
