### ISSUE TITLE
[Bug] 在Note Workspace中编辑使用中文输入法卡顿，而在侧边pane中输入法正常

### ISSUE THREAD

**Issue by RayKr** [windingwind/zotero-better-notes#666]
**Describe the bug**

同一篇note，相同中文输入法，在论文阅读器打开页面的侧边栏中打开note进行编辑，输入中文是正常输入，而当在Note Workspace中打开时，输入中文就会卡顿，英文不会卡顿。

另外，我又重新试了一下新创建的空白note，不会出现中文卡顿了，那怀疑是不是note中的内容有跟输入法冲突的，我的那篇里内容很多，有6000+文字，图片，公式都有。

- OS: Apple Silicon M1 MacBook Pro macOS Ventura 13.5
- Browser: Chromium Engine Version 116.0.5845.110
- Version Zotero 7.0.0-beta.38+b79e0b3d7 + Better Notes 1.1.4-17
- 输入法：落格输入法3，系统自带拼音、双拼，鼠须管都试过，只要是输入中文就会卡顿。

** Screen **
截图无法动态展现该bug，我录制了个视频，https://share.cleanshot.com/FwtNfsjW, 请查看。

**Comment by windingwind** [comment]
禁用其他插件试一下

**Comment by RayKr** [comment]
试过了，和Zotero GPT插件冲突。我突然想到，Better Notes README里说过可以像notion一样，空格键呼出gpt对话窗口https://github.com/windingwind/zotero-better-notes#gpt-integration ，但是我这里没呼出过。输入中文空格上屏和空格呼出GPT应该是冲突了。

**Comment by windingwind** [comment]
@MuiseDestiny

**Comment by windingwind** [comment]
由于与本插件无关，此处关闭
