### ISSUE TITLE
[Note Template]

### ISSUE THREAD

**Issue by aathanor** [windingwind/zotero-better-notes#667]
## Template Type

Item

## Desired Template Performance

On Zotero 7 beta with your latest beta version, the output of "Collect annotations by color" is empty, with no error message.
Does it work on those versions? What could be the problem?

## Current Template

// @author windingwind 
// @link https://github.com/windingwind/zotero-better-notes/issues/85#issuecomment-1210063595
${await new Promise(async (r) => {
  async function getAnnotation(item) {
    try {
      if (!item || !item.isAnnotation()) {
        return null;
      }
      let json = await Zotero.Annotations.toJSON(item);
      json.id = item.key;
      delete json.key;
      for (let key in json) {
        json[key] = json[key] || "";
      }
      json.tags = json.tags || [];
      return json;
    } catch (e) {
      Zotero.logError(e);
      return null;
    }
  }

  async function getAnnotationsByColor(_item, color) {
    const annots = _item
      .getAnnotations()
      .filter((_annot) => _annot.annotationColor === color);
    let annotations = [];
    for (let annot of annots) {
      const annotJson = await getAnnotation(annot);
      annotJson.attachmentItemID = _item.id;
      annotations.push(annotJson);
    }

    const editor =
      await Zotero.Knowledge4Zotero.knowledge.getWorkspaceEditorInstance();
    await editor.importImages(annotations);
    return Zotero.EditorInstanceUtilities.serializeAnnotations(annotations);
  }

  const attachments = Zotero.Items.get(topItem.getAttachments()).filter((i) =>
    i.isPDFAttachment()
  );
  let res = "";
  let colorYellow = "#ffd400";
  let colorRed = "#ff6666";
  let colorGreen = "#5fb236";
  let colorBlue = "#2ea8e5";
  let colorPerple = "#a28ae5";
  for (let attachment of attachments) {
    res += `<h2><p style="background-color:${colorYellow};">Yellow Heading</p></h2>
    ${(await getAnnotationsByColor(attachment, colorYellow)).html}
    `;
    res += `<h2><p style="background-color:${colorRed };">Red Heading</p></h2>
    ${(await getAnnotationsByColor(attachment, colorRed )).html}
    `;
    res += `<h2><p style="background-color:${colorGreen };">Green Heading</p></h2>
    ${(await getAnnotationsByColor(attachment, colorGreen )).html}
    `;
    res += `<h2><p style="background-color:${colorBlue };">Blue Heading</p></h2>
    ${(await getAnnotationsByColor(attachment, colorBlue )).html}
    `;
    res += `<h2><p style="background-color:${colorPerple };">Perple Heading</p></h2>
    ${(await getAnnotationsByColor(attachment, colorPerple )).html}
    `;
  }
  r(res);
})}

**Comment by aathanor** [comment]
Solved! In the docs it is not clear what item you need to select in Zotero library before calling the template.
I was selecting the PDF doc (the logic will dictate that the "item" is a single doc), but in fact the template works when selecting the parent record (the one including the pdf doc and other things). Not sure this is the intended way but this is how it works on Mac.

**Comment by aathanor** [comment]
Thanks! #236 refers to "collect by tag"; mine was "collect by color". Do you have an updated version for this one?

**Comment by windingwind** [comment]
See #227
