### ISSUE TITLE
[Feature]如何在使用颜色或者标签导出子笔记？

### ISSUE THREAD

**Issue by yingker** [windingwind/zotero-better-notes#67]
我习惯在zotero中，用不同颜色的高亮，标注pdf文献，并加上不同的标签作为子笔记，很希望能按照不同颜色或者标签导出子笔记到OB中。这个可能是很多用户的习惯和共同要求。
据说：模板功能可以实现按照颜色或者标签导出笔记，但我试了一下，实现不了。其实多数普通用户对模板怎么使用也是不太清楚，请大神详细示范一下。

**Comment by windingwind** [comment]
请合并到#51 进行讨论。
默认提供的模板有限，近期我会根据颜色/标签的需要新增一些。
是否基于现在的[Item]模板，选择一些条目，并根据颜色/标签将批注导入当前主笔记是合适的？
