### ISSUE TITLE
[Bug]笔记界面图片上的右键菜单

### ISSUE THREAD

**Issue by ZackRABBIT** [windingwind/zotero-better-notes#678]
在笔记界面右键点击图片时，当鼠标在【从左到右】到【图片缩放】之间移动时，最后的图片缩放选项会增加。
![image](https://github.com/windingwind/zotero-better-notes/assets/42856463/11895a34-b2b3-4bfc-82b4-3c19b0f3f86c)

**Comment by windingwind** [comment]
更新插件（如果是z6，请等待z7正式版）
