### ISSUE TITLE
[Bug] image is not copied

### ISSUE THREAD

**Issue by appw-cn** [windingwind/zotero-better-notes#68]
**Describe the bug**
在zotero自带的PDF阅读器中，点击图片笔记中的复制按钮，弹出“image copied to clipboard”，但实际上粘贴板为空。
**To Reproduce**
1. open zotero
2. open a PDF file with zotero PDF reader
3. take a image note
4. click "copy" botton.
5. a message shows "image copied to clipboard"
6. paste it in Logseq/Obsidian/或者其它任意地方，什么也没有发生。

**Expected behavior**
恳请作者大大修复bug

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Zotero 6.0.8

**Additional context**

**Comment by windingwind** [comment]
尝试在word之类的地方粘贴，或者查看剪贴板。在windows上测试通过，也许是不支持mac？

**Comment by appw-cn** [comment]
> 尝试在word之类的地方粘贴，或者查看剪贴板。在windows上测试通过，也许是不支持mac？

也许是的。我换个windows试下。剪贴板确实是空的。。。

**Comment by windingwind** [comment]
因为Zotero基于的Firefox60运行时较旧，文档不全或过时，部分底层接口有可能对不同平台适配有问题。不排除是mac用不了。实在不行mac只能截图复制

**Comment by appw-cn** [comment]
确实是mac系统的原因，在windows下尝试可以。。。因为zotero storage同步太麻烦了，所以放在了iCloud里面……

**Comment by windingwind** [comment]
谢谢反馈，已加入已知问题列表。目前无法在mac复制图片
