### ISSUE TITLE
希望在主笔记界面增加一个功能，可以选择是否import所有的 linked note

### ISSUE THREAD

**Issue by Justin-ShanJ** [windingwind/zotero-better-notes#680]
主笔记中的笔记是一个链接，之前修改Quickinsert的代码也失效了。
希望主笔记界面可以增加一个功能，即可以自主选择是否打开和关闭显示子笔记，对于大量的笔记就比较方便查找和定位。

**Comment by windingwind** [comment]
导出-导出为笔记&嵌入子笔记内容即可
