### ISSUE TITLE
[Bug]Latex与中文互动问题

### ISSUE THREAD

**Issue by HIEROT** [windingwind/zotero-better-notes#681]
**Describe the bug**
在使用笔记编辑器时，如果点击一个渲染过的latex表达式将其展开为源码，然后使用光标移动到周围中文内容中，则无法再输入中文。输入英文、数字等行为正常。重启笔记编辑器也可恢复正常。

**To Reproduce**

1. 打开任意笔记
2. 输入任意Latex内容
3. 使用键盘左右键移动光标至周围中文内容区域

**Expected behavior**
能够继续键入中文

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 11
- Version 1.0.4

**Comment by HIEROT** [comment]
看起来像是光标定位相关的问题，可能与编码格式等有关。

**Comment by windingwind** [comment]
与插件无关，请向zotero forums报告问题
