### ISSUE TITLE
[Note Template]导出的md文件里的链接都是html格式的。怎么才能弄成像Zotero自己导出的那样的格式的？

### ISSUE THREAD

**Issue by NaShiTian** [windingwind/zotero-better-notes#683]
Zotero版本6.0.27    插件版本1.0.4
# 导出设置
![1](https://github.com/windingwind/zotero-better-notes/assets/113958170/7f420027-1dbe-4693-affb-bd7097707353)
# 笔记文本
![2](https://github.com/windingwind/zotero-better-notes/assets/113958170/cfd5b5ab-649b-4e94-a7bd-a778c7275be0)

# 插件导出的Markdown文本
![3](https://github.com/windingwind/zotero-better-notes/assets/113958170/cddc8d59-50d2-4742-b3c2-f4cd5752ea3e)

# Zotero自带导出的Markdown文本
![6](https://github.com/windingwind/zotero-better-notes/assets/113958170/9270c36c-3a75-43f2-ad09-503ffa449b11)

**Comment by windingwind** [comment]
设计如此。

**Comment by NaShiTian** [comment]
> 设计如此。

能通过文件修改吗？
如果能，要改哪个文件？
