### ISSUE TITLE
[Bug]zotero obsidian双向同步错误

### ISSUE THREAD

**Issue by nanadeya** [windingwind/zotero-better-notes#686]
**Describe the bug**
Zotero：7.0.0-beta.39
zotero-better-notes：1.1.4-22

1.点击“导出当前笔记”
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/b51c8f6c-34f1-4ee8-a931-33b7fbfbb473)

2.点击同步管理，发现同步时间都是1970，查看了#594相同的问题，但是还是不知道怎么解决。
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/5fd6076e-1323-4a4c-b41d-f849d5a06902)

3.调试日志是这样显示的。
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/954823ed-4df4-4e52-98ed-c4dc7fd0b95e)

上周五之前好像没有这个问题，突然就这样了。很多操作都尝试了，比如取消同步后再次同步，导出到不是obsidian下的文件夹，把导出模板都重置，都没有办法解决，在两台电脑上都操作过都是这样，请问要怎么解决这个问题？

**Comment by windingwind** [comment]
1. 同步时间1970是计算机计时起始点，意味着从未发生同步。
2. 请描述“双向同步错误”指的是什么错误
3. 请导出完整的调试输出，截图没有帮助

**Comment by nanadeya** [comment]
导出后显示时间1970，在obsidian的文件里没有.md文件，也就是空的。

这是调试文件。
(file:///C:/Users/nana/Desktop/Debug%20Output.htm)

**Comment by nanadeya** [comment]
导出后显示时间1970，在obsidian的文件里没有.md文件，也就是空的，没有导出成功。
这是调试文件。
[bug.txt](https://github.com/windingwind/zotero-better-notes/files/12572001/bug.txt)

**Comment by windingwind** [comment]
请截图内置模板列表（ExportMDFileName/ExportMDFilePath），以及你导出的笔记在库中的截图。
似乎模板运行中出现了错误。

**Comment by nanadeya** [comment]
`${(noteItem.parentItem && noteItem.parentItem.getField("year"))}_${(noteItem.parentItem && noteItem.parentItem.getField('firstCreator').split(" ",1).slice(0))}.md`

![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/aecacef2-636c-4bc6-a2ee-834fca1bfade)

`${{
  let header = {};
  header.tags = noteItem.parentItem.getTags().map(tagObj=>tagObj.tag);
  header.parent = noteItem.parentItem
    ? noteItem.parentItem.getField("title")
    : "";
  header.collections = (
    await Zotero.Collections.getCollectionsContainingItems([
      (noteItem.parentItem || noteItem).id,
    ])
  ).map((c) => c.name);
  return JSON.stringify(header);
}}$`

![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/2cded9d4-2d41-4c68-8520-50c9bfda6c42)
导出的笔记为空，也就是只要显示时间为1970的话，就没有导出。
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/0149215a-a916-444e-8eb7-605eca806c3f)

**Comment by windingwind** [comment]
我感觉你的ExportMDFileName模板可能导致导出结果为空。请试下重置模板，并且重置后记得保存

**Comment by nanadeya** [comment]
你好，我重置了所有默认模板，仍然无法成功。
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/23aaa181-f630-471d-889b-1c92fbb3f8e0)

这是调试文档。
[Uploading 调试.txt…]()

这个模板这里好像多个“)”
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/4215c972-6246-496a-b0c2-4d310cb9f381)

**Comment by nanadeya** [comment]
[调试.txt](https://github.com/windingwind/zotero-better-notes/files/12573025/default.txt)
这是调试文档。

**Comment by windingwind** [comment]
请在打开调试输出窗口后，在同步管理器中，全选所有同步记录，点击同步，然后再发送调试输出，谢谢。

**Comment by nanadeya** [comment]
[Debug Output.txt](https://github.com/windingwind/zotero-better-notes/files/12573269/Debug.Output.txt)
这是调试文档。

**Comment by ti1ga** [comment]
没解决啊
