### ISSUE TITLE
How to insert selected citations in zotero-better-notes?

### ISSUE THREAD

**Issue by lhtmed** [windingwind/zotero-better-notes#69]
**Is your feature request related to a problem? Please describe.**
zotero-better-notes has provided “insert citation” function. But it's not smart because I have to search keywords to find citation(s) that already be selected by cursor.

**Describe the solution you'd like**
Provide "insert selected citation(s)" button so that I can insert one or more already selected citations into notes.

**Additional context**
This is a function in Endnote, it has been proposed in Zotero forum for many years but still not  available.

**Comment by windingwind** [comment]
Currently, you can use the `[+]` button to select items to cite. Alternatively, create a template.
Not sure what you mean by 'citation(s) that already be selected by cursor'. Do you mean select items in the item view?

**Comment by lhtmed** [comment]
this is what I mean
https://youtu.be/ejcrpyD2KZ8

**Comment by windingwind** [comment]
Got it. Here are 3 ways to realize this feature:
1. The Endnote way. Go to Zotero item view; Select some items; Press a button in note editor to insert the citations.
2. Press a button in note editor and select items in a new ‘select items’ window. Press OK to insert citations.
3. Press a button in workspace menu and select items in a new ‘select items’ window. Press OK to insert citations.

Which one do you prefer?

**Comment by windingwind** [comment]
Please try v0.5.16

Select a citation style: Edit->Citation Style in Notes
![image](https://user-images.githubusercontent.com/33902321/174953414-c6cabe23-b455-4d5f-90fa-8147b7f4bc0e.png)

Then click the cite button to select some items and insert them into the note. There will be an extra popup button with the parent item's title for item notes, which will cite the parent item directly.

![image](https://user-images.githubusercontent.com/33902321/174953872-b6c05cbf-77d5-44f6-a5f7-9f79d71ef4ed.png)
