### ISSUE TITLE
[Feature]与obsidian实现文献分类目录和notes分类目录1:1同步

### ISSUE THREAD

**Issue by llity** [windingwind/zotero-better-notes#691]
现在的同步管理应该需要手动添加每一条note到同步目录。

能否自动生成文献对应的目录文件夹，完成同一分类目录下文章的notes一次同步到目标目录
并生成与zotero中1:1的分类目录。

谢谢

**Comment by windingwind** [comment]
参考https://github.com/windingwind/zotero-actions-tags/discussions/140
可以修改同步路径部分的代码，根据collection名称创建文件夹并同步到对应路径
