### ISSUE TITLE
[Bug]安装新版插件没有my notes文件夹

### ISSUE THREAD

**Issue by Chenlulu2020** [windingwind/zotero-better-notes#696]
**Describe the bug**
1.安装新版插件（1.0上下好几款）都没有my notes文件夹
2.主笔记链接notes，有的可以插入（有🔗符号），有的不行（没🔗符号）
3.现在我的主笔记它不能编辑了QAQ

**Desktop (please complete the following information):**
- Zotero Version [6.0.27]

**Comment by windingwind** [comment]
1. 该功能已移除，自己新建即可
2. 没明白
3. 笔记在回收站时不可编辑
