### ISSUE TITLE
大佬您好！我在zotero7 中使用better notes，当笔记中的文字多于一页时，发现不会即时出现滚动条，以至于笔记显示不全[Bug]

### ISSUE THREAD

**Issue by shenhundd** [windingwind/zotero-better-notes#698]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windingwind** [comment]
与本插件无关，禁用其他插件排查问题
