### ISSUE TITLE
duplicate content

### ISSUE THREAD

**Issue by lil-i321** [windingwind/zotero-better-notes#7]
1. 将PDF内部的注释插入到主笔记时，重复显示3次，1注释条目名，2内部内容第一段，3内容。
**能否将1&2合并？或者将2隐藏。**
个人想法：以本条注释的tag内容为条目名，用来索引。
2. 并且，条目名修改后，主笔记的索引并不更新。
![图片](https://user-images.githubusercontent.com/57334649/168246573-bcbd2474-119c-4363-b178-300bf707fe34.png)

**Comment by windingwind** [comment]
均已计划，谢谢建议！

**Comment by windingwind** [comment]
重复标题已在pre-release v0.2.0-0中修复

**Comment by lil-i321** [comment]
> 

感谢更新！！！
已使用。
“Linked Note:”关键字，是否有保留的必要呢？

**Comment by windingwind** [comment]
索引更新功能已在0.2.2支持。

**Comment by windingwind** [comment]
建议一个issue讨论一个问题。你可以新开一个issue并鼓励大家讨论是否需要在导入时移除这个词
