### ISSUE TITLE
批注自动摘录到笔记中

### ISSUE THREAD

**Issue by AixinjueluoVince** [windingwind/zotero-better-notes#70]
目前在pdf中做的批注例如高亮截图等都是要手动拖拽才能进入到笔记中相当麻烦，可否在选中笔记面板就能自动摘录。大部分的pdf阅读器如bookxnote都有这个功能。
https://hhhwhhh.oss-cn-guangzhou.aliyuncs.com/bookxnote3.gif
https://hhhwhhh.oss-cn-guangzhou.aliyuncs.com/Zotero_1.gif

**Comment by windingwind** [comment]
如果仅希望将批注归纳到一个笔记中，可以：
1. 使用Zotero自带的从批注添加笔记功能。选中文献右键/在阅读器右侧笔记栏中’+‘将该文献中的所有批注整理到当前笔记。
![image](https://user-images.githubusercontent.com/33902321/175072437-7d41a8f0-15d4-4d62-90dc-8adc37abc2d7.png)

![image](https://user-images.githubusercontent.com/33902321/175072427-6211cb3f-43da-4402-9360-7affa2b53ef8.png)

2. 使用插件提供的笔记模板，可以同时导入多条文献的批注并按照颜色归类。见#49

但上述做法和你的第一个截图一样，无法在批注的同时整理到大纲框架，实际上没有起到”一边阅读一遍形成知识结构“的目的。推荐的做法是在批注时通过左侧批注栏的插件图标，创建一个批注笔记，并将批注插入到主笔记的对应大纲目录下。见https://github.com/windingwind/zotero-better-notes#all-in-zotero-best-note-practice

**Comment by windingwind** [comment]
此处关闭，合并讨论在#72
