### ISSUE TITLE
同步冲突求助

### ISSUE THREAD

**Issue by Yikedo** [windingwind/zotero-better-notes#700]
**同步时间一到，就跳出来这个“冲突解决”框，求助如何解决？**
![image](https://github.com/windingwind/zotero-better-notes/assets/116061695/101fdc79-7281-4b0a-a861-817e5dadc6a7)
![image](https://github.com/windingwind/zotero-better-notes/assets/116061695/5d271add-838f-4e91-aadd-710749611f78)

**Comment by windingwind** [comment]
与本插件无关。这不是本插件产生的笔记。
