### ISSUE TITLE
[Note Template] ExportMDFileName template not working as expected

### ISSUE THREAD

**Issue by sjgknight** [windingwind/zotero-better-notes#701]
## ExportMDFileName

${noteItem.id}-${noteItem.key}.md

## Desired Template Performance

I'd like to name my notes by id and key, because it will help me process them elsewhere (and avoids long path issues).

## Current Template

I have my [ExportMDFileName] template as below, but my filenames are being exported with the note title instead. 

```js
${noteItem.id}-${noteItem.key}.md
```

**Comment by windingwind** [comment]
please provide screenshots of your template editor

**Comment by sjgknight** [comment]
Sure, hopefully these work
![image one](https://imgur.com/Z70VZj4)
![image two](https://imgur.com/xHavUV6)

**Comment by windingwind** [comment]
images are broken

**Comment by sjgknight** [comment]
doh, I just turned them into regular links, hopefully that works

**Comment by windingwind** [comment]
`[ExportMDFileNameV2]` works for your plugin version. Every time there is an update to the default value of built-in templates, e.g. ExportMDFileName, there will be an increment of version number to avoid overwriting the template code that the user has modified.

You are not allowed to edit the template name of all built-in templates. That's how we expect you to distinguish which one is the built-in template that is currently used.

Thanks for pointing out. I've explained this in https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#builtin-templates
