### ISSUE TITLE
[Feature] Batch export notes

### ISSUE THREAD

**Issue by sjgknight** [windingwind/zotero-better-notes#702]
**Is your feature request related to a problem? Please describe.**
The export of notes is great, but it seems for each new note exported there's a user interaction (confirm filename/location and hit save, wait for next note). I'm not clear if it's possible to batch export by selecting multiple items/notes/collections and confirming their export location just once.

**Describe the solution you'd like**
It would be useful to be able to select multiple items/notes/collections and a destination path to export with a single user interaction. (Or, if already possible, better user or better documentation).

**Comment by windingwind** [comment]
> It would be useful to be able to select multiple items/notes/collections and a destination path to export with a single user interaction. (Or, if already possible, better user or better documentation).

yes, you can.

**Comment by sjgknight** [comment]
Thanks, it's good to know it's possible, when I use the 'export note' function, whether I click 'all embedded in one export' or 'each converted', I receive a dialogue prompt for each individual note. Sorry if I'm missing something but I can't see in the guide or in the UI how I can run this as a background batch job

**Comment by windingwind** [comment]
That used to be only available when syncing the note with MD. I made an option in the export config window `Auto Generate MD File Name` in the latest beta 1.1.4-25.

Check this option and the filename will be controlled by the template `[ExportMDFileNameV$x$]`
