### ISSUE TITLE
[Note Template] macOS 不知道如何插入Template笔记

### ISSUE THREAD

**Issue by MingyanZHU** [windingwind/zotero-better-notes#704]
## Template Type

Item, Note, Quick Import, Quick Insert, ...

## Desired Template Performance

使用默认的Template无法新建笔记，会弹出这样一个窗口（如下图），但是搜不到一个默认的或者新建的模板。

<img width="510" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/36833128/2b85061d-5daa-4eb5-be4a-b750e4bb014d">

默认模板都是存在的
<img width="600" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/36833128/b3464534-b40f-48b9-8156-8ecee73e085a">

**应该怎么样才能用上模板来新建一个笔记呢？**

**Comment by windingwind** [comment]
更新插件

**Comment by wjfu99** [comment]
@windingwind 我的插件已经是最新版本beta.56，还是有上面这个问题，请问怎么解决？
![image](https://github.com/windingwind/zotero-better-notes/assets/57850011/b1df5186-3edd-4c9b-9c5d-e1c753d2fa3f)

**Comment by windingwind** [comment]
如果你没有自己创建或导入可用的模板，可能是没有的，因为类似[QuickInsertV2]的模板都是内置模板，无法用于插入内容，详见文档
