### ISSUE TITLE
[Bug] 插入主笔记时，位置不正确

### ISSUE THREAD

**Issue by RTcui** [windingwind/zotero-better-notes#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:      windows
- Zotero Version:      官网z7最新版   
- Plugin Version:   Bnotes 1.1.4-25                    同时z6配合早版本Bnotess有同样问题

### Describe the bug

子笔记插入主笔记时，位置不是在预定位置，可能跑到最后，也可能跑到其他标题下。  求大家帮忙这是啥情况，救命救命。

### Debug Output

无

**Comment by RTcui** [comment]
重启电脑后好了，不知道问题会不会复现。

**Comment by windingwind** [comment]
需要debug output
