### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by trickard1000** [windingwind/zotero-better-notes#71]
I appreciate being able to create a document with links to the PDF annotations, etc. But, the ultimate step for me would be to move to Word, where I can further manipulate the citations. As it is, it seems the Word add on cannot recognise the citations in better notes. The same issue persists with Logseq, where, once I have written an essay or article, I have to export text then manually add citations through the Word add on, unless I go through some awkward third party solution. 

Can you create an export function that would allow the Word add on to see the citations in better notes? (sorry if this feature exists and I could not see it!)

**Comment by trickard1000** [comment]
Links operate in better notes and logseq. e.g., 

“. There is an increasing emphasis on the need to sensitize researchers and students to diverse epistemologies, methods, and methodologies, especially those of women, minority groups, former colonized societies, indigenous people, historically oppressed communities, economically oppressed groups, and people with disabilities, who have been excluded from dominant epistemologies” ([Chilisa, 2012, p. 14](zotero://select/library/items/EXG3RGHZ)) ([pdf](zotero://open-pdf/library/items/IWG9NL87?page=14))"

I would like these links to translate into citations for the Zotero Word add on....

**Comment by windingwind** [comment]
Maybe the export to richtext is what you need.

**Comment by windingwind** [comment]
Sorry for the late reply. Maybe inserting citations can help you.
![image](https://user-images.githubusercontent.com/33902321/177724722-38ae9476-49f7-4b64-9938-ae915a50fa65.png)
However, as the note is not a formal paper writing tool, the links cannot be converted to Word format: at least we cannot do that now.

**Comment by windingwind** [comment]
I'll close this issue. Please feel free to open it again.

**Comment by trickard1000** [comment]
Hi. No problem.

I await the holy grail of interoperability between Zotero, Word and Logseq
for academic writing.

Thomas.

+55 31 99497-7115 (+Whatsapp) / +44 (0) 7564 251 079

PhD Candidate - Environmental Analysis & Modelling
<http://www.igc.ufmg.br/index.php?option=com_content&view=article&id=331:pos-graduacao-em-analise-e-modelagem-de-sistemas-ambientais&catid=2:uncategorised&Itemid=116>,
GeoSciences Institute, Fed. University of Minas Gerais, Brazil

*Linkedin *Thomas Lloyd Rickard
<https://www.linkedin.com/in/thomaslloydrickard/>
*ResearchGate *Thomas_Rickard
<https://www.researchgate.net/profile/Thomas_Rickard>
*Lattes *Thomas Lloyd Rickard 5619621497755463
<http://lattes.cnpq.br/5619621497755463>
