### ISSUE TITLE
[Bug] Broken automatic updates for the Zotero 7 pre-releases

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.40+24ae34104 (64-bit)
- Plugin Version: 1.1.4-24

### Describe the bug

After doing the Check for Updates in the Zotero Add-ons Manager, a blue dot appears above the three dots on the top right of the plugin. But it cannot update.

### Debug Output

1695363897005	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1695363898270	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "uncaught exception: Object"]

[JavaScript Error: "Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [mozIStorageService.backupDatabaseFile]" {file: "chrome://zotero/content/xpcom/db.js" line: 1058}]

[JavaScript Error: "Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [mozIStorageService.backupDatabaseFile]" {file: "chrome://zotero/content/xpcom/db.js" line: 1058}]

1695369262723	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/muisedestiny/zotero-style/main/update.json - 404: Not Found

1695369262764	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/wshanks/Zutilo/release/deploy/updates.json - 404: Not Found

1695369263008	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data(resource://gre/modules/addons/AddonUpdateChecker.jsm:342:23) JS Stack trace: onLoad@AddonUpdateChecker.jsm:342:23
UpdateParser/<@AddonUpdateChecker.jsm:286:54

1695369263337	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

1695369272241	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

1695369296413	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/wshanks/Zutilo/release/deploy/updates.json - 404: Not Found

1695369296425	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/muisedestiny/zotero-style/main/update.json - 404: Not Found

1695369296527	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data(resource://gre/modules/addons/AddonUpdateChecker.jsm:342:23) JS Stack trace: onLoad@AddonUpdateChecker.jsm:342:23
UpdateParser/<@AddonUpdateChecker.jsm:286:54

1695369296917	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

1695369314970	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

1695369520115	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/muisedestiny/zotero-style/main/update.json - 404: Not Found

1695369520175	addons.update-checker	WARN	Request failed: https://raw.githubusercontent.com/wshanks/Zutilo/release/deploy/updates.json - 404: Not Found

1695369520312	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data(resource://gre/modules/addons/AddonUpdateChecker.jsm:342:23) JS Stack trace: onLoad@AddonUpdateChecker.jsm:342:23
UpdateParser/<@AddonUpdateChecker.jsm:286:54

1695369520685	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-better-notes/releases/latest/download/zotero-better-notes.xpi failed: Expected addon version 1.1.4-3 instead of 1.0.4

appName => Zotero, version => 7.0.0-beta.40+24ae34104, os => Windows 10.0 19045, locale => en-GB, extensions => Zotero PDF Preview (1.0.0-4, extension), Open PDF (0.0.1, extension), Zutilo Utility for Zotero (3.10.1a1, extension), Better BibTex for Zotero (6.7.120, extension), Zotero Last Author (2.1.0, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.1, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2557.0, plugin), Better Notes for Zotero (1.1.4-24, extension, disabled), Translate for Zotero (1.1.0-18, extension, disabled), Ethereal Style (3.1.2, extension, disabled)

**Comment by windingwind** [comment]
Right. The auto-update does not support prerelease intentionally. However since Zotero has been in beta for a long time, it becomes quite awkward.

When the Zotero 7 comes to a stable release, the plugin will have a stable release that can be auto-updated to.
