### ISSUE TITLE
[使用] 为什么笔记都会弹出独立编辑框？

### ISSUE THREAD

**Issue by asiyoua** [windingwind/zotero-better-notes#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Mac
- Zotero Version: 7.0
- Plugin Version: 1.0.4

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/48462903/a33d3590-a55a-481f-9757-a7ec33bfe930)

看教程，点击花花的图标，会直接插入主笔记的区域。但是，**我点击的时候会弹出一个独立笔记编辑框。**
找半天没找到可以设置的地方。

### Debug Output

不是bug，感觉是使用问题。

**Comment by windingwind** [comment]
批注先转化成笔记，在笔记编辑窗口中，点击花形图标，方可链接到工作区。链接只在笔记之间产生
