### ISSUE TITLE
找不到同步功能[Bug] 

### ISSUE THREAD

**Issue by klucius1218** [windingwind/zotero-better-notes#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 6
- Plugin Version: 1.0.4

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/135409766/b6e1e24b-8476-4bd2-a58f-7c335315fc7f)
在文件菜单中找不到better note相关的选项，其他位置试过也找不到

### Debug Output

![image](https://github.com/windingwind/zotero-better-notes/assets/135409766/1799cf1b-d2b0-49bb-854c-8ba9c49f0343)

**Comment by klucius1218** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/135409766/90f5865d-048b-4b75-9808-ca4ff0b8f7c0)
she'zhi设置自动同步的按钮是灰色的，无法选择

**Comment by windingwind** [comment]
链接模式“分别导出”方可使用。请仔细阅读readme
