### ISSUE TITLE
增加自动摘录功能

### ISSUE THREAD

**Issue by TheGodOfKing** [windingwind/zotero-better-notes#72]
请大佬务必实现自动摘录的需求，我认为 #70 的自动摘录功能是十分有必要的。因为我开发了一款产品可以是可以把markdown笔记转为Anki卡片详细请看https://notetocard.com 和 https://www.bilibili.com/video/BV1Za411j7Vv?spm_id_from=333.999.0.0&vd_source=793a152a25049e575a5f472546cd09a7，
zotero-better-notes导出的笔记完全是可以制做anki卡片的，这样就可以形成知识闭环的系统。但是betternotes在做笔记的时候不够顺畅，要拖拽或者点击才能摘录，这些简单又重复的工作还是自动化比较好。最后请大佬增加自动摘录的支持，希望合作愉快。

**Comment by windingwind** [comment]
@TheGodOfKing 
关键的问题在于自动摘录无法将笔记添加到知识结构下，只能顺序堆叠。一个主笔记可能有多个文献二级标题，下又有多个三级标题如背景、创新点、方法、效果等等，如何将当前批注插入到对应文献的对应区域？
如果这一点没法解决，自动化没有太大意义

**Comment by TheGodOfKing** [comment]
这个对应区域不是用户自己选的么，现在我是一个个拖动到到对应区域，几千个批注就要拖动几千次，关键是拖动而不是选着。当用户选着主笔记的某个区域后下一次的高亮会自动摘录到选着光标的后面，然后焦点会回到笔记当中，用户可以继续高亮，也会摘录到当中，当笔记不被选中也就是失去焦点那么用户的下次高亮就不会被自动摘录，这个功能应该不难实现。能减少用户做笔记的阻尼，让用户像吃德芙一样顺滑还是非常有意义的。

> @TheGodOfKing 关键的问题在于自动摘录无法将笔记添加到知识结构下，只能顺序堆叠。一个主笔记可能有多个文献二级标题，下又有多个三级标题如背景、创新点、方法、效果等等，如何将当前批注插入到对应文献的对应区域？ 如果这一点没法解决，自动化没有太大意义

**Comment by windingwind** [comment]
@TheGodOfKing 
OK，可能是设计思路的不同，你说的确实也是一种使用方法。
我设计的思路是尽量减少窗口切换（文献-笔记）带来的思维割裂与分心，希望用户始终停留在文献阅读界面即可完成所有笔记工作。另外对小屏幕用户来说，分屏两个页面也非常不便。
因此，设计的笔记动作是批注->点击创建子笔记->（可编辑以加上自己的想法或整理）->点击插入位置->关闭子笔记。用户不需要离开文献页面，也不需要关注主笔记中的内容如何排布。主笔记实际上不记录具体的内容，而是以层级+链接形式保存所有子笔记的链接。这也是提供笔记链接功能的目的。
当然用户也可以不遵循这套工作方式，如你所说。

按设计的思路，在不修改子笔记内容的情况下最少需要3次点击（创建子笔记-插入位置-关闭）；相比来回切换笔记-文献窗口（即使是自动插入）也不会增加太多操作步骤。

感谢你的建议，计划在后续版本增加自动插入功能（但不会成为默认选项）。也欢迎讨论交流

**Comment by TheGodOfKing** [comment]
@windingwind 太好了，感激不尽。其实obsidian是有个Note Refactor插件可以把笔记内容打散并且创建链接，所以有不少用户把内容放在主笔记，然后再用插件打散形成原子笔记的结构，我个人就是这种工作流。

**Comment by windingwind** [comment]
@TheGodOfKing 近期计划实现这个功能。有如下方式：
1. 在菜单栏增加一个开关选项，开启时所有新增的批注会自动附加
2. 为每个pdf阅读界面增加一个单独开关，开启时当前pdf的批注会自动附加

另，自动摘录统一到主笔记合适，还是为每个pdf生成一个笔记用于摘录合适？

**Comment by windingwind** [comment]
@AixinjueluoVince

**Comment by TheGodOfKing** [comment]
> > @windingwind太好了，感激不尽。其实obsidian是有个Note Refactor插件可以把笔记内容打散并且创建链接，所以有不少用户把内容放在主笔记，然后再用插件打散形成原子笔记的结构，我个人就是这种工作流。
> 
> 对于你提到的这种方式，按照我的理解，在单独做笔记的时候，因为人的思路是连续的，要一下子分块比较困难，因此集中-拆分的方法有用； 但收集文献信息的过程本身是碎片的，zotero可以在阅读-记笔记的时候至下而上地实现原子化笔记，似乎没有必要碎片-集中-拆分，这样反而多了一步。
> 
> 在开始之前我想最好先讨论清楚具体用途的需要（而不是功能的需要），我还不是很理解为什么要自动摘记到一起再拆开

这就涉及到另一个插件了https://notetocard.com/
这个插件能把整片大纲文章自动制成卡片，与obsidian学习闭环系统这是第一个原因
第二个原因并不是每个用户都需要原子化笔记，有些文章我也是希望笔记集中在一起的，聚合和拆分应该是用户自己选着的，而不是只能拆分不能聚合，这样更能符合大众用户的需求，现在就是拆分容易，但是聚合困难，需要通过拖拽的方式，如果能自动摘录就简单很多。

**Comment by windingwind** [comment]
@TheGodOfKing 
对于你说的从碎片到聚合的过程，在better notes中有三种以上的方法实现。
1. Zotero自带的从注释创建笔记/添加注释到笔记
2. 插件的模板功能可批量导入多个文献下的所有批注，包括可以实现按颜色或标签分类导入（适合先批注完在一并导入）
3. 插件在pdf阅读界面的快速从批注创建笔记并快速添加链接到位置的功能（适合边阅读边导入）

因此我觉得所说的聚合困难并不存在，可以先试下这些功能是否可以满足需要

**Comment by TheGodOfKing** [comment]
@windingwind 我保证这是真实且强的需求可以到这个群看下627574819看下整个群的人都在等你开发这个功能，为的就是zotero与obsidian和anki形成PDF的学习闭环系统，而且这个功能也是目前未有的功能啊，并不是什么优化性的功能。

**Comment by windingwind** [comment]
@TheGodOfKing 我想表达的是，以下这三种方法具体为什么适用/不适用你所说的聚合笔记的需求？

> @TheGodOfKing 对于你说的从碎片到聚合的过程，在better notes中有三种以上的方法实现。
> 
> 1. Zotero自带的从注释创建笔记/添加注释到笔记
> 2. 插件的模板功能可批量导入多个文献下的所有批注，包括可以实现按颜色或标签分类导入（适合先批注完在一并导入）
> 3. 插件在pdf阅读界面的快速从批注创建笔记并快速添加链接到位置的功能（适合边阅读边导入）
> 
> 因此我觉得所说的聚合困难并不存在，可以先试下这些功能是否可以满足需要

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/177945361-62244a91-ad12-47b0-89e5-eaf8a6fbd8e4.png)
please try v0.6.3
