### ISSUE TITLE
[Feature] 建议: 添加高亮位置到笔记中

### ISSUE THREAD

**Issue by maxineliu** [windingwind/zotero-better-notes#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS 13.5 (22G74)
- Zotero Version: 6.0.27
- Plugin Version: 1.0.4

### Describe the feature request

**Why do you need this feature?**
比如, 对一篇文献的实验方法很感兴趣, 总结归纳了5个步骤, 其中每个步骤都是对原文方法中的某一段的总结归纳. 在回看笔记时希望能快速回看文献原文.

### Describe the solution you'd like

**The solution you'd like**
据悉, 原文献每一个高亮都有一个专属的定位链接, 格式类似于zotero://open-pdf/library/items/BFI3KXR3?page=3&annotation=S22II5YR

有没有什么办法能把定位链接快速提取出来, 用markdown或betternotes的插入链接功能将其插入到笔记中. 使在笔记里点击链接就可以定位到原文的高亮位置.

**Comment by windingwind** [comment]
在笔记中点击来自文献的段落，即可通过浮窗转跳原始位置

**Comment by maxineliu** [comment]
是, 我也发现这个功能了, 但这样笔记显得好臃肿, 我现在就是手动提取那个链接, 附在选定文字上
