### ISSUE TITLE
[Feature] Make Note Worskspace a central note manager

### ISSUE THREAD

**Issue by tranhungnghiep** [windingwind/zotero-better-notes#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS 12.6.3
- Zotero Version: 6.0.27
- Plugin Version: 1.0.4

### Describe the feature request

If I understand correctly, Better Notes could be viewed as a "note manager" for existing Zotero notes. To provide values for more potential users, the Note Workspace should have "note managing features". In addition, a note manager UI would provide better user experience than opening a single note or asking to create a new note when first opening.

### Describe the solution you'd like

**The solution you'd like**
The Note Workspace tab would be very useful as a Zotero note manager and center for all note editing if it has:
- List of all Zotero notes to choose from
- List of recently edited notes to choose from
- A button for creating new notes if needed
- Note search, moving/adding note to Zotero folders
- Integrating links with Zotero "Tags" and "Related" links

**Alternatives you've considered**
- Currently the Note Workspace tab asks to create a new note when first opening, but this is rather confusing.
- Another alternative is to use a separate markdown editor (such as Obsidian) to manage/edit Zotero notes. This would require exporting--syncing all Zotero notes to external markdown files. However, syncing may cause conflicts, and currently finding all Zotero notes to export--sync is difficult. So this feature should probably only added after Note Workspace has worked as a note manager.

**Comment by windingwind** [comment]
> List of all Zotero notes to choose from

see `1` below

> List of recently edited notes to choose from

see `2` below

<img width="349" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/33902321/2be2cdc8-f3d8-48ed-ad65-10219a404774">

> A button for creating new notes if needed

That's the popup when no workspace note is set.

> Note search, moving/adding note to Zotero folders

That's what Zotero already provides you.

> Integrating links with Zotero "Tags" and "Related" links

Good suggestion.

**Comment by windingwind** [comment]
> About 1 and 2:

It's the latest prerelease (which is for Zotero 7 only).

> About the popup:

Right. But actually, that's just a null-fallback when no workspace note is set, not a welcoming UI. We used to have a setup wizard, I'll consider having it back.

> About note searching/moving:

That's a little bit too much for this plugin. I don't have much time for that currently. Thanks for the suggestions anyway.

**Comment by windingwind** [comment]
> Currently the Note Workspace tab asks to create a new note when first opening, but this is rather confusing.

This is updated in the latest prerelease.

<img width="987" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/33902321/9dbacdae-5a62-4ab4-ba07-3afcd8910839">
