### ISSUE TITLE
[Feature] Create reference to the parent item for notes that do not come from a PDF

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-better-notes#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 6.0.27
- Plugin Version: 1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
I am finding Better Notes a wonderful way to handle research plans. As I make a statement of fact in the Main Note, I can then add links to every note that provides evidence to support the point I'm making.

As I add these links in the Main Note, I need to know the parent item to which each note containing evidence is attached. This creates the footnote, in essence. While the notes coming out of PDFs put an in-text reference, we don't have that for notes that come from other sources--a note attached to a book item, for example. A link back to the parent would be helpful, also.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

When a note link is embedded into the Main Note, a statement is added to the bottom, that says "Referred in" and gives a link to the Main Note. Could an additional reference be made here to the parent item to which a note is attached? Preferably, it could be a bibliographic reference like:

SOURCE: Ancestry.com. 2004. “1900 United States Federal Census.” Year: 1900; Census Place: Lamar, Randolph, Alabama; Roll: 37; Page: 2B; Enumeration District: 0054; FHL microfilm: 1240037. 

Create a link on the word SOURCE to jump to the parent item, for quick access. If the note is freestanding and has no parent, it could say:

SOURCE: None

If, for some reason, the bibliographic reference cannot be embedded into the note, at least a title, linked to the parent item, would be very helpful.

### Anything else?

![Screenshot 2023-09-27 153234](https://github.com/windingwind/zotero-better-notes/assets/54809262/9c284025-325b-4772-8a5f-4826c3d4b473)

**Comment by windingwind** [comment]
> Could an additional reference be made here to the parent item to which a note is attached? Preferably, it could be a bibliographic reference like:

Yes, that's possible. We use the note template `[QuickBackLink]` to customize the back link. I'll look into that when I have time.

**Comment by DonnaCoxBaker** [comment]
Thanks so much!

                   Visit me at Genohistory.com <https://genohistory.com>
                   Sign up for my Genohistory Notes newsletter!
<https://landing.mailerlite.com/webforms/landing/f0x2k7>

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/776

**Comment by windingwind** [comment]
I notice that you are on Zotero 6, while this template uses new APIs provided by BetterNotes beta, which requires Zotero 7. So... probably you'll have to use a Z7 or wait for the stable release.
