### ISSUE TITLE
[Bug] BN添加双链之后有一个选项遮挡了

### ISSUE THREAD

**Issue by mulei000** [windingwind/zotero-better-notes#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 操作系统：Windows 11 22H2
- Zotero Version: beta.40+
- Plugin Version: 25

### Describe the bug

<img width="306" alt="0444836a64e523f40a7b87db3a9bcb4" src="https://github.com/windingwind/zotero-better-notes/assets/109954307/5b229d03-9c46-40f3-992f-def5e4b1f8a5">

### Debug Output

无

**Comment by mulei000** [comment]
不算bug应该，位置有点小问题

**Comment by windingwind** [comment]
与本插件无关，是链接弹窗与批注弹窗互相覆盖。请向https://forums.zotero.org/discussions 反馈，此处关闭
