### ISSUE TITLE
[Bug] open workspace button is missing after updating the extension 

### ISSUE THREAD

**Issue by mnkhprre** [windingwind/zotero-better-notes#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS ventura 
- Zotero Version: 6.0.1
- Plugin Version: latest 

<img width="713" alt="Screenshot 2023-09-29 at 11 17 29" src="https://github.com/windingwind/zotero-better-notes/assets/54448793/fc0c26b0-2374-4333-acb3-16b11edffa4e">

please make it come back. 

### Describe the bug

open workspace button missing after the upgrade extension the latest version

### Debug Output

version => 6.0.27, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => tr-TR, appName => Zotero, appVersion => 6.0.27, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.27, extension), Zotero Word for Mac Integration (6.0.7.SA.6.0.27, extension), Zotero Better Notes (1.0.4, extension), Zotero PDF Translate (1.0.22, extension, disabled), Night for Zotero (0.4.23, extension, disabled)

(4)(+0010659): SELECT COUNT(*) FROM settings WHERE setting='mImport' AND key='cleanup'

(3)(+0002435): Scheduling next feed update

(4)(+0000001): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1

(3)(+0000002): No feeds with auto-update

### Anything else?

nope

**Comment by windingwind** [comment]
See https://github.com/windingwind/zotero-better-notes#getting-started-with-the-workspace
