### ISSUE TITLE
[Feature] save button  保存键

### ISSUE THREAD

**Issue by guolizhang-tyler** [windingwind/zotero-better-notes#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows
- Zotero Version: 6/7
- Plugin Version: 1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

写完笔记不知道保没保存 而且本地文件搜索不到写的笔记 所以心生疑虑，希望添加个保存按钮

### Anything else?

no

**Comment by windingwind** [comment]
自动保存
