### ISSUE TITLE
[Feature]在复制原文到笔记的时候不想显示注释引文，希望给个全局开关或者快捷键不显示注释引文，一个一个一个去修正

### ISSUE THREAD

**Issue by sometimes-naaive** [windingwind/zotero-better-notes#73]
在复制原文到笔记的时候不想显示注释引文，希望给个全局开关或者快捷键不显示注释引文，一个一个一个去修正点的手疼

**Comment by windingwind** [comment]
参见https://www.zotero.org/support/note_templates
这是zotero控制的功能。可修改设置以决定如何插入。

**Comment by windingwind** [comment]
由于Zotero本身具有该功能，将关闭issue。
