### ISSUE TITLE
[Feature] 请问在pdf中添加笔记后能否选择将两个笔记合为一个？

### ISSUE THREAD

**Issue by feizhilee** [windingwind/zotero-better-notes#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 6.0.27
- Plugin Version: 1.0.4

### Describe the feature request

例如某一大段文章换页了，但是直接跨页选中会包括一些无关文字（例如页眉、页尾、注释等）在其中，因此这一大段需要分开选择，但是这样会导致创建了两个笔记，目前好像没有找到能够合二为一的方法。

### Describe the solution you'd like

能够将两个笔记合二为一；亦或者增加快捷键，比如先选中前一页的内容，然后按住 alt + 鼠标左键能够继续选中，目前我看 translate 插件就是这样的

**Comment by windingwind** [comment]
批注功能与本插件无关，谢谢建议，此处关闭
