### ISSUE TITLE
文科博士建议：可以增加嵌套表格和手写笔功能吗？[Feature] 

### ISSUE THREAD

**Issue by doctorofeyes** [windingwind/zotero-better-notes#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win11
- Zotero Version: 6.0.27
- Plugin Version: 1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.
希望增加类似OneNote中的嵌套表格或者思维导图功能，如果实现不了，增加手写笔功能能够自己画也可以。对于大部分逻辑和结构比较复杂的文献，不借助思维导图和嵌套表格很难完成高质量的笔记。Bnote要是能够增加这两项功能，不仅可以真正实现all in one，简直可以用两个字来形容，爆炸！！

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by yzy1228682367** [comment]
嵌套表格/欢呼

**Comment by windingwind** [comment]
嵌套表比较困难，思维导图我觉得也确实有需要。但由于我精力有限，本插件只提供基础的笔记功能增强，可以由其他新插件在bn的基础上实现，我相信也不会太困难
