### ISSUE TITLE
导出条目时，笔记中希望能包含有图片 

### ISSUE THREAD

**Issue by wqfuian** [windingwind/zotero-better-notes#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0
- Plugin Version: 1.1.4-25

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
将条目导出为Zotero RDF
☑导出笔记
☑导出文件
☑包括注释
重新导入到其他人的电脑中，笔记里缺失图片。如下图
![image](https://github.com/windingwind/zotero-better-notes/assets/58714360/ddf05930-bc57-4e2a-aa47-fd390d041b0d)

只有图片的轮廓，看不到图片

**Why do you need this feature?**
A clear and concise description of why you need this feature.
为重要的文献做了图片笔记，分享给课题组其他人时，别人看不到笔记中的图片，不利于此类笔记的共享交流

### Describe the solution you'd like

**The solution you'd like**
希望导出文件为Zotero RDF时，笔记里包含图片
**Alternatives you've considered**
我看图片在......\Zotero\storage\下面，也许通过笔记与图片文件间的链接，能把图片导出，只知道这么多，其他的希望大佬能解决一下，谢谢！

**Comment by windingwind** [comment]
用插件提供的导出，不要用默认的

**Comment by wqfuian** [comment]
> 用插件提供的导出，不要用默认的

我试了大佬说的插件提供的导出，如下图
![image](https://github.com/windingwind/zotero-better-notes/assets/58714360/2483899e-872e-41fa-9d9e-c4c65321e58e)有两方面的需求，1.希望能批量导出，2.希望导出的是笔记，而不是pdf或word，导出的笔记分享给别人，别人能够导入到zotero中，且包含图片，这样的话别人能在在原有的笔记基础上继续做笔记。

**Comment by windingwind** [comment]
有没有可能你说的都有

**Comment by wqfuian** [comment]
> 有没有可能你说的都有

有可能。我倒腾半天，把B站的视频也看了，但导出的笔记还是没有图片

**Comment by wqfuian** [comment]
> 有没有可能你说的都有

解决了，知道怎么用了，虽然给我说的功能不太一样，但是确实能导出带图片的markdown

**Comment by wqfuian** [comment]
> 有没有可能你说的都有

解决了，知道怎么用了，虽然给我说的功能不太一样，但是确实能导出带图片的markdown

**Comment by tianjiaoshanzai** [comment]
请问是怎么解决的呢，我也想导出带图片的。多个文献导出在一个笔记
