### ISSUE TITLE
[Feature] Latex support for exporting to pdf?

### ISSUE THREAD

**Issue by tomohiro-soejima** [windingwind/zotero-better-notes#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 6.0.27
- Plugin Version: 1.0.1

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
When I export a Zotero note that includes latex elements, the resulting PDF does not process latex elements, and instead simply prints $$ x^2 $$ etc. It would be very nice to be able to render latex, so that what I see in Zotero is exactly what I export.

### Describe the solution you'd like

**The solution you'd like**
Latex gets rendered correctly when exporting to PDF. If it is easier, I do not mind if the export format needs to be html instead of PDF.

### Anything else?

Thank you for a great plugin!

**Comment by windingwind** [comment]
fixed in the latest prerelease
