### ISSUE TITLE
跨设备同步图片无法显示[Bug] 

### ISSUE THREAD

**Issue by doctorofeyes** [windingwind/zotero-better-notes#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 6
- Plugin Version: newest

### Describe the bug

如题

### Debug Output

如题

**Comment by windingwind** [comment]
与插件无关，请向https://forums.zotero.org/discussions 反馈

**Comment by jiuwu-zzx** [comment]
我有相同的问题，我同步到ipad上的笔记无法显示图片，在论坛里我似乎没有找到相似问题，请问你解决了吗？

**Comment by doctorofeyes** [comment]
> 我有相同的问题，我同步到ipad上的笔记无法显示图片，在论坛里我似乎没有找到相似问题，请问你解决了吗？
没有。不过有代替方法。在电脑上把笔记完整导出后平板上看。

**Comment by jiuwu-zzx** [comment]
> > 我有相同的问题，我同步到ipad上的笔记无法显示图片，在论坛里我似乎没有找到相似问题，请问你解决了吗？
> > 没有。不过有代替方法。在电脑上把笔记完整导出后平板上看。

请问你是导出什么格式呢，我导出html发现也看不见图片，我猜测图片不是那种链接形式，所以同步不了，在论坛里我发现个类似的，但也没有找到可用的方案https://forums.zotero.org/discussion/comment/447074#Comment_447074

**Comment by doctorofeyes** [comment]
> > > 我有相同的问题，我同步到ipad上的笔记无法显示图片，在论坛里我似乎没有找到相似问题，请问你解决了吗？
> > > 没有。不过有代替方法。在电脑上把笔记完整导出后平板上看。
> 
> 请问你是导出什么格式呢，我导出html发现也看不见图片，我猜测图片不是那种链接形式，所以同步不了，在论坛里我发现个类似的，但也没有找到可用的方案https://forums.zotero.org/discussion/comment/447074#Comment_447074

这个问题我记得当时联系过作者大大，处理起来相当复杂，后面就没管这了。
图片可以直接复制出来。复制到其他文字处理软件上面就不受影响了。
个人感觉这个插件有适用场景，并非十全十美，它的优点是比较适合在阅读过程中做笔记，很方便。但是排版和保存方面就比较一言难尽了。我现在是读文献的时候用这个做完，然后用其他笔记软件排版和保存。供参考吧。用惯了还好。

**Comment by windingwind** [comment]
图片同步走官方同步/webdav。如果用了webdav，则必须两边设置相同的webdav。其他同步方式都无法起作用

**Comment by jiuwu-zzx** [comment]
好的，谢谢二位的回答
