### ISSUE TITLE
[Feature] 笔记中使用latex插入数学公式的时候，希望能够在Latex预览模式下可以编辑公式之外的文本。代码状态不利于笔记内容的梳理。

### ISSUE THREAD

**Issue by pyfriday** [windingwind/zotero-better-notes#74]
插入数学公式的笔记，特别是整理理论知识的笔记中，代码状态的公式阅读体验非常不友好。在梳理笔记内容的时候，要是在公式的预览模式下，编写笔记的文本内容，会极大提高阅读体验，有利于思路的整理。

**Comment by windingwind** [comment]
这确实是一个问题，但可能将会有较低的优先级

**Comment by whyihaveyou** [comment]
> 这确实是一个问题，但可能将会有较低的优先级

可以设计一个快捷键，让读者方便地在编辑和预览模式之间转换，应该比“编辑公式之外的文本”更容易实现。

**Comment by whyihaveyou** [comment]
> 这确实是一个问题，但可能将会有较低的优先级

可以设计一个快捷键，让读者方便地在编辑和预览模式之间转换，应该比“编辑公式之外的文本”更容易实现。

**Comment by windingwind** [comment]
快捷键一直有的，和typora一样是ctrl/command+‘/’

**Comment by whyihaveyou** [comment]
谢谢

另外我发现，有些时候，在条目笔记的侧边栏里这个快捷键才是有用的，而点了按钮进入工作区之后，再按就不行了。但如果重新设置一次主笔记（设置成其他笔记再设置回来），这个快捷键又可用了，不知道是否是bug，或者是我的快捷键冲突所致。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月1日 0:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [windingwind/zotero-better-notes] [Feature] 笔记中使用latex插入数学公式的时候，希望能够在Latex预览模式下可以编辑公式之外的文本。代码状态不利于笔记内容的梳理。 (Issue #74)


快捷键一直有的，和typora一样是ctrl/command+‘/’

―
