### ISSUE TITLE
[Feature] 希望笔记同步时按原文同步，而不要自动转码

### ISSUE THREAD

**Issue by HIEROT** [windingwind/zotero-better-notes#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win 11 22H2
- Zotero Version: 
- Plugin Version: 1.0.4

### Describe the feature request

MarkDown格式笔记同步时似乎自动将链接转化为URL的百分号编码导致一些非预期行为
例如Obsidian中内链的格式使用了空格，^，或#等，都会被转化为%XX从而导致在那边不再可用

### Describe the solution you'd like

希望同步笔记时按文本原样，而不是自动转码

**Comment by HIEROT** [comment]
稍微看了下代码，应该是在md2note中的md2remark时转化了这些链接，不过再一次同步过去的时候这些链接却没有转回原来的文本

**Comment by HIEROT** [comment]
可能需要在remark2md中进行一些处理？谢谢作者！

**Comment by windingwind** [comment]
请提供样例截图

**Comment by HIEROT** [comment]
例如首先在Obsidian中输入这样的链接

![屏幕截图 2023-10-11 191505](https://github.com/windingwind/zotero-better-notes/assets/55292746/6d48a98b-d787-46bb-b648-be286d5c0ac4)

接下来在Zotero Better Notes中使用同步（手动或自动），在Obsidian那边看来文件就会变成这样
![屏幕截图 2023-10-11 191552](https://github.com/windingwind/zotero-better-notes/assets/55292746/8542633a-2afe-41af-b047-399f23de4caf)

**Comment by KL2101** [comment]
类似的需求反馈——能否markdown图片的链接，直接渲染链接，而不是在zotero中将图片直接存在了本地，同步后图片的格式发生了变化。（具体见下图）

1. Obsidian markdown本身的图片链接
![](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/202310142339992.png)

2. 笔记同步后，图片的链接
![](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/202310142340693.png)

**Comment by windingwind** [comment]
@KL2101 不同的需求请单独开issue。

另外zotero笔记不支持渲染在线来源的图片，故无法实现。关于此请求不再回复

**Comment by HIEROT** [comment]
我在Zotero Integration （是一款Obsidian插件）中看到了很好的转化方式
![image](https://github.com/windingwind/zotero-better-notes/assets/55292746/6ee87c5f-6e4e-441f-ac7b-df4b209baef1)
也就是在md文件这边只保留链接样式，在从md文件向note同步时，由better-notes插件识别这些链接，如果是Zotero内部item链接再提取item信息转化为Zotero内部链接，而不是把这些信息也变成html样式留在md文件内，如下图这样，会不会更好呢？
![image](https://github.com/windingwind/zotero-better-notes/assets/55292746/5271933e-ccdc-4796-9f14-7dc116d5d289)

**Comment by HIEROT** [comment]
关于原问题找到一个Alternative，就是将ExportMDFileContent模板改为
```
${{
  return mdContent.replace("\\\[\\\[","[[");
}}$
```
即可

**Comment by windingwind** [comment]
> 也就是在md文件这边只保留链接样式，在从md文件向note同步时，由better-notes插件识别这些链接，如果是Zotero内部item链接再提取item信息转化为Zotero内部链接，而不是把这些信息也变成html样式留在md文件内，如下图这样，会不会更好呢？

单个citation中可能引用多个条目，还带有页码、前后缀等等信息，ob int的做法在这些情况下会丢失信息，因为一个z链接只包含单个条目的信息。

我可以设想的一个妥协方案是，由BN在zo中支持一种新的链接类型（例如zotero://bn-data），将所有现在以富文本形式在markdown中保存的信息，放入单个链接（但可能会很长），由此可将各类信息全部集中在一个链接中。

另外关于同步时的优先级，也并非笔记优先或md优先，而是最新更改的一处优先。因此很难保证升级时的兼容性，会需要进行一次覆盖所有md的同步
