### ISSUE TITLE
[Bug] “复制当前节”功能无效

### ISSUE THREAD

**Issue by RunningDog0** [windingwind/zotero-better-notes#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.44
- Plugin Version: 1.1.4-23

### Describe the bug

在笔记中点击右上角小齿轮，选择“复制当前节”或者“复制当前行”。
然后粘贴在其他笔记中，复制的内容实际上是**整篇笔记**，**而不是当前节或者当前行**。

该问题可100%复现，已附上debug报告，不知是否有帮助

### Debug Output

1697029655860	addons.xpi	WARN	Checking D:\software\Zotero_win-x64\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1697029656426	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\Shouxiang\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.44+64a78412c, os => Windows 10.0 22621, locale => zh-CN, extensions => Better Notes for Zotero (1.1.4-23, extension), ZotFile (5.1.2, extension, disabled), Zotero Tag (0.3.0, extension, disabled), DOI Manager (1.4.2, extension, disabled), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), Translate for Zotero (1.1.0-17, extension, disabled), Jasminum (1.0.0-6, extension, disabled), Green Frog (0.16.02, extension, disabled), Zotero One (5.2.2, extension, disabled)

**Comment by windingwind** [comment]
请提供截图

**Comment by RunningDog0** [comment]
首先点击复制当前节![image](https://github.com/windingwind/zotero-better-notes/assets/147246491/0cc9c624-b1ef-444f-bc3d-9c4ad4f81780)
以下链接被复制：zotero://note/u/FYR3DYT8/?section=(Perry-Smith%20%E5%92%8C%20Mannucci%2C%202017)%20AMR%20-%20The%20journey%20of%20an%20idea
但是，粘贴后的内容是整篇笔记，而不是当前节
![image](https://github.com/windingwind/zotero-better-notes/assets/147246491/7f35c51c-a4c1-449a-8ea8-10318ecf1d4c)
点击编辑链接我们可以看到：zotero://note/u/FYR3DYT8/?ignore=1&section=(Perry-Smith%20%E5%92%8C%20Mannucci%2C%202017)%20AMR%20-%20The%20journey%20of%20an%20idea

**Comment by windingwind** [comment]
1. 链接的定位（节/行）仅在点击链接打开时有效。
2. 你用的功能叫做`展开（嵌入）笔记链接`，会将子笔记整个嵌入当前链接后。
因此不是bug，此处关闭，感谢反馈
