### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ssmbyd** [windingwind/zotero-better-notes#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 6.0.27
- Plugin Version: 最新的那个版本，最上面的。

### Describe the bug

大大您好，我想咨询一下，为什么我下的6.0.27不能安装您最新发的zotero-better-notes哎，一直显示无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容

### Debug Output

没有成功

**Comment by wangbofan** [comment]
u should to download the version 1.0.4

**Comment by ssmbyd** [comment]
你投递的应聘简历已收到，我们将及时处理，10日内给予回复，请耐心等待。谢谢！

**Comment by ssmbyd** [comment]
非常感谢😊



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 15, 2023 10:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [windingwind/zotero-better-notes] [Bug]  (Issue #747)




 
u should to download the version 1.0.4
