### ISSUE TITLE
[Feature] 自定义yaml front matter

### ISSUE THREAD

**Issue by KL2101** [windingwind/zotero-better-notes#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS 14.0
- Zotero Version: 7.0.0
- Plugin Version: 1.1.4-25

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
我希望通过zotero同步obsidian笔记，同时，obsidian设置了front matter，同步之后仅保留了从zotero-better-notes中的front matter。
**Why do you need this feature?**
希望保持zotero与obsidian的笔记同步，并不要影响front matter

### Describe the solution you'd like

**The solution you'd like**
可以自定义better-notes中的front matter，最好是在笔记上明文显示

**Alternatives you've considered**
另一个思路，仅同步正文内容，不同步yaml部分。

### Anything else?

这是从zotero-better-notes中同步过来的front matter，覆盖了原来obsidian笔记中设置的yaml front matter。
![](https://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/202310142350752.png)

供参考，感谢。

**Comment by KL2101** [comment]
忽略我的提问，没有看见类似的讨论→https://github.com/windingwind/zotero-better-notes/issues/527

**Comment by windingwind** [comment]
请在#527中提供反馈，此处关闭
