### ISSUE TITLE
[Bug] images are misplaced in Export linked Notes To Markdown

### ISSUE THREAD

**Issue by Sleepwalker6** [windingwind/zotero-better-notes#75]
When I choose "Export note to md" and "Export linked notes to md" images of different notes are mixed up and are misplaced. 
Here I made an experiment. 

1. Imagine I have 3items each with corresponding pdf in my zotero database. 1-Book of jungle 2.Book of Sea 3.Book of desert 
![image](https://user-images.githubusercontent.com/106707747/175380388-29f2a76d-564c-4863-95f5-9fbfd3f2742b.png)

2. I annotate those pdfs and create notes from those annotations in zotero. 
![image](https://user-images.githubusercontent.com/106707747/175380751-2e1be18f-7482-49f1-af81-b3a139578909.png)

3. I create a main note and export it to md file along with the linked notes.

![image](https://user-images.githubusercontent.com/106707747/175380841-dcabff18-5d4c-42ec-b62c-164c80689317.png)

4. When I open the linked files in obsidian images are either missing or misplaced (images are mislabled)
For example the difference between exported markdown and its original note in zotero for Jungle Book is shown below:
![image](https://user-images.githubusercontent.com/106707747/175381185-c8eb505c-f564-45b9-bc7f-e20342aa0acd.png)

- When I choose export note + Embed linked notes everything works fine.
I know it is weird. But that's what happens to my files!

**Comment by windingwind** [comment]
Thanks for the report. Could you please paste the contents of the 'attachments' folder under the export dir?

**Comment by Sleepwalker6** [comment]
Thanks.
![image](https://user-images.githubusercontent.com/106707747/175526875-a3b4d516-17d1-4069-abe7-559f8dd77732.png)

These are the eport dir in two export mode: 1) Embed export 2)linked
[embed export](https://www.mediafire.com/file/u6g3flzdellwu5k/embed+export.rar/file)
[linked export](https://www.mediafire.com/file/yv3ywgk21yf9uii/Linked+export.rar/file)

Thanks for the help.

**Comment by windingwind** [comment]
Maybe we could fix #35 first and turn to this issue later. This is even more strange than the broken link issue.

**Comment by windingwind** [comment]
any updates? If not, I’ll close this issue.
