### ISSUE TITLE
跳转到PDF指定页面功能异常

### ISSUE THREAD

**Issue by xuewei5113** [windingwind/zotero-better-notes#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 10.15
- Zotero Version: Zotero 7
- Plugin Version: 1.0.4; also Pre-release 1.14-25

### Describe the bug

一般情况下，从Annotation中直接添加到笔记中后：
- 图片下的**引用**功能为“Show Item“，跳转到Library的item功能正常；
    
- 无跳转到指定页面的功能，此时引用中的页面显示为“（Name, Date, **p.18**）”。但这个本质上并不算问题，因为本身这里就只有“Show item”的功能。
<img width="641" alt="image1" src="https://github.com/windingwind/zotero-better-notes/assets/148515528/b22385a0-9c66-4576-beac-d4197faba781">

- 通过点击下方引用，然后“**Edite Citation**” - “输入**指定页码**” - “**确认**”之后，可以将引用改为如下“（Name，Date，**Page 18）**”的格式，此时引文中的页码描述发生了变化（由p.18 改为page.18）并且**“Show Item“选项卡消失，取而代之的是”Go to Page“**。

<img width="643" alt="image2" src="https://github.com/windingwind/zotero-better-notes/assets/148515528/0518ef20-1cf9-45a8-90f9-950d3e3ab135">

- 在Zotero 6中，通过点击“Go to Page”**可以实现**在不打开pdf文件的情况下直接跳转至指定页面，应该也是这样设计的；
- 但在Zotero 7中只能帮助打开pdf（回到上次阅读位置），无法跳转到引用中“page”的指定位置。
    
- 该功能在插件的V.1.04，以及预览版V. 1.14-25中均无法正常使用。
- 希望作者能够将“Go to page“的功能进行修复，这个简直太重要啦。
    
- 感谢作者的付出！

### Debug Output

[Debug Output.html.zip](https://github.com/windingwind/zotero-better-notes/files/13050038/Debug.Output.html.zip)

**Comment by xuewei5113** [comment]
这个异常我只是从annotation添加图片时发现的，应该是所有的出现在笔记中的citation都有这种情况，比如手动插入一个citation也是无法实现页面跳转的。

**Comment by windingwind** [comment]
非插件功能，请向zotero论坛反馈
