### ISSUE TITLE
[Feature] a box or menu to control the autosyncing process

### ISSUE THREAD

**Issue by Sleepwalker6** [windingwind/zotero-better-notes#76]
**Is your feature request related to a problem? Please describe.**
Maybe I am using the syncing feature wrong but some times the addon creates auto updates for notes that I had previously enabled autoupdate but the note has been removed from the main note or even after I created another main note and removed the old main note.
**Describe the solution you'd like**
a menu or a box to show those link that are auto updating, and options to stop, resume or kill the process.

**Comment by windingwind** [comment]
Thanks. This is planned!

**Comment by windingwind** [comment]
Click the 'export' button of an already syncing note and you can disable the sync for all related notes in the sync status window.
