### ISSUE TITLE
[Bug] 笔记导出时，选择区域功能异常

### ISSUE THREAD

**Issue by HIEROT** [windingwind/zotero-better-notes#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: Zotero 7（但在Zotero6中也是如此）
- Plugin Version: [1.1.4-27](https://github.com/windingwind/zotero-better-notes/releases/tag/1.1.4-27)

### Describe the bug

在PDF阅读器中，使用选择区域工具标记一片区域后，右键添加笔记
![image](https://github.com/windingwind/zotero-better-notes/assets/55292746/f5e0a29a-176e-48d6-a3a4-2356458500d3)
在同步前，右侧笔记区是内链
![image](https://github.com/windingwind/zotero-better-notes/assets/55292746/bd781dff-c7d5-4bac-9f54-4d906eaa2b3d)
接下来导出并同步MD笔记，可见其被导出为图片文件，并放在attachments子目录下（注意文件名）
![image](https://github.com/windingwind/zotero-better-notes/assets/55292746/60216015-9766-48f0-8a6b-1585ac4c806c)
接下来，每与MD文件同步一次，MD这边的附件链接都会被更新，对应图片也不断复制，实际上使得该功能不太可用。此外在Zotero笔记侧，图片也失去链接性质，不能再打开对应标记区域。

### Debug Output

若您有需要，我再将Debug部分去除隐私内容提交给您。

**Comment by windingwind** [comment]
最新prerelease已修复

**Comment by HIEROT** [comment]
谢谢！

**Comment by HIEROT** [comment]
本issue上一条评论中已经说明了复现bug的步骤，请查阅，谢谢~
