### ISSUE TITLE
[Feature] 希望Logseq notes 的大纲结构 在同步时能够被保留

### ISSUE THREAD

**Issue by chs33** [windingwind/zotero-better-notes#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 7
- Zotero Version: 6 
- Plugin Version: 1.04

### Describe the feature request

Logseq中的大纲结构(block) 是用markdown的“-” 来表示，BN会在同步时自动将其改成“*”， 在Logseq就无法正确的显示了:

同步前：
![image](https://github.com/windingwind/zotero-better-notes/assets/16418270/9145bd43-bd93-4b8b-b3de-e1a5ead66b00)
在logseq里的效果
![image](https://github.com/windingwind/zotero-better-notes/assets/16418270/8000fd0a-94c7-45c7-8fc0-5a00d78bef5d)

同步后：
![image](https://github.com/windingwind/zotero-better-notes/assets/16418270/5bc11535-13e8-41fe-b8ab-891062618227)

在logseq里的效果
![image](https://github.com/windingwind/zotero-better-notes/assets/16418270/a3b7a3e0-9023-4a2a-a63c-03c196989a0b)

**Comment by windingwind** [comment]
Use `[ExportMarkdownContent]` template to parse the markdown before saving to file.

**Comment by chs33** [comment]
> Use `[ExportMarkdownContent]` template to parse the markdown before saving to file.

How did you do that? Sorry I search the forum and doc didn't find answer

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/768
