### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wilcoxonumi** [windingwind/zotero-better-notes#77]
1. 中文用户指引 3.5 更新链接文本 功能无法使用

 

>    3.5 更新链接文本
>    点击链接弹窗中的'update link text'来更新选择的笔记链接文本。
>   💡 尝试一下!
>   在预览区域中编辑某个链接笔记的第一行文本，然后在主笔记区域更新它的链接文本。

点击update link text后主笔记区域不更新

2. 中文用户指引 3.4中的“链接弹窗中的'import note'”选项不显示

<img width="189" alt="image" src="https://user-images.githubusercontent.com/61941630/175387512-6c447c08-6ad2-4db7-bd38-4b6f26859720.png">

**Comment by windingwind** [comment]
更新链接文本仅在子笔记的标题行修改后才有作用。

**Comment by wilcoxonumi** [comment]
> 更新链接文本仅在子笔记的标题行修改后才有作用。

噢原来！谢谢
