### ISSUE TITLE
[Bug] Reopen #763

### ISSUE THREAD

**Issue by HIEROT** [windingwind/zotero-better-notes#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11
- Zotero Version: Zotero 7
- Plugin Version: .30

### Describe the bug

如issue #763，图片被复制的问题暂未修复。

### Debug Output

无

**Comment by windingwind** [comment]
I'll need steps to reproduce and debug output.

**Comment by windingwind** [comment]
And, please just open that issue again. Do not create an empty issue points to another issue. Close here
