### ISSUE TITLE
[Feature] Jump to bibliography entry / article item

### ISSUE THREAD

**Issue by renyuneyun** [windingwind/zotero-better-notes#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Linux & MacOS
- Zotero Version: 6.0.29
- Plugin Version: 1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
When viewing notes in note workspace provided by this plugin, almost all buttons are about information within and across **notes**. In particular, there is no way to jump to the **article**/**entry** that contains the note.

**Why do you need this feature?**
Having this feature allows navigating between notes and the bib entries which contain them. I often use notes to record key information, and organize the notes. However, often I still need to jump to the original article for further operations (e.g. seeing the bib entry name to be added to paper; adding a new note with different focus). Currently, it is very inconvenient, because the best I can do is:
1. open note
2. click on the gear on top-right corner
3. click on "open attachment"
4. copy the paper title
5. go back to main view, and search the paper title

Here, also, the name "attachment" is quite misleading. It actually means the attachment of the bib entry, but the location it appears seems to indicate this is an attachment of the note.

### Describe the solution you'd like

**The solution you'd like**
A button to directly jump to the bib entry that contains the current note.

**Alternatives you've considered**
A button when clicking on the "linked note" (in the note workspace), that allows to jump to the bib entry.

**Comment by windingwind** [comment]
Sorry but I am not sure what you are looking for.

- If you want to insert the information of the parent item of note (i.e. the bib you mentioned), then take a look at templates like https://github.com/windingwind/zotero-better-notes/discussions/758
- If you want to jump back to a specific position of a PDF/EPUB, use highlights;
- Or are you requesting a new feature to show note item in the library?

**Comment by renyuneyun** [comment]
> Or are you requesting a new feature to show note item in the library

Yes indeed this is the feature request. Actually the request is to show the library entry that contains this note item; but that's roughly the same.

**Comment by mjthoraval** [comment]
The latest plugin update has added a `Show in Library` in the top right gear menu of the note.
What is the difference between this new menu entry and the one already available as a Zotero feature from the three dots menu just below?

**Comment by windingwind** [comment]
In the workspace, the built-in show in library is not available.

**Comment by mjthoraval** [comment]
If you open the note in a new window, then it gives you twice the same link:
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/88db49de-b559-47ce-9062-9481d279b7d3)
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/39009ae6-57e3-403d-a15d-f9a39efedfd6)

Would it be better to add the `Show in Library` menu option in the same location as the built-in Zotero feature (in the three-dots menu, to be consistent), only in places where it is missing?
