### ISSUE TITLE
[Bug] 尝试导入了n多模板，全都无法正常导入到子条目中，模板编辑器里能显示，但语句全是报错

### ISSUE THREAD

**Issue by wwgx** [windingwind/zotero-better-notes#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: 7
- Plugin Version: latest

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/150100792/b4a59b15-95d4-4e79-87e7-5c9413eee113)

### Debug Output

从剪贴板导入模板

**Comment by windingwind** [comment]
report to the template author.
