### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Smx2022** [windingwind/zotero-better-notes#79]
**Describe the bug**
打字过程突然报错卡死，之后就白屏了，内容全都消失，心痛，忘了第一时间截图，只能描述到这里了，下次如果又遇到再补充吧

**Comment by Smx2022** [comment]
卡死之前我粘贴过图片，但不是紧跟着的上一步操作，卡死时我正在修改标题级数。

**Comment by windingwind** [comment]
是否配置了Zotero的数据同步？如果有数据同步，一般十几秒就会把当前的笔记同步上去，即使崩溃也不会丢失数据的。如果同步了却仍然丢失数据，可能是Zotero的问题

**Comment by Smx2022** [comment]
谢谢指导，我刚装了两天，确实还没有同步，另外，您能否添加一个笔记窗口的置顶，这样可能更方便一些。
![(TL1T20}I}J3CY2EP%4`JVR](https://user-images.githubusercontent.com/102869364/176448255-a4dc4a1d-8e14-4da2-8e44-984442592da7.png)

**Comment by windingwind** [comment]
由于卡死问题未见其他报告且不清楚是否是插件问题，将关闭该issue。如果再次遇到，可随时再打开。
