### ISSUE TITLE
[Feature] Note selector pane on the left

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.49+1bb6722c4 (64-bit)
- Plugin Version: 1.1.4-33

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I would like to navigate quickly between notes, in the same way as when using the left pane in Obsidian or Evernote.

**Why do you need this feature?**
I want to use that pane to:
- Quickly look through recently edited notes
- Search for a note
- Quickly add links between notes by drag and drop or a copy-paste shortcut

### Describe the solution you'd like

**The solution you'd like**
I would like to have a left pane similar to the one in Obsidian.
It should also display the colored tags of the notes.

**Alternatives you've considered**
I have tried to use the `Notes` pane from Zotero on the right side.
But:
- It cannot interact with the other notes editing panes
- It cannot show the colored tags
- I prefer to have it on the left side

### Anything else?

Thank you!

**Comment by windingwind** [comment]
Maybe after the stable release of Z7. Please ping me if I forget

**Comment by mjthoraval** [comment]
Thank you.
