### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ChukieWu** [windingwind/zotero-better-notes#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.1 (23B74)
- Zotero Version: 7.0.0-beta.49+1bb6722c4
- Plugin Version: 1.1.4-28

### Describe the bug

mac再安装better-notes插件之后在我的文库那边没有创建工作区这个选项

### Debug Output

D295955225

1699368369586	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1699368370280	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{33d9b940-9aec-4082-9a40-c77435f0d3a2} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "this._id(...) is null" {file: "chrome://zotero/content/elements/relatedBox.js" line: 131}]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{33d9b940-9aec-4082-9a40-c77435f0d3a2} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: previewTab is null" {file: "jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/chrome/content/scripts/pdfpreview.js" line: 1724}]
updatePreviewTab@jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/chrome/content/scripts/pdfpreview.js:1724:7
onPreview@jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/chrome/content/scripts/pdfpreview.js:2001:5
listener@jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/chrome/content/scripts/pdfpreview.js:1798:21
set selectedIndex@chrome://global/content/elements/tabbox.js:207:14
set selectedPanel@chrome://global/content/elements/tabbox.js:225:7
set selectedIndex@chrome://global/content/elements/tabbox.js:549:11
set selectedIndex@chrome://global/content/elements/tabbox.js:71:9
onShutdown@jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/chrome/content/scripts/pdfpreview.js:1996:36
shutdown@jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/pdfpreview@windingwind.com.xpi!/bootstrap.js:58:28
_callMethod@chrome://zotero/content/xpcom/plugins.js:205:23
onDisabled@chrome://zotero/content/xpcom/plugins.js:466:13
callAddonListeners@resource://gre/modules/AddonManager.jsm:1519:48
callAddonListeners@resource://gre/modules/AddonManager.jsm:3570:52
updateAddonDisabledState@resource://gre/modules/addons/XPIDatabase.jsm:2772:29

[JavaScript Error: "item is undefined" {file: "chrome://zotero/content/itemPane.js" line: 114}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "TypeError: Zotero.ZoteroCitation is undefined" {file: "jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/zoterocitation@polygon.org.xpi!/chrome/content/scripts/index.js" line: 5462}]

[JavaScript Error: "TypeError: Zotero.ZoteroCitation is undefined" {file: "jar:file:///Users/chukiewu/Library/Application%20Support/Zotero/Profiles/si9xd70n.default/extensions/zoterocitation@polygon.org.xpi!/chrome/content/scripts/index.js" line: 5462}]

appName => Zotero, version => 7.0.0-beta.49+1bb6722c4, os => macOS 14.1, locale => zh-CN, extensions => Better Notes for Zotero (1.1.4-28, extension), Jasminum (1.0.0-6, extension, disabled), Zotero GPT (0.3.0, extension, disabled), Ethereal Style (3.2.5, extension, disabled), Easier Citation (0.4.2, extension, disabled), Crush Reference (0.6.3, extension, disabled), Actions and Tags for Zotero (1.0.0-23, extension, disabled), Green Frog (0.16.03, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled)

(4)(+9536900): Unregistering notifier observer in notifier with id 'noteWindow_rm'

(4)(+0000003): Unregistering notifier observer in notifier with id 'noteEditor_fx'

(4)(+0000000): Unregistering notifier observer in notifier with id 'undefined'

(3)(+0012188): Getting contents of /Users/chukiewu/Library/Application Support/Zotero/Profiles/si9xd70n.default/treePrefs.json

(3)(+0000007): Writing column prefs of length 7251 to file /Users/chukiewu/Library/Application Support/Zotero/Profiles/si9xd70n.default/treePrefs.json

(3)(+0007606): HTTP POST "1699368369586 addons.xpi WARN …" (5940 chars) to https://repo.zotero.org/repo/report?debug=1

(3)(+0000010): POST body gzipped from 5940 to 1448; 76% savings

(5)(+0000003): CookieSandbox: Being paranoid about channel for repo.zotero.org

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to repo.zotero.org

(5)(+0000930): CookieSandbox: Being paranoid about channel for repo.zotero.org

(5)(+0000000): CookieSandbox: No Set-Cookie header received for repo.zotero.org

(3)(+0000003): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

**Comment by windingwind** [comment]
以主页readme为准。
