### ISSUE TITLE
[Feature] 希望能够在不同的主笔记之间快速切换

### ISSUE THREAD

**Issue by Loticyang** [windingwind/zotero-better-notes#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Plugin Version: 

### Describe the feature request

目前，设置主笔记的方法是，找到某一个笔记，右键菜单设为主笔记。

当我们进行多任务同时推进时，需要经常在不同的主笔记之间切换。如果按照目前的安排，需要：（1）找到相应的文件夹；（2）找到相应的条目；（3）展开该条目，在下面找到主笔记；（4）右键设置为主笔记。

这个步骤就比较冗长。

希望能有一个快速切换的功能。比如，能够在最近设置的5个主笔记之间快速切换。

个人使用中的需求。供作者考虑，谢谢！

**Comment by windingwind** [comment]
latest prerelease (Zotero 7)

![image](https://github.com/windingwind/zotero-better-notes/assets/33902321/73242287-04c2-4792-8d31-9dfdc320710d)

**Comment by Loticyang** [comment]
谢谢。目前还在使用zotero6，没有注意到最新版的功能。谢谢回复。
