### ISSUE TITLE
[Bug] Hidden top right note menu

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.49+1bb6722c4 (64-bit)
- Plugin Version: 1.1.4-36

### Describe the bug

The top right menu wheel of the note editor is too narrow.
There is not enough space to show the Section number.
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/fc276bde-6a7e-48d5-bc33-19ec96b7534a)

### Debug Output

1699477228272	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1699477229511	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 655}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:655:7

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{54f7c80d-4fad-4038-a3a3-db9a3eea5c82} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.49+1bb6722c4, os => Windows 10.0 19045, locale => en-GB, extensions => Better Notes for Zotero (1.1.4-36, extension), Open PDF for Zotero (0.0.8, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Zotero Better Authors (4.0.2, extension, disabled), Actions and Tags for Zotero (1.0.0-23, extension, disabled), Translate for Zotero (1.1.0-21, extension, disabled), Better BibTex for Zotero (6.7.136, extension, disabled)

(3)(+0020051): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

**Comment by windingwind** [comment]
i'll take a look (when i have time...)
