### ISSUE TITLE
[Feature] More precise information in note links to line or section

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.49+1bb6722c4 (64-bit)
- Plugin Version: 1.1.4-36

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
When I copy a note link to a specific line or section, the name displayed on the link only includes the name of the note.

**Why do you need this feature?**
In the current situation, I cannot recognize if it is a general link to a note or a link to a specific location in the note.

### Describe the solution you'd like

**The solution you'd like**
I would like to get something like: `Note title - Line 12` or `Note Title - Section title`.

**Alternatives you've considered**
I could edit the text manually, but this would take too much time.

**Comment by windingwind** [comment]
Yeah, that sounds good. Ping me if I forget
