### ISSUE TITLE
Avoid creating duplicate "My Knowledges" collection in the initializing step

### ISSUE THREAD

**Issue by woodwm** [windingwind/zotero-better-notes#8]
Hi,

I installed the plugin in one computer and then install it in another one. When initializing the plugin  in the second computer, "My Knowledges" collection is already there. Therefore, it should be avoid to create duplicate "My Knowledges" collection in the initializing step.

**Comment by windingwind** [comment]
Thanks,

Planned. This is not a bug or an important feature, thus it will not have a very high priority.

**Comment by woodwm** [comment]
![image](https://user-images.githubusercontent.com/13971199/168305824-8da9bf55-a34a-42cf-b090-db1e6e25f864.png)

Currently, it only allows to create a new collection, but not select a existing one if people changed the name of the collection for notes. So a better way to allow selection existing or create new.

**Comment by windingwind** [comment]
No need to select one. I just want to let users know it is recommended to put main notes in one place.
It is very like the Obsidian workspace, but you are always free to create/select notes from other collections.
