### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jachin-byte** [windingwind/zotero-better-notes#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 22H2
- Zotero Version: 7.0.0-beta.50+8239d04d5 (64-bit)
- Plugin Version: 1.1.4-36

### Describe the bug

打开两侧的导航栏，中间的pdf不能翻到底，两边的导航栏也翻不到底，如gif文件所示。求大佬给出建议
![21](https://github.com/windingwind/zotero-better-notes/assets/53991840/7f9c4954-a42c-4130-82e6-a80a2a49dade)

### Debug Output

以上步骤都尝试过

**Comment by windingwind** [comment]
等待z7更新，与本插件无关，此处关闭
