### ISSUE TITLE
[Feature] 请求增加导出笔记格式为xlsx

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-better-notes#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macos
- Zotero Version: 7
- Plugin Version: 1.1.4-35

我平时看文献将单词和不会的词语积累在excel中，并便于使用quicker来朗读excel的词语进行听写，看到这个插件可以导出多种格式，唯独缺少excel的格式，还是挺需要的。

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
xlsx是表格，笔记是文档，无法互相转化
