### ISSUE TITLE
无法转到链接笔记的对应行或节（当笔记工作区关闭时）[Bug] 

### ISSUE THREAD

**Issue by occasional15** [windingwind/zotero-better-notes#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 10
- Zotero Version: 7.0.0-beta.51+7c5600913 (64-bit)
- Plugin Version: 1.1.4-36

### Describe the bug

复制得到笔记A的当前行或当前节的链接，并粘贴到笔记B中，
![image](https://github.com/windingwind/zotero-better-notes/assets/147971641/4bbe57dd-a897-4045-87c7-12192f1c4b7d)
![image](https://github.com/windingwind/zotero-better-notes/assets/147971641/91a1763a-b5a4-4e15-b5cd-84485dd52afd)
以笔记B作为“笔记工作区”打开时，单击上述链接可以在工作区右侧正常打开笔记A，并且页面会停留在笔记A对应的行或节；
但是当关闭“笔记工作区”、在**单独窗口打开**笔记B时，单击上述链接可以**唤起笔记A在单独窗口打开**，但是页面（**光标**）只会停留在笔记A的第一行，而不会跳转到对应的行或节。

还有另一个问题，粘贴在笔记B中的包含笔记A行数信息的链接，无法随着笔记A内容行数的变化而更新（链接中的行数不变），这个有办法解决吗？
还有一个问题，当链接位于笔记右侧时，出现的菜单栏可能超出笔记窗口范围，如图：
![image](https://github.com/windingwind/zotero-better-notes/assets/147971641/063064d9-6740-43e3-895c-d0f808349539)

### Debug Output

1700455856450	addons.xpi	WARN	Checking D:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1700455857320	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\fengbo\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.51+7c5600913, os => Windows 10.0 19045, locale => zh-CN, extensions => Better Notes for Zotero (1.1.4-36, extension), Crush Reference (0.6.4, extension, disabled), Awesome GPT (0.3.2, extension, disabled), Night (0.1.0-2, extension, disabled), Open PDF for Zotero (0.0.8, extension, disabled), Translate for Zotero (1.1.0-21, extension, disabled), Linter for Zotero (1.6.7, extension, disabled), Jasminum (1.0.0-7, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Actions and Tags for Zotero (1.0.0-25, extension, disabled), Zotero Addons (1.3.5, extension, disabled)

**Comment by windingwind** [comment]
> 但是当关闭“笔记工作区”、在单独窗口打开笔记B时，单击上述链接可以唤起笔记A在单独窗口打开，但是页面（光标）只会停留在笔记A的第一行，而不会跳转到对应的行或节。

是的。该功能只对工作区有效

> 还有另一个问题，粘贴在笔记B中的包含笔记A行数信息的链接，无法随着笔记A内容行数的变化而更新（链接中的行数不变），这个有办法解决吗？

建议使用节链接，而非行链接。行链接就是连接到固定行

> 还有一个问题，当链接位于笔记右侧时，出现的菜单栏可能超出笔记窗口范围，如图：

拉宽窗口即可
