### ISSUE TITLE
关闭打开的PDF后，notes会自动打开。

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-better-notes#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: windows11 23H2
- Zotero Version:7.0.0-beta.51+7c5600913 (64-bit)
- Plugin Version: 1.1.4-36

### Describe the bug

每次打开Zotcard卡片后关闭，better notes就会自动打开。因为前面Zotcard关闭后，会自动打开better notes并且跳转到主工作区笔记里面，后面zotcard作者优化了下，不让自动跳转了，但是还是会打开better notes，能不能增加一个功能，不让它自动打开呢。

### Debug Output

[Debug Output.zip](https://github.com/windingwind/zotero-better-notes/files/13433196/Debug.Output.zip)
这个调试过程是关闭其它插件，只开了zotcard和better notes，操作过程是打开zotcard卡片页面，再关闭，再切换到自动打开的better notes界面，再关闭这个界面。

**Comment by baileichao** [comment]
标题写错了，不是关闭打开PDF后notes会自动打开，关闭打开的PDF后notes自动打开，只有一次出现这个情况，后面都没有出现过。

**Comment by windingwind** [comment]
谢谢反馈，由于BN工作区的按钮以标签页形式存在，关闭最后一个阅读器标签页后会自动聚焦前一个标签页（即BN工作区）。设计如此
