### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by byhwsh** [windingwind/zotero-better-notes#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  windows 10 22H2
- Zotero Version: 6.0.3
- Plugin Version: 1.0.4

### Describe the bug

在笔记中会插入公式，但是导出为PDF的时候，公式就变成了代码格式，如
\sum _ { i = 1 } ^ { N - 1 } a _ { i } \int _ { t _ { i } } ^ { t _ { i + 1 } } \psi _ { j } ( t ) d t \leq c _ { j }

为什么导出的PDF里的公式是这样？感觉是bug

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-better-notes/files/13434928/Debug.Output.txt)

**Comment by windingwind** [comment]
zo6版本的插件不再维护，谢谢理解。已在最新beta版本修复。
