### ISSUE TITLE
[Bug] 主工作区中的内容没法编辑

### ISSUE THREAD

**Issue by WHITE13452** [windingwind/zotero-better-notes#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macos 13.6.2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the bug

主工作区中的内容没法编辑，想要删除主工作区里的内容但无法实现，我该如何清空我的主工作区
<img width="1447" alt="截屏2023-11-24 20 13 47" src="https://github.com/windingwind/zotero-better-notes/assets/72494561/8acc7942-4713-443b-bb01-7cb5155d8cd2">

### Debug Output

无

**Comment by windingwind** [comment]
你的笔记在回收站。善用搜索问过无数遍了
