### ISSUE TITLE
[Color config Bug] 

### ISSUE THREAD

**Issue by Ting-Bao** [windingwind/zotero-better-notes#81]
When using dark mode in Ubuntu OS, the Work space outline can only be dispalyed in black, resulting in hard readabiliy.

**Comment by windingwind** [comment]
Could you please provide a screenshot

**Comment by Ting-Bao** [comment]
![image](https://user-images.githubusercontent.com/32322571/177268621-539702a7-4f59-4f61-b993-c4ce2c3a02f5.png)

**Comment by windingwind** [comment]
Please try v0.6.3

**Comment by rouniuyizu** [comment]
it seems the problem hasn't been sloved -- tried 6.3 and latest 6.28

**Comment by ipcoder** [comment]
Same problem here. Version 0.8.3
Ubuntu 22.10
![image](https://user-images.githubusercontent.com/9642454/208901232-14d0bb3b-9300-468c-b503-c6d3d391f7ac.png)

**Comment by windingwind** [comment]
fixed
