### ISSUE TITLE
[Bug] 导出当前笔记为PDF，弹出空白窗口

### ISSUE THREAD

**Issue by RunningDog0** [windingwind/zotero-better-notes#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10.0 22631
- Zotero Version: 7.0.0-beta.51+7c5600913
- Plugin Version: 1.1.4-23

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/147246491/357fe685-de68-4c91-90da-6cb7d4a6fd1a)
点击导出笔记为PDF，弹出空白窗口，找不到生成的PDF

### Debug Output

[JavaScript Error: "chrome://betternotes/content/pdfPrinter.xhtml : Unable to run script because scripts are blocked internally."]

[JavaScript Error: "XML Parsing Error: mismatched tag. Expected: </br>.
Location: 
Line Number 30, Column 102:"]

[JavaScript Error: "SyntaxError: An invalid or illegal string was specified" {file: "chrome://betternotes/content/pdfPrinter.xhtml" line: 36}]

appName => Zotero, version => 7.0.0-beta.51+7c5600913, os => Windows 10.0 22631, locale => zh-CN, extensions =>  Better Notes for Zotero (1.1.4-23, extension)

**Comment by windingwind** [comment]
1. 升级插件
2. 出现白色窗口是正在导出中，请勿关闭。待白色窗口自动关闭即导出完成
