### ISSUE TITLE
[Feature] 搜索栏增加通配符或正则表达式功能

### ISSUE THREAD

**Issue by 4965898** [windingwind/zotero-better-notes#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win10 
- Zotero Version:6.0
- Plugin Version: 1.0.4

### Describe the feature request

现有的搜索替换功能不能批量处理文本，需要复制粘贴到其他软件处理完后弄回来，非常的麻烦

### Describe the solution you'd like

增加正则表达式或通配符等功能

**Comment by windingwind** [comment]
非插件功能，请向forums.zotero.org反馈
