### ISSUE TITLE
[Feature] 注释笔记的更新功能

### ISSUE THREAD

**Issue by pengxy0** [windingwind/zotero-better-notes#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 家庭中文版 22H2
- Zotero Version: 7.0.0-beta.52+2f8e536f2 (64-bit)
- Plugin Version: 1.1.4-43

### Describe the feature request

我在第一次读文献的时候，会添加一次注释笔记。而后续通过对文献的多次精读，都会在文献上做一些新的注释或者删除之前的一些注释，那么就要对之前笔记手动添加注释，这往往会比较繁琐。

### Describe the solution you'd like

基于上述问题的阐述，大佬是否可以在注释笔记添加一个更新注释笔记的功能。例如下图
![image](https://github.com/windingwind/zotero-better-notes/assets/130196652/30e917b3-0dab-4b24-97f8-c21872f96a5d)
还有一种方法，就是将该笔记删除，重新建立新的注释笔记，这样一来，如果此笔记里有关联其它的笔记，那这样的关联可能会消失。
上面只是一些请求和顾虑，希望大佬可以考虑添加这个功能，感谢大佬！

**Comment by windingwind** [comment]
没有很理解具体指的是更新什么内容？

**Comment by pengxy0** [comment]
@windingwind 感谢大佬回复。  就是第一次阅读做的注释，生成了一个注释笔记。当第二次阅读文献的时候，可能还会做一些注释，这时做的注释只能手动添加到第一次的注释笔记里，有些麻烦。因此，可以添加注释笔记的更新功能，这样会把第二次做的注释直接更新到第一次做的注释笔记里，相对比较方便一些。不知大佬可否实现

**Comment by yzy1228682367** [comment]
> @windingwind 感谢大佬回复。 就是第一次阅读做的注释，生成了一个注释笔记。当第二次阅读文献的时候，可能还会做一些注释，这时做的注释只能手动添加到第一次的注释笔记里，有些麻烦。因此，可以添加注释笔记的更新功能，这样会把第二次做的注释直接更新到第一次做的注释笔记里，相对比较方便一些。不知大佬可否实现

Zotero IF Pro Max好像可以实现这个功能。

**Comment by windingwind** [comment]
如果自动把批注合并到笔记，意味着先前在笔记里做的修改会被覆盖。很难想象这样有什么价值，和直接在左侧栏查看所有批注有何区别
