### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [windingwind/zotero-better-notes#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 家庭中文版 22H2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the bug

通过模板添加条目笔记报错，显示Template [item]englishpaper Error: TypeError: Zotero.ZoteroStyle is undefined
![image](https://github.com/windingwind/zotero-better-notes/assets/49083219/d1c79688-a7f3-48e4-8655-222927a4faf0)

### Debug Output

[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 883}]

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://1059074043%40qq%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://1059074047%40qq%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///C:/Users/10590/AppData/Roaming/Zotero/Zotero/Profiles/k4u9henu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///C:/Users/10590/AppData/Roaming/Zotero/Zotero/Profiles/k4u9henu.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

version => 6.0.30, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.30, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.30, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.30, extension), Zotero Better Notes (1.0.4, extension), Zotero PDF Translate (1.0.25, extension, disabled), Zotero Reference (0.5.8, extension, disabled), Jasminum (0.2.8, extension, disabled)

**Comment by windingwind** [comment]
模板问题请询模板作者，不要在插件里提issue，谢谢
