### ISSUE TITLE
希望添加一个使用latex语法时可以重置公式编号的功能

### ISSUE THREAD

**Issue by xunx911** [windingwind/zotero-better-notes#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Winsdows 10专业版 22H2
- Zotero Version: 7.0.0-beta.53+969031a37 (64-bit)
- Plugin Version:1.1.4-49

### Describe the feature request

比如在做独立笔记的时候，记录了不同的评价指标，使用latex数学公式块时可以使用equation创建带编号的公式，但是这个编号没办法重置，但是我觉得不同的评价指标应该从头开始公式编号。latex语法中可以使用\setcounter{equation}{0}重置，但是这里似乎不行。

### Describe the solution you'd like

添加一个重置公式或者其他编号的功能

### Anything else?

很棒的笔记插件，感谢作者

**Comment by windingwind** [comment]
zotero的笔记公式基于katex，见https://katex.org/docs/supported
如果没有这个功能，就是没这个功能
