### ISSUE TITLE
请求添加撤销上一步的功能

### ISSUE THREAD

**Issue by YYde123** [windingwind/zotero-better-notes#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0
- Plugin Version:1.1.4-49

### Describe the feature request

我在使用better notes过程中发现，如果我不小心将我输入的文字删除后，我还需要重新输入；或者我不小心将添加的笔记内容删除后，我还要重新添加。所以请求添加一个撤销上一步的操作，类似于word撤销操作。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
本身就支持的。

**Comment by YYde123** [comment]
好的好的
