### ISSUE TITLE
[Bug] 把当前笔记链接到主笔记失败

### ISSUE THREAD

**Issue by lyzzz-lab** [windingwind/zotero-better-notes#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0
- Plugin Version: 1.0.4（1.1版本以上的报错不兼容）

### Describe the bug

想连接当前笔记到主笔记时，在当前笔记末尾出现“referred in...”字样
![子笔记](https://github.com/windingwind/zotero-better-notes/assets/154900570/1db7727a-61aa-4aab-ae69-a2733b6f12a3)
但在主笔记页面却只有一个子笔记图标，子笔记标题没显示，且主笔记正文中未出现子笔记链接，应该是没成功
![主笔记](https://github.com/windingwind/zotero-better-notes/assets/154900570/cb894c39-ca5e-4806-9376-ce631f89016b)

后来新建过比较短的笔记，成功了
但是长笔记都还是没办法解决这个问题

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-better-notes/files/13905239/Debug.Output.txt)

**Comment by windingwind** [comment]
尝试重新安装插件，看起来安装包不完整

**Comment by lyzzz-lab** [comment]
> 尝试重新安装插件，看起来安装包不完整
 
谢谢大大，重新安装后解决了。另外我也有尝试刚新建笔记时就链接到主笔记，做完笔记后去主笔记刷新一下子笔记内容，也可行
