### ISSUE TITLE
[Bug] 插入双链后zotero变成无响应状态

### ISSUE THREAD

**Issue by nanadeya** [windingwind/zotero-better-notes#858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win10
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version:1.1.4-49

### Describe the bug

![K@A7T~Z90@UYJ3L0YO6NZ7B](https://github.com/windingwind/zotero-better-notes/assets/37279524/8013ed65-c0cd-4f6d-b3ed-72116099e051)
![8D FRBP0K(FHA(I%~JG%KVK](https://github.com/windingwind/zotero-better-notes/assets/37279524/4adaa7ad-aa4d-479f-b134-2dd557f85e54)
插入双链后zotero变成无响应状态，此时如第一张图所示，在子笔记中显示有反链。
关闭软件重新打开，如第二图所示，只有正链，反链消失不见。

### Debug Output

![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/719fac7d-1826-4c69-b4c1-90ed977e365a)
此时日志也为未响应状态，无法获得输出日志。

**Comment by nanadeya** [comment]
同步笔记到obsidian中zotero也会立马变成无响应状态。

**Comment by windingwind** [comment]
是否可以禁用其他所有插件后，在空白的工作区笔记和空白的子笔记中操作复现？

**Comment by nanadeya** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/37279524/f47d8e71-5769-4444-9bb9-420906974336)
在空白的工作区笔记和空白的子笔记中又正常了。

**Comment by windingwind** [comment]
请依次尝试：
出现问题的工作区笔记+空白子笔记
空白的工作区笔记+出现问题的子笔记
，确定问题来源，然后将出现问题的笔记截图/在公开zotero群组中分享/导出markdown，使我可以查看排查问题。谢谢

**Comment by nanadeya** [comment]
在上一步空白笔记中操作之后，换回原来的主笔记后，插入双链正常了，同步功能也正常了，没有再出现无响应状态。
