### ISSUE TITLE
[Bug] Syncing with Obsidian makes the citation pages dissappear

### ISSUE THREAD

**Issue by cankerubi** [windingwind/zotero-better-notes#864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11 22H2
- Zotero Version: 7.0.0
- Plugin Version: Better Notes for Zotero (1.1.4-49, extension),

### Describe the bug

When I checked my earlier notes, I realized that page numbers of my citations disappeared. Since un-synced notes doesn't have this issue, I thought this might have to do with the plugin. I also used auto-sync in Tags & Actions. I stopped syncing notes altogether now, I am about to give up syncing notes to anywhere and just using Zotero for my note-taking.

### Debug Output

1705408183657	addons.xpi	WARN	Checking C:\Users\rbini\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Error: Target container is not a DOM element." {file: "resource://zotero/react-dom.js" line: 26121}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\rbini\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

appName => Zotero, version => 7.0.0-beta.54+6b996d4f9, os => Windows 10.0 22621, locale => en-US, extensions => Zotero Addons (1.4.5, extension), Better BibTex for Zotero (6.7.143, extension), Better Notes for Zotero (1.1.4-49, extension), Night (0.1.0-2, extension), Zotero Attanger (1.1.1, extension), Actions and Tags for Zotero (1.0.0-beta.33, extension), Ethereal Style (3.3.5.3, extension, disabled)

### Anything else?

I am not willing to reproduce this bug, since it removes my pages and I don't really know how it happens.

**Comment by windingwind** [comment]
fixed in v1.1.4-beta.50

**Comment by cankerubi** [comment]
Hey, thanks for the fix! I am very glad to see you responding the problem very quickly. Can I use this function now without hesitation? Recovering pages for citations is a bit hard for me since I have so many notes in Zotero. Thanks again?

**Comment by windingwind** [comment]
Since Zotero 7 is still in beta, I'm not sure if it is a good idea to...use it without hesitation? But as long as you do a backup periodically, it's safe.

**Comment by windingwind** [comment]
But anyway, please do backup important data even with a stable version of this plugin/Zotero. Your disk may be down, the OS may break. Always keep a backup!
