### ISSUE TITLE
[Feature] Change export path for auto-synced notes

### ISSUE THREAD

**Issue by xinyu-yang** [windingwind/zotero-better-notes#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 Professional 22H2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the feature request

After the notes are exported to a `md` file with `auto-sync` option checked, it works well. However, there are some cases that I would like to change the path of these `md` files.

Currently, the only way I know to achieve that is to unsync the note first and resync it to the new path. This would be annoying if there are a lot of notes to sync.

### Describe the solution you'd like

So I just wonder if you can add a feature to change the export path of those already auto-synced notes?

Thank you.

**Comment by windingwind** [comment]
You can select them in the library and re-export all (with syncing enabled) to a new directory.

**Comment by xinyu-yang** [comment]
By "selecting them in the library" do you mean manually selecting them one by one?
