### ISSUE TITLE
control over which items will be updated in syncing

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#871]
Hi there. Thanks for your effort for this plugin.
I also use Obsidian for note taking and sync with Zotero using Better Notes. I appreciate the new option, that Zotero doesn't overwrite externally changed frontmatter. 
It would be cool, however, to have control over which items will be updated by Zotero and which not by e.g. using `$` in the [ExportMDFileHeaderV2] as well with e.g.: `header.$zotero_tags = noteItem.parentItem.getTags().map((_t) => _t.tag);`

would that be easy to integrate?

_Originally posted by @jakobkilian in https://github.com/windingwind/zotero-better-notes/issues/527#issuecomment-1907940227_

**Comment by windingwind** [comment]
Sorry I do not quite understand. What do you mean by `control over which items will be updated`? You mean update the item metadata from Ob?

**Comment by jakobkilian** [comment]
Like discussed in #527 Zotero Better Notes updates the metadata like $version, $libraryID and $itemKey at every sync. They will be overwritten by Zotero even if you would modify them externally. That's fine and intended.
All the other metadata created with [ExportMDFileHeaderV2] however will not be updated when they got changed in Zotero. For many things this is intended (for controlling certain properties externally like discussed in #527) but it would be nice to have **control over which items** are handled one way (zotero will update them) or the other way (they're set once and can be controlled externally. 
Does this make it more undertandable?

**Comment by windingwind** [comment]
Please try the latest beta, which allows you to overwrite keys starting with `$` from the Z side during syncing.

**Comment by jakobkilian** [comment]
thx for the fast response. 
Needed to update to latest Zotero beta (7.0.0-beta.55+9151fb355 – seems to introduce a lot of changes in the UI as well) to be able to install you lates beta. 
Unfortunately this breaks Better Bibtex and the export of any YAML except `$version, $libraryID and $itemKey`... Did they change sth on Zotero side? Which version did you use?

**Comment by windingwind** [comment]
Thanks for the feedback. I've tried to fix the yaml header bug in v1.1.4-beta.53, I hope it works as expected.

**Comment by jakobkilian** [comment]
Nice. Works like a charm, thank you!
