### ISSUE TITLE
[Feature] Custom title and YAML for exported file with template "Collect annotations by color"

### ISSUE THREAD

**Issue by aathanor** [windingwind/zotero-better-notes#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Mac Sonoma
- Zotero Version: 7.0
- Plugin Version: 1.1.4-beta.50

### Describe the feature request

I use your template to generate Literature Notes. My workflow needs to have the generated markdown files named with the pandoc citekey (like @carrollMeasurementMeaning1959). I would also like to customize the YAML header of the exported file. But this is not generated inside the template code, can't find how to customize it.

**Why do you need this feature?**
When using MarkDB-connect extension, there is an easy link back and forth from Zotero document to the markdown editor. It is also good practice to name files with the pandoc citekey for future modifications of the workflow.

### Describe the solution you'd like

What modifications to what files are needed to achieve the above?

**Comment by aathanor** [comment]
Oops, wrong page, sorry

**Comment by aathanor** [comment]
Not sure at first  if this is related to your plugin, but it seems it does, so reopened it :)

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/618

and the template `[ExportMDFileHeader]` for YAML header.

**Comment by aathanor** [comment]
Thanks a lot!
