### ISSUE TITLE
[Feature] .odt as export filetype

### ISSUE THREAD

**Issue by igarca** [windingwind/zotero-better-notes#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Linux Mint 21.3
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
Libreoffice opens a blank exported docx document.
I know it could be a Libreoffice issue but it's strange since I can open any other docx document without problems.

**Why do you need this feature?**
People using Linux can see and edit the exported notes.

### Describe the solution you'd like

**The solution you'd like**
Including .odt as exports format.

**Alternatives you've considered**
The only workaround is converting the document from docx to odt with an online converter (convertir from doxc to odt with Libreoffice does not work).

**Comment by windingwind** [comment]
Sorry, but I am not familiar with LibreOffice. If we want to do export, we need to do it perfectly (e.g. citations, which is supported by export to DOCX) and I have no idea how these things work in libreOffice.

I would welcome any PR/discussion about that, but I may not be able to provide further help.

**Comment by Pengzhi-Gao** [comment]
you can use pandoc to finish this work
