### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Gczmy** [windingwind/zotero-better-notes#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS Sonoma 14.2.1
- Zotero Version: 7.0.0
- Plugin Version: 1.0.4

### Describe the bug

以svg输出时，图片报错：error on line 1 at column 7985: Entry 'nbsp not defined
![image](https://github.com/windingwind/zotero-better-notes/assets/20588674/7f5f2dd3-3c47-4816-a442-b9f438605dd7)

### Debug Output

[归档.zip](https://github.com/windingwind/zotero-better-notes/files/14070704/default.zip)

**Comment by windingwind** [comment]
已在最新beta版插件修复
