### ISSUE TITLE
[Bug] 插件会导致tab搜索栏失效

### ISSUE THREAD

**Issue by 1067237855** [windingwind/zotero-better-notes#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows10
- Zotero Version: 7.0.0-beta.55+9151fb355 (64-bit)
- Plugin Version:1.1.4-beta.53

### Describe the bug

# 禁用better notes
![image](https://github.com/windingwind/zotero-better-notes/assets/104330036/302961f1-352d-4a58-9211-2183fa1a6778)
# 启用better notes
![image](https://github.com/windingwind/zotero-better-notes/assets/104330036/1d1046fe-8538-418a-9545-3ac57a438227)

### Debug Output

[Debug Output.txt](https://github.com/windingwind/zotero-better-notes/files/14070774/Debug.Output.txt)

**Comment by windingwind** [comment]
请重启zotero尝试

**Comment by 1067237855** [comment]
重启不太行，只有禁用better notes才管用
> 请重启zotero尝试

**Comment by 1067237855** [comment]
1706335716019	addons.xpi	WARN	Checking G:\APP\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36


1706335716955	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Attempt to override an existing message: "delitemwithatt-delete-collection-and-attachment"." {file: "delitemwithatt-addon.ftl" line: 0}]

[JavaScript Error: "TypeError: newNode is undefined" {file: "jar:file:///C:/Users/Administrator/AppData/Roaming/Zotero/Zotero/Profiles/8bc6uvsb.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 27782}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/Administrator/AppData/Roaming/Zotero/Zotero/Profiles/8bc6uvsb.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/Administrator/AppData/Roaming/Zotero/Zotero/Profiles/8bc6uvsb.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/Administrator/AppData/Roaming/Zotero/Zotero/Profiles/8bc6uvsb.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "originalThis.item is undefined" {file: "jar:file:///C:/Users/Administrator/AppData/Roaming/Zotero/Zotero/Profiles/8bc6uvsb.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/zoteroreference.js" line: 21583}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 839}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "TypeError: item.getItemTypeIconName is not a function" {file: "chrome://zotero/content/tabs.js" line: 883}]
Zotero_Tabs</this.refreshTabsMenuList@chrome://zotero/content/tabs.js:883:34
onpopupshowing@chrome://zotero/content/zoteroPane.xhtml:1:13
Zotero_Tabs</this.showTabsMenu@chrome://zotero/content/tabs.js:981:24
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:68


[JavaScript Error: "Style with ID http://www.zotero.org/styles/elsevier-with-titles already loaded from elsevier-with-titles.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14


[JavaScript Error: "Style with ID http://www.zotero.org/styles/royal-society-of-chemistry already loaded from royal-society-of-chemistry.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14


[JavaScript Error: "TypeError: item.getItemTypeIconName is not a function" {file: "chrome://zotero/content/tabs.js" line: 883}]
Zotero_Tabs</this.refreshTabsMenuList@chrome://zotero/content/tabs.js:883:34
onpopupshowing@chrome://zotero/content/zoteroPane.xhtml:1:13
Zotero_Tabs</this.showTabsMenu@chrome://zotero/content/tabs.js:981:24
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:68


[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\Administrator\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12


[JavaScript Error: "TypeError: item.getItemTypeIconName is not a function" {file: "chrome://zotero/content/tabs.js" line: 883}]
Zotero_Tabs</this.refreshTabsMenuList@chrome://zotero/content/tabs.js:883:34
onpopupshowing@chrome://zotero/content/zoteroPane.xhtml:1:13
Zotero_Tabs</this.showTabsMenu@chrome://zotero/content/tabs.js:981:24
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:68


appName => Zotero, version => 7.0.0-beta.55+9151fb355, os => Windows 10.0 19045, locale => zh-CN, extensions => Crush Reference (0.6.4, extension), Del Item With Attachment (0.2.5, extension), Translate for Zotero (1.1.0-beta.30, extension), Ethereal Style (3.3.6, extension), Jasminum (1.0.0-14, extension), Zotero Attanger (1.1.2, extension), Better Notes for Zotero (1.1.4-beta.53, extension), ZotCard (3.0.10, extension), ZoteroExcalidraw (1.0.1, extension), Zotero Addons (1.5.1, extension), Night (0.1.0-2, extension, disabled), Easier Citation (0.4.2, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Obsidian Note for Zotero (1.0.1, extension, disabled), Zotero Debug Bridge (2.0.0, extension, disabled), Awesome GPT (0.5.1.4, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.33, extension, disabled), Zotero One (5.4.7, extension, disabled), Better BibTex for Zotero (6.7.147, extension, disabled), ZotURead (3.0.1, extension, disabled)

(5)(+0116177): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br Accept-Language: en,zh-HK;q=0.9,zh;q=0.8,zh-TW;q=0.7,zh-CN;q=0.6

(5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.55+9151fb355 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found

(3)(+0000468): itemTree.render(). Displaying Item Tree

(5)(+0001534): POST /zoterogpt HTTP/1.1 Host: 127.0.0.1:23119 Connection: keep-alive Content-Length: 145 sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120" Content-Type: application/json sec-ch-ua-mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 sec-ch-ua-platform: "Windows" Accept: */* Sec-Fetch-Site: none Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Accept-Encoding: gzip, deflate, br Accept-Language: en,zh-HK;q=0.9,zh;q=0.8,zh-TW;q=0.7,zh-CN;q=0.6

(5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 7.0.0-beta.55+9151fb355 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found

**Comment by windingwind** [comment]
请禁用其他所有插件进行测试

**Comment by 1067237855** [comment]
其他插件均已禁用
> 请禁用其他所有插件进行测试

**Comment by 1067237855** [comment]
1706441538657	addons.xpi	WARN	Checking G:\APP\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36


1706441539373	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "TypeError: library.waitForDataLoad is not a function" {file: "chrome://zotero/content/contextPane.js" line: 839}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/elsevier-with-titles already loaded from elsevier-with-titles.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14


[JavaScript Error: "Style with ID http://www.zotero.org/styles/royal-society-of-chemistry already loaded from royal-society-of-chemistry.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 182}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:182:32
tryCatcher@resource://zotero/bluebird/util.js:16:23
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/bluebird/generators.js:97:49
module.exports/Promise.prototype._settlePromise@resource://zotero/bluebird/promise.js:609:26
module.exports/Promise.prototype._settlePromise0@resource://zotero/bluebird/promise.js:649:10
module.exports/Promise.prototype._settlePromises@resource://zotero/bluebird/promise.js:729:18
_drainQueueStep@resource://zotero/bluebird/async.js:93:12
_drainQueue@resource://zotero/bluebird/async.js:86:24
Async.prototype._drainQueues@resource://zotero/bluebird/async.js:102:16
Async/this.drainQueues@resource://zotero/bluebird/async.js:15:14


[JavaScript Error: "TypeError: item.getItemTypeIconName is not a function" {file: "chrome://zotero/content/tabs.js" line: 883}]
Zotero_Tabs</this.refreshTabsMenuList@chrome://zotero/content/tabs.js:883:34
onpopupshowing@chrome://zotero/content/zoteroPane.xhtml:1:13
Zotero_Tabs</this.showTabsMenu@chrome://zotero/content/tabs.js:981:24
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:68


[JavaScript Error: "TypeError: item.getItemTypeIconName is not a function" {file: "chrome://zotero/content/tabs.js" line: 883}]
Zotero_Tabs</this.refreshTabsMenuList@chrome://zotero/content/tabs.js:883:34
onpopupshowing@chrome://zotero/content/zoteroPane.xhtml:1:13
Zotero_Tabs</this.showTabsMenu@chrome://zotero/content/tabs.js:981:24
oncommand@chrome://zotero/content/zoteroPane.xhtml:1:68


appName => Zotero, version => 7.0.0-beta.55+9151fb355, os => Windows 10.0 19045, locale => zh-CN, extensions => Better Notes for Zotero (1.1.4-beta.53, extension), Night (0.1.0-2, extension, disabled), Crush Reference (0.6.4, extension, disabled), Easier Citation (0.4.2, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Obsidian Note for Zotero (1.0.1, extension, disabled), Zotero Debug Bridge (2.0.0, extension, disabled), Del Item With Attachment (0.2.5, extension, disabled), Awesome GPT (0.5.1.4, extension, disabled), Translate for Zotero (1.1.0-beta.30, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.33, extension, disabled), Ethereal Style (3.3.6, extension, disabled), Jasminum (1.0.0-14, extension, disabled), Zotero Attanger (1.1.2, extension, disabled), Zotero One (5.4.7, extension, disabled), Better BibTex for Zotero (6.7.147, extension, disabled), ZotCard (3.0.10, extension, disabled), ZoteroExcalidraw (1.0.1, extension, disabled), ZotURead (3.0.1, extension, disabled), Zotero Addons (1.5.1, extension, disabled)

(3)(+0016388): itemTree.render(). Displaying Item Tree

**Comment by windingwind** [comment]
请打开工作区，设置一个有效的笔记即可
