### ISSUE TITLE
[Feature] 能否参照obsidian to anki的功能在zotero里将笔记同步到anki

### ISSUE THREAD

**Issue by Jack20152019** [windingwind/zotero-better-notes#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: window11
- Zotero Version: 7.0.0-beta.55
- Plugin Version:1.1.4 bate 53

### Describe the feature request

anki卡片太碎了，zotero的笔记很有结构性，但是需要记忆的知识点还是需要anki辅助，能否增加一个功能直接将笔记里特有结构的知识点同步到anki呢

### Describe the solution you'd like

  参照obsidian to anki这个插件的功能，例如问答卡，只需要在问题行加上#flashcard这个标签，他能自动将笔记制成卡片同步到anki里，笔记更改点一下同步也能将修改内容同步到anki里非常方便
虽然目前我能结合better notes的同步功能+obsidan实现同样的效果，但还是感觉太过麻烦，希望能有一步到位的方式

**Comment by windingwind** [comment]
感谢意见。本插件的同步功能不是为了某个软件专门设计的。相比通用的文本格式markdown，我不认为有必要在本插件中支持专用软件格式。
