### ISSUE TITLE
截止2024年1月28日的更新的最新better note插件不能在zotero 7 beta 54版本中正常安装[Bug] 

### ISSUE THREAD

**Issue by JayeW1997** [windingwind/zotero-better-notes#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 
- Plugin Version:

### Describe the bug

截止2024年1月28日的更新的最新better note插件不能在zotero 7 beta 54版本中正常安装

<img width="1280" alt="截图_20240128200100" src="https://github.com/windingwind/zotero-better-notes/assets/84283850/3f0c1166-ee52-43a8-ad81-e8aa77ce5c83">

由于这是zotero 7界面修改前的一个版本的zotero，希望能够对better note能有所适配是最好不过了

### Debug Output

1

### Anything else?

1

**Comment by windingwind** [comment]
旧版本安装旧版插件即可。

**Comment by JayeW1997** [comment]
是的，发现了，50 的可以，51，52 的不行，多谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月28日 21:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] 截止2024年1月28日的更新的最新better note插件不能在zotero 7 beta 54版本中正常安装[Bug]  (Issue #879) |

旧版本安装旧版插件即可。
