### ISSUE TITLE
[Bug] Auto Insert to main note

### ISSUE THREAD

**Issue by neybaf** [windingwind/zotero-better-notes#88]
**Describe the bug**
Using the "auto insert new annoations to note" function, the new insertion is done between the old reference and the  name. See in the screenshot 

**To Reproduce**
- activate "autoinsert new annoations to notes" function
- Highlight some text in zotero pdf reader
- check the main note

**Expected behavior**
I expected to have a quote and reference displayed together like 

>  blablabla

(John, 2016)

Or like 
>  blblblb
(Paul, 2017)

**Screenshots**
![Capture d’écran 2022-07-15 à 19 36 52](https://user-images.githubusercontent.com/103755582/179215873-b82efab5-b2ab-4a7e-81c4-29a5ca5a95e1.png)

**Desktop 
 - OS: Mac OS Monterey 12.4 
 - Zotero 6.0.10-beta.7+acba90f27 
 - Zotero Better Notes 0.6.7

**Comment by windingwind** [comment]
The insert position is the line after the current cursor. I guess you just split the old ref into two lines by making the ref line a blockquote and selecting the blockquote line. That's why the new annotations are inserted after the blockquote line.

**Comment by windingwind** [comment]
Any updates? If not, I'll close this issue.

**Comment by neybaf** [comment]
Sorry I took some holidays. 
Yes some updates, the problem still happens 

When I try to move some quotes or write stuff in the main note, then the new highlights are not added at the end. After this the bug happens even if I did put the cursor at the end. 
I suppose the workaround would be to always ask to add the highlight at the end of main note and not at line xxx

To reproduce
- highlights some texts 
- move one highlight
- put the cursor at the end 
- highlight text again (at least 2 or 3)

**Comment by neybaf** [comment]
Problem is still happening with 0.6.16
[Here is a video to show when it happens](https://pan.baidu.com/s/1V8LScWYJcE7AtzVH5lvgyw)
password g43k

**Comment by windingwind** [comment]
Seem like you changed the annotation template in Zotero. Could you please share the template you use to help me reproduce the bug?

**Comment by neybaf** [comment]
Indeed, I may have messed with this. totally forgot about this. My bad, sorry. 
Which template is called with the automatic insert function ?

**Comment by windingwind** [comment]
Don't worry. Please check the template following this: https://www.zotero.org/support/note_templates

**Comment by neybaf** [comment]
The template for annotations is this one right ?
extensions.zotero.annotations.noteTemplates.highlight
My config is this one : 
`<blockquote>{{highlight}}</blockquote><p>{{citation}} {{comment}}</p>`

I don't think there is any problem here. Am I watching at the wrong place ?

**Comment by windingwind** [comment]
Thanks! Currently, I increase the line index by 1 after insertion, while this template will be recognized as 2 lines. This makes the next insert position inside the previous annotation.

I'll try to fix it.

**Comment by windingwind** [comment]
fixed
