### ISSUE TITLE
[Bug] 以svg输出时，图片报错：error on line 1 at column 7985: Entry 'nbsp not defined

### ISSUE THREAD

**Issue by Gczmy** [windingwind/zotero-better-notes#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: macOS Sonoma 14.2.1
- Zotero Version: 7.0.0 
- Plugin Version: 1.1.4-beta.53

### Describe the bug

#875 在最新版中还是出现相同问题
![image](https://github.com/windingwind/zotero-better-notes/assets/20588674/c58bf3ad-4d12-4a23-876b-4a49343745b6)

### Debug Output

[归档.zip](https://github.com/windingwind/zotero-better-notes/files/14076212/default.zip)

**Comment by xiaoyi320** [comment]
最新版添加笔记添加不进去啊，只能手敲

**Comment by Gczmy** [comment]
> 最新版添加笔记添加不进去啊，只能手敲

添加到哪里添加不进去？我貌似没有这个问题

**Comment by windingwind** [comment]
请提供出现问题的笔记截图
