### ISSUE TITLE
[Feature] 希望能新增直接复制markdown和html链接的功能，跳转到正文

### ISSUE THREAD

**Issue by CapZhang** [windingwind/zotero-better-notes#882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: mac
- Zotero Version:  7.0.0
- Plugin Version: 1.1.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

希望能在高亮处新增直接复制markdown和html的链接的按钮，此链接的功能是：可以直接在笔记中点击跳转正文；

<img width="233" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/19522615/cfe23f17-c941-4a59-b79c-e91613b000a4">

经过尝试，链接格式如下：
html格式：
```
<span class="highlight" data-annotation="%7B%22attachmentURI%22%3A%22http%3A%2F%2Fzotero.org%2Fusers%2F12620540%2Fitems%2FIFW4Z4K3%22%2C%22annotationKey%22%3A%22YMY53G47%22%2C%22color%22%3A%22%23ffd400%22%2C%22pageLabel%22%3A%2233%22%2C%22position%22%3A%7B%22pageIndex%22%3A32%2C%22rects%22%3A%5B%5B215.391%2C180.018%2C534.677%2C195.75%5D%2C%5B76.992%2C158.25%2C91.992%2C173.25%5D%5D%7D%7D" ztype="zhighlight"><a href="zotero://open-pdf/library/items/IFW4Z4K3?page=33&#x26;annotation=YMY53G47">“要跳转的文档正文区域”</a></span>
```
经过尝试也可用的Markdown链接：
```
[要跳转的文档正文区域](zotero://open-pdf/library/items/IFW4Z4K3?page=33&#x26;annotation=YMY53G47)
```

**Why do you need this feature?**
1. zotero的笔记组织功能很弱（例如：添加笔记后只能新增一行，而不是继承光标处的格式）；因此希望能够复制出直接链接在其他支持markdown和html的笔记软件中使用
2. 目前这个链接只可以通过导出笔记时，勾选“保留Zotero链接”得到
3. 我自己尝试的导出笔记的同步时单向的，我在笔记软件中的修改没有同步过来

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-actions-tags/discussions/115
