### ISSUE TITLE
[Bug] 主窗口图标消失

### ISSUE THREAD

**Issue by horaynia** [windingwind/zotero-better-notes#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.3
- Zotero Version: 7，b56
- Plugin Version:1.14，b53
BN的主窗口图标消失，但是点击该区域有反应
<img width="293" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/50537627/ed1ee161-8143-4c5e-bdb6-5e6fe105d5ca">

### Describe the bug

BN的主窗口图标消失，但是点击该区域有反应

### Debug Output

无

**Comment by jjcheer** [comment]
I have the same bug. But when I close zotero then reopen, it appears again.

**Comment by windingwind** [comment]
Will be fixed.

For now, you can simply open the workspace and choose a valid note.

<img width="1177" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/33902321/656ff8cf-4e76-44ed-bb6d-90355e2f526a">

**Comment by horaynia** [comment]
> Will be fixed.
> 
> For now, you can simply open the workspace and choose a valid note.
> 
> <img alt="image" width="1177" src="https://private-user-images.githubusercontent.com/33902321/302013483-656ff8cf-4e76-44ed-bb6d-90355e2f526a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDczNzAsIm5iZiI6MTcwNjk0NzA3MCwicGF0aCI6Ii8zMzkwMjMyMS8zMDIwMTM0ODMtNjU2ZmY4Y2YtNGU3Ni00NGVkLWJiNmQtOTAzNTVlMmY1MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA3NTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzZhZDQyMDA0NzBhOTE3YTI4ZmQzZjM0ZmQ0MjQ5OWZmZGM3OWVjYTJjYjdkZjg1YWUwNGE2MjZlODZlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxCKzOjcSDQQwD3bnosvQE-Otl_Cri2eugbk8CmY6Uc">

可以了，但是图标有点小。希望整大点儿。
<img width="272" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/50537627/00498cf1-2d2b-4e35-a428-43fa4fa91104">
