### ISSUE TITLE
[Bug] Export to `docx` with page number

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#886]
I am loving your plugin and this feature, it has made life much easier for me. 

I have found a bug, however. When I export the citations into word, it doesn't copy page numbers together with the citations. Instead, it just leaves them out and I have to copy them from the note manually.

_Originally posted by @Levling in https://github.com/windingwind/zotero-better-notes/discussions/822#discussioncomment-8396968_

**Comment by windingwind** [comment]
@Levling Could you please provide more information about your current version of Z and plugin?

**Comment by sjgknight** [comment]
I also have this issue. 

To reproduce:
1. Create a note from annotations
2. Export note to word / docx
3. Click in to edit a citation, although the page numbers do appear in the export within the 'live' zotero field, they aren't in the locator metadata in Zotero, and when you refresh the references they disappear from the text.

Versions:
- zotero 8.0-beta.10+5a96e7c90 (64-bit)
- better notes  2.5.8
