### ISSUE TITLE
[Feature] 希望可以添加mermaid支持，否则无法在markdown笔记中添加流程图

### ISSUE THREAD

**Issue by BIGwangqz** [windingwind/zotero-better-notes#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0-beta.57
- Plugin Version:1.1.4-beta.53

### Describe the feature request

下方的流程图代码在思源笔记与zotero中的对比
```mermaid
graph TD
subgraph SVN Architecture
client1-->|read / write|SVN((SVN server))
client2-->|read only|SVN
client3-->|read / write|SVN
client4-->|read only|SVN
client5(...)-->SVN
SVN---|store the data|sharedrive
end
​```
思源笔记：
![image](https://github.com/windingwind/zotero-better-notes/assets/107259482/fa6d93ec-f133-4807-a384-7b968b6fc908)
zotero：
![image](https://github.com/windingwind/zotero-better-notes/assets/107259482/888207ff-d838-4912-a399-62ac80de44d0)



### Describe the solution you'd like

_No response_

### Anything else?

_No response_

**Comment by BIGwangqz** [comment]
第一次发，不太会。。。。。
再发一遍截图
![屏幕截图 2024-02-08 130645](https://github.com/windingwind/zotero-better-notes/assets/107259482/c89033dd-f3e7-49f6-9c3e-2d57907277c0)
![屏幕截图 2024-02-08 130720](https://github.com/windingwind/zotero-better-notes/assets/107259482/ca1150f2-05d0-4c8f-84b5-a94a722a3f65)

**Comment by BIGwangqz** [comment]
```
```mermaid
graph TD
subgraph SVN Architecture
client1-->|read / write|SVN((SVN server))
client2-->|read only|SVN
client3-->|read / write|SVN
client4-->|read only|SVN
client5(...)-->SVN
SVN---|store the data|sharedrive
end
​```
```

**Comment by windingwind** [comment]
谢谢反馈，但无计划在插件中支持markdown方言。
适合向https://forums.zotero.org/discussions 反馈
