### ISSUE TITLE
[Bug] 用better notes编辑长文时，出现无法选中文字、编辑的问题

### ISSUE THREAD

**Issue by hkazhl** [windingwind/zotero-better-notes#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the bug

用better notes编辑一较长的笔记时，出现无法选中文字、编辑的问题，
具体表现为：
这个长笔记是从word长文直接按ctrl+拖动到笔记中创建的，（此时word中的原有图片会呈现白底黑色的框，而后我在用图床逐一替换图片）
在编辑时，突然zotero卡住，（我放弃该笔记，重新从word长文直接按ctrl+拖动到笔记中创建，又再次出现了该情况）
重启zotero后再打开这个长笔记，光标闪了一下，随即不再闪烁（而其他短笔记均存在闪烁的光标，可正常编辑）
尝试过重启无效，zotero、better notes均为最新的稳定版

### Debug Output

(3)(+0019796): itemTree.render(). Displaying Item Tree

(3)(+0002003): itemTree.render(). Displaying Item Tree

(3)(+0002125): itemTree.render(). Displaying Item Tree

(3)(+0001401): Reloading tags box

(3)(+0000018): Getting contents of jar:file:///C:/Users/ADMIN/AppData/Roaming/Zotero/Zotero/Profiles/07c0u8qm.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///C:/Users/ADMIN/AppData/Roaming/Zotero/Zotero/Profiles/07c0u8qm.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(3)(+0000394): HTTP GET jar:file:///C:/Users/ADMIN/AppData/Roaming/Zotero/Zotero/Profiles/07c0u8qm.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000190): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000148): HTTP GET file:///C:/Users/ADMIN/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg

(3)(+0000021): HTTP GET file:///C:/Users/ADMIN/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg succeeded with 0

(1)(+0000002): TypeError: blob is null _importImage@chrome://zotero/content/xpcom/editorInstance.js:726:11

(3)(+0000002): [Zotero Better Notes] {}

**Comment by windingwind** [comment]
感谢反馈；z6版本已停止维护。
