### ISSUE TITLE
[Bug] 新建的笔记展示不完全

### ISSUE THREAD

**Issue by horaynia** [windingwind/zotero-better-notes#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.3.1
- Zotero Version: 7.0-b60
- Plugin Version:1.14-b53

### Describe the bug

新建笔记时，只能展示部分笔记。且无法进行拖动到最后面。
状态栏笔记图标展开时，是完整的笔记模版，在右侧从新建模版内创建笔记时，显示不完整。两个的笔记模版是一样的
<img width="1677" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/50537627/4e0c8097-e0eb-460e-8c44-306587763874">

### Debug Output

新建笔记时，只能展示部分笔记。且无法进行拖动到最后面。
状态栏笔记图标展开时，是完整的笔记模版，在右侧从新建模版内创建笔记时，显示不完整。两个的笔记模版是一样的
<img width="1677" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/50537627/36644144-c10a-4a31-aa67-855e4f4513d4">

**Comment by windingwind** [comment]
不太理解问题。 请禁用所有插件后重试
