### ISSUE TITLE
[Feature] Open multiple items in the Reader from a single link

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.60+91e1c6ca3 (64-bit)
- Plugin Version: 1.1.4-beta.53

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

The process of saving and restoring tabs is still quite painful:
1) https://github.com/windingwind/zotero-actions-tags/discussions/129: This action needs to save some special files which are not intuitive to use.
2) https://github.com/windingwind/zotero-actions-tags/discussions/206: This action generates a long list of items. This is probably what the user wants in some cases, but if the purpose is simply to restore the tabs later, it does not work well: it takes too much space and I could not find how to open all of them at once.
3) https://github.com/windingwind/zotero-actions-tags/discussions/213: That one would be nice also, but I would still need to navigate to that collection to reopen all the tabs.

I would like to simplify the process of saving and restoring a group of opened tabs.

**Why do you need this feature?**
I often need to switch between projects when discussing with different students or collaborators.

### Describe the solution you'd like

**The solution you'd like**

In order to do this, I would like to be able to save and restore the tabs to a single link that would reopen all the tabs from a single click.
I could see two ways to do this:

1) Use a "zotero://open-pdf/library/items/[...]" link with multiple PDF files
The advantage is that it is very compact and simple. The drawback is that a new link would need to be created again every time. we want to update the group of tabs.

2) Use a "zotero://open/library/collections/[...]" link to open all the PDF files within a collection.
This is nice, as we can update more easily the content of the collection, and we can manually open a sub-set of them.
But this would take more space in the UI.

Ideally, the solution implemented should still work when not using the plugin, or revert to some default behaviour.

**Alternatives you've considered**

The implementation of [this](https://github.com/windingwind/zotero-actions-tags/discussions/213) would already simplify the process significantly.
I can also create a collection manually from the tabs, but this would take a very long time.
Otherwise, I am not sure what are the development plans of Zotero in this direction, which may provide a better way to save and restore tabs.

**Comment by windingwind** [comment]
I think the restore tabs isn't part of this plugin?

**Comment by mjthoraval** [comment]
I actually started writing this in the A&T plugin.
But then I considered that it probably cannot be done as a simple script, because it needs to modify the behaviour of the "zotero://[...]" links.
And then it slowly shifted towards a generalization of the "zotero://[...]" links.
And since this plugin is already doing this with the "zotero://note/[...]" links, I thought that this may be a better place to implement and test this feature.

Maybe a more general way to formulate this would be to enhance the "zotero://[...]" links to:
- Open multiple notes or PDFs from a single link, either in tabs of the main window or in separate tabs
- Restore a workspace note with several other notes in the side pane and in separate windows
- ...

Just some thoughts about this.
Maybe this can be archived if it is out of the scope of this plugin.

**Comment by mjthoraval** [comment]
I have put a more general idea of this in the forums:
https://forums.zotero.org/discussion/112222/zotero-7-beta-enhanced-zotero-links#latest
