### ISSUE TITLE
[Feature] Move the pinned icon of the Workspace note when it is closed

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.60+91e1c6ca3 (64-bit)
- Plugin Version: 1.1.4-beta.53

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
I find it annoying to always see the pinned icon of the Workspace note when it is closed.
Sometimes it reopens automatically after closing other tabs.

**Why do you need this feature?**
I would like to move the icon of the closed Workspace note to another place, so that it does not interfere with the navigation in tabs when I am not using it.

### Describe the solution you'd like

**The solution you'd like**
Maybe in this place would be nice:
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/8728500a-51db-4332-b50b-acbd3702f727)

**Alternatives you've considered**
I always disable the plugin to get rid of that tab icon.
But then I need to re-activate it any time I want to use the note links.

**Comment by windingwind** [comment]
Yes! Since the Z7 introduces a toolbar above the collections, we should move the button to the toolbar. Thanks for the report.

**Comment by mjthoraval** [comment]
Thanks.
Maybe still keep the option to pin the Workspace note tab, but behaving the same as a pinned tab in a browser:
- Keep it visible only when the tab is open
- Do not expand the tab title when opening it
- Remove it when closing the tab

I guess that this is a more general feature (tab pinning) that should be implemented in Zotero also for other Reader tabs. But I don't know if it is planned to be implemented soon.

**Comment by windingwind** [comment]
OK, just removed it to the toolbar, which is more reasonable to me. In the very early version, it was above the collection list. 

v1.1.4-beta.54

I think it's not the right time to do too many hacks to the tabs, since the Z7 is still in beta. Thanks for the suggestion!

**Comment by mjthoraval** [comment]
Thank you very much!
It is working perfectly.
It feels much nicer now that it does not interfere with the other tabs when it is closed.
