### ISSUE TITLE
[Feature] 可以增加之前那个切换笔记的按钮吗，在工作区可以立马切换

### ISSUE THREAD

**Issue by liuenqian** [windingwind/zotero-better-notes#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

![image](https://github.com/windingwind/zotero-better-notes/assets/64129965/5eeb1f84-ef91-45dc-a945-5d3a45585620)

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
<img width="820" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/33902321/c35f903d-8874-426b-809c-d5ae5b85d728">
