### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tobiaskramer** [windingwind/zotero-better-notes#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 11 23H2
- Zotero Version:  7.0.0-beta.60+91e1c6ca3 (64-bit)
- Plugin Version: 1.0.4

### Describe the bug

Maybe I am using a not supported combination of zotero beta and this plugin, which looks very promising to me:

Export note to docx does not work for me (it asks for a filename,  but not file is created).
Export note to PDF does not work for me (it does not even ask for a filename)
Export note to MD works.

Thanks for your time and work in this useful extension!

### Debug Output

1708776199781	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1708776200327	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "NS_ERROR_ILLEGAL_VALUE" {file: "jar:file:///C:/Users/XXXXXXr/AppData/Roaming/Zotero/Zotero/Profiles/2zzd2831.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/index.js" line: 38104}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\XXXXX\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.60+91e1c6ca3, os => Windows 10.0 22631, locale => en-US, extensions => Zotero Better Notes (1.0.4, extension), ZotFile (5.1.2, extension, disabled), Night (0.1.0-1, extension, disabled), Wandering File (0.2.8, extension, disabled), ZotMeta (1.1, extension, disabled), Better BibTex for Zotero (6.7.162, extension, disabled)

(3)(+0024040): itemTree.render(). Displaying Item Tree

(3)(+0000009): Reloading tags box

(3)(+0000017): Getting contents of jar:file:///C:/Users/Tobias%20Kramer/AppData/Roaming/Zotero/Zotero/Profiles/2zzd2831.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///C:/Users/XXXX/AppData/Roaming/Zotero/Zotero/Profiles/2zzd2831.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(3)(+0000095): HTTP GET jar:file:///C:/Users/XXXX/AppData/Roaming/Zotero/Zotero/Profiles/2zzd2831.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000003): [Zotero Better Notes] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Zotero Better Notes] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(4)(+0000018): Beginning DB transaction JZobY4J6

(4)(+0000003): Updating database with new item data

(4)(+0000001): UPDATE items SET synced=?, clientDateModified=? WHERE itemID=? [0, '2024-02-24 12:03:44', 8825]
[...]

(3)(+0000599): [Zotero Better Notes] {}

(3)(+0004615): Notifier.trigger('start', 'sync', []) called [observers: 3]

(3)(+0000003): Unregistering full-text content processor idle observer

(3)(+0000000): Stopping full-text content processor

(4)(+0000005): Beginning DB transaction l9GKLfzm

(4)(+0000007): Committed DB transaction l9GKLfzm

(4)(+0000002): Beginning DB transaction aSEFwyPy

(4)(+0000001): CREATE TEMPORARY TABLE tagDelete AS SELECT tagID FROM tags WHERE tagID NOT IN (SELECT tagID FROM itemTags)

(4)(+0000001): CREATE INDEX tagDelete_tagID ON tagDelete(tagID)

(4)(+0000001): SELECT tagID AS id, name FROM tagDelete JOIN tags USING (tagID)

(4)(+0000000): DROP TABLE tagDelete

(4)(+0000002): Committed DB transaction aSEFwyPy

(4)(+0000000): Beginning DB transaction PqA4HcLW

(4)(+0000003): Committed DB transaction PqA4HcLW

(3)(+0000001): Purged data tables in 19 ms

(3)(+0000001): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000000): HTTP GET https://api.zotero.org/keys/current

(3)(+0000398): HTTP GET https://api.zotero.org/keys/current succeeded with 200

(3)(+0000002): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(3)(+0000002): { "userID": 4989670 "username": "REMOVE" "displayName": "" "access": { "user": { "library": true "files": true "notes": true "write": true } "groups": { "all": { "library": true "write": true } } } }

(4)(+0000001): Beginning DB transaction QTodbLjX

(3)(+0000002): [ConcurrentCaller] All tasks are done

(4)(+0000003): Committed DB transaction QTodbLjX

(3)(+0000003): [ConcurrentCaller] Running function (0/4 running, 0 queued)

(3)(+0000001): HTTP GET https://api.zotero.org/users/XXXXX/groups?format=versions

(3)(+0000183): HTTP GET https://api.zotero.org/users/XXXXX/groups?format=versions succeeded with 200

(3)(+0000002): [ConcurrentCaller] Done with function (0/4 running, 0 queued)

(3)(+0000001): Local groups:

(3)(+0000001): []

(3)(+0000001): Final libraries to sync:

(3)(+0000000): [ "0": 1 ]

(3)(+0000002): Starting data sync for My Library

(4)(+0000001): SELECT setting, value FROM syncedSettings WHERE synced=0 AND libraryID=? [1]

(3)(+0000001): [ConcurrentCaller] All tasks are done

(3)(+0000003): No settings to upload in My Library

(4)(+0000002): SELECT O.collectionID FROM collections O WHERE libraryID=? AND synced=0 [1]

(4)(+0000003): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'collection']

(3)(+0000003): No collections to upload in My Library

(4)(+0000002): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 1]

(3)(+0000002): No collection deletions to upload in My Library

(4)(+0000001): SELECT O.savedSearchID FROM savedSearches O WHERE libraryID=? AND synced=0 [1]

(4)(+0000006): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'search']

(3)(+0000002): No searches to upload in My Library

(4)(+0000001): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 4]

(3)(+0000003): No search deletions to upload in My Library

(4)(+0000002): SELECT O.itemID FROM items O LEFT JOIN itemAttachments IA USING (itemID) LEFT JOIN itemNotes INo ON (O.itemID=INo.itemID) LEFT JOIN itemAnnotations IAn ON (O.itemID=IAn.itemID) WHERE libraryID=? AND synced=0 AND (IAn.isExternal IS NULL OR IAN.isExternal=0) [1]

(4)(+0000002): SELECT key FROM syncQueue WHERE libraryID=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, 'item']

(3)(+0000002): 1 item to upload in library 1

(4)(+0000001): SELECT key FROM syncDeleteLog WHERE libraryID=? AND syncObjectTypeID=? [1, 3]

(3)(+0000004): No item deletions to upload in My Library

(3)(+0000001): {"item":[8825]}

(4)(+0000001): Registering notifier observer 'itemsUpload_9Q' for [item]

(4)(+0000001): Beginning DB transaction c9ji6ejk

(4)(+0000003): SELECT data FROM syncCache WHERE libraryID=? AND key=? AND version=? AND syncObjectTypeID IN (SELECT syncObjectTypeID FROM syncObjectTypes WHERE name=?) [1, '486TY462', 23282, 'item']

(4)(+0000012): Committed DB transaction c9ji6ejk

(3)(+0000001): UPLOAD BATCH:

**Comment by windingwind** [comment]
If you are on Z7, please use the latest beta of the plugin.

**Comment by tobiaskramer** [comment]
Thanks! I can confirm that the beta version works for me regarding PDF / DOCX export.
