### ISSUE TITLE
Please consider another name for the plugin

### ISSUE THREAD

**Issue by woodwm** [windingwind/zotero-better-notes#9]
Probably "Knowledge4Zotero" is not a good name for it because zotero is a knowledge management tool. If you search "knowledge zotero" in google, you are unable to find the plugin. If you use "knowledge zotero plugin", you can only find the post in Zotero forum, rather then the github page.

Please consider a better name for it. "BetterNotes" or something else.

**Comment by windingwind** [comment]
This addon is inspired by Citavi's knowledge function, that's why it's called *Knowledge4Zotero*.

It was first called Notero in the inside version, but soon we found this name is already taken by another addon.

Thanks for your suggestion, but changing the name, especially after the addon is released, will cause tons of problems, like an auto-update failure, and being unable to find the addon(from the forum and other social media links).

**Comment by woodwm** [comment]
Github allows redirect the link. See https://github.blog/2013-05-16-repository-redirects-are-here/. Forum post can also be edited.

I never used Citavi, so not sure. I think "Knowledge" is a too broad word for this plugin. The name is difficult to find in google. Please try the keywords I showed.

**Comment by woodwm** [comment]
Workflow is how people use the software not the things the software is dealing with. See [zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex). It mainly operates on bibtex, including citation key and bibtex output. It certainly defines a workflow for latex user as well. "better-bibtex" is a clear name for it.

Why notes editor enhancement is limited for this plugin? This is exactly it is doing.

**Comment by windingwind** [comment]
Nice point.

You convinced me. We do have a long bargain about the name. Unfortunately, most of them are already used.

I'll change the repo name. Thanks!

**Comment by woodwm** [comment]
I guess you can leave it for few days before making the final decision. You may also ask for suggestions on the Zotero forum. I think you will get many great ideas about the names.

**Comment by windingwind** [comment]
> I guess you can leave it for few days before making the final decision. You may also ask for suggestions on the Zotero forum. I think you will get many great ideas about the names.

Aha, I just did the rename. The name is good enough!

Leave it for a while until there is a better name. Thanks!

**Comment by virologist** [comment]
Zotero-better-note matchs my mind. Lol

**Comment by windingwind** [comment]
I need some time to update the documents and code to adjust the new name. If you are willing to help, welcome any PR!

**Comment by woodwm** [comment]
The collection name "My Knowledge" can be renamed as "Notes Workspace" or "Notes Hub" or other similar.

Please run some tests (or beta versions) before you commit the name changes to avoid make trouble for the existing users.

**Comment by windingwind** [comment]
I'll make a pre-release for the first version after the rename.

Don't worry, the "My Knowledge" is just a recommended place to put your notes. Rename it or not does not affect your data or this addon's function.

**Comment by windingwind** [comment]
@woodwm Please try the pre-release v0.2.0-0. Besides the rename, some buttons in the workspace window are moved to the menu bar.

**Comment by woodwm** [comment]
I think the following is the default created notes in the main workspace. The templates need to be changed as well.

https://github.com/windingwind/zotero-better-notes/blob/7bde66723f1a03682f265738671709ffce73f3a1/src/wizard.ts#L17-L18

**Comment by windingwind** [comment]
The v0.2.0 is released, with the new feature of inserting links to the main note.
The template is updated.

**Comment by windingwind** [comment]
I'll close this issue.
