### ISSUE TITLE
[Bug] Auto synced md file contains random suffix 

### ISSUE THREAD

**Issue by zhengchencai** [windingwind/zotero-better-notes#90]
Thanks for this amazing tool.

**Describe the bug**
Auto synced note md file name contains a random suffix, e.g., my main note name is ```MainNote```, but the auto synced one is ```MainNote-WGB5C48P.md```. Manually exported note will use the same name as the note per se. It would be nice to preserve the same names for md files while syncing to a folder.

**Comment by windingwind** [comment]
This is actually not a **random** suffix. It's the note's unique key aim to avoid conflict.
If you want to maintain the notes and manually prevent conflict, you could edit the template `ExportMDFileName`. This template controls the filenames when syncing.

**Comment by zhengchencai** [comment]
Thanks a lot. I didn’t know this was intended. Will take a look the template file.
