### ISSUE TITLE
[Bug] Paper阅读界面笔记入口消失

### ISSUE THREAD

**Issue by zhangchaodesign** [windingwind/zotero-better-notes#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 13.5 
- Zotero Version: 7.0.0-beta.63+965149fe0
- Plugin Version: 1.1.4-beta.56

### Describe the bug

在paper阅读界面，在右侧侧边栏找不到打开note的入口

<img width="1920" alt="Screenshot 2024-02-27 at 11 14 41 AM" src="https://github.com/windingwind/zotero-better-notes/assets/35649822/34e3d11c-9967-491b-908d-a9a4769e44f0">

### Debug Output

[Debug Output.html.zip](https://github.com/windingwind/zotero-better-notes/files/14422763/Debug.Output.html.zip)

**Comment by windingwind** [comment]
请详细描述问题

**Comment by zhangchaodesign** [comment]
您好，您的邮件已经收到，我会尽快回复您，谢谢！祝您生活愉快，工作顺利！：）

**Comment by Jesselabrat** [comment]
我也没有 macbook, zotero 7.0.0-beta.64+8f8c0d079; 1.1.4-beta.56， 请问如何解决的呢

**Comment by zhangchaodesign** [comment]
> 我也没有 macbook, zotero 7.0.0-beta.64+8f8c0d079; 1.1.4-beta.56， 请问如何解决的呢

还没有解决。。。
