### ISSUE TITLE
[Bug] Dark mode icons

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-better-notes#902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.63+52856ae69 (64-bit)
- Plugin Version: 1.1.4-beta.56

### Describe the bug

The icons for the note popup window need to be updated for the dark mode:
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/f1a42897-2015-4560-9b38-d9ad6d3c8b5d)

Somehow, they are also not in the same order:
![image](https://github.com/windingwind/zotero-better-notes/assets/36054098/da2cbb21-1e95-4236-97af-d7b97d2f12ff)

### Debug Output

1709057596332	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1709057598139	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 820}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:820:7

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "o.current is null" {file: "resource://zotero/note-editor/editor.js" line: 6}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

1709057725044	addons.xpi	WARN	Download of https://github.com/windingwind/zotero-pdf-translate/releases/latest/download/zotero-pdf-translate.xpi/download/v1.1.0-beta.31/zotero-pdf-translate.xpi failed: 404 Not Found

appName => Zotero, version => 7.0.0-beta.63+52856ae69, os => Windows 10.0 19045, locale => en-GB, extensions => Better Notes for Zotero (1.1.4-beta.56, extension), Notero (0.5.15, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.34, extension, disabled), Translate for Zotero (1.1.0-beta.30, extension, disabled), Open PDF for Zotero (0.0.11, extension, disabled), Better BibTex for Zotero (6.7.162, extension, disabled), Zotero Better Authors (4.1.3, extension, disabled), Zotero Attanger (1.1.3, extension, disabled), ZoteroPreview (0.7.2, extension, disabled)

(3)(+0093178): [Better Notes for Zotero] {}

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] {}

(3)(+0000016): [Better Notes for Zotero] {}

(3)(+0000000): [Better Notes for Zotero] {}

(3)(+0000001): [Better Notes for Zotero] {}

(3)(+0000000): [Better Notes for Zotero] {}

(3)(+0000000): [Better Notes for Zotero] {}

**Comment by windingwind** [comment]
Thanks, planned

**Comment by windingwind** [comment]
thanks for the feedback. fixed in v1.1.4-beta.57

**Comment by windingwind** [comment]
fixed in v1.1.4-beta.61
