### ISSUE TITLE
请问有办法让分离的笔记窗口置顶吗？

### ISSUE THREAD

**Issue by wjfu99** [windingwind/zotero-better-notes#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS
- Zotero Version: Zotero 7
- Plugin Version:1.1.4-beta.56

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
No

**Why do you need this feature?**
在读paper过程中可能会切换窗口/其他app，再想记笔记需要手动重新把笔记窗口调回前台，有点麻烦。而且平时习惯把zotero放竖屏，不使用分离窗口用侧边栏的话空间会不太够。
![image](https://github.com/windingwind/zotero-better-notes/assets/57850011/0c4d6586-e330-4f0f-bec3-bb956d32724c)

### Describe the solution you'd like

**The solution you'd like**
希望可以增加一个选项，让笔记窗口始终悬浮在所有应用之上，如果zotero插件的api没有提供该功能，是否有可能让笔记窗口至少可以悬浮在zotero的主界面之上？

**Alternatives you've considered**

**Comment by windingwind** [comment]
谢谢建议，但mac无法窗口置顶
