### ISSUE TITLE
[Bug] “文件”窗口无法新建笔记

### ISSUE THREAD

**Issue by sammo3182** [windingwind/zotero-better-notes#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11
- Zotero Version: 7.0.0-beta.65+b047f3d90 (64-bit)
- Plugin Version: 1.0.4

### Describe the bug

在工作区点击Zotero `文件` 窗口，下拉菜单无法正常显示，如下图：

![PixPin_2024-03-07_08-26-47](https://github.com/windingwind/zotero-better-notes/assets/6463211/13482aec-dd9f-4ef5-9b6f-4ec8e88a4813)

### Debug Output

1. 无法创建笔记
2. 无法使用模板
3. 使用“插入模板到工作区笔记”，只能显示通过import from clipboard 导入的模板，且显示错误如下图：

![PixPin_2024-03-07_08-33-14](https://github.com/windingwind/zotero-better-notes/assets/6463211/266cfb67-bbb9-42c4-af6d-d1c092bc898c)

### Anything else?

不是组件冲突问题，上述问题当关闭所有其他插件后依然存在。

**Comment by windingwind** [comment]
升级插件。
