### ISSUE TITLE
expect markdown table

### ISSUE THREAD

**Issue by morning-start** [windingwind/zotero-better-notes#91]

**Comment by windingwind** [comment]
Could you please describe in detail what the 'markdown table' means?

**Comment by morning-start** [comment]
like this
![image](https://user-images.githubusercontent.com/76601464/180436801-839c9aa6-321f-44cd-9b5d-f3f2ad8b56aa.png)

**Comment by windingwind** [comment]
No plan to support this feature, ‘cause Zotero note editor is a rich text editor, not a markdown editor.

**Comment by morning-start** [comment]
i think the table format is better to compare, but not must use markdown rule.

**Comment by windingwind** [comment]
please right click to insert a table.

**Comment by morning-start** [comment]
think you very much. 
I had use this function, and I found some incommodity.

1. Alignment can only be changed one by one.
2. Left click cannot change the mouse position, only right can.

**Comment by windingwind** [comment]
Currently Zotero’s note function is still not very mature. Providing more enhancements as a plugin is difficult and may cause potential conflicts.

To quickly insert a table with desired content or specific format, you could use the ‘Note Template’ function to make a template for the table.

The cursor position is a known issue and currently I don’t know how to fix it. Set/open another note as main note could solve this cursor issue temporarily. You could move the cursor with arrow keyboard as well.

**Comment by windingwind** [comment]
cursor bug is fixed.
