### ISSUE TITLE
[Feature] 在编辑笔记Markdown时一键切换预览和源码模式

### ISSUE THREAD

**Issue by fun1024** [windingwind/zotero-better-notes#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.65
- Plugin Version: 1.1.4-beta.56

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
当格式比较复杂的时候，直接在预览页面编辑md文件不太方便

**Why do you need this feature?**
希望能有类似 Typora 那样一键（ctrl+/）切换预览和源码模式

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
Zotero笔记不是markdown，是富文本，因此不存在所谓源码。个人认为所谓预览和源码模式是markdown无法做到所见即所得的一种妥协，没必要开倒车。
