### ISSUE TITLE
[Feature] 希望允许自定义转义规则

### ISSUE THREAD

**Issue by feeshy** [windingwind/zotero-better-notes#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0
- Plugin Version:1.1.4

### Describe the feature request

同步过后部分markdown语法会被转义成文本
目前发现的包括标签、勾选框、callout等
<img width="45" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/10860212/7fd141f0-9085-460f-bc29-3adc56eb4445">

### Describe the solution you'd like

希望支持用户修改转义规则

**Comment by feeshy** [comment]
对了，同步的使用场景一般是配合外部笔记软件，第一次导出之后，基本就不会再用Zotero自带的笔记编辑器添加新的格式了，如果只在第一次导出markdown时转义，之后每次同步不再重复转义，不知道有没有可行性

**Comment by windingwind** [comment]
使用`ExportMDFileContent`模板，类似https://github.com/windingwind/zotero-better-notes/discussions/646
请善用搜索
