### ISSUE TITLE
[Feature] 是否可以增加无序列表转思维导图的功能 Build mindmap from unordered list

### ISSUE THREAD

**Issue by shihanmax** [windingwind/zotero-better-notes#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: mac os
- Zotero Version: 6
- Plugin Version: 

### Describe the feature request

你好作者，非常感谢你为zotero编写的如此优秀的插件。
我这里有一个笔记转思维导图的疑问，还请作者解惑：

目前的设计是从1～6级标题转为思维导图中的树状结构，这个也符合直觉，但实际使用时，如果思维导图中一个节点的深度超过7，那么便无法再继续创建新的子节点了，而只能以正文的形式存在于笔记中，在脑图中无法体现。（受限于md只支持6级标题）。

无序列表天然支持无限层级，相对标题层级而言，似乎更适合转换为思维导图的结构，不知道作者设计时是否考虑过这个选项呢？

另外，如果目前无法/暂未实现的话，请问，是否还能够在BN的笔记中创建深度超过6的思维导图呢？谢谢！

Hi, thank you very much for creating such an excellent plugin for Zotero. I have a question regarding the conversion of notes into mind maps, which I hope you can clarify:

The current design converts headings from level 1 to level 6 into a tree structure within the mind map, which is intuitive. However, in practice, if a node in the mind map exceeds a depth of 7, it is no longer possible to create additional child nodes, and they can only exist in the notes in plain text form, not reflected in the mind map. This is due to the limitation that markdown supports only up to 6 levels of headings.

Unordered lists naturally support an unlimited number of levels, and compared to heading levels, they seem more suitable for conversion into the structure of a mind map. I wonder if you considered this option during the design process?

Additionally, if it is currently not possible or not yet implemented, may I ask if it is still possible to create mind maps with a depth exceeding 6 in BN's notes? Thank you!

**Comment by windingwind** [comment]
谢谢建议。
首先，不会支持列表作为思维导图的节点，因为列表内可以嵌套标题，导致层级混乱。
其次，本插件中的思维导图意在提供文档结构的展示与交互，并非思维导图软件。要创建复杂思维导图，请用专门软件。

**Comment by shihanmax** [comment]
> 谢谢建议。 首先，不会支持列表作为思维导图的节点，因为列表内可以嵌套标题，导致层级混乱。 其次，本插件中的思维导图意在提供文档结构的展示与交互，并非思维导图软件。要创建复杂思维导图，请用专门软件。

谢谢解答，明白了👍  btw 我最终采用六级以内的标题来构建知识结构，其余子层级用无序列表，这样基本上也能满足需求（或许是有些偏门的需求😂）
