### ISSUE TITLE
[Feature]在pdf注释中点击花形图案后能否根据markdown语法对生成的笔记进行格式渲染？

### ISSUE THREAD

**Issue by FongTsang** [windingwind/zotero-better-notes#92]
开发者你好，我遇到的问题是这样的，比如我在文章中创建了注释，我想把注释生成笔记，希望笔记生成的时候能根据注释的内容对笔记进行markdown排版，我习惯对每条注释起一个小标题，比如：
![图片](https://user-images.githubusercontent.com/53118840/180439317-2c2e0521-5010-4982-96d6-35b43b937ded.png)
在我点击花形图案把注释创建成笔记的时候，笔记内容是这样的，所有的内容挤成一行，注释中的换行符也被作为空格对待。
![图片](https://user-images.githubusercontent.com/53118840/180439506-b663f402-d076-46e9-bc8d-914abc65325e.png)
我每次都需要手动对每一条注释笔记进行排版，改成类似如下的形式：
![图片](https://user-images.githubusercontent.com/53118840/180439710-0ed4af0c-a214-4b39-b041-2b81a744e682.png)

如果注释在生成笔记的同时内直接根据markdown语法进行格式排版的话就更好了。

**Comment by windingwind** [comment]
可通过QuickNote模板配置自定义的笔记格式。请具体描述需要？

**Comment by FongTsang** [comment]
我的需求是这样的，当我点击pdf里面的注释的花形图案之后，生成笔记能把注释的第一句话作为标题，我试过换行、空一行，可是生成的笔记里都会把我的注释全部显示出来，换行和空一格都被视为一个空格。
![图片](https://user-images.githubusercontent.com/53118840/180502536-151263be-2a56-4751-bda0-ce30d82a5789.png)
![图片](https://user-images.githubusercontent.com/53118840/180502499-18d5b1d6-f509-49b8-8884-9084bcf0356b.png)
我希望我在把注释笔记添加在主笔记的时候，超链接只显示注释笔记的第一行，即下图中红色框框的部分，其他的内容，我希望在导出markdown的时候再显示。
![图片](https://user-images.githubusercontent.com/53118840/180502939-5a323938-3793-4025-9e07-964de22ff0c3.png)
这样主笔记在组织和整理的时候看着不会太凌乱。
不好意思，我不知道我表述的会不会不太清楚。

**Comment by windingwind** [comment]
已支持。请在菜单栏 编辑->模板编辑器中，选择QuickNote模板，在下方点击按钮重置（reset）来使用最新模板。
效果如图：

![image](https://user-images.githubusercontent.com/33902321/181722706-5e4b98d9-0353-4c91-9ae1-861e5b53dc49.png)
