### ISSUE TITLE
[Bug] 按照zotero6的模版正常使用一段时间后突然无法调用模版，报错Error: getAttachments() cannot be called on attachment items

### ISSUE THREAD

**Issue by Mississippi-wei** [windingwind/zotero-better-notes#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Mac
- Zotero Version: 6.0.37
- Plugin Version:1.0.4

### Describe the bug

按照zotero6的模版正常使用一段时间后突然无法调用模版，报错如下：
[JavaScript Application]
Template [Item] conclude article with metadata 论文阅读并包含元数据 Error: Error: getAttachments() cannot be called on attachment items

### Debug Output

version => 6.0.37, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.37, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.37, extension), Zotero Word for Mac Integration (6.0.10.SA.6.0.37, extension), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), Zotero PDF Translate (1.0.25, extension, disabled), Zotero Reference (0.5.8, extension, disabled), Zotero Style (2.6.7, extension, disabled), Zotero Better Notes (1.0.4, extension, disabled)

### Anything else?

![WX20240326-230252](https://github.com/windingwind/zotero-better-notes/assets/165098371/51afb4b8-3769-44da-8184-09b53f34747c)
![WX20240326-230317](https://github.com/windingwind/zotero-better-notes/assets/165098371/e8725284-cef6-4f00-89e4-12acd3f0604d)

**Comment by windingwind** [comment]
1. 模板问题请向对应作者反馈
2. 善用搜索

**Comment by Mississippi-wei** [comment]
> 1. 模板问题请向对应作者反馈
> 2. 善用搜索

收到，感谢！
