### ISSUE TITLE
Optimize text citation and note titles

### ISSUE THREAD

**Issue by Pengzhi-Gao** [windingwind/zotero-better-notes#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: window 10 22h2
- Zotero Version:  6.0.36
- Plugin Version: 1.0.4

### Describe the feature request

Hello author, thank you for your work and efforts in providing us with this plugin. Recently, while using your plugin, I found that adding two features could enhance its usability. Firstly, when adding citation text to notes, it would be helpful if it automatically turned blue. This highlighting would make it easier to distinguish quoted text from the main body of the text. Secondly, incorporating a function to collapse title text would improve the readability of notes.

**Comment by windingwind** [comment]
> Firstly, when adding citation text to notes, it would be helpful if it automatically turned blue. This highlighting would make it easier to distinguish quoted text from the main body of the text. 

See https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#builtin-templates

> Secondly, incorporating a function to collapse title text would improve the readability of notes.

See existing issues/discussion.
