### ISSUE TITLE
[Feature] Define custom storage path for image pasted from clipboard into note editor

### ISSUE THREAD

**Issue by divisonofficer** [windingwind/zotero-better-notes#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 6.0.36
- Plugin Version:  1.0.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

Can i assign a new path of storage for image files in md notes?

**Why do you need this feature?**

When i insert any image from the clipboard into md editor embedded in this plugin, it is copied to the zotero default filesystem.

But, A storage located in Cloud Service (in my case, MS OneDrive) is my present configure for PDF files. It is useful to get rid of burden of narrow space of the free zotero cloud.

I designed this using Zotfile. Zotfile can reallocate attachments of items when they appear in zotero library. So zotero cloud only syncs metadata and notes.

The key is, the image file copied by ZoteroBettherNote is directedly transfered to zotero default filesystem, regardless of attachments manage system. Since image file of note never appear in zotero library, it can't be synced both zotero cloud and zotfile.

### Describe the solution you'd like

**The solution you'd like**
If there is a option for define default location for image attachments of markdown notes, Various methods are possible for organizing image files well.

**Comment by windingwind** [comment]
as explained in other threads, zotero note's images are managed by zotero and thus not possible to use `custom path`.
