### ISSUE TITLE
[Feature] 建议将工作区主笔记中【展开笔记卡片】功能设为快捷键触发

### ISSUE THREAD

**Issue by BlinVin** [windingwind/zotero-better-notes#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS  Catalina 10.15.7 
- Zotero Version: 6.0.30
- Plugin Version: 1.0.4

### Describe the feature request

平时在工作区笔记中回顾浏览时，需要点击链接再点击展开按钮才能实现【展开笔记卡片】，如果浏览大量的笔记时，这样会非常麻烦（累手T^T）。见附图
![Snipaste_2024-03-30_20-19-24](https://github.com/windingwind/zotero-better-notes/assets/67635827/835f0d47-1348-47ce-97fc-e7e03f1b8e3e)

### Describe the solution you'd like

希望开发大佬能够将【展开笔记卡片】功能设为 【快捷键触发】
细究起来，选中的单个笔记卡片、该标题下全部笔记卡片、全部笔记卡片 这三类可以设定【各自的快捷键】触发展开
obsidian中的做法是 鼠标置于链接处，点击command，即可弹出相应的卡片，见附图。但是对于工作区笔记这种文本而言，展开卡片比弹出卡片更合适一些
![Snipaste_2024-03-30_20-12-52](https://github.com/windingwind/zotero-better-notes/assets/67635827/ca6b6513-3d3a-4e4d-9d29-c90cb8bd21f3)

**Comment by windingwind** [comment]
请使用点击链接来预览笔记。所谓的“展开”实为“导入到当前笔记”，请不要用于预览内容。
