### ISSUE TITLE
[Bug] 找不到内置模板，复制安装后无法使用

### ISSUE THREAD

**Issue by AnYu124** [windingwind/zotero-better-notes#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 22H2
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4

### Describe the bug

安装插件后没有内置模板，无“使用模板插入多条笔记”“使用模板插入多个条目”等选项
![图片](https://github.com/windingwind/zotero-better-notes/assets/158389183/93f4f1ed-1ad7-4c57-a5a7-676c879832eb)

复制代码从剪贴板导入，显示格式invalid

复制讨论区网友分享的代码，粘贴在编辑器，可以新建模板，但选用时报错
![图片](https://github.com/windingwind/zotero-better-notes/assets/158389183/316b71f2-94b1-4898-a01a-34127e945d4f)

### Debug Output

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://18353730673%40163%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://18353730673%40163%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

[JavaScript Error: "XML Parsing Error: no root element found
Location: https://18353730673%40163%2Ecom:****@dav.jianguoyun.com/dav/zotero/
Line Number 1, Column 1:" {file: "https://18353730673%40163%2Ecom:****@dav.jianguoyun.com/dav/zotero/" line: 1}]

No chrome package registered for chrome://betternotes/content/icons/favicon.png

No chrome package registered for chrome://betternotes/content/icons/favicon.png

[JavaScript Error: "1712023426247	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1712023426248	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

Security Error: Content at moz-nullprincipal:{d8aa7482-0f5b-470b-a293-6cc838437d4a} may not load or link to chrome://betternotes/content/treeView.html.

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///C:/Users/chen/AppData/Roaming/Zotero/Zotero/Profiles/e3ah6xm6.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///C:/Users/chen/AppData/Roaming/Zotero/Zotero/Profiles/e3ah6xm6.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.36, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.36, extension), Zotero Word for Windows Integration (6.0.4.SA.6.0.36, extension), Zotero PDF Translate (1.0.25, extension), Jasminum (0.2.8, extension), Zotero Better Notes (1.0.4, extension)

**Comment by AnYu124** [comment]
CS小白，不确定是不是bug，您看有什么解决方案吗

**Comment by windingwind** [comment]
需要自己添加模板，没有内置的

**Comment by AnYu124** [comment]
您好，是这儿，“插入模板”中无内容，“使用模板插入多条笔记”“使用模板插入多个条目”选项不存在。

![image](https://github.com/windingwind/zotero-better-notes/assets/158389183/63044f03-2e45-49a7-92b0-2ce1bc32c704)
“Better Notes为这三类提供了数个默认的模板，具体功能在模板标题中说明，可尝试使用。”

**Comment by windingwind** [comment]
> “Better Notes为这三类提供了数个默认的模板，具体功能在模板标题中说明，可尝试使用。”

你看的文档已经过时

> 复制导入社区内已有的模板也无法使用，错误如下：

你使用了一个依赖zotero-style插件的模板。请善用搜索，或者尝试别的模板

**Comment by AnYu124** [comment]
明白了，感谢您耐心回复。
