### ISSUE TITLE
[Bug] Note Workspace's Viewport loses track of the current focused line when getting resized

### ISSUE THREAD

**Issue by ThachNgocTran** [windingwind/zotero-better-notes#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10 x64 (22H2)
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4

### Intro

When I read to a certain line within Note Workspace, I move to another tab (PDF Viewer) to read, and from time to time, switching on/off the button:

![button](https://github.com/windingwind/zotero-better-notes/assets/9520123/24c3056c-359c-4355-9ba6-bbd2ce513412)

When switching back to the Note Workspace, the lastly focused line is now out of sight (maybe above or under). This is troublesome because if the Note Workspace is long, it takes time to get back to the aforementioned line. I workarounded this issue by marking the line with additional characters, e.g. AAA, then I only need to Ctrl + F with the phrase to jump to the line.

We can also see this issue by just resizing the splitter in Note Workspace, as showed in the Reproducibility part.

I know when resizing, the Note Workspace's Viewport has to accommodate the new size changes, thus re-rendering itself. But it would be great if the resizing is done, without losing track of the current line.

### Reproducibility

https://github.com/windingwind/zotero-better-notes/assets/9520123/766dedf4-c23b-4550-804b-31a08f53dc68

### Acceptance Criteria

A fixed solution would look like: when resizing, one sees the scrollbar changes (bigger or smaller, up or down), but the currently focused line should not move out of the current Viewport.

https://github.com/windingwind/zotero-better-notes/assets/9520123/eda86c35-96ec-47ed-b5b0-5966a4d8c853

### Debug Output

Debug Output when resizing the splitter (before this, cleared the Debug output).

[Debug Output.zip](https://github.com/windingwind/zotero-better-notes/files/14832316/Debug.Output.zip)

**Comment by windingwind** [comment]
Thanks for the feedback. Sorry there will be no further updates to the Z6 version, but this is fixed in the latest Z7 beta release (1.1.4-beta.60)
