### ISSUE TITLE
建议下一级标题自动缩进4个字符宽度；标题下内容也自动缩进4个字符宽度。或者在前面基础上，各层级分别用各自颜色显示

### ISSUE THREAD

**Issue by lmlm1995** [windingwind/zotero-better-notes#93]
建议下一级标题自动缩进4个字符宽度；标题下内容也自动缩进4个字符宽度。或者在前面基础上，各层级分别用各自颜色显示

**Comment by windingwind** [comment]
现在的缩进方式有什么问题么

**Comment by lmlm1995** [comment]
好像没有自动缩进，字体大小也差不多，所以不知道哪个是一级标题，哪个是二级标题。现在我自己加上序号，分辨起来就清楚很多了。







better-note真是个好东西，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] 建议下一级标题自动缩进4个字符宽度；标题下内容也自动缩进4个字符宽度。或者在前面基础上，各层级分别用各自颜色显示 (Issue #93)





 
现在的缩进方式有什么问题么

**Comment by lmlm1995** [comment]
好像没有自动缩进，字体大小也差不多，所以不知道哪个是一级标题，哪个是二级标题。现在我自己加上序号，分辨起来就清楚很多了。







better-note真是个好东西，非常感谢！


还有个建议：是不是可以考虑将笔记自动生成到obsidian，并且实时双向更新，毕竟obsidian在文本编辑方面还是更方便些。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] 建议下一级标题自动缩进4个字符宽度；标题下内容也自动缩进4个字符宽度。或者在前面基础上，各层级分别用各自颜色显示 (Issue #93)





 
现在的缩进方式有什么问题么

**Comment by windingwind** [comment]
目前是每级标题缩进2字符，同时字号小一点。可能对比不是那么明显
后面我考虑在标题之前加上一些标记符号来指示层级，用颜色来表示可能会扰乱视觉效果
