### ISSUE TITLE
[Feature] markdown同步功能

### ISSUE THREAD

**Issue by pengxy0** [windingwind/zotero-better-notes#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: zotero7-54版
- Plugin Version: 1.1.4-49

### Describe the feature request

再使用zotero better notes将笔记导出到obsidian中，同步方式有两种，一种是通过工具栏里的同步管理器进行同步，另一种是笔记页面右上角的齿轮按钮里的立即同步选项。第一种同步功能可以选中文献1的笔记同步不影响文献2的笔记；而第二种齿轮同步方式，在文献1的笔记页面同步会影响文献2的笔记，相当于第一种同步功能不选择任何文献直接同步。那第一种同步管理器的方式的那个文献比较多的时候，需要寻找是哪一篇文献的笔记，有些不方便。
![PixPin_2024-04-05_00-54-10](https://github.com/windingwind/zotero-better-notes/assets/130196652/bbee2348-ec80-4f54-9df6-ff1724ea47c8)

### Describe the solution you'd like

希望大佬可以将第二种同步方式更改为只同步当前的笔记，不知这样修改是不是会比较麻烦。因为自动同步带来的风险可能比较大，手动同步会好一点。还希望大佬可以修改一下！给大佬鞠躬！

**Comment by pengxy0** [comment]
@windingwind 感谢大佬的改进。我看同步这个功能的改进是在better notes 58版本上，我目前正在使用的是zotero 54版本，所以better notes 只能安装49版本，暂时不想更新zotero。大佬要是在better notes 49版本上改进，太浪费你时间了。所以我想自己把这个同步的脚本添到better notes 49上，是否可行？这个有操作难度么？我是脚本小白哈哈哈。

**Comment by pengxy0** [comment]
@windingwind 
大佬帮我看下，是按照87ae3b0的脚本，这样操作下是不是可以的？
![image](https://github.com/windingwind/zotero-better-notes/assets/130196652/57d57ef6-1278-467a-a0de-9ada399b8a81)

**Comment by windingwind** [comment]
是的
