### ISSUE TITLE
Zotero 7版本sync header信息

### ISSUE THREAD

**Issue by ZIV-LY** [windingwind/zotero-better-notes#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0
- Plugin Version: 1.1.4-beta.57

### Describe the feature request

导出为markdown后，sync可以同步正文的修改，但是修改的header不能同步过去。只有把markdown文件删除之后再同步才可以更新成为最新的header信息。
Zotero 6 的插件可以同步header，但是Zotero 7目前似乎还不能。
感谢大佬！！

**Comment by windingwind** [comment]
不太明白你的意思。

> 但是修改的header不能同步过去

zotero不支持存储header信息，因此md的编辑不作用于zotero数据。
header中仅以`$`开头的键，会随每次同步由zotero中的数据覆盖更新。

**Comment by ZIV-LY** [comment]
> 不太明白你的意思。
> 
> > 但是修改的header不能同步过去
> 
> zotero不支持存储header信息，因此md的编辑不作用于zotero数据。 header中仅以`$`开头的键，会随每次同步由zotero中的数据覆盖更新。

非常感谢大佬的回复！我确实没表达清楚，我的意思是在zotero里面的信息，比如标题，年份，导出到markdown的时候这些字段作为header输出到markdown的yaml。之后我在zotero更新了这些信息，比如标题，年份，我点击sync到markdown，是否这些信息可以更新markdown的yaml区。
我隐隐约约记得在zotero 6里面的这些zotero的header的更新是能同步到markdown的，不过也有可能我记错了，哈哈哈😂

**Comment by windingwind** [comment]
> header中仅以$开头的键，会随每次同步由zotero中的数据覆盖更新。

**Comment by ZIV-LY** [comment]
> > header中仅以$开头的键，会随每次同步由zotero中的数据覆盖更新。

哦哦，是这样啊，明白了！谢谢大佬😄

**Comment by pengxy0** [comment]
> > > header中仅以$开头的键，会随每次同步由zotero中的数据覆盖更新。
> 
> 哦哦，是这样啊，明白了！谢谢大佬😄

你好，我刚接触这块东西，按照大佬说的，是不是就不能更新。
