### ISSUE TITLE
[Bug] 1.1.4-beta.58 breaks native relations between notes

### ISSUE THREAD

**Issue by ulahcherubim** [windingwind/zotero-better-notes#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11 Pro Version 10.0.22631 Build 22631
- Zotero Version: 7.0.0-beta.71+03d0ea436 (64-bit)
- Plugin Version: 1.1.4-beta.58

### Describe the bug

When I ugraded the plugin the last beta of 1.1.4-beta.58 version, my related fields in native Zotero notes started to disappear. Luckily I will be most likely to recover them from a back up but it is a dangerous bug. Even though I unchecked "Take over note relation" from the plugin's settings and tried using "Take over opening note" for opening notes in new tab, it still deleted the native relations. After disabling the plugin, the relations didn't recover.
I see and fully support the idea of a note graph in Zotero but no feature of this plugin should delete native relations imho. 
Also the plugin breaks right-hand pane:
![image](https://github.com/windingwind/zotero-better-notes/assets/134001160/2e7012e6-fbfb-4877-8492-d216f29a1e9c)
Video of the process:
https://drive.google.com/file/d/1dRHLqi4JYoJmU-STpbyW5QoPCXQXCPyZ/view?usp=drive_link

### Debug Output

Couldn't provide this because it is so long.

**Comment by windingwind** [comment]
Thanks for the feedback. I have released a 1.1.4-beta.59 to prompt confirmation for note relation control.

I do not have access to your share, and we'd better start a new issue for the layout bug.

**Comment by windingwind** [comment]
Yes, the graph relies on the related field, which is automatically updated if you allow the plugin to take over. It might still work, though, if you disable the setting and manually manage relations - but then there is no promise that the links between notes are correctly represented.

**Comment by ulahcherubim** [comment]
I see that relating notes in this way is different from native relations. One needs to use the ZBN option to relate in order to establish the relation without it getting broken after a refresh. Should I start a new issue for this? I also opened access to the video which is not the UI problem but the relation problem. You would see that it doesn't open the tab if you don't allow to take over on opening notes. I am starting a new issue for the UI problem.

**Comment by windingwind** [comment]
So I've released a 1.1.4-beta.63, where the related field is no longer used for storing note link relations. The data is now stored in the database locally.

Welcome discuss at https://github.com/windingwind/zotero-better-notes/discussions/938
