### ISSUE TITLE
[Bug]文本翻译的内容无法保存到笔记

### ISSUE THREAD

**Issue by fan291752035** [windingwind/zotero-better-notes#94]
![image](https://user-images.githubusercontent.com/73932884/180900628-5f4858fe-5d42-4c27-ab2a-b08da47ddfb9.png)

**Comment by windingwind** [comment]
如果先创建的笔记，再翻译内容，是无法更新过来的

**Comment by fan291752035** [comment]
> 如果先创建的笔记，再翻译内容，是无法更新过来的

不是先创建的笔记，我是先翻译之后，然后在创建笔记
昨天这个功能还是正常的，zotero重启之后也没有效果

**Comment by fan291752035** [comment]
我PDF translate 功能关闭自动翻译批注时，手动翻译之后就会出现这个情况，当我打开自动翻译批注功能时就会正常更新翻译内容

**Comment by windingwind** [comment]
我试了下，如果翻译内容保存在comment，加入是正常的；保存在批注本身，关闭pdf重新打开以后再创建笔记才正常。我会检查一下，目前可以设置保存翻译位置为保存在批注评论

**Comment by fan291752035** [comment]
对的，保存在批注可以使用，关闭PDF重新打开之后也正常了，麻烦作者大大了
