### ISSUE TITLE
[Bug] 工作区

### ISSUE THREAD

**Issue by anshangtangyuan** [windingwind/zotero-better-notes#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11
- Zotero Version: 最新
- Plugin Version:最新

### Describe the bug

更新最新版本后没有了工作区笔记项目，然后有按回了旧版包括插件和zotero  结果 工作区笔记全都没了？

### Debug Output

额嗯

**Comment by windingwind** [comment]
工作区的概念已去掉，现在可以打开任意数量的笔记标签/窗口

**Comment by anshangtangyuan** [comment]
可以像之前工作区那样，将笔记整到一块吗？

**Comment by anshangtangyuan** [comment]
> 工作区的概念已去掉，现在可以打开任意数量的笔记标签/窗口
可以像之前工作区那样，将笔记整到一块吗？

**Comment by windingwind** [comment]
不理解你说的整到一块是什么意思。

**Comment by anshangtangyuan** [comment]
> 不理解你说的整到一块是什么意思。
![image](https://github.com/windingwind/zotero-better-notes/assets/125590994/5e628658-8bbd-452c-8b80-f7b6827084ea)
这样，不同文献的笔记，以及网络上整理的笔记，整合到一起
