### ISSUE TITLE
[Bug] Link current note to another note window search is unresponsive, cannot link multiple notes

### ISSUE THREAD

**Issue by ulahcherubim** [windingwind/zotero-better-notes#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11 Pro Version 10.0.22631 Build 22631
- Zotero Version: 7.0.0-beta.73+398454f85 (64-bit)
- Plugin Version: 1.1.4-beta.63

### Describe the bug

When I try the new function to link current note to another note via button, the window opened has a search bar. However this search bar is unresponsive and cannot execute any search. Also selecting multiple notes to link is not working, this might be another issue or a request.
Video link: https://drive.google.com/file/d/1yrb0K1k8RAAM0QKmR4ZVhbmpSpqD6aPe/view?usp=sharing

### Debug Output

Debug output:

https://docs.google.com/document/d/156_mUDArAN9X1gD3hVj8nzUEndLq8D92p-zgxnUcYYs/edit?usp=sharing

**Comment by Exilioloz** [comment]
same problem, search function not responsive

**Comment by windingwind** [comment]
search should be fixed in 1.1.4-beta.64;

the multiple link is not an option for now, since I don't know how to provide multiple previews at the same time.

**Comment by ulahcherubim** [comment]
Search is fixed now, thanks.
