### ISSUE TITLE
[Bug] Link current note to another note window cannot be resized, opened notes section disappear when list is long

### ISSUE THREAD

**Issue by ulahcherubim** [windingwind/zotero-better-notes#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

OS: Win 11 Pro Version 10.0.22631 Build 22631
Zotero Version: 7.0.0-beta.73+398454f85 (64-bit)
Plugin Version: 1.1.4-beta.63

### Describe the bug

When I try the new function to link current note to another note via button, the window opened cannot be resized. 
Also it has a opened notes section at the bottom but when the list is long, opened notes section disappears.
As a side note, relation graph node text is small imho. Making it customizable or a bit bigger or perhaps showing full title when hovered might be a good idea. 

Video link:
https://drive.google.com/file/d/1z0YSfn90zfE__-_9QTKjdaCuwRS1_rTb/view?usp=sharing

### Debug Output

Debut output: https://docs.google.com/document/d/1dYR3TbO-uPWunHbs1rC3vLcfz8NfqD4FrfayZdIqiWA/edit?usp=sharing

**Comment by Exilioloz** [comment]
same problem, search not responsive

**Comment by windingwind** [comment]
fixed by 1.1.4-beta.64

**Comment by ulahcherubim** [comment]
Unfortunately after I updated the plugin, opened notes section still disapper when item list or collections list is long (I think this is the case). Also I still cannot resize the window.
Video: https://drive.google.com/file/d/1-gjyrdpR99nVow95R5JOXWa6WmARJHZ1/view?usp=sharing
Debug file: https://drive.google.com/file/d/1-tnGgVpC4Lq9XbGY2SJDv4xhnk4werkS/view?usp=sharing

**Comment by windingwind** [comment]
Did you try restarting Zotero (fully restarting, with ctrl+Q)?

**Comment by ulahcherubim** [comment]
Yes, I tried with fully restarting my PC. It still cuts of the open notes pane when the item list is long. I think long item list causes collections list to get elongated and it gets on top the pane.

**Comment by windingwind** [comment]
Please check 1.1.4-beta.65

**Comment by ulahcherubim** [comment]
Thank you! Resizing issue is gone but still open notes pane is not shown when item list is long.
Debug: https://pastebin.com/W4DFQ63g
Video: https://drive.google.com/file/d/1-z5pdreHF0HgX_Np-K7yEOf2lmxa6rck/view?usp=sharing

**Comment by windingwind** [comment]
Please check 1.1.4-beta.66

**Comment by ulahcherubim** [comment]
It solved the problem, thank you.
