### ISSUE TITLE
模板编辑器里出现了很多无法删除的模板

### ISSUE THREAD

**Issue by kjoying** [windingwind/zotero-better-notes#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 6.0.36
- Plugin Version:1.0.4

### Describe the bug

模板编辑器里出现了很多无法删除的模板
![PixPin_2024-04-13_19-31-37](https://github.com/windingwind/zotero-better-notes/assets/148022514/f682a7a4-fb58-40ed-a52c-6f09003e589d)

### Debug Output

想知道怎么删掉这些空模板

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes/discussions/802
