### ISSUE TITLE
Opened Notes section disappears from the Note choice window before item can be selected

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-better-notes#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version:  7.0.0-beta.74
- Plugin Version: 1.1.4-beta.65

### Describe the bug

I am attempting to put an item note into a Better Note. When I click on the Better Note icon in the Item Note, it opens a window to choose the note and where to put it. For a second, I see a section in the bottom-left that says Opened Notes, but it disappears before I can choose it. Then I have to search through the entire My Library to find the note again.

### Debug Output

1713048906282	addons.xpi	WARN	Checking C:\Users\Donna Baker\Zotero\Zotero 7 Beta\distribution\extensions for addons

1713048906767	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713048906767	addons.webextension.zoterotag@euclpts.com	WARN	Loading extension 'zoterotag@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713048906770	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713048906770	addons.webextension.zoterotag@euclpts.com	WARN	Loading extension 'zoterotag@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

1713059297828	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data(resource://gre/modules/addons/AddonUpdateChecker.sys.mjs:314:23) JS Stack trace: onLoad@AddonUpdateChecker.sys.mjs:314:23
UpdateParser/<@AddonUpdateChecker.sys.mjs:258:54

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

[JavaScript Error: "TypeError: document.l10n is null" {file: "chrome://global/content/elements/search-textbox.js" line: 118}]
disconnectedCallback@chrome://global/content/elements/search-textbox.js:118:7
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkNoteDialog@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32552:12
listener@jar:file:///C:/Users/Donna%20Baker/AppData/Roaming/Zotero/Zotero/Profiles/jsagh6x5.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32586:33

appName => Zotero, version => 7.0.0-beta.74+2e8073ab9, os => Windows 10.0 22631, locale => en-US, extensions => Actions and Tags for Zotero (1.0.0-beta.38, extension), Better Notes for Zotero (1.1.4-beta.65, extension), Add-on Market for Zotero (1.6.0, extension), Zutilo Utility for Zotero (3.10.0, extension, disabled), Night (0.1.0-2, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Zotero OCR (0.7.1, extension, disabled), Zotero Attanger (1.1.7, extension, disabled)

**Comment by ulahcherubim** [comment]
Same issue with #944

**Comment by windingwind** [comment]
See 1.1.4-beta.66
