### ISSUE TITLE
[Feature] Open/edit markdown attachments (.md files) in Zotero to avoid reinventing the wheel！！！

### ISSUE THREAD

**Issue by 1067237855** [windingwind/zotero-better-notes#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

An idea about zotero note editing: there are many software on the market that support markdown file editing, so there are many good wheels (for markdown file editing), and if zotero can support opening/editing markdown attachments (.md files) in zotero, you can avoid the process of reinventing the wheel (For example: plugins for note import/export, plugins for annotation cross-referencing, plugins for linking Zotero with Obsidian, etc., can all be uninstalled.). The .md file itself is a universal format, and the .md note file is stored as an attachment under the Zotero entry, which can be opened with either Zotero or an external Markdown editor, which will be a wonderful thing!!

### Describe the feature request

An idea about zotero note editing: there are many software on the market that support markdown file editing, so there are many good wheels (for markdown file editing), and if zotero can support opening/editing markdown attachments (.md files) in zotero, you can avoid the process of reinventing the wheel (For example: plugins for note import/export, plugins for annotation cross-referencing, plugins for linking Zotero with Obsidian, etc., can all be uninstalled.). The .md file itself is a universal format, and the .md note file is stored as an attachment under the Zotero entry, which can be opened with either Zotero or an external Markdown editor, which will be a wonderful thing!!

### Describe the solution you'd like

An idea about zotero note editing: there are many software on the market that support markdown file editing, so there are many good wheels (for markdown file editing), and if zotero can support opening/editing markdown attachments (.md files) in zotero, you can avoid the process of reinventing the wheel (For example: plugins for note import/export, plugins for annotation cross-referencing, plugins for linking Zotero with Obsidian, etc., can all be uninstalled.). The .md file itself is a universal format, and the .md note file is stored as an attachment under the Zotero entry, which can be opened with either Zotero or an external Markdown editor, which will be a wonderful thing!!

### Anything else?

An idea about zotero note editing: there are many software on the market that support markdown file editing, so there are many good wheels (for markdown file editing), and if zotero can support opening/editing markdown attachments (.md files) in zotero, you can avoid the process of reinventing the wheel (For example: plugins for note import/export, plugins for annotation cross-referencing, plugins for linking Zotero with Obsidian, etc., can all be uninstalled.). The .md file itself is a universal format, and the .md note file is stored as an attachment under the Zotero entry, which can be opened with either Zotero or an external Markdown editor, which will be a wonderful thing!!

**Comment by windingwind** [comment]
Not sure what you are requesting. You can always open any file attachment in Zotero with any third-party software.

**Comment by windingwind** [comment]
Anyway, I will not do this. Zotero is not going to be a markdown editor.
