### ISSUE TITLE
[Feature] Maintain the last used UI layout

### ISSUE THREAD

**Issue by occasional15** [windingwind/zotero-better-notes#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win 11
- Zotero Version:  7 beta
- Plugin Version: 1.14 beta.66

### Describe the feature request

**Why do you need this feature?**
When we open a note as tab or window, it seems better to maintain the last used UI layout (whether to show and how wide are the left and right columns). We don't need to adjust the UI layout of every note as we want everytime.

BTW, this new beta version is amazing!!
另外想问下大佬可以开放支付宝或微信赞助吗？没找到。

**Comment by ulahcherubim** [comment]
I think this might have to do with Zotero's not remebering latest pane widths. There are some issues in Zotero 7 beta right now because of Firefox version bump (such as links to Zotero not working outside of Zotero) and I think this will be solved after these problems are solved.

**Comment by occasional15** [comment]
补充说明：阅读文献时，打开右侧快捷选项卡中的notes列表，右键note>edit in a separate window，可以用软件的默认方式打开note且保持上次的note界面布局。因此，1）可以考虑类似实现打开BN note时保持上次的note界面布局。2）如图，建议此处可以考虑添加右键“open as tab or window”打开BN note的快捷方式（不然只能单击进入note然后点击右上角“三个点”再选择open as tab or window）。
![1713339851203(1)](https://github.com/windingwind/zotero-better-notes/assets/147971641/0faafe45-967e-45d3-913a-43e81847822c)

**Comment by mjthoraval** [comment]
It seems that Zotero now remembers the width of the panes.
Can this be addressed now?

**Comment by occasional15** [comment]
测试过几次，其他没问题，但是高度无法保持调整后的状态，请验证。
感谢大佬，太厉害了！

**Comment by windingwind** [comment]
高度指的是什么？

**Comment by occasional15** [comment]
> 高度指的是什么？

就是UI界面的高度，每次打开都回到了初始高度（大约电脑屏幕的1/3）。

**Comment by windingwind** [comment]
不太理解是什么的高度。可否截图看一下

**Comment by occasional15** [comment]
> 不太理解是什么的高度。可否截图看一下

双击note或使用open as window后，UI界面的高度都回到了初始高度（大约电脑屏幕的1/3），每次调整后都一样。如图：
![image](https://github.com/windingwind/zotero-better-notes/assets/147971641/491ac8e3-71ef-4398-a297-477a7a37ca3f)

**Comment by occasional15** [comment]
再详细描述一下需求，以供参考：
1）软件本身能实现的：打开notes列表，右键note>edit in a separate window，可以用z7软件的默认方式打开note且保持上次任意调整后的note界面布局及长宽比。
2）BN note的状况：在列表中双击note或使用open as window，可以以单独窗口打开BN note，但是，**此窗口的长宽比每次都会回到初始状态（如上面的截图，长宽分别为约电脑屏幕的1/2和1/3）**，不能维持上次调整后的状态（习惯上以调整到类似pc微信界面的窗口大小为宜，即略小于1/2电脑屏幕）。

**Comment by ramonmi** [comment]
> 再详细描述一下需求，以供参考： 1）软件本身能实现的：打开notes列表，右键note>edit in a separate window，可以用z7软件的默认方式打开note且保持上次任意调整后的note界面布局及长宽比。 2）BN note的状况：在列表中双击note或使用open as window，可以以单独窗口打开BN note，但是，**此窗口的长宽比每次都会回到初始状态（如上面的截图，长宽分别为约电脑屏幕的1/2和1/3）**，不能维持上次调整后的状态（习惯上以调整到类似pc微信界面的窗口大小为宜，即略小于1/2电脑屏幕）。

open as tab也无法保持上次调整的UI

**Comment by occasional15** [comment]
> open as tab也无法保持上次调整的UI

open as tab可以保持上次的UI布局和窗格尺寸，这个是没问题的。有问题的是open as window的单独窗口。你再确认一下。

**Comment by ramonmi** [comment]
> > open as tab也无法保持上次调整的UI
> 
> open as tab可以保持上次的UI布局和窗格尺寸，这个是没问题的。有问题的是open as window的单独窗口。你再确认一下。

重启软件后确实可以了，谢谢提醒。
