### ISSUE TITLE
导出PDF文件无法显示高亮颜色[Feature]

### ISSUE THREAD

**Issue by jamerri** [windingwind/zotero-better-notes#95]
建议作者是否能够将导出的PDF文件显示高亮颜色。
另外，笔记内的字体颜色是否能够进行设置。

**Comment by windingwind** [comment]
字体颜色目前可以通过插入文本模板中设置颜色，在颜色字体后面继续编辑也会带有对应颜色。导出pdf的高亮消失原因还在排查，谢谢反馈
