### ISSUE TITLE
[Bug] Both in tab view and window view, linked notes cannot be moved around via outline

### ISSUE THREAD

**Issue by ulahcherubim** [windingwind/zotero-better-notes#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11
- Zotero Version: 7.0.0-beta.74+2e8073ab9 (64-bit)
- Plugin Version: 1.1.4-beta.66

### Describe the bug

When I try to use outline view to move around notes, outline view changes but not the actual content. 

https://github.com/windingwind/zotero-better-notes/assets/134001160/094c30f4-f3b4-4530-ad44-4c7234aba8e7

### Debug Output

https://pastebin.com/SdxZXizR

### Anything else?

On another note, it might be very good if we can open a global graph view. I know this is a big thing, but I am considering writing my academic materials solely in this plugin. Thanks a lot!

**Comment by windingwind** [comment]
try 1.1.4-beta.69

**Comment by ulahcherubim** [comment]
Now it works, thanks for the fix!
