### ISSUE TITLE
[Bug] Cannot link a note to another note

### ISSUE THREAD

**Issue by jianghuchuanshuo** [windingwind/zotero-better-notes#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: window 11
- Zotero Version: 7.0.0-beta.74+2e8073ab9
- Plugin Version:1.1.4-beta.68

### Describe the bug

Cannot link a note to another note;
Connecting Thesis Notes to Total Notes but clicking repeatedly doesn't work, closing all other plugins, restarting zotero and reinstalling the plugin doesn't work.

### Debug Output

[JavaScript Error: "TypeError: this.collectionsView is undefined" {file: "chrome://betternotes/content/scripts/customElements.js" line: 17203}]
destroy@chrome://betternotes/content/scripts/customElements.js:17203:7
disconnectedCallback@chrome://zotero/content/elements/base.js:61:10
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkCreator@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32553:12
listener@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32587:30

**Comment by windingwind** [comment]
Sorry, I do not understand. Please provide the screenshot/record, steps to reproduce, and full debug output.

**Comment by jianghuchuanshuo** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/34358874/718e28a1-d3cf-4ee6-80cf-4b66d8ec8d10)

**Comment by jianghuchuanshuo** [comment]
like this：
![image](https://github.com/windingwind/zotero-better-notes/assets/34358874/7e65aad8-cb65-488d-881e-4cbb6aa1bd9b)

**Comment by jianghuchuanshuo** [comment]
there is the full debug output:

1713254955517	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

1713254955950	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713254955951	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713254955951	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713254955952	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713254955962	addons.webextension.Knowledge4Zotero@windingwind.com	WARN	Loading extension 'Knowledge4Zotero@windingwind.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955962	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955962	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955962	addons.webextension.jasminum@linxzh.com	WARN	Loading extension 'jasminum@linxzh.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.scipdf@ytshen.com	WARN	Loading extension 'scipdf@ytshen.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.zoterogpt@polygon.org	WARN	Loading extension 'zoterogpt@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.zoteroif@qnscholar	WARN	Loading extension 'zoteroif@qnscholar': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.zoteropdftranslate@euclpts.com	WARN	Loading extension 'zoteropdftranslate@euclpts.com': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.zoteroreference@polygon.org	WARN	Loading extension 'zoteroreference@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

1713254955963	addons.webextension.zoterostyle@polygon.org	WARN	Loading extension 'zoterostyle@polygon.org': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "TypeError: extraData is undefined" {file: "jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js" line: 36022}]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 681}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:681:7


1713265368403	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713265368404	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "original is undefined" {file: "jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/jasminum@linxzh.com.xpi!/chrome/content/scripts/index.js" line: 5029}]

1713265368576	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots

1713265368576	addons.webextension.greenfrog@redleafnew.me	WARN	Loading extension 'greenfrog@redleafnew.me': Reading manifest: Using experimental APIs requires a privileged add-on.

[JavaScript Error: "Request timed out"]

[JavaScript Error: "Request timed out"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{f6c8c1c8-678f-4195-b960-d6285874f0b5} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "extraData is undefined" {file: "chrome://betternotes/content/scripts/customElements.js" line: 21086}]

[JavaScript Error: "TypeError: extraData is undefined" {file: "jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js" line: 36022}]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{089689f3-f770-47e8-b068-ab1e60c24006} may not load or link to chrome://betternotes/content/lib/css/github-markdown.css."]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{089689f3-f770-47e8-b068-ab1e60c24006} may not load or link to chrome://betternotes/content/lib/css/katex.min.css."]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{089689f3-f770-47e8-b068-ab1e60c24006} may not load or link to chrome://betternotes/content/lib/css/github-markdown.css."]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{089689f3-f770-47e8-b068-ab1e60c24006} may not load or link to chrome://betternotes/content/lib/css/katex.min.css."]

[JavaScript Error: "TypeError: this.collectionsView is undefined" {file: "chrome://betternotes/content/scripts/customElements.js" line: 17203}]
destroy@chrome://betternotes/content/scripts/customElements.js:17203:7
disconnectedCallback@chrome://zotero/content/elements/base.js:61:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkCreator@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32553:12
listener@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32587:30


[JavaScript Error: "TypeError: this.collectionsView is undefined" {file: "chrome://betternotes/content/scripts/customElements.js" line: 17203}]
destroy@chrome://betternotes/content/scripts/customElements.js:17203:7
init/<@chrome://betternotes/content/scripts/customElements.js:17199:14
openLinkCreator@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32553:12
listener@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32587:30


[JavaScript Error: "TypeError: this.collectionsView is undefined" {file: "chrome://betternotes/content/scripts/customElements.js" line: 17203}]
destroy@chrome://betternotes/content/scripts/customElements.js:17203:7
disconnectedCallback@chrome://zotero/content/elements/base.js:61:10
disconnectedCallback@chrome://zotero/content/elements/base.js:60:10
_handleWindowUnload@chrome://zotero/content/elements/base.js:67:10
openLinkCreator@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32553:12
listener@jar:file:///C:/Users/zhangjian002/AppData/Roaming/Zotero/Zotero/Profiles/naoo7oyc.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js:32587:30


appName => Zotero, version => 7.0.0-beta.74+2e8073ab9, os => Windows 10.0 22631, locale => zh-CN, extensions => Jasminum (1.0.0-14, extension), Ethereal Reference (0.7.5, extension), Sci-PDF (1.1.1, extension), Zotero IF (1.5.4, extension), Awesome GPT (0.8.0, extension), Better BibTex for Zotero (6.7.174, extension), Translate for Zotero (1.1.0-beta.41, extension), Ethereal Style (4.3.5, extension), Better Notes for Zotero (1.1.4-beta.68, extension), Green Frog (0.18.06, extension), Sci-Hub Plugin for Zotero (1.4.4, extension, disabled), ZotFile (5.1.2, extension, disabled), Zotero PDF Preview (0.3.7, extension, disabled)

**Comment by windingwind** [comment]
try v1.1.4-beta.70

**Comment by jianghuchuanshuo** [comment]
Already tried v1.1.3-beta70, rebooted, reloaded, still doesn't work, can't connect to note, no change.

**Comment by windingwind** [comment]
Don't try to link an empty note created in the context pane (right pane in reader).

Update to v1.1.4-beta.71, you will get an error message when you try to do so.

**Comment by jianghuchuanshuo** [comment]
I didn't connect an empty note, the two notes connected to each other have content, I tried v1.1.4-beta.71 and it still doesn't work, nothing has changed, I can't connect, and there is no error message, what is the problem?

**Comment by windingwind** [comment]
In that case, check the note template `[QuickInsertV2]` (Settings - Better Notes - Open Template Editor). What does it look like?

**Comment by jianghuchuanshuo** [comment]
Think you, at first when I went into [QuickInsertV2] it was empty, reset it as below, now I can connect notes. Thank you very much.
![image](https://github.com/windingwind/zotero-better-notes/assets/34358874/6408df2d-2f07-42fa-8348-ee2b50b4884e)

**Comment by jianghuchuanshuo** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/34358874/36fc6b02-7622-4e5f-b302-a918a32424ae)
But another problem has arisen, adding notes here, before it was not adding, now I find that after clicking on add note, it appears in the notes of other documents, why is this happening?

**Comment by windingwind** [comment]
> But another problem has arisen, adding notes here, before it was not adding, now I find that after clicking on add note, it appears in the notes of other documents, why is this happening?

This is a Zotero feature, not related to this plugin. It adds the selected text as annotation to the note opened in the right pane。

**Comment by jianghuchuanshuo** [comment]
OK，thank you every much.
