### ISSUE TITLE
[Feature] 为一些子功能添加快捷键

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-better-notes#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows 10
- Zotero Version:  zotero 7 beta75
- Plugin Version: 1.1.4-beta.71

### Describe the feature request

为一些功能添加快捷键，比如对于双链重度用户，下面这两个功能可能需要经常使用

editor-toolbar-settings-copyLink=复制行(L{ $line })
editor-toolbar-settings-copyLinkAtSection=复制节(Sec. { $section })

### Describe the solution you'd like

为一些常用功能添加快捷键，快捷键允许用户自定义设置

**Comment by windingwind** [comment]
> 另外此处的功能还能用吗？还是废弃了？

已由新的link creator界面替代
