### ISSUE TITLE
[Bug] Outline not showing h2-h6 when no h1 present

### ISSUE THREAD

**Issue by ulahcherubim** [windingwind/zotero-better-notes#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win 11 Pro
- Zotero Version: 7.0.0-beta.75+f7dc68c7f (64-bit)
- Plugin Version: 1.1.4-beta.71

### Describe the bug

Outline only shows sub headers when h1 present.
![image](https://github.com/windingwind/zotero-better-notes/assets/134001160/36ce4cb7-ba72-4f2f-bf46-0ebd173e5d15)
![image](https://github.com/windingwind/zotero-better-notes/assets/134001160/6c1997cc-a012-47bd-b35a-893e6b3bcf8b)
![image](https://github.com/windingwind/zotero-better-notes/assets/134001160/6191645e-d536-434f-8e7a-a426da7b6ef8)

### Debug Output

[1.1-b Hume'un izlenimleri duyumsamaya, ideleri düşünmeye dayandırması](file:///%22zotero://select/library/items/RCWSRCAF/%22)
\n

İnsan zihninin empirik bir incelemesini sunmaya çalışan Hume, kendi araştırma programını sıkılıkla takip etmiş, geniş anlamda  tanımladığı gözlemlenebilir olana dayanarak (buraya Treatise'in ön sözündeki gözleme ilişkin tanıma atıf gelmeli) izlenimlerin ve idelerin kökenlerini ortaya koymuştur. Buna göre izlenimler duyumsamada, ideler düşünmede kökenlerini bulur. (Çıvgın, 2016, p. 383) (Coventry, 2007, p. 38)  Ancak düşünmeye konu olan ideler de izlenimlerin cansız birer kopyası olmakla duyumsama kökenine sahiptirler. Bununla birlikte insan zihnin düşünme özelliği sayesinde kopyası oldukları izlenimlerden farklılaşabilirler. (Hume, 2022, p. 24)
\n\n

[[[1.1-a Hume’da idelerin tanımı]]](file:///%22zotero://note/u/YGRYP9BE//%22)
\n

[[[1.1-a4-b Hume’da bellek ve imgelemin tanımları]]](file:///%22zotero://note/u/8RG32MFQ//%22)
\n
" "tags": [ "0": { "tag": "Hume" } "1": { "tag": "duyumsama" } "2": { "tag": "düşünme" } "3": { "tag": "empirizm" } "4": { "tag": "gözdengeçirilecek" } "5": { "tag": "ide" } "6": { "tag": "izlenim" } "7": { "tag": "moral felsefe" } "8": { "tag": "parçanot" } "9": { "tag": "ylt" } "10": { "tag": "yltkullanıldı" } ] "collections": [ "0": "7FIA3T7V" "1": "U9MMJ94E" ] "relations": { "dc:relation": [ "0": "http://zotero.org/users/9094695/items/6VIWY8JH" "1": "http://zotero.org/users/9094695/items/F2CSNLAW" "2": "http://zotero.org/users/9094695/items/M9827GWN" "3": "http://zotero.org/users/9094695/items/4EK8TAFX" "4": "http://zotero.org/users/9094695/items/4SRX5KUY" "5": "http://zotero.org/users/9094695/items/8RG32MFQ" "6": "http://zotero.org/users/9094695/items/YGRYP9BE" "7": "http://zotero.org/users/9094695/items/YQXQLWR4" "8": "http://zotero.org/users/9094695/items/I2A97Q7I" ] } "dateAdded": "2024-01-07T16:04:12Z" "dateModified": "2024-04-19T18:41:44Z" } } ] (4)(+0000001): INSERT OR REPLACE INTO syncCache (libraryID, key, syncObjectTypeID, version, data) VALUES (?, ?, ?, ?, ?) [1, 'RCWSRCAF', 3, 12238, '{"key":"RCWSRCAF","version":12238,"library":{"type":"user","id":9094695,"name":"Rıdvan Binici","links":{"alternate":{"href":"https://www.zotero.org/ridvanbinici","type":"text/html"}}},"links":{"self":{"href":"https://api.zotero.org/users/9094695/items/RCWSRCAF","type":"application/json"},"alternate":{"href":"https://www.zotero.org/ridvanbinici/items/RCWSRCAF","type":"text/html"}},"meta":{"numChildren":0},"data":{"key":"RCWSRCAF","version":12238,"itemType":"note","note":"
[1.1-b Hume'un izlenimleri duyumsamaya, ideleri düşünmeye dayandırması](file:///%22zotero://select/library/items/RCWSRCAF/%22)
\n

İnsan zihninin empirik bir incelemesini sunmaya çalışan Hume, kendi araştırma programını sıkılıkla takip etmiş, geniş anlamda  tanımladığı gözlemlenebilir olana dayanarak (buraya Treatise'in ön sözündeki gözleme ilişkin tanıma atıf gelmeli) izlenimlerin ve idelerin kökenlerini ortaya koymuştur. Buna göre izlenimler duyumsamada, ideler düşünmede kökenlerini bulur. (Çıvgın, 2016, p. 383) (Coventry, 2007, p. 38)  Ancak düşünmeye konu olan ideler de izlenimlerin cansız birer kopyası olmakla duyumsama kökenine sahiptirler. Bununla birlikte insan zihnin düşünme özelliği sayesinde kopyası oldukları izlenimlerden farklılaşabilirler. (Hume, 2022, p. 24)
\n\n

[[[1.1-a Hume’da idelerin tanımı]]](file:///%22zotero://note/u/YGRYP9BE//%22)
\n

[[[1.1-a4-b Hume’da bellek ve imgelemin tanımları]]](file:///%22zotero://note/u/8RG32MFQ//%22)
\n
","tags":[{"tag":"Hume"},{"tag":"duyumsama"},{"tag":"düşünme"},{"tag":"empirizm"},{"tag":"gözdengeçirilecek"},{"tag":"ide"},{"tag":"izlenim"},{"tag":"moral felsefe"},{"tag":"parçanot"},{"tag":"ylt"},{"tag":"yltkullanıldı"}],"collections":["7FIA3T7V","U9MMJ94E"],"relations":{"dc:relation":["http://zotero.org/users/9094695/items/6VIWY8JH","http://zotero.org/users/9094695/items/F2CSNLAW","http://zotero.org/users/9094695/items/M9827GWN","http://zotero.org/users/9094695/items/4EK8TAFX","http://zotero.org/users/9094695/items/4SRX5KUY","http://zotero.org/users/9094695/items/8RG32MFQ","http://zotero.org/users/9094695/items/YGRYP9BE","http://zotero.org/users/9094695/items/YQXQLWR4","http://zotero.org/users/9094695/items/I2A97Q7I"]},"dateAdded":"2024-01-07T16:04:12Z","dateModified":"2024-04-19T18:41:44Z"}}'] (3)(+0000000): [ConcurrentCaller] All tasks are done (4)(+0000013): Beginning DB transaction df79zv1m (4)(+0000001): Item 4966 has not changed (4)(+0000001): Updating database with new library data (4)(+0000000): UPDATE libraries SET version=?, storageVersion=? WHERE libraryID=? [12238, 12238, 1] (4)(+0000001): UPDATE items SET version=12238 WHERE itemID IN (?) [4966] (4)(+0000001): UPDATE items SET synced=1 WHERE itemID IN (?) [4966] (4)(+0000003): Committed DB transaction df79zv1m (4)(+0000001): DELETE FROM syncCache WHERE ROWID IN (SELECT SC.ROWID FROM syncCache SC LEFT JOIN items O USING (libraryID, key, version) WHERE syncObjectTypeID=? AND SC.libraryID=? AND (O.libraryID IS NULL OR SC.version < O.version)) [3, 1] (2)(+0000008): Failed: 0 (4)(+0000000): Unregistering notifier observer in notifier with id 'itemsUpload_ex' (3)(+0000000): Done uploading items in library 1 (3)(+0000000): {} (4)(+0000000): Upload result is 1 (4)(+0000001): Updating database with new library data (4)(+0000000): Beginning DB transaction TDgjRgVe (4)(+0000001): UPDATE libraries SET lastSync=? WHERE libraryID=? [1713552121, 1] (4)(+0000002): Committed DB transaction TDgjRgVe (3)(+0000001): Done syncing My Library (4)(+0000000): REPLACE INTO version (schema, version) VALUES ('lastsync', ?) [1713552121] (3)(+0000002): Starting file syncing (3)(+0000000): Done with file syncing (3)(+0000001): Starting full-text syncing (3)(+0000000): Done with full-text syncing (3)(+0000000): Done syncing (3)(+0000000): Notifier.trigger('finish', 'sync', []) called [observers: 4] (4)(+0000001): SELECT libraryID AS id FROM feeds WHERE refreshInterval IS NOT NULL AND ( lastCheck IS NULL OR (julianday(lastCheck, 'utc') + (refreshInterval/1440.0) - julianday('now', 'utc')) <= 0 ) (3)(+0000006): Running update for feeds: (3)(+0000000): All feed updates done (3)(+0000000): Scheduling next feed update (4)(+0000001): SELECT ( CASE WHEN lastCheck IS NULL THEN 0 ELSE strftime('%s', lastCheck) + refreshInterval * 60 - strftime('%s', 'now') END ) AS nextCheck FROM feeds WHERE refreshInterval IS NOT NULL ORDER BY nextCheck ASC LIMIT 1 (3)(+0000000): Next feed check in 1831 seconds (3)(+0002071): {better-bibtex} +18013 emit: better-bibtex event emit window-loaded {"win":"[object Window]","href":"chrome://zotero/content/standalone/basicViewer.xhtml"} (3)(+0000924): WebSocket message: {"event":"topicUpdated","topic":"/users/9094695","version":12238} (3)(+0000001): Library is already up to date (3)(+0001817): HTTP POST "1713551889059 addons.xpi WARN …" (207789 chars) to https://repo.zotero.org/repo/report?debug=1 (3)(+0000007): POST body gzipped from 207789 to 24416; 88% savings (3)(+0000885): HTTP POST https://repo.zotero.org/repo/report?debug=1 succeeded with 200

**Comment by windingwind** [comment]
Thanks, this is a known issue. Will look into it.
