### ISSUE TITLE
[Feature] 允许用户在思维导图（或大纲视图）上直接插入和编辑节点，然后反映到note中

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#96]
这个功能对于习惯用思维导图的用户而言会十分方便，尤其是在做笔记的时候

**Comment by windingwind** [comment]
导图的编辑功能将会是远期考虑补充的功能，近期受限于我个人的时间，没有办法增加大量新功能，以维护小功能与修复bug为主，谢谢建议
