### ISSUE TITLE
[Feature] 关系图一旦添加，好像无法调整，删除不了

### ISSUE THREAD

**Issue by she529** [windingwind/zotero-better-notes#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win
- Zotero Version: 最新测试版
- Plugin Version:最新版

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
链接精灵功能很有趣但是关系图一旦添加，好像无法调整，删除不了，不知能否在入链 出链处也添加删除选项
![1](https://github.com/windingwind/zotero-better-notes/assets/75371769/c7deff21-5dbf-46ce-a3f7-98d20a3bbc49)

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
请直接在笔记正文删除对应链接即可
