### ISSUE TITLE
[Bug] Better Notes images are not sync between devices

### ISSUE THREAD

**Issue by PotatoCL** [windingwind/zotero-better-notes#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 Pro 23H2
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4

### Describe the bug

The images in the better notes cannot be synced between each device. 
eg, I have inserted images in my better note plugin in zotero on device #1, then i checked from device #2, I can find the note, but the image is not there. Also, i checked online from my zotero web library, the same issue was there. That means, the images in the better notes plugin on my device #1 just stayed locally, instead of upload it to the zotero server.   

### Debug Output

Anyone can help me figure it out? thanks

**Comment by windingwind** [comment]
Multi-device syncing is a Zotero feature, not part of this plugin. Please report to zotero forums

**Comment by ramonmi** [comment]
beta 77 may have supported the images syncing.
