### ISSUE TITLE
这几次更新的版本，在构建笔记关联时失效，没有在zotero7的related里边生成关系

### ISSUE THREAD

**Issue by leedonghai** [windingwind/zotero-better-notes#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macOS 14.4.1 (23E224
- Zotero Version: 7.0.0-beta.75+f7dc68c7f
- Plugin Version:Release 1.1.4-beta.72

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
已不再使用笔记的related属性展示链接关系，有专门的位置展示，因此不自动改变related。如有需要可从笔记编辑器右上角菜单-更新关系手动生成笔记related。
