### ISSUE TITLE
[Bug] Sync error: Reference error: blob is not defined

### ISSUE THREAD

**Issue by DSZNETosis** [windingwind/zotero-better-notes#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 23H2
- Zotero Version: 6.0.36
- Plugin Version:1.0.4

### Describe the bug

This bug appeared when I am using Automatic Sync after I clicked “export the current note”.

In previous issue https://github.com/windingwind/zotero-better-notes/issues/502 
and
https://github.com/windingwind/zotero-better-notes/issues/550

I saw exactly the same error, and I have already updated the betternote plugin to 1.0.4 version.

I have not edited this note anywhere else， Just do it in Zotero. 
My notes do not contain any images, just the text synchronization of the problem

![Screenshot](https://github.com/windingwind/zotero-better-notes/assets/151889789/54c028d9-f5a1-4aef-9eb2-72c53dc53684)

![微信图片_20240422170527](https://github.com/windingwind/zotero-better-notes/assets/151889789/e7f27f7d-d990-4c8d-b2e8-6aa0a8610da7)

### Debug Output

[JavaScript Error: "TypeError: this.nestedTagsContainer is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/Users/HUAWEI/AppData/Roaming/Zotero/Zotero/Profiles/y63gkxzk.default/extensions/zoterostyle@polygon.org.xpi!/bootstrap.js -> jar:file:///C:/Users/HUAWEI/AppData/Roaming/Zotero/Zotero/Profiles/y63gkxzk.default/extensions/zoterostyle@polygon.org.xpi!/chrome/content/scripts/index.js" line: 14031}]

**Comment by windingwind** [comment]
Only the latest version (which is currently Release 1.1.4-beta.72) is maintained.
