### ISSUE TITLE
[Bug] 笔记中点击show on page无反应，有时会导致Zotero软件闪退

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: win11 23H2
- Zotero Version: 7.0.0-beta.75+f7dc68c7f (64-bit)
- Plugin Version: 1.1.4-beta.71

### Describe the bug

如图，在笔记中点击复制文本的show on page无反应，debug无输出，但有时会导致Zotero软件闪退
![微信截图_20240422195138](https://github.com/windingwind/zotero-better-notes/assets/105206348/9488c644-eaf9-446d-8552-72c385ee6c8d)

### Debug Output

无

**Comment by windingwind** [comment]
请禁用所有插件（troubleshooting mode）重试。该功能与插件无关，如仍出现问题，请向zotero forums反馈
