### ISSUE TITLE
[Bug] 问题1：笔记中图片会莫名变成的灰色矩形，重启也无法恢复显示；问题2：在插入新的链接后，有时部分内容会丢失

### ISSUE THREAD

**Issue by puppet9527** [windingwind/zotero-better-notes#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win11 23H2
- Zotero Version: 1.1.4-beta.72
- Plugin Version: 7.0.0-beta.76+91054acfe (64-bit)

### Describe the bug

问题1：笔记中图片会莫名变成的灰色矩形，重启也无法恢复显示
图片是截图，然后粘贴到笔记中。之后当再次打开查看时，图片莫名变成灰色矩形，重启也无法恢复显示。
![Clip_2024-04-24_16-37-20](https://github.com/windingwind/zotero-better-notes/assets/42835379/88782ed0-6b07-4ad2-849d-f2a0daa4ed68)

问题2：上午编辑的内容，在下午插入链接的操作后，先是没有显示出链接，重启后上午编辑的内容全部丢失，但插入的链接显示出来了。

### Debug Output

[Debug Output.zip](https://github.com/windingwind/zotero-better-notes/files/15091383/Debug.Output.zip)

### Anything else?

附件同步方式：webdav（坚果云）。我这个图片丢失问题是否与webdav同步有关？使用BN过程中，需要按ctrl+S进行保存吗？或者需要在插入链接前，先单击右上角的zotero的同步按钮，同步笔记内容？

**Comment by pengxy0** [comment]
你这两个问题我也遇到过。我也不知道是啥原因，有时候我把另一张图重新复制一下，那张灰色的就能刷新出来，有时候就不行。

**Comment by HMTTT** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/51215588/839f1eba-e0f7-463c-9168-40936f041963)

我今天也遇到了这个问题，复制图片时显示灰色方块，无法插入图片

**Comment by HMTTT** [comment]
> ![image](https://private-user-images.githubusercontent.com/51215588/325986019-839f1eba-e0f7-463c-9168-40936f041963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzcxMjksIm5iZiI6MTcxNDEzNjgyOSwicGF0aCI6Ii81MTIxNTU4OC8zMjU5ODYwMTktODM5ZjFlYmEtZTBmNy00NjNjLTkxNjgtNDA5MzZmMDQxOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEzMDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOGY0NzU1ZTc3MjM3NzAwZTEzOGYzMTM3NzgyYjVlMDNiOThiZDVmNTE2YTU0ODU0YzU3ZjAwMmI0ZmRiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wX1PRO1mL0sl51dw1tAtPpYjxBfsJu2a74o0Y8HdQi0)
> 
> 我今天也遇到了这个问题，复制图片时显示灰色方块，无法插入图片

直接在首页点击笔记进去无法复制图片，在论文侧边栏打开后可以正常插入图片
![image](https://github.com/windingwind/zotero-better-notes/assets/51215588/956ec92b-510f-4888-9644-50cd08fc3e60)

**Comment by puppet9527** [comment]
太感谢了，对我帮助很大。这个问题，我也遇到过，一直不知道什么原因导致的，就没反馈。估计我反馈的这个问题，跟你说的这个操作也有关。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月26日 21:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] [Bug] 问题1：笔记中图片会莫名变成的灰色矩形，重启也无法恢复显示；问题2：在插入新的链接后，有时部分内容会丢失 (Issue #966) |

我今天也遇到了这个问题，复制图片时显示灰色方块，无法插入图片

直接在首页点击笔记进去无法复制图片，在论文侧边栏打开后可以正常插入图片
image.png (view on web)

**Comment by windingwind** [comment]
问题1与插件无关，应在近期zotero7 beta更新中会解决。
问题2暂不清楚，笔记保存机制由zotero控制。当修改内容后在非常短暂时间内立刻关闭笔记编辑器/zotero，可能导致内容尚未保存。

**Comment by puppet9527** [comment]
原来如此，谢谢您的解答。问题2，我以后会注意一下操作速度的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月28日 20:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] [Bug] 问题1：笔记中图片会莫名变成的灰色矩形，重启也无法恢复显示；问题2：在插入新的链接后，有时部分内容会丢失 (Issue #966) |

问题1与插件无关，应在近期zotero7 beta更新中会解决。
问题2暂不清楚，笔记保存机制由zotero控制。当修改内容后在非常短暂时间内立刻关闭笔记编辑器/zotero，可能导致内容尚未保存。

**Comment by zhangyan000005** [comment]
我也遇到了，插入图片一直显示灰色框，之前的笔记图片就可以显示，请问这个问题要怎么解决呢？
环境
操作系统： Win11 23H2
Zotero 版本：7.0.0-beta.98+0b3eda5d8 (64-bit)
插件版本：1.1.4-beta.97

**Comment by dogeeelin** [comment]
请问这个问题解决了吗？同样的问题
![截屏2024-09-09 14 47 54](https://github.com/user-attachments/assets/039bd55f-771b-4f47-ace8-92e308001e8f)

**Comment by zhangyan000005** [comment]
您的邮件我已收到，谢谢！

**Comment by puppet9527** [comment]
没有解决，昨天又遇到了。都不知道什么情况下会出现这问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月09日 14:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [windingwind/zotero-better-notes] [Bug] 问题1：笔记中图片会莫名变成的灰色矩形，重启也无法恢复显示；问题2：在插入新的链接后，有时部分内容会丢失 (Issue #966) |

您的邮件我已收到，谢谢！

**Comment by windingwind** [comment]
请检查zotero数据同步是否正确设置。如果：
1. 使用链接附件+第三方网盘同步（例如onedrive）
2. 将数据目录设置为使用第三方网盘同步（例如onedrive）
3. 未设置数据同步
4. 数据同步存储空间不足

则可能发生上述问题，请调整同步方式

**Comment by Joe-Hall-Lee** [comment]
问题 1 又遇到了。

**Comment by zhangyan000005** [comment]
您的邮件我已收到，谢谢！
