### ISSUE TITLE
[Bug] 以Tab形式打开的笔记无法移动到新窗口

### ISSUE THREAD

**Issue by ramonmi** [windingwind/zotero-better-notes#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Win1123H2
- Zotero Version: 7.0.0-beta.76+91054acfe (64-bit)
- Plugin Version: 1.1.4-beta.72

### Describe the bug

直接在library双击打开的比较（即以Tab形式打开的笔记），可以移到最前或最后，但无法移动到新窗口can not move to new window，也无法复制标签页Duplicate Tab。不知是不是因为zotero7beta原生不支持。

### Debug Output

无

**Comment by windingwind** [comment]
可按住shift打开笔记，或笔记右上角菜单-在单独窗口打开

**Comment by ramonmi** [comment]
> 可按住shift打开笔记，或笔记右上角菜单-在单独窗口打开

好的，不过按住shift的话，使用的是默认note编辑界面，不包含BN的左侧大纲和右侧双链。那只能是右上角菜单，在单独窗口打开open as window了。
