### ISSUE TITLE
[Bug] Exports not working

### ISSUE THREAD

**Issue by macrospecter** [windingwind/zotero-better-notes#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Sonoma 14.3.1
- Zotero Version: 7.0.0-beta.77
- Plugin Version: 1.1.4-9

### Describe the bug

I've used Better Notes for about a year and never had this problem: suddenly my notes are just not exporting. I select "Export current note" in the Better Notes menu bar within the PDF reader, I am prompted to select options in the Export Notes window (like Linked Notes Mode, MD format, PDF format, etc.), and then nothing happens once I select ok. Ordinarily, after I select ok, I get another popup window asking me where the note should be saved. But now nothing. And also no linked note appears. No linked note appears in Obsidian (where I export notes to) or in the Sync Manager. Also immediately I am able to select "Export current note" again in the menu bar—which I ordinarily cannot do after a note has already been exported. Any suggestions for what might be wrong? All I see is a warning that no "namespace" is available. Thank you!

### Debug Output

(4)(+0021304): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [2400, '']

(3)(+0000009): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0001327): [Warning] Creating element title with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000002): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000003): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): [Warning] Creating element label with no namespace specified. Found multiply namespace matches.

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000000): {}

(3)(+0000001): {}

**Comment by windingwind** [comment]
Please update to the latest version of plugin.

**Comment by macrospecter** [comment]
1. It is very confusing which is the latest version. The latest version I see on github is 1.0.4, which seems _earlier_ than the original 1.1.4 I had. My latest update was also after the latest release of the plugin. However, I went ahead and downloaded 1.0.4 and replaced my 1.1.4. 

2. This didn't fix the problem. Notes are still not exporting.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-better-notes?tab=readme-ov-file#-install

According to the readme (which I suppose you have already read before posting this issue), if you are using Zotero 7 beta, you should always use the latest beta of this plugin. At the time I write this reply, it's 1.1.4-beta.72, while you are on 1.1.4-9

**Comment by macrospecter** [comment]
Ah I see! Very sorry. I read the Readme when I installed Better Notes, before moving to Zotero 7, and didn't realize it had been updated. As always, I very much appreciate this plugin!
