### ISSUE TITLE
[Bug] 直接复制带有Tab或者带#的条目到note中后，不会被顺利识别为标题。

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#97]
这个功能的用处在于，目前zotero better notes 的导图功能不够方便，我希望用其他导图软件对文章进行笔记，之后把很重要的内容复制到zotero 的note中。
此时复制过来的不同级别的内容一般会以不同缩进的形式体现，比如xmind中复制若干个节点之后粘贴到word或者zotero better notes中时，每一行开头会存在若干个tab来说明级别。本来我考虑借助一些文本替换工具（比如AHK）把Tab都替换成井号，必要时再在每行文字的开头和井号之间添加一个空格，但测试发现仍无法顺利使用。

比如 
“##a 
#b
## c 
”
这里的所有行都不能被顺利识别，即使井号与文本之间有空格。
建议将上述这种每行以tab或者井号开头的一串字符都能直接被识别成不同级别的标题。 
另外希望能对设置不同级别标题提供快捷键

**Comment by windingwind** [comment]
针对此问题以及#92 ，计划增加一种新的模板类型：输入字符串，输出对应格式的文本，用于转换markdown等格式的纯文本内容。

另标题快捷键是ctrl+shift+数字

**Comment by ghweili** [comment]
使用模板来插入似乎不够方便，如果从其他地方复制过来后直接就能粘贴那会方便不少。可以考虑设置一个替代粘贴的快捷键，当按这个键的时候，可以把剪贴板里的内容以预期的形式粘贴进来

**Comment by windingwind** [comment]
我可以从原理层面简单解释一下为什么有的软件（word）复制到笔记格式正常保留，从有的软件复制格式不保留。这实际上应该算是复制源的支持性问题，而非zotero笔记的问题。
zotero笔记是富文本编辑器，支持复制粘贴格式（以html富文本方式）。大多数软件复制内容时会以多种格式放入剪贴板，例如纯文本、富文本、markdown等。富文本方式的复制粘贴是可以保留格式的。
由于你提到的这个软件可能在复制内容时仅保留了纯文本，因此无法识别格式。

zotero笔记尽管是富文本编辑器，对markdown语法做了不少支持，但主要在输入时候。复制粘贴目前无法识别markdown语法。通过插件来修改粘贴逻辑有点困难。

一个想法：增加一个按钮，将剪贴板中的md文本以富文本格式转换并重新放入剪贴板，这样在粘贴的时候就能正确具有格式。是否可以？

**Comment by ghweili** [comment]
增加一个按钮是不错的想法，不过最好能为这些按钮添加键盘快捷键，最好是可自定义的键盘快捷键，这样会比较方便。通过模板功能我目前使用的还不熟，如果需要鼠标操作感觉有点麻烦。如果也可以自定义快捷键直接选择对应模板来转换并粘贴，应该不错。

目前我处理上述问题的思路是，在AHK等其他工具设置了一个快捷键，具体功能是：把选中部分自动复制到剪贴版，并把那些包含Tab的文本里的Tab转换为#，之后把新文本推送到剪贴板上。因此，当需要将这些内容贴到zotero时，在选中文本后不是按Ctrl+C复制，而是按前边提到的那个快捷键复制，之后粘贴就可以正常Ctrl+V 粘贴了，这个思路供参考

**Comment by windingwind** [comment]
功能入口：菜单栏编辑->转换剪贴板中的markdown。然后可以正常ctrl+v粘贴内容。
使用没问题的话，下次更新加个快捷键。另外什么快捷键合适？
