### ISSUE TITLE
I don't know which version of the plugin to start with, so I can no longer set the main note. This results in a series of functions not functioning properly. There is no relevant main note setting option in the right-click of the main page.[Feature] 

### ISSUE THREAD

**Issue by wingshuohuo** [windingwind/zotero-better-notes#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: I don't know which version of the plugin to start with, so I can no longer set the main note. This results in a series of functions not functioning properly. There is no relevant main note setting option in the right-click of the main page.
- Zotero Version: 
- Plugin Version:

### Describe the feature request

**Is your feature request related to a problem? Please describe.**

**Why do you need this feature?**
A clear and concise description of why you need this feature.

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by wingshuohuo** [comment]
不知道该从哪个版本的插件开始，所以我不能再设置主注释了。这导致一系列功能无法正常工作。在主页面的右键单击中没有相关的主注释设置选项。

**Comment by wingshuohuo** [comment]
不知道该从哪个版本的插件开始，所以我不能再设置主笔记的文件了。在主页面上的右键单击中没有相关的主笔记设置选项。这导致一系列功能无法正常工作，比如文献中的标注引用到主笔记中的功能等等。magic 插件的全文翻译也无法自动写入条目笔记了。

**Comment by wingshuohuo** [comment]
我在b站等找过相关问题，大家都遇到了这个问题，有些人不得不选择使用过去很久的版本的better notes。希望能尽快解决，或者给以解决的方法。

**Comment by windingwind** [comment]
re version:

https://github.com/windingwind/zotero-better-notes?tab=readme-ov-file#-install

re workspace:

https://github.com/windingwind/zotero-better-notes?tab=readme-ov-file#getting-started-with-the-workspace

**Comment by wingshuohuo** [comment]
To open the workspace, click the icon button in the tabs bar！！！！ 我的工作区上面没有这个笔记本的按钮！
![image](https://github.com/windingwind/zotero-better-notes/assets/116100828/478b30b5-47b6-4cef-a68d-1938fe13bfd0)
![Uploading image.png…]()

**Comment by wingshuohuo** [comment]
![image](https://github.com/windingwind/zotero-better-notes/assets/116100828/b387e223-1a06-432a-9ed8-61b0836f56a6)
重新安装了这个插件，依然没有这个按钮

**Comment by windingwind** [comment]
re workspace:

https://github.com/windingwind/zotero-better-notes?tab=readme-ov-file#getting-started-with-the-workspace

> 💡 This section is outdated and will be removed. For the latest beta version, the workspace is no longer a thing. You can open unlimited number of note tab/window, which is what we call workspace in the past.

**Comment by LandryJC** [comment]
如何才能作为窗口打开，可以作为独立窗口，但无法作为窗口显示。感觉还不如之前的工作区，这部分更新什么时候会有更详细的说明呢。

**Comment by windingwind** [comment]
> 如何才能作为窗口打开，可以作为独立窗口，但无法作为窗口显示。感觉还不如之前的工作区，这部分更新什么时候会有更详细的说明呢。

不理解你说的意思。

**Comment by XianheZhang** [comment]
在以往的主工作空间中，我可以方便地进行双链的链接，并轻松的预览他们的思维导图，这使得来自单篇文献的注释笔记有更好的归属感和十分明了的组织结构，我仿佛可以自然而然的完成一篇综述的大纲，而不幸的是，主笔记区的移除，工作空间的削弱，使得上述功能失效或大打折扣

**Comment by windingwind** [comment]
所谓工作区没有移除，只是由“仅限一个”变为“任意多个”。任何笔记都可以和过去的工作区一样打开为标签页，并带有侧边大纲/导图。
@XianheZhang 以及本issue中的所有回复：
提issue时请按照模板填写内容；回复/评论issue请尽量提供建设性内容（想要改进/添加/移除具体哪个功能）。关于不会用/找不到，请尽量在discussion中交流。由于此issue未有有效讨论，将关闭
