### ISSUE TITLE
[Bug] Cannot restore the Sync Manager info after Zotero migration

### ISSUE THREAD

**Issue by duduOliver** [windingwind/zotero-better-notes#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [x] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11 Pro 23H2
- Zotero Version: 6.0.36
- Plugin Version: 0.8.9

### Describe the bug

I've just migrated my Zotero to a new device with all Zotero data and attachments. In addition, I restore all the addons and preferences by using Tara (an addon). I also reviewed the `prefs.js` file under `AppData\Roaming` to double check if all the sync info of BN (better notes) has been appended in the `prefs.js` and it looked good. However, I can't find all the sync notes info in the Sync Manager after I started Zotero. 

### Debug Output

NULL

**Comment by windingwind** [comment]
Note syncing path may be different on different devices and the relevant settings do not support cross-device migration. You need to manually export and sync notes you want to sync in another device.

**Comment by duduOliver** [comment]
> Note syncing path may be different on different devices and the relevant settings do not support cross-device migration. You need to manually export and sync notes you want to sync in another device.

Thanks for your reply! 
The notes sync path is the same and I found there is a note sync record appearing in the Sync Manager on the new device. The awkward thing is the export path refers to a correct exported note path, but the Zotero note refers to the wrong one (It's a note but not a BN note). I thought the Sync Manager only tracks the notes by `noteMd5`, doesn't it? how come it tracks to the wrong one? Do I need to restore the `itemID`, but how? 
Do you know if there exist any configs or cookies related to Better Note and the Sync Manager besides `prefs.js`? 
In addition, do you consider adding new features to support the cross-device migration or any good solution for that?

**Comment by windingwind** [comment]
> The notes sync path is the same and I found there is a note sync record appearing in the Sync Manager on the new device.

The sync manager's prefs use the item id, which may differ on different devices' DB; only the library key + item key is unique. So please do not simply overwrite the prefs on another device.

On 1.1.4-beta.83, you may goto sync manager -> detect and choose the folder(s) where you place the synced markdown files. If you previously overwrite the prefs, please either revert or clear them in the sync manager before doing any detecting.

> I thought the Sync Manager only tracks the notes by noteMd5, doesn't it? how come it tracks to the wrong one? Do I need to restore the itemID, but how?

The MD5 can change anytime since Zotero is not aware of file modifications. It's only for deciding whether the markdown is modified and which side (Z or MD) is newer.

Please check if this new feature works well for you, and if it does, we could consider some background tasks to periodically check your directory and update the synced notes list.

**Comment by duduOliver** [comment]
Thanks a lot for your explanation, now I have a clearer vision of how the BN works. 
I'm looking forward to knowing if 1.1.4-beta.83 would help in the cross device sync issue, but do you have a Z6 version of it? As I haven't decided to move to Z7 yet.

**Comment by duduOliver** [comment]
> > The notes sync path is the same and I found there is a note sync record appearing in the Sync Manager on the new device.
> 
> The sync manager's prefs use the item id, which may differ on different devices' DB; only the library key + item key is unique. So please do not simply overwrite the prefs on another device.
> 
> On 1.1.4-beta.83, you may goto sync manager -> detect and choose the folder(s) where you place the synced markdown files. If you previously overwrite the prefs, please either revert or clear them in the sync manager before doing any detecting.
> 
> > I thought the Sync Manager only tracks the notes by noteMd5, doesn't it? how come it tracks to the wrong one? Do I need to restore the itemID, but how?
> 
> The MD5 can change anytime since Zotero is not aware of file modifications. It's only for deciding whether the markdown is modified and which side (Z or MD) is newer.
> 
> Please check if this new feature works well for you, and if it does, we could consider some background tasks to periodically check your directory and update the synced notes list.


Thanks a lot for your explanation, now I have a clearer vision of how the BN works.
I'm looking forward to knowing if 1.1.4-beta.83 would help in the cross device sync issue, but do you have a Z6 version of it? As I haven't decided to move to Z7 yet.

**Comment by duduOliver** [comment]
Just found a not perfect solution. 

1. Unsync all notes in the sync manager on your old device. 
2. Export all the sync-needed notes to the same paths of your synced notes on your new device.
