### ISSUE TITLE
把论文里面的笔记插入到better notes中时，会产生不必要的标签

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-better-notes#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 23H2
- Zotero Version: 7.0-beta77
- Plugin Version:1.1.4-beta.72

### Describe the bug

只要把论文里面的笔记插入到better notes里面，就会在该笔记下方产生一个标签，如下图：
![image](https://github.com/windingwind/zotero-better-notes/assets/57392772/5c31746f-5955-424a-8d69-249cb35246fb)
返回Zotero主界面后，标签下面就会显示这些标签了，能不能不显示这个呢？
![xuanxuan_20240516_173446](https://github.com/windingwind/zotero-better-notes/assets/57392772/9d31e132-2034-4913-b31b-a11eb9fb26a6)

### Debug Output

无

**Comment by oushiei120** [comment]
我也有一个类似的问题，同步到 obsidian的笔记中有 
<img width="801" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/86762134/d63860ce-898b-4571-9a8f-218d1cd54679">
这样的标签，

**Comment by oushiei120** [comment]
<img width="997" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/86762134/1edbcf9e-11e7-42ad-b523-9c26dbc02b98">
<img width="865" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/86762134/ce23ea14-660a-4938-8599-4885ba3d0765">
<img width="904" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/86762134/60389ae4-1433-452b-9ca0-a268b0a9ac1a">

这样不是很美观，可否只有留下(陈妍, 2018, p. 11)部分的链接？

**Comment by windingwind** [comment]
@oushiei120 不要在无关issue下回复不同的问题
