### ISSUE TITLE
It is not possible to create links into a Master Note.

### ISSUE THREAD

**Issue by DonnaCoxBaker** [windingwind/zotero-better-notes#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: Beta 7 .79
- Plugin Version:  1.1.4-beta.72

### Describe the bug

When I am in a note and attempt to send a link to a master note, I get a dialog that only contains the labels "Mention in" and "Link To" with the buttons "Cancel" and "OK." (See screenshot.) It has been several weeks since I used this, so I don't know when the problem began.

![Screenshot 2024-05-18 133209](https://github.com/windingwind/zotero-better-notes/assets/54809262/facc07ae-593c-441e-86cb-ebdd5c451257)

### Debug Output

none

### Anything else?

none

**Comment by windingwind** [comment]
Could you please provide a debug output contains the log during opening the `Link Creator`?

**Comment by windingwind** [comment]
Should be fixed by the latest beta
