### ISSUE TITLE
[Bug] 笔记的“在窗口中打开”功能失效，打开的窗口中没有笔记内容

### ISSUE THREAD

**Issue by jievvvvvia** [windingwind/zotero-better-notes#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 
- Zotero Version: 最新
- Plugin Version:最新
![image](https://github.com/windingwind/zotero-better-notes/assets/156058717/31ed712d-d9e7-4e62-baee-424675ef11b8)

### Describe the bug

![image](https://github.com/windingwind/zotero-better-notes/assets/156058717/1abe4443-5ea0-4354-883f-4d2762370dba)
![image](https://github.com/windingwind/zotero-better-notes/assets/156058717/43ea9049-04b2-4a34-b9a6-1ce54b26e0f6)

### Debug Output

[Debug Output_files.zip](https://github.com/windingwind/zotero-better-notes/files/15368108/Debug.Output_files.zip)
[Debug Output.zip](https://github.com/windingwind/zotero-better-notes/files/15368109/Debug.Output.zip)

**Comment by windingwind** [comment]
已修复

**Comment by jievvvvvia** [comment]
感谢博主！！

**Comment by jievvvvvia** [comment]
> 已修复

您好，我是个小白，修复之后我如何更新以实现功能呢，我看软件没有更新。谢谢

**Comment by windingwind** [comment]
如果自动更新未生效，重新从github下载对应版本安装包，覆盖安装

**Comment by jievvvvvia** [comment]
> 如果自动更新未生效，重新从github下载对应版本安装包，覆盖安装

博主您好，我更新之后发现了您对插件相关功能的更新，对此表示感谢！！不过，我发现，似乎您更新插件相关功能的策略是删除冗余的相关选项。对此，我表示理解和感谢。然而，一个关键问题在于，用户以单独窗口打开betternote的核心动机在于，利用其左侧标题导航窗格以实现边阅读文献边拖拽文献中的重要文段片段至betternote的相关标题下。但是，我发现，更新之后的betternote只能单独窗口打开，没有左侧标题导航窗格，这可能导致用户（如我）不得不在主界面使用可以带导航窗格的betternote，而以独立窗格显示单篇文献，或者以独立窗口显示betternote而不得不每次插入文本时费力寻找对应位置。换言之，更新之后连费力的简便操作也无法实现。因此，能否使betternote以单独窗口打开时仍存在左侧标题导航窗格（之前一直是可以的）。十分感谢。



![image](https://github.com/windingwind/zotero-better-notes/assets/156058717/3d4ff11a-4fef-4980-9495-6f2b2dbecc1d)

**Comment by windingwind** [comment]
更新插件后建议重启zotero
