### ISSUE TITLE
[Bug] 链接到主笔记的窗口空白，无法选择

### ISSUE THREAD

**Issue by nbrabbit** [windingwind/zotero-better-notes#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.79+95d5a5417 (64-bit)
- Plugin Version:1.1.4-beta.72
![微信截图_20240519202115](https://github.com/windingwind/zotero-better-notes/assets/25836410/9c4221d1-70f9-4e68-95a5-7ea9c2c70b88)

### Describe the bug

点击链接图标
![image](https://github.com/windingwind/zotero-better-notes/assets/25836410/a21ae598-0c4b-466b-a070-5326db07dd7b)
，显示空白，无法选择主笔记

### Debug Output

![Uploading 微信截图_20240519202115.png…]()

**Comment by windingwind** [comment]
已修复
