### ISSUE TITLE
右侧笔记格式设置下拉选项透明

### ISSUE THREAD

**Issue by yunjia2001** [windingwind/zotero-better-notes#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

OS: Windows 11 23H2
Zotero Version: 7.0.0-beta.80+9de70613a (64-bit)
Plugin Version: 1.1.4-beta.73

### Describe the bug

<img width="285" alt="Snipaste_2024-05-22_15-23-28" src="https://github.com/windingwind/zotero-better-notes/assets/119392749/3612951c-d054-4bf4-a254-f79c05c978e9">
<img width="286" alt="Snipaste_2024-05-22_15-24-23" src="https://github.com/windingwind/zotero-better-notes/assets/119392749/e282ce94-3b2a-4dd1-9954-202e8b71f3ec">

作者你好，在笔记右侧设置格式时，下拉选项透明，较为影响使用，能否改为不透明呢

### Debug Output

无

### Anything else?

无

**Comment by windingwind** [comment]
请禁用其他所有插件
