### ISSUE TITLE
[Bug] 笔记工作区打开单独窗口时右侧边栏变空白且无法调整

### ISSUE THREAD

**Issue by Exilioloz** [windingwind/zotero-better-notes#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: MacOS 14.3.1
- Zotero Version: 7.0.0-beta.80+9de70613a
- Plugin Version:1.1.4-beta.73

### Describe the bug

试图打开单独窗口笔记工作区编辑（下拉菜单+open as window）时，打开的窗口右侧边栏变灰色，原有内容无法显示且无法关闭边栏。关闭其他插件后，作为tab打开出现同样的情况。
<img width="478" alt="截屏2024-05-23 12 34 29" src="https://github.com/windingwind/zotero-better-notes/assets/164539896/534f6d3f-c0d4-438a-923f-975ac9a126b6">

### Debug Output

1716438940923	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this._details.render is not a function" {file: "chrome://betternotes/content/scripts/customElements.js" line: 2471}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{200abeae-d2bc-47e7-a0e5-64ebf7758d03} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this._details.render is not a function" {file: "chrome://betternotes/content/scripts/customElements.js" line: 2471}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{200abeae-d2bc-47e7-a0e5-64ebf7758d03} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this._details.render is not a function" {file: "chrome://betternotes/content/scripts/customElements.js" line: 2471}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{200abeae-d2bc-47e7-a0e5-64ebf7758d03} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this._details.render is not a function" {file: "chrome://betternotes/content/scripts/customElements.js" line: 2471}]

[JavaScript Error: "Security Error: Content at moz-nullprincipal:{200abeae-d2bc-47e7-a0e5-64ebf7758d03} may not load or link to chrome://betternotes/content/treeView.html."]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "TypeError: this._details.render is not a function" {file: "chrome://betternotes/content/scripts/customElements.js" line: 2471}]

appName => Zotero, version => 7.0.0-beta.80+9de70613a, os => macOS 14.3.1, locale => en-US, extensions => Better Notes for Zotero (1.1.4-beta.73, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.8.1.2, plugin), Widevine Content Decryption Module provided by Google Inc. (4.10.2710.0, plugin), Tara (0.0.6, extension, disabled), ZotFile (5.1.2, extension, disabled), Jasminum (1.0.0-14, extension, disabled), Translate for Zotero (1.1.0-beta.41, extension, disabled), Actions and Tags for Zotero (1.0.0-beta.39, extension, disabled), Awesome GPT (0.8.9, extension, disabled), Zotero Attanger (1.2.2, extension, disabled)

(3)(+0062815): Getting contents of /Users/exilioloz/Library/Application Support/Zotero/Profiles/9aq083t2.default/treePrefs.json

(3)(+0000004): Writing column prefs of length 17437 to file /Users/exilioloz/Library/Application Support/Zotero/Profiles/9aq083t2.default/treePrefs.json

(3)(+0011256): itemTree.render(). Displaying Item Tree

(4)(+0000014): Beginning DB transaction 210cgj9s

(3)(+0000001): Reloading tags box

(3)(+0000027): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(4)(+0000041): Committed DB transaction 210cgj9s

(3)(+0000012): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000007): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css succeeded with 200

(3)(+0000173): Notifier.trigger('add', 'tab', [tab-OE96qJ59], {"tab-OE96qJ59":{"itemID":31107,"type":"note"}}) called [observers: 7]

(3)(+0000008): Notifier.trigger('select', 'tab', [tab-OE96qJ59], {"tab-OE96qJ59":{"type":"note"}}) called [observers: 7]

(4)(+0000009): Registering notifier observer 'paneHeader_TY' for [item]

(4)(+0000003): Registering notifier observer 'itemBox_4E' for [item]

(4)(+0000004): Registering notifier observer 'abstractBox_oO' for [item]

(4)(+0000004): Registering notifier observer 'attachmentPreview_x9' for [item]

(4)(+0000000): Registering notifier observer 'attachmentsBox_Cg' for [item]

(4)(+0000002): Registering notifier observer 'notesBox_Qc' for [item]

(4)(+0000004): Registering notifier observer 'attachmentPreview_vt' for [item]

(4)(+0000003): Registering notifier observer 'tagsBox_NW' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_yv' for [item]

(4)(+0000000): Registering notifier observer 'noteEditor_BB' for [item,file]

(4)(+0000000): Registering notifier observer 'attachmentbox_iW' for [item]

(4)(+0000000): Registering notifier observer 'attachmentAnnotationsBox_sf' for [item]

(4)(+0000001): Registering notifier observer 'librariesCollectionsBox_7O' for [item]

(4)(+0000001): Registering notifier observer 'tagsBox_2z' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_P7' for [item]

(4)(+0000000): Registering notifier observer 'ItemDetails_vX' for [item,itempane,tab]

(3)(+0000000): Viewing item

(4)(+0000004): Registering notifier observer 'Fr' for [item]

(4)(+0000003): Registering notifier observer '7K' for [item]

(4)(+0000002): Registering notifier observer 'qd' for [item]

(3)(+0000001): Refreshing item box

(3)(+0000019): Setting mode to 'edit'

(3)(+0000001): Reloading tags box

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000017): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(3)(+0000009): HTTP GET chrome://zotero/skin/feedAbstract.css

(3)(+0000009): HTTP GET chrome://zotero/skin/feedAbstract.css succeeded with 200

(4)(+0000013): Registering notifier observer 'attachmentsBox_0u' for [item]

(4)(+0000006): Registering notifier observer 'tagsBox_UW' for [item-tag,setting] with priority 101

(4)(+0000000): Registering notifier observer 'relatedbox_5s' for [item]

(4)(+0000001): Registering notifier observer 'noteEditor_Ad' for [item,file]

(3)(+0000002): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000001): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000000): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000003): [Better Notes for Zotero] executeRelationWorker {"type":"rebuildLinkForNote","data":{"fromLibID":1,"fromKey":"FLIZ37FI","links":[]}} brM2OlXU

(3)(+0000011): [Better Notes for Zotero] executeRelationWorker return {"type":"rebuildLinkForNote","jobID":"brM2OlXU","result":{"oldOutboundLinks":[]}}

(3)(+0000000): Notifier.trigger('updateBNRelation', 'item', [31107], {}) called [observers: 64]

(3)(+0000001): Yielding for refresh promise

(3)(+0000002): itemTree.render(). Displaying Item Tree

(4)(+0000017): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000023): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(3)(+0000126): itemTree.render(). Displaying Item Tree

(3)(+0000040): BlockingObserver: Added observer

(3)(+0000107): BlockingObserver: Added observer

(2)(+0000006): Failed to load preview for attachment 1/HP93G5XP: Error: Reader is already initialized this.warn@chrome://zotero/content/xpcom/zotero.js:1258:71 _open@chrome://zotero/content/xpcom/reader.js:1381:14

(3)(+0000000): BlockingObserver: Removed observer

(1)(+0000004): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000001): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(1)(+0000000): Unknown relation predicate 'owl:sameAs'

(3)(+0000313): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000001): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000000): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000102): Reloading tags box

(3)(+0000006): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(3)(+0000034): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000002): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(1)(+0000001): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000004): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css succeeded with 200

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000043): BlockingObserver: Added observer

(3)(+0000249): Got MIME type application/pdf from extension 'pdf'

(3)(+0000224): [Better Notes for Zotero] {}

(3)(+0001119): [Better Notes for Zotero] {}

(3)(+0000001): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000001): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000000): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(3)(+0000003): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(4)(+0001372): Registering notifier observer 'QO' for all types

(4)(+0000164): Registering notifier observer 'attachmentsBox_t8' for [item]

(4)(+0000005): Registering notifier observer 'tagsBox_HX' for [item-tag,setting] with priority 101

(4)(+0000001): Registering notifier observer 'relatedbox_wc' for [item]

(4)(+0000000): Registering notifier observer 'noteEditor_CR' for [item,file]

(3)(+0000002): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000001): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000000): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000002): [Better Notes for Zotero] executeRelationWorker {"type":"rebuildLinkForNote","data":{"fromLibID":1,"fromKey":"FLIZ37FI","links":[]}} fa0EshHT

(3)(+0000003): [Better Notes for Zotero] executeRelationWorker return {"type":"rebuildLinkForNote","jobID":"fa0EshHT","result":{"oldOutboundLinks":[]}}

(3)(+0000001): Notifier.trigger('updateBNRelation', 'item', [31107], {}) called [observers: 68]

(3)(+0000000): Yielding for refresh promise

(3)(+0000001): itemTree.render(). Displaying Item Tree

(4)(+0000024): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000000): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [878, '']

(4)(+0000077): Registering notifier observer 'o3' for all types

(4)(+0000239): Registering notifier observer 'RM' for all types

(3)(+0000100): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000000): [Better Notes for Zotero] push blockquote <blockquote> ["blockquote"]

(3)(+0000000): [Better Notes for Zotero] pop blockquote </blockquote> []

(3)(+0000102): Reloading tags box

(3)(+0000008): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000000): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js

(3)(+0000042): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js succeeded with 200

(3)(+0000001): [Better Notes for Zotero] [Warning] Creating element script with no namespace specified. Found multiply namespace matches.

(3)(+0000002): Getting contents of jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(1)(+0000000): Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

(3)(+0000001): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element button with no namespace specified. Found multiply namespace matches.

(3)(+0000003): HTTP GET jar:file:///Users/exilioloz/Library/Application%20Support/Zotero/Profiles/9aq083t2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/styles/editor.css succeeded with 200

(3)(+0000000): [Better Notes for Zotero] [Warning] Creating element style with no namespace specified. Found multiply namespace matches.

(3)(+0000314): [Better Notes for Zotero] {}

**Comment by windingwind** [comment]
谢谢反馈，已修复，请升级插件
