### ISSUE TITLE
[Feature] 选中论文的几行文字后点击“添加笔记”，在betternote中发现添加的笔记在原文换行的地方多出来一个空格，能否自动检测并消除空格？

### ISSUE THREAD

**Issue by xiaoyu200009** [windingwind/zotero-better-notes#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10
- Zotero Version: 6.0.36
- Plugin Version: 1.0.4

**Comment by windingwind** [comment]
Zotero自带功能，与插件无关
