### ISSUE TITLE
[Feature] 更强的markdown语法支持[表格合并，markdown源码显示]

### ISSUE THREAD

**Issue by Grozta** [windingwind/zotero-better-notes#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0-dev.31+24ca4e44f 
- Plugin Version: [1.1.4-beta.76]

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
当前的笔记对markdown的支持不多，如果能够像Typora一样对markdown有着比较丰富的特性支持就好了
**Why do you need this feature?**
想在笔记中记录实验，需要更强的表格表达，最好能够解析html格式的文本，标题可以支持产过6级（越多越好）
bn中能够对笔记的标题生成树状的思维导图，实验的进展也都是相互关联和循序渐进的，标题可以是对实验的简洁描述，而实验的表格如果可以合并的话，就可以制出合理的实验记录表格。

### Describe the solution you'd like

**The solution you'd like**

**Alternatives you've considered**

**Comment by windingwind** [comment]
zotero笔记并非markdown，而是支持markdown语法的富文本。

对表格的功能扩展可考虑，感谢建议

**Comment by glwhappen** [comment]
复制的markdown文本，粘贴进去文本框的时候能自动变成富文本吗，现在看到的还是markdown的内容
