### ISSUE TITLE
[Bug] 插入的表格似乎无法选择行列数目，且插入的表格似乎无法删除，无法点击该行最前边的那个标志选中该表格进而删除

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-better-notes#99]
目前发现的唯一的方法是Ctrl+A然后把整个note的内容删除

**Comment by windingwind** [comment]
插入表格可右键操作增加删除行列或表

**Comment by ghweili** [comment]
看到了，可用，谢谢。 不过建议可以在insert table 或者右键编辑table时添加一个可以输入行列数目的选项，如果行列数目与默认数值差比较大时可有用。

**Comment by windingwind** [comment]
已计划，谢谢建议

**Comment by windingwind** [comment]
@ghweili 
新版本已支持插入表格时设定行列数，入口为菜单栏=>编辑=>插入模板=>Table

**Comment by Hansomeboy** [comment]
表格用着用着会卡住，不能编辑（表格内鼠标点击不动，无法）
![image](https://user-images.githubusercontent.com/52063730/185734348-14465b89-fb23-4b16-8e27-313573e381a0.png)
而且卡住之后无法删除
请问这种bug怎么解决
![image](https://user-images.githubusercontent.com/52063730/185734364-b1a1dff2-1f84-4774-8b0c-c9db766b6da2.png)

**Comment by windingwind** [comment]
@Hansomeboy 插件是否是最新版？另外可否具体描述下问题，是否可以稳定复现呢？
我不清楚具体是什么缘故，为笔记界面加一个刷新功能是否会有帮助？

**Comment by Hansomeboy** [comment]
你好，问题就是使用表格的时候，再mainnote里面表格使用会很顺畅，但在pdf右侧自己的笔记中表格的使用存在一段时间后会无法编辑的情况，就是表格内容鼠标点击不动（点不出‘工’字形的鼠标输入符号），无法在里面输入东西，表格用右键删除表格也删不掉，其他都可以正常编辑，就表格会出现突然不能用的情况，不知道您能否理解我的意思，楼主浙大的吗？好像在98上看到过winding

**Comment by Hansomeboy** [comment]
![image](https://user-images.githubusercontent.com/52063730/185779809-7dc33d9f-edf7-4fd3-b1a9-5c7aef109c7a.png)

**Comment by windingwind** [comment]
@Hansomeboy 是的。我感觉这可能是Zo的bug，我之后加个刷新按钮吧，遇到卡住就刷新下应该能解决。
卡住以后，用鼠标右键还是能在表格里移动光标的应该

**Comment by windingwind** [comment]
@Hansomeboy refresh the editor here:
![image](https://user-images.githubusercontent.com/33902321/188257809-c9a6ee91-4ffa-4efe-90fb-7e67a1aead43.png)

**Comment by Hansomeboy** [comment]
thank you
请问显示不兼容无法下载是要更新zotero吗，但我看官网好像没有新版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windingwind/zotero-better-notes] [Bug] 插入的表格似乎无法选择行列数目，且插入的表格似乎无法删除，无法点击该行最前边的那个标志选中该表格进而删除 (Issue #99)




 
@Hansomeboy refresh the editor here:

**Comment by Hansomeboy** [comment]
好的，辛苦了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-better-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午3:31
***@***.***&gt;;
抄送:&nbsp;"!@***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-better-notes] [Bug] 插入的表格似乎无法选择行列数目，且插入的表格似乎无法删除，无法点击该行最前边的那个标志选中该表格进而删除 (Issue #99)





 
@Hansomeboy 是的。我感觉这可能是Zo的bug，我之后加个刷新按钮吧，遇到卡住就刷新下应该能解决。
 卡住以后，用鼠标右键还是能在表格里移动光标的应该

**Comment by wyd1123** [comment]
我试了Ctrl+X然后再Ctrl+V，可以编辑了

**Comment by wyd1123** [comment]
> 我试了Ctrl+X然后再Ctrl+V，可以编辑了

得建立新的笔记，而且下次开启时又得重新来一次
