### ISSUE TITLE
无法新建笔记，无法链接文章中的笔记到note中，无工作区笔记

### ISSUE THREAD

**Issue by npj06** [windingwind/zotero-better-notes#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: 14.5
- Zotero Version: 7.0.0-beta
- Plugin Version:1.1.4-beta.77

### Describe the bug

如题目所示，已经不知道该怎么使用了，不知道是bug问题还是整个插件的设计做了大的更改，感谢解答和帮助
<img width="510" alt="截屏2024-06-03 11 05 40" src="https://github.com/windingwind/zotero-better-notes/assets/114918453/4a3abd11-e4f7-45fd-a7ac-5568d50c8acd">
<img width="1365" alt="截屏2024-06-03 11 11 43" src="https://github.com/windingwind/zotero-better-notes/assets/114918453/32c6265a-72c4-4be0-8b36-d47054e8144f">
<img width="254" alt="截屏2024-06-03 11 12 10" src="https://github.com/windingwind/zotero-better-notes/assets/114918453/c409761e-daf2-4367-b98b-fe11b425e376">
<img width="259" alt="截屏2024-06-03 11 12 27" src="https://github.com/windingwind/zotero-better-notes/assets/114918453/0fedc098-1cc0-4c6e-bd1c-a9ad7d21bb80">
<img width="797" alt="截屏2024-06-03 11 13 12" src="https://github.com/windingwind/zotero-better-notes/assets/114918453/b2f31fe9-8867-4134-b23f-79d90a7185c0">

### Debug Output

没有debug可以展示，把模板新建到工作区笔记，不知道是否成功，因为根本找不到工作区笔记去了哪儿....

**Comment by windingwind** [comment]
1. 笔记模板报错请向笔记模板作者咨询，与插件无关
2. “工作区”概念已在最新版本中移除，因为所有笔记都默认可以成为“工作区”，既无需额外设置，也无需特殊操作，可对任意笔记执行原本“工作区”的操作。所有功能均正常。如果对某个特定功能如何使用有疑惑，欢迎在discussion中讨论

**Comment by windingwind** [comment]
关于链接精灵窗口的文本缺失已修复。由于本issue不够具体，无法进一步回复，此处关闭

**Comment by wangjun-kai** [comment]
我也遇到这种情况了请问下你怎么解决
